### PR TITLE
`partition_by_hash()`: support index

### PR DESCRIPTION
**Pull request by madsbk**
AFAICT, `DataFrame.partition_by_hash()` doesn't handle index correctly. 

When `keep_index=True`, we now include the index in the call to `libcudf.hash.hash_partition()`

## Checklist
- [x] I am familiar with the [Contributing Guidelines](https://github.com/rapidsai/cudf/blob/HEAD/CONTRIBUTING.md).
- [x] New or existing tests cover these changes.
- [x] The documentation is up to date with these changes.

### CODE REVIEW

**Review by wence- — APPROVED** [review]
Looks like correct behaviour, thanks.

**Comment by madsbk** [comment]
CI fails:

**Comment by wence-** [comment]
> What is going on?

cudf tests have `xfail_strict = true` which means that any test marked with xfail that _passes_ turns into a failure in the test suite. The question is, why did code that fixed that bug without removing the xfail get into trunk?

**Pull request merged**
