### PR TITLE
Split out non-device code from fixed_point_tests.cu

### PR DESCRIPTION
**Pull request by davidwendt**
This change moves the non-device code from `cudf/tests/fixed_point/fixed_point_tests.cu` into a new `cudf/tests/fixed_point/fixed_point_tests.cpp` file. This helped speed up the compile time in libcudf debug (and release) build.

### CODE REVIEW

**Comment by davidwendt** [comment]
Working with @codereport to figure out what to do with the overflow test code
https://github.com/rapidsai/cudf/pull/8238/files#diff-319c7ef0db23e1effc306d7b25a64205eb19e804824b94d462bc3f5924b5f403R76-R82

**Comment by codereport** [comment]
```
[----------] 7 tests from FixedPointTest
[ RUN      ] FixedPointTest.OverflowDecimal32
[       OK ] FixedPointTest.OverflowDecimal32 (1568429 ms)
[ RUN      ] FixedPointTest.OverflowDecimal64
[       OK ] FixedPointTest.OverflowDecimal64 (1580168 ms)
```
So it actually does work, but it takes ~1 hr ro run. So maybe we should just turn them off?

**Comment by davidwendt** [comment]
> 
> So it actually does work, but it takes ~1 hr ro run. So maybe we should just turn them off?

I think the choices are:

- I can leave them in and _disable_ them so they compile but never execute (along with a comment). This keeps the code there in case someone really wants to enable it in the future.
- I could wrap them with the `#ifdef __CUDACC_DEBUG__` or `#ifndef NDEBUG` with a comment. This would mean if someone runs it in debug they will think it is hung up unless they go read the comment and either avoid the test or disable it then.
- Of we could remove the completely since they don't work in Release and are unusable in Debug.

I vote for the first one. I assume this was usable at some point when it was created and so may become useful again with a partial debug build perhaps.

**Review by robertmaynard — APPROVED** [review]
CMake changes approved

**Review by codereport — APPROVED** [review]
lgtm :+1: thanks for doing this @davidwendt

**Comment by davidwendt** [comment]
@gpucibot merge

**Pull request merged**
