### PR TITLE
Upgrade to Arrow 17

### PR DESCRIPTION
**Pull request by galipremsagar**
## Description
This PR upgrades to arrow-17 in cudf.

## Checklist
- [x] I am familiar with the [Contributing Guidelines](https://github.com/rapidsai/cudf/blob/HEAD/CONTRIBUTING.md).
- [x] New or existing tests cover these changes.
- [x] The documentation is up to date with these changes.

### CODE REVIEW

**Review by ttnghia — APPROVED** [review]

**Review by vyasr — CHANGES_REQUESTED** [review]
I don't think we want to upgrade this, certainly not so quickly. We know that moving our Arrow dependency too quickly can cause pain for some of our users (CC @beckernick), and also we're targeting removing the libarrow dependency in 24.10 anyway.

**Comment by bdice** [comment]
Thanks @vyasr - I had the same concern. Let's try to reduce our Arrow dependencies first, and we can upgrade this later in the release cycle if still needed.

**Comment by galipremsagar** [comment]
> I don't think we want to upgrade this, certainly not so quickly. We know that moving our Arrow dependency too quickly can cause pain for some of our users (CC @beckernick), and also we're targeting removing the libarrow dependency in 24.10 anyway.

Sounds good 👍

**Comment by vyasr** [comment]
@galipremsagar once #16640 merges, we should replace this PR with one that simply relaxes the pyarrow constraint. Would you be able to take point on testing the versions that we support? I expect that anything after pyarrow 13 should work for us (we need pyarrow 13 for https://github.com/apache/arrow/pull/36162). 

@seberg when we add the earliest dependency testing to cudf (the cudf version of https://github.com/rapidsai/rmm/pull/1613) can we also ensure that the appropriate pyarrow (and pandas) versions are being tested there? Thank you!

**Comment by galipremsagar** [comment]
> @galipremsagar once #16640 merges, we should replace this PR with one that simply relaxes the pyarrow constraint. Would you be able to take point on testing the versions that we support? I expect that anything after pyarrow 13 should work for us (we need pyarrow 13 for [apache/arrow#36162](https://github.com/apache/arrow/pull/36162)).
> 
> @seberg when we add the earliest dependency testing to cudf (the cudf version of [rapidsai/rmm#1613](https://github.com/rapidsai/rmm/pull/1613)) can we also ensure that the appropriate pyarrow (and pandas) versions are being tested there? Thank you!

Sure 👍

**Comment by seberg** [comment]
> hen we add the earliest dependency testing to cudf (the cudf version of https://github.com/rapidsai/rmm/pull/1613) can we also ensure that the appropriate pyarrow (and pandas) versions are being tested there?

They already are part of gh-16570 (although you can double check the versions, and I guess this would modify them).

**Comment by vyasr** [comment]
Oh awesome I thought there was a cudf PR for this but couldn't find it. Thanks for pointing it out! Yes, we'd just want to update the versions there I think.

**Comment by jakirkham** [comment]
Right this is the cuDF PR: https://github.com/rapidsai/cudf/pull/16570

Think Matthew is going to work on adding some skips and xfails as appropriate: https://github.com/rapidsai/cudf/pull/16570#discussion_r1725956815

Guessing once that is done it can be merged

**Comment by vyasr** [comment]
Replaced by #16681.

**Pull request closed without merging**
