### PR TITLE
Add Doxygen CI check

### PR DESCRIPTION
**Pull request by karthikeyann**
closes https://github.com/rapidsai/cudf/issues/9373
Add doxygen CI check to check warnings for missing documentation
Depends on PR https://github.com/rapidsai/cudf/pull/11056

### CODE REVIEW

**Comment by ttnghia** [comment]
Hah I was just about to create an issue for this :smile:

**Review by codereport — APPROVED** [review]
lgtm

**Review by ttnghia — APPROVED** [review]
I'm not sure if we still need the other sub PR (https://github.com/rapidsai/cudf/pull/11056).

**Comment by karthikeyann** [comment]
@gpucibot merge

**Review by sevagh — APPROVED** [review]

**Pull request merged**
