### PR TITLE
[WIP] Add rolling functions and ewm functions to Series

### PR DESCRIPTION
**Pull request by yidong72**
I added the rolling function and ewm functions to the Series.

### CODE REVIEW

**Comment by GPUtester** [comment]
Can one of the admins verify this patch?

**Comment by GPUtester** [comment]
Can one of the admins verify this patch?

**Comment by harrism** [comment]
add to whitelist

**Comment by kkraus14** [comment]
Given this has gone stale and we have a libcudf implementation for rolling windows I'm going to close this.

**Pull request closed without merging**
