### PR TITLE
[REVIEW] Smorgasbord of utility code changes, additions and moves

### LINKED ISSUE #1367: [FEA] Need a general, testing-framework-aware column comparison for testing
Most libcudf tests need to compare columns: Expected vs Actual. Some do this using the `gdf_equal_columns` template in `cpp/tests/utilities/cudf_test_utils.cuh`. Some tests have idiosyncratic functions which copy data from the device and make it accessible for comparison in std::vector's; and some, especially more recently, use the `cudf::test::column_wrapper` abstraction, with its `operator==`. While column_wrapper is far from perfect (see #1178 ), it is at least taking many steps in the direction of a uniform facility for handling columns in tests and should be in general use in relevant tests.

Now, the two factored-out and general-case comparators - `gdf_equal_columns` and `column_wrapper::operator==`, are oblivious to gtest, our testing framework. They merely return a boolean value. On the other hand, the custom comparator code in various tests _is_ mostly testing-framework-aware, and uses `EXPECT_` and/or `ASSERT_` macros to provide more specific indications of errors or mismatches. Of course, not all tests using custom comparison code give indication of all possible cases of mismatch, and may ignore or bunch together some of them.

There should be a common facility for comparing columns - preferably both `cudf::test::column_wrapper<E>`'s and `gdf_column`'s - which all tests can use and which will be as specific as is reasonable in reporting errors.

### LINKED ISSUE #1368: [BUG] set_null_count() doesn't check for nullptr's enough
In `utilities/cudf_utilities.h` we have the `set_null_count()`. It:

1. Doesn't make sure the `col` pointer is non-null before dereferencing it.
2. Calls `gdf_count_nonzero_mask()` even if `col->valid` is `nullptr`

As for (1.) - we should at least add an `assert()` there.
As for (2.) - **edit:** this is fine, but as @jrhemstad suggests, the Doxygen for gdf_count_nonzero_mask() should be fixed to indicate it's ok to call it with a null pointer like this.

### LINKED ISSUE #1371: [BUG] allocation size calculations etc. may overflow
In several places in our code, and perhaps most importantly in the functions we use to calculate sizes for allocations, we do something like the following:
```
z = (x+y-1)/y;
```
or
```
z = ((x+y-1)/y)*y;
```
the former is supposed to a division of x by y, rounding up, and the latter - just rounding up to a multiple of y. These calculations run the risk of **overflow** - and this is especially a problem considering the small type we use for allocation sizes - `gdf_size_type` is effectively a 32-bit integer. It is not inconceivable that someone will try to use an `x` value that's close to 2^31, and this value will just overflow.

We need safe versions of integer round-up and division-rounding-up - and to have allocation functions use them (e.g. in `cpp/src/bitmask/legacy_bitmask.cpp`). They should also be used when forming CUDA kernel launch grids; perhaps a bit of code facilitating that, at least in simple cases, could be added.

### LINKED ISSUE #1372: [FEA] Use a RAII wrapper for streams in outer API function implementations
Quite a few implementations of our cuDF API functions have the following pattern in their code:
```
gdf_error gdf_foo(args...) 
{
    // some setup
    cudaStream_t stream;
    cudaStreamCreate(&stream);
    // do stuff with the stream
    if (error) {
        // some teardown
        cudaStreamSynchronize(stream);
        cudaStreamDestroy(stream);
        return GDF_SOME_ERROR;
    }          
    // do more stuff
    cudaStreamSynchronize(stream);
    cudaStreamDestroy(stream);
}
```
... and that's assuming errors are actually checked and the stream properly destroyed...

instead, we should have a RAII gadget that will simplify this to merely:
```
gdf_error gdf_foo(args...) 
{
    // some setup
    cudf::util::scoped_stream stream; // will throw on failure to create
    // do stuff with the stream
    if (error) {
        // some teardown
        return GDF_SOME_ERROR;
    }          
    // do more stuff
}
```
3 less lines - but absolutely no stream handle leaks!

### LINKED ISSUE #1387: [FEA] Some (trivial) utility functions for gdf_column's
There are some routine, mostly-trivial tasks we occasionally, or often, need to perform on `gdf_column`'s, the code for which is currently at best repeated and at worst partially-repeated in different places in libcudf. Also, when we use this code, we don't quite say what it is that we're doing:

* Ensuring a column is valid (e.g. not having more nulls than elements and a bunch of other checks)
* Determining whether two columns have matching types (which includes the nullability check) 
* Checking whether a column is nullable or not not. Right now we use the "implementation" of this check, i.e. check whether `some_column->valid == nullptr`, when we could say `is_nullable(some_column)`
* Determining whether two columns have compatible extra_type_info (which sometimes means doing nothing, depending on the dtype)

Let's have these utility functions implemented.

### PR DESCRIPTION
**Pull request by eyalroz**
This PR contains multiple (minor) additions, changes, fixes and some file moves/renames. Below is a brief description of each of them, with links to specific issues they address.

* Added: Functions for column comparison in testing code, which use GTest EXPECT()'s for various phases of the comparison, indicating errors while stopping the comparison only when it is irrelevant to continue; one function for `column_wrapper<E>` and another taking no structure, but rather the fields of a `gdf_column`. (Fixes #1367)
* Added: Utility code for working with `gdf_column`'s: A uniform, comprehensive validation function for columns and a check for type compatibility including extra type info when necessary. (Fixes #1387)
* Added: non-cuDF-API, but cuDF-API-like, functionality for filling a `gdf_column` with a single value. It takes a CUDA stream, and can thus be used within implementations of existing API functions (or trivially wrapped by a proper cuDF API function). Includes separate code for setting the validity indicators to a uniform value. (Regards #1075 but doesn't quite fix it)
* Added: A `GDF_TRY()` macro - similar to `GDF_REQUIRE()`, but for use with values of type `gdf_error` rather than booleans (half of a resolution of #1369).
* Added: `ASSERT_CUDF_SUCCEEDED()` in testing code - ensuring that a call to a cuDF API function doesn't throw and that it returns `GDF_SUCCESS`, with a concise syntax (half of a resolution of #1369).
* Added: Integer arithmetic utilities for safe division and rounding, put to use in `legacy_bitmask.cpp` for determining allocation sizes. (Fixes #1371)
* Added: A RAII gadget for holding CUDA streams in cuDF API function outer implementations, which ensures they're destroyed on return. (Resolves #1372)
* Added: A function for easy generation of 1-dimension CUDA launch configurations (using the safe rounding integer utilitiy code). (Regards #1371)
* Beefed up `set_null_count()` function with more null checks (Fixes #1368)
* Improved bit-manipulation functionality in `utilities/bit_util.cuh` (part of the resolution of #1373)
* Harmonized `bit_mask.h` with `utilities/bit_util.cuh` (part of the resolution of #1373)
* Better separation of the `BitMask` class from code in `bit_mask.h` independent of the class ( part of the resolution of #1373)
*  Moved: The file `utilities/cuda_utils.cu` was not holding utility code used by our implementation, but rather an implementation of cuDF API functions. Placed it in its own directory, outside `utilities/` and renamed it according to the functionality it exposes.

Notes:

* These changes originate in code I've written/been writing for a few API function implementations - but have turned out not to be particularly related to them; so I've spun them off.
* No device-side code changes or additions.
* These changes do not affect the functionality of cuDF in any way (except in catching corner cases of overflows in allocation).
* The code is actually ready for review, it's just the descriptions in this PR that are lacking.
* Some of the code added in this PR can or should be used in most/all cuDF API functions: the RAII stream gadget, and the column validation function. For now it is _not_ used anywhere.

### CODE REVIEW

**Comment by eyalroz** [comment]
Not sure what to put in the changelong yet.

**Comment by harrism** [comment]
Hi @eyalroz, can you please split this into multiple PRs? It will be much easier to merge small, self-contained changes. PRs that cover disparate functionality are difficult to review and take a lot of time. Simple PRs that fix individual problems are easy and quick to review. It also helps us prioritize what issues/PRs go into which releases. For the purposes of prioritization and scheduling we also prefer that you open up issues for discussion first.

**Comment by eyalroz** [comment]
@harrism : I've actually opened up issues for everything here except for a file move. I can do separate PRs, but - how about I do that when your or other reviewers give me a general go-ahead on the relevant issue pages?

**Comment by jrhemstad** [comment]
> @harrism : I've actually opened up issues for everything here except for a file move. I can do separate PRs, but - how about I do that when your or other reviewers give me a general go-ahead on the relevant issue pages?

I went through your issues and agree addressed each of them. I agreed with almost all of your changes. However, I do agree with @harrism that it will be much easier to review if your break the PR into pieces. Ideally one-to-one with issues to PRs.

**Comment by eyalroz** [comment]
@jrhemstad : Ok, I'll put in some elbow grease and create separate PRs. Will close this one as I add those.

**Comment by harrism** [comment]
Thanks, @eyalroz .

**Comment by eyalroz** [comment]
Almost all changes here are now in separate PRs (and issue #1411 ).

**Pull request closed without merging**
