### PR TITLE
[REVIEW] Revert arrow to 0.15.0 temporarily to unblock downstream projects CI

### PR DESCRIPTION
**Pull request by dantegd**
PR reverts `arrow-cpp` and `pyarrow` to 0.15.0 to avoid a conflict with conda-forge that is causing the conda solver to hang in cuML and cuGraph CI.

### CODE REVIEW

**Comment by mike-wendt** [comment]
Will update the CI containers to roll back as well

**Comment by mike-wendt** [comment]
@kkraus14 Didn't expect there to be a merge to cause conflicts. Given what the merge is from #3317 are we ok to resolve conflicts and merge this or are we going to need to retest?

**Comment by kkraus14** [comment]
> @kkraus14 Didn't expect there to be a merge to cause conflicts. Given what the merge is from #3317 are we ok to resolve conflicts and merge this or are we going to need to retest?

As long as you're okay with it once this reports green I'm totally fine with resolving conflicts and admin merging.

**Comment by mike-wendt** [comment]
> > @kkraus14 Didn't expect there to be a merge to cause conflicts. Given what the merge is from #3317 are we ok to resolve conflicts and merge this or are we going to need to retest?
> 
> As long as you're okay with it once this reports green I'm totally fine with resolving conflicts and admin merging.

Yeah at this point I don't want to wait another cycle. I have stuff in progress to shorten all of this,  but the firehouse has been more busy than usual to get the new fire truck built 😉

**Pull request merged**
