### PR TITLE
Update README and CONTRIBUTING for 0.19

### PR DESCRIPTION
**Pull request by robertmaynard**

### CODE REVIEW

**Comment by robertmaynard** [comment]
@harrism  This also address https://github.com/rapidsai/cudf/issues/7695 for 0.19

**Comment by robertmaynard** [comment]
rerun tests

**Review by jrhemstad — APPROVED** [review]

**Comment by jrhemstad** [comment]
@gpucibot

**Comment by jrhemstad** [comment]
@gpucibot merge

**Pull request merged**
