### PR TITLE
ListColumn `__setitem__`

### PR DESCRIPTION
**Pull request by brandon-b-miller**
Closes https://github.com/rapidsai/cudf/issues/8553
based on https://github.com/rapidsai/cudf/pull/8459

### CODE REVIEW

**Review by shwina — APPROVED** [review]
LGTM!

**Comment by galipremsagar** [comment]
@brandon-b-miller Looks like there are some pytest failures related to this PR, could you take a look at it when you get time?

**Review by galipremsagar — APPROVED** [review]

**Comment by brandon-b-miller** [comment]
rerun tests

**Comment by brandon-b-miller** [comment]
rerun tests

**Comment by galipremsagar** [comment]
rerun tests

**Comment by brandon-b-miller** [comment]
@gpucibot merge

**Pull request merged**
