### PR TITLE
Fix size passed to column constructors in _with_type_metadata

### PR DESCRIPTION
**Pull request by shwina**

### CODE REVIEW

**Review by charlesbluca — COMMENTED** [review]
Thanks @shwina 😄 would we also need to pass `size` for the struct column's `_with_type_metadata` constructor call?

https://github.com/rapidsai/cudf/blob/2bbeac9bb73245373a4630b8749eb5f3636a3449/python/cudf/cudf/core/column/struct.py#L118-L128

**Review by charlesbluca — APPROVED** [review]

**Comment by shwina** [comment]
rerun tests

**Review by marlenezw — APPROVED** [review]
This looks good to me Ashwin  😄

**Comment by shwina** [comment]
rerun tests

**Comment by shwina** [comment]
@gpucibot merge

**Pull request merged**
