### PR TITLE
[REVIEW] Add Java bindings for is_timestamp [skip ci]

### PR DESCRIPTION
**Pull request by andygrove**
This PR simply adds Java bindings for the `is_timestamp` method, along with a unit test.

### CODE REVIEW

**Comment by GPUtester** [comment]
Please update the changelog in order to start CI tests.

View the gpuCI docs [here](https://docs.rapids.ai/gpuci#open-pr-or-update-pr).

**Review by kuhushukla — COMMENTED** [review]
Missing change log entry . Lgtm otherwise.

**Review by kuhushukla — COMMENTED** [review]
Do you think checking with null input in the java test might be useful too?

**Comment by andygrove** [comment]
Thanks @kuhushukla this is ready for review now.

**Review by kuhushukla — APPROVED** [review]
Looks great!

**Review by jlowe — APPROVED** [review]

**Comment by jlowe** [comment]
rerun tests

**Pull request merged**
