### PR TITLE
Update ORC statistics API to use C++17 standard library 

### PR DESCRIPTION
**Pull request by vuule**
Uses `std::optional` instead of `std::unique_ptr` for optional ORC statistics fields, and `std::variant` instead of the manually implemented type erasure. 
Removes a lot of code that simulated `std::optional` and `std::variant` when it wasn't available.

### CODE REVIEW

**Comment by vuule** [comment]
Breaking because it modifies the type that `read_parsed_orc_statistics` returns.

**Comment by vuule** [comment]
Rerun tests

**Review by hyperbolic2346 — COMMENTED** [review]
I really like how so much of this melted away.

**Comment by vuule** [comment]
> I really like how so much of this melted away.

Yeah, I wrote so much code to approximate `std::variant` and `std::optional` functionality. So glad to be able to remove it :)

**Review by trxcllnt — APPROVED** [review]
:+1:

**Review by nvdbaranec — APPROVED** [review]
Nice work.

**Comment by vuule** [comment]
rerun tests

**Comment by vuule** [comment]
@gpucibot merge

**Pull request merged**
