### PR TITLE
[REVIEW] Make java Column Builder row agnostic [skip ci]

### PR DESCRIPTION
**Pull request by kuhushukla**
Bug fix that allows `ColumnBuilder`s at top level for lists and structs and other types to not care about the rows up front but figure it out during append calls. This was half way done with child builders but not at the top level.

### CODE REVIEW

**Comment by GPUtester** [comment]
Please update the changelog in order to start CI tests.

View the gpuCI docs [here](https://docs.rapids.ai/gpuci#open-pr-or-update-pr).

**Review by revans2 — APPROVED** [review]

**Comment by revans2** [comment]
looks good need to upmerge

**Comment by kuhushukla** [comment]
Wow, things are moving fast in cudf town, I had upmerged today earlier! Will do now.

**Review by mythrocks — APPROVED** [review]

**Comment by kuhushukla** [comment]
Thanks @revans2 , @mythrocks , merging now.

**Comment by mythrocks** [comment]
> Wow, things are moving fast in cudf town

All but my patches. :D

**Pull request merged**
