### PR TITLE
Update jni version to 22.10.0-SNAPSHOT

### PR DESCRIPTION
**Pull request by pxLi**
## Description
Update JNI version to 22.10.0-SNAPSHOT

jni cmake change has been covered in https://github.com/rapidsai/cudf/commit/df248086e79dc4f9cda5a527e862f4481be8ea90#diff-85b071fcb8436e7b5eedefcb44bd66949e9d8062d160f7317e19fc50ace7c887

## Checklist
- [X] I am familiar with the [Contributing Guidelines](https://github.com/rapidsai/cudf/blob/HEAD/CONTRIBUTING.md).
- [X] New or existing tests cover these changes.
- [X] The documentation is up to date with these changes.

### CODE REVIEW

**Comment by pxLi** [comment]
I will re-trigger the build when the CI of 22.10 is ready

**Review by jlowe — APPROVED** [review]

**Comment by ttnghia** [comment]
Rerun tests.

**Comment by ttnghia** [comment]
Rerun tests.

**Comment by ttnghia** [comment]
Maybe this needs some @rapidsai/ops-codeowners ok to test?

**Comment by jlowe** [comment]
rerun tests

**Comment by ttnghia** [comment]
Rerun tests.

**Comment by pxLi** [comment]
> Maybe this needs some @rapidsai/ops-codeowners ok to test?

2210 CI images were not ready yet. Let me try re-trigger

```
Error response from daemon: manifest for gpuci/rapidsai-driver:22.10-cuda11.5-devel-centos7-py3.8 not found: manifest unknown: manifest unknown

FATAL: Could not pull image: gpuci/rapidsai-driver:22.10-cuda11.5-devel-centos7-py3.8

java.io.IOException: Could not pull image: gpuci/rapidsai-driver:22.10-cuda11.5-devel-centos7-py3.8
```

**Comment by pxLi** [comment]
rerun tests

**Comment by pxLi** [comment]
all CI would fail unrelated tests right now.
```
13:32:10 [gw7] [ 99%] FAILED tests/test_s3.py::test_read_csv[1024] 
13:37:12 tests/test_s3.py::test_read_csv_arrow_nativefile 
13:37:12 [gw7] [ 99%] FAILED tests/test_s3.py::test_read_csv_arrow_nativefile 
13:42:15 tests/test_s3.py::test_read_csv_byte_range[True-32] 
13:42:15 [gw7] [ 99%] FAILED tests/test_s3.py::test_read_csv_byte_range[True-32] 
13:47:17 tests/test_s3.py::test_read_csv_byte_range[True-1024] 
13:47:17 [gw7] [ 99%] FAILED tests/test_s3.py::test_read_csv_byte_range[True-1024] 
13:52:20 tests/test_s3.py::test_read_csv_byte_range[False-32] 
13:52:20 [gw7] [ 99%] FAILED tests/test_s3.py::test_read_csv_byte_range[False-32] 
13:57:23 tests/test_s3.py::test_read_csv_byte_range[False-1024] 
13:57:23 [gw7] [ 99%] FAILED tests/test_s3.py::test_read_csv_byte_range[False-1024] 
14:02:27 tests/test_s3.py::test_write_csv[None] 
14:02:27 [gw7] [ 99%] FAILED tests/test_s3.py::test_write_csv[None] 
14:07:30 tests/test_s3.py::test_write_csv[3] 
14:07:30 [gw7] [ 99%] FAILED tests/test_s3.py::test_write_csv[3] 
14:12:34 tests/test_s3.py::test_read_parquet[True-None-None-32] 
14:12:34 [gw7] [ 99%] FAILED tests/test_s3.py::test_read_parquet[True-None-None-32] 
14:17:38 tests/test_s3.py::test_read_parquet[True-None-None-1024] 
14:17:38 [gw7] [ 99%] FAILED tests/test_s3.py::test_read_parquet[True-None-None-1024] 
```

I will retrigger when the pytest CI gets fix

**Comment by pxLi** [comment]
rerun tests

**Comment by pxLi** [comment]
rerun tests

**Comment by pxLi** [comment]
@gpucibot merge

**Pull request merged**
