### PR TITLE
Add decimal column handling in copy_type_metadata

### PR DESCRIPTION
**Pull request by shwina**
* All decimal columns returned by libcudf have a precision of 18 (`Decimal64Dtype.MAX_PRECISION`). The `copy_type_metadata` method is extended to copy the precision from the input column to the result as often we want the returned column to have the same precision as the input column.

* In adding a test for this, I realized that the `assert_eq` utility is broken: it doesn't correctly check for dtype equality when the dtype is a cudf-specific type. Tacked on a fix.

### CODE REVIEW

**Comment by shwina** [comment]
Will do!

**Comment by shwina** [comment]
rerun tests

**Review by isVoid — APPROVED** [review]
lgtm!

**Review by galipremsagar — APPROVED** [review]

**Review by kkraus14 — APPROVED** [review]

**Comment by kkraus14** [comment]
rerun tests

**Comment by kkraus14** [comment]
@gpucibot merge

**Pull request merged**
