### PR TITLE
[REVIEW] Add coverage for `skiprows` and `num_rows` in parquet reader fuzz testing

### PR DESCRIPTION
**Pull request by galipremsagar**
This PR adds coverage for `skiprows` and `num_rows` parameters in parquet reader fuzz tests.

### CODE REVIEW

**Comment by vuule** [comment]
what values of depth/length are covered by default here?

**Comment by galipremsagar** [comment]
> what values of depth/length are covered by default here?

`None` or any random number between `0` to `len(dataframe)`

**Comment by vuule** [comment]
> > what values of depth/length are covered by default here?
> 
> `None` or any random number between `0` to `len(dataframe)`

I think you can limit the depth to 10. 
Is there an easy way to tell if a test failed due to OOM?

**Review by kkraus14 — DISMISSED** [review]

**Comment by galipremsagar** [comment]
> What if skip_rows + num_rows > len(dataframe)

That seems to be handled in other readers but not parquet reader,

This works:
```python
>>> cudf.read_parquet('a', skiprows=5, num_rows=1)
Empty DataFrame
Columns: [a]
Index: []
>>> cudf.read_parquet('a')
    a
a  10
b  20
c  30
d  40
e  50
```

But this doesn't: https://github.com/rapidsai/cudf/issues/7218

**Comment by vuule** [comment]
With `skip_rows + num_rows > len(dataframe)`, will the tests will assert correctly and expect the correct output, and not `num_rows` rows in the output table?

**Comment by galipremsagar** [comment]
> With `skip_rows + num_rows > len(dataframe)`, will the tests will assert correctly and expect the correct output, and not `num_rows` rows in the output table?

Yep the logic in tests will assert correctly because `head` & `iloc` would not error when the values exceed the bounds, for example:
```python
>>> import pandas as pd
>>> df = pd.read_parquet('a')
>>> df
    a
a  10
b  20
c  30
d  40
e  50
# skiprows
>>> df.iloc[5:]
Empty DataFrame
Columns: [a]
Index: []
# skiprows + numrows
>>> df.iloc[5:].head(2)
Empty DataFrame
Columns: [a]
Index: []
# numrows
>>> df.head(100)
    a
a  10
b  20
c  30
d  40
e  50
```

**Review by rgsl888prabhu — APPROVED** [review]

**Review by vuule — APPROVED** [review]

**Review by kkraus14 — APPROVED** [review]

**Comment by kkraus14** [comment]
@gpucibot merge

**Pull request merged**
