### PR TITLE
Clean up usage of __CUDA_ARCH__ and other macros.

### LINKED ISSUE #15030: Remove obsolete restrictions of `__CUDA_ARCH__ >= 700`.
cudf now requires Volta+, so we can remove `#if __CUDA_ARCH__ >= 700` everywhere.

_Originally posted by @bdice in https://github.com/rapidsai/cudf/pull/14993#discussion_r1486399299_

### PR DESCRIPTION
**Pull request by bdice**
## Description
Closes #15030.

This PR cleans up references to `__CUDA_ARCH__` and other macros.

- We can safely drop Pascal support now that the required minimum is Volta (`__CUDA_ARCH__` of 700).
- Removed a leftover reference to CUDA 10.
- Removed an instance of `#if 1` that was no longer needed.

## Checklist
- [x] I am familiar with the [Contributing Guidelines](https://github.com/rapidsai/cudf/blob/HEAD/CONTRIBUTING.md).
- [x] New or existing tests cover these changes.
- [x] The documentation is up to date with these changes.

### CODE REVIEW

**Comment by davidwendt** [comment]
The `row_conversion.cu` code was moved from the Spark repo to here temporarily and is slated to be moved back https://github.com/rapidsai/cudf/issues/14853
I'm guessing if we don't support Pascal then they would follow but it may be good to check with them.

**Comment by bdice** [comment]
@ttnghia Can you confirm the plan to remove the row conversion code? Can we safely merge the changes in this PR?

**Comment by ttnghia** [comment]
Yes we will move it back to spark-rapids-jni very soon. I can do it this week if I have time. @hyperbolic2346 please review the code change here.

**Review by miscco — APPROVED** [review]

**Review by ttnghia — APPROVED** [review]
Changes in `row_conversion.cu` LGTM, as well as the rest.

**Review by hyperbolic2346 — APPROVED** [review]
row conversion changes look magnificent. I always love removing complexity.

**Pull request merged**
