### PR TITLE
[REVIEW] Set `*count` to 0 when there are 0 rows to count valid bits for

### LINKED ISSUE #1370: [BUG] gdf_count_nonzero_mask() fails when num_rows is 0
Have a look at the implementation of [`gdf_count_nonzero_mask()` on branch-0.7](https://github.com/rapidsai/cudf/blob/branch-0.7/cpp/src/bitmask/valid_ops.cu#L129). If there are "no rows", it immediately returns, even though it's supposed to set `*count` to 0 (see its Doxygen).

### PR DESCRIPTION
**Pull request by eyalroz**
... and updated the doxygen for `gdf_count_nonzero_mask()` in `cudf/functions.h`.

Fixes #1370.

### CODE REVIEW

**Comment by jrhemstad** [comment]
Will merge upon CI passing.

**Comment by jrhemstad** [comment]
@eyalroz the CHANGELOG needs to be updated in order for CI to pass.

**Comment by jrhemstad** [comment]
@eyalroz looks like a many more changes were added to this PR. Was the intentional?

**Comment by eyalroz** [comment]
> @eyalroz looks like a many more changes were added to this PR. Was the intentional?

No, I've gotten the branch mixed up.

**Comment by eyalroz** [comment]
@jrhemstad : Remvoed the irrelevant changes.

**Pull request merged**
