### PR TITLE
Add nvtx annotatations to groupby methods

### PR DESCRIPTION
**Pull request by wence-**
## Description

Not sure if not annotating these was an oversight during implementation...

## Checklist
- [x] I am familiar with the [Contributing Guidelines](https://github.com/rapidsai/cudf/blob/HEAD/CONTRIBUTING.md).
- [x] New or existing tests cover these changes.
- [x] The documentation is up to date with these changes.

### CODE REVIEW

**Review by bdice — COMMENTED** [review]
@wence- This would be a good opportunity to add a section to our Developer Guide about what methods should be annotated. (Searching "nvtx" returns nothing right now.) Should (all/some) private methods be annotated, or only public methods? Let's look at past NVTX PRs for guidance here, like these:
- https://github.com/rapidsai/cudf/pull/10396
- https://github.com/rapidsai/cudf/pull/10374
- https://github.com/rapidsai/cudf/pull/10256
- https://github.com/rapidsai/cudf/pulls?q=is%3Apr+nvtx+is%3Aclosed

**Comment by shwina** [comment]
> Should (all/some) private methods be annotated, or only public methods?

We have been super inconsistent about this so far, but I think all (and only) public methods should be annotated.

**Comment by galipremsagar** [comment]
> Should (all/some) private methods be annotated, or only public methods?

I'd vote for all public methods to be annotated and select private methods on a case-by-case basis. Historically we've annotated private methods for the sake of easier nvtx profiling while working on performance issues.

**Review by bdice — APPROVED** [review]
@wence- I updated this PR for 23.06. I think this is in a good state. Comments above mentioned that only "select" private methods should be annotated. I think the private methods that are annotated here are good candidates for annotation, so I would recommend merging this in the current state.

If we want to add documentation on when to add annotations, I think the discussion above is a good starting point but I would write that in a separate PR so this can merge without further delay.

**Pull request merged**
