### PR TITLE
Fix local build creating directories owned by root

### PR DESCRIPTION
**Pull request by mluukkainen**
Fails to unrelated errors from testing phase. Cannot be merged until tests are fixed.

### CODE REVIEW

**Comment by mluukkainen** [comment]
This patch should be fine. I see same testing result from bash ci/local/build.sh when building with this PR or without this PR. 

== 462 passed, 15 skipped, 7 xfailed, 3 xpassed, 3 warnings in 384.20 seconds ==
Traceback (most recent call last):
  File "/conda/envs/gdf/lib/python3.6/site-packages/numba/utils.py", line 745, in _exitfunc
    f()
  File "/conda/envs/gdf/lib/python3.6/site-packages/numba/utils.py", line 669, in __call__
    return info.func(*info.args, **(info.kwargs or {}))
  File "/conda/envs/gdf/lib/python3.6/site-packages/numba/cuda/cudadrv/driver.py", line 1037, in core
    dealloc.add_item(module_unload, handle)
AttributeError: 'NoneType' object has no attribute 'add_item'

**Comment by harrism** [comment]
Is this WIP or is it ready to merge?

**Comment by mluukkainen** [comment]
> Is this WIP or is it ready to merge?

Good to merge from my POV. Removed WIP

**Comment by mluukkainen** [comment]
> Is this WIP or is it ready to merge?

Not WIP. Ready to merge

**Pull request merged**
