### PR TITLE
Fix null check when comparing structs in `arg_min` operation of reduction/groupby

### PR DESCRIPTION
**Pull request by ttnghia**
This is another fix for https://github.com/NVIDIA/spark-rapids/pull/4434, when the null order is wrongly handled if the input structs column does not have nulls at the top level but only has null at the children levels.

### CODE REVIEW

**Comment by ttnghia** [comment]
@res-life Please test this PR if it can fix all your issues. If there is another corner case that fails, let report it here and I can address it together.

It is not good to have a separate PR to address one issue at a time. If you test it only when it has been merged, then report a new issue, you will end up to wait => fix => wait.... forever.

**Review by hyperbolic2346 — APPROVED** [review]

**Comment by res-life** [comment]
Test case passed with this code, please merge.

**Review by mythrocks — APPROVED** [review]
Good catch!

**Comment by ttnghia** [comment]
Thanks the reviewers. Hope that we will not have another related bug :smile:

**Comment by ttnghia** [comment]
@gpucibot merge

**Pull request merged**
