### PR TITLE
Change environment requirement.

### LINKED ISSUE #560: [BUG] two python tests are failing with numba==0.42.0rc1
**Description**
Conda env created using `/cudf/conda/environments/dev_py35.yml`, installs the `numba==0.42.0rc1`. And with this numba version, two functional test within `test_dataframe.py` are failing.
* `test_dataframe.test_buffer_append()`
* `test_dataframe.test_series_basic()`  
  
 When i tried downgrading the numba version to 0.40.0 and 0.41.0, all the tests got successfully passed.  

Error log:
```
========================================= FAILURES ==========================================
________________________________________test_buffer_append___________________________________

    def test_buffer_append():
        n = 10
        expected = np.arange(n, dtype=np.float64)
        buf = Buffer(expected, size=n - 4, capacity=n)
        assert buf.size == n - 4
        assert buf.capacity == n
        np.testing.assert_equal(buf.mem.copy_to_host(), expected)
        np.testing.assert_equal(buf.to_array(), np.arange(n - 4, dtype=np.float64))

        # Buffer.append
>       buf.append(1.23)

cudf/tests/test_dataframe.py:43:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
cudf/dataframe/buffer.py:155: in append
    self.extend(np.asarray(element, dtype=self.dtype))
cudf/dataframe/buffer.py:161: in extend
    self.mem[self.size:].copy_to_device(array)
/conda/envs/cudf/lib/python3.5/site-packages/numba/cuda/cudadrv/devices.py:212: in _require_cuda_context
    return fn(*args, **kws)
/conda/envs/cudf/lib/python3.5/site-packages/numba/cuda/cudadrv/devicearray.py:197: in copy_to_device
    check_array_compatibility(self_core, ary_core)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
ary1 = <numba.cuda.cudadrv.devicearray.DeviceNDArray object at 0x7f9e915d94a8>, ary2 = array(1.23)

    def check_array_compatibility(ary1, ary2):
        ary1sq, ary2sq = ary1.squeeze(), ary2.squeeze()
        if ary1.dtype != ary2.dtype:
            raise TypeError('incompatible dtype: %s vs. %s' %
                            (ary1.dtype, ary2.dtype))
        if ary1sq.shape != ary2sq.shape:
            raise ValueError('incompatible shape: %s vs. %s' %
>                            (ary1.shape, ary2.shape))
E           ValueError: incompatible shape: (4,) vs. ()

/conda/envs/cudf/lib/python3.5/site-packages/numba/cuda/cudadrv/devicearray.py:696: ValueError
________________________________________test_series_basic_______________________________________

    def test_series_basic():
        # Make series from buffer
        a1 = np.arange(10, dtype=np.float64)
        series = Series(a1)
        assert len(series) == 10
        np.testing.assert_equal(series.to_array(), np.hstack([a1]))

        # Add new buffer
        a2 = np.arange(5)
>       series = series.append(a2)

cudf/tests/test_dataframe.py:88:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
cudf/dataframe/series.py:436: in append
    return Series(self._column.append(other_col))
cudf/dataframe/column.py:458: in append
    newbuf.extend(buf.to_gpu_array())
cudf/dataframe/buffer.py:161: in extend
    self.mem[self.size:].copy_to_device(array)
/conda/envs/cudf/lib/python3.5/site-packages/numba/cuda/cudadrv/devices.py:212: in _require_cuda_context
    return fn(*args, **kws)
/conda/envs/cudf/lib/python3.5/site-packages/numba/cuda/cudadrv/devicearray.py:187: in copy_to_device
    check_array_compatibility(self_core, ary_core)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

ary1 = <numba.cuda.cudadrv.devicearray.DeviceNDArray object at 0x7f9e90c27080>, ary2 = <numba.cuda.cudadrv.devicearray.DeviceNDArray object at 0x7f9e90c27160>

    def check_array_compatibility(ary1, ary2):
        ary1sq, ary2sq = ary1.squeeze(), ary2.squeeze()
        if ary1.dtype != ary2.dtype:
            raise TypeError('incompatible dtype: %s vs. %s' %
                            (ary1.dtype, ary2.dtype))
        if ary1sq.shape != ary2sq.shape:
            raise ValueError('incompatible shape: %s vs. %s' %
>                            (ary1.shape, ary2.shape))
E           ValueError: incompatible shape: (15,) vs. (10,)

/conda/envs/cudf/lib/python3.5/site-packages/numba/cuda/cudadrv/devicearray.py:696: ValueError
```

### PR DESCRIPTION
**Pull request by thomcom**
I think this is an issue in numba 0.41.0rc1. Fixes #560.

### CODE REVIEW

**Comment by thomcom** [comment]
I closed this when I had a corrupt environment, possibly from switching to numba 0.40.0. I have tested two environments cleanly now, one with numba>=0.40 in `dev_py35.yml` and one with `numba=0.40.0` in `dev_py35.yml`. Confirmed that numba 0.42.0 produces two failing tests, and numba 0.40.0 has 1912 passing, 6 skipped, 79 xfails, and 8 xpasses.

That is, numba 0.42.0 has the bug, but numba 0.40.0 is working perfectly.

**Comment by kkraus14** [comment]
@thomcom the issues you're seeing with numba 0.42.0 is that an official release or an rc/dev version? I don't want to lock a user to 0.41.0 if 0.40.0 works as well, ideally we'd want `>=0.40.0,<0.42.0`

**Comment by thomcom** [comment]
The issue has been seen on an `rc1` each time. I didn't know that a complicated version string like that is allowed in `dev_py35.yml`.

**Comment by thomcom** [comment]
The issue began on an `rc1`. Numba is up to `0.42.0` and the issue still exists.

**Comment by thomcom** [comment]
I didn't know that a version string like `>=0.40.0,<0.42.0` is supported, I'll look into 0.41.0. Want me to set that version string if it is good?

**Comment by thomcom** [comment]
It's numba `0.42.0`, numba `0.41.0` is fine:

```
tcomer@dgx02:~/NVIDIA/cudf/python$ conda activate cudf_dev_bad_numba
(cudf_dev_bad_numba) tcomer@dgx02:~/NVIDIA/cudf/python$ pytest -x cudf/tests/test_dataframe.py
============================= test session starts ==============================
platform linux -- Python 3.5.5, pytest-3.8.1, py-1.7.0, pluggy-0.8.0
rootdir: /home/nfs/tcomer/NVIDIA/cudf/python, inifile:
collected 474 items

cudf/tests/test_dataframe.py .F                                          [0/741]

=================================== FAILURES ===================================
______________________________ test_buffer_append ______________________________

    def test_buffer_append():
        n = 10
        expected = np.arange(n, dtype=np.float64)
        buf = Buffer(expected, size=n - 4, capacity=n)
        assert buf.size == n - 4
        assert buf.capacity == n
        np.testing.assert_equal(buf.mem.copy_to_host(), expected)
        np.testing.assert_equal(buf.to_array(), np.arange(n - 4, dtype=np.float64))

        # Buffer.append
>       buf.append(1.23)

cudf/tests/test_dataframe.py:43:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
cudf/dataframe/buffer.py:155: in append
    self.extend(np.asarray(element, dtype=self.dtype))
cudf/dataframe/buffer.py:161: in extend
    self.mem[self.size:].copy_to_device(array)
../../../anaconda3/envs/cudf_dev_bad_numba/lib/python3.5/site-packages/numba/cuda/cudadrv/devices.py:212: in _require_cuda_context
    return fn(*args, **kws)
../../../anaconda3/envs/cudf_dev_bad_numba/lib/python3.5/site-packages/numba/cuda/cudadrv/devicearray.py:197: in copy_to_device
    check_array_compatibility(self_core, ary_core)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

ary1 = <numba.cuda.cudadrv.devicearray.DeviceNDArray object at 0x7fc6c6ea1048>
ary2 = array(1.23)

    def check_array_compatibility(ary1, ary2):
        ary1sq, ary2sq = ary1.squeeze(), ary2.squeeze()
        if ary1.dtype != ary2.dtype:
            raise TypeError('incompatible dtype: %s vs. %s' %
                            (ary1.dtype, ary2.dtype))
        if ary1sq.shape != ary2sq.shape:
            raise ValueError('incompatible shape: %s vs. %s' %
>                            (ary1.shape, ary2.shape))
E           ValueError: incompatible shape: (4,) vs. ()

../../../anaconda3/envs/cudf_dev_bad_numba/lib/python3.5/site-packages/numba/cuda/cudadrv/devicearray.py:696: ValueError
====================== 1 failed, 1 passed in 1.14 seconds ======================
(cudf_dev_bad_numba) tcomer@dgx02:~/NVIDIA/cudf/python$ conda list | grep numba
# packages in environment at /home/nfs/tcomer/anaconda3/envs/cudf_dev_bad_numba:
llvmlite                  0.27.0           py35hf484d3e_0    numba
numba                     0.42.0          np115py35hf484d3e_0    numba
(cudf_dev_bad_numba) tcomer@dgx02:~/NVIDIA/cudf/python$
```

**Comment by thomcom** [comment]
Haha so `0.42.0rc1` is younger than `0.42.0` so that string fails.

**Comment by thomcom** [comment]
`0.42.0dev0` works.... Next update pushed.

**Comment by harrism** [comment]
@thomcom can we close this?

**Comment by thomcom** [comment]
y

**Pull request closed without merging**
