### PR TITLE
Update to UCX-Py 0.24

### PR DESCRIPTION
**Pull request by pentschev**

### CODE REVIEW

**Review by ajschmidt8 — APPROVED** [review]

**Comment by pentschev** [comment]
rerun tests

**Comment by pentschev** [comment]
rerun tests

**Comment by pentschev** [comment]
rerun tests

**Comment by quasiben** [comment]
rerun tests

**Comment by ajschmidt8** [comment]
This can be merged with `@gpucibot merge` when ready. The failing/pending status checks here are old checks that can't be removed unless a new commit is pushed. The required checks have all passed.

**Comment by quasiben** [comment]
@gpucibot merge

**Pull request merged**
