### PR TITLE
Potential overflow of `decimal32` when casting to `int64_t`

### PR DESCRIPTION
**Pull request by codereport**
This bug fixes https://github.com/rapidsai/cudf/issues/9281.

The issue is that we should be using `std::common_type_t` for explicit casting between different types to avoid overflow. That fix has been applied.

### CODE REVIEW

**Comment by codereport** [comment]
rerun tests

**Review by jrhemstad — APPROVED** [review]

**Comment by jrhemstad** [comment]
Great job on the quick fix.

**Review by ttnghia — APPROVED** [review]

**Review by robertmaynard — APPROVED** [review]

**Review by nvdbaranec — APPROVED** [review]

**Comment by codereport** [comment]
@shwina Currently, Python tests are failing:
```py
E   AssertionError: Series are different
E   
E   Series values are different (30.0 %)
E   [index]: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
E   [left]:  [14.0, 2.0, nan, 0.0, 1844674399.0, nan, 94.0, 1844674295.0, 1844674399.0, nan]
E   [right]: [14.0, 2.0, nan, 0.0, 1.8446744073709552e+19, nan, 94.0, 1.8446744073709552e+19, 1.8446744073709552e+19, nan]
```
The input sequence is: 
```py
@pytest.mark.parametrize(
    "data",
    [
        cudf.Series(
            [
                14.12309,
                2.343942,
                np.nan,
                0.0,
                -8.302082, # failing
                np.nan,
                94.31308,
                -112.2364, # failing
                -8.029972, # failing
                np.nan,
            ]
        ),
    ],
)
```
So although it seems like the previous behaviour was consistent with arrow, negative numbers seem to not be working.

This looks like an orthogonal issue to the current bug. Do you agree? or is the previous behaviour expected?

**Comment by codereport** [comment]
@ashwin And I just had a short call and diagnosed the issue was that we were using `NUMERIC_TYPES` in the Python tests when we should have been using `SIGNED_TYPES`.

**Review by galipremsagar — APPROVED** [review]

**Comment by codereport** [comment]
rerun tests

**Comment by codereport** [comment]
@gpucibot merge

**Pull request merged**
