### PR TITLE
Fix an issue with one_level_list schemas in parquet reader.

### PR DESCRIPTION
**Pull request by nvdbaranec**
Partially addresses: https://github.com/rapidsai/cudf/issues/10733

For a particular way of encoding list schemas (an old way that Spark seems to use sometimes), the parquet reader was accidentally propagating incorrect nesting information between columns.  Just a simple bug of not popping an extra value off a stack.

Note:  this is simply a fix so that the files read correctly, however the internal data in the file is actually of binary type and cudf converts these to string columns.  This PR does not add support for binary as a real type in cudf.

### CODE REVIEW

**Review by PointKernel — APPROVED** [review]
LGTM. Thanks!

**Review by mythrocks — APPROVED** [review]
Thanks for explaining it to me, @nvdbaranec.

**Comment by mythrocks** [comment]
I realize there isn't a good way to test the readers without checking in the parquet file itself. :/

**Review by galipremsagar — APPROVED** [review]

**Comment by nvdbaranec** [comment]
@gpucibot merge

**Pull request merged**
