### PR TITLE
[REVIEW] Keep name when unpickling an Index

### PR DESCRIPTION
**Pull request by shwina**
Fixes https://github.com/rapidsai/cudf/issues/3798

...but probably not what we want

### CODE REVIEW

**Comment by kkraus14** [comment]
Looks like we need to add Index classes to here: https://github.com/rapidsai/cudf/blob/6f81a5ccd21abb245fba869045cd63a4cd6250cc/python/cudf/cudf/comm/serialize.py

**Comment by jakirkham** [comment]
Added PR ( https://github.com/dask/distributed/pull/3378 ) to include `cudf.Index` in that list.

**Comment by rjzamora** [comment]
Yes- We should probably have index objects in those lists.  However, that doesn't seem to be the cause of the problem here.  The problem is that `distributed` is not even trying to use `"cuda"` as a serialization backend at all.  I am still struggling to figure out the *correct* fix here.

**Comment by rjzamora** [comment]
Note that the following pytest illustrates that there is no problem if the `"cuda"` is explicitly passed in the list of allowable serialization backends, but fails otherwise:

```python
from distributed.protocol import serialize, deserialize
import pytest
import cudf
import numpy as np


@pytest.mark.parametrize("serializers", [
    [("dask", "pickle"), ("dask", "pickle", "error")],
    [("cuda", "dask", "pickle"), ("cuda", "dask", "pickle", "error")],
])
def test_serialize_cudf(serializers):
    x = cudf.DataFrame({'a':[1,2,3,4], 'b':[5,1,2,5]}).set_index('b')
    header, frames = serialize(x, serializers=serializers[0])
    y = deserialize(header, frames, deserializers=serializers[1])
    assert x.index.name == y.index.name
```

**Pull request merged**
