### PR TITLE
Add missing atomic operators, refactor atomic operators, move atomic operators to detail namespace.

### PR DESCRIPTION
**Pull request by bdice**
## Description
This PR does a thorough refactoring of `device_atomics.cuh`.

- I moved all atomic-related functions to `cudf::detail::` (making this an API-breaking change, but most likely a low-impact break)
- I added all missing operators for natively supported types to `atomicAdd`, `atomicMin`, `atomicMax`, etc. as discussed in #10149 and #14907.
  - This should prevent fallback to the `atomicCAS` path for types that are natively supported for those atomic operators, which we suspect as the root cause of the performance regression in #14886.
- I kept `atomicAdd` rather than `cudf::detail::atomic_add` in locations where a native CUDA overload exists, and the same for min/max/CAS operations. Aggregations are the only place where we use the special overloads. We were previously calling the native CUDA function rather than our special overloads in many cases, so I retained the previous behavior. This avoids including the additional headers that implement an unnecessary level of wrapping for natively supported overloads.
- I enabled native 2-byte CAS operations (on `unsigned short int`) that eliminate the do-while loop and extra alignment-checking logic
  - The CUDA docs don't state this, but some forum posts claim this is only supported by compute capability 7.0+. We now have 7.0 as a lower bound for RAPIDS so I'm not concerned by this as long as builds/tests pass.
- I improved/cleaned the documentation and moved around some code so that the operators were in a logical order.
- I assessed the existing tests and it looks like all the types are being covered. I'm not sure if there is a good way to enforce that certain types (like `uint64_t`) are passing through native `atomicAdd` calls.

## Checklist
- [x] I am familiar with the [Contributing Guidelines](https://github.com/rapidsai/cudf/blob/HEAD/CONTRIBUTING.md).
- [x] New or existing tests cover these changes.
- [x] The documentation is up to date with these changes.

### CODE REVIEW

**Comment by karthikeyann** [comment]
>I changed all uses of atomicAdd to use cudf::detail::atomic_add . I'd like to retain the previous behavior 

I support to retain previous behaviour. If not, it introduces another templated header into include dependency of other files. Templated atomicAdd is created to support unsupported types in CUDA. It's not required for these other files.

**Comment by GregoryKimball** [comment]
@SurajAralihalli FYI

**Review by davidwendt — APPROVED** [review]

**Comment by GregoryKimball** [comment]
@SurajAralihalli Would you like to share a review on this change?

**Review by SurajAralihalli — APPROVED** [review]

**Pull request merged**
