### PR TITLE
Fix make_empty_scalar_like on list_type

### LINKED ISSUE #9758: [BUG] First reduction produces incorrect result type for inputs of list_type
**Describe the bug**
The column view of return scalar is in list_type rather than the child type of the input list_type. It is because in `make_empty_scalar_like` we create list scalar with the list column instead of its child.

### PR DESCRIPTION
**Pull request by sperlingxx**
Fixes #9758

In `make_empty_scalar_like`, we create list scalar with the list column itself, which is wrong. The correct way is with the child of list column.

### CODE REVIEW

**Comment by sperlingxx** [comment]
rerun tests

**Review by ttnghia — APPROVED** [review]

**Review by devavret — APPROVED** [review]

**Comment by sperlingxx** [comment]
rerun tests

**Comment by sperlingxx** [comment]
@gpucibot  merge

**Comment by sperlingxx** [comment]
@gpucibot merge

**Pull request merged**
