### PR TITLE
[REVIEW] max/min binary operator that considers null values

### LINKED ISSUE #3762: [FEA] greatest/least in list of columns and scalars.
**Is your feature request related to a problem? Please describe.**
We would like to implement the Spark SQL greatest function and least function.  They return the largest or smallest non-null value among a list of scalars and columns respectively. 

**Describe the solution you'd like**
I would love some functions that take in a vector of columns and a vector of scalars and return the largest value or the smallest value depending on the function or null if all values were null.

**Describe alternatives you've considered**
We can implement this using existing operators like >, isNull, and copy_if_else but it would materialize a lot more intermediate data than would be ideal.

### PR DESCRIPTION
**Pull request by sriramch**
- this is a superset of #4880 (and includes the changes from #4880)
  - this addresses feature request 3762 - Closes #3762
  - return max/min of 2 values such that:
    - `min/max(x, null)` || `min/max(null, x)` returns `x`
    - `min/max(null, null)` returns `null`
    - `min/max(x, y)` returns the min/max value between x and y
    - this also works for string types (as long as the operands are string as well)

### CODE REVIEW

**Comment by GPUtester** [comment]
Please update the changelog in order to start CI tests.

View the gpuCI docs [here](https://docs.rapids.ai/gpuci#open-pr-or-update-pr).

**Comment by devavret** [comment]
> perhaps we just need another set of binary op APIs that are "null aware"

Either that or we make the existing APIs take parameters like `NULLS_ARE_EQUAL` and `NULLS_AS_LARGEST` (which was replaced in libcudf++ with `null_order::AFTER`)

**Comment by sriramch** [comment]
> I know this contradicts what I said in the prior PR, but if this is going to continue to be a pattern, then perhaps we just need another set of binary op APIs that are "null aware". So:

[sc] i'll add a separate set of api's (which was how #4880 started). as far as i now, equal/min/max were the only requirements. 

> Though I definitely dislike the naming of "null_aware" in the API and that would need to be changed, but this gives the overall idea.

[sc] would `null_considering` be any better?

**Comment by sriramch** [comment]
> Either that or we make the existing APIs take parameters like `NULLS_ARE_EQUAL` and `NULLS_AS_LARGEST` (which was replaced in libcudf++ with `null_order::AFTER`)

@devavret - for my own edification - what is the abi compatibility policy for cudf? is binary compatibility guaranteed at all? if so, is it between minor releases (0.13->0.14 etc.), between major releases etc.?

**Comment by jrhemstad** [comment]
> what is the abi compatibility policy for cudf? is binary compatibility guaranteed at all?

Not until 1.0.

**Comment by jrhemstad** [comment]
> would `null_considering` be any better?

The problem I have with both `null_aware` and `null_considering` is that they are putting implementation details into the external API.

As far as a user is concerned, the current binary ops are "null aware", it's just that any operation with a null begets a null. 

It very well could have been implemented such that the kernel is actually "aware" of null values, but instead it was a lot more efficient to just AND the two masks together and ignore nulls in the kernel. But that's all implementation detail.

The difference I want to highlight is that in the current binary ops, any operation with NULL yields NULL. But with the new ones, that's not always the case. I'm not sure how to capture that.

**Comment by sriramch** [comment]
>> The problem I have with both null_aware and null_considering is that they are putting implementation details into the external API.
>
>> ...in the current binary ops, any operation with NULL yields NULL. But with the new ones, that's not always the case. I'm not sure how to capture that.

[sc] as much as i do not like to state this, i'll do so nonetheless, only because i see a precedent for such a thing! notwithstanding that cudf is used outside of spark, how about calling these operators - `null_safe_equal` (sql term), `spark|sql_greatest` etc.? i say this only because there exists a `pymod` operator today that respects python sign rules to compute the modulo value.

**Comment by jrhemstad** [comment]
> i say this only because there exists a `pymod` operator today that respects python sign rules to compute the modulo value.

I actually resisted calling that operation `pymod` and instead just calling it `modulus` while calling the C++ `%` operator `remainder`.

As such, I wouldn't want to use Spark specific terminology. `null_safe_equal` is unappealing as it implies the other function is "unsafe".

**Comment by revans2** [comment]
I agree that naming is really hard to get right.  The spark operators are called `greatest`, `least`, and `<=>`.  Not that those names are really any better.  They are part of standard SQL and kind of look like they picked them because `min` and `max` were taken for aggregates and `<=>` is just its own thing.  

I think it comes down to a couple of options.

1) Null handling needs to be a separate concern for binops. That might require changes to all of the bin ops kernels because null in == null out is simple to do outside of the core kernel function, but nulls are greater or less requires knowledge of the operator.
2) These are one-off operators and trying to combine them with binops is the problem.
3) null handling is not inherent in binops so just pick a name, and name and go on.  Users just need to document what it does and be careful.

As a consumer of the library, I can see a lot of value in keeping the API consistent.  You don't want to surprise the user, especially with a "rare" case like nulls, so I think option 3 is not really a good one. In picking option 1 vs option 2 it really comes down to how useful generic null handling would be vs how much code/testing would be required.

If this PR is the only one going to handle nulls differently then making it a parameter to binops is probably the wrong call.  But if there are other cases...

Since we are not at 1.0 yet we can change things, so I would say start by making them separate operations, not bin-ops, and we can change things in the future.

**Comment by devavret** [comment]
>     1. nulls are greater or less requires knowledge of the operator.

In this case, they're neither greater nor less. `op(null, x) = x` for both min and max. Binary ops considers `op(null, x) = null`. 

>     2. These are one-off operators and trying to combine them with binops is the problem

Indeed, there is no "null-unaware" min and max in binops either. Although, even with making them standalone APIs, the problem still stands as to what should be done to specify the behaviour. Should `max(x, null) == null` or `x`. If we were to take that as a parameter then what would we call it? `propagate_nulls`?

**Comment by sriramch** [comment]
>> Although, even with making them standalone APIs, the problem still stands as to what should be done to specify the behaviour. Should max(x, null) == null or x.

if there are going to be *separate* api's for `equals/min/max` or a *single* api with one of these ops as a parameter, wouldn't the semantics/docs or the fact that this is a new api distinguish this from a traditional binop api? iow, users will use this api only for non-traditional behavior (`max(x, null) = x`)

**Comment by harrism** [comment]
So, at the risk of stating the obvious,  the proposed APIs return valid (!NULL) if either of its inputs is valid, right? 

> min/max(x, null) || min/max(null, x) returns x
> min/max(null, null) returns null
> min/max(x, y) returns the min/max value between x and y

While the existing bins return valid (!NULL) only if both of the inputs are valid.

So the existing ones do a "valid AND", and the proposed ones do a "valid OR".

> If we were to take that as a parameter then what would we call it? propagate_nulls?

```
enum class validity_propagation : bool {
  AND, 
  OR
};
```

**Comment by sriramch** [comment]
> So, at the risk of stating the obvious, the proposed APIs return valid (!NULL) if either of its inputs is valid, right?
> While the existing bins return valid (!NULL) only if both of the inputs are valid.
> So the existing ones do a "NULL AND", and the proposed ones do a "NULL OR".

[sc] there are 2 classes of these (null using/aware/considering) operators - one that return bool and one that returns another datatype. the former is in #4880 which is now bundled here. for the ones that returns bool, the result is also valid when both operands are invalid. hence, from that perspective, it is neither and/or. i'm not sure if `propagate_nulls` really captures what these 3 operators are doing uniformly.

should these be made as a separate api that takes another enum class (different from `binary_operator`) as an argument that deals with the null_mask in a way that is appropriate for that operation?

**Comment by devavret** [comment]
> > > Although, even with making them standalone APIs, the problem still stands as to what should be done to specify the behaviour. Should max(x, null) == null or x.
> 
> if there are going to be _separate_ api's for `equals/min/max` or a _single_ api with one of these ops as a parameter, wouldn't the semantics/docs or the fact that this is a new api distinguish this from a traditional binop api? iow, users will use this api only for non-traditional behavior (`max(x, null) = x`)

If we were to add min/max as separate operations apart from binaryops, we'd want the same API to handle both null propagation behaviours, as opposed to adding `binary_operation::MAX` that `AND` propagates nulls and a separate `cudf::greater()` that does the same thing but `OR` propagates nulls.

**Comment by sriramch** [comment]
> If we were to add min/max as separate operations apart from binaryops, we'd want the same API to handle both null propagation behaviours, as opposed to adding `binary_operation::MAX` that `AND` propagates nulls and a separate `cudf::greater()` that does the same thing but `OR` propagates nulls. Unless there's good reason for the contrary.

[sc] what about equals then? what we need is `xnor` and what seems to be present is `and`. if this has to be a separate api like (min/max that returns something besides a bool), what about the `equal` operator that is already present?

**Comment by devavret** [comment]
> > If we were to add min/max as separate operations apart from binaryops, we'd want the same API to handle both null propagation behaviours, as opposed to adding `binary_operation::MAX` that `AND` propagates nulls and a separate `cudf::greater()` that does the same thing but `OR` propagates nulls. Unless there's good reason for the contrary.
> 
> [sc] what about equals then? what we need is `xnor` of null mask and what seems to be present is `and`. if this has to be a separate api like min/max (that returns something besides a bool), what about the `equal` operator that is already present?

Ok, I'm convinced. These should just stay as binaryops' enums. Binaryops needs a little bit of refactoring to enable this without hacks but that's out of scope for this PR.

**Comment by sriramch** [comment]
@devavret @trxcllnt can you please review this? i have defined these as separate binary operators with the semantics documented in the header file (which spark needs). these can be handled as separate api's as well, but there will a number of them (3 for each one of these ops (combinations of column/scalar) times 3 ops (null/min/max)). alternatively, there can be a single api that takes in a new enum class that has these null-aware ops defined. 

this is required, as these operators differ from the traditional equals/min/max in terms of return type and the null masks.

**Pull request merged**
