### PR TITLE
Use segmented_sort_by_key for sorting smaller lists

### PR DESCRIPTION
**Pull request by shwina**
`DeviceSegmentedRadixSort` is much slower than `segmented_sort_by_key` for the use-case of O(10)-O(100) size lists. For larger lists, there's a significant advantage to using `DeviceSegmentedRadixSort`. This PR introduces a simple heuristic to choose between the two.

The chart below compares the previous "best" performing sort with the heuristic-based approach:

chart

In all cases, we get the "best" sort with this heuristic.

### CODE REVIEW

**Comment by revans2** [comment]
I'm not sure that we should assume lists will be `O(100)` or smaller. What is the performance like for bigger arrays? If `DeviceSegmentedRadixSort` is about the same then I am fine with this, but if it is much faster for those situations then we should look at using a heuristic to decide which to use. It is simple enough to get the average number of elements in a list for the column that looks like it might be a good starting point.

**Comment by jrhemstad** [comment]
> I'm not sure that we should assume lists will be `O(100)` or smaller. What is the performance like for bigger arrays? If `DeviceSegmentedRadixSort` is about the same then I am fine with this, but if it is much faster for those situations then we should look at using a heuristic to decide which to use. It is simple enough to get the average number of elements in a list for the column that looks like it might be a good starting point.

I suspect you'd need at least `O(1000)`+ to see an advantage. Even then, not sure.

**Review by trxcllnt — APPROVED** [review]

**Comment by ttnghia** [comment]
Sorry, from the graph I don't see very much advantage of using this patch. Can you clarify the speedup number, please? Such as "with heuristic, we gained 1.5X/3X/5X faster performance etc...".

**Comment by shwina** [comment]
@ttnghia Apologies - I should have been more clear. There's no speedup - the heuristic chooses between the two implementations. See the chart below that makes this more clear; for all sizes, the heuristic chooses the faster sort:

chart (1)

**Comment by shwina** [comment]
rerun tests

**Review by nvdbaranec — APPROVED** [review]

**Comment by shwina** [comment]
rerun tests

**Comment by jrhemstad** [comment]
@gpucibot merge

**Pull request merged**
