### PR TITLE
Forward-merge branch-21.12 to branch-22.02

### PR DESCRIPTION
**Pull request by bdice**
Resolves conflicts in #9721 following the [forward merger instructions](https://docs.rapids.ai/maintainers/gpuci/#forward-mergers). Necessary to fix failing gpuCI style checks with changed clang-format version.

### CODE REVIEW

**Comment by bdice** [comment]
rerun tests

**Review by davidwendt — APPROVED** [review]

**Review by galipremsagar — APPROVED** [review]

**Comment by galipremsagar** [comment]
Thanks @bdice !
@ajschmidt8 could you admin merge this pr?

**Comment by ttnghia** [comment]
@gpucibot merge

**Comment by ttnghia** [comment]
Still need approval to merge.
```
Waiting on code owner review from rapidsai/ops-codeowners.
```

**Review by karthikeyann — APPROVED** [review]

**Review by ajschmidt8 — APPROVED** [review]

**Comment by bdice** [comment]
Thanks for the quick review/merge! 👍

**Pull request merged**
