### PR TITLE
[REVIEW] Makes register methods in cleaner not synchronized to prevent extra c…

### PR DESCRIPTION
**Pull request by abellina**
…ontention on the MemoryCleaner lock

During some testing in Spark I found some contention for MemoryCleaner's lock (where all tasks were waiting on that when registering memory with the cleaner). This patch removes the synchronized in the register functions (from a recommendation by @revans2). In my case it removed this as a dominant time sink when running without it.

The collection we are adding to is already a concurrent collection, so the synchronized is just extra overhead.

### CODE REVIEW

**Comment by revans2** [comment]
Rerun CI

**Comment by revans2** [comment]
rerun tests

**Comment by jlowe** [comment]
rerun tests

**Comment by jlowe** [comment]
@kkraus14 do you have an idea on what's going on with the CI failures?  Seen a couple of PRs where the jenkins script runs, spits out a single Java filename, then fails, e.g.:
```
[cudf-cpu-build] $ /bin/bash /tmp/jenkins1689370546584275943.sh

java/src/main/java/ai/rapids/cudf/MemoryCleaner.java
Build step 'Execute shell' marked build as failure
```

**Comment by kkraus14** [comment]
> @kkraus14 do you have an idea on what's going on with the CI failures? Seen a couple of PRs where the jenkins script runs, spits out a single Java filename, then fails, e.g.:
> 
> ```
> [cudf-cpu-build] $ /bin/bash /tmp/jenkins1689370546584275943.sh
> 
> java/src/main/java/ai/rapids/cudf/MemoryCleaner.java
> Build step 'Execute shell' marked build as failure
> ```

Sorry this is the first I've seen it @raydouglass any ideas what's going on here?

**Comment by abellina** [comment]
rerun tests

**Comment by jlowe** [comment]
rerun tests

**Pull request merged**
