### PR TITLE
[REVIEW] Implemented a lazy import mechanism

### PR DESCRIPTION
**Pull request by rlratzel**
This PR attempts to address #627

A more recent profile of the cudf import did not yield anything especially suspicious, and I'm assuming that importing fewer things into the cudf namespace would certainly help, but may not be backwards-compatible. Rather than try to discover safe code paths to optimize or remove and hope our unit test coverage is adequate, I thought a lazy-import mechanism might be worth trying. This approach would obviously not prevent future optimizations to speed up importing either.

This mechanism was written with the idea that a "non-lazy" import could still be achieved by selectively importing items from the cudf namespace that were known to be needed, which is commonly done anyway, like this:
```
from cudf import DataFrame   # only import items needed for DataFrame
```
but a truly lazy approach can be taken as well:
```
import cudf     # nothing is imported, only the namespace is set up
cudf.DataFrame  # the import happens now, and only for items needed for DataFrame
```
**One other thing to mention is this also fully creates a CUDA context when cudf is imported, which did not seem to be happening before.**

Here's some crude metrics:
*BEFORE:*
```
>>> import time
>>> st=time.time();import cudf;print(time.time()-st)
1.0936174392700195
>>> st=time.time();import numba.cuda;numba.cuda.current_context();print(time.time()-st)
<CUDA context c_void_p(94497316818880) of device 0>
0.5631046295166016
```
*AFTER:*
```
>>> import time
>>> st=time.time();import cudf;print(time.time()-st)
1.099449634552002
>>> st=time.time();import numba.cuda;numba.cuda.current_context();print(time.time()-st)
<CUDA context c_void_p(94567540370160) of device 0>
0.00026226043701171875
>>> st=time.time();from cudf import DataFrame;print(time.time()-st)
0.4151611328125
>>> st=time.time();import cudf;print(time.time()-st)
4.5299530029296875e-06
>>> st=time.time();from cudf import DataFrame;print(time.time()-st)
1.1682510375976562e-05
```
*AFTER (non-lazy import of everything):*
```
>>> import time
>>> st=time.time();from cudf import *;print(time.time()-st)
1.5957310199737549
>>> st=time.time();import numba.cuda;numba.cuda.current_context();print(time.time()-st)
<CUDA context c_void_p(93934529509952) of device 0>
0.0002961158752441406
>>> st=time.time();from cudf import DataFrame;print(time.time()-st)
1.33514404296875e-05
>>> st=time.time();from cudf import *;print(time.time()-st)
5.3882598876953125e-05
```

### CODE REVIEW

**Comment by rlratzel** [comment]
*NOTE: The overall performance improvement is not as large as it was in `branch-0.9`, I'm guessing due to some recent refactorings that may have improved the "BEFORE" import time.  We should consider the ROI of having this import mechanism as part of accepting this PR.*

**Comment by rlratzel** [comment]
The CPU CI check revealed a problem with how I'm auto-creating the CUDA context on import of cudf:
```
numba.cuda.cudadrv.driver.CudaAPIError: [100] Call to cuInit results in CUDA_ERROR_NO_DEVICE
```
which (I'm assuming) happens because a CPU build won't have a GPU available.

I can do a dumb catch-and-ignore of this exception, but that seems like a bad idea. I can also just remove it to get the old behavior of not creating the context (and it'll make the import lightning fast). Or, I can write some code to query if there's a GPU available and conditionally create the context.  Or, something else? attn: @kkraus14

**Comment by rlratzel** [comment]
Looks like the CPU builds import cudf as part of the conda build recipe `test` section, which performs a `python -c "import cudf"` and I believe that's where the failing import is coming from.

The CI log showing the failure can be seen [here](https://gpuci.gpuopenanalytics.com/blue/organizations/jenkins/gpuCI%2Fcudf%2Fprb%2Fcudf-cpu-build/detail/cudf-cpu-build/21628/pipeline/)

**Comment by thomcom** [comment]
This is really interesting. Which of the two AFTER cases are you enabling here? Either/or? If you do the lazy `import cudf` but do not create a CUDA context at the time, does import time go down to ~0.6 for cudf?

**Comment by rlratzel** [comment]
> This is really interesting. Which of the two AFTER cases are you enabling here? Either/or?

Both of the AFTER cases are supported. I wanted it to work this way to provide the option of either a truly lazy approach, or a more explicit "I want the import penalty now, but only for this one thing" type of approach.  For example:
```
from cudf import DataFrame   # import items needed for DataFrame now
                             # (and create CUDA context, but no other
                             # cudf namespace members will be imported)
...
df = DataFrame()  # already imported, no import penalty
```
or a lazier option, which assumes you're okay with an import penalty at a potentially critical algorithm execution time:
```
import cudf     # nothing is really imported, this is the fastest option where only the
                # namespace is set up and CUDA context created
...
df = cudf.DataFrame()  # the real import happens now
```

I should mention that there's a [lazy import mechanism in the stdlib](https://docs.python.org/3/library/importlib.html#importlib.util.LazyLoader) but it only allows for the "truly" lazy approach, even if you explicitly import names, and because of that it's discouraged.  Since we explicitly import names, this PR should be better since it'll allow you to take the import hit upfront in a predictable place, but still guarantee that only the imports needed for the names you specify are pulled in. 

>  If you do the lazy `import cudf` but do not create a CUDA context at the time, does import time go down to ~0.6 for cudf?

It's actually faster than that.  If I remove the creation of the CUDA context _and the import of `numba.cuda` needed to do it_, I get the following:
```
>>> import time
>>> st=time.time();import cudf;print(time.time()-st)
0.0006768703460693359
```
`import numba.cuda` and calling `numba.cuda.current_context()` takes up the vast majority of the import time.

**Comment by thomcom** [comment]
@kkraus14 @shwina interested in your takes on this PR.

**Comment by kkraus14** [comment]
I connected with @rlratzel offline and expressed my concerns about the complexity of this PR, especially with regards to the Python version specific semantics for being able to lazily get modules.

I'd like to see a profile of what the current state of importing cudf looks like to understand if there's any low hanging fruit that we could just tackle.

**Comment by harrism** [comment]
@rlratzel @kkraus14 moving this to 0.12...

**Comment by kkraus14** [comment]
Closing as this has gone stale.

**Pull request closed without merging**
