### PR TITLE
Make `is_decompression_disabled` and `is_compression_disabled` thread-safe

### PR DESCRIPTION
**Pull request by vuule**
## Description
Adds a mutex to guard the use of the memoization map for the status of nvCOMP features.

## Checklist
- [x] I am familiar with the [Contributing Guidelines](https://github.com/rapidsai/cudf/blob/HEAD/CONTRIBUTING.md).
- [ ] New or existing tests cover these changes.
- [ ] The documentation is up to date with these changes.

### CODE REVIEW

**Comment by ttnghia** [comment]
I wonder if we can just call `is_(de)compression_disabled_impl` directly without the caching mechanism, as these function is very cheap.

**Comment by vuule** [comment]
> I wonder if we can just call `is_(de)compression_disabled_impl` directly without the caching mechanism, as these functions are very cheap.

Yes, we could. I only added this mechanism to be able to log the result of each query once. Otherwise we would either need a similar map for logging, or we would have to allow logs to be very repetitive.

**Comment by abellina** [comment]
@vuule I ran with this and it did not reproduce.

**Review by abellina — APPROVED** [review]

**Comment by abellina** [comment]
We are hitting all kinds of segfaults in CI that I think are all related to this issue: https://github.com/NVIDIA/spark-rapids/issues/8194, so the spark-rapids CI is currently blocked or limping along.

**Review by ttnghia — APPROVED** [review]

**Pull request merged**
