### PR TITLE
Removed unsafe use of reinterpret_cast and made pointer testing explicit

### PR DESCRIPTION
**Pull request by lamarrr**
Hi I've fixed the issue here: https://github.com/rapidsai/cudf/issues/6029
I've made the `dataptr` a `void *` as recommended and also made the pointer tests within the file explicit rather than implicit as  implicit pointer-to-bool conversion is also undefined behavior.

### CODE REVIEW

**Comment by GPUtester** [comment]
Can one of the admins verify this patch?

**Comment by GPUtester** [comment]
Can one of the admins verify this patch?

**Comment by kkraus14** [comment]
Hey @lamarrr you need to add an entry in `CHANGELOG.md` with a one-liner of the change that you made in order for CI to run.

**Comment by lamarrr** [comment]
> Hey @lamarrr you need to add an entry in `CHANGELOG.md` with a one-liner of the change that you made in order for CI to run.

Thanks! I've made the changes on another PR.

**Pull request closed without merging**
