### PR TITLE
Add support for pydocstyle and test on abc.py

### PR DESCRIPTION
**Pull request by vyasr**
This PR is related to #202 and adds support for using pydocstyle to lint docstrings. It adds flake8 configuration, a pre-commit hook, and sets up the flake8 config to enable incremental application of docstring styling. As an added bonus, because of the way that pydocstyle chooses not to lint docstrings on internal objects (those prefixed with an underscore), as more files are linted we can evaluate what constitutes public API for `cudf`. Once a file has been linted and is added to the regex filter in the config, ongoing CI checks will prevent regressions in the documentation.

As an initial test, this PR lints the abc.py file containing the Serializable class (and updates the docstrings accordingly). We may want to mark that entire class as internal in any case, but it's important enough that it needs to be documented in any case (and perhaps we could settle on a standard docstring style for internal-facing code as well while we're at it).

### CODE REVIEW

**Comment by vyasr** [comment]
@kkraus14 @galipremsagar would appreciate thoughts here before I go any further. I started this because I was rewriting docstrings anyway in the process of other work being done in some of my recent PRs before I found #202. A wholesale update of our docstrings is a big task and too much time investment to be worth prioritizing, but I think following this approach we can improve docs incrementally without dedicating too much time.

**Comment by vyasr** [comment]
@kkraus14 mentioned that it would be great if we could reduce duplication between docstrings and type annotations. The main related tool I was previously aware was [darglint](https://github.com/terrencepreilly/darglint), which is a linter that validates consistency between docstring types and actually accepted arguments. It works well, but has some limitations I've run into that prevented me from adopting it for previous projects and it can be a bit slow. Looks like [`napoleon` has actually implemented support for docstrings where types are pulled from annotations instead of being required in the docstring](https://github.com/sphinx-doc/sphinx/blob/master/doc/usage/extensions/napoleon.rst#type-annotations). There's also [this Sphinx plugin](https://github.com/agronholm/sphinx-autodoc-typehints), but again that seems geared towards Google-style docstrings rather than numpy. `numpydoc` [doesn't have this yet](https://github.com/numpy/numpydoc/issues/196), but we could push for or contribute to making it happen in the longer term if we think it's worthwhile.

I don't think any of this should block us from moving forward with adding docstring validation, but it's something we should keep in mind to reduce duplication in the future.

**Comment by vyasr** [comment]
ok to test

**Comment by vyasr** [comment]
This PR is ready for initial review. rapidsai/integration#258 was just merged, so it may take a while for CI to pick up the new images with `pydocstyle` installed, but `pydocstyle` passes locally (as do all other style checks) so review can move forward and I'll retrigger tests as needed.

**Comment by cwharris** [comment]
style check is failing with no actionable information. :(
```
>>>> FAILED: pydocstyle style check; begin output



>>>> FAILED: pydocstyle style check; end output
```

**Comment by cwharris** [comment]
```
ci/checks/style.sh: line 37: pydocstyle: command not found
```

**Comment by vyasr** [comment]
I added it to the rapids integration metapackage and that change got merged, so I think we'll just have to wait for that conda package to get built. @ajschmidt8 may have a better idea of when that might be.

**Comment by ajschmidt8** [comment]
> I added it to the rapids integration metapackage and that change got merged, so I think we'll just have to wait for that conda package to get built. @ajschmidt8 may have a better idea of when that might be.
> 
> For reference, I think the relevant conda package is [here](https://anaconda.org/rapidsai/rapids-build-env) and we should be able to see when it's been updated (last update is from 5 days ago, which is before pydocstyle was added).

The nightly conda package location is here: https://anaconda.org/rapidsai-nightly/rapids-build-env

There was an issue with CI that I just fixed that prevented the package from getting re-deployed after your changes. Everything is getting re-built and re-deployed now. After the package is updated, the Docker container that installs that package will also have to be updated and re-deployed ([this one](https://hub.docker.com/layers/gpuci/rapidsai-driver/0.20-cuda11.0-devel-ubuntu16.04-py3.7/images/sha256-d0e98ba5e0476ed60e7a0ccfcc05d4ea4ef86026cd01982b7c25befb661bdbcf?context=explore)). After both of those are complete, this PR should have `pydocstyle` included.

**Comment by vyasr** [comment]
rerun tests

**Comment by vyasr** [comment]
@cwharris CI images are updated and the style check passes now.

**Review by cwharris — APPROVED** [review]

**Review by ajschmidt8 — APPROVED** [review]

**Review by kkraus14 — APPROVED** [review]

**Comment by kkraus14** [comment]
@gpucibot merge

**Pull request merged**
