### PR TITLE
[REVIEW] Fix csv_test CUDA too many resources requested fail

### LINKED ISSUE #440: CSV_TEST fails with CUDA launch failure
- [x] I am using the latest version of cuDF from conda, built from `master`, or
built from the latest tagged release. 
- [x] I have included the following environment details:
      Linux Ununtu 18.04, Tesla V100

CSV_TEST fails with the error: `ERROR: CUDA Runtime call cudaGetLastError() in line 833 of file /home/mharris/src/cudf/cpp/src/io/csv/csv_reader.cu failed with too many resources requested for launch (7).`

We believe the error is caused by a block size set to 1024 threads which causing too many registers to be needed to launch the `countRecords` kernel.

### PR DESCRIPTION
**Pull request by j-ieong**
This is to fix #440. The main change is to reduce threads from 1024. It also fixes the simple test, as it was not running if the test file was missing.

### CODE REVIEW

**Comment by GPUtester** [comment]
Can one of the admins verify this patch?

**Comment by GPUtester** [comment]
Can one of the admins verify this patch?

**Comment by harrism** [comment]
add to whitelist

**Comment by harrism** [comment]
add to whitelist

**Comment by harrism** [comment]
@j-ieong I have tested on my machine and I can confirm that this fixes the failures! Thanks for using the CUDA occupancy API. I'd be curious to know what block size it suggested.

If in the future you find that cudaOccupancyAPI calls are expensive (shouldn't be but I have seen perf issues with the underlying cudaFuncGetAttributes call in the past on cuDF), then we could add memoization of the block sizes (e.g. with a static variable) so that they are cached after the first read_csv call.  I doubt they will be a bottleneck for CSV reading, though.

Once we get full CI tests for this I will merge.

**Comment by harrism** [comment]
rerun tests

**Comment by j-ieong** [comment]
@harrism Thanks for pointing out that API, it makes the code look much better.

Yup, the perf is also something for us to keep in mind; and I also doubt that it's a current bottleneck.

I was curious too: it suggested 512 threads on my RTX 2080.

**Comment by mike-wendt** [comment]
run tests

**Comment by mike-wendt** [comment]
add to whitelist

**Comment by mike-wendt** [comment]
run tests

**Comment by mike-wendt** [comment]
run tests

**Comment by mike-wendt** [comment]
If we get all ✅ for the other checks except for `jarvis/cudf-cpu-prb` ignore that failure as the job no longer updates this status message due to the issues we've had. Without a fresh commit there is no way to remove that status easily.

**Comment by harrism** [comment]
Merged. Thanks for the fix, @j-ieong !

**Pull request merged**
