### PR TITLE
Type `Buffer` as `uint8`

### PR DESCRIPTION
**Pull request by jakirkham**
Trying to type `Buffer` as `uint8` again.

### CODE REVIEW

**Comment by GPUtester** [comment]
Please update the changelog in order to start CI tests.

View the gpuCI docs [here](https://docs.rapids.ai/gpuci#open-pr-or-update-pr).

**Comment by jakirkham** [comment]
Looks like this is passing. Anything else we are missing here @kkraus14?

**Comment by kkraus14** [comment]
I think we are implicitly typecasting it from uint8 to a signed type now but this can be expensive as we need to check to avoid overflows and whatnot.

This could inadvertently cause a int16 column to form in certain situations. And lead to incorrect results.

**Comment by jakirkham** [comment]
Do you know where that happens?

**Comment by kkraus14** [comment]
This is the place that comes to mind as to why we didn't use uint8: https://github.com/rapidsai/cudf/blob/branch-0.14/python/cudf/cudf/utils/applyutils.py#L121-L126

**Comment by jakirkham** [comment]
Thanks Keith! It appears that [`mask_dtype` is `int32`]( https://github.com/rapidsai/cudf/blob/724e51910b09bbcf370a8a749adba803e7ef50b4/python/cudf/cudf/utils/utils.py#L16 ). So isn't casting inevitable or am I missing something?

**Comment by kkraus14** [comment]
Maybe I have my streams crossed 😄. I could have sworn there was somewhere that if we changed Buffer to be uint8 we ended up causing errors, but we may have refactored it out since then.

Is there a strong reason to make it uint8 instead of int8?

**Comment by jakirkham** [comment]
No worries. TBH I don't know much about how masks work here. So just trying to fill in the gaps 🙂

It makes it much easier to work with both here and in Dask as allocations on device (and host if we go that way) are backed by `uint8`. Otherwise we need to cast in a bunch of places.

**Comment by kkraus14** [comment]
I just have a fear that we're making this change and everything ends up working due to implicit typecasting rules that we have defined, but I guess worst case they'll show up in profiles and we can address them then.

**Comment by jakirkham** [comment]
Happy to investigate further if you can advise where to look 🙂

**Comment by kkraus14** [comment]
Lets retarget this to 0.15 and I think we're good to go. I'm 99% sure we've fixed the previous issues I was seeing, but would feel more comfortable not trying to push this in right before a release.

**Comment by jakirkham** [comment]
Oh yeah this was never intended for 0.14. Probably got that branch by accident. Will update

**Comment by jakirkham** [comment]
Should be retargeted. Please let me know if I missed anything 🙂

**Pull request merged**
