### PR TITLE
[gpuCI] Forward-merge branch-22.02 to branch-22.04 [skip gpuci]

### PR DESCRIPTION
**Pull request by GPUtester**
Forward-merge triggered by push to `branch-22.02` that creates a PR to keep `branch-22.04` up-to-date. If this PR is unable to be immediately merged due to conflicts, it will remain open for the team to manually merge.

### CODE REVIEW

**Comment by GPUtester** [comment]
**FAILURE** - Unable to forward-merge due to conflicts, **manual** merge is necessary. Do not use the `Resolve conflicts` option in this PR, follow these instructions https://docs.rapids.ai/maintainers/gpuci/#forward-mergers 
 **IMPORTANT:** Before merging and approving this PR, be sure to change the merging strategy to `Create a Merge Commit`. Otherwise, history will be lost and the branches become incompatible.

**Comment by vyasr** [comment]
This PR is replaced by #10079.

**Comment by ajschmidt8** [comment]
@vyasr, let's keep this open. It will "merge" automatically once #10079 is merged since that PR contains all of the commits that this one has. Once this PR "merges", we'll know that the other PR was merged correctly (i.e. merge commit instead of squash commit).

**Comment by vyasr** [comment]
> @vyasr, let's keep this open. It will "merge" automatically once #10079 is merged since that PR contains all of the commits that this one has. Once this PR "merges", we'll know that the other PR was merged correctly (i.e. merge commit instead of squash commit).

Ah OK got it, good to know the process. Thanks!

**Pull request merged**
