### PR TITLE
Add `bytes_per_second` to distinct_count of stream_compaction nvbench.

### PR DESCRIPTION
**Pull request by Blonck**
This patch relates to #13735.

Benchmark:  [benchmark_distinct_count.txt](https://github.com/rapidsai/cudf/files/12700496/benchmark_distinct_count.txt)

## Checklist
- [x] I am familiar with the [Contributing Guidelines](https://github.com/rapidsai/cudf/blob/HEAD/CONTRIBUTING.md).

### CODE REVIEW

**Review by davidwendt — APPROVED** [review]

**Review by karthikeyann — APPROVED** [review]

**Review by harrism — APPROVED** [review]

**Comment by harrism** [comment]
Thanks for the contribution @Blonck! This PR was opened after we entered burndown for 23.10 so @GregoryKimball should decide if this should be merged into 23.10. I suspect it will need to be retargeted to 23.12.

**Comment by Blonck** [comment]
Hi @harrism, I can just rebase this onto 23.12. It's just a benchmark so there is no need to add it to 23.10.

**Comment by vyasr** [comment]
Thanks @Blonck!

**Pull request merged**
