### PR TITLE
Update cudf JNI version to 22.12.0-SNAPSHOT

### PR DESCRIPTION
**Pull request by pxLi**
## Description
Update JNI version to 22.12.0-SNAPSHOT

## Checklist
- [X] I am familiar with the [Contributing Guidelines](https://github.com/rapidsai/cudf/blob/HEAD/CONTRIBUTING.md).
- [X] New or existing tests cover these changes.
- [X] The documentation is up to date with these changes.

### CODE REVIEW

**Comment by pxLi** [comment]
Will rerun the test when CI of 22.12 is available

**Review by ttnghia — APPROVED** [review]

**Comment by pxLi** [comment]
rerun tests

**Comment by pxLi** [comment]
looks like must wait for https://github.com/rapidsai/cudf/pull/11789 before we could pass the pre-merge CI

**Comment by pxLi** [comment]
rerun tests

**Comment by pxLi** [comment]
will wait for https://github.com/rapidsai/cudf/pull/11816 to unblock CI

**Comment by pxLi** [comment]
rerun tests

**Comment by pxLi** [comment]
unrelated test failures. still no clean CI pass for branch-22.12

**Comment by pxLi** [comment]
rerun tests

**Comment by pxLi** [comment]
rerun tests

**Review by revans2 — APPROVED** [review]

**Comment by pxLi** [comment]
rerun tests

**Comment by ttnghia** [comment]
You may need to upstream.

**Comment by revans2** [comment]
@gpucibot merge

**Comment by pxLi** [comment]
> You may need to upstream.

this commit used to test against CI is merged SHA from github, that commit should always be update-to-date when trigger unless merge conflict ~

**Pull request merged**
