### PR TITLE
Readers: Remove copying of result pointers to gdf_column

### PR DESCRIPTION
**Pull request by nartal1**
This is follow-on PR that was discussed in https://github.com/rapidsai/cudf/pull/2212 .

### CODE REVIEW

**Comment by revans2** [comment]
I'm not really sure how I feel about always assuming that the column pointers are always stored in a contiguous block of memory, especially for a small optimization.  I am fine with doing it for a vector because that is a part o the contract, but there is nothing in the table API contract that indicates the same.

**Comment by jlowe** [comment]
> but there is nothing in the table API contract that indicates the same.

I disagree, since `table.begin()` and `table.end()` effectively enforce this.  They can only be used to iterate the table columns with the assumption the pointers are in a contiguous array.

**Comment by jlowe** [comment]
rerun tests

**Comment by revans2** [comment]
Sorry, you are right.

I wrongly assumed what the type of begin and end are.

```
gdf_column** begin();
gdf_column** end();
```

I assumed that an iterator would be returned.

**Pull request merged**
