### PR TITLE
Simplify Python implementations of to_arrow/from_arrow for decimals

### PR DESCRIPTION
**Pull request by shwina**
https://github.com/rapidsai/cudf/pull/7609 added libcudf implementations of these functions, so we can simplify the Python greatly.

### CODE REVIEW

**Review by marlenezw — APPROVED** [review]

**Review by marlenezw — COMMENTED** [review]
This looks good to me! The Dask test failures seem unrelated to the changes, so maybe re-running the tests might help? Really great how much cleaner this makes the code, and wondering if this will work for other cases too :D

**Comment by shwina** [comment]
Retargeting to 21.10 as there's more work to be done here. We now have 32-bit decimals in Python. libcudf doesn't yet have to/from_arrow implementations for 32-bit decimal types and this PR depends on that functionality being available.

**Comment by vyasr** [comment]
@shwina @skirui-source are the necessary libcudf changes ready for this? Should we move to 21.12?

**Comment by shwina** [comment]
Pushed to 21.12, as this is going to need some more work on the libcudf side.

**Comment by shwina** [comment]
I'm closing this PR as it has gone stale. The blocker for this PR has been that libcudf has no concept of `precision`, and being able to convey that metadata about the column to libcudf was essential for correctness, although now the details are a bit hazy for me. For now, keeping the Python implementations seems fine.

**Pull request closed without merging**
