### PR TITLE
Always call rapids_cuda_init_architectures before enabling CUDA language

### PR DESCRIPTION
**Pull request by robertmaynard**
## Description
Ensures that strings_udf_python and strings_udf_cpp properly initialize the CUDA architectures before enabling the CUDA language.

## Checklist
- [x] I am familiar with the [Contributing Guidelines](https://github.com/rapidsai/cudf/blob/HEAD/CONTRIBUTING.md).
- [x] New or existing tests cover these changes.
- [x] The documentation is up to date with these changes.

### CODE REVIEW

**Review by galipremsagar — APPROVED** [review]

**Comment by robertmaynard** [comment]
> Should this ensure that `CMAKE_CUDA_ARCHITECTURES` is properly initialized with all architectures for the `strings_udf` build? I still seem to be seeing it get set only to `"52"` locally with this branch.

Can you confirm that you deleted your build directory before trying this PR? `CMAKE_CUDA_ARCHITECTURES` is a cache variable and requires a full delete for this change to work properly.

**Comment by gmarkall** [comment]
I ran `git clean -fdx` in the `python/cudf/strings_udf` subdir and then built in there again with `setup.py develop` (which is how I had been building it) - perhaps there are artifacts outside of there that would have also affected it? Would I have needed a whole clean build of cudf?

**Comment by robertmaynard** [comment]
> I ran `git clean -fdx` in the `python/cudf/strings_udf`

You will need to clean `python/strings_udf`

**Comment by gmarkall** [comment]
> You will need to clean `python/strings_udf`

Ah yes, sorry - that is what I did, I mis-stated above.

**Comment by robertmaynard** [comment]
It looks like that by enabling all the CUDA architectures we are exposing an error when we try to load PTX that aren't supported by the given machine.

>            raise LinkerError(msg)
> 11:16:39 E           numba.cuda.cudadrv.driver.LinkerError: [222] Call to cuLinkAddFile results in UNKNOWN_CUDA_ERROR
> 11:16:39 E           ptxas application ptx input, line 9; fatal   : Unsupported .version 7.5; current version is '7.0'

**Comment by robertmaynard** [comment]
Closing as #11846 has these changes and has been merged.

**Pull request closed without merging**
