### PR TITLE
[REVIEW] Fix issue 1302, hash join estimated result size is not correct

### PR DESCRIPTION
**Pull request by JinHai-CN**
Fix: #1302

### CODE REVIEW

**Comment by GPUtester** [comment]
Can one of the admins verify this patch?

**Comment by jrhemstad** [comment]
@JinHai-CN can you add an entry to the `CHANGELOG.md` so that CI can pass?

**Comment by jrhemstad** [comment]
add to whitelist

**Comment by kkraus14** [comment]
@JinHai-CN You need to add a line to the `CHANGELOG.md` file with a brief summary of the PR for the `check-changelog` test to pass.

**Comment by jrhemstad** [comment]
Thanks @JinHai-CN . Will merge once CI passes.

**Comment by JinHai-CN** [comment]
@jrhemstad CI failed, but the reason is strange, would you please help check if there is something wrong? Thank you.

**Comment by jrhemstad** [comment]
> @jrhemstad CI failed, but the reason is strange, would you please help check if there is something wrong? Thank you.

@kkraus14 has said there's something broken with the pip-build test, so we can safely ignore it. 

Merging!

**Pull request merged**
