### PR TITLE
[REVIEW] Removed old sort based group by code and gdf_filter

### PR DESCRIPTION
**Pull request by williamBlazing**
This PR is related to #1099 and #1103 . Now that lesserRTTI has been removed, we can also purge easily a lot of old code that is not being used anymore.
The old code being removed is primarily related to the old sort based group by functions which are not currently exposed and the function gdf_filter, which to my knowledge is not used on the python side.
NOTE: #1067 would become irrelevant with this PR since we wont have a gdf_filter anymore

### CODE REVIEW

**Comment by jrhemstad** [comment]
I think you can also remove the entire `src/sqls` directory in addition to https://github.com/rapidsai/cudf/blob/branch-0.8/cpp/tests/sqls/sqls_test.cu

**Comment by williamBlazing** [comment]
> I think you can also remove the entire `src/sqls` directory in addition to https://github.com/rapidsai/cudf/blob/branch-0.8/cpp/tests/sqls/sqls_test.cu

I did remove the entire src/sqls directory and also now the tests/sqls directory. 

If i am not mistaken git does not track folders, so if i remove all files from the folder, then the folder should not exist anymore.

**Comment by jrhemstad** [comment]
> If i am not mistaken git does not track folders, so if i remove all files from the folder, then the folder should not exist anymore.

Ah, good point.

**Comment by jrhemstad** [comment]
@shwina do you mean something more needs to be done other than what @williamBlazing has already done here: https://github.com/rapidsai/cudf/pull/1796/files?file-filters%5B%5D=.pxd#diff-51972750fe600adfa4986c062d0e21e9L228 ?

**Comment by williamBlazing** [comment]
@shwina Let me know what changes need to be made and I will gladly do so, but I am not sure where to get rid of the `gdf_filter` declaration

**Comment by shwina** [comment]
@jrhemstad @williamBlazing My apologies - I Ctrl-F'd for `.pyx` in the GitHub diff and found nothing; hence my comment. But the `.pxd` file was the only place any changes needed to be made. Please disregard my above comment; this PR is approved

**Pull request merged**
