### PR TITLE
Add shallow hash function and shallow equality comparison for column_view

### LINKED ISSUE #9139: [FEA] Provide shallow equality comparison for `column_view`
**Is your feature request related to a problem? Please describe.**

Given two arbitrary `column_view`s, I would like to be able to know in constant time if the two objects are views of identical logical columns. 

**Describe the solution you'd like**

In short, I want a `is_shallow_equal(column_view, column_view)` (name TBD) that returns `true` if the two views reference the _exact_ same data (i.e., their `data`/null_mask pointers are equal, they have equal offsets/size/type/num_children, and all of these things apply recursively to all descendants) Otherwise, returns false, even if the two columns view equivalent data. 

**Additional context**

The primary motivation for this function is in the context of groupby where we maintain a cache of already computed aggregations. We would like to be able to unambiguously detect if we have already computed a particular aggregation for a given column. We'll likewise need a hash function that hashes all of the "shallow" state of a `column_view`. 

For a fascinating look into _Regularity_ and why `std::span` doesn't have an `operator==`, check out:

https://abseil.io/blog/20180531-regular-types
https://stackoverflow.com/questions/60633668/why-does-stdspan-lack-the-comparison-operators

### LINKED ISSUE #9140: [FEA] Provide shallow hash function for `column_view`
**Is your feature request related to a problem? Please describe.**

I want to hash all of the "shallow" state of a `column_view` into a single value. 

**Describe the solution you'd like**

I would like a constant time hash function that hashes all of the shallow state of a `column_view` such that for two `column_view`s `a` and `b` then:
```
is_shallow_equal(a,b) => shallow_hash(a) == shallow_hash(b)
```

See also https://github.com/rapidsai/cudf/issues/9139

### PR DESCRIPTION
**Pull request by karthikeyann**
Fixes #9140 
Added `shallow_hash(column_view)`
Added unit tests
SWIPAT approval complete

It computes hash values based on the shallow states of `column_view`:
type, size, data pointer, null_mask pointer,  offset, and the hash value of the children. 
`null_count` is not used since it is a cached value and it may vary based on contents of `null_mask`, and may be pre-computed or not.

Fixes #9139
Added `is_shallow_equivalent(column_view, column_view)` ~shallow_equal~
Added unit tests

It compares two column_views based on the shallow states of column_view:
type, size, data pointer, null_mask pointer, offset, and the column_view of the children.
null_count is not used since it is a cached value and it may vary based on contents of null_mask, and may be pre-computed or not.

### CODE REVIEW

**Comment by karthikeyann** [comment]
rerun tests

**Review by vyasr — APPROVED** [review]
I'm assuming #9185 was reverted solely due to the need for SWIPAT approval, because AFAICT the contents of this PR are identical to that one and LGTM.

**Comment by vyasr** [comment]
I confirmed that the contents are identical to #9185 with @karthikeyann offline. Since that PR received four approvals before it was merged I'm comfortable going ahead and merging this PR with a single review.

**Comment by vyasr** [comment]
@gpucibot merge

**Pull request merged**
