### PR TITLE
Fix type-o in docstring for json_reader_options

### PR DESCRIPTION
**Pull request by dagardner-nv**
Same as https://github.com/rapidsai/cudf/pull/10626 but against the correct branch

### CODE REVIEW

**Comment by GPUtester** [comment]
Can one of the admins verify this patch?

**Comment by GPUtester** [comment]
Can one of the admins verify this patch?

**Review by cwharris — APPROVED** [review]

**Review by PointKernel — APPROVED** [review]

**Comment by cwharris** [comment]
@gpucibot merge

**Comment by PointKernel** [comment]
@cwharris I guess CI checks are still required to merge this PR.

**Comment by ajschmidt8** [comment]
ok to test

**Comment by ajschmidt8** [comment]
admin merged since it just updates comments

**Pull request merged**
