### PR TITLE
Updating cudf version also updates rapids cmake branch

### PR DESCRIPTION
**Pull request by robertmaynard**
Ensure that when a new cudf version is made, we also bump the rapids-cmake version at the same time.

Otherwise we will get the previous release's dependencies by mistake.

### CODE REVIEW

**Review by raydouglass — APPROVED** [review]

**Comment by ajschmidt8** [comment]
rerun tests

**Comment by robertmaynard** [comment]
@gpucibot merge

**Comment by robertmaynard** [comment]
rerun tests

**Comment by robertmaynard** [comment]
rerun tests

**Comment by robertmaynard** [comment]
@gpucibot merge

**Comment by robertmaynard** [comment]
@gpucibot merge

**Comment by robertmaynard** [comment]
rerun tests

**Comment by vyasr** [comment]
@gpucibot merge

**Review by jlowe — APPROVED** [review]

**Pull request merged**
