### PR TITLE
Fix double counting of selected columns in CSV reader

### PR DESCRIPTION
**Pull request by ochan1**
Fix a bug where the program can Segmentation Fault as a result of selecting the same column twice using index + column_name OR the column_name is typed twice

### CODE REVIEW

**Comment by GPUtester** [comment]
Can one of the admins verify this patch?

**Comment by GPUtester** [comment]
Can one of the admins verify this patch?

**Comment by rgsl888prabhu** [comment]
@ochan1, awesome find, it was great that you pushed a PR for this. The code looks good, it would be better if there is a test case to verify. Can you please add a test case for this [here](https://github.com/rapidsai/cudf/blob/branch-21.08/cpp/tests/io/csv_test.cpp)

**Review by karthikeyann — COMMENTED** [review]
Added. unit tests.
Fixed similar issue in duplicate select indices (causes seg fault)

**Comment by karthikeyann** [comment]
rerun tests

**Comment by karthikeyann** [comment]
rerun tests

**Comment by Ethyling** [comment]
rerun tests

**Comment by Ethyling** [comment]
ok to test

**Comment by Ethyling** [comment]
rerun tests

**Review by karthikeyann — APPROVED** [review]

**Comment by karthikeyann** [comment]
ok to test

**Comment by karthikeyann** [comment]
@ochan1 could you comment "ok to test" and "rerun tests" in separate comments?

**Review by rgsl888prabhu — APPROVED** [review]

**Comment by rgsl888prabhu** [comment]
ok to test

**Comment by rgsl888prabhu** [comment]
rerun tests

**Comment by ajschmidt8** [comment]
ok to test

**Review by trxcllnt — APPROVED** [review]

**Comment by karthikeyann** [comment]
@gpucibot merge

**Pull request merged**
