### PR TITLE
[REVIEW] Remove 2nd type-dispatcher call from cudf::reduce for simple operations

### LINKED ISSUE #6717: [FEA] Improve libcudf compile time for simple reductions (cudf::reduce)
Currently the source files simple reductions (`min`, `max`, `sum`, `product`, and `sum-of-squares`) each take 5-7 minutes to build and in the top 12 slowest source files to compile.

| (ms) | object file built |
| ----- | ----- |
| 860441 | CMakeFiles/cudf_base.dir/src/sort/sort.cu.o |
| 857510 | CMakeFiles/cudf_base.dir/src/sort/stable_sort.cu.o |
| 496797 | CMakeFiles/cudf_rolling.dir/src/rolling/rolling.cu.o |
| 491553 | CMakeFiles/cudf_reductions.dir/src/reductions/scan.cu.o |
| 440116 | CMakeFiles/cudf_reductions.dir/src/reductions/**max.cu**.o |
| 423566 | CMakeFiles/cudf_reductions.dir/src/reductions/**min.cu**.o |
| 417868 | CMakeFiles/cudf_base.dir/src/stream_compaction/drop_duplicates.cu.o |
| 401584 | CMakeFiles/cudf_base.dir/src/strings/sorting/sorting.cu.o |
| 398396 | CMakeFiles/cudf_hash.dir/src/hash/hashing.cu.o |
| 330566 | CMakeFiles/cudf_reductions.dir/src/reductions/**product.cu**.o |
| 322124 | CMakeFiles/cudf_reductions.dir/src/reductions/**sum.cu**.o |
| 319379 | CMakeFiles/cudf_reductions.dir/src/reductions/**sum_of_squares.cu**.o |
| 284708 | CMakeFiles/cudf_join.dir/src/join/semi_join.cu.o |
| 279809 | CMakeFiles/cudf_base.dir/src/search/search.cu.o |
| 243226 | CMakeFiles/cudf_base.dir/src/groupby/hash/groupby.cu.o |
| `^` | Top 15 slowest compile objects |

baseline

The [`cudf::reduce`](https://docs.rapids.ai/api/libcudf/stable/group__aggregation__reduction.html#ga382c3ca1ce3191138795a5c0c4619450) function looks like the following:
```
std::unique_ptr<scalar> reduce(
  const column_view &col,
  std::unique_ptr<aggregation> const &agg,
  data_type output_dtype,
  rmm::mr::device_memory_resource *mr = rmm::mr::get_current_device_resource());
```

The output-type of the scalar is passed as a parameter. This means that the reduce function requires a double type-dispatch. The 1st type-dispatch is for the input `col` column-type and the 2nd type-dispatch is for the output-type `output_dtype`. Although operations like `sum` and `product` only work with numeric types, `min` and `max` handle non-numerics as well. With over 20 numeric types (`int, float, bool, timestamp, duration`), the combination is over 400. That is, a double type-dispatch creates 400 unique code-paths for each of the simple reduction types. And the `min` and `max` operations also includes the strings type.

Adding the dictionary column type to this code increased the compile time for _each of these_ from ~5 minutes to ~18 minutes.

Note that the compound operations (`mean`, `std`, and `var`) all compile in less than 2 minutes because the 2nd type-dispatch is isolated to only the two float types. Adding dictionary support to these operations did not change the compile time significantly.

I propose improving the compile time for the simple reduce ops by trying to remove the 2nd type-dispatcher call for the output-type. For operations like `min` and `max`, we could reasonable restrict the output-type to be equal to the input-type. However, for the other 3 operations (`sum`, `product`, `sum-of-squares`) it is reasonable to expect an output-type different (larger, say) than the input column-type.

But if the output-type is generally the same as the input-type we could optimize for that case. And whenever the output-type does not match the input-type we can perform the reduction operation on a hardcoded type (`int64_t` for integer columns and `double` for floating point columns) and then cast the single scalar result to the output type upon return. The extra cast step would be a performance hit but only applicable if the types do not match.

Testing with the `sum` operation, the compile time is now about ~30s. This includes handling the output-type cast. Running the gbenchmarks for reduction for `sum` showed no change in performance. But the benchmark code logic sets the output-type to the input column-type. Testing with unmatched types showed a significant slow down (~30%) attributed to the extra, final scalar cast step. Perhaps there are some techniques to improve this cast step -- like converting the type without allocating a new scalar.

One other question for consideration or clarification. Are they cases where the overflow side-effects of reduce on smaller output-types are expected and desired? For example, summing 1000 `uint8` values can currently cause intermediate overflows as the values accumulate. This seems non-deterministic and probably undefined behavior but I wanted to ask to be sure.

Changes here would also require reworking the `any` and `all` operations which currently call `min` and `max` but require the output-type to be boolean. Therefore, this seems a good optimization for these 2 ops since the 2nd type-dispatch would not be required.

Overall, I think this could improve the code a bit by defactoring the `result_type_dispatcher` defined in [simple.cuh](https://github.com/rapidsai/cudf/blob/e4404e45a07ff2b599184724dd4bc564c0329d8c/cpp/src/reductions/simple.cuh#L73-L88) which has different rules for different ops and type combinations:
```
  static constexpr bool is_supported_v()
  {
    // for single step reductions,
    // the available combination of input and output dtypes are
    //  - same dtypes (including cudf::wrappers)
    //  - any arithmetic dtype to any arithmetic dtype
    //  - bool to/from any arithmetic dtype
    //  - fixed_point to fixed_point
    return cudf::is_convertible<ElementType, ResultType>::value &&
           (std::is_arithmetic<ResultType>::value ||
            std::is_same<Op, cudf::reduction::op::min>::value ||
            std::is_same<Op, cudf::reduction::op::max>::value) &&
           !cudf::is_fixed_point<ResultType>() &&
           !std::is_same<ResultType, cudf::list_view>::value &&
           !std::is_same<ResultType, cudf::struct_view>::value;
  }
```
Adding a new legal type/op combination to this logic seems problematic. Without this 2nd dispatch, each operation can handle their combination of types more independently and more naturally.

### PR DESCRIPTION
**Pull request by davidwendt**
Closes #6717 

This PR removes the 2nd type-dispatch from the simple reduce operations: `any()`, `all()`, `min()`, `max()`, `sum()`, `product()`, and `sum_of_squares()`. It is replaced with logic using either the same type as the input column type or a hardcoded type as follows:

- `any()` and `all()` expect only `BOOL8` as the output type
- `min()` and `max()` expect the output type to match the column input type
- `sum()`, `product()`, and `sum_of_squares()` allow any output type but may incur an extra scalar cast operation

The cast operation is only required if the output type does not match the input type or if the output type is not `INT64` for integer columns or `FLOAT64` for floating point columns. The extra cast only applies to `sum()`, `product()`, and `sum_of_squares()` ops.

This change improves the compile time for these operations as follows. Times are from ninja_log output and are in seconds.
| source | baseline | this PR |
| --- | --- | --- |
| max() | 440 | 89 |
| min() | 424 | 89 |
| product() | 331 | 75 |
| sum() | 322 | 71 |
| sum-of-squares() | 319 | 77 |

Also, the overall size of the `libcudf_reductions.so` file is reduced from `88 MB` to `50 MB`.
The gbenchmarks results for reductions did not change since the benchmarks had already been coded with the above restrictions.

### CODE REVIEW

**Review by trxcllnt — APPROVED** [review]
:clap:

**Review by harrism — APPROVED** [review]
Awesome. Saving 23 minutes on a sequential build or at least 4 minutes on a parallel build is excellent.

**Comment by karthikeyann** [comment]
Awesome.
How does this impact the reduction benchmarks? (doing 64 bit operations for all bit widths)

**Comment by davidwendt** [comment]
> Awesome.
> How does this impact the reduction benchmarks? (doing 64 bit operations for all bit widths)

The `gbenchmarks/REDUCTION_BENCH` results did not change. The `cpp/reduction/reduce_benchmark.cpp` only forces `mean`, `std`, and `var` output type to `FLOAT64` which the refactored code expects/optimizes.

**Pull request merged**
