### PR TITLE
Make tests deterministic

### PR DESCRIPTION
**Pull request by galipremsagar**
## Description
This PR is a first pass of making tests deterministic, I noticed one of CI job failed due to an overflow error related to random data generation.

 
## Checklist
- [x] I am familiar with the [Contributing Guidelines](https://github.com/rapidsai/cudf/blob/HEAD/CONTRIBUTING.md).
- [x] New or existing tests cover these changes.
- [x] The documentation is up to date with these changes.

### CODE REVIEW

**Review by vyasr — APPROVED** [review]

**Review by rjzamora — APPROVED** [review]
Dask changes LGTM. Thanks!

**Review by mroeschke — COMMENTED** [review]
Not a blocker, but going forward it would be good to start using numpy's new, recommended `numpy.random.Generator` API https://numpy.org/doc/stable/reference/random/generator.html#numpy.random.Generator

**Comment by galipremsagar** [comment]
> Not a blocker, but going forward it would be good to start using numpy's new, recommended `numpy.random.Generator` API https://numpy.org/doc/stable/reference/random/generator.html#numpy.random.Generator

Good point. Noted 👍

**Comment by jakirkham** [comment]
It is worth noting that this is covered by [Ruff's rule `NPY002`]( https://docs.astral.sh/ruff/rules/numpy-legacy-random/#numpy-legacy-random-npy002 ). We may want to consider adding that to this list

https://github.com/rapidsai/cudf/blob/ba4afae921f6d1906a201636c084a82a8586bb36/pyproject.toml#L28-L32

<hr>

On a more general note, we are discussing the value of enabling more Ruff rules for NumPy across RAPIDS in issue: https://github.com/rapidsai/build-planning/issues/103

**Pull request merged**
