### PR TITLE
removing some unused code

### PR DESCRIPTION
**Pull request by hyperbolic2346**
In my endless wandering through parquet code, I found this unused code. Removing it.

### CODE REVIEW

**Review by ttnghia — APPROVED** [review]
I wonder why the compiler doesn't complain.

**Review by PointKernel — APPROVED** [review]

**Comment by hyperbolic2346** [comment]
rerun tests

**Comment by hyperbolic2346** [comment]
rerun tests

**Comment by hyperbolic2346** [comment]
rerun tests

**Comment by PointKernel** [comment]
rerun tests

**Comment by hyperbolic2346** [comment]
@gpucibot merge

**Pull request merged**
