### PR TITLE
[REVIEW] Change cudf docs theme to pydata theme

### PR DESCRIPTION
**Pull request by galipremsagar**
Fixes: #7098

This PR changes our docs theme to pydata theme: https://github.com/pydata/pydata-sphinx-theme, rest of the additional changes include:

- [x] Revamps cudf docs theme to use pydata theme, and made changes to generate separate html pages for each API **thus docs are not going to take ~30s to load anymore, you should see the doc page for each API load almost instantly**.
- [x] Replaced `sphinx_rtd_theme` usages with `pydata-sphinx-theme`.
- [x] Removed `copybutton` being used in code samples, `pydata-sphinx-theme` has this support inbuilt.
- [x] Introduced rapids color scheme 🟪  css styling into `pydata-sphinx-theme`.
- [x] Removed some dead-code related to `markdown` in docs. - We no longer use markdown in docs.
- [x] Moved all Class-related docstrings into `Class` declarations rather than in their `__init__` methods, to make the docstrings be uniform for `autoclass_content` to work correctly.
- [x] Removed the rapids css which is now not needed: `"https://docs.rapids.ai/assets/css/custom.css"`
- [x] Fixed reference errors in multipe places in docstrings; for ex: replaced `cudf.core.series.Series.factorize` with `cudf.Series.factorize`.
- [x] Make top-level import of `StringIndex` possible, previously we cannot do `cudf.StringIndex`, this PR enables it.
- [x] Enable top-level imports for `pivot` & `unstack`: `cudf.pivot` & `cudf.unstack`.

For reviewing purposes, a demo live url to docs is here: https://6111734dedccb71ae0db66dc--docs-rapids-ai.netlify.app/api/cudf/stable/

### CODE REVIEW

**Comment by quasiben** [comment]
The change from the RAPIDS theme to PyData is something we should check in on with other folks about before merging in this PR.  My current understanding is that this PR is resolving performance issues due to a single pane html file, correct ?

**Comment by kkraus14** [comment]
> My current understanding is that this PR is resolving performance issues due to a single pane html file, correct ?

If I try to load the current docs on my phone it crashes the browser 😆. Yes this should resolve the performance issues as well as making the docs cleaner and more familiar to end users (in my opinion!).

**Comment by galipremsagar** [comment]
Thanks to @ajschmidt8 for the live demo site, it is now live at: https://610ad2fcba410508437d6b06--docs-rapids-ai.netlify.app/api/cudf/stable/

**Review by isVoid — COMMENTED** [review]
On API reference page, the description area is default text:
image

**Comment by kkraus14** [comment]
On the `PandasCompat` page it looks like things are duplicated: https://610ad2fcba410508437d6b06--docs-rapids-ai.netlify.app/api/cudf/stable/basics/pandascompat

**Comment by kkraus14** [comment]
It looks like table formatting doesn't have vertical bars which can make certain tables really difficult to read, i.e. https://610ad2fcba410508437d6b06--docs-rapids-ai.netlify.app/api/cudf/stable/basics/groupby.html

image

**Review by ajschmidt8 — COMMENTED** [review]
we'll also need to add `pydata-sphinx-theme` to https://github.com/rapidsai/integration/blob/branch-21.10/conda/recipes/rapids-doc-env/meta.yaml

**Comment by galipremsagar** [comment]
@kkraus14 @isVoid resolved all the 3 concerns and here are the updated docs: https://6111390c1ec726f8f6b9c53b--docs-rapids-ai.netlify.app/api/cudf/stable/

**Review by kkraus14 — APPROVED** [review]

**Review by isVoid — APPROVED** [review]

**Review by vuule — APPROVED** [review]

**Comment by quasiben** [comment]
Thanks @galipremsagar ! And thank you @kkraus14 and @isVoid for the reviews.

With the new theme and multiple pages we may want to consider restructuring a bit more.  For example, the `Basics` heading no longer makes much sense and more interesting topics, like GDS, are not easily visible.  Again, for another PR/discussion.

**Review by quasiben — APPROVED** [review]

**Comment by quasiben** [comment]
@gpucibot merge

**Comment by ajschmidt8** [comment]
just waiting for the changes in https://github.com/rapidsai/integration/pull/336 to be published and then this can be approved and merged.

**Review by ajschmidt8 — APPROVED** [review]

**Comment by ajschmidt8** [comment]
GitHub is having issues which is probably why this didn't merge. Let's try another merge comment. If not, we'll wait a bit until their problems are resolved.

https://www.githubstatus.com/incidents/rmfrw9dfbtbp

**Comment by ajschmidt8** [comment]
@gpucibot merge

**Comment by ajschmidt8** [comment]
had some doc build issues. this should fix it. i tested it locally: https://github.com/rapidsai/integration/pull/338

**Comment by ajschmidt8** [comment]
new docs are live: https://docs.rapids.ai/api/cudf/nightly/

**Pull request merged**
