### PR TITLE
fix device_scalar::get errors cause by rmm#167

### PR DESCRIPTION
**Pull request by cwharris**
Fixes a breaking change caused by rapidsai/rmm#167, so this PR's build will fail until that is merged.

### CODE REVIEW

**Comment by harrism** [comment]
`/var/lib/jenkins/workspace/rapidsai/gpuci/cudf/prb/cudf-gpu-build_2/cpp/src/bitmask/null_mask.cu(171): error: class "rmm::device_scalar<cudf::size_type>" has no member "data"`

**Comment by harrism** [comment]
RMM packages must not be updated...

**Comment by cwharris** [comment]
It looks like the build is compiling against an older version of rmm than is present in `rmm@branch-0.11`. When/how does that update?

**Comment by harrism** [comment]
rerun tests

**Comment by harrism** [comment]
rerun tests

**Comment by cwharris** [comment]
rerun tests

**Comment by cwharris** [comment]
rerun tests

**Pull request merged**
