### PR TITLE
Fix a leftover _has_nulls change from Nullate

### PR DESCRIPTION
**Pull request by devavret**
There was one missed change from template param has_nulls to member Nullate _has_nulls. It worked because has_nulls resolved to pointer to the function `has_nulls(table_view)` which is always true and didn't break at runtime because the subsequent is_null has a built in nullmask check.

### CODE REVIEW

**Review by davidwendt — APPROVED** [review]
That's amazing. Good catch Devavret.
Don't forget to change the copyright.

**Review by rgsl888prabhu — APPROVED** [review]

**Review by rgsl888prabhu — APPROVED** [review]

**Comment by devavret** [comment]
One more small fix in default value of null_equality. This one should've broken because `null_equality::EQUAL` is 0 but `true` is 1.

**Comment by rgsl888prabhu** [comment]
> One more small fix in default value of null_equality. This one should've broken because `null_equality::EQUAL` is 0 but `true` is 1.

In few minutes you might find one more :)

**Review by hyperbolic2346 — APPROVED** [review]
Nice find

**Comment by davidwendt** [comment]
So I hit this kind of thing when introducing the nullate type. Actually one of the motivations for coming up with this name was due to many name-collisions with the existing `has_nulls` in the repo. Given that I missed one (or more perhaps) without a compile error, I think it would be good to turn `cudf::has_nulls(cudf::table_view)` into a member function on `cudf::table_view` instead. 
I can also see a similar error occuring with `cudf::nullable(cudf::table_view)`

**Comment by devavret** [comment]
> I think it would be good to turn `cudf::has_nulls(cudf::table_view)` into a member function on `cudf::table_view` instead. 

Should I do that in this PR?

**Comment by davidwendt** [comment]
> > I think it would be good to turn `cudf::has_nulls(cudf::table_view)` into a member function on `cudf::table_view` instead.
> 
> Should I do that in this PR?

There are over 40 places that `cudf::has_nulls(table_view)` is being used so I think a separate PR would be better.
Also, we may want to get other opinions on converting this into a member function independent of this fix.

**Comment by devavret** [comment]
@gpucibot merge

**Pull request merged**
