### PR TITLE
[REVIEW] Fix GroupBy sort=True

### PR DESCRIPTION
**Pull request by brandon-b-miller**

### CODE REVIEW

**Comment by GPUtester** [comment]
Please update the changelog in order to start CI tests.

View the gpuCI docs [here](https://docs.rapids.ai/gpuci#open-pr-or-update-pr).

**Comment by shwina** [comment]
Oops - sorry for approving a WIP PR @brandon-b-miller  - is there more to be done here?

**Comment by brandon-b-miller** [comment]
@shwina nope, I suspect nothing more here, I just usually wait for CI to clear the changes before review in case I missed something.

**Comment by kkraus14** [comment]
Going to float an idea here... Should we default to `sort=False`? We have an unstable sort underneath anyway where there's still potential to end up with unaligned indexes from running multiple aggregations separately.

**Comment by brandon-b-miller** [comment]
For what its worth, pandas has this to say:

```
sortbool, default True
Sort group keys. Get better performance by turning this off. Note this does not influence the order of observations within each group. Groupby preserves the order of rows within each group.
```

**Comment by kkraus14** [comment]
Merging as is and we can then have a follow up about default sorting behavior.

**Pull request merged**
