### PR TITLE
[REVIEW] Fix some docstrings formatting

### PR DESCRIPTION
**Pull request by galipremsagar**
This PR fixes some of the broken docstring formattings in the code-base.

### CODE REVIEW

**Comment by bdice** [comment]
@galipremsagar I have a complementary PR in progress - it doesn't overlap much with this one, but let me know if you plan to expand the scope of this PR.

**Comment by brandon-b-miller** [comment]
Thanks for taking care of this @galipremsagar

**Comment by galipremsagar** [comment]
> @galipremsagar I have a complementary PR in progress - it doesn't overlap much with this one, but let me know if you plan to expand the scope of this PR.

I was looking to expand the scope, but thanks for letting me. Let's coordinate offline.

**Comment by vyasr** [comment]
@galipremsagar this looks good to me, but just to prevent any overzealous reviewers from reviewing prematurely before you and @bdice sort out PR scopes I've marked this as DO NOT MERGE. Feel free to ping if you need extra reviews/eyes.

**Comment by bdice** [comment]
@vyasr We chatted and we're going to merge #10663 first. This PR may have minor conflicts in one spot but should be ready for review.

**Comment by galipremsagar** [comment]
This is now ready for review

**Review by bdice — APPROVED** [review]
LGTM. Thanks Prem!

**Comment by galipremsagar** [comment]
@gpucibot merge

**Pull request merged**
