### PR TITLE
Missing `f` prefix on f-strings fix

### LINKED ISSUE #10720: Missing `f` prefix on f-strings
Some strings looks like they're meant to be f-strings but are missing the `f` prefix meaning variable interpolation won't happen.

https://github.com/rapidsai/cudf/blob/d6e30681aab3167db8eb3fa38fb3be05fde18627/python/cudf/cudf/core/indexed_frame.py#L2210
https://github.com/rapidsai/cudf/blob/d6e30681aab3167db8eb3fa38fb3be05fde18627/python/cudf/cudf/testing/testing.py#L218
https://github.com/rapidsai/cudf/blob/d6e30681aab3167db8eb3fa38fb3be05fde18627/python/dask_cudf/dask_cudf/io/orc.py#L82

I found this issue automatically. I'm a bot. Beep Boop 🦊. See other issues I found in your repo [here](https://codereview.doctor/rapidsai/cudf)

### PR DESCRIPTION
**Pull request by code-review-doctor**
Fixes #10720

### CODE REVIEW

**Comment by GPUtester** [comment]
Can one of the admins verify this patch?

**Comment by quasiben** [comment]
ok to test

**Comment by shwina** [comment]
rerun tests

**Comment by galipremsagar** [comment]
rerun tests

**Review by galipremsagar — APPROVED** [review]

**Pull request merged**
