### PR TITLE
Enable decimal support in parquet writer

### LINKED ISSUE #7669: [BUG] Can't write Parquet file containing Decimal/Fixed Point column(s)
Using the latest rapidsai-nightly conda package ('0.19.0a+248.g5d7767ec2f'):
```
import cudf
from cudf.core.dtypes import Decimal64Dtype

df = cudf.DataFrame()
df['id'] = [0, 1, 2]
df['val'] = [0.00, 0.01, 0.02]

df['dec_val'] = df['val'].astype(Decimal64Dtype(7,2))
df.to_parquet('test.parquet')
```
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-5-904034a55c73> in <module>
----> 1 df.to_parquet('test.parquet')

/conda/lib/python3.8/site-packages/cudf/core/dataframe.py in to_parquet(self, path, *args, **kwargs)
   7319         from cudf.io import parquet as pq
   7320 
-> 7321         return pq.to_parquet(self, path, *args, **kwargs)
   7322 
   7323     @ioutils.doc_to_feather()

/conda/lib/python3.8/site-packages/cudf/io/parquet.py in to_parquet(df, path, engine, compression, index, partition_cols, partition_file_name, statistics, metadata_file_path, int96_timestamps, *args, **kwargs)
    320                 )
    321         else:
--> 322             write_parquet_res = libparquet.write_parquet(
    323                 df,
    324                 path=path_or_buf,

cudf/_lib/parquet.pyx in cudf._lib.parquet.write_parquet()

cudf/_lib/parquet.pyx in cudf._lib.parquet.write_parquet()

cudf/_lib/utils.pyx in cudf._lib.utils.generate_pandas_metadata()

cudf/_lib/utils.pyx in cudf._lib.utils.generate_pandas_metadata()

/conda/lib/python3.8/site-packages/cudf/utils/dtypes.py in np_to_pa_dtype(dtype)
    123         # default fallback unit is ns
    124         return pa.duration("ns")
--> 125     return _np_pa_dtypes[np.dtype(dtype).type]
    126 
    127 

TypeError: Cannot interpret 'Decimal64Dtype(precision=7, scale=2)' as a data type
```

### PR DESCRIPTION
**Pull request by devavret**
Resolves #7669

### CODE REVIEW

**Review by kkraus14 — APPROVED** [review]

**Comment by kkraus14** [comment]
@devavret are there any issues with round tripping decimal64 vs decimal32 in generating Arrow / Pandas compatible metadata, or is that handled by the logical / physical types in Parquet anyway?

**Comment by devavret** [comment]
> @devavret are there any issues with round tripping decimal64 vs decimal32 in generating Arrow / Pandas compatible metadata, or is that handled by the logical / physical types in Parquet anyway?

Correct me if I'm wrong but I thought cudf only had decimal64 https://github.com/rapidsai/cudf/blob/04f90211fe95b99f4ad934f273faf87639b1f6ff/python/cudf/cudf/core/dtypes.py#L234

**Comment by kkraus14** [comment]
> > @devavret are there any issues with round tripping decimal64 vs decimal32 in generating Arrow / Pandas compatible metadata, or is that handled by the logical / physical types in Parquet anyway?
> 
> Correct me if I'm wrong but I thought cudf only had decimal64
> 
> https://github.com/rapidsai/cudf/blob/04f90211fe95b99f4ad934f273faf87639b1f6ff/python/cudf/cudf/core/dtypes.py#L234

For now yes, but `Decimal32` is planned to be supported in the future and we want to make sure that we don't introduce changes into the Parquet metadata that aren't forward / backward compatible if possible.

**Comment by devavret** [comment]
> > > @devavret are there any issues with round tripping decimal64 vs decimal32 in generating Arrow / Pandas compatible metadata, or is that handled by the logical / physical types in Parquet anyway?
> > 
> > 
> > Correct me if I'm wrong but I thought cudf only had decimal64
> > https://github.com/rapidsai/cudf/blob/04f90211fe95b99f4ad934f273faf87639b1f6ff/python/cudf/cudf/core/dtypes.py#L234
> 
> For now yes, but `Decimal32` is planned to be supported in the future and we want to make sure that we don't introduce changes into the Parquet metadata that aren't forward compatible if possible.

Alright then yes, for that, it will be taken care of during the conversion of `Column` to `cudf::column_view`. And as long as the `dtype` class for Decimal32 has a `precision` member then no changes would be required to the bindings either.

**Comment by kkraus14** [comment]
@gpucibot merge

**Pull request merged**
