### PR TITLE
Avoid skbuild 0.17.2 which affected the cmake -DPython_LIBRARY string

### PR DESCRIPTION
**Pull request by sevagh**
We see builds are failing in cuDF, possibly because of a missing `-DPython_LIBRARY` string in the CMake command: https://github.com/rapidsai/cudf/actions/runs/4750812902/jobs/8439338686#step:11:861

This may be a result of the scikit-build release 0.17.2: https://github.com/scikit-build/scikit-build/pull/943/files

### CODE REVIEW

**Comment by sevagh** [comment]
https://github.com/scikit-build/scikit-build/pull/943

**Review by galipremsagar — APPROVED** [review]

**Review by vyasr — APPROVED** [review]

**Review by ajschmidt8 — APPROVED** [review]

**Comment by henryiii** [comment]
Is this still necessary with 0.17.5? There were several fixes, the only remaining failure is if user code had a `find_package(PythonLibs REQUIRED)` (which is incorrect; some places like manylinux don't have the Python libraries, and you should not link to them on Unix). The internal issues with this showing up & headers not being linked if missing were fixed by 0.17.4.

**Comment by vyasr** [comment]
@henryiii thanks for the ping. I'm not sure. I can test opening a new PR to remove the pinning and see if tests pass.

**Comment by vyasr** [comment]
Testing in #13424

**Pull request merged**
