### PR TITLE
Remove libcudacxx patch needed for nvcc 11.4

### PR DESCRIPTION
**Pull request by robertmaynard**
The `libcudacxx.patch` was required to fix issues with libcudacxx 1.6 and incorrect detection of the arm nvcc 11.4 compiler. 

As we move to libcudacxx 1.7 this patch is not needed, and should be removed.

### CODE REVIEW

**Review by harrism — APPROVED** [review]

**Comment by robertmaynard** [comment]
rerun tests

**Comment by galipremsagar** [comment]
rerun tests

**Comment by vyasr** [comment]
rerun tests

**Comment by galipremsagar** [comment]
rerun tests

**Comment by galipremsagar** [comment]
rerun tests

**Comment by galipremsagar** [comment]
@robertmaynard is this good to be merged?

**Comment by robertmaynard** [comment]
> @robertmaynard is this good to be merged?

Yes, just waiting on a green CI

**Comment by robertmaynard** [comment]
@gpucibot merge

**Pull request merged**
