### PR TITLE
Rename aggregate_metadata in writer to fix name collision

### LINKED ISSUE #9935: [BUG] Segfault in libcudf debug build running PARQUET_TEST
Something changed in the last week or so in 22.02 causing this failure. The segfault only happens in a libcudf DEBUG build.

```
# gtests/PARQUET_TEST 
[==========] Running 114 tests from 35 test suites.
[----------] Global test environment set-up.
[----------] 2 tests from ParquetWriterNumericTypeTest/0, where TypeParam = signed char
[ RUN      ] ParquetWriterNumericTypeTest/0.SingleColumn
Segmentation fault (core dumped)

```

### PR DESCRIPTION
**Pull request by devavret**
Fixes  #9935

### CODE REVIEW

**Comment by devavret** [comment]
rerun tests

**Comment by devavret** [comment]
rerun tests

**Comment by devavret** [comment]
rerun tests

**Review by karthikeyann — APPROVED** [review]

**Comment by vuule** [comment]
@devavret Any idea why the error happens only in debug build?

**Review by vuule — APPROVED** [review]
Maybe we should also rename the reader counterpart to `aggregate_reader_metadata`?

**Comment by devavret** [comment]
> @devavret Any idea why the error happens only in debug build?

Nope. It should've. Neither is in an anonymous namespace.

**Review by nvdbaranec — APPROVED** [review]

**Comment by devavret** [comment]
Java failure seems unrelated because I'm seeing this on other PRs as well.

**Comment by devavret** [comment]
@gpucibot merge

**Pull request merged**
