### PR TITLE
Bump typing_extensions minimum version to 4.0.0

### LINKED ISSUE #13616: [BUG] `typing_extensions` needs a pin for >= `4.0.0` for pip packages
**Describe the bug**
The Databricks runtime environments have a bunch of preinstalled pip packages including a pretty old version (3.10.x) of the typing-extensions package that predates [the addition](https://github.com/python/typing_extensions/commit/0d10fec91740924bb48cc4435df093c12a1c2368#diff-ecec88c33adb7591ee6aa88e29b62ad52ef443611cba5e0f0ecac9b5725afdbaR13) of Self (4.0.0+).   

It appears that the cudf pip package doesn't constrain the version `typing_extensions`.   A constraint of say >= 4.0.0 should be added.

**Steps/Code to reproduce bug**
 - Start a databricks runtime environment
 - Install cuDF through pip
 - Attempt to use cuDF

**Expected behavior**
cuDF can be used within Databricks through pip.

**Environment overview (please complete the following information)**
 - Environment location: Databricks
 - Method of cuDF install: pip

**Environment details**
N/A

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by shwina**
## Description
Closes #13616 

## Checklist
- [x] I am familiar with the [Contributing Guidelines](https://github.com/rapidsai/cudf/blob/HEAD/CONTRIBUTING.md).
- [x] New or existing tests cover these changes.
- [x] The documentation is up to date with these changes.

### CODE REVIEW

**Review by bdice — COMMENTED** [review]
Please update https://github.com/rapidsai/cudf/blob/12210fd7891b9735531a03bf99ce7627e182aa6e/conda/recipes/cudf/meta.yaml#L78 too. Then this is good to go.

**Review by galipremsagar — APPROVED** [review]

**Comment by vyasr** [comment]
I don't know exactly what the process is here. Since we already know we want to hotfix this for 23.06, do we target this at 23.08 then cherry-pick the commit, or do we target at 23.06 and then let the forward-merger take over @raydouglass?

**Comment by raydouglass** [comment]
> do we target this at 23.08 then cherry-pick the commit, or do we target at 23.06 and then let the forward-merger take over

You can do either. Merging to `branch-23.06` and letting the forward-merger merge into `branch-23.08` is probably easier. That said, it looks like this PR branch was branched originally from `23.08` so it needs to be rebased before merging into `23.06`. So six of one, half dozen the other in this case.

**Review by raydouglass — APPROVED** [review]

**Comment by shwina** [comment]
OK, then I'll open a new PR targeting 23.06

**Comment by bdice** [comment]
@shwina FYI, I think the cleanest way to do this (without sending tons of GitHub notifications) is to rebase locally, force push, then change the target branch.

**Comment by shwina** [comment]
Actually with @bdice's help I'm going to finally figure out how to rebase correctly.

**Review by wence- — APPROVED** [review]

**Pull request merged**
