### PR TITLE
Include missing header for usage of `get_current_device_resource()`

### LINKED ISSUE #10621: [BUG] Some cudf headers do not include `per_device_resource` when necessary.
Recently in Morpheus we encountered a bug where `get_current_device_resource` was undefined in a place we were not explicitly using it. Most public-facing libcudf APIs provide a `memory_resource*` as a default argument by calling `get_current_device_resource`, defined in `rmm/mr/per_device_resource.hpp`, however in some places this header is not included which requires the caller of libcudf APIs to include the header. If the header is not included by the caller, the symbol will remain undefined, leading to linker issues.

To fix the issue, public-facing libcudf APIs should IWYU, specifically `per_device_resource.hpp` in the case of calling `get_current_device_resource`. Likely this means adding an explicit `per_device_resource.hpp` import to all files matching the pattern `include/cudf/**/*.hpp`

### PR DESCRIPTION
**Pull request by AtlantaPepsi**
Closes #10621

As pointed out in the issue, I pretty much just included `<rmm/mr/per_device_resource.hpp>` in every public libcudf API source where `get_current_device_resource()` is invoked. 

Just for compilation it's probably not necessary to explicitly include it in _all_ these places, since many could transitively include `<rmm/mr/per_device_resource.hpp>` through other commonly used headers (like `<cudf/column/column_view.hpp>`), but I still did to IWYU

### CODE REVIEW

**Comment by GPUtester** [comment]
Can one of the admins verify this patch?

**Comment by AtlantaPepsi** [comment]
@jrhemstad @cwharris could you please check if I missed any, or any general comments would be helpful, while I check formats and tests

Also, should I add the header for NVText public APIs as well?

**Comment by PointKernel** [comment]
ok to test

**Comment by cwharris** [comment]
@AtlantaPepsi Thanks, Tim!

Would you be able to remove the forward declaration of `device_memory_resource` found in `types.hpp`? That forward declaration is the root of the problem, and why these headers have been excluded in the first place.

Also, it looks like the copyright headers still need to be updated in several of those files.

```
Copyright headers incomplete in some of the files!
  cpp/include/cudf/column/column.hpp:2 Issue: Current year not included in the copyright header
  cpp/include/cudf/dictionary/dictionary_factories.hpp:2 Issue: Current year not included in the copyright header
  cpp/include/cudf/dictionary/encode.hpp:2 Issue: Current year not included in the copyright header
  cpp/include/cudf/dictionary/update_keys.hpp:2 Issue: Current year not included in the copyright header
  cpp/include/cudf/lists/contains.hpp:2 Issue: Current year not included in the copyright header
  cpp/include/cudf/lists/count_elements.hpp:2 Issue: Current year not included in the copyright header
  cpp/include/cudf/lists/explode.hpp:2 Issue: Current year not included in the copyright header
  cpp/include/cudf/lists/extract.hpp:2 Issue: Current year not included in the copyright header
  cpp/include/cudf/lists/filling.hpp:2 Issue: Current year not included in the copyright header
  cpp/include/cudf/lists/sorting.hpp:2 Issue: Current year not included in the copyright header
  cpp/include/cudf/merge.hpp:2 Issue: Current year not included in the copyright header
  cpp/include/cudf/strings/attributes.hpp:2 Issue: Current year not included in the copyright header
  cpp/include/cudf/strings/capitalize.hpp:2 Issue: Current year not included in the copyright header
  cpp/include/cudf/strings/case.hpp:2 Issue: Current year not included in the copyright header
  cpp/include/cudf/strings/combine.hpp:2 Issue: Current year not included in the copyright header
  cpp/include/cudf/strings/convert/convert_booleans.hpp:2 Issue: Current year not included in the copyright header
  cpp/include/cudf/strings/convert/convert_fixed_point.hpp:2 Issue: Current year not included in the copyright header
  cpp/include/cudf/strings/convert/convert_floats.hpp:2 Issue: Current year not included in the copyright header
  cpp/include/cudf/strings/convert/convert_integers.hpp:2 Issue: Current year not included in the copyright header
  cpp/include/cudf/strings/convert/convert_ipv4.hpp:2 Issue: Current year not included in the copyright header
  cpp/include/cudf/strings/convert/convert_urls.hpp:2 Issue: Current year not included in the copyright header
  cpp/include/cudf/strings/find.hpp:2 Issue: Current year not included in the copyright header
  cpp/include/cudf/strings/repeat_strings.hpp:2 Issue: Current year not included in the copyright header
  cpp/include/cudf/strings/replace.hpp:2 Issue: Current year not included in the copyright header
  cpp/include/cudf/strings/split/partition.hpp:2 Issue: Current year not included in the copyright header
  cpp/include/cudf/strings/split/split.hpp:2 Issue: Current year not included in the copyright header
  cpp/include/cudf/strings/strip.hpp:2 Issue: Current year not included in the copyright header
  cpp/include/cudf/strings/substring.hpp:2 Issue: Current year not included in the copyright header
  cpp/include/cudf/strings/wrap.hpp:2 Issue: Current year not included in the copyright header
```

In addition, there is a root cause problem that would be good to fix, and that is the forward-declaration of memory_resource

**Comment by AtlantaPepsi** [comment]
@cwharris I wonder why is it that we used the forward declaration in `types.hpp` in the first place instead of explicitly including `<rmm/mr/per_device_resource.hpp>`, was there a particular reason in past development? What about the forward declaration for `rmm::device_buffer` in line 38, should we remove those and explicitly include `<rmm/device_buffer.hpp>` as well?

**Review by karthikeyann — COMMENTED** [review]
Simple `grep get_current_device_resource` revealed 153 files in cudf. I suppose, dependent files excludes many of these files. 
without this change, how is the build successful?

**Comment by AtlantaPepsi** [comment]
> Simple `grep get_current_device_resource` revealed 153 files in cudf. I suppose, dependent files excludes many of these files. without this change, how is the build successful?

@karthikeyann I believe previously the forward declaration in `types.hpp` makes all under `cpp/include/cudf/` compile, plus the actual definition in `<rmm/mr/device/per_device_resource.hpp>`most likely already included somewhere else in the build process, so it ran just fine. All other tests, source code or even JNI at least include one of the header files when used

**Comment by vyasr** [comment]
> @cwharris I wonder why is it that we used the forward declaration in types.hpp in the first place instead of explicitly including <rmm/mr/per_device_resource.hpp>, was there a particular reason in past development? What about the forward declaration for rmm::device_buffer in line 38, should we remove those and explicitly include <rmm/device_buffer.hpp> as well?

@AtlantaPepsi the usual reason for forward declarations is reducing build time. The (early steps of) compiling are basically text processing, and a `#include` is a literal textual inclusion of the included file, so when you include headers into many files it increases compile times. If you include headers into a file like types.hpp, which itself is a header file included in almost every part of libcudf, it can theoretically increase compile times a lot. That being said, libcudf is extremely slow to compile for other reasons that are much more expensive than includes, and includes are much easier to work with (less code that we need to write and more self-documenting), so we generally prefer includes to having to propagate forward declarations all over the place.

**Comment by bdice** [comment]
I agree with @vyasr's comment here. We should prefer `#include` (IWYU) over forward declarations, but not if it costs a significant amount of build time. We should gather some data: measure a clean build time without ccache before (forward declarations) and after (includes). Before measuring, be sure to merge in the latest `branch-22.08` to this PR and compare to the latest `branch-22.08`.

**Comment by GregoryKimball** [comment]
Thanks @bdice for your suggestion. I agree that measuring a clean build time difference with a base `branch-22.08` is the next step. Based on our [gpuCI build metrics report](https://gpuci.gpuopenanalytics.com/job/rapidsai/job/gpuci/job/cudf/job/prb/job/cudf-cpu-cuda-build/CUDA=11.5/10257/Build_20Metrics_20Report/) the change looks promising. 

`join/*` compile time is in the normal range:
image

Also `groupby/*` looks promising:
image

**Comment by vyasr** [comment]
@GregoryKimball I'm not sure what to take from the plots here. The highlighted sha is not the head of this branch, is it? Are you aiming to compare the values in this build report to the current main branch?

I would be curious to hear @davidwendt's opinion here, but in my experience our extensive use of templating is responsible for >90% of our build time and forward declarations aren't likely to move the needle more than a tiny bit. I think we're probably better off moving forward with IWYU for now so that we at least remove all implicit dependencies, then doing a more thorough analysis of the impact of forward declarations to see if we can make more targeted changes to improve our build times (e.g. we choose the 10 most commonly used headers and only use forward declarations in those).

**Comment by bdice** [comment]
> Headers should not be including other headers as a service -- they should include only what the header itself needs.

I agree. This PR aligns with that guidance, as far as I can tell. The default parameters of an API are declared in the header, and we have many default parameters that are memory resources coming from the header that is being included here.

> It gets fuzzy for `rmm` since it is ours but also not.

This is a good point. I lean towards treating `rmm` like `thrust` and not forward-declaring its contents in our headers. We should strive to treat components of RAPIDS independently wherever possible.

**Comment by davidwendt** [comment]
> Should a header (say `search.hpp`) that needs some subset of types to be able to declare its APIs just be forward declaring those types rather than just including `types.hpp`? In that (obviously extreme) case, we'd end up with every header in libcudf having forward declarations, often of the same things.

I would be in favor of this. I feel this is the same level of burden as IWYU. Many headers would have the same set includes or the same set of forward declarations. Most of our internal headers are template based or device code and so it may be difficult to show significant compile time improvement.

Besides compile time there is the matter of a someone building against libcudf. I recently tried building some libcudf examples and got several warnings in headers that I was not including (e.g. arrow declarations). I think we could do better with this in at least our public headers.

**Comment by davidwendt** [comment]
> Except that you'd be making a one-to-many replacement (one header to an arbitrarily large number of forward declarations). That's the bit that I find cumbersome.

I'm not advocating all or nothing here. Just that we be smart and thoughtful.

**Comment by vyasr** [comment]
> I'm not advocating all or nothing here. Just that we be smart and thoughtful.

I am on board with that.

@AtlantaPepsi also sorry, this thread has diverged a bit from the original goal of your PR! I think that resolving `get_current_device_resource` issues with an include is perfectly fine for now. We may want to reconsider using forward declarations for this kind of thing in the future, but I don't think we need to block your change. Let's just make sure in this PR that we fix cases that are getting this function implicitly rather than via an explicit include.

**Comment by AtlantaPepsi** [comment]
@vyasr no please don't be, I very much enjoy the ongoing discussion and am learning quite a bit. I think this PR itself already handled all cases of explicit includes, but don't mind it if we decide to stick with forward declaration now or anytime in future

**Review by bdice — APPROVED** [review]
The changes in this PR look good. Thank you to @jrhemstad for the insight that a forward declaration is insufficient here, I agree with your assessment and think this should be merged.

**Review by karthikeyann — APPROVED** [review]

**Comment by davidwendt** [comment]
> What about the forward declaration for `rmm::device_buffer` in line 38, should we remove those and explicitly include `<rmm/device_buffer.hpp>` as well?

I'd like to consider this as well here.  Or perhaps this PR is too big already.

**Comment by bdice** [comment]
> > What about the forward declaration for `rmm::device_buffer` in line 38, should we remove those and explicitly include `<rmm/device_buffer.hpp>` as well?
> 
> I'd like to consider this as well here. Or perhaps this PR is too big already.

My vote is for a second PR. @davidwendt if that sounds fine to you, we can merge this.

**Review by davidwendt — APPROVED** [review]

**Comment by bdice** [comment]
@gpucibot merge

**Pull request merged**
