### PR TITLE
Fix union operation in `_is_supported()`

### PR DESCRIPTION
**Pull request by charlesbluca**
Changes the `_global_set` union operation happening in `_is_supported()` to

```python
_global_set = _global_set.union(set(arg[col]))
```

Since `set.union()` doesn't actually modify the set in place. Before this PR, passing something like `{"a": ["unsupported_agg"]}` into `_is_supported()` would always return `True`.

cc @rjzamora

### CODE REVIEW

**Review by rjzamora — APPROVED** [review]
Thanks @charlesbluca !  Looks good.

I would normally ask you to add a test that includes a groupby test that is not supported by the optimized code path.  However, it looks like any aggregation that is **not** supported by that path is broken in upstream dask anyway...

**Comment by charlesbluca** [comment]
Thanks @rjzamora! Would a good compromise be to add some tests for `_is_supported()` alone to make sure it returns what we're expecting?

**Comment by rjzamora** [comment]
>Thanks @rjzamora! Would a good compromise be to add some tests for _is_supported() alone to make sure it returns what we're expecting?

Yeah - Although I'd rather not add a (possibly fragile) test for a private function, it's probably better than no test coverage at all.  Maybe just test that including a completely made-up aggregation name will return `False` :)

**Comment by charlesbluca** [comment]
Sure! I added a simple test for returning `False`. If needed, I can extend it / add another to check for `True`.

**Comment by charlesbluca** [comment]
Also I think I need a category label for the rest of the checks to run

**Comment by kkraus14** [comment]
> Also I think I need a category label for the rest of the checks to run

I think gpuci is just currently down due to a network outage.

**Comment by charlesbluca** [comment]
rerun tests

**Comment by charlesbluca** [comment]
Is gpuCI up and running for cuDF again? Reran the tests yesterday and looks like they might have timed out

**Comment by kkraus14** [comment]
rerun tests

**Review by kkraus14 — APPROVED** [review]

**Comment by kkraus14** [comment]
@gpucibot merge

**Pull request merged**
