### PR TITLE
Dynamically set version in RAPIDS doc builds

### PR DESCRIPTION
**Pull request by jakirkham**
Following up on issue ( https://github.com/rapidsai/build-planning/issues/15 ), drop RAPIDS version hard-coding in doc builds.

### CODE REVIEW

**Review by bdice — DISMISSED** [review]
Please delete this line as well: https://github.com/rapidsai/cudf/blob/4ce99af7438d38e91ee2540336a278ade2fffd79/ci/release/update-version.sh#L111

Any time a hard-coded version is adjusted, the `update-version.sh` script should be checked.

**Review by bdice — APPROVED** [review]

**Review by raydouglass — APPROVED** [review]

**Comment by ajschmidt8** [comment]
This broke our docs uploads. `rapids-generate-version` generates strings like `24.04.00a476`, which is different from the original `24.04` string that was hardcoded.

Our documentation bucket now contains a list of folders that looks like this:

```
23.02
23.04
23.06
23.08
23.10
23.12
24.02
24.04.00a476
24.04.00a485
24.04.00a486
24.04.00a488
24.04.00a489
24.04.00a491
24.04.00a493
24.04.00a502
24.04.00a503
24.04.00a504
24.04.00a506
24.04.00a508
24.04.00a512
24.04.00a513
24.04.00a516
24.04.00a519
24.04.00a524
24.04.00a526
24.04.00a530
24.04.00a531
24.04.00a532
24.04.00a533
24.04.00a543
24.04.00a544
24.04.00a546
24.04.00a550
24.04.00a551
24.04.00a553
24.04.00a554
24.04.00a558
24.04.00a559
24.04

```

cc: @raydouglass

**Comment by jakirkham** [comment]
Thanks AJ! 🙏

Addressing with PR: https://github.com/rapidsai/cudf/pull/15291

**Pull request merged**
