### PR TITLE
add mvn wrapper for ease of building java bindings [skip ci]

### PR DESCRIPTION
**Pull request by razajafri**
Adding maven wrapper so the end-user doesn't have to download the correct version of maven that we support. We should update this when/if we move to a different version of maven

### CODE REVIEW

**Comment by revans2** [comment]
So where exactly did this code come from?  Copying code, especially a binary jar from another project is problematic without traceability to know if there are security issues etc.

**Comment by razajafri** [comment]
This is from maven plugin io.takari released under apache v2.0 license. It has been approved to be included as a part of the apache maven project and is set to be released along with 3.7.0

Github link: https://github.com/takari/maven-wrapper
License: https://github.com/takari/maven-wrapper/blob/master/LICENSE.txt

**Comment by harrism** [comment]
Please remember to add PRs to projects : 
image

Otherwise they are orphans and may get missed.

What is the status of this PR for 0.13?

**Comment by revans2** [comment]
It is a lower priority and we didn't find time to get it in. It should be moved to 0.14.

**Comment by razajafri** [comment]
@revans2 @jlowe 

What do we want to do about this PR?

**Comment by harrism** [comment]
@razajafri please don't force push to git branches associated with a PR. It disassociates any review comments with the code.

**Comment by revans2** [comment]
@razajafri if you really want to put this in that is fine, but I just don't see a lot of value in it.  Installing maven is not that much harder than installing java.  We also don't have any hard requirements on a specific version of maven so it feels like we would be adding in code that no one will use, but I could be wrong.  If others feel differently I am happy to let it in.

**Comment by razajafri** [comment]
Thank you @harrism. I don't generally do that here but I slipped. 

@revans2 I think it's useful for people like the other day I was talking to a cpp dev who was trying to build our bindings. In the end, we didn't have to but I can imagine a situation like that. But I respect your opinion and I am not married to having this checked in, at the end of the day what matters is what's useful to the project.

@jlowe your take?

**Comment by revans2** [comment]
@razajafri that is a good point.  I would prefer to have java + maven included in the conda package but after we couldn't even get basic build/test for CI I don't think that is going to happen, so I am +1 on this.

**Comment by jlowe** [comment]
I'm leaning towards @revans2's side on this.  Installing Maven is not a large burden.  Users don't have to download a very specific version, the latest will suffice.  Most developer environments have turnkey Maven packages that would be easier to maintain for security fixes than a custom install.  I'm also not a fan of raw binaries without corresponding source in git repos.

**Comment by revans2** [comment]
So then should we just add instructions to the README.md on how to install maven through conda, because all of the C++ devs should have conda installed, and it should be simple for them if they don't already have an env with it in there.

**Comment by jlowe** [comment]
> add instructions to the README.md on how to install maven through conda

IMO this makes more sense than the Maven wrapper.  Unless the wrapper installs a JDK as well, it doesn't really solve the problem of getting Maven to run for C++-only developers.

People building from source are required to have conda setup and are used to updating their conda environment via the yml files.  It would be nice to provide a yml file to update a conda environment with openjdk and Maven, both of which appear to be available via conda.

**Comment by harrism** [comment]
Then should we just close this PR?

**Comment by razajafri** [comment]
Yes. I will open another PR with the suggested changes

**Pull request closed without merging**
