### PR TITLE
DO NOT MERGE: testing Remove mr

### PR DESCRIPTION
**Pull request by karthikeyann**
## Description
testing remove mr with compile options

### CODE REVIEW

**Comment by karthikeyann** [comment]
STRINGS_TEST (Failed) on all machines.

```
[ RUN      ] StringsConvertTest.FixedPointStringConversionOperator
/opt/conda/conda-bld/work/cpp/tests/strings/fixed_point_tests.cpp:328: Failure
Expected equality of these values:
  static_cast<std::string>(x)
    Which is: "-1.0000000000"
  "17014118346046923173168730371.5884105727"

[  FAILED  ] StringsConvertTest.FixedPointStringConversionOperator (0 ms)
```

**Comment by bdice** [comment]
FWIW, `17014118346046923173168730371.5884105727` is the value `2^127 - 1` shifted by 10 decimal places. Probably has to do with decimal128 representation somewhere.

**Pull request closed without merging**
