### PR TITLE
Turn on CI for `clang-tidy`

### PR DESCRIPTION
**Pull request by codereport**
This is a follow up to https://github.com/rapidsai/cudf/pull/9860

To do list: 
* [ ] Disable `clang-diagnostic-errors/warnings`
* [ ] Fix include files being skipped
* [ ] Set up CI script
* [ ] Clean up python script

### CODE REVIEW

**Review by bdice — APPROVED** [review]
LGTM, with two minor Python improvements.

**Comment by codereport** [comment]
rerun tests

**Comment by codereport** [comment]
rerun tests

**Comment by codereport** [comment]
rerun tests

**Pull request closed without merging**
