### PR TITLE
Fix Debug-mode failing Arrow test

### LINKED ISSUE #17153: [BUG] INTEROP_TEST fails on a libcudf debug build at ToArrowTest.NestedList
The following assert occurs in the `ToArrowTest.NestedList` test in `INTEROP_TEST`:

```
$ gtests/INTEROP_TEST --gtest_filter=ToArrowTest.NestedList
Note: Google Test filter = ToArrowTest.NestedList
[==========] Running 1 test from 1 test suite.
[----------] Global test environment set-up.
[----------] 1 test from ToArrowTest
[ RUN      ] ToArrowTest.NestedList
/cudf/cpp/build/_deps/arrow-src/cpp/src/arrow/array/array_nested.cc:468:  Check failed: self->list_type_->value_type()->Equals(data->child_data[0]->type) 
Aborted (core dumped)

```

This only occurs in a debug build likely because the `assert` is compiled out in a release build.

### PR DESCRIPTION
**Pull request by zeroshade**
## Description
Fixes #17153 by fixing the appropriate element nullability data types

## Checklist
- [x] I am familiar with the [Contributing Guidelines](https://github.com/rapidsai/cudf/blob/HEAD/CONTRIBUTING.md).
- [x] New or existing tests cover these changes.
- [x] The documentation is up to date with these changes.

### CODE REVIEW

**Comment by davidwendt** [comment]
Thanks for this fix @zeroshade 
We are currently in burndown for 24.12 and since this is just fixing tests we probably should just target this PR for `branch-25.02`

**Comment by zeroshade** [comment]
@davidwendt updated this to be based on `branch-25.02` instead.

**Review by PointKernel — APPROVED** [review]
LGTM. Thanks for the fix.

**Review by davidwendt — APPROVED** [review]
Verified this fixes #17153

**Pull request merged**
