### PR TITLE
[REVIEW] Removed deprecated gdf_concat function

### PR DESCRIPTION
**Pull request by jrhemstad**
Closes https://github.com/rapidsai/cudf/issues/526

The `gdf_concat` function should no longer be used as it is superseded by `gdf_column_concat`.

As such, this PR removes it to reduce compile and testing times.

### CODE REVIEW

**Comment by jrhemstad** [comment]
@kkraus14 as far as I could tell, this isn't being used on the Python side, but would appreciate if you could verify.

**Comment by kkraus14** [comment]
> @kkraus14 as far as I could tell, this isn't being used on the Python side, but would appreciate if you could verify.

It is not, thanks!

**Comment by raydouglass** [comment]
rerun tests

**Comment by kkraus14** [comment]
> I LOVE this PR. No new code to review. I assume you verified that none of the cuDF python code uses this?

Yes I did and we're clear 😄

**Comment by kkraus14** [comment]
Just need confirmation from @williamBlazing to make sure they're not using the function

**Pull request merged**
