### PR TITLE
Apply Type Metadata to Column Children

### LINKED ISSUE #9177: [FEA] Slice from nested `struct` type column `to_arrow` does not retain inner level field names
**Describe the bug**
Given a slice of nested struct type column, the inner field name is not retained when converting it to arrow.

**Steps/Code to reproduce bug**
```python
>>> import cudf 
>>> s = cudf.Series([
...     {"a": {"b": 42, "c": "abc"}},
...     {"a": {"b": 42, "c": "hello world"}},
... ])
>>> s[0:1].to_arrow().type
StructType(struct<a: struct<0: int64, 1: string>>)
```

**Expected behavior**
Retain inner field name
```python
StructType(struct<a: struct<b: int64, c: string>>)
```

**Environment overview (please complete the following information)**
 - Environment location: rapids-compose
 - Method of cuDF install: rapids-compose

**Environment details**
<details><summary>Click here to see environment details</summary><pre>
     
     **git***
     commit 0d9f36328edfe159b1cc81941ed2d1378b6bd2c1 (HEAD -> branch-21.10, upstream/branch-21.10)
     Author: GALI PREM SAGAR <sagarprem75@gmail.com>
     Date:   Fri Sep 3 08:31:25 2021 -0500
     
     `dask_cudf` dispatch registering cleanup (#9160)
     
     This PR does a cleanup of try/except blocks around dask dispatch objects which were introduced to maintain backward compatibility. This PR removes all such `try/except` blocks that are present in `2021.6.0` version of dask.
     
     Authors:
     - GALI PREM SAGAR (https://github.com/galipremsagar)
     
     Approvers:
     - Richard (Rick) Zamora (https://github.com/rjzamora)
     
     URL: https://github.com/rapidsai/cudf/pull/9160
     **git submodules***
     
     ***OS Information***
     DISTRIB_ID=Ubuntu
     DISTRIB_RELEASE=18.04
     DISTRIB_CODENAME=bionic
     DISTRIB_DESCRIPTION="Ubuntu 18.04.5 LTS"
     NAME="Ubuntu"
     VERSION="18.04.5 LTS (Bionic Beaver)"
     ID=ubuntu
     ID_LIKE=debian
     PRETTY_NAME="Ubuntu 18.04.5 LTS"
     VERSION_ID="18.04"
     HOME_URL="https://www.ubuntu.com/"
     SUPPORT_URL="https://help.ubuntu.com/"
     BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
     PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
     VERSION_CODENAME=bionic
     UBUNTU_CODENAME=bionic
     Linux dgx06 4.15.0-76-generic #86-Ubuntu SMP Fri Jan 17 17:24:28 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
     
     ***GPU Information***
     Fri Sep  3 13:12:51 2021
     +-----------------------------------------------------------------------------+
     | NVIDIA-SMI 460.39       Driver Version: 460.39       CUDA Version: 11.2     |
     |-------------------------------+----------------------+----------------------+
     | GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
     | Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
     |                               |                      |               MIG M. |
     |===============================+======================+======================|
     |   0  Tesla V100-SXM2...  On   | 00000000:85:00.0 Off |                    0 |
     | N/A   32C    P0    56W / 300W |   1299MiB / 32510MiB |      0%      Default |
     |                               |                      |                  N/A |
     +-------------------------------+----------------------+----------------------+
     
     +-----------------------------------------------------------------------------+
     | Processes:                                                                  |
     |  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
     |        ID   ID                                                   Usage      |
     |=============================================================================|
     +-----------------------------------------------------------------------------+
     
     ***CPU***
     Architecture:        x86_64
     CPU op-mode(s):      32-bit, 64-bit
     Byte Order:          Little Endian
     CPU(s):              80
     On-line CPU(s) list: 0-79
     Thread(s) per core:  2
     Core(s) per socket:  20
     Socket(s):           2
     NUMA node(s):        2
     Vendor ID:           GenuineIntel
     CPU family:          6
     Model:               79
     Model name:          Intel(R) Xeon(R) CPU E5-2698 v4 @ 2.20GHz
     Stepping:            1
     CPU MHz:             2972.694
     CPU max MHz:         3600.0000
     CPU min MHz:         1200.0000
     BogoMIPS:            4389.88
     Virtualization:      VT-x
     L1d cache:           32K
     L1i cache:           32K
     L2 cache:            256K
     L3 cache:            51200K
     NUMA node0 CPU(s):   0-19,40-59
     NUMA node1 CPU(s):   20-39,60-79
     Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 cdp_l3 invpcid_single pti intel_ppin ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm rdt_a rdseed adx smap intel_pt xsaveopt cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm ida arat pln pts md_clear flush_l1d
     
     ***CMake***
     /raid/wangm/dev/rapids/compose/etc/conda/cuda_11.2/envs/rapids/bin/cmake
     cmake version 3.21.2
     
     CMake suite maintained and supported by Kitware (kitware.com/cmake).
     
     ***g++***
     /usr/local/bin/g++
     g++ (Ubuntu 9.4.0-1ubuntu1~18.04) 9.4.0
     Copyright (C) 2019 Free Software Foundation, Inc.
     This is free software; see the source for copying conditions.  There is NO
     warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
     
     
     ***nvcc***
     /usr/local/bin/nvcc
     nvcc: NVIDIA (R) Cuda compiler driver
     Copyright (c) 2005-2021 NVIDIA Corporation
     Built on Sun_Feb_14_21:12:58_PST_2021
     Cuda compilation tools, release 11.2, V11.2.152
     Build cuda_11.2.r11.2/compiler.29618528_0
     
     ***Python***
     /raid/wangm/dev/rapids/compose/etc/conda/cuda_11.2/envs/rapids/bin/python
     Python 3.7.10
     
     ***Environment Variables***
     PATH                            : /raid/wangm/dev/rapids/compose/etc/conda/cuda_11.2/envs/rapids/bin:/raid/wangm/dev/rapids/compose/etc/conda/cuda_11.2/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/cuda/bin
     LD_LIBRARY_PATH                 : /raid/wangm/dev/rapids/compose/etc/conda/cuda_11.2/envs/rapids/lib:/raid/wangm/dev/rapids/compose/etc/conda/cuda_11.2/lib:/usr/lib/x86_64-linux-gnu:/usr/lib/i386-linux-gnu:/usr/local/nvidia/lib:/usr/local/nvidia/lib64:/usr/local/nvidia/lib:/usr/local/nvidia/lib64:/usr/local/cuda/lib64:/usr/local/lib:/raid/wangm/dev/rapids/rmm/build/release:/raid/wangm/dev/rapids/cudf/cpp/build/release:/raid/wangm/dev/rapids/raft/cpp/build/release:/raid/wangm/dev/rapids/cuml/cpp/build/release:/raid/wangm/dev/rapids/cugraph/cpp/build/release:/raid/wangm/dev/rapids/cuspatial/cpp/build/release
     NUMBAPRO_NVVM                   :
     NUMBAPRO_LIBDEVICE              :
     CONDA_PREFIX                    : /raid/wangm/dev/rapids/compose/etc/conda/cuda_11.2/envs/rapids
     PYTHON_PATH                     :
     
     ***conda packages***
     /raid/wangm/dev/rapids/compose/etc/conda/cuda_11.2/bin/conda
     # packages in environment at /raid/wangm/dev/rapids/compose/etc/conda/cuda_11.2/envs/rapids:
     #
     # Name                    Version                   Build  Channel
     _libgcc_mutex             0.1                 conda_forge    conda-forge
     _openmp_mutex             4.5                       1_gnu    conda-forge
     _pytorch_select           0.1                       cpu_0
     abseil-cpp                20210324.2           h9c3ff4c_0    conda-forge
     alabaster                 0.7.12                     py_0    conda-forge
     apipkg                    1.5                        py_0    conda-forge
     appdirs                   1.4.4              pyh9f0ad1d_0    conda-forge
     argon2-cffi               20.1.0           py37h8f50634_2    conda-forge
     arrow-cpp                 5.0.0           py37h9a83b69_3_cuda    conda-forge
     arrow-cpp-proc            3.0.0                      cuda    conda-forge
     async_generator           1.10                       py_0    conda-forge
     attrs                     20.3.0             pyhd3deb0d_0    conda-forge
     aws-c-cal                 0.5.11               h95a6274_0    conda-forge
     aws-c-common              0.6.2                h7f98852_0    conda-forge
     aws-c-event-stream        0.2.7               h3541f99_13    conda-forge
     aws-c-io                  0.10.5               hfb6a706_0    conda-forge
     aws-checksums             0.1.11               ha31a3da_7    conda-forge
     aws-sdk-cpp               1.8.186              hb4091e7_3    conda-forge
     babel                     2.9.0              pyhd3deb0d_0    conda-forge
     backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
     backports                 1.0                        py_2    conda-forge
     backports.functools_lru_cache 1.6.4              pyhd8ed1ab_0    conda-forge
     beautifulsoup4            4.9.3              pyhb0f4dca_0    conda-forge
     binutils_impl_linux-64    2.35.1               h193b22a_2    conda-forge
     black                     19.10b0                  py37_0    conda-forge
     blas                      1.0                         mkl
     bleach                    3.3.0              pyh44b312d_0    conda-forge
     bokeh                     2.3.1            py37h89c1867_0    conda-forge
     boost-cpp                 1.76.0               h312852a_1    conda-forge
     brotli                    1.0.9                h9c3ff4c_4    conda-forge
     brotlipy                  0.7.0           py37hb5d75c8_1001    conda-forge
     bzip2                     1.0.8                h7f98852_4    conda-forge
     c-ares                    1.17.2               h7f98852_0    conda-forge
     ca-certificates           2021.4.13            h06a4308_1
     cachetools                4.2.2              pyhd8ed1ab_0    conda-forge
     certifi                   2020.12.5        py37h89c1867_1    conda-forge
     cffi                      1.14.6           py37hc58025e_0    conda-forge
     cfgv                      3.2.0                      py_0    conda-forge
     chardet                   4.0.0            py37h89c1867_1    conda-forge
     clang                     11.0.0               ha770c72_2    conda-forge
     clang-11                  11.0.0          default_ha5c780c_2    conda-forge
     clang-tools               11.0.0          default_ha5c780c_2    conda-forge
     clangxx                   11.0.0          default_ha5c780c_2    conda-forge
     click                     7.1.2              pyh9f0ad1d_0    conda-forge
     cloudpickle               1.6.0                      py_0    conda-forge
     cmake                     3.21.2               h8897547_0    conda-forge
     cmake-format              0.6.11             pyh9f0ad1d_0    conda-forge
     cmake_setuptools          0.1.3                      py_0    rapidsai
     colorama                  0.4.4              pyh9f0ad1d_0    conda-forge
     commonmark                0.9.1                      py_0    conda-forge
     cryptography              3.4.7            py37h5d9358c_0    conda-forge
     cudatoolkit               11.2.72              h2bc3f7f_0    nvidia
     cudnn                     8.2.1.32             h86fa8c9_0    conda-forge
     cupy                      9.4.0            py37hf4b2161_0    conda-forge
     cutensor                  1.3.1.3              h97a9cb7_2    conda-forge
     cycler                    0.10.0                     py_2    conda-forge
     cython                    0.29.24          py37hcd2ae1e_0    conda-forge
     cytoolz                   0.11.0           py37h5e8e339_3    conda-forge
     dask                      2021.6.0+14.g1d0262c3          pypi_0    pypi
     dask-cuda                 21.10.00a210827         py37_34    rapidsai-nightly
     dask-glm                  0.2.0                      py_1    conda-forge
     dask-ml                   1.9.0              pyhd8ed1ab_0    conda-forge
     dataclasses               0.8                pyhc8e2a94_1    conda-forge
     decorator                 5.0.7              pyhd8ed1ab_0    conda-forge
     defusedxml                0.7.1              pyhd8ed1ab_0    conda-forge
     distlib                   0.3.1              pyh9f0ad1d_0    conda-forge
     distributed               2021.6.0+7.gddec3c9c          pypi_0    pypi
     dlpack                    0.5                  h9c3ff4c_0    conda-forge
     docutils                  0.16             py37h89c1867_3    conda-forge
     double-conversion         3.1.5                h9c3ff4c_2    conda-forge
     doxygen                   1.9.1                hb166930_1    conda-forge
     editdistance-s            1.0.0            py37h2527ec5_1    conda-forge
     entrypoints               0.3             py37hc8dfbb8_1002    conda-forge
     execnet                   1.8.0              pyh44b312d_0    conda-forge
     expat                     2.4.1                h9c3ff4c_0    conda-forge
     faiss-proc                1.0.0                      cuda    rapidsai
     fastavro                  1.4.4            py37h5e8e339_0    conda-forge
     fastrlock                 0.6              py37hcd2ae1e_0    conda-forge
     filelock                  3.0.12             pyh9f0ad1d_0    conda-forge
     flake8                    3.8.3                      py_1    conda-forge
     flatbuffers               2.0.0                h9c3ff4c_0    conda-forge
     freetype                  2.10.4               h0708190_1    conda-forge
     fsspec                    2021.7.0           pyhd8ed1ab_0    conda-forge
     future                    0.18.2           py37h89c1867_3    conda-forge
     gcc_impl_linux-64         9.3.0               h70c0ae5_19    conda-forge
     gflags                    2.2.2             he1b5a44_1004    conda-forge
     glog                      0.5.0                h48cff8f_0    conda-forge
     gmp                       6.2.1                h58526e2_0    conda-forge
     grpc-cpp                  1.39.1               hf1f433d_0    conda-forge
     hdbscan                   0.8.27           py37h902c9e0_0    conda-forge
     heapdict                  1.0.1                      py_0    conda-forge
     huggingface_hub           0.0.8              pyhd8ed1ab_0    conda-forge
     hypothesis                6.17.2             pyhd8ed1ab_0    conda-forge
     icu                       68.1                 h58526e2_0    conda-forge
     identify                  2.2.3              pyhd8ed1ab_0    conda-forge
     idna                      2.10               pyh9f0ad1d_0    conda-forge
     imagesize                 1.2.0                      py_0    conda-forge
     importlib-metadata        3.10.1           py37h89c1867_0    conda-forge
     importlib_metadata        3.10.1               hd8ed1ab_0    conda-forge
     iniconfig                 1.1.1              pyh9f0ad1d_0    conda-forge
     intel-openmp              2019.4                      243
     ipykernel                 5.5.3            py37h085eea5_0    conda-forge
     ipython                   7.27.0           py37h6531663_0    conda-forge
     ipython_genutils          0.2.0                      py_1    conda-forge
     isort                     5.6.4                      py_0    conda-forge
     jbig                      2.1               h7f98852_2003    conda-forge
     jedi                      0.18.0           py37h89c1867_2    conda-forge
     jinja2                    2.11.3             pyh44b312d_0    conda-forge
     joblib                    1.0.1              pyhd8ed1ab_0    conda-forge
     jpeg                      9d                   h516909a_0    conda-forge
     jsonschema                3.2.0            py37hc8dfbb8_1    conda-forge
     jupyter_client            6.1.12             pyhd8ed1ab_0    conda-forge
     jupyter_core              4.7.1            py37h89c1867_0    conda-forge
     jupyterlab_pygments       0.1.2              pyh9f0ad1d_0    conda-forge
     kernel-headers_linux-64   2.6.32              h77966d4_13    conda-forge
     kiwisolver                1.3.2            py37h2527ec5_0    conda-forge
     krb5                      1.19.1               hcc1bbae_0    conda-forge
     lcms2                     2.12                 hddcbb42_0    conda-forge
     ld_impl_linux-64          2.35.1               hea4e1c9_2    conda-forge
     lerc                      2.2.1                h9c3ff4c_0    conda-forge
     libblas                   3.9.0           1_h6e990d7_netlib    conda-forge
     libbrotlicommon           1.0.9                h7f98852_5    conda-forge
     libbrotlidec              1.0.9                h7f98852_5    conda-forge
     libbrotlienc              1.0.9                h7f98852_5    conda-forge
     libcblas                  3.9.0           3_h893e4fe_netlib    conda-forge
     libclang-cpp11            11.0.0          default_ha5c780c_2    conda-forge
     libcumlprims              21.10.00a210826 cuda11.2_ga512fc5_5    rapidsai-nightly
     libcurl                   7.78.0               h2574ce0_0    conda-forge
     libdeflate                1.7                  h7f98852_5    conda-forge
     libedit                   3.1.20210216         h27cfd23_1
     libev                     4.33                 h516909a_1    conda-forge
     libevent                  2.1.10               hcdb4288_3    conda-forge
     libfaiss                  1.7.0           cuda112h5bea7ad_8_cuda    conda-forge
     libffi                    3.3                  h58526e2_2    conda-forge
     libgcc-devel_linux-64     9.3.0               h7864c58_19    conda-forge
     libgcc-ng                 11.1.0               hc902ee8_8    conda-forge
     libgfortran-ng            7.5.0               h14aa051_19    conda-forge
     libgfortran4              7.5.0               h14aa051_19    conda-forge
     libgomp                   11.1.0               hc902ee8_8    conda-forge
     libhwloc                  2.3.0                h5e5b7d1_1    conda-forge
     libiconv                  1.16                 h516909a_0    conda-forge
     liblapack                 3.9.0           3_h893e4fe_netlib    conda-forge
     libllvm10                 10.0.1               he513fc3_3    conda-forge
     libllvm11                 11.0.1               hf817b99_0    conda-forge
     libllvm8                  8.0.1                hc9558a2_0    conda-forge
     libmklml                  2019.0.5                      0
     libnghttp2                1.43.0               h812cca2_0    conda-forge
     libopenblas               0.3.12          pthreads_hb3c22a3_1    conda-forge
     libpng                    1.6.37               hed695b0_2    conda-forge
     libprotobuf               3.16.0               h780b84a_0    conda-forge
     libsodium                 1.0.18               h516909a_1    conda-forge
     libssh2                   1.9.0                ha56f1ee_6    conda-forge
     libstdcxx-ng              11.1.0               h56837e0_8    conda-forge
     libthrift                 0.14.2               he6d91bd_1    conda-forge
     libtiff                   4.3.0                hf544144_1    conda-forge
     libutf8proc               2.6.1                h7f98852_0    conda-forge
     libuv                     1.41.0               h7f98852_0    conda-forge
     libwebp-base              1.2.0                h7f98852_2    conda-forge
     libxml2                   2.9.12               h72842e0_0    conda-forge
     llvmlite                  0.36.0           py37h9d7f4d0_0    conda-forge
     locket                    0.2.1            py37h06a4308_1
     lz4-c                     1.9.3                h9c3ff4c_0    conda-forge
     markdown                  3.3.4              pyhd8ed1ab_0    conda-forge
     markupsafe                1.1.1            py37h5e8e339_3    conda-forge
     matplotlib-base           3.4.3            py37h1058ff1_0    conda-forge
     matplotlib-inline         0.1.2              pyhd8ed1ab_2    conda-forge
     mccabe                    0.6.1                      py_1    conda-forge
     mimesis                   4.0.0              pyh9f0ad1d_0    conda-forge
     mistune                   0.8.4           py37h5e8e339_1003    conda-forge
     mkl                       2020.2                      256
     more-itertools            8.7.0              pyhd8ed1ab_0    conda-forge
     msgpack-python            1.0.2            py37h2527ec5_1    conda-forge
     multipledispatch          0.6.0                      py_0    conda-forge
     mypy                      0.782                      py_0    conda-forge
     mypy_extensions           0.4.3            py37h89c1867_3    conda-forge
     nbclient                  0.5.3              pyhd8ed1ab_0    conda-forge
     nbconvert                 6.0.7            py37h89c1867_3    conda-forge
     nbformat                  5.1.3              pyhd8ed1ab_0    conda-forge
     nbsphinx                  0.8.7              pyhd8ed1ab_0    conda-forge
     nccl                      2.10.3.1             hdc17891_0    conda-forge
     ncurses                   6.2                  h58526e2_4    conda-forge
     nest-asyncio              1.5.1              pyhd8ed1ab_0    conda-forge
     ninja                     1.10.2               h4bd325d_0    conda-forge
     nltk                      3.6.2              pyhd8ed1ab_0    conda-forge
     nodeenv                   1.6.0              pyhd8ed1ab_0    conda-forge
     notebook                  6.4.3              pyha770c72_0    conda-forge
     numba                     0.53.1           py37hb11d6e1_1    conda-forge
     numpy                     1.21.2           py37h31617e3_0    conda-forge
     numpydoc                  1.1.0                      py_1    conda-forge
     nvtx                      0.2.3            py37h5e8e339_0    conda-forge
     olefile                   0.46               pyh9f0ad1d_1    conda-forge
     openssl                   1.1.1k               h7f98852_0    conda-forge
     orc                       1.6.10               h58a87f1_0    conda-forge
     packaging                 21.0               pyhd8ed1ab_0    conda-forge
     pandas                    1.2.5            py37h219a48f_0    conda-forge
     pandoc                    1.19.2.1             hea2e7c5_1
     pandocfilters             1.4.3            py37h06a4308_1
     parquet-cpp               1.5.1                         1    conda-forge
     parso                     0.8.2              pyhd8ed1ab_0    conda-forge
     partd                     1.2.0              pyhd8ed1ab_0    conda-forge
     pathspec                  0.8.1              pyhd3deb0d_0    conda-forge
     patsy                     0.5.1                      py_0    conda-forge
     pexpect                   4.8.0            py37hc8dfbb8_1    conda-forge
     pickleshare               0.7.5           py37hc8dfbb8_1002    conda-forge
     pillow                    8.2.0            py37he98fc37_0
     pip                       21.2.4             pyhd8ed1ab_0    conda-forge
     pluggy                    0.13.1           py37h89c1867_4    conda-forge
     pre-commit                2.14.1           py37h89c1867_0    conda-forge
     pre_commit                2.14.1               hd8ed1ab_0    conda-forge
     prometheus_client         0.10.1             pyhd8ed1ab_0    conda-forge
     prompt-toolkit            3.0.18             pyha770c72_0    conda-forge
     protobuf                  3.16.0           py37hcd2ae1e_0    conda-forge
     psutil                    5.8.0            py37h5e8e339_1    conda-forge
     ptvsd                     4.3.2                    pypi_0    pypi
     ptyprocess                0.7.0              pyhd3deb0d_0    conda-forge
     py                        1.10.0             pyhd3deb0d_0    conda-forge
     py-cpuinfo                8.0.0              pyhd3eb1b0_0
     pyarrow                   5.0.0           py37hf0016df_3_cuda    conda-forge
     pycodestyle               2.6.0              pyh9f0ad1d_0    conda-forge
     pycparser                 2.20               pyh9f0ad1d_2    conda-forge
     pydata-sphinx-theme       0.6.3              pyhd8ed1ab_0    conda-forge
     pyflakes                  2.2.0              pyh9f0ad1d_0    conda-forge
     pygments                  2.8.1              pyhd8ed1ab_0    conda-forge
     pynndescent               0.5.4              pyh6c4a22f_0    conda-forge
     pynvml                    11.0.0             pyhd8ed1ab_0    conda-forge
     pyopenssl                 20.0.1             pyhd8ed1ab_0    conda-forge
     pyorc                     0.4.0                    pypi_0    pypi
     pyparsing                 2.4.7              pyh9f0ad1d_0    conda-forge
     pyrsistent                0.17.3           py37h5e8e339_2    conda-forge
     pysocks                   1.7.1            py37h89c1867_3    conda-forge
     pytest                    6.2.4            py37h89c1867_0    conda-forge
     pytest-benchmark          3.4.1              pyhd8ed1ab_0    conda-forge
     pytest-forked             1.3.0              pyhd3deb0d_0    conda-forge
     pytest-xdist              2.3.0              pyhd8ed1ab_0    conda-forge
     python                    3.7.10          hffdb5ce_100_cpython    conda-forge
     python-dateutil           2.8.1                      py_0    conda-forge
     python_abi                3.7                     1_cp37m    conda-forge
     pytorch                   1.7.1           cpu_py37h6a09485_0
     pytz                      2021.1             pyhd8ed1ab_0    conda-forge
     pyyaml                    5.4.1            py37h5e8e339_0    conda-forge
     pyzmq                     22.0.3           py37h336d617_1    conda-forge
     rapidjson                 1.1.0             he1b5a44_1002    conda-forge
     re2                       2021.08.01           h9c3ff4c_0    conda-forge
     readline                  8.1                  h27cfd23_0
     recommonmark              0.7.1              pyhd8ed1ab_0    conda-forge
     regex                     2021.4.4         py37h5e8e339_0    conda-forge
     requests                  2.25.1             pyhd3deb0d_0    conda-forge
     rhash                     1.4.1                h7f98852_0    conda-forge
     s2n                       1.0.10               h9b69904_0    conda-forge
     sacremoses                0.0.43             pyh9f0ad1d_0    conda-forge
     scikit-learn              0.23.1           py37h8a51577_0    conda-forge
     scipy                     1.6.3                    pypi_0    pypi
     seaborn                   0.11.2               hd8ed1ab_0    conda-forge
     seaborn-base              0.11.2             pyhd8ed1ab_0    conda-forge
     send2trash                1.5.0                      py_0    conda-forge
     setuptools                52.0.0           py37h06a4308_0
     six                       1.15.0             pyh9f0ad1d_0    conda-forge
     snappy                    1.1.8                he1b5a44_3    conda-forge
     snowballstemmer           2.1.0              pyhd8ed1ab_0    conda-forge
     sortedcontainers          2.3.0              pyhd8ed1ab_0    conda-forge
     soupsieve                 2.0.1            py37hc8dfbb8_0    conda-forge
     spdlog                    1.8.5                h4bd325d_0    conda-forge
     sphinx                    4.1.2              pyh6c4a22f_1    conda-forge
     sphinx-copybutton         0.4.0              pyhd8ed1ab_0    conda-forge
     sphinx-markdown-tables    0.0.15             pyhd3deb0d_0    conda-forge
     sphinx_rtd_theme          0.5.2              pyhd8ed1ab_1    conda-forge
     sphinxcontrib-applehelp   1.0.2                      py_0    conda-forge
     sphinxcontrib-devhelp     1.0.2                      py_0    conda-forge
     sphinxcontrib-htmlhelp    2.0.0              pyhd8ed1ab_0    conda-forge
     sphinxcontrib-jsmath      1.0.1                      py_0    conda-forge
     sphinxcontrib-qthelp      1.0.3                      py_0    conda-forge
     sphinxcontrib-serializinghtml 1.1.5              pyhd8ed1ab_0    conda-forge
     sphinxcontrib-websupport  1.2.4              pyh9f0ad1d_0    conda-forge
     sqlite                    3.35.4               h74cdb3f_0    conda-forge
     statsmodels               0.12.2           py37h902c9e0_0    conda-forge
     streamz                   0.6.2              pyh44b312d_0    conda-forge
     sysroot_linux-64          2.12                h77966d4_13    conda-forge
     tbb                       2020.2               h4bd325d_4    conda-forge
     tblib                     1.7.0              pyhd8ed1ab_0    conda-forge
     terminado                 0.9.4            py37h89c1867_0    conda-forge
     testpath                  0.4.4                      py_0    conda-forge
     threadpoolctl             2.2.0              pyh8a188c0_0    conda-forge
     tk                        8.6.10               hed695b0_1    conda-forge
     tokenizers                0.10.1           py37hcb7a40c_0    conda-forge
     toml                      0.10.2             pyhd8ed1ab_0    conda-forge
     toolz                     0.11.1                     py_0    conda-forge
     tornado                   6.1              py37h5e8e339_1    conda-forge
     tqdm                      4.60.0             pyhd8ed1ab_0    conda-forge
     traitlets                 5.0.5                      py_0    conda-forge
     transformers              4.9.2              pyhd8ed1ab_0    conda-forge
     treelite                  2.0.0            py37hc731546_0    conda-forge
     treelite-runtime          2.0.0                    pypi_0    pypi
     typed-ast                 1.4.3            py37h5e8e339_0    conda-forge
     typing-extensions         3.10.0.0             hd8ed1ab_0    conda-forge
     typing_extensions         3.10.0.0           pyha770c72_0    conda-forge
     ucx                       1.9.0+gcd9efd3       cuda11.2_0    rapidsai
     ucx-proc                  1.0.0                       gpu    rapidsai
     ucx-py                    0.22.0a210830   py37_gcd9efd3_18    rapidsai-nightly
     umap-learn                0.5.1            py37h89c1867_1    conda-forge
     urllib3                   1.26.4             pyhd8ed1ab_0    conda-forge
     virtualenv                20.4.3           py37h89c1867_0    conda-forge
     wcwidth                   0.2.5              pyh9f0ad1d_2    conda-forge
     webencodings              0.5.1                      py_1    conda-forge
     wheel                     0.36.2             pyhd3deb0d_0    conda-forge
     xz                        5.2.5                h516909a_1    conda-forge
     yaml                      0.2.5                h516909a_0    conda-forge
     zeromq                    4.3.4                h9c3ff4c_0    conda-forge
     zict                      2.0.0                      py_0    conda-forge
     zipp                      3.4.1              pyhd8ed1ab_0    conda-forge
     zlib                      1.2.11            h516909a_1010    conda-forge
     zstd                      1.5.0                ha95c52a_0    conda-forge
     
</pre></details>

**Additional context**
Follow up of #9131

### PR DESCRIPTION
**Pull request by isVoid**
This PR applies type metadata to column children when the column is slice constructed. This make sure compound type metadata (lists, structs) gets passed on correctly to children.

closes #9177

### CODE REVIEW

**Comment by isVoid** [comment]
rerun tests

**Comment by isVoid** [comment]
rerun tests

**Comment by isVoid** [comment]
rerun tests

**Comment by Ethyling** [comment]
rerun tests

**Comment by Ethyling** [comment]
rerun tests

**Comment by Ethyling** [comment]
rerun tests

**Comment by isVoid** [comment]
rerun tests

**Comment by karthikeyann** [comment]
@isVoid is it possible to avoid the deep copy here? (for slicing).

**Pull request merged**
