### PR TITLE
Describe unpickling expectations when cudf.pandas is enabled

### PR DESCRIPTION
**Pull request by shwina**
## Description

Adds to the docs the unpickling expectations that were noted in #14692.

## Checklist
- [x] I am familiar with the [Contributing Guidelines](https://github.com/rapidsai/cudf/blob/HEAD/CONTRIBUTING.md).
- [x] New or existing tests cover these changes.
- [x] The documentation is up to date with these changes.

### CODE REVIEW

**Review by mroeschke — APPROVED** [review]

**Comment by davidwendt** [comment]
Perhaps this addresses (or can address) https://github.com/rapidsai/cudf/issues/14738 as well?

**Pull request merged**
