### PR TITLE
[REVIEW] Fix for round robin bug when npartitions divide nrows.

### PR DESCRIPTION
**Pull request by aschaffer**
Fix for round robin bug when npartitions divide nrows. Issue: https://github.com/rapidsai/cudf/issues/4043

### CODE REVIEW

**Comment by aschaffer** [comment]
rerun tests

**Comment by karthikeyann** [comment]
> rerun tests

> CI fails because rmm-0.13 moved mr/ to mr/device. Next commit will fix this.
https://github.com/rapidsai/cudf/pull/3693#issuecomment-581642073

**Comment by aschaffer** [comment]
> CI fails because rmm-0.13 moved mr/ to mr/device. Next commit will fix this.
> [#3693 (comment)](https://github.com/rapidsai/cudf/pull/3693#issuecomment-581642073)

So, I assume I need to wait for that to be merged and then merge it into this branch. Correct? 

I've just tried updating this branch from rapidsai/branch-0.13 about 30 mins. ago and got the message:
```
$ git pull https://github.com/rapidsai/cudf.git branch-0.13
From https://github.com/rapidsai/cudf
 * branch            branch-0.13 -> FETCH_HEAD
Already up-to-date.
```

**Comment by karthikeyann** [comment]
> So, I assume I need to wait for that to be merged and then merge it into this branch. Correct?

Jake just merged another PR with fix #3985. You can merge branch-0.13 now.

**Comment by aschaffer** [comment]
> Jake just merged another PR with fix #3985. You can merge branch-0.13 now.

I've just merged 0.13 now and I see errors (locally):

/home/aschaffer/Development/Projects/Rapids/forked/bug_ext_round_robin_4043/cudf/cpp/src/hash/hash_allocator.cuh:23:52: fatal error: rmm/mr/device/device_memory_resource.hpp: No such file or directory
 #include <rmm/mr/device/device_memory_resource.hpp>

**Comment by karthikeyann** [comment]
> > Jake just merged another PR with fix #3985. You can merge branch-0.13 now.
> 
> I've just merged 0.13 now and I see errors (locally):
> 
> /home/aschaffer/Development/Projects/Rapids/forked/bug_ext_round_robin_4043/cudf/cpp/src/hash/hash_allocator.cuh:23:52: fatal error: rmm/mr/device/device_memory_resource.hpp: No such file or directory
> #include <rmm/mr/device/device_memory_resource.hpp>

update conda environment.
`conda env update -f conda/environments/cudf_dev_cuda<>.yml --prune`

**Comment by aschaffer** [comment]
> conda env update -f conda/environments/cudf_dev_cuda<>.yml --prune

Thanks. I've update (10.1, only). Retrying.

**Pull request merged**
