### PR TITLE
Add a `__dataframe__` method to the protocol dataframe object

### PR DESCRIPTION
**Pull request by rgommers**
This will align the implementation with those in other libraries, xref https://github.com/data-apis/dataframe-api/issues/80.

Cc @shwina 

## Checklist
- [x] I am familiar with the [Contributing Guidelines](https://github.com/rapidsai/cudf/blob/HEAD/CONTRIBUTING.md).
- [x] New or existing tests cover these changes.
- [x] The documentation is up to date with these changes.

### CODE REVIEW

**Comment by GPUtester** [comment]
Can one of the admins verify this patch?

Admins can comment `ok to test` to allow this one PR to run or `add to allowlist` to allow all future PRs from the same author to run.

**Comment by shwina** [comment]
ok to test

**Comment by raydouglass** [comment]
ok to test

**Review by shwina — APPROVED** [review]

**Comment by shwina** [comment]
@gpucibot merge

**Pull request merged**
