### PR TITLE
Remove deprecated expand parameter from str.findall.

### PR DESCRIPTION
**Pull request by bdice**
This PR follows up on #10459, #10491 to remove the deprecated `expand` parameter and update the behavior of `str.findall` to always returns a list column of results.

### CODE REVIEW

**Comment by bdice** [comment]
There may be some opportunity for cleaning up the libcudf side. I need to investigate further but I think we have an unused function in libcudf now. I also need to update tests for this PR.

**Comment by bdice** [comment]
I updated tests but decided against removing the libcudf `findall` function for now. It may be unused in Python, but there may be other consumers of this code. We should check on that before deleting it from libcudf, and that can be done in a separate PR.

**Comment by bdice** [comment]
@shwina @brandon-b-miller This PR is now ready for review. Sorry for the delay, it fell to the back burner for a while.

**Review by galipremsagar — APPROVED** [review]

**Comment by bdice** [comment]
@gpucibot merge

**Pull request merged**
