### PR TITLE
[REVIEW] Update 10min guide for 0.9 and include dask wait/persist example

### PR DESCRIPTION
**Pull request by beckernick**
**Summary of Changes**
- Updates the Intro to cudf/dask guide to reflect cuDF 0.9 functionality
- Updates the guide to include a **Performance Tips** section (should consider renaming) that goes over a basic usage of `persist` and `wait` in Dask

### CODE REVIEW

**Comment by beckernick** [comment]
@quasiben I know you already took a look (thanks!), but this update is now ready for review if you'd like to take a look with fresh eyes. @randerzander I believe you had some ideas about other updates we could make in this same PR, as well.

**Comment by kkraus14** [comment]
rerun tests

**Comment by beckernick** [comment]
rerun tests

**Comment by kkraus14** [comment]
rerun tests

**Pull request merged**
