### PR TITLE
[REVIEW] Add Tail method, update Head method to use iloc for Series/DataFrame

### LINKED ISSUE #845: tail cudf method
There is a `head` method for cudf, while there is no `tail`. I would like to request `tail` method, similarly as the one in pandas.
```py
print(gdf.head(3))
#   id4 mean_v1 mean_v2   mean_v3
#0    1       3       3 50.523914
#1    2       2       3 50.630413
#2    3       3       3 50.728027
print(gdf.tail(3))
#AttributeError: 'DataFrame' object has no attribute 'tail'
```

### PR DESCRIPTION
**Pull request by beckernick**
- Implements `tail` methods for `DataFrame` and `Series`.
- Updates the `head` method to use `iloc` accessor pattern.
- Adds unit tests for both `head` and `tail` methods.

This PR closes #845.

### CODE REVIEW

**Comment by beckernick** [comment]
@kkraus14 Do you think we should update `head/tail` to use `iloc` instead of directly accessing on `self`, or is our `iloc` too early stage?

For context, Pandas made a similar switch from direct access to leveraging `iloc` in 2013: https://github.com/pandas-dev/pandas/blob/master/pandas/core/generic.py#L4590 and https://github.com/pandas-dev/pandas/pull/5373/files)?

**Comment by beckernick** [comment]
rerun tests

**Comment by kkraus14** [comment]
> @kkraus14 Do you think we should update `head/tail` to use `iloc` instead of directly accessing on `self`, or is our `iloc` too early stage?
> 
> For context, Pandas made a similar switch from direct access to leveraging `iloc` in 2013: https://github.com/pandas-dev/pandas/blob/master/pandas/core/generic.py#L4590 and https://github.com/pandas-dev/pandas/pull/5373/files

Our `iloc` accessing I believe ends up going through the `self` accessor so it shouldn't particularly matter for now. I would support using `iloc` for better future compatibility.

**Comment by beckernick** [comment]
Tests are currently failing for two reasons:

- Negative slicing of empty dataframe causing non-empty index (#856)
- `iloc` slicing columns of type `bool` causes an error (#874).

Can avoid these issues by changing/reducing the breadth of tests and go back to direct `self` access instead of `iloc` access. Defer to @kkraus14 if we prefer to do that and get the `tail` method merged and then update `head`/`tail` to use `iloc` at a later date.

**Comment by kkraus14** [comment]
I'll jump in and finish this

**Comment by kkraus14** [comment]
This also now fixes #628

**Pull request merged**
