### PR TITLE
Check `num_children() == 0` in `Column.from_column_view`

### PR DESCRIPTION
**Pull request by cwharris**
## Description
This fixes a bug where `Column.from_column_view` is not verifying the existence of a string column's offsets child column prior to accessing it, resulting in a segmentation fault when passing a `column_view` from `Column.view()` to `Column.from_column_view(...)`.

The issue can be reproduced with:
```
import cudf
from cudf.core.column.column import as_column
df = cudf.DataFrame({'a': cudf.Series([[]], dtype=cudf.core.dtypes.ListDtype('string'))})
s = df['a']
col = as_column(s)
col2 = cudf._lib.column.Column.back_and_forth(col)
print(col)
print(col2)
```
where `back_and_forth` is defined as:
```
    @staticmethod
    def back_and_forth(Column input_column):
        cdef column_view input_column_view = input_column.view()
        return Column.from_column_view(input_column_view, input_column)
```
I don't have the expertise to write the appropriate tests for this without introducing the `back_and_forth` function as an API, which seems undesirable.

## Checklist
- [x] I am familiar with the [Contributing Guidelines](https://github.com/rapidsai/cudf/blob/HEAD/CONTRIBUTING.md).
- [x] New or existing tests cover these changes.
- [x] The documentation is up to date with these changes.

### CODE REVIEW

**Review by bdice — APPROVED** [review]
This looks fine to me. We don't really have a way to test Cython-only methods at this time, as far as I am aware.

**Review by vyasr — APPROVED** [review]
This change looks correct to me, thanks! I agree with Bradley, there really isn't a great way to test this right now.

**Pull request merged**
