### PR TITLE
Support for JIT compilation of libcudacxx on ppc64

### PR DESCRIPTION
**Pull request by jglaser**
This addresses a JIT compile error on Power9. I created a corresponding PR for libcudacxx [here](https://github.com/rapidsai/thirdparty-freestanding/pull/3)

The underlying issue is that the 'hacky' headers in `libcudacxx/include/simt/cfloat` define a too small/large value for `LDBL_MIN` and `LDBL_MAX`, which work for x86_64 but are not portable to ppc. See the link above for the type of JIT error encountered with BlazingSQL queries.

The solution I took was to export another CPU architecture define to NVRTC via jitify, which gets picked up by libcudacxx.

### CODE REVIEW

**Comment by GPUtester** [comment]
Can one of the admins verify this patch?

**Comment by GPUtester** [comment]
Can one of the admins verify this patch?

**Comment by jrhemstad** [comment]
Okay to test

**Comment by jrhemstad** [comment]
Thanks for the fix @jglaser. If you can add an entry to the `CHANGELOG.md`, that will trigger CI to run.

As I mentioned here: https://github.com/rapidsai/thirdparty-freestanding/pull/3#issuecomment-657609430, we'll likely need to revisit this once we switch from the freestanding libcu++ to the real one.

**Comment by harrism** [comment]
@kkraus14 you added "merge after dependencies", but I don't see what the dependencies are. Can you clarify?

Also, why is CI not running?

**Comment by kkraus14** [comment]
> @kkraus14 you added "merge after dependencies", but I don't see what the dependencies are. Can you clarify?
> 
> Also, why is CI not running?

There's a corresponding PR into the freestanding repo that needs to be pushed into our form that I believe this depends on.

If I'm incorrect please feel free to remove the label though.

**Comment by kkraus14** [comment]
ok to test

**Comment by kkraus14** [comment]
rerun tests

**Comment by davidwendt** [comment]
@jglaser Can you run the `cpp/src/jit/common_headers.hpp` file through `clang-format` and then re-commit it in this PR?

**Pull request merged**
