### PR TITLE
Add multiple rows to subword tokenizer benchmark

### PR DESCRIPTION
**Pull request by davidwendt**
When porting the subword tokenizer code from CLX, the benchmark was not updated to measure multiple rows. This updates the benchmark to include a row test range and add the missing `cuda_event_timer`.

### CODE REVIEW

**Review by codereport — APPROVED** [review]
lgtm

**Review by karthikeyann — COMMENTED** [review]
Looks good. 
This PR could also be an opportunity to move from gbench to NVBench.

**Comment by davidwendt** [comment]
> Looks good. This PR could also be an opportunity to move from gbench to NVBench.

Yes, I considered that but I think I want to convert all of the text ones at the same time instead.

**Comment by davidwendt** [comment]
@gpucibot merge

**Pull request merged**
