### PR TITLE
[REVIEW] Specialize update_existing_value in concurrent_unordered_map for sum_op

### PR DESCRIPTION
**Pull request by andars**
This PR adds specialized implementations for sum aggregations to the concurrent_unordered_map. This helps quite a bit for contended updates, since they can occur in L2.

Using the comparison from #533, I get these results on a Intel(R) Core(TM) i7-7800X CPU @ 3.50GHz with a Titan X(Pascal):

Before:
```python
import pandas as pd, cudf, numpy as np
pdf = pd.DataFrame({'x': np.random.random(10000000), 'y': np.random.randint(0, 10, size=10000000)})
gdf = cudf.DataFrame.from_pandas(pdf)
%timeit pdf.groupby('y').mean() # ~ 170ms
%timeit gdf.groupby('y').mean() # ~ 3.7 s
```

After:
```python
import pandas as pd, cudf, numpy as np
pdf = pd.DataFrame({'x': np.random.random(10000000), 'y': np.random.randint(0, 10, size=10000000)})
gdf = cudf.DataFrame.from_pandas(pdf)
%timeit pdf.groupby('y').mean() # ~ 170ms
%timeit gdf.groupby('y').mean() # ~ 60 ms
```

As far as I can tell, this change doesn't cause any new test failures.

### CODE REVIEW

**Comment by GPUtester** [comment]
Can one of the admins verify this patch?

**Comment by GPUtester** [comment]
Can one of the admins verify this patch?

**Comment by andars** [comment]
Yeah, I was surprised by the 50x (in this case) as well. I guess the combination of contention + thread divergence was really hurting perf.

**Comment by jrhemstad** [comment]
@andars you need to also update  `cudf/CHANGELOG.md` with a short description of your change under the 0.6.0 Release for Improvements.

**Comment by kkraus14** [comment]
run tests

**Pull request merged**
