### PR TITLE
[REVIEW] Move nvstrings standalone docs pages to libcudf doxygen pages

### LINKED ISSUE #4920: [DOC] Move nvstrings unicode and regex documentation files to cudf docs
The following 2 pages need to be moved and updated from the `nvstrings` documentation pages to `libcudf` somehow.

https://docs.rapids.ai/api/nvstrings/stable/regex.html
https://docs.rapids.ai/api/nvstrings/stable/unicode.html

Source files are here

https://github.com/rapidsai/cudf/blob/branch-0.14/docs/nvstrings/source/regex.md
https://github.com/rapidsai/cudf/blob/branch-0.14/docs/nvstrings/source/unicode.md

The timestamp documentation was moved into the doxygen comments for the appropriate `cudf::strings` function APIs.

### PR DESCRIPTION
**Pull request by davidwendt**
Closes #4920 
The following pages apply across several strings column APIs and document behavior in nvstrings.
https://docs.rapids.ai/api/nvstrings/stable/regex.html
https://docs.rapids.ai/api/nvstrings/stable/unicode.html
Now that libnvstrings has been ported to libcudf, these documents need to be updated and added to the libcudf documentation.

This PR adds these to the doxygen output as "Related Pages".
Also, appropriate APIs will add links to these pages from their doxygen comments.
Further, the strings-specific APIs will be grouped to make it easier to find them.

### CODE REVIEW

**Comment by GPUtester** [comment]
Please update the changelog in order to start CI tests.

View the gpuCI docs [here](https://docs.rapids.ai/gpuci#open-pr-or-update-pr).

**Comment by davidwendt** [comment]
This PR contains no code changes. This is all just updating doxygen comments and adding markdown files.

**Comment by vuule** [comment]
Is there a way to see the effect this has on the generated documentation?

**Comment by davidwendt** [comment]
> Is there a way to see the effect this has on the generated documentation?

That is a good question. I suppose you could pull the PR and build `make docs_cudf` and then point your browser to `cpp/doxygen/html/index.html`. I don't know if the docs are built as part of CI.

**Comment by davidwendt** [comment]
> Would it be possible to move the 'related pages tab' to the right? I feel like it should be the last or maybe second-to-last tab.

It does not look simple to do.
http://www.doxygen.nl/manual/customize.html#layout
We would need to build a custom layout xml. I tried something basic and all the tabs disappeared so I suppose you need to include everything and then you can reorder.

**Comment by vuule** [comment]
> We would need to build a custom layout xml. I tried something basic and all the tabs disappeared so I suppose you need to include everything and then you can reorder.

I don't think it's worth the effort then.

**Pull request merged**
