### PR TITLE
[REVIEW] Use `asarray` to coerce indices to a NumPy array

### PR DESCRIPTION
**Pull request by jakirkham**
Calling `np.array` on a NumPy array will cause a copy. This can be avoided by calling `np.asarray`, which will preserve an existing array when passed in.

xref: https://github.com/rapidsai/cudf/issues/1888

### CODE REVIEW

**Comment by jakirkham** [comment]
Happy to add the changelog entry. Please just let me know where we want this to land.

**Comment by kkraus14** [comment]
@jakirkham this looks good with a changelog entry

**Comment by jakirkham** [comment]
Changelog entry added. Should be good to go 🙂

**Comment by jakirkham** [comment]
Looks like the build is failing on CI. Doesn't seem related. Should we try restarting?

**Comment by shwina** [comment]
rerun tests

**Comment by jakirkham** [comment]
rerun tests

**Comment by jakirkham** [comment]
Yeah I'm not sure how this build error is related. This is happening in the C++ portion. Are people seeing this in other builds? What are we missing?

```
[ 86%] Building CUDA object CMakeFiles/cudf.dir/src/column/column.cu.o
/usr/local/cuda/bin/nvcc -ccbin=/usr/bin/g++-5 -DARROW_METADATA_V4 -Dcudf_EXPORTS -I$SRC_DIR/cpp/build/googletest/install/include -I$SRC_DIR/cpp/build/include -I$SRC_DIR/cpp/include -I$SRC_DIR/cpp/src -I$SRC_DIR/cpp/thirdparty/cub -I$SRC_DIR/cpp/thirdparty/jitify -I$SRC_DIR/cpp/thirdparty/libcudacxx/include -I$SRC_DIR/cpp/build/arrow/install/include -I$SRC_DIR/cpp/build/arrow/build/flatbuffers_ep-prefix/src/flatbuffers_ep-install/include -I$BUILD_PREFIX/include -I$PREFIX/include  -gencode=arch=compute_60,code=sm_60 -gencode=arch=compute_70,code=sm_70 -gencode=arch=compute_70,code=compute_70 --expt-extended-lambda --expt-relaxed-constexpr -Werror cross-execution-space-call -Xcompiler -Wall,-Werror --define-macro HT_LEGACY_ALLOCATOR -O3 -DNDEBUG -Xcompiler=-fPIC   -DJITIFY_USE_CACHE -DCUDF_VERSION=0.11.0 -std=c++14 -x cu -c $SRC_DIR/cpp/src/column/column.cu -o CMakeFiles/cudf.dir/src/column/column.cu.o
make[3]: Leaving directory '$SRC_DIR/cpp/build'
make[2]: Leaving directory '$SRC_DIR/cpp/build'
make[1]: Leaving directory '$SRC_DIR/cpp/build'
Traceback (most recent call last):
  File "/conda/bin/conda-build", line 11, in <module>
    sys.exit(main())
  File "/conda/lib/python3.7/site-packages/conda_build/cli/main_build.py", line 456, in main
    execute(sys.argv[1:])
  File "/conda/lib/python3.7/site-packages/conda_build/cli/main_build.py", line 447, in execute
    verify=args.verify, variants=args.variants)
  File "/conda/lib/python3.7/site-packages/conda_build/api.py", line 208, in build
    notest=notest, need_source_download=need_source_download, variants=variants)
  File "/conda/lib/python3.7/site-packages/conda_build/build.py", line 2314, in build_tree
    notest=notest,
  File "/conda/lib/python3.7/site-packages/conda_build/build.py", line 1477, in build
    cwd=src_dir, stats=build_stats)
  File "/conda/lib/python3.7/site-packages/conda_build/utils.py", line 374, in check_call_env
    return _func_defaulting_env_to_os_environ('call', *popenargs, **kwargs)
  File "/conda/lib/python3.7/site-packages/conda_build/utils.py", line 354, in _func_defaulting_env_to_os_environ
    raise subprocess.CalledProcessError(proc.returncode, _args)
subprocess.CalledProcessError: Command '['/bin/bash', '-e', '/conda/conda-bld/libcudf_1570733233310/work/conda_build.sh']' returned non-zero exit status 2.
```

**Comment by jakirkham** [comment]
Rebased on `master` in case that helps. 🍀

**Comment by jakirkham** [comment]
So it ran all the way through and most of the checks passed. However it looks like a couple failed, but still for unrelated reasons. Now the failures appear to be Dask related. 😕

**Comment by jakirkham** [comment]
Here's one of the Dask failures for reference.

```python
17:02:29 ___________________________ test_roundtrip_from_dask ___________________________
17:02:29 
17:02:29 tmpdir = '/tmp/pytest-of-jenkins/pytest-292/test_roundtrip_from_dask0'
17:02:29 
17:02:29     def test_roundtrip_from_dask(tmpdir):
17:02:29         tmpdir = str(tmpdir)
17:02:29         ddf.to_parquet(tmpdir, engine="pyarrow")
17:02:29         files = sorted(
17:02:29             [
17:02:29                 os.path.join(tmpdir, f)
17:02:29                 for f in os.listdir(tmpdir)
17:02:29                 if not f.endswith("_metadata")
17:02:29             ],
17:02:29             key=natural_sort_key,
17:02:29         )
17:02:29     
17:02:29         # Read list of parquet files
17:02:29         ddf2 = dask_cudf.read_parquet(files, gather_statistics=True)
17:02:29 >       assert_eq(ddf, ddf2)
17:02:29 
17:02:29 dask_cudf/io/tests/test_parquet.py:39: 
17:02:29 _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
17:02:29 /conda/envs/gdf/lib/python3.6/site-packages/dask/dataframe/utils.py:780: in assert_eq
17:02:29     b = _check_dask(b, check_names=check_names, check_dtypes=check_dtypes)
17:02:29 /conda/envs/gdf/lib/python3.6/site-packages/dask/dataframe/utils.py:692: in _check_dask
17:02:29     result = dsk.compute(scheduler="sync")
17:02:29 /conda/envs/gdf/lib/python3.6/site-packages/dask/base.py:165: in compute
17:02:29     (result,) = compute(self, traverse=False, **kwargs)
17:02:29 /conda/envs/gdf/lib/python3.6/site-packages/dask/base.py:433: in compute
17:02:29     dsk = collections_to_dsk(collections, optimize_graph, **kwargs)
17:02:29 /conda/envs/gdf/lib/python3.6/site-packages/dask/base.py:211: in collections_to_dsk
17:02:29     groups = {opt: _extract_graph_and_keys(val) for opt, val in groups.items()}
17:02:29 /conda/envs/gdf/lib/python3.6/site-packages/dask/base.py:211: in <dictcomp>
17:02:29     groups = {opt: _extract_graph_and_keys(val) for opt, val in groups.items()}
17:02:29 /conda/envs/gdf/lib/python3.6/site-packages/dask/base.py:239: in _extract_graph_and_keys
17:02:29     graph = merge(*graphs)
17:02:29 _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
17:02:29 
17:02:29 dicts = ParquetSubgraph<name='read-parquet-d7048e03f9eb4a9b948d55e79b402c59', n_parts=13>
17:02:29 kwargs = {}, factory = <class 'dict'>, rv = {}
17:02:29 d = ('read-parquet-d7048e03f9eb4a9b948d55e79b402c59', 0)
17:02:29 
17:02:29     def merge(*dicts, **kwargs):
17:02:29         """ Merge a collection of dictionaries
17:02:29     
17:02:29         >>> merge({1: 'one'}, {2: 'two'})
17:02:29         {1: 'one', 2: 'two'}
17:02:29     
17:02:29         Later dictionaries have precedence
17:02:29     
17:02:29         >>> merge({1: 2, 3: 4}, {3: 3, 4: 4})
17:02:29         {1: 2, 3: 3, 4: 4}
17:02:29     
17:02:29         See Also:
17:02:29             merge_with
17:02:29         """
17:02:29         if len(dicts) == 1 and not isinstance(dicts[0], dict):
17:02:29             dicts = dicts[0]
17:02:29         factory = _get_factory(merge, kwargs)
17:02:29     
17:02:29         rv = factory()
17:02:29         for d in dicts:
17:02:29 >           rv.update(d)
17:02:29 E           ValueError: dictionary update sequence element #0 has length 45; 2 is required
17:02:29 
17:02:29 /conda/envs/gdf/lib/python3.6/site-packages/toolz/dicttoolz.py:38: ValueError
```

**Comment by jakirkham** [comment]
Looks like all of the nvstrings tests are failing.

```
12:44:04 Scanning dependencies of target test_nvstrings
12:44:04 Test project /jenkins/workspace/rapidsai/gpuci/cudf/prb/cudf-gpu-build_3/cpp/build
12:44:04       Start 54: NVSTRINGS_ARRAY_TEST
12:44:05  1/15 Test #54: NVSTRINGS_ARRAY_TEST .............***Failed    1.10 sec
12:44:05       Start 55: NVSTRINGS_ATTRS_TEST
12:44:06  2/15 Test #55: NVSTRINGS_ATTRS_TEST .............***Failed    1.06 sec
12:44:06       Start 56: NVSTRINGS_CASE_TEST
12:44:07  3/15 Test #56: NVSTRINGS_CASE_TEST ..............***Failed    1.12 sec
12:44:07       Start 57: NVSTRINGS_COMBINE_TEST
12:44:08  4/15 Test #57: NVSTRINGS_COMBINE_TEST ...........***Failed    1.06 sec
12:44:08       Start 58: NVSTRINGS_CONVERT_TEST
12:44:10  5/15 Test #58: NVSTRINGS_CONVERT_TEST ...........***Failed    1.43 sec
12:44:10       Start 59: NVSTRINGS_DATE_TEST
12:44:11  6/15 Test #59: NVSTRINGS_DATE_TEST ..............***Failed    1.46 sec
12:44:11       Start 60: NVSTRINGS_EXTRACT_TEST
12:44:12  7/15 Test #60: NVSTRINGS_EXTRACT_TEST ...........***Failed    1.11 sec
12:44:12       Start 61: NVSTRINGS_FIND_TEST
12:44:13  8/15 Test #61: NVSTRINGS_FIND_TEST ..............***Failed    1.06 sec
12:44:13       Start 62: NVSTRINGS_MODIFY_TEST
12:44:14  9/15 Test #62: NVSTRINGS_MODIFY_TEST ............***Failed    1.08 sec
12:44:14       Start 63: NVSTRINGS_PAD_TEST
12:44:15 10/15 Test #63: NVSTRINGS_PAD_TEST ...............***Failed    1.08 sec
12:44:15       Start 64: NVSTRINGS_STRIP_TEST
12:44:17 11/15 Test #64: NVSTRINGS_STRIP_TEST .............***Failed    1.06 sec
12:44:17       Start 65: NVSTRINGS_SPLIT_TEST
12:44:18 12/15 Test #65: NVSTRINGS_SPLIT_TEST .............***Failed    1.08 sec
12:44:18       Start 66: NVSTRINGS_REPLACE_TEST
12:44:19 13/15 Test #66: NVSTRINGS_REPLACE_TEST ...........***Failed    1.11 sec
12:44:19       Start 67: NVSTRINGS_TEXT_TEST
12:44:20 14/15 Test #67: NVSTRINGS_TEXT_TEST ..............***Failed    1.07 sec
12:44:20       Start 68: NVSTRINGS_URL_TEST
12:44:21 15/15 Test #68: NVSTRINGS_URL_TEST ...............***Failed    1.08 sec
12:44:21 
12:44:21 0% tests passed, 15 tests failed out of 15
12:44:21 
12:44:21 Total Test time (real) =  16.98 sec
12:44:21 
12:44:21 The following tests FAILED:
12:44:21 	 54 - NVSTRINGS_ARRAY_TEST (Failed)
12:44:21 	 55 - NVSTRINGS_ATTRS_TEST (Failed)
12:44:21 	 56 - NVSTRINGS_CASE_TEST (Failed)
12:44:21 	 57 - NVSTRINGS_COMBINE_TEST (Failed)
12:44:21 	 58 - NVSTRINGS_CONVERT_TEST (Failed)
12:44:21 	 59 - NVSTRINGS_DATE_TEST (Failed)
12:44:21 	 60 - NVSTRINGS_EXTRACT_TEST (Failed)
12:44:21 	 61 - NVSTRINGS_FIND_TEST (Failed)
12:44:21 	 62 - NVSTRINGS_MODIFY_TEST (Failed)
12:44:21 	 63 - NVSTRINGS_PAD_TEST (Failed)
12:44:21 	 64 - NVSTRINGS_STRIP_TEST (Failed)
12:44:21 	 65 - NVSTRINGS_SPLIT_TEST (Failed)
12:44:21 	 66 - NVSTRINGS_REPLACE_TEST (Failed)
12:44:21 	 67 - NVSTRINGS_TEXT_TEST (Failed)
12:44:21 	 68 - NVSTRINGS_URL_TEST (Failed)
12:44:21 Errors while running CTest
12:44:21 make[3]: *** [CMakeFiles/test_nvstrings.dir/build.make:57: CMakeFiles/test_nvstrings] Error 8
12:44:21 make[2]: *** [CMakeFiles/Makefile2:73: CMakeFiles/test_nvstrings.dir/all] Error 2
12:44:21 make[1]: *** [CMakeFiles/Makefile2:80: CMakeFiles/test_nvstrings.dir/rule] Error 2
12:44:21 make: *** [Makefile:175: test_nvstrings] Error 2
12:44:21 Build step 'Execute shell' marked build as failure
12:44:23 Recording test results
```

**Comment by kkraus14** [comment]
rerun tests

**Comment by jakirkham** [comment]
Am seeing the nvstrings failures again. 😟 Will rebase again just in case things are out-of-date here.

ref: https://gpuci.gpuopenanalytics.com/blue/organizations/jenkins/rapidsai%2Fgpuci%2Fcudf%2Fprb%2Fcudf-gpu-build/detail/cudf-gpu-build/1458/pipeline

**Comment by jakirkham** [comment]
Hmm...looks like I'm already on the latest commit of `branch-0.11`. Any other ideas?

**Comment by jakirkham** [comment]
Appears we needed PR ( https://github.com/rapidsai/cudf/pull/3061 ). Have rebased on top of that.

**Comment by jakirkham** [comment]
It's green! 😄 🎉

**Pull request merged**
