### PR TITLE
Refactor setting stack size in regex code

### PR DESCRIPTION
**Pull request by davidwendt**
This PR is the first of several to cleanup the regex strings code. The regex code employs multiple stack sizes to perform its matching based on the number of instructions in the given regex pattern. The current implementation allocates the stack for the regex code. This PR moves this down into the regex functions themselves. This helps simplify the interface and reduce compile time a bit.

### CODE REVIEW

**Comment by nvdbaranec** [comment]
Question about the transition between "LARGE" stack size and "global memory". It seems like there's a hole between `RX_LARGE_INSTS` (920) and `MAX_STACK_INSTS` (1000).   It looks like this code can get into the RX_STACK_ANY case as soon as the # of instructions is > 920.  But the code for allocating the global memory doesn't kick in until 1000 instructions:

```
  if (insts_count > MAX_STACK_INSTS) {
    auto relist_alloc_size = relist::alloc_size(insts_count);
    rlm_size               = relist_alloc_size * 2L * strings_count;  // reljunk has 2 relist ptrs
  }
```

Is there some kind of rounding thing going on here where it will always be some safe multiple of instructions?

**Comment by davidwendt** [comment]
I think you are right. There appears to be an overlap where too much memory is being allocated. I should change the threshold check to use `RX_LARGE_INSTS` instead of `MAX_STACK_INSTS` and then get rid of the latter.

**Review by nvdbaranec — APPROVED** [review]

**Review by devavret — APPROVED** [review]
Didn't review the entire logic but now I understand the change. Code quality looks good.

**Comment by davidwendt** [comment]
@gpucibot merge

**Pull request merged**
