### PR TITLE
Ensure comparisons with pyints and integer series always succeed

### PR DESCRIPTION
**Pull request by seberg**
When Python integers are compared to a series of integers, the result can always be correctly defined no matter the values of the Python integer.

This was always a very mild issue.  But with NumPy 2 behavior not upcasting the computation result type based on the value anymore, even things like:
```
cudf.Series([1, 2, 3], dtype="int8") < 1000
```
would fail.
(Similar paths could be taken for other integer scalars, but there would be mostly nice for performance.)

N.B. NumPy/pandas also support exact comparisons when mixing e.g. uint64 and int64.  This is another rare exception that cudf currently does not support.

Closes gh-16282

## Checklist
- [x] I am familiar with the [Contributing Guidelines](https://github.com/rapidsai/cudf/blob/HEAD/CONTRIBUTING.md).
- [x] New or existing tests cover these changes.
- [x] The documentation is up to date with these changes.

---

Just as a note for reviewers.  The later operator checks, need `other` to be fully coerced, so unfortunately can't deal with all operator special paths at the start.

### CODE REVIEW

**Review by mroeschke — APPROVED** [review]
Would there be a similar issue with comparing pyfloats and integer or float series?

**Comment by seberg** [comment]
> Would there be a similar issue with comparing pyfloats and integer or float series?

Yes and no: we are usually content with normal promotion logic there (unlike Python, which corrects for overflows and rounding when comparing int and float scalars).

**Comment by jakirkham** [comment]
Thanks Sebastian and Matt! 🙏

**Pull request merged**
