### PR TITLE
[WIP] Add GroupValidTest Implementations to GroupByTests

### PR DESCRIPTION
**Pull request by aocsa**
List of changes:
-  inputs and references solutions for group_by using nulls (see class GroupValidTest)
- gdf_columns inputs and outputs  for group_by using valid. GroupValidTest::create_input_with_nulls, and GroupValidTest::create_gdf_output_buffers_with_nulls was added. 
- GroupTest::create_gdf_column was updated to initialize gdf_column with `gdf_valid_type* host_valid`.
- GroupValidTest::compute_reference_solution_with_nulls is a sql reference solution.

All the best,

### CODE REVIEW

**Comment by GPUtester** [comment]
Can one of the admins verify this patch?

**Comment by kkraus14** [comment]
add to whitelist

**Comment by williamBlazing** [comment]
Some additional information about this PR:
This should likely not be merged in until the null support for hash based group by is merged in. At that point the execution and validation step in the unit test should be uncommented and tested out. 
We should also need to check and make sure that the reference solution in this PR matches the expected behavior of groups by's with nulls as was implemented. This reference solution is based on SQL-like expected behavior. I am not sure what the expected behavior is of the hash based group by with null support at this point.

**Comment by harrism** [comment]
In that case should it be [WIP] rather than [REVIEW]?

**Comment by aocsa** [comment]
> In that case should it be [WIP] rather than [REVIEW]?

Yes, now it is in WIP.

**Comment by harrism** [comment]
> This should likely not be merged in until the null support for hash based group by is merged in. At that point the execution and validation step in the unit test should be uncommented and tested out.

Which PR is that?

**Comment by aocsa** [comment]
> > This should likely not be merged in until the null support for hash based group by is merged in. At that point the execution and validation step in the unit test should be uncommented and tested out.
> 
> Which PR is that?

**Comment by aocsa** [comment]
@mt-jones All check pass, this branch is updated with the current master (cudf 0.3.0) ;). So if null support for hash-based group by is merged in, I can change the PR to Review.  Let me known.

**Comment by harrism** [comment]
>  if null support for hash-based group by is merged in, I can change the PR to Review. Let me known.

@aocsa What PR are you referring to for "null support for hash-based groupby"?

**Comment by aocsa** [comment]
> > if null support for hash-based group by is merged in, I can change the PR to Review. Let me known.
> 
> @aocsa What PR are you referring to for "null support for hash-based groupby"?
Jacob  said yesterday that `hash-based implementation has completed null support that just needs to be merged`. So I will wait up to this is merged. 

Jacob Hemstad [11:52]
FYI, in order to consolidate the code base and reduce the amount of code that needs to be maintained, we're planning to drop the sort-based groupby from the cudf source. The hash-based implementation has completed null support that just needs to be merged, as well as pending optimazation for doing multiple aggregations in a single pass through the data. This does not preclude the multi-column sort/orderby that would be used for a groupby with a user defined reduction operation. Any objections?

**Comment by harrism** [comment]
This PR is waiting on null support in groupby, which is now delayed until groupby is refactored to support multi-aggregation. See https://github.com/rapidsai/cudf/pull/460#issuecomment-447960976 and https://github.com/rapidsai/cudf/issues/544

**Comment by harrism** [comment]
@jrhemstad I assume this isn't going to happen for 0.6?

**Comment by jrhemstad** [comment]
> @jrhemstad I assume this isn't going to happen for 0.6?

Correct.

**Comment by harrism** [comment]
@jrhemstad is this PR relevant now that the new groupby with null support is done?

**Pull request closed without merging**
