### PR TITLE
[REVIEW] Dataframe drop method

### LINKED ISSUE #370: DataFrame drop_column should be replaced with drop and not be inplace
Usage should be along the lines of:

```
gdf = cudf.DataFrame()
gdf['a'] = [1,2,3,4,5]
gdf['b'] = [11,12,13,14,15]
gdf['c'] = [21,22,23,24,25]

gdf = gdf.drop(['b', 'c']) # assumes axis=1 and inplace=False compared to Pandas
```

### PR DESCRIPTION
**Pull request by bahaugen**
This PR implements the drop method for the dataframe and deprecates the drop_column method.

closes #370

### CODE REVIEW

**Comment by GPUtester** [comment]
Can one of the admins verify this patch?

**Comment by GPUtester** [comment]
Can one of the admins verify this patch?

**Comment by harrism** [comment]
run tests

**Comment by thomcom** [comment]
Thanks @bahaugen ! This is all pretty solid. I would like to see tests of immutability in the `drop` test - if you use `id(df[col])` between a df before and after dropping you should validate that the id has changed.

* I'm confused why you use `.drop` in `test_dataframe.py` and `del ` in `test_joining.py` and `test_multi.py`

**Comment by bahaugen** [comment]
Good catch @thomcom !

I added a few asserts to check the ids between the original dataframe and the dataframe returned by the `.drop` but they are the same. This appears to be related to the `.copy` operation. What should be the expected behavior of the `.copy` method? The implementation appears to be pretty "shallow" and the new dataframe refers to the same underlying series as the original.

As for the `.drop` vs `del` in `test_joining.py` and `test_multi.py`, it replaces the `.drop_column` method which was inplace. This means it could be replaced with `del got['a']` (inplace) or `got = got.drop('a')` (not inplace). Do you have a preference?

**Comment by harrism** [comment]
run tests

**Comment by harrism** [comment]
@bahaugen Can you please add a line for this PR in the CHANGELOG.md (requirement for merge). Since we already release 0.4.0, can you add it above that section? We will include it in 0.5.0 assuming all CI passes.

Also notice you have style failures. I recommend you install flake8 locally and test for PEP8 compliance before pushing Python changes.

**Comment by bahaugen** [comment]
@harrism I think this should fix the changelog and pep8 problems.

 Unfortunately I can't see the rest of the CI output anymore. Let me know if this passes now or if it still needs some work.

**Comment by harrism** [comment]
Rerun tests

**Pull request merged**
