### PR TITLE
Fix release assert

### PR DESCRIPTION
**Pull request by jrhemstad**
The `release_assert` macro is used in device code to signal that an error occurred and kill the kernel. 

There were two issues with `release_assert`:

1. It was incorrectly guarded with a macro that doesn't exist `__CUDACC_ARCH__`.
   - This means `release_assert` has just been a no-op this whole time.
2. It incorrectly use the `__assertfail` built-in instead of the `__assert_fail` built-in.
   - This was never caught because of the problems with the above `ifdef`.

This should have been caught by tests, but it seems that the test that used to verify this behavior was dropped. Likely sometime in the libcudf++ transition. 

https://github.com/rapidsai/cudf/blob/3e14fb54fb80815f2e0beb5332b04cf607e381a1/cpp/tests/types/dispatcher_test.cu#L127-L147

This PR corrects the `release_assert` and adds tests that it works as expected.

### CODE REVIEW

**Comment by GPUtester** [comment]
Please update the changelog in order to start CI tests.

View the gpuCI docs [here](https://docs.rapids.ai/gpuci#open-pr-or-update-pr).

**Review by karthikeyann — APPROVED** [review]
All this time I thought, it's supposed to be no-op!
Great catch.

**Review by rgsl888prabhu — APPROVED** [review]

**Comment by trivialfis** [comment]
Strangely I have undefined indentifier error with `assert_fail`

**Comment by jrhemstad** [comment]
rerun tests

**Pull request merged**
