### PR TITLE
Revert "New Decimal <--> Floating conversion (#15905)"

### PR DESCRIPTION
**Pull request by ttnghia**
After the PR https://github.com/rapidsai/cudf/pull/15905 merged, there was a performance regression reported:

> We observed significant performance degradation to binary ops. We see 12-14x slowdowns in our AST benchmarks, plus 6-10x slowdowns in other binary ops.

This reverts the problematic PR (https://github.com/rapidsai/cudf/pull/15905), waiting for more investigation on the regression.

### CODE REVIEW

**Review by vyasr — APPROVED** [review]
Approving based on offline discussions indicating that we think it's safe to go ahead without rebenchmarking.

**Review by davidwendt — APPROVED** [review]

**Comment by abellina** [comment]
@ttnghia just wondering what we are waiting for in this PR.

**Comment by mattahrens** [comment]
This is the related perf fix PR: https://github.com/rapidsai/cudf/pull/16287.  It's been merged, but still waiting for final confirmation that is fixed the issue.

**Pull request closed without merging**
