### PR TITLE
Update Python labels and remove unnecessary ones

### PR DESCRIPTION
**Pull request by vyasr**
## Description

This PR leverages some of the new labels we have for organizing our issues and removes labels that aren't really used at the moment. If reviewers feel strongly I can keep the ci label, but AFAICT that doesn't really get used for anything at the moment and we'll benefit more from leveraging future labels to help direct tasks to the build/infra team vs cudf devs.

## Checklist
- [x] I am familiar with the [Contributing Guidelines](https://github.com/rapidsai/cudf/blob/HEAD/CONTRIBUTING.md).
- [x] New or existing tests cover these changes.
- [x] The documentation is up to date with these changes.

### CODE REVIEW

**Review by bdice — APPROVED** [review]
I'm weakly in favor of keeping `ci`.

Perhaps we can rename `conda` to `packaging` and also make it trigger on `pyproject.toml` files? No strong feelings, I'm okay with any outcome here so I'll defer to your preferences.

**Comment by vyasr** [comment]
I'd like to stick to somewhat actionable labeling, especially autolabeling. If we can find a good way to make use of the information that an issue has these labels I'd be fine keeping them, I'm open to suggestions!

**Comment by bdice** [comment]
I thought the point of these labels was to have a way to find historical PRs that touch CI files. Are there other ways to use labels besides this kind of categorization?

**Comment by vyasr** [comment]
I regularly make use of labels to find open issues/PRs that need my (or someone else's) attention. Labels can also be used in building automations, such as adding issues to project boards for specific teams or handling auto-assignment (independent of PR/issue creation). I find less use of them for historical purposes tbh. That being said, I'm not opposed to that.

If you prefer, I can leave the ci and conda auto-labeling in place for now since those don't really have any negative impact. The main reason I was considering removing them from the auto-labeler is because we were considering removing those labels altogether. In our discussions around improving the triage process and the labels we use, nobody really spoke up for these two being useful, conda in particular.

**Review by galipremsagar — APPROVED** [review]

**Comment by bdice** [comment]
I thought some more. If you think removing those labels makes things easier / cleaner, go ahead and delete them. It's not important to me.

**Pull request merged**
