### PR TITLE
Remove mr from test fixtures

### PR DESCRIPTION
**Pull request by vyasr**
## Description

This is a follow-up to #14057. The PR was split in two because in that PR this particular change led to an unexpected and very specific test failure (see https://github.com/rapidsai/cudf/pull/14057#issuecomment-1712340714). If this PR reproduces that issue we will need to debug more closely on the appropriate hardware.

## Checklist
- [x] I am familiar with the [Contributing Guidelines](https://github.com/rapidsai/cudf/blob/HEAD/CONTRIBUTING.md).
- [x] New or existing tests cover these changes.
- [x] The documentation is up to date with these changes.

### CODE REVIEW

**Review by harrism — APPROVED** [review]

**Review by karthikeyann — APPROVED** [review]
Change looks good to me!

**Comment by karthikeyann** [comment]
Same tests failed as https://github.com/rapidsai/cudf/actions/runs/6126279847/job/16630671974?pr=14057
doesn't seem random, but can't find a pattern either.
No errors while running it with `valgrind`, `compute-sanitizer` (memcheck, racecheck, initcheck, synccheck)
```
[  FAILED  ] 5 tests, listed below:
[  FAILED  ] RoundRobinTest/4.RoundRobinNPartitionsDivideNRows, where TypeParam = unsigned char
[  FAILED  ] RoundRobinTest/7.RoundRobinNPartitionsDivideNRows, where TypeParam = unsigned long
[  FAILED  ] RoundRobinTest/10.RoundRobinNPartitionsDivideNRows, where TypeParam = double
[  FAILED  ] RoundRobinTest/15.RoundRobinNPartitionsDivideNRows, where TypeParam = cuda::std::__4::chrono::time_point<cuda::std::__4::chrono::system_clock,cuda::std::__4::chrono::duration<long,cuda::std::__4::ratio<1l,1000000000l> > >
[  FAILED  ] RoundRobinTest/23.RoundRobinNPartitionsDivideNRows, where TypeParam = numeric::fixed_point<__int128,(numeric::Radix)10>

 5 FAILED TESTS
```

**Comment by vyasr** [comment]
@robertmaynard and I have both spent some time trying to investigate the issues here. We were unable to reproduce on at least one other arm node, and Robert said he was not able to reproduce this using CUDA 12. Since the issue appears to be very specific and compiler-related, I'm going to close this PR for now. The plan will be to reopen this once we drop CUDA 11 support since the issue appears to be specific to CUDA 11.

**Comment by vyasr** [comment]
Tracking in #14236

**Pull request closed without merging**
