### PR TITLE
[REVIEW] Update dask make_meta changes to be compatible with dask upstream

### PR DESCRIPTION
**Pull request by galipremsagar**
This PR updates the `make_meta` dispatch renaming to be compatible and back-ward compatible with latest dask and older versions of dask respectively.

This PR needs upstream dask changes: https://github.com/dask/dask/pull/7743

### CODE REVIEW

**Comment by galipremsagar** [comment]
rerun tests

**Review by jakirkham — APPROVED** [review]

**Comment by galipremsagar** [comment]
@gpucibot merge

**Comment by quasiben** [comment]
rerun tests

**Comment by jakirkham** [comment]
Think we need to merge PR ( https://github.com/rapidsai/dask-cuda/pull/637 ) first for CI to pass

**Comment by jakirkham** [comment]
rerun tests

(dask-cuda packages are up)

**Pull request merged**
