### PR TITLE
Fix regex handling of fixed quantifier with 0 range

### LINKED ISSUE #17065: [BUG] 0 range regexp appear to be broken
**Describe the bug**
I recently was testing some spark cases and ran into some failures related to 0 range patterns.

- `A{0,}` for replaceRegexp NON_CAPTURE
- `A{0,5}` for replaceRegexp NON_CAPTURE
- `[a0-9]{0,2}` for replaceRegexp NON_CAPTURE
- `(?:ab){0,3}` for containsRe NON_CAPTURE

These were for  the java APIs, but it should apply to python too. The patch https://github.com/rapidsai/cudf/pull/16798 appears to have caused this some how.

The differences in replace appear to show that it no longer honors the 0 in the range some of the time. For example the pattern `A{0,}` being replaced with PROD for an input of 'TEST A' produces 'TEST PROD'. But before it would match everywhere and produce 'PRODTPRODEPRODSPRODTPROD PROD PRODPROD'. I think that is an issue for python too

```python
>>> re.sub("A{0,}","PROD","TEST A")
'PRODTPRODEPRODSPRODTPROD PRODPROD'
```

**Steps/Code to reproduce bug**
The tests failing in Spark are 

```
FAILED ../../src/main/python/regexp_test.py::test_regexp_replace_digit[DATAGEN_SEED=1728593263, TZ=UTC] - AssertionError: GPU and CPU string values are different at [0, 'regexp_repl...
FAILED ../../src/main/python/regexp_test.py::test_re_replace_repetition[DATAGEN_SEED=1728593263, TZ=UTC] - AssertionError: GPU and CPU string values are different at [0, 'regexp_repl...
FAILED ../../src/main/python/regexp_test.py::test_regexp_memory_ok[DATAGEN_SEED=1728593263, TZ=UTC, INJECT_OOM] - AssertionError: GPU and CPU boolean values are different at [0, 'RLIKE(a, (...
```

But the examples above are the cleaned up versions of the tests. 

**Expected behavior**
It should behave like python or java regular expressions.

### PR DESCRIPTION
**Pull request by davidwendt**
## Description
Fixes regex logic handling of a pattern with a fixed quantifier that includes a zero-range.
Added new gtests for this specific case.
Bug was introduced in #16798 

Closes #17065

## Checklist
- [x] I am familiar with the [Contributing Guidelines](https://github.com/rapidsai/cudf/blob/HEAD/CONTRIBUTING.md).
- [x] New or existing tests cover these changes.
- [x] The documentation is up to date with these changes.

### CODE REVIEW

**Review by revans2 — APPROVED** [review]
All of the tests pass after this.

Thanks for the really quick fix.

**Review by vyasr — APPROVED** [review]
Well this is fun. Nice find Bobby. Out of curiosity: these are certainly valid regexes, but is there a good reason to use them?

**Review by mythrocks — APPROVED** [review]
I reviewed this on Friday, and neglected to 👍 it.

LGTM.

**Review by lamarrr — APPROVED** [review]

**Pull request merged**
