### PR TITLE
Minor code refactor for sorted_order

### PR DESCRIPTION
**Pull request by wbo4958**
the fast-path for single column sort will not use any sorted_indices, this PR just move the sorted_indices behind the single column sort code block

### CODE REVIEW

**Comment by davidwendt** [comment]
21.06 is in burndown https://docs.rapids.ai/maintainers
Perhaps move this to 21.08

**Comment by wbo4958** [comment]
> 21.06 is in burndown https://docs.rapids.ai/maintainers
> Perhaps move this to 21.08

Thx for the information, Done

**Comment by wbo4958** [comment]
build

**Comment by davidwendt** [comment]
rerun tests

**Review by harrism — APPROVED** [review]

**Comment by harrism** [comment]
rerun tests

**Comment by wbo4958** [comment]
rerun tests

**Comment by wbo4958** [comment]
rerun tests

**Comment by wbo4958** [comment]
rerun tests

**Comment by harrism** [comment]
Need to wait until CI is enabled for 21.08 -- waiting on RAPIDS metapackages.

**Comment by wbo4958** [comment]
rerun tests

**Comment by wbo4958** [comment]
@gpucibot merge

**Pull request merged**
