### PR TITLE
Fix fallback to sort aggregation for grouping only hash aggregate (21.12)

### PR DESCRIPTION
**Pull request by abellina**
This is a cherry-pick of https://github.com/rapidsai/cudf/commit/335862bf5bc8433d5d0896adf8210a13c5a21ab3 for the 21.12 branch.

I'll run a few tests with this, so posting as is (a clean cherry-pick) just to get the ball rolling.

### CODE REVIEW

**Comment by abellina** [comment]
Given CI is blocked because of:

> Branch Checker — Base branch is not under active development

I am not sure someone needs to pull this patch manually, or if this PR is the right approach.

**Review by jrhemstad — APPROVED** [review]

**Comment by abellina** [comment]
One thing that this is not doing is changing the version of the cudf jar artifact. I assume that comes later, as we'd want to publish a cudf 21.12.1.

**Review by mythrocks — APPROVED** [review]

**Comment by ajschmidt8** [comment]
> One thing that this is not doing is changing the version of the cudf jar artifact.
> 
> @ajschmidt8 should I change the version, or does that happen separately? There's the version in the jar itself (https://github.com/rapidsai/cudf/blob/branch-21.12/java/pom.xml#L24), and at least one from the cpp side (https://github.com/rapidsai/cudf/blob/branch-22.02/cpp/CMakeLists.txt#L28).

No need to touch the version strings. We will update any necessary strings during the hotfix release.

**Comment by abellina** [comment]
I've used a jar that I temporarily created as 21.12.1 and had it used with our plugin (21.12.0) as staged. I have run our hash aggregate integration tests that touch this code, and those passed. I'll also run all the tests and then run some benchmark code as well on our side to double check.

**Review by ttnghia — APPROVED** [review]

**Comment by abellina** [comment]
We ran more tests, including our Spark rapids CI against the would be 21.12.1 jar, and did not find issues. Thanks for the reviews!

**Pull request merged**
