### PR TITLE
Increase max RLE stream size estimate to avoid potential overflows

### PR DESCRIPTION
**Pull request by vuule**
Issue https://github.com/rapidsai/cudf/issues/9478

Increase the max RLE stream size to account for the fact that varint encoding encodes 7 bits pre byte.
Remove unused flush parameter in `integerRLE` kernel.

### CODE REVIEW

**Review by rgsl888prabhu — APPROVED** [review]

**Comment by rgsl888prabhu** [comment]
Is it possible to add a small test case ?

**Comment by vuule** [comment]
> Is it possible to add a small test case ?

Working on it, it's a bit tricky to avoid all benefits of RLE encoding :)

**Comment by vuule** [comment]
@rgsl888prabhu Update on testing: 
added a test that reads a valid file (with correct stream sizes, so no overlap), writes it again to an ORC file and tries to read the result with pyarrow. Without this PR, pyarrow segfaults, and with the PR it reads the data correctly. It's a bit of a weird test, but AFAICT it's valid.

**Review by rgsl888prabhu — APPROVED** [review]

**Comment by vuule** [comment]
rerun tests

**Review by hyperbolic2346 — APPROVED** [review]

**Comment by vuule** [comment]
rerun tests

**Review by bdice — APPROVED** [review]
Python looks good. 👍

**Comment by vuule** [comment]
@gpucibot merge

**Comment by vuule** [comment]
rerun tests

**Comment by vuule** [comment]
looks like branch checker is stuck :\

**Comment by galipremsagar** [comment]
@gpucibot merge

**Comment by galipremsagar** [comment]
rerun tests

**Comment by galipremsagar** [comment]
rerun tests

**Comment by galipremsagar** [comment]
> looks like branch checker is stuck :\

Switching the base branch to `21.10` and back again to `21.12` did the trick. But tagging @ajschmidt8 for visibility just in case you may see this in the future again.

**Pull request merged**
