### PR TITLE
[REVIEW] to_frame now accepts name argument

### PR DESCRIPTION
**Pull request by quasiben**
Resolves https://github.com/rapidsai/cudf/issues/1161

### CODE REVIEW

**Comment by quasiben** [comment]
@kkraus14 This works locally.  Can you remind me how to retest something from GH ?  is it `retest` ?

**Comment by quasiben** [comment]
rerun tests
\

**Comment by kkraus14** [comment]
add to whitelist

**Comment by kkraus14** [comment]
rerun tests

**Comment by quasiben** [comment]
Thanks @kkraus14

**Comment by kkraus14** [comment]
Going to try closing and reopening to trigger CI.

**Pull request merged**
