### PR TITLE
Fix accessing `.columns` by an external API

### PR DESCRIPTION
**Pull request by galipremsagar**
## Description
`pa.pandas_compat.construct_metadata` seems to be accessing `.columns` of `cudf.DataFrame`, this is unsafe and expensive, so instead this PR will only return empty rows and only a pandas DataFrame. While doing so, uncovered and fixed issues with column type preservation in `head` API.

## Checklist
- [x] I am familiar with the [Contributing Guidelines](https://github.com/rapidsai/cudf/blob/HEAD/CONTRIBUTING.md).
- [x] New or existing tests cover these changes.
- [x] The documentation is up to date with these changes.

### CODE REVIEW

**Review by bdice — APPROVED** [review]
Nice! This looks like a good fix for the original problem and the bug you found along the way.

**Review by ttnghia — APPROVED** [review]

**Comment by bdice** [comment]
I proposed an admin merge on both #15212 (this PR) and #15210. I think that's the best path forward to unblocking CI failures.

**Pull request merged**
