### PR TITLE
Use no-sync copy for fixed-width types in cudf::concatenate

### LINKED ISSUE #17172: [PERF] Remove stream sync in concatenate for better pipelining
Concatenate function uses `thrust::copy` in its implementation but throws away the return value from `thrust::copy`. Since `thrust::copy` needs to return an iterator it leads to an unnecessary stream sync.
https://github.com/rapidsai/cudf/blob/2de545b41ce936dabfaa47e7d482e707dcf7df62/cpp/src/copying/concatenate.cu#L310

### PR DESCRIPTION
**Pull request by davidwendt**
## Description
Replacing `thrust::copy` with `cudaMemcpyAsync` improves performance upto 2x in specific cases in `cudf::concatenate`
The `thrust::copy` does a sync for device-to-device copy though it is not necessary.  Using `rmm::exec_policy_nosync` had no effect. Will work with CCCL to determine if this is a bug in `thrust::copy` since computing the return value does not require a sync.

Also moved the benchmark for concatenate from googlebench to nvbench.

Closes #17172 

## Checklist
- [x] I am familiar with the [Contributing Guidelines](https://github.com/rapidsai/cudf/blob/HEAD/CONTRIBUTING.md).
- [x] New or existing tests cover these changes.
- [x] The documentation is up to date with these changes.

### CODE REVIEW

**Comment by davidwendt** [comment]
Less significant improvement for larger columns
```
## [0] NVIDIA RTX A6000

|  num_rows | num_cols |  nulls  |   Ref Time |   Cmp Time |       Diff |   %Diff |
|-----------|----------|---------|------------|------------|------------|---------|
|  2000000  |    2     |    0    | 114.436 us | 102.196 us | -12.239 us | -10.70% |
|  4000000  |    2     |    0    | 203.199 us | 190.811 us | -12.388 us |  -6.10% |
|  10000000 |    2     |    0    | 469.245 us | 456.899 us | -12.345 us |  -2.63% |
| 100000000 |    2     |    0    |   4.459 ms |   4.445 ms | -14.445 us |  -0.32% |
|  2000000  |    2     |   0.3   | 114.514 us | 102.074 us | -12.440 us | -10.86% |
|  4000000  |    2     |   0.3   | 203.316 us | 190.778 us | -12.538 us |  -6.17% |
|  10000000 |    2     |   0.3   | 469.317 us | 456.894 us | -12.423 us |  -2.65% |
| 100000000 |    2     |   0.3   |   4.458 ms |   4.445 ms | -13.113 us |  -0.29% |
```

**Review by vyasr — APPROVED** [review]
Should we open a CCCL issue or do you want to start on Slack? Other than that, change looks great.

**Comment by davidwendt** [comment]
> Should we open a CCCL issue or do you want to start on Slack? Other than that, change looks great.

I'm still looking through the code a bit. I will likely open an issue with some details.

**Review by vuule — APPROVED** [review]

**Comment by vuule** [comment]
Do we know for sure that the difference is because of the sync?

**Comment by davidwendt** [comment]
> Do we know for sure that the difference is because of the sync?

Yes. An nsys trace shows calls to `cudaStreamSynchronize` in each for-loop iteration before the change no sync calls after.

**Comment by davidwendt** [comment]
Found an existing CCCL issue: https://github.com/NVIDIA/cccl/issues/1474
And added a PR for the possible fix there: https://github.com/NVIDIA/cccl/pull/3149

**Pull request merged**
