### PR TITLE
[REVIEW] Bump cmake minimum version to 3.18 in dev environments

### PR DESCRIPTION
**Pull request by galipremsagar**
Fixes: #8001 

This PR changes the minimum CMake version to 3.18 at remaining places in the code-base.

### CODE REVIEW

**Review by Ethyling — APPROVED** [review]

**Comment by karthikeyann** [comment]
check these files as well.
conda/recipes/libcudf_kafka/meta.yaml
conda/recipes/cudf_kafka/meta.yaml

**Review by karthikeyann — APPROVED** [review]

**Comment by galipremsagar** [comment]
rerun tests

**Review by kkraus14 — APPROVED** [review]

**Comment by galipremsagar** [comment]
rerun tests

**Comment by galipremsagar** [comment]
rerun tests

**Comment by galipremsagar** [comment]
rerun tests

**Comment by galipremsagar** [comment]
@gpucibot merge

**Pull request merged**
