### PR TITLE
[REVIEW] Datetime Typecasting and fix empty column test

### PR DESCRIPTION
**Pull request by kkraus14**
Add support for typecasting to/from datetime dtype.

### CODE REVIEW

**Comment by kkraus14** [comment]
rerun tests

**Comment by kkraus14** [comment]
Fixes a test with empty columns that assumes dictionaries are ordered which is only true for Python 3.6+

**Comment by harrism** [comment]
Looks good to go.

**Comment by kkraus14** [comment]
Thanks @harrism merging.

**Pull request merged**
