### PR TITLE
[WIP] update gather_bitmask_kernel to use or remove unused template parameter

### PR DESCRIPTION
**Pull request by cwharris**
`gather_bitmask_kernel` isn't using its `ignore_out_of_bounds` type argument. Removing it.

### CODE REVIEW

**Comment by jrhemstad** [comment]
If it's not being used, then that sounds like a bug that should be fixed, not removed.

**Comment by cwharris** [comment]
I'll try to prove/disprove a bug exists for this, and go from there.

**Comment by jrhemstad** [comment]
You can see how it was used in the old `gather_bitmask_kernel` https://github.com/rapidsai/cudf/blob/branch-0.11/cpp/src/copying/legacy/gather.cuh#L83

**Comment by cwharris** [comment]
This is closed by #3354.

**Pull request closed without merging**
