### PR TITLE
Move standalone UTF8 functions from string_view.hpp to utf8.hpp

### PR DESCRIPTION
**Pull request by davidwendt**
Move some standalone UTF8 functions that were defined in `string_view.hpp` to a new `details/utf8.hpp`. While working on #10270 and reworking some regex utilities, the standalone functions are useful without needing to include the `string_view` class definition. These can be included and used in `.cpp` host source files as needed as well.

This is purely for cleanup and convenience. No actual functions have been added, updated or removed.

### CODE REVIEW

**Review by PointKernel — APPROVED** [review]
LGTM

**Review by ajschmidt8 — APPROVED** [review]
Approving `ops-codeowner` file changes

**Review by ttnghia — APPROVED** [review]

**Comment by davidwendt** [comment]
@gpucibot merge

**Comment by Ethyling** [comment]
@gpucibot merge

**Pull request merged**
