### PR TITLE
Refactor pad_side and strip_type enums into side_type enum

### PR DESCRIPTION
**Pull request by davidwendt**
## Description
Refactors the `cudf::strings::pad_side` and `cudf::strings::strip_type` to a single enum `cudf::strings::side_type`.
These have the same values as used by `cudf::strings::pad` and `cudf::strings::strip`
Moving these into a single header helps with reusing them in the `strings_udf` work.
Updates to gtests and cython code layers are also included.

## Checklist
- [x] I am familiar with the [Contributing Guidelines](https://github.com/rapidsai/cudf/blob/HEAD/CONTRIBUTING.md).
- [x] New or existing tests cover these changes.
- [x] The documentation is up to date with these changes.

### CODE REVIEW

**Review by galipremsagar — APPROVED** [review]

**Review by jlowe — APPROVED** [review]

**Review by ajschmidt8 — APPROVED** [review]
Approving `ops-codeowner` file changes

**Review by robertmaynard — APPROVED** [review]

**Comment by davidwendt** [comment]
This should be marked as a _breaking change_ since the public enums have been moved/renamed.

**Review by bdice — APPROVED** [review]
Code looks good. Naming questions: would `side_type` be better to call something like “alignment” or “justification”? That might work for padding but maybe not for stripping. I am unsure if we’re generalizing something that should actually be distinctly named between the algorithms (despite having similar options), due to the difference in its action. For example, I could imagine an alternative world where padding is a float where 0 corresponds to left, 0.5 to center, and 1 to right. This would make a lot of sense for text layout (terminal or HTML-like) applications, but a float like that wouldn’t be as sensible for a strip algorithm. I suppose we could always split these types again in the future if we needed.

**Comment by davidwendt** [comment]
@gpucibot merge

**Pull request merged**
