### PR TITLE
[REVIEW] Add cudf::make_dictionary_from_scalar factory function

### PR DESCRIPTION
**Pull request by davidwendt**
Another item for #5963 

The current `make_column_from_scalar` uses the scalar's type to create the column. This is not possible for creating a dictionary column since there is no scalar dictionary type. Added `cudf::make_dictionary_from_scalar` which simply creates the keys column using the scalar and the sets the indices column to all `0` values as appropriate. For this reason, an invalid scalar is not allowed when creating a dictionary since a valid key is required.

This PR also includes gtests for the create and the error check for invalid scalar.

### CODE REVIEW

**Comment by davidwendt** [comment]
rerun tests

**Comment by davidwendt** [comment]
rerun tests

**Comment by davidwendt** [comment]
rerun tests

**Review by codereport — APPROVED** [review]
LGTM

**Review by nvdbaranec — APPROVED** [review]
Looks good.

**Pull request merged**
