### PR TITLE
[REVIEW] Fix failing test for issue #416

### LINKED ISSUE #416: Can't build cudf using CUDA-10.0
- [x] I am using the latest version of cuDF from conda, built from `master`, or
built from the latest tagged release. 
- [x] I have included the version or commit hash I am using for reference.
cudf commit 43e8f2b1bd23933fbda62a049dcd34dcfed62577
- [x] I have included the following environment details:
```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.5 LTS
Release:        16.04
Codename:       xenial
$ uname -r
4.4.0-134-generic
$ nvidia-smi
Wed Nov 28 13:17:02 2018       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 410.72       Driver Version: 410.72       CUDA Version: 10.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla V100-SXM2...  On   | 00000000:06:00.0 Off |                    0 |
| N/A   32C    P0    45W / 300W |      0MiB / 32480MiB |      0%      Default |
```
## Issue

The master branch of cudf won't build `map_test.cu` using CUDA-10. Following specifically the instructions for building and installing cudf in the README, when `make -j` is performed, the build fails due to 
```
/usr/local/cuda-10.0/targets/x86_64-linux/include/thrust/system/cuda/detail/parallel_for.h(98): error: identifier "std::pair<unsigned long long, unsigned long long> ::operator =" is undefined in device code

/usr/local/cuda-10.0/targets/x86_64-linux/include/thrust/system/cuda/detail/parallel_for.h(98): error: calling a __host__ function("std::pair<unsigned long long, unsigned long long> ::operator =") from a __device__ function("thrust::cuda_cub::__parallel_for::ParallelForAgent< ::thrust::cuda_cub::__transform::unary_transform_f< ::thrust::pointer< ::std::pair<unsigned long long, unsigned long long> ,  ::thrust::cuda_cub::tag,  ::thrust::use_default,  ::thrust::use_default> ,  ::std::pair<unsigned long long, unsigned long long>  *,  ::thrust::cuda_cub::__transform::no_stencil_tag,  ::thrust::identity< ::std::pair<unsigned long long, unsigned long long> > ,  ::thrust::cuda_cub::__transform::always_true_predicate> , long> ::consume_tile<(bool)0> ") is not allowed
```

The `std::vector<std::pair<key_type,value_type>> pairs;` in `map_test.cu:130` needs to be updated to `std::vector<thrust::pair<key_type,value_type>> pairs;`.

### PR DESCRIPTION
**Pull request by thomcom**
This minor change fixes #416 and gets CUDA-10 building and all tests passing.

### CODE REVIEW

**Comment by jrhemstad** [comment]
add to whitelist

**Comment by kkraus14** [comment]
add to whitelist

**Comment by kkraus14** [comment]
@thomcom can you modify the conda build scripts to not run the sed command when CUDA is detected as version 10 as well?

**Comment by thomcom** [comment]
Ah, yes, I'll get rid of those exclusions.

**Comment by thomcom** [comment]
👍

**Comment by mt-jones** [comment]
Woot woot @thomcom !!

**Comment by kkraus14** [comment]
Changes LGTM. Will merge once CI wakes up :)

**Comment by kkraus14** [comment]
Going to try closing it and reopening it to trigger CI.

**Comment by raydouglass** [comment]
run tests

**Comment by kkraus14** [comment]
add to whitelist

**Pull request merged**
