### PR TITLE
[REVIEW] Fix typo in column_buffer.hpp docs [skip-ci]

### PR DESCRIPTION
**Pull request by goodengineer**
small typo fix

### CODE REVIEW

**Comment by GPUtester** [comment]
Can one of the admins verify this patch?

**Comment by GPUtester** [comment]
Can one of the admins verify this patch?

**Comment by GPUtester** [comment]
Can one of the admins verify this patch?

**Comment by harrism** [comment]
@goodengineer thanks for the contribution. We are in the middle of a release (v0.15), so I've retargeted this PR to the next release branch (branch-0.16).

**Review by davidwendt — APPROVED** [review]

**Comment by harrism** [comment]
I don't think we want to clutter the changelog with this. It's already more work than its worth for a single-word doc change.

**Comment by harrism** [comment]
On the other hand I can't even admin merge  it.

**Comment by kkraus14** [comment]
> On the other hand I can't even admin merge it.

There was an ask made to combine the typo fixes in #6064 into here that we were waiting on before merging.

**Comment by harrism** [comment]
This has been  incorporated into #5861

**Pull request closed without merging**
