### PR TITLE
[REVIEW] IO Readers: Consolidate all readers to use `datasource` class

### LINKED ISSUE #1574: [FEA] Consolidate input source for CSV/JSON/Parquet/ORC and other readers
**Is your feature request related to a problem? Please describe.**
Currently, most of the readers implement different ways of reading either files or buffers or Arrow sources.

**Describe the solution you'd like**
All common interface that is used by all readers to get source data, but that is flexible enough to handle various source types (file, memory, Arrow, GPU-DIRECT, etc.)

**Describe alternatives you've considered**
Use existing Arrow IO classes as-is rather than as another source type. This would tie the IO readers to Arrow and impose a strict dependency.

Disadvantage is that some sources (such as GPU-DIRECT) do not have Arrow implementations yet or the Arrow IO interfaces may not be suitable for our usage (i.e. easily retrieve source data in either host or device memory).

**Additional context**
The implementation of the interface could be backed by existing Arrow classes or use our own native memory map calls for files.

### PR DESCRIPTION
**Pull request by j-ieong**
Fixes #1574.

* Implement a mmap-based `datasource` for files
    - Arrow's version does not handle offset padding
* Switch JSON and CSV readers to `datasource`
    - push the `mmap` padding into the mmap class rather than each reader
* Remove no longer used memory mapped `file_utils.cpp` and `file_utils.hpp`
* Use lowercase naming for conformance

### CODE REVIEW

**Comment by wesm** [comment]
> Arrow's version does not handle offset padding

Could you elaborate on this? Is there a JIRA that could be opened in Arrow?

**Comment by j-ieong** [comment]
> > Arrow's version does not handle offset padding
> 
> Could you elaborate on this? Is there a JIRA that could be opened in Arrow?

Sure. From what I can see, Arrow's `MemoryMappedFile` maps or remaps to a specific size but it's always from the start of the file (last parameter to `mmap()` is always 0).
https://github.com/apache/arrow/blob/6f98807e3a5e68820e70c775bf97b5871c5e7f86/cpp/src/arrow/io/file.cc#L519

We may only want to map a portion from a specific offset (ex. read last half of the file).

**Comment by wesm** [comment]
OK. Can you open a JIRA issue?

**Comment by wesm** [comment]
Here you go: https://issues.apache.org/jira/browse/ARROW-6141. I would appreciate if you would propose improvements to the Arrow libraries rather than working around issues you run into

**Pull request merged**
