### PR TITLE
[REVIEW] Reduce mem usage by categorical `codes`,  when they have null(s).

### PR DESCRIPTION
**Pull request by philtrade**
When categorifying a column with null value entry, `as_categorical_column()`would see 2 cases where the `labels` type is 2x the necessary size.

In the 1st case, `cudf` uses 2x the memory as `pandas`.
In the 2nd case, `cudf` uses about the same as `pandas`, but *could use only half of that with this fix*.  Thus a question to reviewers, *is this 2nd case worth optimizing for, as it depends on cudf's design choice?*

In `column.py`, `as_categorical_column()` says:
```
        # columns include null index in factorization; remove:
        if self.has_nulls:
            cats = cats.dropna()
            labels = labels - 1
```

#### Case 1: number of categories **<** `np.iinfo(dtype).max` + null entry in the labels.  Say 1 < n_cat < 127, `int8` should suffice.

After `labels = labels - 1`, `labels`'s `dtype` is bumped to `int16` from `int8`, because down the rabbit trail the code decides `int8` minus `int8` needs `int16`, even though `labels.min()` will only be -1, well covered by `int8`.

For 1 < no. of cats < 127 , `cudf` uses 2x the memory as `pandas`:
```
import pandas as pd, cudf as gd
x = pd.DataFrame({'a': ['foo']*10000 + [None]}).astype('category')
y = gd.DataFrame({'a': ['foo']*10000 + [None]}).astype('category')
x126 = pd.DataFrame({'a': list(range(126))*10000 + [None]}).astype('category')
y126 = gd.DataFrame({'a': list(range(126))*10000 + [None]}).astype('category')

print(f"pd: {x['a'].memory_usage()}, cudf: {y['a'].memory_usage()}")
print(f"pd126: {x126['a'].memory_usage()}, cudf126: {y126['a'].memory_usage()}")
```
shows:
```
pd: 10217, cudf: 21290
pd126: 1266257, cudf126: 2678514
```
Ouch.

#### Case 2: number of categories **==** `np.iinfo(dtype).max`, plus null entry in the labels. e.g 127 non-null categories.

In this case, originally `cats` has 128 "things"  [ 0..126 + None ] -- hence it uses `int16` to encode `labels`.    Next, `cats.dropna()` keeps only 127 things (fits in `int8`),  but `labels - 1` stays at `np.int16` (thank God the code doesn't upcast it to `int32`!)

Here, both `pandas` and `cudf` use `int16`, thus about 2x as much memory as the 126-categories case.  `Pandas` must, because it uses -1 as the `na-sentinel` in the `cat.codes`. 

```
x127 = pd.DataFrame({'a': list(range(127))*10000 + [None]}).astype('category')
y127 = gd.DataFrame({'a': list(range(127))*10000 + [None]}).astype('category')
print(f"pd127: {x127['a'].memory_usage()}, cudf127: {y127['a'].memory_usage()}")
```
gives:
```
pd127: 2546266, cudf127: 2699802
```
Notice `pandas` memory usage doubled from 126 items previously.

----

With this PR, the memory usage is on par with `pandas` in the first case, and can be 1/2 of `pandas`'s in the second case.

```
pd: 10217, cudf: 11289
pd126: 1266257, cudf126: 1418513
pd127: 2546266, cudf127: 1429801 
```

Now the question is, ***is **case 2** worth optimizing for?*** That is, say `cats` only has 127 categories after the `dropna()`, is it considered correct to use `int8` for the corresponding codes, and rely on `null_bitmasks` for the null entries?

### CODE REVIEW

**Comment by GPUtester** [comment]
Can one of the admins verify this patch?

**Comment by kkraus14** [comment]
ok to test

**Comment by kkraus14** [comment]
@philtrade could you add a line to `CHANGELOG.md` with a brief description of the change made? This is required to kick off CI to test the code. Thanks!

**Comment by GPUtester** [comment]
Please update the changelog in order to start CI tests.

View the gpuCI docs [here](https://docs.rapids.ai/gpuci#open-pr-or-update-pr).

**Comment by kkraus14** [comment]
ok to test

**Comment by kkraus14** [comment]
This is good to go, thanks for your contribution @philtrade! Will merge once CI reports green.

**Comment by philtrade** [comment]
Thanks @kkraus14 for taking care of the last substantial merge 🙏🏻🙏🏻

**Pull request merged**
