### PR TITLE
[REVIEW] Fix header not being included in legacy jit transform.

### PR DESCRIPTION
**Pull request by devavret**
Legacy transform was broken because of the changes in #5022 . Specifically [this diff](https://github.com/rapidsai/cudf/pull/5022/files#diff-ced24843bdfb76c327ae4f0511895bbcR22-R32), which caused header `types.hpp` to not be included in the kernel string anymore. This fixes it.

### CODE REVIEW

**Comment by GPUtester** [comment]
Please update the changelog in order to start CI tests.

View the gpuCI docs [here](https://docs.rapids.ai/gpuci#open-pr-or-update-pr).

**Comment by vuule** [comment]
Is there an issue filed for this?

**Comment by vuule** [comment]
Looking at the diff that caused the issue, it looks to me like the types header is still included in CUDA headers (`kernel_header`). If I understand this PR, you are adding the types header include to all CUDA files. Should you remove the types header from `kernel_header` to avoid duplication?

**Comment by devavret** [comment]
> Is there an issue filed for this?

Just a slack convo.

> Looking at the diff that caused the issue, it looks to me like the types header is still included in CUDA headers (`kernel_header`). If I understand this PR, you are adding the types header include to all CUDA files. Should you remove the types header from `kernel_header` to avoid duplication?

`kernel_header` isn't used for includes in legacy implementation. Cannot use it either because it contains the two other headers that legacy doesn't have.

**Comment by vuule** [comment]
> `kernel_header` isn't used for includes in legacy implementation. Cannot use it either because it contains the two other headers that legacy doesn't have.
Is kernel used for legacy includes? I'm trying to understand how [diff](https://github.com/rapidsai/cudf/pull/5022/files#diff-ced24843bdfb76c327ae4f0511895bbcR22-R32) caused the issue.

**Comment by devavret** [comment]
`kernel` contains the string that will be a part of the source to jit compile. The final source to JIT compile used to be `UDF + kernel`, where the include of `types.hpp` appeared after the UDF string. This was fine as long as the UDF only used built-in types. But now, the UDFs can support timestamps so we need to modify the JIT string so that the order is like this: `headers + UDF + kernel`. This caused the headers to be moved into their own string variable. Legacy transform broke because it used to rely on the header being included in the `kernel` string variable.

**Comment by devavret** [comment]
rerun tests

**Pull request merged**
