### PR TITLE
[REVIEW] Port reductions to libcudf++

### PR DESCRIPTION
**Pull request by karthikeyann**
move legacy code PR for  https://github.com/rapidsai/cudf/issues/2943
- [x] move legacy
- [x] move legacy gtests

### CODE REVIEW

**Comment by harrism** [comment]
@karthikeyann per guidance, you should finish this PR to just move the old files to legacy, and then open a new PR to implement the new versions.

**Comment by karthikeyann** [comment]
@harrism I moved the new code to another PR. This PR is ready for review.

**Comment by jrhemstad** [comment]
@karthikeyann several conflicts that need to be addressed.

**Comment by karthikeyann** [comment]
@jrhemstad  conflicts resolved.

**Pull request merged**
