### PR TITLE
Recommending `miniforge` for conda install

### PR DESCRIPTION
**Pull request by mmccarty**
## Description
Recommending miniforge for conda install in README

## Checklist
- [ ] I am familiar with the [Contributing Guidelines](https://github.com/rapidsai/cudf/blob/HEAD/CONTRIBUTING.md).
- [ ] New or existing tests cover these changes.
- [ ] The documentation is up to date with these changes.

### CODE REVIEW

**Comment by mroeschke** [comment]
If interested there are a few more `README.md`s that specify miniconda

```bash
python/cudf/README.md:cuDF can be installed with conda (via [miniconda](https://docs.conda.io/projects/miniconda/en/latest/) or the full [Anaconda distribution](https://www.anaconda.com/download) from the `rapidsai` channel:
python/cudf_polars/README.md:cuDF can be installed with conda (via [miniconda](https://docs.conda.io/projects/miniconda/en/latest/) or the full [Anaconda distribution](https://www.anaconda.com/download) from the `rapidsai` channel:
python/libcudf/README.md:cuDF can be installed with conda (via [miniconda](https://docs.conda.io/projects/miniconda/en/latest/) or the full [Anaconda distribution](https://www.anaconda.com/download) from the `rapidsai` channel:
python/cudf_kafka/README.md:cuDF can be installed with conda (via [miniconda](https://docs.conda.io/projects/miniconda/en/latest/) or the full [Anaconda distribution](https://www.anaconda.com/download) from the `rapidsai` channel:
python/pylibcudf/README.md:cuDF can be installed with conda (via [miniconda](https://docs.conda.io/projects/miniconda/en/latest/) or the full [Anaconda distribution](https://www.anaconda.com/download) from the `rapidsai` channel:
python/custreamz/README.md:cuStreamz is installed with conda ([miniconda](https://conda.io/miniconda.html), or the full [Anaconda distribution](https://www.anaconda.com/download)) from the `rapidsai` or `rapidsai-nightly` channel:
```

**Comment by mmccarty** [comment]
Thanks, @mroeschke! I'll update those as well.

**Comment by mmccarty** [comment]
@mroeschke updated `custreamz` but I looks like the rest are fixed on the latest from `branch-24.10`

**Comment by bdice** [comment]
The rest are symlinked — this should be complete now.

**Pull request merged**
