### PR TITLE
[REVIEW] Make scalar destructor virtual.

### PR DESCRIPTION
**Pull request by nvdbaranec**
Ensures derived class destructors get called in all circumstances.

Closes https://github.com/rapidsai/cudf/issues/4396

### CODE REVIEW

**Comment by jrhemstad** [comment]
The dtor for `fixed_width_scalar` also needs to be virtual since `numeric` and `timestamp` scalars derive from it https://github.com/rapidsai/cudf/blob/bb2ebf088a2e0be8db0d364719cfb21b3c11ba5f/cpp/include/cudf/scalar/scalar.hpp#L117

**Comment by nvdbaranec** [comment]
Not needed.  Once you mark the base class as virtual, it's virtual all the way down.  I verified.

**Comment by jrhemstad** [comment]
Yeah, I suppose nothing will ever be deleted through a `fixed_width_scalar` pointer, so there isn't a need to make it virtual.

**Comment by nvdbaranec** [comment]
> Yeah, I suppose nothing will ever be deleted through a fixed_width_scalar pointer, so there isn't a need to make it virtual.

Let me verify that deleting a pointer from the middle of the hierarchy does what's expected.  I just tested deleting a scalar* that was a numeric_scalar.

**Comment by jrhemstad** [comment]
> Thanks for fixing this major embarrassment.

Happens to the best of us. Super easy to forget. Plus reviewers (like me) should have caught it too :roll_eyes:

**Comment by nvdbaranec** [comment]
> 
> 
>     Yeah, I suppose nothing will ever be deleted through a fixed_width_scalar pointer, so there isn't a need to make it virtual.
> 
> Let me verify that deleting a pointer from the middle of the hierarchy does what's expected. I just tested deleting a scalar* that was a numeric_scalar.

Confirming, it works.  

There's some info here.  Basically if your base class has a virtual destructor, you automatically do. 

https://isocpp.org/wiki/faq/virtual-functions

**Comment by nvdbaranec** [comment]
rerun tests

**Comment by kkraus14** [comment]
rerun tests

**Comment by nvdbaranec** [comment]
rerun tests

**Comment by kkraus14** [comment]
Going to try closing and reopening the PR to see if that triggers CI.

**Comment by mike-wendt** [comment]
rerun tests

**Comment by jlowe** [comment]
Was it intentional to merge this only to 0.14?  This is an important fix to avoid permanently fragmenting device memory for the lifetime of a cudf application.

**Comment by harrism** [comment]
Looks like @kkraus14 had it in the 0.13 project, but @nvdbaranec must have set the branch to 0.14.

**Comment by jrhemstad** [comment]
> Looks like @kkraus14 had it in the 0.13 project, but @nvdbaranec must have set the branch to 0.14.

@nvdbaranec asked me what release and since codefreeze was fast approaching, I said 0.14. Of course, this was before the release was pushed back a few times.

**Pull request merged**
