### PR TITLE
Use make_strings_children for fill() specialization logic

### PR DESCRIPTION
**Pull request by davidwendt**
## Description
Refactors the `cudf::strings::detail::fill()` function to use `make_strings_children`. 
This refactors some duplicated logic and will help to enable large strings support.

## Checklist
- [x] I am familiar with the [Contributing Guidelines](https://github.com/rapidsai/cudf/blob/HEAD/CONTRIBUTING.md).
- [x] New or existing tests cover these changes.
- [x] The documentation is up to date with these changes.

### CODE REVIEW

**Review by vuule — APPROVED** [review]

**Comment by vuule** [comment]
What is the difference in behavior with https://github.com/rapidsai/cudf/pull/14697/commits/3de1ee5b3b3421c34f0b5539f2ba7fc622b2d821?
Looks like it's just calling copy_string with an empty string, I must be missing something.

**Comment by davidwendt** [comment]
> What is the difference in behavior with [3de1ee5](https://github.com/rapidsai/cudf/commit/3de1ee5b3b3421c34f0b5539f2ba7fc622b2d821)? Looks like it's just calling copy_string with an empty string, I must be missing something.

Just a subtle improvement. The current commit only calls `element()` when necessary.
The previous commit called it for every row and threw it away if it was not needed.
This is more inline with original code as well.

**Comment by vuule** [comment]
> > What is the difference in behavior with [3de1ee5](https://github.com/rapidsai/cudf/commit/3de1ee5b3b3421c34f0b5539f2ba7fc622b2d821)? Looks like it's just calling copy_string with an empty string, I must be missing something.
> 
> Just a subtle improvement. The current commit only calls `element()` when necessary. The previous commit called it for every row and threw it away if it was not needed. This is more inline with original code as well.

oh, that was not the fix for tests? I misunderstood and spent too much time staring at the diff. I'll take a look at the other new commit as well.

**Review by ttnghia — APPROVED** [review]

**Pull request merged**
