### PR TITLE
 [REVIEW] Remove old NVTX functionality

### LINKED ISSUE #4326: [FEA] Remove old NVTX functionality
**Is your feature request related to a problem? Please describe.**

Once https://github.com/rapidsai/cudf/issues/4312 is merged, the old NVTX functionality should be removed. Specifically, the contents of https://github.com/rapidsai/cudf/tree/branch-0.13/cpp/src/utilities/nvtx

Users that depended on this functionality are free to either use the new stuff added in https://github.com/rapidsai/cudf/issues/4312 or make native language NVTX bindings (recommended).

### PR DESCRIPTION
**Pull request by millerhooks**
closes #4326

### CODE REVIEW

**Comment by millerhooks** [comment]
rerun tests

**Comment by harrism** [comment]
`[FEA]` is only used on issue titles. For PRs, use `[REVIEW]` or `[WIP]`.

**Comment by millerhooks** [comment]
I think I've got a handle on the nvtx3 tools. Thank you for the clarification.

**Comment by millerhooks** [comment]
@kkraus14 Am removing all instances of nvtx that isn't nvtx3 or am I replacing those instances of usage with nvtx3 domains/ranges/etc?

**Comment by kkraus14** [comment]
> @kkraus14 Am removing all instances of nvtx that isn't nvtx3 or am I replacing those instances of usage with nvtx3 domains/ranges/etc?

We don't have new Python interfaces to the nvtx code in place yet so I don't think you can really remove anything other than the legacy code currently.

**Comment by millerhooks** [comment]
So to be clear, should be removing things like `cudf::nvtx::range_push("CUDF_ROLLING_WINDOW", cudf::nvtx::color::ORANGE);` and `cudf::nvtx::range_pop();` from `rolling.cu` for instance?

**Comment by kkraus14** [comment]
> So to be clear, should be removing things like `cudf::nvtx::range_push("CUDF_ROLLING_WINDOW", cudf::nvtx::color::ORANGE);` and `cudf::nvtx::range_pop();` from `rolling.cu` for instance?

No. The C++ has already been updated based on the new `nvtx3` infrastructure. The Python is still using the `nvtx` infrastructure but requires a new standalone binding layer that @shwina has been working on.

**Comment by millerhooks** [comment]
Ok. Awesome.

**Comment by kkraus14** [comment]
@millerhooks we shouldn't be stripping out the existing Python/Cython nvtx infrastructure until we have something new to replace it with...

**Comment by millerhooks** [comment]
I am syncing with @shwina on his nvtx3 implementation. Is the legacy removal urgent before his work is complete? I was thinking I could close this PR by tracking with him as he rolls out what he's working on. He says another week before the bindings will be incorporated. ~1 month for completion. In the mean time I can focus on other PRs. 

If it's urgent to provide a transitional solution, I can also do that. I just may need a quick pair with someone for clarification on the details.

**Comment by kkraus14** [comment]
> I am syncing with @shwina on his nvtx3 implementation. Is the legacy removal urgent before his work is complete? I was thinking I could close this PR by tracking with him as he rolls out what he's working on. He says another week before the bindings will be incorporated. ~1 month for completion. In the mean time I can focus on other PRs.
> 
> If it's urgent to provide a transitional solution, I can also do that. I just may need a quick pair with someone for clarification on the details.

No it isn't urgent, lets just close this.

**Comment by millerhooks** [comment]
@kkraus14 - @shwina tells me he will have a PR tomorrow that will let me replace the current calls. I'd like to keep it open and wrap it up tomorrow if possible if that's cool.

**Pull request closed without merging**
