### PR TITLE
Revert "Add support for struct type in ORC writer (#9025)"

### PR DESCRIPTION
**Pull request by devavret**
This reverts commit 2c6b39bdd7a37e0aa8708ed4018d1ad360a4d104.

### CODE REVIEW

**Comment by vuule** [comment]
rerun tests

**Comment by karthikeyann** [comment]
code freeze started. 
will this draft PR be finally merged to 21.10 ?

**Comment by vuule** [comment]
this was opened to triage a CI issue, please don't merge :)

**Review by karthikeyann — CHANGES_REQUESTED** [review]
blocking

**Pull request closed without merging**
