### PR TITLE
Remove arrow_io_source

### PR DESCRIPTION
**Pull request by vyasr**
## Description

The `arrow_io_source` in libcudf only existed to support Python's pyarrow NativeFile integration, which was deprecated and removed in #16589.

## Checklist
- [x] I am familiar with the [Contributing Guidelines](https://github.com/rapidsai/cudf/blob/HEAD/CONTRIBUTING.md).
- [x] New or existing tests cover these changes.
- [x] The documentation is up to date with these changes.

### CODE REVIEW

**Review by lithomas1 — APPROVED** [review]
🙌

**Comment by lithomas1** [comment]
question:
Are we able to start removing Arrow linkages from pylibcudf I/O now?

**Comment by vyasr** [comment]
Not quite yet. We also need https://github.com/rapidsai/cudf/pull/16590 to go in. I'm making many smaller PRs since some changes depend on others while others are independent.

**Review by bdice — APPROVED** [review]

**Review by PointKernel — APPROVED** [review]

**Pull request merged**
