### PR TITLE
Fix ambiguous constructor compile error with devtoolset

### LINKED ISSUE #6334: [BUG] build error for `cpp/tests/io/parquet_test.cpp`
**Describe the bug**
```
/home/0.alpha/rapids.pkgs/20200917/cudf.dev.0.16.arena_memory_resource/cudf.dev/cpp/tests/io/parquet_test.cpp: In member function ‘virtual void ParquetWriterTest_MultipleMismatchedSources_Test::TestBody()’:
/home/0.alpha/rapids.pkgs/20200917/cudf.dev.0.16.arena_memory_resource/cudf.dev/cpp/tests/io/parquet_test.cpp:693:91: error: call of overloaded ‘source_info(<brace-enclosed initializer list>)’ is ambiguous
       cudf_io::parquet_reader_options::builder(cudf_io::source_info{{int5file, float5file}});
                                                                                           ^
In file included from /home/0.alpha/rapids.pkgs/20200917/cudf.dev.0.16.arena_memory_resource/cudf.dev/cpp/include/cudf/io/parquet.hpp:19:0,
                 from /home/0.alpha/rapids.pkgs/20200917/cudf.dev.0.16.arena_memory_resource/cudf.dev/cpp/tests/io/parquet_test.cpp:26:
/home/0.alpha/rapids.pkgs/20200917/cudf.dev.0.16.arena_memory_resource/cudf.dev/cpp/include/cudf/io/types.hpp:167:12: note: candidate: cudf::io::source_info::source_info(const string&)
   explicit source_info(std::string const& file_path)
            ^~~~~~~~~~~
/home/0.alpha/rapids.pkgs/20200917/cudf.dev.0.16.arena_memory_resource/cudf.dev/cpp/include/cudf/io/types.hpp:163:12: note: candidate: cudf::io::source_info::source_info(const std::vector<std::basic_string<char> >&)
   explicit source_info(std::vector<std::string> const& file_paths)
            ^~~~~~~~~~~
/home/0.alpha/rapids.pkgs/20200917/cudf.dev.0.16.arena_memory_resource/cudf.dev/cpp/tests/io/parquet_test.cpp:699:90: error: call of overloaded ‘source_info(<brace-enclosed initializer list>)’ is ambiguous
       cudf_io::parquet_reader_options::builder(cudf_io::source_info{{int5file, int10file}});
                                                                                          ^
In file included from /home/0.alpha/rapids.pkgs/20200917/cudf.dev.0.16.arena_memory_resource/cudf.dev/cpp/include/cudf/io/parquet.hpp:19:0,
                 from /home/0.alpha/rapids.pkgs/20200917/cudf.dev.0.16.arena_memory_resource/cudf.dev/cpp/tests/io/parquet_test.cpp:26:
/home/0.alpha/rapids.pkgs/20200917/cudf.dev.0.16.arena_memory_resource/cudf.dev/cpp/include/cudf/io/types.hpp:167:12: note: candidate: cudf::io::source_info::source_info(const string&)
   explicit source_info(std::string const& file_path)
            ^~~~~~~~~~~
/home/0.alpha/rapids.pkgs/20200917/cudf.dev.0.16.arena_memory_resource/cudf.dev/cpp/include/cudf/io/types.hpp:163:12: note: candidate: cudf::io::source_info::source_info(const std::vector<std::basic_string<char> >&)
   explicit source_info(std::vector<std::string> const& file_paths)
            ^~~~~~~~~~~
make[2]: *** [tests/CMakeFiles/PARQUET_TEST.dir/build.make:83: tests/CMakeFiles/PARQUET_TEST.dir/io/parquet_test.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1563: tests/CMakeFiles/PARQUET_TEST.dir/all] Error 2
make: *** [Makefile:161: all] Error 2

```

**Environment details**
commit 7e7b329857d5f849393982919ebfd1bc55601b4f
devtoolset-7
java/ci/build-in-docker.sh

### PR DESCRIPTION
**Pull request by jlowe**
Fixes #6334 

I was able to reproduce the ambiguous constructor build error with devtoolset-7 (based on GCC 7.3.1) and devtoolset-8 (based on GCC 8.3.1).  I can't readily explain why I do not see the error outside of the devtoolset environment with GCC 7.5.0, but it's easy to update the test so all the build environments are happy.

### CODE REVIEW

**Comment by GPUtester** [comment]
Please update the changelog in order to start CI tests.

View the gpuCI docs [here](https://docs.rapids.ai/gpuci#open-pr-or-update-pr).

**Review by vuule — APPROVED** [review]

**Comment by jlowe** [comment]
rerun tests

**Comment by jlowe** [comment]
rerun tests

**Comment by jlowe** [comment]
@harrism @kkraus14 would you be willing to merge this?  I've tried many times to get CI to work on this, but inevitably a couple of the runs fall victim to the seemingly random process killing and then fail.

**Pull request merged**
