### PR TITLE
Fix compiler warning about non-POD types passed through ellipsis

### PR DESCRIPTION
**Pull request by jrhemstad**
In https://github.com/rapidsai/cudf/pull/7725/ I updated some of the fall through error cases to use old, [C-style ellipsis variadics ](https://github.com/jrhemstad/cudf/blob/f92d4626c7a4296075c5aa6240d6e3b88049abe6/cpp/include/cudf/detail/gather.cuh#L145 
)since we don't care about the parameters in the error case. Turns out C++ forbids passing "non-POD" types through this kind of variadic ellipsis, which ends up generating a compiler warning:

> warning: non-POD class type passed through ellipsis

### CODE REVIEW

**Review by davidwendt — APPROVED** [review]

**Comment by jrhemstad** [comment]
rerun tests

**Comment by jrhemstad** [comment]
rerun tests

**Review by ttnghia — APPROVED** [review]

**Comment by ttnghia** [comment]
Rerun tests.

**Review by harrism — APPROVED** [review]

**Comment by harrism** [comment]
@gpucibot merge

**Pull request merged**
