### PR TITLE
[REVIEW] Add axis= and win_type= arguments to rolling for Dask compatibility

### LINKED ISSUE #2372: [BUG] Missing rolling window API arguments
Because our keyword arguments to `Rolling` do not match pandas, we get dask compatibility issues downstream.

In particular, we need to include `win_type` (defaulting to None) and `axis` (defaulting to 0)

### PR DESCRIPTION
**Pull request by shwina**
Closes #2372

### CODE REVIEW

**Comment by beckernick** [comment]
@shwina this will require a bit more. Sorry for not being more clear in the issue.

We need to add these keyword parameters to Series.rolling, and we also need the attributes self.axis and self.win_type

**Comment by shwina** [comment]
@beckernick is this better?

**Comment by kkraus14** [comment]
@shwina looks like a default parameter causes an exception to be thrown :)

**Comment by kkraus14** [comment]
@shwina Think we can resolve these issues before code freeze at EOD tomorrow?

**Comment by shwina** [comment]
run tests

**Pull request merged**
