### PR TITLE
[REVIEW] Fix for test_orc.py and test_sparse_df.py test failures

### PR DESCRIPTION
**Pull request by pradghos**
- .pkl and .orc files are not getting pulled
   into data directory used for cuDF pytests.
- Fixing https://github.com/rapidsai/cudf/issues/1464

### CODE REVIEW

**Comment by GPUtester** [comment]
Can one of the admins verify this patch?

**Comment by kkraus14** [comment]
ok to test

**Comment by pradghos** [comment]
@kkraus14 : Sorry for delayed update. new changes are ready for review. Thanks!

**Comment by kkraus14** [comment]
@pradghos apologies for the delay, looks like there's been some test updates that have caused a conflict that should be addressed. I also think it would be better to have it check if the file exists using normal file checking semantics as opposed to a try except, but we can do that in the future.

**Comment by pradghos** [comment]
> 
> 
> @pradghos apologies for the delay, looks like there's been some test updates that have caused a conflict that should be addressed. I also think it would be better to have it check if the file exists using normal file checking semantics as opposed to a try except, but we can do that in the future.

Sure @kkraus14 ; I have just resolved the merge conflict in the latest commit for now. Do you think its better to have issue opened to use `normal file checking semantics` and we can address other similar improvement via the same issue. Please let me know what do you suggest. Thank you !

**Comment by pradghos** [comment]
@kkraus14 : Please let me know if any other changes required for the final approval / merge. Thank you !

**Pull request merged**
