### PR TITLE
[REVIEW] Make `table_view_base.column()` const and add `mutable_table_view.column()`

### PR DESCRIPTION
**Pull request by shwina**

### CODE REVIEW

**Comment by kkraus14** [comment]
rerun tests

**Comment by kkraus14** [comment]
rerun tests

**Comment by jrhemstad** [comment]
CI is failing because the files merged in `https://github.com/rapidsai/cudf/pull/3080` include a header that was moved in https://github.com/rapidsai/cudf/pull/3202.

The include path for `error_utils.hpp` needs to be changed in `legacy/valid_if.cuh`.

**Comment by kkraus14** [comment]
> CI is failing because the files merged in `https://github.com/rapidsai/cudf/pull/3080` include a header that was moved in #3202.
> 
> The include path for `error_utils.hpp` needs to be changed in `legacy/valid_if.cuh`.

I was very confused because CI was only failing on one of the GPU workers and then I just assumed there was conda HTTP issues 😅

**Comment by kkraus14** [comment]
rerun tests

**Pull request merged**
