### PR TITLE
Use PyNVML 12

### PR DESCRIPTION
**Pull request by jakirkham**
## Description

Bump `pynvml` from `11` to `12`. This version of `pynvml` also now depends on `nvidia-ml-py` for core functionality.

Depends on PR: https://github.com/rapidsai/dask-cuda/pull/1419

## Checklist
- [ ] I am familiar with the [Contributing Guidelines](https://github.com/rapidsai/cudf/blob/HEAD/CONTRIBUTING.md).
- [ ] New or existing tests cover these changes.
- [ ] The documentation is up to date with these changes.

### CODE REVIEW

**Comment by jakirkham** [comment]
Will need to update to PyNVML 12 in Dask-CUDA before this will work. CI failures underline this point

**Comment by jakirkham** [comment]
Marking as ready for review. Will rerun CI after the Dask-CUDA PR lands

**Review by jameslamb — COMMENTED** [review]
Makes sense to me based on the other related changes, but I'd like to see CI results before approving.

**Comment by jakirkham** [comment]
All good. Wanted to see a rerun as well

Mainly stating that for context

In any event Dask-CUDA has rebuilt with those changes

So have pulled in the latest cuDF changes to refresh the PR and rerun CI. Let's see how it goes

**Review by pentschev — APPROVED** [review]
LGTM, thanks @jakirkham . Let's get this merged ASAP, as this is blocking cuDF's nightly build-docs.

**Review by raydouglass — APPROVED** [review]

**Comment by jakirkham** [comment]
Thanks Peter and Ray! 🙏

**Pull request merged**
