### PR TITLE
[WIP] Add append mode flag to CSV writer

### PR DESCRIPTION
**Pull request by trevorsm7**
Closes https://github.com/rapidsai/cudf/issues/4715

### CODE REVIEW

**Comment by davidwendt** [comment]
This PR is adding a feature to legacy code.
This code change should probably wait until after the csv writer is ported in #4484 
Also, I think #4715 should be a feature request since the append option does not actually exist and no documentation says it is supported -- so nothing is technically broken.

**Comment by trevorsm7** [comment]
>This PR is adding a feature to legacy code.
This code change should probably wait until after the csv writer is ported in #4484

Correct. I've also been looking into how this would be implemented for the new CSV writer via `cudf::io::data_sink` (which may also work for orc and parquet).

>Also, I think #4715 should be a feature request since the append option does not actually exist and no documentation says it is supported -- so nothing is technically broken.

I suppose that's true, though I think it's misleading that the cudf API takes a Python file handle, but internally actually reopens the file, ignoring any mode that had been set. I suppose an alternative solution would be to assert that the mode flag is set to write and defer adding modes to the API as a feature request as you suggest.

**Comment by harrism** [comment]
@trevorsm7 do you have a plan for this now that CSV writer port is done?

**Comment by trevorsm7** [comment]
> @trevorsm7 do you have a plan for this now that CSV writer port is done?

Yep, we had discussed another approach using `data_sink` in https://github.com/rapidsai/cudf/issues/4715 This PR can just be closed.

**Pull request closed without merging**
