### PR TITLE
Make ColumnBase.__cuda_array_interface__ opt out instead of opt in

### PR DESCRIPTION
**Pull request by mroeschke**
## Description
Column types that support CAI already have custom `NotImplementedError`s, and since the implementation is the same for datetime and numeric columns, moving their implementation to `ColumnBase`

Should help address timedelta support in https://github.com/rapidsai/cudf/pull/15615 cc @brandon-b-miller 

## Checklist
- [ ] I am familiar with the [Contributing Guidelines](https://github.com/rapidsai/cudf/blob/HEAD/CONTRIBUTING.md).
- [ ] New or existing tests cover these changes.
- [ ] The documentation is up to date with these changes.

### CODE REVIEW

**Review by galipremsagar — CHANGES_REQUESTED** [review]
While we are at it could you move `__cuda_array_interface__` implementation from `Decimal64Column` to `DecimalBaseColumn`? So that all decimal column types are covered.

**Comment by mroeschke** [comment]
> While we are at it could you move `__cuda_array_interface__` implementation from `Decimal64Column` to `DecimalBaseColumn`? So that all decimal column types are covered.

Nice catch! Moved in the last commit

**Review by galipremsagar — APPROVED** [review]

**Comment by galipremsagar** [comment]
Thank you @mroeschke for handling this!

**Pull request merged**
