### PR TITLE
Fix assertion in dask_cudf test_struct_explode 

### PR DESCRIPTION
**Pull request by rjzamora**
The current implementation of `test_accessor.py::test_struct_explode` relies on `got` having a single partition. However, an [upstream fix](https://github.com/dask/dask/pull/9221) will change the behavior of `from_cudf` to return the **correct** number of partitions (2) soon.  Therefore, this PR is just a preemptive fix.

### CODE REVIEW

**Comment by galipremsagar** [comment]
Dev env yml is used only for local dev, you will need to add the pip install statement after this line: https://github.com/rapidsai/cudf/blob/branch-22.08/ci/gpu/build.sh#L96

**Comment by rjzamora** [comment]
rerun tests

**Review by galipremsagar — APPROVED** [review]

**Comment by rjzamora** [comment]
[@gpucibot](https://github.com/gpucibot) merge

**Comment by galipremsagar** [comment]
@gpucibot merge

**Pull request merged**
