### PR TITLE
[Review] Correct unused parameter warnings in rolling algorithms

### PR DESCRIPTION
**Pull request by robertmaynard**
Starting in CUDA 11.3, nvcc will start to unconditionally warn about unused parameters on functions/methods that are in anonymous namespaces.

### CODE REVIEW

**Review by ttnghia — APPROVED** [review]
It is a good/better practice to use `Type /*variable_name*/` instead of removing the unused variable name entirely. Having the name there will let us a better hint about what is sitting at the parameter position.

**Comment by robertmaynard** [comment]
> It is a good/better practice to use `Type /*variable_name*/` instead of removing the unused variable name entirely. Having the name there will let us a better hint about what is sitting at the parameter position.

I don't mind updating the approach but it would be great to have a consistent style. When I brought this up on slack people wanted me to drop the unused names so they can't go out of sync, so that is what I used for both of the open PR's and https://github.com/rapidsai/cudf/pull/8239, and https://github.com/rapidsai/cudf/pull/8232

**Review by karthikeyann — APPROVED** [review]

**Comment by harrism** [comment]
Does NVCC respect the C++17 ``[[maybe_unused]]` attribute? https://en.cppreference.com/w/cpp/language/attributes/maybe_unused

**Comment by ttnghia** [comment]
> Does NVCC respect the C++17 ``[[maybe_unused]]` attribute? https://en.cppreference.com/w/cpp/language/attributes/maybe_unused

I think it should, as C++ standard is the same for both host and device code compilation.

**Comment by robertmaynard** [comment]
> > Does NVCC respect the C++17 ``[[maybe_unused]]` attribute? https://en.cppreference.com/w/cpp/language/attributes/maybe_unused
> 
> I think it should, as C++ standard is the same for both host and device code compilation.

This warning is generated by a component of the CUDA compiler unconditionally when invoked independent of the standard level, or if the code is host or device. In addition this component currently doesn't respect any ``[[maybe_unused]]`` attributes and will generate these warnings. 

So for now we have to jump through these hoops.

**Comment by robertmaynard** [comment]
rerun tests

**Comment by robertmaynard** [comment]
@gpucibot merge

**Pull request merged**
