### PR TITLE
[REVIEW] cudf.sqrt

### LINKED ISSUE #1055: [FEA] Square Root via __array_ufunc__ protocol
As a special case of https://github.com/rapidsai/cudf/issues/256 it would be useful to have a `sqrt` computation accessible from cudf on the Python side.  This would enable the computation of groupby-std (among other things).

Looking at instances of sqrt in the codebase today 

```
MROCKLIN-MLT:cudf mrocklin$ git grep sqrt
cpp/include/cudf/functions.h:gdf_error gdf_sqrt_generic(gdf_column *input, gdf_column *output);
cpp/include/cudf/functions.h:gdf_error gdf_sqrt_f32(gdf_column *input, gdf_column *output);
cpp/include/cudf/functions.h:gdf_error gdf_sqrt_f64(gdf_column *input, gdf_column *output);
cpp/python/libgdf_cffi/tests/test_unaryops.py:def test_sqrt(dtype, ulp):
cpp/python/libgdf_cffi/tests/test_unaryops.py:    math_op_test(dtype, ulp, np.sqrt, libgdf.gdf_sqrt_generic,
cpp/src/unary/unary_ops.cu:        return std::sqrt(data);
cpp/src/unary/unary_ops.cu:DEF_UNARY_OP_REAL(gdf_sqrt)
cpp/src/unary/unary_ops.cu:gdf_error gdf_sqrt_f32(gdf_column *input, gdf_column *output) {
cpp/src/unary/unary_ops.cu:gdf_error gdf_sqrt_f64(gdf_column *input, gdf_column *output) {
python/cudf/bindings/cudf_cpp.pxd:    cdef gdf_error gdf_sqrt_generic(gdf_column *input, gdf_column *output)
python/cudf/bindings/cudf_cpp.pxd:    cdef gdf_error gdf_sqrt_f32(gdf_column *input, gdf_column *output)
python/cudf/bindings/cudf_cpp.pxd:    cdef gdf_error gdf_sqrt_f64(gdf_column *input, gdf_column *output)
python/cudf/dataframe/series.py:        return np.sqrt(self.var(ddof=ddof))
```

We see references to it in C++ side, a few references to bindings in the Cython side, but no use of it on the Python side as far as I can tell.  Oddly we *do* see `np.sqrt` used in the `Series.std` method, which I suspect converts to a numpy array?

### PR DESCRIPTION
**Pull request by thomcom**
Fixes #1055. Sets a simple template for improving all unaryops and extending them from libgdf. Cython has to be this simple.

### CODE REVIEW

**Comment by thomcom** [comment]
One flaw in this PR is that we get an UNSUPPORTED_DTYPE error if we attempt to `cudf.sqrt(cudf.Series([1, 2]))` - that is, the integer type is not promoted to float prior to sqrt. I'm not sure where this update should be made.

**Comment by thomcom** [comment]
rerun tests

**Comment by kkraus14** [comment]
> One flaw in this PR is that we get an UNSUPPORTED_DTYPE error if we attempt to `cudf.sqrt(cudf.Series([1, 2]))` - that is, the integer type is not promoted to float prior to sqrt. I'm not sure where this update should be made.

We can do that as a followup later.

**Comment by devavret** [comment]
I just enabled math unary ops to work on integer types. Except, currently they're made to output the same type as input. Is that going to be of any use? `sqrt(int)` seems useless for anything other than perfect squares.

**Pull request merged**
