### PR TITLE
Reduce page fragment size in Parquet writer

### PR DESCRIPTION
**Pull request by vuule**
## Description
Parquet writer creates pages from fragments of fixed number of rows. With deep nesting or long strings this way of creating pages can lead to pages that are much larger than the target size.
This PR alleviates the issue by reducing the number of rows in each fragment.

Performance impact:
5% throughput increase on average in the writer benchmark. The benefit is very uneven, with numeric types having almost 10% throughput loss and list type getting up to 110% faster.
15% throughput increase on average in the reader benchmark, with ~10% throughput loss with numeric types and up to 220% gain with lists.

## Checklist
- [x] I am familiar with the [Contributing Guidelines](https://github.com/rapidsai/cudf/blob/HEAD/CONTRIBUTING.md).
- [ ] New or existing tests cover these changes.
- [ ] The documentation is up to date with these changes.

### CODE REVIEW

**Comment by etseidl** [comment]
@vuule Any chance of making the fragment size configurable for power users? 😉

**Comment by jbrennan333** [comment]
I am trying to verify if this is a win with respect to output sizes.  It does seem to improve the case of query98 at scale 100 from https://github.com/NVIDIA/spark-rapids/issues/3037.
```
6.0M	power-output-gpu-parquet-cpu-zstd/
4.4M	power-output-gpu-parquet-vukasin/
4.2M	power-output-cpu-parquet-cpu-zstd/

384K	power-output-cpu-parquet-cpu-zstd/query98/part-00000-c96789af-69ad-41ad-978f-593fa9569cb2-c000.zstd.parquet
388K	power-output-cpu-parquet-cpu-zstd/query98/part-00001-c96789af-69ad-41ad-978f-593fa9569cb2-c000.zstd.parquet
384K	power-output-cpu-parquet-cpu-zstd/query98/part-00002-c96789af-69ad-41ad-978f-593fa9569cb2-c000.zstd.parquet
460K	power-output-cpu-parquet-cpu-zstd/query98/part-00003-c96789af-69ad-41ad-978f-593fa9569cb2-c000.zstd.parquet

1.1M	power-output-gpu-parquet-cpu-zstd/query98/part-00000-eb6d346a-438e-4d54-8415-7a447c7dc3e4-c000.zstd.parquet
1.1M	power-output-gpu-parquet-cpu-zstd/query98/part-00001-eb6d346a-438e-4d54-8415-7a447c7dc3e4-c000.zstd.parquet
1.5M	power-output-gpu-parquet-cpu-zstd/query98/part-00002-eb6d346a-438e-4d54-8415-7a447c7dc3e4-c000.zstd.parquet

552K	power-output-gpu-parquet-vukasin/query98/part-00000-da7a35fa-d6ea-444c-9dd6-950cca951307-c000.zstd.parquet
556K	power-output-gpu-parquet-vukasin/query98/part-00001-da7a35fa-d6ea-444c-9dd6-950cca951307-c000.zstd.parquet
764K	power-output-gpu-parquet-vukasin/query98/part-00002-da7a35fa-d6ea-444c-9dd6-950cca951307-c000.zstd.parquet
```
But when I run a conversion from csv to parquet-zstd data at scale 100, I am actually seeing a larger overall output size:
```
26G	cpu_parquet_sf100_zstd
27G	gpu_parquet_sf100_zstd (before this change)
29G	vukasin_gpu_parquet_sf100_zstd (with this change)
```
These are sizes for each file for GPU before:
```
16K	./gpu_parquet_sf100_zstd/income_band
16K	./gpu_parquet_sf100_zstd/reason
16K	./gpu_parquet_sf100_zstd/ship_mode
20K	./gpu_parquet_sf100_zstd/warehouse
24K	./gpu_parquet_sf100_zstd/call_center
24K	./gpu_parquet_sf100_zstd/web_site
32K	./gpu_parquet_sf100_zstd/household_demographics
40K	./gpu_parquet_sf100_zstd/web_page
44K	./gpu_parquet_sf100_zstd/store
48K	./gpu_parquet_sf100_zstd/promotion
488K	./gpu_parquet_sf100_zstd/time_dim
796K	./gpu_parquet_sf100_zstd/catalog_page
960K	./gpu_parquet_sf100_zstd/date_dim
5.0M	./gpu_parquet_sf100_zstd/customer_demographics
16M	./gpu_parquet_sf100_zstd/customer_address
27M	./gpu_parquet_sf100_zstd/item
82M	./gpu_parquet_sf100_zstd/customer
435M	./gpu_parquet_sf100_zstd/web_returns
887M	./gpu_parquet_sf100_zstd/catalog_returns
1.3G	./gpu_parquet_sf100_zstd/store_returns
1.6G	./gpu_parquet_sf100_zstd/inventory
3.8G	./gpu_parquet_sf100_zstd/web_sales
7.8G	./gpu_parquet_sf100_zstd/catalog_sales
11G	./gpu_parquet_sf100_zstd/store_sales
```
And these are the sizes with this change:
```
16K	./vukasin_gpu_parquet_sf100_zstd/income_band
16K	./vukasin_gpu_parquet_sf100_zstd/reason
16K	./vukasin_gpu_parquet_sf100_zstd/ship_mode
20K	./vukasin_gpu_parquet_sf100_zstd/warehouse
24K	./vukasin_gpu_parquet_sf100_zstd/call_center
24K	./vukasin_gpu_parquet_sf100_zstd/web_site
32K	./vukasin_gpu_parquet_sf100_zstd/household_demographics
40K	./vukasin_gpu_parquet_sf100_zstd/web_page
44K	./vukasin_gpu_parquet_sf100_zstd/store
48K	./vukasin_gpu_parquet_sf100_zstd/promotion
488K	./vukasin_gpu_parquet_sf100_zstd/time_dim
792K	./vukasin_gpu_parquet_sf100_zstd/catalog_page
960K	./vukasin_gpu_parquet_sf100_zstd/date_dim
5.0M	./vukasin_gpu_parquet_sf100_zstd/customer_demographics
16M	./vukasin_gpu_parquet_sf100_zstd/customer_address
27M	./vukasin_gpu_parquet_sf100_zstd/item
84M	./vukasin_gpu_parquet_sf100_zstd/customer
435M	./vukasin_gpu_parquet_sf100_zstd/web_returns
887M	./vukasin_gpu_parquet_sf100_zstd/catalog_returns
1.5G	./vukasin_gpu_parquet_sf100_zstd/store_returns
1.6G	./vukasin_gpu_parquet_sf100_zstd/inventory
3.8G	./vukasin_gpu_parquet_sf100_zstd/web_sales
8.6G	./vukasin_gpu_parquet_sf100_zstd/catalog_sales
13G	./vukasin_gpu_parquet_sf100_zstd/store_sales
```
It looks like the bulk of the difference is in store_sales, 11G vs 13G.  This is the largest file.  I will try this at scale 3000 to see if the difference holds.

Uploading the parquet-tools output for one of the partition files.
[store_sales-example-gpu-orig.txt](https://github.com/rapidsai/cudf/files/10005551/store_sales-example-gpu-orig.txt)

[store_sales-example-gpu-vukasin.txt](https://github.com/rapidsai/cudf/files/10005550/store_sales-example-gpu-vukasin.txt)

**Comment by jbrennan333** [comment]
Here is the CPU version: 
[store_sales-example-cpu.txt](https://github.com/rapidsai/cudf/files/10005819/store_sales-example-cpu.txt)

**Comment by jbrennan333** [comment]
At scale 3000, nds2.0 data conversion is also producing larger output:
```
      11.8 K       11.8 K            725.6 G /data/jimb/cpu_parquet_sf3k_decimal_zstd
      11.8 K       11.8 K            778.0 G /data/jimb/gpu_parquet_sf3k_decimal_zstd
      11.8 K       11.8 K            812.0 G /data/jimb/vukasin_gpu_parquet_sf3k_decimal_zstd
```
Per file break-down with original code:
```
           1            2                944 /data/jimb/gpu_parquet_sf3k_decimal_zstd/income_band
           1            2              1.4K /data/jimb/gpu_parquet_sf3k_decimal_zstd/reason
           1            2              2.0K /data/jimb/gpu_parquet_sf3k_decimal_zstd/ship_mode
           1            2              4.5K /data/jimb/gpu_parquet_sf3k_decimal_zstd/warehouse
           1            2             12.1K /data/jimb/gpu_parquet_sf3k_decimal_zstd/call_center
           1            2             12.8K /data/jimb/gpu_parquet_sf3k_decimal_zstd/web_site
           1            2             17.5K /data/jimb/gpu_parquet_sf3k_decimal_zstd/household_demographics
           1            2             48.4K /data/jimb/gpu_parquet_sf3k_decimal_zstd/web_page
           1            2             59.0K /data/jimb/gpu_parquet_sf3k_decimal_zstd/promotion
           1            2             87.0K /data/jimb/gpu_parquet_sf3k_decimal_zstd/store
           1            2            475.4K /data/jimb/gpu_parquet_sf3k_decimal_zstd/time_dim
           1            2            940.4K /data/jimb/gpu_parquet_sf3k_decimal_zstd/date_dim
           1            2              1.3M /data/jimb/gpu_parquet_sf3k_decimal_zstd/catalog_page
           1            2              5.1M /data/jimb/gpu_parquet_sf3k_decimal_zstd/customer_demographics
           1            2             45.5M /data/jimb/gpu_parquet_sf3k_decimal_zstd/item
           1            2            216.4M /data/jimb/gpu_parquet_sf3k_decimal_zstd/customer_address
           1            2              1.2G /data/jimb/gpu_parquet_sf3k_decimal_zstd/customer
         262          262              4.3G /data/jimb/gpu_parquet_sf3k_decimal_zstd/inventory
       2.1K        2.1K             12.4G /data/jimb/gpu_parquet_sf3k_decimal_zstd/web_returns
       2.1K        2.1K             26.4G /data/jimb/gpu_parquet_sf3k_decimal_zstd/catalog_returns
       2.0K        2.0K             39.2G /data/jimb/gpu_parquet_sf3k_decimal_zstd/store_returns
       1.8K        1.8K            117.9G /data/jimb/gpu_parquet_sf3k_decimal_zstd/web_sales
       1.8K        1.8K            241.7G /data/jimb/gpu_parquet_sf3k_decimal_zstd/catalog_sales
       1.8K        1.8K            334.6G /data/jimb/gpu_parquet_sf3k_decimal_zstd/store_sales
```
And with this change:
```
           1            2                944 /data/jimb/vukasin_gpu_parquet_sf3k_decimal_zstd/income_band
           1            2              1.4K /data/jimb/vukasin_gpu_parquet_sf3k_decimal_zstd/reason
           1            2              2.0K /data/jimb/vukasin_gpu_parquet_sf3k_decimal_zstd/ship_mode
           1            2              4.5K /data/jimb/vukasin_gpu_parquet_sf3k_decimal_zstd/warehouse
           1            2             12.1K /data/jimb/vukasin_gpu_parquet_sf3k_decimal_zstd/call_center
           1            2             12.8K /data/jimb/vukasin_gpu_parquet_sf3k_decimal_zstd/web_site
           1            2             17.5K /data/jimb/vukasin_gpu_parquet_sf3k_decimal_zstd/household_demographics
           1            2             48.4K /data/jimb/vukasin_gpu_parquet_sf3k_decimal_zstd/web_page
           1            2             58.9K /data/jimb/vukasin_gpu_parquet_sf3k_decimal_zstd/promotion
           1            2             87.0K /data/jimb/vukasin_gpu_parquet_sf3k_decimal_zstd/store
           1            2            475.1K /data/jimb/vukasin_gpu_parquet_sf3k_decimal_zstd/time_dim
           1            2            940.5K /data/jimb/vukasin_gpu_parquet_sf3k_decimal_zstd/date_dim
           1            2              1.3M /data/jimb/vukasin_gpu_parquet_sf3k_decimal_zstd/catalog_page
           1            2              5.1M /data/jimb/vukasin_gpu_parquet_sf3k_decimal_zstd/customer_demographics
           1            2             45.5M /data/jimb/vukasin_gpu_parquet_sf3k_decimal_zstd/item
           1            2            216.4M /data/jimb/vukasin_gpu_parquet_sf3k_decimal_zstd/customer_address
           1            2              1.3G /data/jimb/vukasin_gpu_parquet_sf3k_decimal_zstd/customer
         262          262              4.3G /data/jimb/vukasin_gpu_parquet_sf3k_decimal_zstd/inventory
       2.1K        2.1K             14.4G /data/jimb/vukasin_gpu_parquet_sf3k_decimal_zstd/web_returns
       2.1K        2.1K             29.4G /data/jimb/vukasin_gpu_parquet_sf3k_decimal_zstd/catalog_returns
       2.0K        2.0K             41.1G /data/jimb/vukasin_gpu_parquet_sf3k_decimal_zstd/store_returns
       1.8K        1.8K            117.9G /data/jimb/vukasin_gpu_parquet_sf3k_decimal_zstd/web_sales
       1.8K        1.8K            251.7G /data/jimb/vukasin_gpu_parquet_sf3k_decimal_zstd/catalog_sales
       1.8K        1.8K            351.7G /data/jimb/vukasin_gpu_parquet_sf3k_decimal_zstd/store_sales
```

**Comment by vuule** [comment]
Surprised top see that some files get larger with this change. It should only allow writer to more closely stick to the target page size.
I don't think we can go ahead with this change in 22.12, more investigation is required before merging.

@jbrennan333 @etseidl do you see any value in keeping the default and only adding a way for users to control the fragment size in this release?

**Comment by jbrennan333** [comment]
I agree more testing is required.  It might be nice to have a way to configure it, but it is such a low-level detail (from a spark user point of view), that I don't think it's something we would make available to users.

I am also puzzled by the increased file sizes.  If you look at the parquet tools output I shared, it seems like with the new code there are some Decimal columns that were not compressed (compared to without this change).  I don't understand why that would have happened?

**Comment by jbrennan333** [comment]
I should note that the original data was generated a while ago so it is possible that other changes in cuDF or the spark plugin might be impacting this.  I'll rerun with current code to check whether this is the case.

**Comment by etseidl** [comment]
> do you see any value in keeping the default and only adding a way for users to control the fragment size in this release?

I don't know if it's a super high priority.  It would be nice for a very heavily nested set of data I have, but by no means necessary.

I wonder if the increased sizes here are due to the same dictionary issues I'm seeing elsewhere.   Perhaps this change changed the file  layout enough to push some dictionaries over 64k.  I'll have a draft PR soon that might help with this.

**Comment by jbrennan333** [comment]
I verified that the size change I am seeing at scale 100 on my desktop is solely due to this change.
```
27G	gpu_parquet_sf100_zstd
27G	vukasin-orig_gpu_parquet_sf100_zstd
29G	vukasin_gpu_parquet_sf100_zstd
```
The with this change removed (`vukasin-orig_gpu_parquet_sf100_zstd`) match my original numbers (`gpu_parquet_sf100_zstd`).

**Comment by vuule** [comment]
Turns out this is just a piece of the puzzle that is the Parquet file size :)
Closing for now, will likely be included in a larger PR later on.

**Pull request closed without merging**
