### PR TITLE
[REVIEW] Fix iloc performance

### LINKED ISSUE #1176: [BUG] iloc is very slow
```python
In [1]: import cudf, dask.dataframe as dd, numpy as np

In [2]: df = cudf.DataFrame({'x': np.arange(100000)})

In [3]: %time df.iloc[1000:100000]
CPU times: user 10.3 s, sys: 136 ms, total: 10.5 s
Wall time: 10.5 s
Out[3]: <cudf.DataFrame ncols=1 nrows=99000 >
```

### PR DESCRIPTION
**Pull request by kkraus14**
Fixes #1176 

Currently it creates a massive list host side which becomes a huge bottleneck.

### CODE REVIEW

**Comment by kkraus14** [comment]
@mrocklin give this branch a shot and let me know if it resolves your performance issues.

**Comment by thomcom** [comment]
Of course I think this commit is great since it just cuts 50 loc. I'm confused because when Iloc was added to Dataframe and Series, row-wise accesses were not available. I guess that efficient row access was written in a different commit and you're throwing out the inefficient code and using the now-existing good stuff?

**Comment by kkraus14** [comment]
> Of course I think this commit is great since it just cuts 50 loc. I'm confused because when Iloc was added to Dataframe and Series, row-wise accesses were not available. I guess that efficient row access was written in a different commit and you're throwing out the inefficient code and using the now-existing good stuff?

No, this code has actually been in place for a while, the iloc implementation just needed to be optimized to avoid host objects unless necessary.

**Comment by mrocklin** [comment]
Well, the `on=str` case should go in regardless I think.  It produced a bug that is easy to fix, and decently common.

Supporting `left_on`, `right_on` is useful if we want to support big-to-small joins in dask-cudf, which was requested by @randerzander

**Comment by mrocklin** [comment]
I'm going to keep looking at this for a bit and see if I can figure it out if that's ok

**Comment by mrocklin** [comment]
Oh, whoops, wrong PR

**Comment by mrocklin** [comment]
Looks nicer to me!

```python

In [1]: import cudf, numpy as np

In [2]: df = cudf.DataFrame({'x': np.arange(1000000)})

In [3]: %time df.iloc[:]
CPU times: user 132 ms, sys: 16 ms, total: 148 ms
Wall time: 465 ms
Out[3]: <cudf.DataFrame ncols=1 nrows=1000000 >

In [4]: %time df.iloc[1000:-1000]
CPU times: user 4 ms, sys: 0 ns, total: 4 ms
Wall time: 6.02 ms
Out[4]: <cudf.DataFrame ncols=1 nrows=998000 >

In [5]: %time df.iloc[:]
CPU times: user 4 ms, sys: 4 ms, total: 8 ms
Wall time: 5.53 ms
Out[5]: <cudf.DataFrame ncols=1 nrows=1000000 >
```

**Comment by kkraus14** [comment]
> Looks nicer to me!
> 
> ```python
> In [1]: import cudf, numpy as np
> 
> In [2]: df = cudf.DataFrame({'x': np.arange(1000000)})
> 
> In [3]: %time df.iloc[:]
> CPU times: user 132 ms, sys: 16 ms, total: 148 ms
> Wall time: 465 ms
> Out[3]: <cudf.DataFrame ncols=1 nrows=1000000 >
> 
> In [4]: %time df.iloc[1000:-1000]
> CPU times: user 4 ms, sys: 0 ns, total: 4 ms
> Wall time: 6.02 ms
> Out[4]: <cudf.DataFrame ncols=1 nrows=998000 >
> 
> In [5]: %time df.iloc[:]
> CPU times: user 4 ms, sys: 4 ms, total: 8 ms
> Wall time: 5.53 ms
> Out[5]: <cudf.DataFrame ncols=1 nrows=1000000 >
> ```

The first one is `465ms` because of JIT compilation overhead so this looks good to go pending CI, schweet.

**Comment by mrocklin** [comment]
Looks like a test failure here.  Copying for convenience

```python
@pytest.mark.xfail(
        raises=NotImplementedError,
        reason="cudf columnar iloc not supported"
    )
    def test_dataframe_iloc_tuple():
        gdf = DataFrame()
        nelem = 123
        gdf['a'] = ha = np.random.randint(low=0, high=100, size=nelem) \
            .astype(np.int32)
        gdf['b'] = hb = np.random.random(nelem).astype(np.float32)
    
        pdf = pd.DataFrame()
        pdf['a'] = ha
        pdf['b'] = hb
    
        def assert_col(g, p):
            np.testing.assert_equal(g['a'].to_array(), p['a'])
            np.testing.assert_equal(g['b'].to_array(), p['b'])
    
>       assert_col(gdf.iloc[1, 2], pdf.iloc[1, 2])

cudf/tests/test_dataframe.py:515: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/conda/envs/gdf/lib/python3.6/site-packages/pandas/core/indexing.py:1472: in __getitem__
    return self._getitem_tuple(key)
/conda/envs/gdf/lib/python3.6/site-packages/pandas/core/indexing.py:2013: in _getitem_tuple
    self._has_valid_tuple(tup)
/conda/envs/gdf/lib/python3.6/site-packages/pandas/core/indexing.py:222: in _has_valid_tuple
    self._validate_key(k, i)
/conda/envs/gdf/lib/python3.6/site-packages/pandas/core/indexing.py:1957: in _validate_key
    self._validate_integer(key, axis)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <pandas.core.indexing._iLocIndexer object at 0x7fed9dcd7638>, key = 2
axis = 1

    def _validate_integer(self, key, axis):
        # return a boolean if we have a valid integer indexer
    
        ax = self.obj._get_axis(axis)
        l = len(ax)
        if key >= l or key < -l:
>           raise IndexError("single positional indexer is out-of-bounds")
E           IndexError: single positional indexer is out-of-bounds

/conda/envs/gdf/lib/python3.6/site-packages/pandas/core/indexing.py:2009: IndexError
```

**Comment by thomcom** [comment]
Strange, Pandas is throwing the error.

**Comment by kkraus14** [comment]
> Strange, Pandas is throwing the error.

@thomcom any chance you can take this over and drive to completion? I'm fighting with strings some more 😄

**Comment by kkraus14** [comment]
Our behavior in handling tuples is wrong, we treat them as a list of row indices instead of a row indices and then a column index.

**Comment by kkraus14** [comment]
> > Strange, Pandas is throwing the error.
> 
> @thomcom any chance you can take this over and drive to completion? I'm fighting with strings some more 😄

nevermind turns out it's a libcudf issue so those devs are tackling so I can take this

**Comment by kkraus14** [comment]
rerun tests

**Pull request merged**
