### PR TITLE
[REVIEW] unified libcudf API functions by replacing gpu_ with gdf_.  #383

### PR DESCRIPTION
**Pull request by q2w**
Currently, The APIs in libgdf/include/gdf/cffi/functions.h has some functions prefixed with gdf_ and some with gpu_. This fix replaces gpu_ by gdf_ and make it consistent.

fixes https://github.com/rapidsai/cudf/issues/383

### CODE REVIEW

**Comment by GPUtester** [comment]
Can one of the admins verify this patch?

**Comment by GPUtester** [comment]
Can one of the admins verify this patch?

**Comment by kkraus14** [comment]
ok to test

**Comment by jrhemstad** [comment]
Thanks for updating this @q2w. Right now you've only updated the function declarations. You'll also need to update the function definitions in order to build and pass CI.

**Comment by jrhemstad** [comment]
@q2w CI is currently failing because your update to the CHANGELOG refers to the incorrect PR#.

**Comment by q2w** [comment]
Thanks @harrism for the help and recommendation.

**Comment by kkraus14** [comment]
@harrism @jrhemstad will defer to you for merge since this mainly touches the libcudf side of the codebase

**Comment by eyalroz** [comment]
Hey, wait a minute... shouldn't these functions all be prefixed with `cudf_` rather than `gdf`?

**Comment by harrism** [comment]
They should, and that task is a little bit easier now that they are all prefixed the same. We would welcome a PR that does this, but I think it's a bigger undertaking because we would also change the names of datatypes, and update all the Python bindings, which requires modifying all the Python code that calls those bindings.

**Pull request merged**
