### PR TITLE
Improve Polars docs

### PR DESCRIPTION
**Pull request by bdice**
## Description
This PR improves the docs by reducing the size of the Polars heading (too many words) and tightening up the writing of the docs page.

## Checklist
- [x] I am familiar with the [Contributing Guidelines](https://github.com/rapidsai/cudf/blob/HEAD/CONTRIBUTING.md).
- [x] New or existing tests cover these changes.
- [x] The documentation is up to date with these changes.

### CODE REVIEW

**Comment by bdice** [comment]
We can target `branch-24.08` or `branch-24.10` with this PR. Reviewers, please weigh in on that decision.

**Review by galipremsagar — APPROVED** [review]
I'm okay with merging into 24.08

**Review by quasiben — APPROVED** [review]
Looks great!

**Review by wence- — APPROVED** [review]
Thanks @bdice

**Comment by wence-** [comment]
The docs builds are failing because the artifact download is attempting to grab 3.12 artifacts, but those don't exist:

https://github.com/rapidsai/cudf/actions/runs/10950652331/job/30437458677?pr=16820#step:9:139
https://github.com/rapidsai/cudf/actions/runs/10950652331/job/30437458677?pr=16820#step:9:401

I don't know what part of the workflow is controlling the environment variable `RAPIDS_PY_VERSION`

**Comment by bdice** [comment]
Yes, it's due to `latest` tags changing. I'll see what to do here.

**Comment by bdice** [comment]
I pinned the CI images to a Python 3.11 version. We'll need to undo that change when this is forward-merged.

**Comment by bdice** [comment]
The docs render fine.

However, something strange happened with the ARM CUDA 12 CI jobs and they spat out 114 megabytes of logs, seemingly to do with FNV hash functions in Numba. I'm unsure why this would erupt into so much output... I have no explanation, so I will rerun CI and hope for the best.

**Pull request merged**
