### PR TITLE
[REVIEW] Fixing loc bug when indexing by column name

### PR DESCRIPTION
**Pull request by rjzamora**
Minor change to avoid treating strings as lists when indexing a dataframe by the column name.  This bug is described in issue #1505

### CODE REVIEW

**Comment by GPUtester** [comment]
Can one of the admins verify this patch?

**Comment by thomcom** [comment]
rerun tests

**Comment by mrocklin** [comment]
Checking in here.  @rjzamora it looks like CI isn't running, I suspect because of the changelog conflict.  You may want to resolve that conflict (should be easy to do in the github UI) and then see how tests proceed.

**Comment by kkraus14** [comment]
add to whitelist

**Pull request merged**
