### PR TITLE
Add Java interface for the new API 'explode' [skip ci]

### PR DESCRIPTION
**Pull request by firestarman**
This PR is to add Java interface for the new API '`explode`', along with its unit tests.

This PR depends on the PR https://github.com/rapidsai/cudf/pull/7140 .

### CODE REVIEW

**Comment by GPUtester** [comment]
Can one of the admins verify this patch?

**Comment by jlowe** [comment]
Needs 2021 copyrights added to the files but otherwise lgtm.

**Comment by firestarman** [comment]
> Needs 2021 copyrights added to the files but otherwise lgtm.

Updated, thanks.

**Review by jlowe — APPROVED** [review]

**Review by revans2 — APPROVED** [review]

**Comment by firestarman** [comment]
mark as review since PR7140 has been merged

**Comment by revans2** [comment]
@gpucibot merge

**Comment by revans2** [comment]
rerun tests

**Comment by ajschmidt8** [comment]
ok to test

**Comment by revans2** [comment]
@gpucibot merge

**Pull request merged**
