### PR TITLE
Update cudf java binding version to 22.04.0-SNAPSHOT

### PR DESCRIPTION
**Pull request by pxLi**
Signed-off-by: Peixin Li <pxli@nyu.edu>

Update cudfjni version to 22.04.0-SNAPSHOT

### CODE REVIEW

**Comment by pxLi** [comment]
will retrigger tests when 22.04 CI is ready

**Review by jlowe — APPROVED** [review]

**Review by ttnghia — APPROVED** [review]

**Comment by ttnghia** [comment]
@gpucibot merge

**Comment by ttnghia** [comment]
Rerun tests.

**Comment by ttnghia** [comment]
Rerun tests.

**Comment by ttnghia** [comment]
Maybe need to merge upstream, as other PRs have all CI passed before this one reran tests.

**Pull request merged**
