### PR TITLE
[REVIEW] Fix ingest of 1 row arrow tables

### LINKED ISSUE #687: [BUG] Cannot create DataFrame from a single-row PyArrow table
**Describe the bug**
Creating a DataFrame from a one-row PyArrow table results in a ValueError

**Steps/Code to reproduce bug**
Repro:
```
import pyarrow as pa
from cudf import DataFrame

data = [pa.array([0]), pa.array([1])]
batch = pa.RecordBatch.from_arrays(data, ['f0', 'f1'])
table = pa.Table.from_batches([batch])
DataFrame.from_arrow(table)
```
Result:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/conda/envs/cudf/lib/python3.7/site-packages/cudf-0.6.0.dev0+157.gdf5a9ef.dirty-py3.7-linux-x86_64.egg/cudf/dataframe/dataframe.py", line 1841, in from_arrow
    df[col.name] = col.data
  File "/conda/envs/cudf/lib/python3.7/site-packages/cudf-0.6.0.dev0+157.gdf5a9ef.dirty-py3.7-linux-x86_64.egg/cudf/dataframe/dataframe.py", line 260, in __setitem__
    self.add_column(name, col)
  File "/conda/envs/cudf/lib/python3.7/site-packages/cudf-0.6.0.dev0+157.gdf5a9ef.dirty-py3.7-linux-x86_64.egg/cudf/dataframe/dataframe.py", line 646, in add_column
    series = self._prepare_series_for_add(data, forceindex=forceindex)
  File "/conda/envs/cudf/lib/python3.7/site-packages/cudf-0.6.0.dev0+157.gdf5a9ef.dirty-py3.7-linux-x86_64.egg/cudf/dataframe/dataframe.py", line 618, in _prepare_series_for_add
    col = self._sanitize_values(col)
  File "/conda/envs/cudf/lib/python3.7/site-packages/cudf-0.6.0.dev0+157.gdf5a9ef.dirty-py3.7-linux-x86_64.egg/cudf/dataframe/dataframe.py", line 599, in _sanitize_values
    cudautils.gpu_fill_value.forall(arr.size)(arr, col)
  File "/conda/envs/cudf/lib/python3.7/site-packages/numba/cuda/compiler.py", line 226, in __call__
    kernel = self.kernel.specialize(*args)
  File "/conda/envs/cudf/lib/python3.7/site-packages/numba/cuda/compiler.py", line 775, in specialize
    [self.typingctx.resolve_argument_type(a) for a in args])
  File "/conda/envs/cudf/lib/python3.7/site-packages/numba/cuda/compiler.py", line 775, in <listcomp>
    [self.typingctx.resolve_argument_type(a) for a in args])
  File "/conda/envs/cudf/lib/python3.7/site-packages/numba/typing/context.py", line 339, in resolve_argument_type
    return typeof(val, Purpose.argument)
  File "/conda/envs/cudf/lib/python3.7/site-packages/numba/typing/typeof.py", line 34, in typeof
    raise ValueError(msg)
ValueError: cannot determine Numba type of <class 'pyarrow.lib.ChunkedArray'>
```

**Expected behavior**
Instead of throwing a stacktrace, the code above should return a cuDF DataFrame

**Environment details (please complete the following information):**
 - Environment location: [Docker]
 - Method of cuDF install: [from source]

**Additional context**
From tip of branch-0.6

### PR DESCRIPTION
**Pull request by kkraus14**
Fixes #687

### CODE REVIEW

**Comment by kkraus14** [comment]
rerun tests

**Comment by kkraus14** [comment]
rerun tests

**Comment by kkraus14** [comment]
rerun tests

**Comment by randerzander** [comment]
looks good to me, and solves my issue

**Pull request merged**
