### PR TITLE
[REVIEW] remove unused variables

### PR DESCRIPTION
**Pull request by jameslamb**
Hello from Chicago 👋 

I've been getting familiar with `cudf` recently. I wanted to contribute back to this project, so I ran `pylint` over this project's Python code. A lot of the warnings from that linter are subjective style things that I think are best ignored or left to maintainers, but I did find a few small warnings that I think should be fixed.

This PR proposes removing a few unused variables. I think this makes the affected code a little easier to read, and reduces the risk of name conflicts between variables.

I specifically am proposing fixing these warnings:

```text
python/cudf/cudf/core/dataframe.py:7312:8: W0612: Unused variable 'idx' (unused-variable)
python/cudf/cudf/core/reshape.py:450:11: W0612: Unused variable 'var' (unused-variable)
python/cudf/cudf/core/series.py:980:8: W0612: Unused variable 'width' (unused-variable)
python/cudf/cudf/core/frame.py:1050:16: W0612: Unused variable 'i' (unused-variable)
python/cudf/cudf/core/frame.py:1324:18: W0612: Unused variable 'col' (unused-variable)
python/cudf/cudf/core/multiindex.py:683:16: W0612: Unused variable 'idx' (unused-variable)
python/cudf/cudf/core/groupby/groupby.py:70:30: W0612: Unused variable 'grouped_keys' (unused-variable)
python/cudf/cudf/io/parquet.py:101:12: W0612: Unused variable 'i' (unused-variable)
```

which can be reproduced like this:

```shell
pylint python/ | grep unused-variable
```

Thank you for your time and consideration.

### CODE REVIEW

**Comment by GPUtester** [comment]
Can one of the admins verify this patch?

**Comment by GPUtester** [comment]
Can one of the admins verify this patch?

**Comment by kkraus14** [comment]
ok to test

**Comment by GPUtester** [comment]
Please update the changelog in order to start CI tests.

View the gpuCI docs [here](https://docs.rapids.ai/gpuci#open-pr-or-update-pr).

**Comment by kkraus14** [comment]
Hey @jameslamb, thanks for contributing! You'll need to add a line to `CHANGELOG.md` in order for CI to run.

These changes look good and it seems like we should consider adding pylint into our formatting / linting toolchain.

**Comment by jameslamb** [comment]
ah ok, I can do that! Sorry, didn't realize that was necessary.

> These changes look good and it seems like we should consider adding pylint into our formatting / linting toolchain.

In my experience, `pylint` catches things that `flake8` and `black` don't. I tend to ignore many of its style things, but it can catch genuine code-correctness problems.

**Review by kkraus14 — APPROVED** [review]

**Pull request merged**
