### PR TITLE
[REVIEW] Fix negative slicing of empty dataframe with columns creates non-empty index

### PR DESCRIPTION
**Pull request by q2w**
This PR resolves https://github.com/rapidsai/cudf/issues/856. 

It also addresses the following behaviour. 

import cudf
df=cudf.DataFrame()
df['a']=[0,1,1,2]
df['b']=[0,1,1,2]
print(df[-6:])

     a    b
-2    0    0
-1    1    1
0    1    1
1    2    2

It should be ..

import cudf
df=cudf.DataFrame()
df['a']=[0,1,1,2]
df['b']=[0,1,1,2]
print(df[-6:])

     a    b
0    0    0
1    1    1
2    1    1
3    2    2

### CODE REVIEW

**Comment by GPUtester** [comment]
Can one of the admins verify this patch?

**Comment by GPUtester** [comment]
Can one of the admins verify this patch?

**Comment by kkraus14** [comment]
run tests

**Comment by q2w** [comment]
@kkraus14 sure.. thanks

**Comment by kkraus14** [comment]
run tests

**Comment by q2w** [comment]
run tests

**Comment by kkraus14** [comment]
run tests

**Comment by kkraus14** [comment]
run tests

**Pull request merged**
