### PR TITLE
Adding `drop` argument to set_index

### PR DESCRIPTION
**Pull request by rjzamora**
This is a simple solution to Issue #2476, which asks for a `drop` argument in the `set_index` dataframe method.

Some notes:

- Default is `drop=True`
- The `drop` argument is ignored in the case that the `index` argument is not a `str` (i.e. `Index` or `Series`-convertible)

### CODE REVIEW

**Comment by shwina** [comment]
In Pandas the default is `drop=False` - do we have a good reason to deviate?

**Comment by shwina** [comment]
Side note:

This is outside the scope of this PR, but I'm realizing now that we assume that the column names are all `str`, which is definitely not true always...

**Comment by rjzamora** [comment]
> In Pandas the default is drop=False - do we have a good reason to deviate?

I don't *think* this is true: https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.set_index.html

**Comment by shwina** [comment]
Oops - sorry! You're absolutely right

**Pull request merged**
