### PR TITLE
[WIP] Cleanup detail APIs

### PR DESCRIPTION
**Pull request by trevorsm7**
Closes https://github.com/rapidsai/cudf/issues/5119

### CODE REVIEW

**Comment by GPUtester** [comment]
Please update the changelog in order to start CI tests.

View the gpuCI docs [here](https://docs.rapids.ai/gpuci#open-pr-or-update-pr).

**Comment by harrism** [comment]
Moving to 0.15.

**Comment by GPUtester** [comment]
Can one of the admins verify this patch?

**Comment by harrism** [comment]
Superseded by #6744

**Pull request closed without merging**
