### PR TITLE
[REVIEW] shutdown RMM in JNI to avoid truncating logs [skip ci]

### PR DESCRIPTION
**Pull request by rongou**
@jlowe @revans2

### CODE REVIEW

**Comment by GPUtester** [comment]
Please update the changelog in order to start CI tests.

View the gpuCI docs [here](https://docs.rapids.ai/gpuci#open-pr-or-update-pr).

**Comment by rongou** [comment]
That's true but it seems to help with the logging. Perhaps a better way is to have java manage the native objects and free them in the `finalize()` method, but that is not guaranteed either.

**Comment by kkraus14** [comment]
From the Python side we've used C++ `std::atexit` hooks in the past to guarantee shutdown behavior (unless there was a program crash) irrespective of Python interpreter shutdown behavior. Unsure if that would help in your situation here.

**Comment by rongou** [comment]
I tried `std::atexit` in the JNI code, but it doesn't seem to help. Looks like when the JVM shuts down, it doesn't automatically destruct the native objects.

**Comment by revans2** [comment]
The only other issue is race conditions. We have debug code that tries to detect leaks by cleaning things up in a shut down hook. If things happen badly we might end up trying to give resources back to RMM that it does not know about because it has been shut down.  We can cross that bridge when we come to it, but it might be nice to have a way to disable this through a system property.

**Comment by rongou** [comment]
Hmm, this does seem pretty finicky. I guess another option is to auto flush when logging is enabled from the java/scala side. It's a debug option so the overhead with flushing every time shouldn't be too big of a deal. What do you think?

**Comment by rongou** [comment]
Auto flush seems to work pretty well. Closing this now, and will open another PR for auto flush.

**Pull request closed without merging**
