### PR TITLE
Make nvcomp adapter compatible with new version macros

### PR DESCRIPTION
**Pull request by vuule**
## Description
New nvcomp version changed the names of the version macros. This PR adds "aliasing" to the old names so rest of the code is not affected.

## Checklist
- [x] I am familiar with the [Contributing Guidelines](https://github.com/rapidsai/cudf/blob/HEAD/CONTRIBUTING.md).
- [ ] New or existing tests cover these changes.
- [ ] The documentation is up to date with these changes.

### CODE REVIEW

**Comment by vuule** [comment]
CC @GregoryKimball for viz

**Review by mythrocks — APPROVED** [review]
LGTM.

> New nvcomp version changed the names of the version macros.

Why would they do such a thing? :|

**Review by mhaseeb123 — APPROVED** [review]

**Comment by vuule** [comment]
> LGTM.
> 
> > New nvcomp version changed the names of the version macros.
> 
> Why would they do such a thing? :|

I think the goal was to align with similar libraries.

**Pull request merged**
