### PR TITLE
Remove the hashing detail default allocator

### PR DESCRIPTION
**Pull request by PointKernel**
## Description
Related to #11176

This PR removes the custom `default_allocator` class located in the global namespace since it's the same as `rmm::mr::polymorphic_allocator`. It also moves all free functions in `hashing/detail/helper_functions.cuh` into `cudf::hashing::detail` namespace.

There are no actual code changes but using `cudf::hashing::detail::default_allocator` as an alias of `rmm::mr::polymorphic_allocator<char>` to replace the previous `default_allocator` class.

## Checklist
- [x] I am familiar with the [Contributing Guidelines](https://github.com/rapidsai/cudf/blob/HEAD/CONTRIBUTING.md).
- [x] New or existing tests cover these changes.
- [X] The documentation is up to date with these changes.

### CODE REVIEW

**Comment by PointKernel** [comment]
> While we're here can we look into #11176? We don't have to address it in this PR, but the changes are related since this is all around the refactoring effort to use the new cuco data structures and removing the default_allocator is a step towards #11176. CC @ttnghia

Thanks for bringing this up.

I have that particular PR in my mind when working on this and feel `cuco_helpers.cuh` is a too-specific name while `hashing/detail/helper_functions.cuh` can provide more generic descriptions of what's contained in the file. Several things I'm planning to put in this file: size type sentinel, pair type alias, hash adaptor, and desired occupancy (in the file already but seems not widely used yet), etc. Happy to hear your and other reviewers' thoughts on this.

**Comment by ttnghia** [comment]
> I have that particular PR in my mind when working on this and feel cuco_helpers.cuh is a too-specific name while hashing/detail/helper_functions.cuh can provide more generic descriptions of what's contained in the file.

I see that using `hashing::detail::` is fine, as long as it contains the hashing-related functions. If we call `cuco_helpers` then what is the namespace? `cudf::cuco_helpers::`?

**Comment by ttnghia** [comment]
In addition, calling `helper_functions.cuh` is vague if we mostly put in the cuco stuff there. So maybe `cuco_adapter.cuh`, but still use `namespace cudf::hashing::detail` in it?

**Comment by PointKernel** [comment]
Oh sorry for messing up the git log. Will open another PR to address this work.

**Comment by harrism** [comment]
I look forward to it. This is the only place that libcudf does "raw" allocation using mr->allocate / deallocate.  Removing it helps with our move to `async_resource_ref`.

**Pull request closed without merging**
