### PR TITLE
JNI build image default as cuda11.8

### PR DESCRIPTION
**Pull request by pxLi**
Signed-off-by: Peixin Li <pxli@nyu.edu>

## Description
Update default build image to cuda 11.8

## Checklist
- [X] I am familiar with the [Contributing Guidelines](https://github.com/rapidsai/cudf/blob/HEAD/CONTRIBUTING.md).
- [X] New or existing tests cover these changes.
- [X] The documentation is up to date with these changes.

### CODE REVIEW

**Comment by pxLi** [comment]
rerun tests

**Review by jlowe — APPROVED** [review]

**Comment by pxLi** [comment]
failed unrelated tests. going to retrigger the CI

**Comment by pxLi** [comment]
rerun tests

**Comment by pxLi** [comment]
@gpucibot merge

**Pull request merged**
