### PR TITLE
[WIP] dask_cudf: concatenation by column in repartition_by_hash()

### PR DESCRIPTION
**Pull request by madsbk**
In order to reduce memory pressure, this PR implement concatenation of DataFrames by concatenation individual columns in `repartition_by_hash()`.

### CODE REVIEW

**Comment by kkraus14** [comment]
@madsbk FYI, retargetted to 0.14.

**Comment by harrism** [comment]
@madsbk is this PR still needed? Moving to 0.15.

**Comment by GPUtester** [comment]
Please update the changelog in order to start CI tests.

View the gpuCI docs [here](https://docs.rapids.ai/gpuci#open-pr-or-update-pr).

**Comment by madsbk** [comment]
> @madsbk is this PR still needed? Moving to 0.15.

Let's close it, I am working on a general solution in Dask/Distributed.

**Pull request closed without merging**
