### PR TITLE
[REVIEW] Return the result of `to_json`

### PR DESCRIPTION
**Pull request by wbadart**
When no path is given to `to_json`, it serializes the data to a string (rather than a file). However, this string is lost to the void because the result of the underlying call to pandas is ignored. This results in the following divergence with pandas:

```py
import cudf
import pandas as pd

pdf = pd.DataFrame({'a': [1, 2, 3], 'b': ['a', 'b', 'c']})
gdf = cudf.from_pandas(pdf)

print('pandas:')
print(pdf.to_json())

print('cudf:')
print(gdf.to_json())
```

=>

```
pandas:
{"a":{"0":1,"1":2,"2":3},"b":{"0":"a","1":"b","2":"c"}}
cudf:
/* warning omitted */
None
```

This PR fixes the divergence by returning the results of `to_json`.

I'd really appreciate some guidance from the team on these two considerations:

1. What other IO functions would it make sense to extend in this way? (If there are any, should I tackle them here or in a fresh PR?)
2. I took a first stab at adding a test case. How much coverage are you guys looking for? Like, should I add some checks for other orients and such?

Thanks!

### CODE REVIEW

**Comment by GPUtester** [comment]
Can one of the admins verify this patch?

**Comment by kkraus14** [comment]
ok to test

**Comment by kkraus14** [comment]
Thanks for the PR @wbadart!

**Comment by GPUtester** [comment]
Please update the changelog in order to start CI tests.

View the gpuCI docs [here](https://docs.rapids.ai/gpuci#open-pr-or-update-pr).

**Pull request merged**
