### PR TITLE
[REVIEW] JNI Header Cleanup for cuspacial [skip-ci]

### LINKED ISSUE #5784: [Java] jni_utils.hpp CATCH_STD() with class_name parameter
**Is your feature request related to a problem? Please describe.**
Re-using CATCH_STD(env, ret_val) from jni_utils.hpp in cuspatial JNI layer, the exception class name fixed to be the default cudf::jni::CUDF_ERROR_CLASS.

**Describe the solution you'd like**
```
#define CATCH_STD(env, ret_val)
  CATCH_STD(env, cudf::jni::CUDF_ERROR_CLASS, ret_val)

#define CATCH_STD(env, class_name, ret_val)                                                                    \
  catch (const std::bad_alloc &e) {                                                                \
    /* In some cases a cuda exception can be the cause so peek and clear if needed*/               \
    if (cudaErrorMemoryAllocation == cudaPeekAtLastError()) {                                      \
      cudaGetLastError();                                                                          \
    }                                                                                              \
    JNI_CHECK_THROW_NEW(env, cudf::jni::OOM_CLASS, "Could not allocate native memory", ret_val);   \
  }                                                                                                \
  catch (const std::exception &e) {                                                                \
    /* If jni_exception caught then a Java exception is pending and this will not overwrite it. */ \
    JNI_CHECK_THROW_NEW(env, class_name, e.what(), ret_val);                      \
  }
```
Then user build their JNI based on cudf can re-use CATCH_STD(env, **class_name**, ret_val) 

**Describe alternatives you've considered**
Alternatively user need to maintain another copy of CATCH_STD(env, **class_name**, ret_val)

### PR DESCRIPTION
**Pull request by revans2**
This fixes #5784 

@byin-nvidia

Please take a look at this and let me know if this meets your needs.

### CODE REVIEW

**Comment by GPUtester** [comment]
Please update the changelog in order to start CI tests.

View the gpuCI docs [here](https://docs.rapids.ai/gpuci#open-pr-or-update-pr).

**Comment by revans2** [comment]
@byin-nvidia sorry this got merged before I expected it too.  If you need/want any changes please let me know and I'll see what I can do to put up a new PR.

**Comment by jlowe** [comment]
@revans2 @byin-nvidia my apologies, I saw the offline ping for review of this PR and mistakenly thought this was blocking and needed to go in.  We can definitely do a followup if necessary.

**Comment by byin-nvidia** [comment]
@revans2 @jlowe No worries. The split make sense to me, and no dependency broken in my build. The public jni utils header contains sufficient utils for cuspatial jni for now. Thanks for your response!

**Pull request merged**
