### PR TITLE
Fix comparisons between Series and cudf.NA

### PR DESCRIPTION
**Pull request by brandon-b-miller**
Fixes https://github.com/rapidsai/cudf/issues/7043, gives less than ideal results due to https://github.com/rapidsai/cudf/issues/7066.

### CODE REVIEW

**Comment by brandon-b-miller** [comment]
rerun tests

**Review by galipremsagar — COMMENTED** [review]
Should we add some unit-tests so that we can be sure we don't regress on this fix in the future while changing this part of code?

**Comment by brandon-b-miller** [comment]
@galipremsagar yes we should add tests. When I sat down to write them though, the issue of https://github.com/rapidsai/cudf/issues/7066 came up. This PR causes the code to "work", but we get `nan`-like results. I am not sure if I should write tests that assert that logic since it's arguably not right.

**Review by galipremsagar — APPROVED** [review]
Got it, probably we can just have an `eq` test case and xfail rest of the comparisons(`lt`, `gt`, ...) mentioning the #7066 in xfail reason.

**Pull request merged**
