### PR TITLE
Fix character counting when writing sliced tables into ORC

### PR DESCRIPTION
**Pull request by vuule**
## Description
ORC writer incorrectly counts characters in sliced string columns, ignoring the slice offset. This potentially leads to under-allocated stripes and errors.
This PR fixes the char counting kernel to take the string column offset into account.

## Checklist
- [x] I am familiar with the [Contributing Guidelines](https://github.com/rapidsai/cudf/blob/HEAD/CONTRIBUTING.md).
- [x] New or existing tests cover these changes.
- [ ] The documentation is up to date with these changes.

### CODE REVIEW

**Review by galipremsagar — APPROVED** [review]
Thanks for the fix @vuule ! The issue is also resolved on my local setup.

**Review by davidwendt — APPROVED** [review]
LGTM

**Comment by GregoryKimball** [comment]
Thank you @vuule for quickly finding a solution

**Review by ttnghia — APPROVED** [review]

**Pull request merged**
