### PR TITLE
[REVIEW] Move existing `table` files to legacy/ directory

### PR DESCRIPTION
**Pull request by jrhemstad**
Similar to https://github.com/rapidsai/cudf/pull/2103, in order to avoid conflicts with the new `table` classes I'm creating in https://github.com/rapidsai/cudf/pull/2207, this PR moves all of the existing `table` related files into a `legacy/` directory.

### CODE REVIEW

**Comment by kkraus14** [comment]
rerun tests

**Comment by jrhemstad** [comment]
rerun tests

**Comment by jrhemstad** [comment]
rerun tests

**Comment by kkraus14** [comment]
rerun tests

**Pull request merged**
