### PR TITLE
New docs layout

### PR DESCRIPTION
**Pull request by vyasr**
This PR attempts to simplify our docs layout in a way that requires less manual updating when APIs are changed. For now, this PR just modifies the page containing indexes, but I will roll it out to others if we like it.

### CODE REVIEW

**Comment by vyasr** [comment]
Here's what the pages look like now. Note that the sidebar has two levels instead of 1 so that methods are contained within the classes. Some pages should correspond to modules instead of classes, so we'll need to add a corresponding template for modules. In specific cases where we think that it's worthwhile to group certain top-level functions like I/O or reshaping, we can take a more manual approach to listing specific entities, but at least for our class-level documentation this approach significantly reduces the redundancy of needing to list out all methods.

MainPage
RangeIndex

**Comment by bdice** [comment]
I'm not sure what causes this but I observed painfully slow builds when trying this locally.
`branch-22.06` takes 3m46s to do a clean build of the docs, and the docs' `build` directory is 130MB.
This PR takes 16m47s to do a clean build and the `build` directory is 545MB.

**Comment by vyasr** [comment]
> I'm not sure what causes this but I observed painfully slow builds when trying this locally. `branch-22.06` takes 3m46s to do a clean build of the docs, and the docs' `build` directory is 130MB. This PR takes 16m47s to do a clean build and the `build` directory is 545MB.

Oh yes this is another question that we need to think about, somewhat orthogonal to whether or not we follow the automatic population approach. Currently we only generate docs for index methods on the `cudf.Index` class and don't include documentation of the corresponding methods for other Index classes, so most of them only contain a small set of methods that differ from the parent class. With my current changes that is no longer the case, this branch currently generates a full set of API docs for all Index classes. It's straightforward to remove those extra docs whether or not we use more autodoc in places where we are including all docs, so the decision is independent but also probably worth having the discussion on this PR.

**Comment by vyasr** [comment]
After further discussion with the team, we decided not to pursue this change any further. Matching the pandas layout exactly was deemed to be a higher priority.

**Pull request closed without merging**
