### PR TITLE
[DISCUSSION] CuPy Implementation + benchmarks of row-wise reduction and scan ops

### PR DESCRIPTION
**Pull request by beckernick**
I’d like to raise for discussion using CuPy plus the DLPack and CUDA Array interfaces to implement functionality for nearly the entire suite of standard row-wise reductions and scan operations for Python users. We should support these in libcuDF eventually; this is intended as a discussion of functionality we can implement quickly to empower users that should ultimately be replaced down the road.

The example implementation in this PR provides significantly faster row-wise ops compared to pandas, and works with Dask. This would unlock a large amount of functionality for users with minimal development effort. For large dataframes, the ops are more than 10-20x faster.

This example implementation does not handle missing values because:
- We can't easily (yet) ship missing values via the interfaces
- CuPy currently supports `nansum/prod/min/max` only in the >7.0 versions. CuPy also doesn't yet support `nanmean` and a few others (for example).

This is just an example focused on simplicity/clarity. We could of course eventually switch to use the nan-version functions to allow for them where possible as they are released and as we're able to ship them.

### Background and Problem

Today, users who wish to do row-wise operations on a dataframe have two primary options from which to choose:
- Transpose the dataframe and execute the operations as column-wise operations
- Write a UDF that explicitly defines the desired behavior and leverage apply_rows

Transposing dataframes currently isn’t effective for dataframes beyond a few thousand rows, as the computational time blows up quickly. The primary bottlenecks are currently the non libcuDF based steps of renaming the new columns based on the old index, setting the new index, and allocating many new empty columns. We should optimize this by pushing these steps from Python to Cython and from Cython to libcuDF (where appropriate), but it’s likely going to take some time to support efficient transposes on hundreds of thousands or millions of rows. It also comes with an opportunity cost in terms of other high-priority development work. In the meantime, this isn't a viable option.

Writing a UDF for row-wise operations also comes with significant costs, but in developer time rather than computational time. Such UDFs require explicit enumeration of the logic (which could be quite difficult for ops like cumsum) and careful mapping of column names, among other verbosity requirements. This can quickly become untenable from a user-experience perspective with more than a few columns to manage.

As a result of these two drawbacks, efficient row-wise operations (from both a developer and computational perspective) simply aren’t supported in cuDF today.

### Proposed Solution

This PR illustrates one implementation with a focus on clarity to serve as an example. It’s certainly not the optimal one. It coerces all columns to be of type float64 for simplicity, and it also could be refactored to simply add an axis argument and logic to _apply_support_method.

In this PR, all of the following row-wise operations succeed in cuDF and Dask-cuDF land:
- Max
- Min
- Sum
- Product
- Mean
- Var
- Std
- Cumsum
- Cumprod

With slightly more effort, we could also add `all` and `any`, as well as `quantile` and `median`.

Compatible CuPy conda packaging is in progress. Explicitly adding CuPy as a dependency would allow us to provide users this functionality with minimal development effort on our part. We could also allow this functionality optionally, by including a logical check of whether CuPy is available inside the apply row-wise op function, and raising an error if it’s not. Perhaps something similar to our check of whether NEP-18 is active:

```python
def cupy_available():
    try:
        import cupy as cp
        return True
    except ImportError:
        return False
```

### Initial Benchmarks

The following are loose benchmarks of this example implementation that illustrate a clear speed increase compared to pandas.

For large dataframes (1 million rows x 100 columns), the ops are more than 10-20x faster (all dataframes are dense and full of randomly generated values).

rowwise_ops_benchmarking_large

For medium sized dataframes (100,000 rows), the reduction ops are also significantly faster (5-8x), except when there are very few columns. The scan ops of cumsum and cumprod perform worse with only a few columns, but still perform comparably.

rowwise_ops_benchmarking_small

### CODE REVIEW

**Comment by kkraus14** [comment]
A few things:

1) If row-wise operations are needed we should just support them via libcudf ultimately, but I understand the desire for a stopgap solution.

2) Instead of using DLPack, it would be better if we had a fast operation that returns a 2d dense row-major numba device array that could be passed to cupy via `__cuda_array_interface__` as the codepath is MUCH simpler versus DLPack. See #1898 for feature request for optimization of this as it's currently implemented via a semi-inefficient numba kernel.

3) @devavret @harrism Do you think we could possibly JIT the row-wise ops via libcudf / jitify to handle mixed / different dtypes without having to typecast everything which incurs some huge memory penalties?

**Comment by beckernick** [comment]
I agree with 1 and 2, @kkraus14 (I'm just not the right person to weigh in on 3). We should support these in libcuDF ultimately; this is intended as a discussion of functionality that should ultimately be replaced. This implementation does not handle missing values effectively, for example, due to CuPy currently supporting `nansum` but not yet supporting `nanmean` (for example) and my desire to keep this simple/consistent just as an example. Adding this comment to the original post, as well.

On point two, I do have a question. Would we not need to typecast anyway if we originally columns of different types to create a 2D numba device array, since an ndarray can only have a single dtype.

**Comment by jrhemstad** [comment]
> 3. @devavret @harrism Do you think we could possibly JIT the row-wise ops via libcudf / jitify to handle mixed / different dtypes without having to typecast everything which incurs some huge memory penalties?

@hummingtree is the one who could best answer this.

@beckernick could you provide a very simple Numba UDF that operates on rows of a DF so we can inspect the PTX that is generated?

**Comment by beckernick** [comment]
@jrhemstad @hummingtree 

```python
import cudf
from numba import cuda
​
​
df = cudf.DataFrame()
for i in range(4):
    df['col' + str(i)] = np.random.random(5)
    
    
def rowsum_kernel(col0,col1,col2,col3, out):
    for i, (w, x, y, z) in enumerate(zip(col0, col1, col2, col3)):
        out[i] = w + x + y + z
        
df.apply_rows(rowsum_kernel,
              incols=['col0', 'col1', 'col2', 'col3'],
              outcols=dict(out=np.float64),
              kwargs=dict()
             )
<cudf.DataFrame ncols=5 nrows=5 >
       col0      col1      col2      col3       out
0  0.381408  0.440478  0.723583  0.051394  1.596864
1  0.111574  0.627878  0.301624  0.693015  1.734091
2  0.410537  0.335330  0.372299  0.330936  1.449102
3  0.034103  0.298029  0.375362  0.687435  1.394928
4  0.396269  0.337241  0.987515  0.329759  2.050784


df.sum(axis=1)
<cudf.Series nrows=5 >
0    1.596864
1    1.734091
2    1.449102
3    1.394928
4    2.050784
dtype: float64
```

**Comment by jrhemstad** [comment]
@beckernick 

The formulation you provided specifies a *kernel* to execute. What we need is a device function. 

So we need something like this instead:

```
@cuda.jit(device=True)
def row_function(w, x, y, z, out)
   out = w + x + y + z
   
def rowsum_kernel(col0,col1,col2,col3, out):
    for i, (w, x, y, z) in enumerate(zip(col0, col1, col2, col3)):
        row_function(w,x,y,z, out[i])
```

**Comment by hummingtree** [comment]
> > 1. @devavret @harrism Do you think we could possibly JIT the row-wise ops via libcudf / jitify to handle mixed / different dtypes without having to typecast everything which incurs some huge memory penalties?
> 
> @hummingtree is the one who could best answer this. This is effectively the `n-ary` version of the `cudf::transform` he's already added.
> 
> @beckernick could you provide a very simple Numba UDF that operates on rows of a DF so we can inspect the PTX that is generated?

The current `binary` routine with PTX UDF routines already supports mixed dtypes without casting, i.e. the two input columns, as well as the output column can have different types, as long as they are compatible with the PTX UDF. This should be straight forward to be extended to n-ary operations, expect for `libcudf` to support arbitrary number of input column. But I think with variadic template this is possible.

**Comment by beckernick** [comment]
Thanks @jrhemstad . Is this more consistent with what you need?

```python
import cudf
from numba import cuda
import numpy as np
​
np.random.seed(12)
​
df = cudf.DataFrame()
for i in range(4):
    df['col' + str(i)] = np.random.random(5)
    
​
@cuda.jit('float64(float64, float64, float64, float64)', device=True)
def row_function(w, x, y, z):
    return w + x + y + z
    
def rowsum_kernel(col0, col1, col2, col3, out):
    for i, (w, x, y, z) in enumerate(zip(col0, col1, col2, col3)):
        out[i] = row_function(w, x, y, z)
        
df.apply_rows(rowsum_kernel,
              incols=['col0', 'col1', 'col2', 'col3'],
              outcols=dict(out=np.float64),
              kwargs=dict()
             )
<cudf.DataFrame ncols=5 nrows=5 >
       col0      col1      col2      col3       out
0  0.154163  0.918747  0.283828  0.521226  1.877964
1  0.740050  0.900715  0.606083  0.552038  2.798885
2  0.263315  0.033421  0.944225  0.485377  1.726339
3  0.533739  0.956949  0.852736  0.768134  3.111558
4  0.014575  0.137209  0.002259  0.160717  0.314760

df.sum(axis=1)
<cudf.Series nrows=5 >
0    1.877964
1    2.798885
2    1.726339
3    3.111558
4    0.314760
dtype: float64
```

**Comment by jrhemstad** [comment]
@beckernick that should be perfect.

**Comment by devavret** [comment]
Jitify takes ~150ms to compile a new kernel. This means that with JITing, the operation still won't be faster as a whole, on smaller number of columns. Even with the help of caching, what are the odds that you'll do the same operation on the same number of columns of the same datatypes in the same order.

Instead, we should make a libcudf API that internally uses a series of binary ops. Pretty much all the operations listed here can be done with a combination of binary ops. And there wouldn't be any extra memory needed. Just use the one that we allocate for result. JITing is still involved because you'll be instantiating a new kernel template for each pair of datatypes you want to operate on, but there's a much greater chance of a cache hit with each of these individual ops.

**Comment by jrhemstad** [comment]
> Jitify takes ~150ms to compile a new kernel. This means that with JITing, the operation still won't be faster as a whole, on smaller number of columns. Even with the help of caching, what are the odds that you'll do the same operation on the same number of columns of the same datatypes in the same order.

Yes but, but with file-caching of the JIT kernels, most Python users won't care because they're typically running the same script repeatedly. 

> Instead, we should make a libcudf API that internally uses a series of binary ops. Pretty much all the operations listed here can be done with a combination of binary ops. And there wouldn't be any extra memory needed. Just use the one that we allocate for result. JITing is still involved because you'll be instantiating a new kernel template for each pair of datatypes you want to operate on, but there's a much greater chance of a cache hit with each of these individual ops.

This could work, however, there's some downsides:
- I'm having trouble imaging what the Python interface to such a function would be. You'd have to specify `n` columns and `n-1` binary operations between those columns.
- Requires launching `n-1` kernels for `n` columns vs. doing a single kernel with a UDF row operator
- More limited in the operators that can be supported vs. supporting any generic row-wise operation

One upside to this approach is that we could better handle null values. Since all of the binary operators already handle null values, we could leverage that. However, with a generic n-ary UDF, I don't know how we'd support null elements in the row.

**Comment by devavret** [comment]
> most Python users won't care because they're typically running the same script repeatedly.

Fair point. 

>I'm having trouble imaging what the Python interface to such a function would be. You'd have to specify n columns and n-1 binary operations between those columns

That's not what I thought this was for. I was speaking strictly of making scans and reductions with the approach I mentioned.

>supporting any generic row-wise operation

I'm unsure of its usefulness in the context of this PR. Would it be convenient for a user to make the scan and reduce operations in numba kernels? Could be. I just don't know it so well. @kkraus14 ?

We could just try POCing both approaches.

**Comment by beckernick** [comment]
Super excited about the discussion in this thread. I just wanted to weigh in with what I hope is somewhat representative of the perspective of Python end users.

There's a reason that implementing this functionality in libcuDF wasn't prioritized: libcuDF support for functionality like the following was scoped by @harrism, @randerzander and others as being more important to end users:
- searchsorted
- groupby operations like standard deviation, quantile, cumsum, and others
- cudf::column redesign
- all the other functionality and improvements everyone is currently working on


As primarily a Python user of GPUs, I'm pumped to hear that it's possible to that libcuDF POCs for this could just work. But, if this suite of functionality can be implemented smoothly in the Python layer as a stopgap that gives me 5-25x faster operations without slowing the velocity of crucial libcuDF development, _that's an even bigger win than having it be speed of light from the start and delaying parts of the above list._

Coming from that perspective, I want to also add the following to the discussion:

**Compatible CuPy Packaging**
I believe @jakirkham has a working example of compatible CuPy conda packaging. Is the packaging tied to CuPy 6.2, or is >=7.0 compatible to enable row-wise operations that support missing values?  
If the packaging can support CuPy >= 7.0, in an actual stopgap implementation of this functionality we would probably want to use the CuPy nansum/prod/etc. functions (where they exist).

**DLPack vs CUDA Array interfaces**
The Numba function @kkraus14 mentioned as a candidate for optimization (`as_gpu_matrix`, I believe) does not support missing values. While DLPack is a more complicated codepath, it lets us ship arrays with nulls directly to CuPy. While this would not matter for ops like `sum`, `prod`, `max` and `min`, this distinction would matter for operations like reductions like `mean`, `std`, and `var`.

We could get ahead of that behavior by verifying that there are no missing values before conducting those operations. Or, perhaps more cleanly, we could simply raise a warning that the operations will take place as if the pandas argument `skipna=False` is guaranteed.

If we can support nulls for the listed operations, I think we should. That might mean it's easier to use DLPack (versus refactoring `as_gpu_matrix` to ship nulls). Where we can't, we could raise a warning that we're skipping nulls.

Very interested to also hear from @kkraus14 @randerzander @shwina @thomcom .

**Comment by kkraus14** [comment]
Stale via #2691

**Pull request closed without merging**
