### PR TITLE
Use ARC V2 self-hosted runners for GPU jobs

### PR DESCRIPTION
**Pull request by jjacobelli**
This PR is updating the runner labels to use ARC V2 self-hosted runners for GPU jobs. This is needed to resolve the auto-scalling issues.

### CODE REVIEW

**Review by ajschmidt8 — APPROVED** [review]

**Review by bdice — COMMENTED** [review]
Is there no longer a way to specify “use the latest driver version, any GPU is fine”?

**Comment by bdice** [comment]
> arc-v2 only allows a single label per runner set.

Then does "latest" make sense, or should we always need to specify the driver version?

**Comment by ajschmidt8** [comment]
> > arc-v2 only allows a single label per runner set.
> 
> Then does "latest" make sense, or should we always need to specify the driver version?

We will no longer be using driver-specific labels at all for arc-v2.

There are more details in the PR below (the PR was closed before the force-push that was recently done to that repository, but will be rebased and re-opened soon)

- https://github.com/rapidsai/docs/pull/357

**Pull request merged**
