### PR TITLE
Reduce (shallow) copies in DataFrame ops

### PR DESCRIPTION
**Pull request by mroeschke**
## Description

In particular for ops which only modify the axes

* Reduce multiple shallow copies in `DataFrame.rename`
* Avoid a shallow copy in `DataFrame.to_arrow` until necessary

Also fixes a bug in `DataFrame.rename` to maintain the original `dtype` of the `columns` after renaming

## Checklist
- [ ] I am familiar with the [Contributing Guidelines](https://github.com/rapidsai/cudf/blob/HEAD/CONTRIBUTING.md).
- [ ] New or existing tests cover these changes.
- [ ] The documentation is up to date with these changes.

### CODE REVIEW

**Review by wence- — APPROVED** [review]
One question, should I read this statement:

>  shallow copies instead of deep copies like pandas

To mean "perform shallow copies like pandas, instead of the previous deep copies"?

Or "perform shallow copies, unlike pandas which does deep copies"?

I presume the former?

**Comment by mroeschke** [comment]
> "perform shallow copies like pandas, instead of the previous deep copies"

Yes, this is what I intended to communicate. Sorry for the lack of clarity

**Review by galipremsagar — APPROVED** [review]

**Comment by mroeschke** [comment]
I actually noticed my copy comparisons to pandas was based on the pandas main branch which has copy-on-write enabled and therefore shallow copies could be made instead of deep copies. I reverted changes to the APIs where I changed the deep copy behavior and added a comment instead for a future change with copy on write.

**Comment by wence-** [comment]
I reran things, based on hopefully https://github.com/rapidsai/shared-workflows/pull/221 being fixed

**Comment by vyasr** [comment]
Changes to shared workflows will require pushing an empty commit to restart CI, IIRC just rerunning jobs will reuse the cached workflows from before.

**Pull request merged**
