### PR TITLE
Align Index __init__ APIs with pandas 2.x

### PR DESCRIPTION
**Pull request by mroeschke**
## Description
* It would be nice to have `Index`'s constructor to not go through `IndexMeta.__call__`, but I think that would be a separate effort
* There were a couple `verify_integrity` keyword arguments added that don't raise a `NotImplementedError` since there's not support, but I don't think it's worth making this case falling back in `cudf.pandas` as it's just a validation and won't affect further behavior with the object

## Checklist
- [ ] I am familiar with the [Contributing Guidelines](https://github.com/rapidsai/cudf/blob/HEAD/CONTRIBUTING.md).
- [ ] New or existing tests cover these changes.
- [ ] The documentation is up to date with these changes.

### CODE REVIEW

**Review by galipremsagar — APPROVED** [review]

**Comment by galipremsagar** [comment]
@mroeschke Could you look into the docs build failure: https://github.com/rapidsai/cudf/actions/runs/10061519027/job/27815726597?pr=16362#step:9:4464

**Comment by mroeschke** [comment]
Yeah I ignored that in this commit https://github.com/rapidsai/cudf/pull/16362/commits/7b397be2ee1e27be21538c92f2634ecd97a3189d. It might be due to the sphinx issue linked in `conf.py`

**Pull request merged**
