### PR TITLE
Remove unsafe `reinterpret_cast` and implicit pointer-to-bool casts

### PR DESCRIPTION
**Pull request by lamarrr**
Hi, I've addressed the bug/issue here: #6029
I've made the `dataptr` variable a `void *` as recommended and also made the pointer tests within the file explicit rather than implicit as implicit pointer-to-bool conversion is also undefined behavior.

### CODE REVIEW

**Comment by jrhemstad** [comment]
> implicit pointer-to-bool conversion is also undefined behavior.

AFAIK, implicit pointer-to-bool conversion is well-defined: http://eel.is/c++draft/conv#bool-1

However, I do strongly support explicitly checking against `nullptr` as it is much more legible.

**Comment by kkraus14** [comment]
ok to test

**Review by vuule — APPROVED** [review]

**Comment by kkraus14** [comment]
rerun tests

**Review by harrism — APPROVED** [review]
Welcome, Basit! (And thanks for the contribution. 🙏 )

**Comment by kkraus14** [comment]
rerun tests

**Comment by kkraus14** [comment]
@lamarrr is this good to go or are you still doing more work on it? You have it labelled `[WIP]` 😄

**Comment by lamarrr** [comment]
> > implicit pointer-to-bool conversion is also undefined behavior.
> 
> AFAIK, implicit pointer-to-bool conversion is well-defined: http://eel.is/c++draft/conv#bool-1
> 
> However, I do strongly support explicitly checking against `nullptr` as it is much more legible.

Nice! Thanks for this

**Comment by lamarrr** [comment]
> Welcome, Basit! (And thanks for the contribution. 🙏 )

Thanks, Harris 😁

**Comment by lamarrr** [comment]
> @lamarrr is this good to go or are you still doing more work on it? You have it labelled `[WIP]` 😄

It's good to go. Thanks!

**Comment by kkraus14** [comment]
rerun tests

**Pull request merged**
