### PR TITLE
Switch to DISABLE_DEPRECATION_WARNINGS to match other RAPIDS projects

### PR DESCRIPTION
**Pull request by robertmaynard**
## Description
Use the term `DISABLE_DEPRECATION_WARNINGS` so that we match other RAPIDS projects https://github.com/rapidsai/cuml/pull/4946 plus the plural tense in general makes more sense.

## Checklist
- [x] I am familiar with the [Contributing Guidelines](https://github.com/rapidsai/cudf/blob/HEAD/CONTRIBUTING.md).
- [x] New or existing tests cover these changes.
- [x] The documentation is up to date with these changes.

### CODE REVIEW

**Review by bdice — APPROVED** [review]

**Review by vyasr — APPROVED** [review]

**Comment by vyasr** [comment]
Thanks for following up, I was going to start looking to make sure we were consistent too.

**Comment by robertmaynard** [comment]
@gpucibot merge

**Comment by vyasr** [comment]
@robertmaynard I updated the copyright, that should hopefully be enough to get through tests.

**Comment by robertmaynard** [comment]
@gpucibot merge

**Comment by vyasr** [comment]
@gpucibot merge

**Pull request merged**
