### PR TITLE
[WIP] Convert 10min to cudf to IPython Notebook to avoid GPU CI requirements

### PR DESCRIPTION
**Pull request by beckernick**
**WIP**

This PR converts `10min.rst` to an `ipynb` file and uses the `nbpshinx` extension to build the documentation without relying on GPU-enabled CI.

This PR also resolves two docs errors in cudf 0.3
- Class locations need to be updated for Groupby and GpuArrow
- Sum_of_squares series method is removed (temporarily broken)

### CODE REVIEW

**Comment by harrism** [comment]
@beckernick I also noticed that the developer.rst is way out of date. Still refers to libgdf, directory structure has changed, etc.

**Comment by beckernick** [comment]
Great point. @randerzander, would you rather update those in a separate PR as it may take a bit more time or combine into this one? If we separate, we can change the naming convention of this one to be more specific.

**Comment by kkraus14** [comment]
The larger problem is readthedocs expects a `setup.py` in the root folder of the repository which we obviously don't have. @randerzander @mike-wendt any ideas?

**Comment by randerzander** [comment]
@beckernick - In the interests of fixing the existing broken docs sooner, I'd rather have developer.rst updated in a separate PR.

@kkraus14 - for cuML, we moved setup.py to the root of the repo. Not sure what impact that'd have on CI scripts.

**Comment by harrism** [comment]
@kkraus14 @randerzander RTD seems to support non-standard locations for setup.py: https://github.com/rtfd/readthedocs.org/issues/1567

**Comment by beckernick** [comment]
@randerzander I have a nbsphinx version that won't require readthedocs GPU CI. Will add to this PR and change the naming convention to reflect the updated purpose. Per your comment, we can make a separate PR to address the `developer.rst` suggested by @harrism

**Comment by randerzander** [comment]
fyi - we've switched to [static doc builds](https://rapidsai.github.io/projects/cudf/en/latest/) (at least temporarily).

@beckernick thanks for your work creating the 10min doc, and updating it to make it easier to build.

This looks good to me!

**Comment by harrism** [comment]
@randerzander @beckernick Can one of you resolve the conflicts and add changelog so we can get this merged before 0.5 code freeze next week?

**Comment by harrism** [comment]
Also @randerzander please submit an approving review if you don't have any remaining issues with this PR.

**Pull request closed without merging**
