### PR TITLE
Use `numpy.empty()` instead of `bytearray` to allocate host memory for spilling

### PR DESCRIPTION
**Pull request by madsbk**
A `bytearray` is zero-initialized using `calloc`, which we don't need.  Additionally, `numpy.empty` both skips the zero-initialization and uses hugepages when available <https://github.com/numpy/numpy/pull/14216>.

### CODE REVIEW

**Review by vyasr — APPROVED** [review]
I suspect that there are places in our code that use e.g. numpy.zeros that could also be improved in this way, but that's out of scope for this PR.

**Comment by madsbk** [comment]
rerun tests

**Review by jakirkham — APPROVED** [review]
Looks great! Thanks Mads 😄

Is there anywhere else we should be doing this?

**Comment by madsbk** [comment]
Thanks @jakirkham and @vyasr, I think it can be merged

**Pull request merged**
