### PR TITLE
[REVIEW] Update Errors in docs: 10min-cudf-cupy.ipynb and Dataframes section

### PR DESCRIPTION
**Pull request by taureandyernv**
Solves https://github.com/rapidsai/cudf/issues/3617 by adding an ignore warnings line in the code.

Also solves https://github.com/rapidsai/cudf/issues/3638 dict syntax error in example

Currently, dlpack() warnings show up a couple of times in our documentation notebook https://rapidsai.github.io/projects/cudf/en/0.11.0/10min-cudf-cupy.html#

### CODE REVIEW

**Comment by cwharris** [comment]
Why is Codecov reporting changes in coverage? There all seem to be doc / notebook changes.

**Comment by jakirkham** [comment]
@beckernick, would you be able to take a look at this? 🙂

**Comment by beckernick** [comment]
Nice catch on the small dataframe docstring error. This LGTM also.

With that said, @taureandyernv those dlpack warnings are not superfluous. They are providing materially relevant information.

It might be nice to add a line indicating that cuDF will throw a warning as a reminder to check if you need to transpose your data before using the dlpack interface. I'd not go as far as necessary since transposing is discussed in the current text.

**Comment by taureandyernv** [comment]
> Nice catch on the small dataframe docstring error. This LGTM also.
> 
> With that said, @taureandyernv those dlpack warnings are not superfluous. They are providing materially relevant information.
> 
> It might be nice to add a line indicating that cuDF will throw a warning as a reminder to check if you need to transpose your data before using the dlpack interface. I'd not go as far as saying it's necessary since transposing is discussed in the current text.

@beckernick , great point to keep the warnings as that's the case.  I changed the code to no longer ignore the warnings.

**Comment by kkraus14** [comment]
rerun tests

**Pull request merged**
