### PR TITLE
[REVIEW] Avoid index materialization when `DataFrame` is created with un-named `Series` objects

### PR DESCRIPTION
**Pull request by galipremsagar**
Fixes: #10070 

This PR removed materializing of `index` incase of list-like un-named `Series` inputs are passed to `DataFrame` constructor.

### CODE REVIEW

**Review by vyasr — APPROVED** [review]
We might be able to simplify the code by just inlining `_get_union_of_series_names` since it's a single-use function and the indirection makes this behavior a little more confusing than it needs to be, but for now this LGTM.

**Comment by galipremsagar** [comment]
@gpucibot merge

**Comment by galipremsagar** [comment]
@gpucibot merge

**Review by shwina — APPROVED** [review]

**Comment by galipremsagar** [comment]
Thanks @shwina ! 

@gpucibot merge

**Comment by galipremsagar** [comment]
@gpucibot merge

**Pull request merged**
