### PR TITLE
Default to equal NaNs in make_collect_set_aggregation.

### LINKED ISSUE #11329: Inconsistent default values for null equality and NaN equality
In `cudf::distinct`, we default to [**equal nulls and equal NaNs**](https://github.com/rapidsai/cudf/blob/719f4c8399f54340f51aeb37c79035dfbc3cc749/cpp/include/cudf/stream_compaction.hpp#L279-L280). This aligns with the defaults of `intersect_distinct`, `union_distinct`, and `difference_distinct` in PR #11043 (as of this writing - not yet merged).

However, there are competing standards:
- In `make_collect_set_aggregation`, we default to [**equal nulls and unequal NaNs**](https://github.com/rapidsai/cudf/blob/719f4c8399f54340f51aeb37c79035dfbc3cc749/cpp/include/cudf/aggregation.hpp#L519-L520).
- In `drop_list_duplicates`, we default to [**equal nulls and unequal NaNs**](https://github.com/rapidsai/cudf/blob/719f4c8399f54340f51aeb37c79035dfbc3cc749/cpp/include/cudf/lists/drop_list_duplicates.hpp#L81-L82).

We should strive for a consistent set of defaults for how null and NaN equality are handled. I think I would recommend a change in `make_collect_set_aggregation` and `drop_list_duplicates` to align with the other functions mentioned above.

_Originally posted by @bdice in https://github.com/rapidsai/cudf/pull/11043#discussion_r927186236_

### PR DESCRIPTION
**Pull request by bdice**
## Description
Partially resolves #11329. This helps to align our default behaviors for null and NaN equality across APIs, specifically for `make_collect_set_aggregation` in this PR. All functions should default to treating null values as equal to one another and NaN values as equal to one another.

## Checklist
- [x] I am familiar with the [Contributing Guidelines](https://github.com/rapidsai/cudf/blob/HEAD/CONTRIBUTING.md).
- [x] New or existing tests cover these changes.
- [x] The documentation is up to date with these changes.

### CODE REVIEW

**Comment by bdice** [comment]
rerun tests

**Comment by bdice** [comment]
rerun tests

**Review by davidwendt — APPROVED** [review]
LGTM

**Review by ttnghia — APPROVED** [review]
`NaN` was defaulted to `UNEQUAL` because that (`collect_set`) was implemented as requested for Spark. Anyway, since we have the parameter and Spark explicitly passes in that parameter, the changes in this PR will not cause any breaking.

**Comment by bdice** [comment]
@gpucibot merge

**Pull request merged**
