### PR TITLE
[REVIEW] Fixed inconsistent type of index created with from_pandas vs direct construction

### PR DESCRIPTION
**Pull request by galipremsagar**
Fixes: #2334 
~There is one unit-test failure, which should go away once this PR is merged: #2318~ **<-Fixed in this PR**

### CODE REVIEW

**Comment by kkraus14** [comment]
@galipremsagar there's the following error:
```
=================================== FAILURES ===================================
_________________________ test_drop_duplicates_inplace _________________________

    def test_drop_duplicates_inplace():
        orig = DataFrame(
            {
                "A": ["foo", "bar", "foo", "bar", "foo", "bar", "bar", "foo"],
                "B": ["one", "one", "two", "two", "two", "two", "one", "two"],
                "C": [1, 1, 2, 2, 2, 2, 1, 2],
                "D": range(8),
            }
        )
        orig = cudf.DataFrame.from_pandas(orig)
        # single column
        df = orig.copy()
        df.drop_duplicates("A", inplace=True)
        expected = orig[:2]
        result = df
        assert_df(result, expected)
    
        df = orig.copy()
        df.drop_duplicates("A", keep="last", inplace=True)
>       expected = orig.loc[[6, 7]]

cudf/tests/test_duplicates.py:505: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
cudf/indexing.py:79: in __getitem__
    df = self._getitem_tuple_arg(arg)
cudf/indexing.py:178: in _getitem_tuple_arg
    df.add_column(name=col, data=self._df[col].loc[arg[0]])
cudf/indexing.py:34: in __getitem__
    [], dtype=self._sr.dtype, index=self._sr.index.__class__([])
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <[AttributeError("'RangeIndex' object has no attribute '_stop'") raised in repr()] RangeIndex object at 0x7f3a33c63ba8>
start = 0, stop = [], name = None

    def __init__(self, start, stop=None, name=None):
        """RangeIndex(size), RangeIndex(start, stop)
    
        Parameters
        ----------
        start, stop: int
        name: string
        """
        if isinstance(start, range):
            therange = start
            start = therange.start
            stop = therange.stop
        if stop is None:
            start, stop = 0, start
        self._start = int(start)
>       self._stop = int(stop)
E       TypeError: int() argument must be a string, a bytes-like object or a number, not 'list'

cudf/dataframe/index.py:355: TypeError
```

**Comment by galipremsagar** [comment]
> @galipremsagar there's the following error:
> 
> ```
> =================================== FAILURES ===================================
> _________________________ test_drop_duplicates_inplace _________________________
> 
>     def test_drop_duplicates_inplace():
>         orig = DataFrame(
>             {
>                 "A": ["foo", "bar", "foo", "bar", "foo", "bar", "bar", "foo"],
>                 "B": ["one", "one", "two", "two", "two", "two", "one", "two"],
>                 "C": [1, 1, 2, 2, 2, 2, 1, 2],
>                 "D": range(8),
>             }
>         )
>         orig = cudf.DataFrame.from_pandas(orig)
>         # single column
>         df = orig.copy()
>         df.drop_duplicates("A", inplace=True)
>         expected = orig[:2]
>         result = df
>         assert_df(result, expected)
>     
>         df = orig.copy()
>         df.drop_duplicates("A", keep="last", inplace=True)
> >       expected = orig.loc[[6, 7]]
> 
> cudf/tests/test_duplicates.py:505: 
> _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
> cudf/indexing.py:79: in __getitem__
>     df = self._getitem_tuple_arg(arg)
> cudf/indexing.py:178: in _getitem_tuple_arg
>     df.add_column(name=col, data=self._df[col].loc[arg[0]])
> cudf/indexing.py:34: in __getitem__
>     [], dtype=self._sr.dtype, index=self._sr.index.__class__([])
> _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
> 
> self = <[AttributeError("'RangeIndex' object has no attribute '_stop'") raised in repr()] RangeIndex object at 0x7f3a33c63ba8>
> start = 0, stop = [], name = None
> 
>     def __init__(self, start, stop=None, name=None):
>         """RangeIndex(size), RangeIndex(start, stop)
>     
>         Parameters
>         ----------
>         start, stop: int
>         name: string
>         """
>         if isinstance(start, range):
>             therange = start
>             start = therange.start
>             stop = therange.stop
>         if stop is None:
>             start, stop = 0, start
>         self._start = int(start)
> >       self._stop = int(stop)
> E       TypeError: int() argument must be a string, a bytes-like object or a number, not 'list'
> 
> cudf/dataframe/index.py:355: TypeError
> ```

@kkraus14 
This PR would depend on https://github.com/rapidsai/cudf/pull/2318
As this particular line is going away: https://github.com/rapidsai/cudf/blob/cc1ade105b658866daa50ec978b263bba8b957cd/python/cudf/cudf/indexing.py#L34

**Comment by kkraus14** [comment]
@galipremsagar given that PR may take a bit to be merged, do you want to just fix that line for the time being?

**Comment by galipremsagar** [comment]
> @galipremsagar given that PR may take a bit to be merged, do you want to just fix that line for the time being?

Cool 👍 Sure, looking into it.

**Comment by galipremsagar** [comment]
@kkraus14 Made a fix in indexing which should take care if the index is of type `RangeIndex`.(as rangeIndex is only such index which doesn't take a list input).

Testcases passed locally:
`== 11658 passed, 657 skipped, 85 xfailed, 6 xpassed, 1974 warnings in 357.99 seconds ==`

**Pull request merged**
