### PR TITLE
Rewrite Java API `Table.readJSON` to return the output from libcudf `read_json` directly

### LINKED ISSUE #17002: [FEA] Implement a better JNI function to assemble the output columns from `cudf::read_json`
After reading data using `cudf::read_json`, if the read schema is given, we need to rearrange the output columns from the output table such that the final output columns will have order matched with the column order given in the input schema.

Currently, this process can lead to copying a lot of columns from the output table of `cudf::read_json` (hundreds column) into a structs column, which leads to significant overhead. We can do much better by just moving them instead, so there will be no data copying at all.

### PR DESCRIPTION
**Pull request by ttnghia**
With this PR, `Table.readJSON` will return the output from libcudf `read_json` directly without the need of reordering the columns to match with the input schema, as well as generating all-nulls columns for the ones in the input schema that do not exist in the JSON data. This is because libcudf `read_json` already does these thus we no longer have to do it.

Depends on:
 * https://github.com/rapidsai/cudf/pull/17029

Partially contributes to https://github.com/NVIDIA/spark-rapids/issues/11560.
Closes #17002

### CODE REVIEW

**Review by revans2 — APPROVED** [review]
I love this change. My biggest problem is that this is a breaking change.

I put in a number of changes into the Spark Plugin to provide the emptyRowCount and fully removing those changes is not simple. So either please make sure that this provides some backwards compatibility so we can make the change in a few steps or can we please have the other PR ready to go so that there is very little down time between the two.

**Review by revans2 — APPROVED** [review]

**Comment by ttnghia** [comment]
Changed to non-breaking as the old Java methods are not removed in this PR. We can remove them later on when all the plugin code complete their adaptation.

**Comment by ttnghia** [comment]
After this (with https://github.com/rapidsai/cudf/pull/17029), the overhead of reordering columns is significantly reduced:
image

**Review by revans2 — APPROVED** [review]

**Review by revans2 — APPROVED** [review]

**Pull request merged**
