### PR TITLE
[REVIEW] remove unnecessary std::move() call [skip ci]

### PR DESCRIPTION
**Pull request by rongou**
Newer gcc versions complain about this:
```console
     [exec] [ 91%] Building CUDA object CMakeFiles/cudfjni.dir/src/map_lookup.cu.o
     [exec] /home/rou/src/cudf/java/src/main/native/src/map_lookup.cu: In instantiation of ‘std::unique_ptr<cudf::column> cudf::_GLOBAL__N__57_tmpxft_00012f16_00000000_10_map_lookup_compute_80_cpp1_ii_ab7b9cf2::get_gather_map_for_map_values(const cudf::column_view&, cudf::string_scalar&, rmm::mr::device_memory_resource*, cudaStream_t) [with bool has_nulls = true; cudaStream_t = CUstream_st*]’:
     [exec] /home/rou/src/cudf/java/src/main/native/src/map_lookup.cu:158:104:   required from here
     [exec] /home/rou/src/cudf/java/src/main/native/src/map_lookup.cu:128:28: error: moving a local object in a return statement prevents copy elision [-Werror=pessimizing-move]
     [exec]   128 |   return std::move(gather_map);
     [exec]       |                            ^
     [exec] /home/rou/src/cudf/java/src/main/native/src/map_lookup.cu:128:28: note: remove ‘std::move’ call
     [exec] /home/rou/src/cudf/java/src/main/native/src/map_lookup.cu: In instantiation of ‘std::unique_ptr<cudf::column> cudf::_GLOBAL__N__57_tmpxft_00012f16_00000000_10_map_lookup_compute_80_cpp1_ii_ab7b9cf2::get_gather_map_for_map_values(const cudf::column_view&, cudf::string_scalar&, rmm::mr::device_memory_resource*, cudaStream_t) [with bool has_nulls = false; cudaStream_t = CUstream_st*]’:
     [exec] /home/rou/src/cudf/java/src/main/native/src/map_lookup.cu:158:182:   required from here
     [exec] /home/rou/src/cudf/java/src/main/native/src/map_lookup.cu:128:28: error: moving a local object in a return statement prevents copy elision [-Werror=pessimizing-move]
     [exec] /home/rou/src/cudf/java/src/main/native/src/map_lookup.cu:128:28: note: remove ‘std::move’ call
     [exec] cc1plus: all warnings being treated as errors
     [exec] make[2]: *** [CMakeFiles/cudfjni.dir/build.make:212: CMakeFiles/cudfjni.dir/src/map_lookup.cu.o] Error 1
     [exec] make[1]: *** [CMakeFiles/Makefile2:95: CMakeFiles/cudfjni.dir/all] Error 2
     [exec] make: *** [Makefile:103: all] Error 2
```
@mythrocks

### CODE REVIEW

**Comment by GPUtester** [comment]
Please update the changelog in order to start CI tests.

View the gpuCI docs [here](https://docs.rapids.ai/gpuci#open-pr-or-update-pr).

**Comment by harrism** [comment]
Yeah `return std::move(...);` is to be avoided because it forces the move even when RVO (copy elision) would be better.

**Review by mythrocks — APPROVED** [review]
LGTM.

Thanks, I didn't realize that I could bank on RVO. Makes sense.

**Comment by mythrocks** [comment]
As an aside, I should try moving to GCC-9.

**Pull request merged**
