### PR TITLE
Update cmake and conda to 22.02

### PR DESCRIPTION
**Pull request by devavret**
Changes related to update to 22.02 in one conda environment recipe (only 11.5) was missed. This adds that.
Also makes project version changes in cmake related to update from 21.12 to 22.02.

### CODE REVIEW

**Review by robertmaynard — APPROVED** [review]

**Review by robertmaynard — CHANGES_REQUESTED** [review]
Can you update `ci/release/update-version.sh` to reflect the new CMake code layout that caused the script to miss these

**Comment by devavret** [comment]
rerun tests

**Review by raydouglass — APPROVED** [review]

**Review by robertmaynard — APPROVED** [review]

**Comment by devavret** [comment]
rerun tests

**Review by vyasr — APPROVED** [review]

**Comment by robertmaynard** [comment]
This needs to have latest 22.02 merged in since the failing JIT test issue has been solved

**Comment by trxcllnt** [comment]
rerun tests

**Comment by devavret** [comment]
@gpucibot merge

**Pull request merged**
