### PR TITLE
[REVIEW] Removes noexcept from managed_allocator & a CMakeLists fix for NVstrings

### PR DESCRIPTION
**Pull request by eyalroz**
Fixes two minor issues I noticed today in trying to build libgdf using the cudf master branch (each issue in a separate file): #362 and #363 .

Note: I have only checked that this _builds_, I haven't run any tests, so caveat emptor.

### CODE REVIEW

**Comment by GPUtester** [comment]
Can one of the admins verify this patch?

**Comment by jrhemstad** [comment]
The changes to `managed_allocator` look good to me. @mt-jones or someone else will need to review the cmake changes, as that's not something I have any expertise with.

**Comment by kkraus14** [comment]
add to whitelist

**Comment by kkraus14** [comment]
> Note: I have only checked that this _builds_, I haven't run any tests, so caveat emptor.

GPUtester to the rescue! 😄

**Comment by kkraus14** [comment]
Tests look to pass, cc @harrism since RMM code is being touched to review / merge.

**Comment by harrism** [comment]
@jrhemstad Did you write the managed_allocator classes? I'm wondering why they don't handle the errors from cudaFree. I think I added the throw for RMM errors because I didn't know any other way to handle it (leaving noexcept in was an oversight, not sure why @eyalroz 's compiler caught it and ours didn't).  Anyway, shouldn't we be doing the same thing in the managed_allocator too?

**Comment by eyalroz** [comment]
@harrism : to be honest, I only recently got me a Pascal GPU on my computer at home, and just installed it yesterday.

**Comment by harrism** [comment]
Still interested in @jrhemstad 's answer to my question above, but this is fine to merge.

**Pull request merged**
