### PR TITLE
Fix broken alias from DataFrame.{at,iat} to {loc,iloc}

### PR DESCRIPTION
**Pull request by philtrade**
Fixes issue #5329.  Use `@property` because `loc` and `iloc` are.

### CODE REVIEW

**Comment by GPUtester** [comment]
Can one of the admins verify this patch?

**Comment by shwina** [comment]
ok to test

**Comment by kkraus14** [comment]
ok to test

**Comment by GPUtester** [comment]
Please update the changelog in order to start CI tests.

View the gpuCI docs [here](https://docs.rapids.ai/gpuci#open-pr-or-update-pr).

**Pull request merged**
