### PR TITLE
enable list to be forced as string in JSON reader.

### LINKED ISSUE #15278: [FEA] Support casting of LIST type to STRING in JSON
**Is your feature request related to a problem? Please describe.**

This is a follow on issue for https://github.com/rapidsai/cudf/pull/14936#discussion_r1516854731

Really we just want to be able to request that a column or child column, be returned as a string and it works, even if the data is a nested type.

### PR DESCRIPTION
**Pull request by karthikeyann**
## Description
closes #15278

This PR allows list type also forced as string when mixed type as string is enabled and a user given schema specifies a column as string, in JSON reader.

## Checklist
- [x] I am familiar with the [Contributing Guidelines](https://github.com/rapidsai/cudf/blob/HEAD/CONTRIBUTING.md).
- [x] New or existing tests cover these changes.
- [x] The documentation is up to date with these changes.

### CODE REVIEW

**Review by ttnghia — APPROVED** [review]

**Review by shrshi — APPROVED** [review]

**Comment by GregoryKimball** [comment]
@revans2 is it possible to profile the tree algorithms against `get_json_object_multiple_paths` using this branch?

**Comment by ttnghia** [comment]
> @revans2 is it possible to profile the tree algorithms against `get_json_object_multiple_paths` using this branch?

Sorry we don't use any of this code in `get_json_object` or `get_json_object_multiple_paths` thus they are not comparable.

**Comment by GregoryKimball** [comment]
@karthikeyann is this ready to merge?

**Comment by karthikeyann** [comment]
yes. it's ready to merge.

**Pull request merged**
