### PR TITLE
add templated benchmark with fixture

### PR DESCRIPTION
**Pull request by karthikeyann**
BENCHMARK_TEMPLATE_F is for non-templated benchmark with templated fixture.
BENCHMARK_F is for non-templated benchmark with non-templated fixture.
Google benchmark does not have support for templated benchmark function with non-templated fixture.

Often, BENCHMARK_TEMPLATE_F is used as a proxy for templated benchmark. But templated fixture is not really required here.  It also has limitation of specifying different name for each template.
So, this PR extends google benchmark to support templated benchmark with non-templated fixture.

- [x] Use TEMPLATED_BENCHMARK_F in compiled binary op.
- [x] Use in other relevant benchmarks as well.

Usage:
`TEMPLATED_BENCHMARK_F(FixtureClass,    TemplateFunction, ...);`
`...`  are template arguments

Example:
```
class FixtureClass : public cudf::benchmark {
};

template<typename T, typename U>
void TemplateFunction(benchmark::State& state) {
     for (auto _ : state) {
       // benchmark stuff
     }
}
TEMPLATED_BENCHMARK_F(FixtureClass, TemplateFunction, int, double)->Range(128, 512);
```

### CODE REVIEW

**Review by devavret — APPROVED** [review]
cool stuff

**Comment by robertmaynard** [comment]
I wonder if we should just switch these tests over to NVBench as IIRC it already supports this feature.

**Comment by karthikeyann** [comment]
https://github.com/NVIDIA/nvbench/issues/24 Found this issue. It doesn't have support for fixtures yet.
RAII is good enough.

We should move to nvbench https://github.com/rapidsai/cudf/issues/7960 eventually.
https://github.com/rapidsai/cudf/issues/7960#issuecomment-828091028 `compare.py` equivalent is still pending.

**Review by harrism — APPROVED** [review]

**Comment by karthikeyann** [comment]
@gpucibot merge

**Pull request merged**
