### PR TITLE
Implement pymod, a special modulo that follows python's sign rules

### LINKED ISSUE #1916: [FEA] Create libcudf `pymod` binaryop and plumb to Python __mod__ (%) operator
The `%` operator gives incorrect results when there are negative values in the LHS:

```python

In [13]: print(pd.Series([-1, 1, 2]) % 3)                                                                                                                                                                      
0    2
1    1
2    2
dtype: int64

In [14]: print(cudf.Series([-1, 1, 2]) % 3)                                                                                                                                                                    
0   -1
1    1
2    2
dtype: int64
```

### PR DESCRIPTION
**Pull request by devavret**
Closes #1916

### CODE REVIEW

**Comment by devavret** [comment]
> The existing `Mod` operation could be renamed to `Remainder`, since in C++ the `%` operator is really the "remainder" operator, _not_ the modulo operator. 

Pretty sure it's also called modulo 
https://en.cppreference.com/w/cpp/language/operator_arithmetic
https://en.cppreference.com/w/c/numeric/math/fmod

**Comment by jrhemstad** [comment]
> > The existing `Mod` operation could be renamed to `Remainder`, since in C++ the `%` operator is really the "remainder" operator, _not_ the modulo operator.
> 
> Pretty sure it's also called modulo
> https://en.cppreference.com/w/cpp/language/operator_arithmetic
> https://en.cppreference.com/w/c/numeric/math/fmod

Yes, obviously it's called modulo in C++. The point is that what C++ calls "modulo" doesn't fit what the rest of the world calls "modulo". Hence why I linked that SO article.

**Comment by harrism** [comment]
> In mathematics, the result of the modulo operation is the remainder of the Euclidian division.

So saying that what C/C++ calls modulo is actually a "remainder" is not really meaningful. What "the rest of the world calls modulo" is also not a well-defined thing. See table: https://en.wikipedia.org/wiki/Modulo_operation

I don't think calling the C++ version "Remainder" is a good idea because `remainder` is a floating-point function with different semantics from `%`.

**Comment by harrism** [comment]
Just noticed this is already merged. @devavret I don't think you should merge a PR that has ongoing discussion.

@jrhemstad to be fair if you had an issue, I guess you would have requested changes rather than approving.

**Comment by jrhemstad** [comment]
> So saying that what C/C++ calls modulo is actually a "remainder" is not really meaningful. What "the rest of the world calls modulo" is also not a well-defined thing. See table: https://en.wikipedia.org/wiki/Modulo_operation

Yeah, this table also shows plenty of languages (Ada, Clojure, Lisp, etc) that make the distinction between "remainder" and "mod". I was thinking we could benefit from following the same convention.
 
> I don't think calling the C++ version "Remainder" is a good idea because remainder is a floating-point function with different semantics from %.

What's worse is calling an operation `PyMod`. It doesn't tell a user of the C++ interface what it actually means. In general, we should use descriptions that stand on their own and do not resort to knowledge of another language or library.

**Comment by harrism** [comment]
Please open an issue @jrhemstad .

**Pull request merged**
