### PR TITLE
Fix lists strings scatter to handle zero child rows

### LINKED ISSUE #8098: [BUG] partitioning a column of empty lists of strings fails
**Describe the bug**
If I want to partition something that has a column of lists of strings in it, or a column of lists of lists in it. And all of the first level lists are empty or null then we get an exception.

```
C++ exception with description "cuDF failure at: ../include/cudf/strings/detail/utilities.cuh:52: Invalid iterator range" thrown in the test body.
```

**Steps/Code to reproduce bug**

Not really a complete test, but it shows the error.

```diff
diff --git a/cpp/tests/partitioning/partition_test.cpp b/cpp/tests/partitioning/partition_test.cpp
index ed994da20f..2be2ff1928 100644
--- a/cpp/tests/partitioning/partition_test.cpp
+++ b/cpp/tests/partitioning/partition_test.cpp
@@ -170,6 +170,20 @@ TYPED_TEST(PartitionTest, Struct)
   CUDF_TEST_EXPECT_TABLES_EQUAL(expected, *actual_partitioned_table);
 }
 
+struct PartitionTestNotTyped : public cudf::test::BaseFixture {
+};
+
+
+TEST_F(PartitionTestNotTyped, ListOfStringsEmpty)
+{
+  // WORKS cudf::test::lists_column_wrapper<cudf::string_view> list{{"one", "two"}, {"three", "four", "five"}};
+  cudf::test::lists_column_wrapper<cudf::string_view> list{{}, {}};
+  auto table_to_partition = cudf::table_view{{list}};
+  fixed_width_column_wrapper<int32_t> map{0, 0};
+  // This crashes so no assert checks right now
+  auto result = cudf::partition(table_to_partition, map, 2);
+}
+
 TYPED_TEST(PartitionTest, Reverse)
 {
   using value_type = cudf::test::GetType<TypeParam, 0>;
```

This is enough of a corner case that I think we can ignore it for 0.19, but I really would like to get this fixed in 0.20

### PR DESCRIPTION
**Pull request by davidwendt**
Closes #8098 

The lists scatter code specialization for strings child was not checking the number of child rows equal to 0. This produces an empty strings column. This PR checks for the case and returns an empty column appropriately.
The test-case provided in the #8098 has also been incorporated in the `partition_test.cpp` gtest source.

### CODE REVIEW

**Review by rgsl888prabhu — APPROVED** [review]

**Review by harrism — APPROVED** [review]

**Review by ttnghia — APPROVED** [review]

**Comment by davidwendt** [comment]
rerun tests

**Comment by davidwendt** [comment]
> This is great, but I saw the issue with not just strings. I could also make it happen with a list of lists, not just a list of strings.

I'm not exactly sure what you mean by _lists of lists_. I tried lists of _lists of strings_ and that does not fail with this change.
Can you provide an example?

**Comment by revans2** [comment]
I'm not 100% sure how to create a list of list of bytes in C++. In java if I do that with only null entire or empty lists at the top level it fails in exactly the same way as with strings. I'll try to come up with a repro case on Monday.

**Comment by revans2** [comment]
Sorry it took me so long to get the test figured out for the list side of things. It turns out that the `list_column_wrapper` code for nested lists produced a different layout that would not show the problem. But the java API produces the problematic layout.

```diff
diff --git a/cpp/tests/partitioning/partition_test.cpp b/cpp/tests/partitioning/partition_test.cpp
index 8fb54995ec..af27dc11e3 100644
--- a/cpp/tests/partitioning/partition_test.cpp
+++ b/cpp/tests/partitioning/partition_test.cpp
@@ -294,3 +294,24 @@ TEST_F(PartitionTestNotTyped, ListOfStringsEmpty)
   CUDF_TEST_EXPECT_TABLES_EQUAL(table_to_partition, result.first->view());
   EXPECT_EQ(3, result.second.size());
 }
+
+TEST_F(PartitionTestNotTyped, ListOfListOfIntEmpty)
+{
+  cudf::test::lists_column_wrapper<int32_t> level_2_list;
+
+  fixed_width_column_wrapper<int32_t> level_1_offsets{0, 0, 0};
+  std::unique_ptr<cudf::column> level_1_list = cudf::make_lists_column(2,
+          level_1_offsets.release(),
+          level_2_list.release(),
+          0,
+          {});
+
+  cudf::test::print(*level_1_list);
+
+  auto table_to_partition = cudf::table_view{{*level_1_list}};
+  fixed_width_column_wrapper<int32_t> map{0, 0};
+
+  auto result = cudf::partition(table_to_partition, map, 2);
+  CUDF_TEST_EXPECT_TABLES_EQUAL(table_to_partition, result.first->view());
+  EXPECT_EQ(3, result.second.size());
+}
```

The output looks like
```
[ RUN      ] PartitionTestNotTyped.ListOfListOfByteEmpty
List<List<int32_t>>:
Length : 2
Offsets : 0, 0, 0
   List<int32_t>:
   Length : 0
   Offsets : 
      


unknown file: Failure
C++ exception with description "cuDF failure at: ../include/cudf/strings/detail/utilities.cuh:56: Invalid iterator range" thrown in the test body.
[  FAILED  ] PartitionTestNotTyped.ListOfListOfByteEmpty (0 ms)
```

**Comment by davidwendt** [comment]
Added new gtest from comment above. Fixed the error with the same logic in list_view specialization as for string_view in the same file `lists/detail/scatter.cuh`.

**Review by revans2 — APPROVED** [review]
Looks good to me.

**Comment by davidwendt** [comment]
@gpucibot merge

**Pull request merged**
