### PR TITLE
Move predicates files to legacy

### PR DESCRIPTION
**Pull request by cwharris**

### CODE REVIEW

**Comment by jrhemstad** [comment]
Make sure https://github.com/rapidsai/cudf/pull/3265 is merged before this PR.

**Comment by cwharris** [comment]
rerun tests

**Comment by cwharris** [comment]
@harrism Is this right?

https://github.com/rapidsai/cudf/pull/3270/files#diff-e7594bfb6059a18b2c92a59da9b20b75L74

**Comment by cwharris** [comment]
#2941

**Pull request merged**
