### PR TITLE
[REVIEW] Add deprecation warning for `Series.set_mask` API

### PR DESCRIPTION
**Pull request by galipremsagar**
`Series.set_mask` is more of internal implementation detail that the end-users will not have knowledge about, hence deprecating the API.

### CODE REVIEW

**Comment by galipremsagar** [comment]
rerun tests

**Comment by galipremsagar** [comment]
rerun tests

**Review by vyasr — COMMENTED** [review]
Two questions:
1. Do we have a general policy on removing immediately vs. deprecating? We often making breaking PRs, so not sure how we should weigh that here.
2. Do we want to indicate _when_ we'll remove this deprecated API? Again, not sure whether we have standards for that.

**Comment by galipremsagar** [comment]
> Two questions:
> 
> 1. Do we have a general policy on removing immediately vs. deprecating? We often making breaking PRs, so not sure how we should weigh that here.

Public APIs we usually deprecate in a release and remove in the next consecutive release(s).

> 2. Do we want to indicate _when_ we'll remove this deprecated API? Again, not sure whether we have standards for that.

Don't remember ever specifying a solid version we will remove deprecated API in. There were instances we kept deprecated stuff for years 😆 I plan on removing this next immediate release along with any other bunch of deprecations(if any).

**Review by vyasr — APPROVED** [review]
Sounds good. I would like to formalize some of that a bit in the future, will put that up for discussion in the dev guide.

**Comment by galipremsagar** [comment]
@gpucibot merge

**Pull request merged**
