### PR TITLE
[REVIEW] Port `gather`, `scatter`, and `type_dispatcher` benchmarks to libcudf++

### PR DESCRIPTION
**Pull request by hummingtree**
This PR ports the legacy `gather`, `scatter`, and `type_dispathcher` benchmarks to the Great libcudf++.

Closes part of #4209.

### CODE REVIEW

**Comment by harrism** [comment]
@hummingtree I think it would be better to temporarily keep the old benchmarks around as legacy/, and to run both the old and the new and compare. That way we can catch any major regressions before we remove legacy.

**Comment by hummingtree** [comment]
> @hummingtree I think it would be better to temporarily keep the old benchmarks around as legacy/, and to run both the old and the new and compare. That way we can catch any major regressions before we remove legacy.
That's great. Does CI has the feature to run the benchmarks and report any significant performance regression?

**Comment by karthikeyann** [comment]
> @hummingtree I think it would be better to temporarily keep the old benchmarks around as legacy/, and to run both the old and the new and compare. That way we can catch any major regressions before we remove legacy.

Are legacy APIs removed in this release 0.14? 
PR https://github.com/rapidsai/cudf/pull/4769 
If yes, then legacy benchmarks should go away too.

**Comment by hummingtree** [comment]
> > @hummingtree I think it would be better to temporarily keep the old benchmarks around as legacy/, and to run both the old and the new and compare. That way we can catch any major regressions before we remove legacy.
> 
> Are legacy APIs removed in this release 0.14?
> PR #4769
> If yes, then legacy benchmarks should go away too.

I don't know. @harrism what is the plan in terms of the legacy removing?

**Comment by devavret** [comment]
> My understanding is there will be a giant "legacy removing" PR that removes all the legacies. 

That's what @karthikeyann linked #4769 

> @harrism what is the plan in terms of the legacy removing?

It's supposed to be done in 0.14

**Comment by harrism** [comment]
@hummingtree my point is to report any regressions in this PR so we can discuss.

**Comment by hummingtree** [comment]
> @hummingtree my point is to report any regressions in this PR so we can discuss.

The new gather is always faster than legacy gather. 

For scatter, there isn't significant regression for an inverse map (coalesce_x), but for a random map (coalesce_o) with large column sizes there is an ~20% slow down.

For type_dispatcher, the new device dispatcher is slower than the legacy one for small column sizes.

**Comment by harrism** [comment]
Please file issues for the regressions (with repro instructions -- may have to point to 0.13 or something for the legacy version, so that we can remove the legacy versions).

**Pull request merged**
