### PR TITLE
[WIP] added array cumsum util function

### PR DESCRIPTION
**Pull request by yidong-nvidia**
@yidong-nvidia Please follow the instructions and write a description for this PR.

### CODE REVIEW

**Comment by harrism** [comment]
Definitely reinventing the wheel, since the libcuDF version will be much more efficient and not have JIT overhead.

There is a Python cuDF version but it only provides inclusive prefix sum.

https://github.com/rapidsai/cudf/blob/b3ea8d036f70caa3a208691bbb081c22a90d61bb/python/cudf/utils/cudautils.py#L225

Which calls this:

https://github.com/rapidsai/cudf/blob/branch-0.6/python/cudf/_gdf.py#L345

Which calls into libcudf.

I think we should probably implement Pandas cumsum (and others) rather than the current (hidden) Python API, but they should be wrappers around libcudf functions.

https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.cumsum.html

**Comment by yidong-nvidia** [comment]
thanks for letting me know there is already an existing function for this. I played with it and found there is a bug in computation. Check https://github.com/rapidsai/cudf/issues/860

**Comment by kkraus14** [comment]
@harrism What do you want to do with this PR? My view is kernels of this complexity should just be implemented in libcudf. Additionally, there's no documentation or unit tests so there's still a non-trivial amount of work for this.

**Comment by harrism** [comment]
@kkraus14 my suggestion is the same as I wrote above: "I think we should probably implement Pandas[-like] cumsum (and others) rather than the current (hidden) Python API, but they should be wrappers around libcudf functions."

This Pandas-like `cumsum` and related functions would call into the prefix sum functionality already in libcudf (and we can bug fix and improve that functionality simultaneously).

**Comment by harrism** [comment]
@kkraus14 Assigning this to you to decide on approach and priority for Python API.

**Comment by kkraus14** [comment]
> @kkraus14 my suggestion is the same as I wrote above: "I think we should probably implement Pandas[-like] cumsum (and others) rather than the current (hidden) Python API, but they should be wrappers around libcudf functions."
> 
> This Pandas-like `cumsum` and related functions would call into the prefix sum functionality already in libcudf (and we can bug fix and improve that functionality simultaneously).

Agreed, I don't think we should move forward with this PR and should fix the libcudf functions where necessary. I imagine we'd want a `cumsum` function from the libcudf level as well.

**Comment by harrism** [comment]
@keith we already have it on the libcudf side: `gdf_prefixsum_generic()`. Although it appears not implemented for float types yet?

**Comment by kkraus14** [comment]
> @keith we already have it on the libcudf side: `gdf_prefixsum_generic()`. Although it appears not implemented for float types yet?

ACK. Sorry had a brain fart. Yes we should be able to just utilize that. @yidong-nvidia it would be great if you wanted to tackle extending the libcudf `gdf_prefixsum_generic()` to add the types you're missing and build out the Python bindings.

**Comment by jrhemstad** [comment]
Closing as this PR is superseded by https://github.com/rapidsai/cudf/pull/947

**Pull request closed without merging**
