### PR TITLE
Change cudf::detail::concatenate_masks to return null-count

### PR DESCRIPTION
**Pull request by davidwendt**
## Description
Changes `cudf::detail::concatenate_masks` to also return the null count. This saves computing the null count in a separate kernel launch where this function is used. Also changes the `detail/concatenate.cuh` header to `detail/concatenate_masks.hpp` since contains no device code and only includes the `detail::concatenate_masks()` functions. The `detail::concatenate()` functions are already declared in `detail/concatenate.hpp`.
This is marked as non-breaking since it only effects a detail function.
Reference: https://github.com/rapidsai/cudf/issues/11968

## Checklist
- [x] I am familiar with the [Contributing Guidelines](https://github.com/rapidsai/cudf/blob/HEAD/CONTRIBUTING.md).
- [x] New or existing tests cover these changes.
- [x] The documentation is up to date with these changes.

### CODE REVIEW

**Review by hyperbolic2346 — APPROVED** [review]
Small const nit

**Review by bdice — APPROVED** [review]
This is quite nice. Thanks @davidwendt.

**Review by ajschmidt8 — APPROVED** [review]
Approving `ops-codeowner` file changes

**Pull request merged**
