### PR TITLE
Remove the use of volatile in ORC

### PR DESCRIPTION
**Pull request by vuule**
## Description

`volatile` should no be required in our code, unless there are compiler or synchronization issues.
This PR removes the use in ORC reader and writer.

## Checklist
- [x] I am familiar with the [Contributing Guidelines](https://github.com/rapidsai/cudf/blob/HEAD/CONTRIBUTING.md).
- [x] New or existing tests cover these changes.
- [ ] The documentation is up to date with these changes.

### CODE REVIEW

**Comment by vuule** [comment]
Aiming to merge early in the release so there's plenty of time for *ahem* field testing.

**Comment by vuule** [comment]
The PR increases throughput in benchmarks on average by 16%.

**Review by PointKernel — APPROVED** [review]
LGTM. Nice free speedups.

**Review by bdice — APPROVED** [review]

**Pull request merged**
