### PR TITLE
Remove benchmarks suffix

### PR DESCRIPTION
**Pull request by bdice**
This PR addresses suggestions from @robertmaynard, @karthikeyann, and @harrism in #10093 to remove the suffix `_benchmark` from the name of the benchmark files. The developer guide has been updated to reflect this change.

I left a few shared files with the word "benchmark" in them, such as [cpp/benchmarks/fixture/benchmark_fixture.hpp](https://github.com/rapidsai/cudf/blob/cfb6cbe6a8e4b01d7ee28fbe3212b5f2eb275167/cpp/benchmarks/fixture/benchmark_fixture.hpp) and [cpp/benchmarks/fixture/templated_benchmark_fixture.hpp](https://github.com/rapidsai/cudf/blob/cfb6cbe6a8e4b01d7ee28fbe3212b5f2eb275167/cpp/benchmarks/fixture/templated_benchmark_fixture.hpp).

I built the benchmarks locally to ensure that nothing was broken (I'm noting this because I recall that our CI does not build the benchmarks).

### CODE REVIEW

**Review by robertmaynard — APPROVED** [review]

**Review by karthikeyann — APPROVED** [review]
LGTM 👍

**Comment by harrism** [comment]
CI should build benchmarks. Are you certain it is not? I just fixed this in RMM, which was not.

**Comment by bdice** [comment]
> CI should build benchmarks. Are you certain it is not? I just fixed this in RMM, which was not.

Last I checked this was a month ago: https://github.com/rapidsai/cudf/pull/9905. It's possible this has changed since then, but my comment indicated that CI did not build benchmarks. https://github.com/rapidsai/cudf/pull/9810#discussion_r769161581

**Comment by bdice** [comment]
@harrism I see your changes to RMM https://github.com/rapidsai/rmm/pull/941/ and I think this line indicates we are not building benchmarks in cuDF CI:

https://github.com/rapidsai/cudf/blob/cfb6cbe6a8e4b01d7ee28fbe3212b5f2eb275167/conda/recipes/libcudf/build.sh#L7

Shall I make a follow-up PR to build cuDF benchmarks in CI? There is a trade-off because this would cost additional CI time.

**Review by ttnghia — APPROVED** [review]
Fantastic! Please do the same for `tests/*_tests.*`.

**Comment by bdice** [comment]
@gpucibot merge

**Comment by harrism** [comment]
> @harrism I see your changes to RMM https://github.com/rapidsai/rmm/pull/941/ and I think this line indicates we are not building benchmarks in cuDF CI (missing `benchmarks`):
> 
> 
> 
> https://github.com/rapidsai/cudf/blob/cfb6cbe6a8e4b01d7ee28fbe3212b5f2eb275167/conda/recipes/libcudf/build.sh#L7
> 
> 
> 
> Shall I make a follow-up PR to build cuDF benchmarks in CI? There is a trade-off because this would cost additional CI time.

Would be good to discuss with the team. Not sure what CI time cost would be?

**Comment by bdice** [comment]
> Not sure what CI time cost would be?

I think the best way to find out is to open a draft PR. I'll work on this.

**Comment by karthikeyann** [comment]
> I think the best way to find out is to open a draft PR. I'll work on this.

Use build time metrics html report.

**Pull request merged**
