### PR TITLE
[REVIEW] Enable memory_usage in dask_cudf

### PR DESCRIPTION
**Pull request by rjzamora**
Adding `from_pandas` definition for pd.Index, enabling `memory_usage` on dask_cudf DataFrame objects.  Although #3610 implemented `memory_usage` in cudf, these changes are needed for functionality in dask.

### CODE REVIEW

**Comment by quasiben** [comment]
This PR looks good to me but when i started play with `memory_usage` I saw some strange behavior:

```python
In [1]: import numpy as np

In [2]: import cudf

In [3]: cdf = cudf.DataFrame({'A': np.arange(10), 'B': np.arange(10,20)})

In [4]: foo = cdf.groupby(['A', 'B']).sum()

In [5]: foo.memory_usage()
Out[5]:
Index    160
dtype: int64

In [6]: foo
Out[6]:
Empty DataFrame
Columns: []
Index: [(0, 10), (1, 11), (2, 12), (3, 13), (4, 14), (5, 15), (6, 16), (7, 17), (8, 18), (9, 19)]

In [7]: foo.memory_usage()
Out[7]:
Index    480
dtype: int64
```

Notice that the memory_usage increases after printing the object.  It's unrelated to this PR perhaps I should open an issue

**Comment by rjzamora** [comment]
@quasiben -  That is definitely strange - It seems that you get the `deep=True` result after printing the dataframe...

**Comment by quasiben** [comment]
I think we should merge this is as is and come back to the weirdness in a separate PR/issue.  @kkraus14 thoughts ?

**Comment by kkraus14** [comment]
@quasiben @rjzamora I think this is to be expected. When printing the DataFrame we convert the minimal amount possible to a Pandas dataframe for nice repr things. For MultiIndexes, this means materializing the codes / dictionaries which is what Pandas expects. So we calculate and memoize them. I'm guessing we're actually computing that memory here. cc @thomcom does that sound right from your perspective?

**Comment by thomcom** [comment]
Yes, when sending a DataFrame `to_pandas` the levels (a list of `Series`) and codes (a DataFrame of the same size as its owner) get enumerated. Thanks Keith! It might be possible to improve the memory footprint of printing, at least temporarily, if it is an issue.

**Comment by rjzamora** [comment]
Thanks for the info @kkraus14 and @thomcom - Interesting!

**Pull request merged**
