### PR TITLE
Fix default value of str.split expand parameter.

### PR DESCRIPTION
**Pull request by bdice**
This is a small fix to [match the pandas API](https://pandas.pydata.org/docs/reference/api/pandas.Series.str.split.html) for the `expand` parameter of `Series.str.split`. Only boolean values are allowed. Currently the default is set to `None` and then replaced with the intended default of `False`. This PR changes it to have a default value of `False`.

This is a tiny bit of an API break because users who explicitly passed `None` will now see an error instead of getting the intended default value, but the previous behavior was a bug with respect to pandas API compatibility.

### CODE REVIEW

**Review by galipremsagar — APPROVED** [review]
Thanks @bdice for spotting this!

**Review by charlesbluca — APPROVED** [review]

**Comment by bdice** [comment]
rerun tests

**Comment by bdice** [comment]
rerun tests

**Comment by galipremsagar** [comment]
@gpucibot merge

**Pull request merged**
