### PR TITLE
Update doxyfile project number [skip-ci]

### PR DESCRIPTION
**Pull request by davidwendt**
The Doxyfile project number is set to 0.16. I know I've seen it in the UI before but cannot find it now. I've updated the number just in case. And I've added a line to the update-version.sh (thanks @ajschmidt8 ) to automatically update the file when a new release is created.

Neither of these 2 files effect the CI/CD build.

### CODE REVIEW

**Comment by karthikeyann** [comment]
It would nice to use a Semver tool or practice instead of editing this manually.
Now, README.md, several python files, still have versions manually edited.

**Review by karthikeyann — APPROVED** [review]

**Comment by davidwendt** [comment]
@karthikeyann Why did you remove the _improvement_ label from this?

**Review by ajschmidt8 — APPROVED** [review]

**Comment by ajschmidt8** [comment]
> @karthikeyann Why did you remove the _improvement_ label from this?

@davidwendt, the `Label Checker` CI check shown below will fail if there is more than one category label on a PR.

image

**Comment by davidwendt** [comment]
> > @karthikeyann Why did you remove the _improvement_ label from this?
> 
> @davidwendt, the `Label Checker` CI check shown below will fail if there is more than one category label on a PR.
> 
> image

I thought the 3 categories were _bug_, _improvement_, and _feature_ based on the 3 sections of the changelog.

**Comment by ajschmidt8** [comment]
> > > @karthikeyann Why did you remove the _improvement_ label from this?
> > 
> > 
> > @davidwendt, the `Label Checker` CI check shown below will fail if there is more than one category label on a PR.
> > image
> 
> I thought the 3 categories were _bug_, _improvement_, and _feature_ based on the 3 sections of the changelog.

there are 4 categories (see https://github.com/rapidsai/kb/issues/42):

- bug
- doc
- feature request
- improvement

**Review by harrism — APPROVED** [review]

**Pull request merged**
