### PR TITLE
Adopt experimental row comparator for struct `min` and `max` operators

### PR DESCRIPTION
**Pull request by ttnghia**
This PR modifies struct `min` and `max` operators, changing from using the old row comparator (operating on the flattened table of the input column) into using the experimental row comparator that supports arbitrarily nested types.

Although initial implementation shows some regression in performance, this PR is the precondition to support generic nested types for `min` and `max` operations thus this work is unavoidable.

### CODE REVIEW

**Comment by ttnghia** [comment]
Note that, using the experimental row comparator leads to slightly (significant?) lower performance. A simple benchmark shows that:

Using old comparator:
```
GROUPBY_BENCH
Run on (36 X 4600 MHz CPU s)
CPU Caches:
  L1 Data 32 KiB (x18)
  L1 Instruction 32 KiB (x18)
  L2 Unified 1024 KiB (x18)
  L3 Unified 25344 KiB (x1)
Load Average: 4.47, 4.41, 4.66
***WARNING*** CPU scaling is enabled, the benchmark real time measurements may be noisy and will incur extra overhead.
-----------------------------------------------------------------------------------
Benchmark                                         Time             CPU   Iterations
-----------------------------------------------------------------------------------
Groupby/Aggregation/10000/manual_time          1.06 ms         1.08 ms          492
Groupby/Aggregation/16384/manual_time          1.05 ms         1.07 ms          657
Groupby/Aggregation/65536/manual_time          1.13 ms         1.15 ms          609
Groupby/Aggregation/262144/manual_time         2.02 ms         2.05 ms          329
Groupby/Aggregation/1048576/manual_time        5.13 ms         5.16 ms          137
Groupby/Aggregation/4194304/manual_time        17.7 ms         17.8 ms           37
Groupby/Aggregation/10000000/manual_time       44.2 ms         44.2 ms           15
Groupby/Scan/10000/manual_time                 1.14 ms         1.16 ms          599
Groupby/Scan/16384/manual_time                 1.16 ms         1.19 ms          626
Groupby/Scan/65536/manual_time                 1.33 ms         1.35 ms          527
Groupby/Scan/262144/manual_time                2.14 ms         2.16 ms          325
Groupby/Scan/1048576/manual_time               6.06 ms         6.09 ms          115
Groupby/Scan/4194304/manual_time               21.6 ms         21.7 ms           29
Groupby/Scan/10000000/manual_time              53.9 ms         54.0 ms           13
```

Using new (experimental) comparator:
```
GROUPBY_BENCH
Run on (36 X 4600 MHz CPU s)
CPU Caches:
  L1 Data 32 KiB (x18)
  L1 Instruction 32 KiB (x18)
  L2 Unified 1024 KiB (x18)
  L3 Unified 25344 KiB (x1)
Load Average: 4.85, 4.72, 4.83
***WARNING*** CPU scaling is enabled, the benchmark real time measurements may be noisy and will incur extra overhead.
-----------------------------------------------------------------------------------
Benchmark                                         Time             CPU   Iterations
-----------------------------------------------------------------------------------
Groupby/Aggregation/10000/manual_time          1.29 ms         1.31 ms          437
Groupby/Aggregation/16384/manual_time          1.31 ms         1.33 ms          541
Groupby/Aggregation/65536/manual_time          1.42 ms         1.44 ms          476
Groupby/Aggregation/262144/manual_time         2.07 ms         2.09 ms          335
Groupby/Aggregation/1048576/manual_time        5.78 ms         5.80 ms          109
Groupby/Aggregation/4194304/manual_time        21.7 ms         21.7 ms           32
Groupby/Aggregation/10000000/manual_time       52.3 ms         52.3 ms           13
Groupby/Scan/10000/manual_time                 1.10 ms         1.11 ms          640
Groupby/Scan/16384/manual_time                 1.19 ms         1.21 ms          633
Groupby/Scan/65536/manual_time                 1.28 ms         1.30 ms          564
Groupby/Scan/262144/manual_time                2.38 ms         2.40 ms          311
Groupby/Scan/1048576/manual_time               6.86 ms         6.89 ms           93
Groupby/Scan/4194304/manual_time               24.6 ms         24.7 ms           27
Groupby/Scan/10000000/manual_time              64.3 ms         64.3 ms            8
```

**Comment by ttnghia** [comment]
Just add `DO_NOT_MERGE` label to see if there is anything we can do to improve the performance.

**Comment by jrhemstad** [comment]
The slowdown is surprising as previous results for things like `sort` showed dramatically _improved_ performance. We should definitely explore.

fyi, when showing perf comparisons, it is much appreciated to use the `compare.py` script and report the results from that script so that I don't have to manually copy/paste and compute the slowdown myself.

**Comment by ttnghia** [comment]
Here is the new benchmark. The performance is improved slightly as I switched to cuda 11.7 and gcc-11.
```
╰─ python /home/nghiat/Devel/cudf/4/cpp/build/_deps/benchmark-src/tools/compare.py benchmarks ./0 ./1
RUNNING: ./0 --benchmark_out=/tmp/tmpsy0actz8
2022-05-12T15:28:15-07:00
Running ./0
Run on (36 X 4600 MHz CPU s)
CPU Caches:
  L1 Data 32 KiB (x18)
  L1 Instruction 32 KiB (x18)
  L2 Unified 1024 KiB (x18)
  L3 Unified 25344 KiB (x1)
Load Average: 7.18, 7.55, 13.40
***WARNING*** CPU scaling is enabled, the benchmark real time measurements may be noisy and will incur extra overhead.
-----------------------------------------------------------------------------------
Benchmark                                         Time             CPU   Iterations
-----------------------------------------------------------------------------------
Groupby/Aggregation/10000/manual_time         0.921 ms        0.937 ms          642
Groupby/Aggregation/16384/manual_time         0.887 ms        0.904 ms          774
Groupby/Aggregation/65536/manual_time         0.975 ms        0.993 ms          707
Groupby/Aggregation/262144/manual_time         1.46 ms         1.48 ms          476
Groupby/Aggregation/1048576/manual_time        4.17 ms         4.18 ms          165
Groupby/Aggregation/4194304/manual_time        15.1 ms         15.2 ms           44
Groupby/Aggregation/10000000/manual_time       37.0 ms         37.0 ms           18
Groupby/Scan/10000/manual_time                0.835 ms        0.851 ms          822
Groupby/Scan/16384/manual_time                0.855 ms        0.871 ms          806
Groupby/Scan/65536/manual_time                0.989 ms         1.01 ms          693
Groupby/Scan/262144/manual_time                1.61 ms         1.63 ms          431
Groupby/Scan/1048576/manual_time               4.97 ms         4.99 ms          133
Groupby/Scan/4194304/manual_time               18.8 ms         18.8 ms           35
Groupby/Scan/10000000/manual_time              45.9 ms         45.9 ms           15
RUNNING: ./1 --benchmark_out=/tmp/tmpm2o88ip6
2022-05-12T15:28:29-07:00
Running ./1
Run on (36 X 4600 MHz CPU s)
CPU Caches:
  L1 Data 32 KiB (x18)
  L1 Instruction 32 KiB (x18)
  L2 Unified 1024 KiB (x18)
  L3 Unified 25344 KiB (x1)
Load Average: 6.38, 7.37, 13.28
***WARNING*** CPU scaling is enabled, the benchmark real time measurements may be noisy and will incur extra overhead.
-----------------------------------------------------------------------------------
Benchmark                                         Time             CPU   Iterations
-----------------------------------------------------------------------------------
Groupby/Aggregation/10000/manual_time         0.992 ms         1.01 ms          701
Groupby/Aggregation/16384/manual_time          1.01 ms         1.02 ms          687
Groupby/Aggregation/65536/manual_time          1.11 ms         1.13 ms          626
Groupby/Aggregation/262144/manual_time         1.73 ms         1.75 ms          399
Groupby/Aggregation/1048576/manual_time        5.18 ms         5.20 ms          126
Groupby/Aggregation/4194304/manual_time        18.9 ms         19.0 ms           35
Groupby/Aggregation/10000000/manual_time       46.4 ms         46.4 ms           15
Groupby/Scan/10000/manual_time                0.930 ms        0.947 ms          740
Groupby/Scan/16384/manual_time                0.947 ms        0.962 ms          723
Groupby/Scan/65536/manual_time                 1.10 ms         1.11 ms          631
Groupby/Scan/262144/manual_time                1.86 ms         1.87 ms          375
Groupby/Scan/1048576/manual_time               5.84 ms         5.86 ms          114
Groupby/Scan/4194304/manual_time               21.9 ms         21.9 ms           31
Groupby/Scan/10000000/manual_time              53.4 ms         53.4 ms           13
Comparing ./0 to ./1
Benchmark                                                  Time             CPU      Time Old      Time New       CPU Old       CPU New
---------------------------------------------------------------------------------------------------------------------------------------
Groupby/Aggregation/10000/manual_time                   +0.0779         +0.0774             1             1             1             1
Groupby/Aggregation/16384/manual_time                   +0.1356         +0.1338             1             1             1             1
Groupby/Aggregation/65536/manual_time                   +0.1351         +0.1327             1             1             1             1
Groupby/Aggregation/262144/manual_time                  +0.1851         +0.1830             1             2             1             2
Groupby/Aggregation/1048576/manual_time                 +0.2446         +0.2436             4             5             4             5
Groupby/Aggregation/4194304/manual_time                 +0.2503         +0.2500            15            19            15            19
Groupby/Aggregation/10000000/manual_time                +0.2519         +0.2517            37            46            37            46
Groupby/Scan/10000/manual_time                          +0.1140         +0.1123             1             1             1             1
Groupby/Scan/16384/manual_time                          +0.1065         +0.1045             1             1             1             1
Groupby/Scan/65536/manual_time                          +0.1083         +0.1065             1             1             1             1
Groupby/Scan/262144/manual_time                         +0.1528         +0.1513             2             2             2             2
Groupby/Scan/1048576/manual_time                        +0.1753         +0.1747             5             6             5             6
Groupby/Scan/4194304/manual_time                        +0.1685         +0.1683            19            22            19            22
Groupby/Scan/10000000/manual_time                       +0.1631         +0.1632            46            53            46            53
```

**Comment by ttnghia** [comment]
I ran performance profiling (ncu-ui) and it shows this comparison for the most expensive kernel (`thrust::reduce_by_key`):
 * Old comparator: run time is 560s, registers/thread = 80
 * New comparator: run time is 745s, register/thread = 128

Maybe the number of registers/thread is where we should blame?

**Comment by jrhemstad** [comment]
> * New comparator: run time is 745s, register/thread = 128

Yeah, that is likely the problem. That is a pretty significant increase and is probably impacting occupancy.

> Fixing performance regression of the new comparator is of-of-scope of this PR and it should be addressed separately.

Sure, but then this PR shouldn't be merged until we've better understood the source of the regression. I don't see a reason to needlessly merge a performance regression without more analysis.

**Comment by ttnghia** [comment]
> Sure, but then this PR shouldn't be merged until we've better understood the source of the regression. I don't see a reason to needlessly merge a performance regression without more analysis.

Okay, then let's halt this until further analysis.

**Comment by vyasr** [comment]
@ttnghia should we pick this back up given all the recent activity on comparators?

**Comment by ttnghia** [comment]
> @ttnghia should we pick this back up given all the recent activity on comparators?

This one stalled because the new experimental comparator is slower when comparing structs. I believe that when we have more optimized comparator (such as https://github.com/rapidsai/cudf/issues/12932 and https://github.com/rapidsai/cudf/issues/13032) then we can resume this.

**Comment by vyasr** [comment]
Closing in favor of #13069

**Pull request closed without merging**
