### PR TITLE
Upgrade to nvCOMP 3.0.4

### PR DESCRIPTION
**Pull request by vuule**
## Description
Update the nvCOMP version used for cuIO compression/decompression to 3.0.4.

## Checklist
- [x] I am familiar with the [Contributing Guidelines](https://github.com/rapidsai/cudf/blob/HEAD/CONTRIBUTING.md).
- [x] New or existing tests cover these changes.
- [x] The documentation is up to date with these changes.

### CODE REVIEW

**Review by bdice — COMMENTED** [review]
We need to update these files before merging:
- `fetch_rapids.cmake` -- revert changes to this file once the upstream rapids-cmake PR is merged.
- https://github.com/rapidsai/cudf/blob/56fe5dbb32bb6d4f4ab954e1abea9218fed404e1/conda/recipes/libcudf/conda_build_config.yaml#L41 -- update to 3.0.4
- https://github.com/rapidsai/cudf/blob/56fe5dbb32bb6d4f4ab954e1abea9218fed404e1/dependencies.yaml#L230 -- update to 3.0.4

Also remove "TEST" From the PR title.

**Review by bdice — APPROVED** [review]

**Review by raydouglass — APPROVED** [review]

**Comment by bdice** [comment]
^ Triggering a merge for when CI finishes. I expect it to pass based on the build logs I was watching.

**Pull request merged**
