### PR TITLE
Include <optional> in headers that use std::optional

### PR DESCRIPTION
**Pull request by robertmaynard**
Detected when compiling with gcc-11 where <optional> wasn't being brought in by other standard headers

### CODE REVIEW

**Comment by robertmaynard** [comment]
rerun tests

**Review by bdice — APPROVED** [review]
LGTM.

**Review by davidwendt — APPROVED** [review]

**Comment by robertmaynard** [comment]
rerun tests

**Review by ttnghia — APPROVED** [review]

**Comment by robertmaynard** [comment]
rerun tests

**Comment by davidwendt** [comment]
Looks like another PR (#10067) has been opened that does this too.
From there it looks like a benchmark file has been missed in this PR.
https://github.com/rapidsai/cudf/pull/10067/files#diff-8ea6c0e0bf3596d2913e6ac09171c05f4fd18e88e5cfcb5897844f9aa5a8637bR34

**Comment by robertmaynard** [comment]
> Looks like another PR (#10067) has been opened that does this too. From there it looks like a benchmark file has been missed in this PR. https://github.com/rapidsai/cudf/pull/10067/files#diff-8ea6c0e0bf3596d2913e6ac09171c05f4fd18e88e5cfcb5897844f9aa5a8637bR34

I will revise. I was only building `libcudf` so I missed that

**Comment by robertmaynard** [comment]
rerun tests

**Comment by robertmaynard** [comment]
@gpucibot merge

**Comment by rongou** [comment]
rerun tests

**Comment by robertmaynard** [comment]
CI failures are resolved by https://github.com/rapidsai/cudf/pull/10008

**Comment by vyasr** [comment]
rerun tests

**Review by vyasr — APPROVED** [review]

**Pull request merged**
