### PR TITLE
[REVIEW] Fix handling read only schema buffers in gpuarrow reader

### LINKED ISSUE #1766: [BUG] GpuArrowReader behavior changed between 0.6 and 0.7 (ValueError: buffer source array is read-only)
**Describe the bug**
In pymapd, we are seeing a bug when using cudf 0.7.1 with GpuArrowReader. Our code passes the following to GpuArrowReader:

```python
    schema_buffer = np.frombuffer(schema_buffer[0].to_pybytes(),
                                  dtype=np.uint8)

    dtype = np.dtype(np.byte)
    darr = cuda.devicearray.DeviceNDArray(shape=dptr.size,
                                          strides=dtype.itemsize,
                                          dtype=dtype,
                                          gpu_data=dptr)
    reader = GpuArrowReader(schema_buffer, darr)
```

This code works in cudf 0.6 to create a cudf dataframe.

**Steps/Code to reproduce bug**
```python
In [6]: df = con.select_ipc_gpu("select start_station_latitude from fordgobike_tripdata")
Traceback (most recent call last):

  File "<ipython-input-6-c183a84f9277>", line 1, in <module>
    df = con.select_ipc_gpu("select start_station_latitude from fordgobike_tripdata")

  File "/home/rzwitch/github_work/pymapd/pymapd/connection.py", line 306, in select_ipc_gpu
    df = _parse_tdf_gpu(tdf)

  File "/home/rzwitch/github_work/pymapd/pymapd/_parsers.py", line 203, in _parse_tdf_gpu
    reader = GpuArrowReader(schema_buffer, darr)

  File "cudf/bindings/gpuarrow.pyx", line 203, in cudf.bindings.gpuarrow.GpuArrowReader.__init__

  File "cudf/bindings/gpuarrow.pyx", line 228, in cudf.bindings.gpuarrow.GpuArrowReader._open

  File "cudf/bindings/gpuarrow.pyx", line 248, in cudf.bindings.gpuarrow.GpuArrowReader._parse_metdata

  File "stringsource", line 654, in View.MemoryView.memoryview_cwrapper

  File "stringsource", line 349, in View.MemoryView.memoryview.__cinit__

ValueError: buffer source array is read-only

```

**Expected behavior**
The expected behavior would be to return a cudf in the same way it is returned in cudf 0.6.

**Environment details (please complete the following information):**
 - Please run and attach the output of the `cudf/print_env.sh` script to gather relevant environment details
 
Environment: Ubuntu 18.04 LTS, conda environment install

### PR DESCRIPTION
**Pull request by kkraus14**
Fixes #1766

### CODE REVIEW

**Comment by kkraus14** [comment]
Wait for confirmation from @randyzwitch that this resolves the problem before merging.

**Comment by kkraus14** [comment]
rerun tests

**Comment by randyzwitch** [comment]
Trying with @kkraus14 's patch fails (with a different error though):

```python
In [3]: df = conn.select_ipc_gpu("select start_station_latitude from fordgobike_tripdata")                                                                          
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-3-c559a331e63c> in <module>
----> 1 df = conn.select_ipc_gpu("select start_station_latitude from fordgobike_tripdata")

~/github_work/pymapd/pymapd/connection.py in select_ipc_gpu(self, operation, parameters, device_id, first_n, release_memory)
    304         self._tdf = tdf
    305 
--> 306         df = _parse_tdf_gpu(tdf)
    307 
    308         # Deallocate TDataFrame at OmniSci instance

~/github_work/pymapd/pymapd/_parsers.py in _parse_tdf_gpu(tdf)
    201                                           dtype=dtype,
    202                                           gpu_data=dptr)
--> 203     reader = GpuArrowReader(schema_buffer, darr)
    204     df = DataFrame()
    205     df.set_tdf = MethodType(set_tdf, df)

cudf/bindings/gpuarrow.pyx in cudf.bindings.gpuarrow.GpuArrowReader.__init__()

cudf/bindings/gpuarrow.pyx in cudf.bindings.gpuarrow.GpuArrowReader._open()

cudf/bindings/gpuarrow.pyx in cudf.bindings.gpuarrow.GpuArrowReader._parse_metdata()

ValueError: Buffer dtype mismatch, expected 'const char' but got 'unsigned char'
```

**Comment by randyzwitch** [comment]
@kkraus14 we're good here, pulled in 41b9c95 and tested and it appears to have fixed the issue

**Pull request merged**
