### PR TITLE
[WIP] Removing? `data` method from `column_device_view`

### PR DESCRIPTION
**Pull request by codereport**
This is a work in progress.

### CODE REVIEW

**Comment by GPUtester** [comment]
Please update the changelog in order to start CI tests.

View the gpuCI docs [here](https://docs.rapids.ai/gpuci#open-pr-or-update-pr).

**Comment by trevorsm7** [comment]
I suppose instead of removing `.data()` entirely, we could just disable it for T=fixed_point. That would prevent it from being used in any of the common fixed width specializations, but would still allow it to be used for strings.

It does look like the strings stuff _could_ work with iterators, but would require changing a lot of function signatures from `const char*` to `template <typename Iterator>`... Probably not worth the effort.

**Comment by codereport** [comment]
> I suppose instead of removing `.data()` entirely, we could just disable it for T=fixed_point. That would prevent it from being used in any of the common fixed width specializations, but would still allow it to be used for strings.
> 
> It does look like the strings stuff _could_ work with iterators, but would require changing a lot of function signatures from `const char*` to `template <typename Iterator>`... Probably not worth the effort.

Sounds like a plan to me!

**Comment by harrism** [comment]
Can you add a reference to an issue this closes? The question mark in the title worries me -- should there be a discussion issue?

**Comment by codereport** [comment]
> Can you add a reference to an issue this closes? The question mark in the title worries me -- should there be a discussion issue?

There is no issue atm, but I can add one and a summary of the discussion that Trevor and I have had.

**Comment by harrism** [comment]
Issues are good for logging discussion and decisions made, and they can also help with tracking (though they are not always required for that purpose). This just sounded like there was a not insignificant decision made...

**Comment by codereport** [comment]
Work for this direction was dropped, fixed-point PR can be found here: https://github.com/rapidsai/cudf/pull/5704

**Pull request closed without merging**
