### PR TITLE
Implement DataFrame._get_numeric_data

### LINKED ISSUE #1355: [FEA] Add DataFrame._get_numeric_data method
Many operations work on only numeric columns.  Consider for example `std` on DataFrame objects with both numeric and string columns.  This is handled in Pandas with the `_get_numeric_data` method.  This would help improve functionality within dask-cudf when we have mixed types.

### PR DESCRIPTION
**Pull request by mrocklin**
Fixes #1355

### CODE REVIEW

**Comment by mrocklin** [comment]
(I haven't tested this yet (not on VPN at the moment), I would wait on approval until tests pass)

**Comment by kkraus14** [comment]
> (I haven't tested this yet (not on VPN at the moment), I would wait on approval until tests pass)

Can't merge until tests pass anyway :)

**Comment by mrocklin** [comment]
Thanks for the fix @kkraus14 !

**Comment by kkraus14** [comment]
> Thanks for the fix @kkraus14 !

Thanks for the PR! 😄

**Pull request merged**
