### PR TITLE
Handle host frames in serialization

### PR DESCRIPTION
**Pull request by jakirkham**
Depends on PR ( https://github.com/rapidsai/cudf/pull/5308 )

As some serialization strategies may rely on some or all frames on host, add logic to `Serializable` to track which frames are on host or device and ensure they are handled appropriately. This should help cases like pack/unpack ( https://github.com/rapidsai/cudf/pull/5025 ) and allow `Serializable` to be used by other objects using host frames like those in FIL ( https://github.com/rapidsai/cuml/pull/2263 ).

Note: Adding this as a draft for now, though am not aware of anything missing from it (unless reviewers spot something ;)

cc @shwina @hcho3

### CODE REVIEW

**Comment by shwina** [comment]
FWIW the `pickle` failure you're seeing here is resolved in the downstream PR #5025; although I'm not clear on why it comes up here.

**Comment by jakirkham** [comment]
Thanks! Yeah was looking at that as well. It looks like you were able to [drop `serialize`/`deserialize` from `DataFrame`]( https://github.com/rapidsai/cudf/pull/5025/files?file-filters%5B%5D=.py&file-filters%5B%5D=No+extension#diff-d4816377962eac0ab58997c5037843af ). Wonder if there is something missing in those methods.

**Comment by jakirkham** [comment]
After looking more closely at the test failures here, I think this is the same issue we ran into yesterday. IOW the pickle test is assuming approximate equality of the size of the pickled data to the size of the Python object. However pickling will always tack in more information for the unpickling process. So we should just be checking that the pickled data is at least as big as the original data (though most likely bigger). Submitted PR ( https://github.com/rapidsai/cudf/pull/5334 ), which grabs your change from PR ( https://github.com/rapidsai/cudf/pull/5025 ). Hopefully once that is in we will clear the failure here.

**Comment by jakirkham** [comment]
Merged in `branch-0.15` with the pickle test fix. Let's see if that resolves it.

**Pull request merged**
