### PR TITLE
move input generation for json benchmark to device

### PR DESCRIPTION
**Pull request by karthikeyann**
- Use device functions to move input generation to device in json benchmark.
- Use raw string literal for readability
- replace BENCHMARK_CAPTURE with benchmark fixture without template.

Splitting PR https://github.com/rapidsai/cudf/pull/10109 for review

### CODE REVIEW

**Review by nvdbaranec — APPROVED** [review]
Looks good.

**Review by robertmaynard — APPROVED** [review]
Approving the CMake changes

**Review by robertmaynard — APPROVED** [review]
Device side data generation LGTM

**Comment by karthikeyann** [comment]
@gpucibot merge

**Pull request merged**
