### PR TITLE
Don't use CMake 3.25.0 as it has a show stopping FindCUDAToolkit bug

### PR DESCRIPTION
**Pull request by robertmaynard**
## Description
Don't use CMake 3.25.0 as it has a show stopping FindCUDAToolkit bug

## Checklist
- [x] I am familiar with the [Contributing Guidelines](https://github.com/rapidsai/cudf/blob/HEAD/CONTRIBUTING.md).
- [x] New or existing tests cover these changes.
- [x] The documentation is up to date with these changes.

### CODE REVIEW

**Review by galipremsagar — APPROVED** [review]
Thanks for the quick fix @robertmaynard !

**Review by ajschmidt8 — APPROVED** [review]

**Comment by galipremsagar** [comment]
rerun tests

**Comment by galipremsagar** [comment]
@gpucibot merge

**Comment by vyasr** [comment]
rerun tests

**Pull request merged**
