### PR TITLE
Pin libcudf runtime dependency for cudf / libcudf-kafka nightlies

### PR DESCRIPTION
**Pull request by charlesbluca**
Looking at the cudf nightlies on Anaconda, I noticed we aren't pinning the libcudf dependency, only constraining it to the current minor version (i.e. `libcudf >=22.2.0a.211206,<22.3.0a0`); this makes it possible to install mismatched versions of cudf and libcudf nightlies, which can result in a broken cudf installation.

This PR pins the libcudf runtime dependency for our cudf nightlies, as well as for libcudf-kafka, which also has a libcudf runtime dependency.

### CODE REVIEW

**Review by ajschmidt8 — APPROVED** [review]
Hmm. It looks like it used to be in the recipe many years ago, but was removed [here](https://github.com/rapidsai/cudf/commit/5e38eebefd12e28652742de5be2407254f665461#diff-7124683c66bb4a7c20a6d7c4e88742936e4484929a208418e009d6f8bf2fe47e) by @kkraus14. Not sure if he has any input here. Looks fine to me though, so I'm inclined to approve.

**Comment by charlesbluca** [comment]
Wondering if we should also do this for `libcudf_kafka`, which also has libcudf as an unpinned dependency for its nightlies?

**Review by ajschmidt8 — APPROVED** [review]

**Comment by kkraus14** [comment]
> Hmm. It looks like it used to be in the recipe many years ago, but was removed [here](https://github.com/rapidsai/cudf/commit/5e38eebefd12e28652742de5be2407254f665461#diff-7124683c66bb4a7c20a6d7c4e88742936e4484929a208418e009d6f8bf2fe47e) by @kkraus14. Not sure if he has any input here. Looks fine to me though, so I'm inclined to approve.

IIRC this was very early on in cudf and the desire at the time was to allow changing the nightly libcudf version underneath cudf to pull in nightly bug fixes in libcudf without necessarily pulling in changes in cudf. It likely isn't relevant anymore now that cudf is a lot more mature.

**Comment by charlesbluca** [comment]
Thanks for the clarification @kkraus14 🙂 in that case, think we should be safe to merge this

**Comment by charlesbluca** [comment]
Hmm actually I didn't consider the case where the versions match up but the build strings don't; for example, it would still be possible to do something like

```bash
mamba install cudf=*=cuda_11_py38_g38631a635f_189 libcudf=*=cuda11_gdb9aef8181_190
```

And end up with a broken cuDF installation (which is exactly what happened in this [erroneous image build](https://gpuci.gpuopenanalytics.com/job/dask/job/dask-build-environment/job/branch/job/dask-build-env-main/172/BUILD_NAME=dask_sql,CUDA_VER=11.2,LINUX_VER=ubuntu18.04,PYTHON_VER=3.8,RAPIDS_VER=22.02/console) for dask-sql's gpuCI).

Would it be too restrictive to pin nightlies by their git describe tag and number?

```yaml
    - libcudf {{ version }} *{{ GIT_DESCRIBE_HASH }}_{{ GIT_DESCRIBE_NUMBER }}
```

**Comment by ajschmidt8** [comment]
> Hmm actually I didn't consider the case where the versions match up but the build strings don't; for example, it would still be possible to do something like
> 
> ```shell
> mamba install cudf=*=cuda_11_py38_g38631a635f_189 libcudf=*=cuda11_gdb9aef8181_190
> ```
> 
> And end up with a broken cuDF installation (which is exactly what happened in this [erroneous image build](https://gpuci.gpuopenanalytics.com/job/dask/job/dask-build-environment/job/branch/job/dask-build-env-main/172/BUILD_NAME=dask_sql,CUDA_VER=11.2,LINUX_VER=ubuntu18.04,PYTHON_VER=3.8,RAPIDS_VER=22.02/console) for dask-sql's gpuCI).
> 
> Would it be too restrictive to pin nightlies by their git describe tag and number?
> 
> ```yaml
>     - libcudf {{ version }} *{{ GIT_DESCRIBE_HASH }}_{{ GIT_DESCRIBE_NUMBER }}
> ```

Hmmm. I think that was attempted before and caused some issues: https://github.com/rapidsai/cudf/pull/7793

**Comment by charlesbluca** [comment]
In that case I'm okay with merging this for now, as it should at least reduce some conda solving issues. I'm interested in what the failures were cc @raydouglass in case you recall - it looks like the pinning was originally meant to solve https://github.com/rapidsai/ops/issues/1490 but it didn't?

**Comment by ajschmidt8** [comment]
@charlesbluca, for reference, we're currently exploring a lot of improvements to our current build/CI system.

One of the things we're looking into is consolidating our recipes, similarly to what's [described here](https://docs.conda.io/projects/conda-build/en/latest/resources/variants.html#transition-guide) (particularly the screenshot below). This would let us build the CPP and Python packages from a single recipe and pin the Python packages to the exact CPP package from the same build. No word on any ETAs yet, but just wanted to let you know that this is something we're looking into.

image

**Review by ajschmidt8 — APPROVED** [review]
LGTM. We can discuss this more with @jakirkham in the upcoming meeting that I mentioned to you. For now, this is in line with how `cuml` does things, so it should be fine.

**Comment by ajschmidt8** [comment]
@gpucibot merge

**Comment by ajschmidt8** [comment]
(I deployed some updates that broke the merge bot which is probably why the initial `@gpucibot merge` command didn't work. They've since been reverted)

**Pull request merged**
