### PR TITLE
[WIP] Add dask_cudf split_partitions API

### PR DESCRIPTION
**Pull request by rjzamora**
This PR adds a convenience API (`dask_cudf.split_partitions`) to split all partitions of a dask_cudf DataFrame.  The criteria for the number of splits within each partition can be based on the maximum row-count or byte size desired  in each *final* partition.  That is, the user can pass the *desired* maximum length (`max_length`), or the *desired* maximum byte size (`max_size`).

To split each partition, we initially try to split along index-value boundaries.  If a partition contains only a single index key, we fall back to a linear split within the (initially) homogeneous partition.

cc @quasiben @beckernick @randerzander

### CODE REVIEW

**Comment by beckernick** [comment]
@rjzamora @quasiben , Based on https://github.com/rapidsai/cudf/blob/004ecc1cd179ee8dd93b464ecdee50a52afa35e9/python/dask_cudf/dask_cudf/tests/test_core.py#L534-L542

It looks like the conceptual idea here is the following:
- Run set index, and generate whatever currently comes out
- Split partitions accordingly

Please correct me if I'm misunderstanding, though

This conceptually solves the case in which we can run `set_index` and *create* super-partitions without running out of memory, but does not solve the underlying issue of creating super-partitions in the first place. If we end up with co-located super-partitions (same GPU), we can suddenly blow up memory and fail during the `set_index`.

Is there perhaps an opportunity to address the partition size within the `set_index` operation itself, so the shuffle + combine doesn't create them in the first place?

**Comment by rjzamora** [comment]
@beckernick - The point of this feature is just to reduce your partition sizes (given a desired size or row-count maximum).  It does not improve imbalance in `set_index` results - The only way to do that is to improve the division calculation used in the "planning" stage of the distributed sort.

Overall - This feature is only meant to help you "recover" from imbalanced partitions if you know they might cause a problem in a donw-stream calculation, it will not help prevent the imbalance from happening.  If this is not particularly useful to you guys, I completely understand, and can focus my attention elsewhere :)

**Comment by harrism** [comment]
What is the status of this PR for 0.13? Please remember to add PRs to projects so they don't get missed for a release.

image

**Comment by rjzamora** [comment]
@beckernick - I am closing this  since the improved division calculation made the new function unnecessary (I think). I am happy to revisit if needed.

**Pull request closed without merging**
