### PR TITLE
Add new patch to hide more CCCL APIs

### PR DESCRIPTION
**Pull request by vyasr**
## Description

See rapidsai/rapids-cmake#580

## Checklist
- [x] I am familiar with the [Contributing Guidelines](https://github.com/rapidsai/cudf/blob/HEAD/CONTRIBUTING.md).
- [x] New or existing tests cover these changes.
- [x] The documentation is up to date with these changes.

### CODE REVIEW

**Review by bdice — APPROVED** [review]

**Review by robertmaynard — CHANGES_REQUESTED** [review]
`cpp/cmake/thirdparty/patches/kernel_pointer_hiding.diff` isn't required anymore since we have merged that patch into rapids-cmake proper

**Comment by vyasr** [comment]
Whoops thanks I had updated the path but didn't delete.

**Comment by vyasr** [comment]
This failure is odd. I see builds of other packages like cuml succeeding with the new patch from upstream rapids-cmake, so I wonder if there's something wrong with how this patch works with cudf's other patches.

**Review by robertmaynard — APPROVED** [review]

**Pull request merged**
