### PR TITLE
Introduce a common parent class for NumericalColumn and DecimalColumn

### PR DESCRIPTION
**Pull request by vyasr**
Adds a common parent class for NumericalColumn and DecimalColumn that implements the common operations (mainly reductions and scans). As part of enabling this, the _copy_type_metadata method was refactored to have different column types override it to perform column-specific tasks (necessary because DecimalColumn has some special handling), which should also provide some marginal performance improvements for methods that copy metadata.

This PR (and some to follow) are designed to help simplify the ongoing [Array refactoring](#8273).

### CODE REVIEW

**Review by kkraus14 — APPROVED** [review]

**Review by galipremsagar — APPROVED** [review]

**Comment by galipremsagar** [comment]
@vyasr Looks like there are some test failures in `test_transform.py` that are linked to this refactor, could you take a look at it?

**Comment by vyasr** [comment]
Yes sorry I noticed this failure but I've been focusing on #8214 for the past few days. I should hit a good stopping point this afternoon to come back and wrap up my open Python PRs including this one.

**Comment by kkraus14** [comment]
Marking this as breaking since we don't technically hide the Column class even though we don't intend for it to be part of our public API.

**Comment by kkraus14** [comment]
@gpucibot merge

**Pull request merged**
