### PR TITLE
Move cudf::char_utf8 definition from detail to public header

### PR DESCRIPTION
**Pull request by davidwendt**
## Description
Moves the `cudf::char_utf8` definition from the `cudf/strings/detail/utf8.hpp` to `cudf/types.hpp` since it is declared in the public namespace and used in public functions.

Reference: https://github.com/rapidsai/cudf/blob/9acddc08cc209e8d6b94891be6131edd63ff5b43/docs/cudf/source/conf.py#L372-L375

## Checklist
- [x] I am familiar with the [Contributing Guidelines](https://github.com/rapidsai/cudf/blob/HEAD/CONTRIBUTING.md).
- [x] New or existing tests cover these changes.
- [x] The documentation is up to date with these changes.

### CODE REVIEW

**Review by PointKernel — APPROVED** [review]

**Review by ttnghia — APPROVED** [review]

**Comment by ttnghia** [comment]
@davidwendt Do we need to update [cudf/docs/cudf/source/conf.py](https://github.com/rapidsai/cudf/blob/9acddc08cc209e8d6b94891be6131edd63ff5b43/docs/cudf/source/conf.py#L372-L375) accordingly?

**Comment by davidwendt** [comment]
> @davidwendt Do we need to update [cudf/docs/cudf/source/conf.py](https://github.com/rapidsai/cudf/blob/9acddc08cc209e8d6b94891be6131edd63ff5b43/docs/cudf/source/conf.py#L372-L375) accordingly?

That is a good question. I made @vyasr a reviewer. I think that I can just remove the comment.

**Review by vyasr — COMMENTED** [review]
Thanks for this David! Yes, you can remove the comment as well as the line below it that actually says `"char_utf8"`.

**Review by vyasr — APPROVED** [review]

**Pull request merged**
