### PR TITLE
[REVIEW] Create issue templates

### PR DESCRIPTION
**Pull request by mike-wendt**
The idea is to use the same templates throughout RAPIDS, but start here as this is the largest repo. 

For a "live" preview see my repo https://github.com/mike-wendt/cudf/issues/new/choose

### CODE REVIEW

**Comment by mike-wendt** [comment]
@datametrician good to get your thoughts on these as well as you asked for them

**Comment by mike-wendt** [comment]
https://github.com/mike-wendt/cudf/issues/new/choose < For a "live" preview I have the same templates and labels in my repo to try out and get feedback on

**Comment by datametrician** [comment]
I like this a lot. The only thing I could think of was example, but that could fall in docs.

**Comment by harrism** [comment]
This is awesome. My number one suggestion is to start every template with "INSTRUCTIONS: read the following instructions. REPLACE the instructions with answers to the instructions", or something like that. Currently people leave all the text of the templates in place and basically ignore the fact that the template is instructions. The instructions should make it clear that you shouldn't leave the instructions in your issue.

**Comment by mrocklin** [comment]
I didn't realize that this was possible.  I like it.  

I also like the cleanliness of the text.  It's more welcoming than the previous set from a newcomer's perspective.

**Comment by jrhemstad** [comment]
Is it possible to automatically label the issue depending on what kind of issue it is? e.g., add `bug` label when someone opens an issue via the "Bug report" template.

**Comment by mike-wendt** [comment]
> Is it possible to automatically label the issue depending on what kind of issue it is? e.g., add `bug` label when someone opens an issue via the "Bug report" template.

Yes each issue will be tagged automatically if they use a template.

**Pull request merged**
