### PR TITLE
Update read_parquet to align with upstream-dask improvements

### PR DESCRIPTION
**Pull request by rjzamora**
Once [dask#6346](https://github.com/dask/dask/pull/6346) is merged, a few read_parquet tests will break for dask_cudf.  This PR aligns `CudfEngine` with the upstream improvements.

### CODE REVIEW

**Comment by GPUtester** [comment]
Please update the changelog in order to start CI tests.

View the gpuCI docs [here](https://docs.rapids.ai/gpuci#open-pr-or-update-pr).

**Comment by jakirkham** [comment]
Thanks Rick! 😄

So this is just WIP in the sense that we want to wait for PR ( https://github.com/dask/dask/pull/6346 ) to be merged? Or are there other changes still needed here?

**Comment by rjzamora** [comment]
> So this is just WIP in the sense that we want to wait for PR ( dask/dask#6346 ) to be merged? Or are there other changes still needed here?

It doesn't really need to be WIP, I just expect CI to fail before dask/dask#6346 is merged.

**Comment by jakirkham** [comment]
Looks like it was just merged 🙂

**Comment by rjzamora** [comment]
Thanks for the quick review @jakirkham !

**Pull request merged**
