### PR TITLE
Fix some issues with deprecated / removed cccl facilities

### PR DESCRIPTION
**Pull request by miscco**
`cub::If` has been deprecated and should not be used. There is a better alternative in `cuda::std::conditional_t`

`thrust::{binary, unary}_function` has been deprecated and does not serve a purpose similar to the removed `std::{binary, unary}_function`

Rather than relying on the type aliases one should use the `std::invoke` machinery

### CODE REVIEW

**Review by miscco — COMMENTED** [review]
Note: I am not sure what the current release branch is, we might want to bring this into 24.08

**Review by miscco — COMMENTED** [review]
This is technically potentially breaking, although all breakage would rather be a code smell and should be fixed

**Comment by miscco** [comment]
Yeah happy to remove the breaking label. 

The only issue could be if a user would try to build 24.08 with a newer CCCL version, which I believe means they should just upgrade to the latest branch

**Review by bdice — APPROVED** [review]

**Review by ttnghia — APPROVED** [review]

**Review by bernhardmgruber — APPROVED** [review]

**Pull request merged**
