### PR TITLE
Add stream parameter to Set Operations (Public List APIs)

### PR DESCRIPTION
**Pull request by SurajAralihalli**
This PR marks the conclusion of the List API series. The PR introduces the stream parameter to the Set operations (Public List Comparison and Intersection APIs).

 Comparison and Intersection (`set_operations.hpp`)

```
have_overlap
intersect_distinct
union_distinct
difference_distinct
```

Reference [13744](https://github.com/rapidsai/cudf/issues/13744)
## Checklist
- [X] I am familiar with the [Contributing Guidelines](https://github.com/rapidsai/cudf/blob/HEAD/CONTRIBUTING.md).
- [X] New or existing tests cover these changes.
- [X] The documentation is up to date with these changes.

### CODE REVIEW

**Comment by ttnghia** [comment]
Those are not "list" operations. They are set operations---"list" is something else.

**Comment by SurajAralihalli** [comment]
Thanks @ttnghia. I have updated the PR title and description.

**Review by ttnghia — APPROVED** [review]

**Review by shrshi — COMMENTED** [review]
Looks good to me, thanks!

**Comment by SurajAralihalli** [comment]
The test for `pr / conda-cpp-build / build (11.8.0, ubuntu22.04, amd64, 3.10)` failed with the following error. This error didn't show up during local build and testing because it originates from the benchmarks suite. I'm moving this PR to draft and will investigate the issue further.

```
$SRC_DIR/cpp/benchmarks/lists/set_operations.cpp:53:10: error: use of deleted function 'constexpr rmm::cuda_stream_view::cuda_stream_view(int)'
   53 |     bfunc(cudf::lists_column_view{*lhs},
      |     ~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   54 |           cudf::lists_column_view{*rhs},
      |           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   55 |           cudf::null_equality::EQUAL,
      |           ~~~~~~~~~~~~~~~~~~~~~~~~~~~
   56 |           cudf::nan_equality::ALL_EQUAL,
      |           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   57 |           rmm::mr::get_current_device_resource());
      |           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from $PREFIX/include/rmm/device_buffer.hpp:18,
                 from $SRC_DIR/cpp/include/cudf/utilities/span.hpp:19,
                 from $SRC_DIR/cpp/include/cudf/column/column_view.hpp:20,
                 from $SRC_DIR/cpp/include/cudf/column/column.hpp:18,
                 from $SRC_DIR/cpp/include/cudf/table/table.hpp:18,
                 from $SRC_DIR/cpp/benchmarks/common/generate_input.hpp:19,
                 from $SRC_DIR/cpp/benchmarks/lists/set_operations.cpp:17:
$PREFIX/include/rmm/cuda_stream_view.hpp:51:13: note: declared here
   51 |   constexpr cuda_stream_view(int)            = delete;  //< Prevent cast from 0
```

**Comment by davidwendt** [comment]
To reproduce locally, add the `-DBUILD_BENCHMARKS=ON` option to your local cmake build.

**Comment by ttnghia** [comment]
Just to update the benchmark code to add `stream` param. 
This is when CI/CD shows its advantages.

**Comment by SurajAralihalli** [comment]
Thanks @davidwendt @ttnghia, I'll do that!

**Review by hyperbolic2346 — APPROVED** [review]

**Pull request merged**
