### PR TITLE
Move rolling impl details to detail/ directory.

### LINKED ISSUE #11211: [BUG] Move `_detail` in `rolling/` to `rolling/detail`
The contents of `cpp/src/rolling/` are a mix of `_detail` files that are private to implementation. This includes `rolling_detail.hpp`, `rolling_detail.cuh`, and an assortment of aggregation-specific files.
It would be best to follow the custom that other modules are using, and putting these under `cpp/src/rolling/detail`.

### PR DESCRIPTION
**Pull request by mythrocks**
Fixes #11211.

The contents of `cpp/src/rolling/` are a mix of `_detail` files that are private to implementation. This includes `rolling_detail.hpp`, `rolling_detail.cuh`, and an assortment of aggregation-specific files.
This commit moves these under `cpp/src/rolling/detail`, thus bringing `rolling` into compliance with other modules.

Note that there are no changes to functionality. Only the paths of existing source files have been reshuffled.

### CODE REVIEW

**Comment by mythrocks** [comment]
I have taken @devavret off the hook, and added @vyasr whose suggestion prompted this change.

**Review by vyasr — COMMENTED** [review]
Missed one: https://github.com/rapidsai/cudf/blob/branch-22.08/cpp/src/rolling/jit/kernel.cu#L18. I would also double-check the other JIT rolling files just in case.

**Comment by mythrocks** [comment]
> Missed one: https://github.com/rapidsai/cudf/blob/branch-22.08/cpp/src/rolling/jit/kernel.cu#L18. I would also double-check the other JIT rolling files just in case.

Thanks for catching that, @vyasr. I think I've gotten them all now.

**Review by bdice — APPROVED** [review]
Approving because it’s a pure renaming. It might be nice to know if the detail includes in test files are testing detail APIs or only using them for test setup.

**Review by ttnghia — APPROVED** [review]

**Review by vyasr — APPROVED** [review]

**Comment by mythrocks** [comment]
> be nice to know if the detail includes in test files are testing detail APIs or only using them for test setup.

It's being used to construct reference/expected outputs for different tests.

When further functionality was adding in `rolling`, the suggestion was made that we use explicitly hardcoded reference outputs, rather than to use production code for it. This makes it easier to "follow along". The newer tests do this. `rolling_test` (and part of `grouped_rolling_test`) are legacy.

**Pull request merged**
