### PR TITLE
Add hive partitioning and file-aggregation to dask-cudf ORC API

### PR DESCRIPTION
**Pull request by rjzamora**
This PR is an adaptation of an ORC API that was originally intended for Dask-Dataframe ([dask#8004](https://github.com/dask/dask/pull/8004)).  That PR was closed, because it was decided that Dask-Dataframe support for hive-partitioning and filtering should rely on the (yet-to-be developed) `pyarrow.dataset` ORC API.  The long term plan for dask-cudf is to rely on these upstream `pyarrow.dataset`/`dask.dataframe` features (once they are completed).

In the mean time, it seems reasonable to offer the "experimental" ORC API in dask-cudf for hive-partitioning and file-aggregation features.  Note that the original "legacy" `dask_cudf.read_orc` API can still be accessed by passing `legacy=True`.

**NEW read_orc API**:

```python
def read_orc(
    path,
    engine="cudf",
    legacy=False,
    columns=None,
    index=None,
    filters=None,
    split_stripes=1,
    aggregate_files=None,
    storage_options=None,
    gather_statistics=True,
    files_per_metadata_task=None,
    sample_data=None,
    read_kwargs=None,
):
    """Read dataframe from ORC file(s)
    Parameters
    ----------
    path: str or list(str)
        Location of file(s), which can be a full URL with protocol
        specifier, and may include glob character if a single string.
    engine: str, default "cudf"
        IO engine label to pass to cudf backend.
    legacy: bool, default False
        Whether to use the legacy ``dask_cudf.read_orc`` implementation.
    columns: None or list(str)
        Columns to load. If None, loads all.
    index: str
        Column name to set as index.
    filters : None or list of tuple or list of lists of tuples
        Specifies a filter predicate used to filter out row groups using
        statistics stored for each row group as Parquet metadata. Row
        groups that do not match the given filter predicate are not read. The
        predicate is expressed in disjunctive normal form (DNF) like
        `[[('x', '=', 0), ...], ...]`. DNF allows arbitrary boolean logical
        combinations of single column predicates. The innermost tuples each
        describe a single column predicate. The list of inner predicates is
        interpreted as a conjunction (AND), forming a more selective and
        multiple column predicate. Finally, the outermost list combines
        these filters as a disjunction (OR). Predicates may also be passed
        as a list of tuples. This form is interpreted as a single conjunction.
        To express OR in predicates, one must use the (preferred) notation of
        list of lists of tuples.
    split_stripes: int or False
        Maximum number of ORC stripes to include in each output-DataFrame
        partition. Use False to specify a 1-to-1 mapping between files
        and partitions. Default is 1.
    aggregate_files : bool or str, default False
        Whether distinct file paths may be aggregated into the same output
        partition. A setting of True means that any two file paths may be
        aggregated into the same output partition, while False means that
        inter-file aggregation is prohibited. If the name of a partition
        column is specified, any file within the same partition directory
        (e.g. ``"/<aggregate_files>=*/"``) may be aggregated.
    storage_options: None or dict
        Further parameters to pass to the bytes backend.
    gather_statistics : bool, default True
        Whether to gather file and stripe statistics from the orc metadata.
    files_per_metadata_task : int, optional
        Number of files to process within each metadata-processing task.
        Default is ``32``. If set to ``0``, metadata-processing will be
        performed in serial (on the client).
    sample_data : bool, optional
        Whether to sample data to construct output collection metadata.
    read_kwargs : dict, optional
        Dictionary of key-word arguments to pass to the partition-level
        IO function.
    Returns
    -------
    dask_cudf.DataFrame (even if there is only one column)
    """
```

**NEW to_orc API**:

```python
def to_orc(
    df,
    path,
    write_index=True,
    append=False,
    partition_on=None,
    storage_options=None,
    compute=True,
    compute_kwargs=None,
    **kwargs,
):
    """Write a dask_cudf dataframe to ORC file(s). There will be one output
    file per partition, unless `partition_on` is specified (in which case
    each partition may be split into multiple files).
    Parameters
    ----------
    df : dask_cudf.DataFrame
    path: string or pathlib.Path
        Destination directory for data.  Prepend with protocol like ``s3://``
        or ``hdfs://`` for remote data.
    write_index : boolean, optional
        Whether or not to write the index. Defaults to True.
    append : boolean, default False
        If False (default), construct data-set from scratch. If True, add new
        file(s) to an existing data-set (if one exists).
    partition_on : list, default None
        Construct directory-based partitioning by splitting on these fields'
        values. Each dask partition will result in one or more datafiles,
        there will be no global groupby.
    storage_options: None or dict
        Further parameters to pass to the bytes backend.
    compute : bool, optional
        If True (default) then the result is computed immediately. If False
        then a ``dask.delayed`` object is returned for future computation.
    compute_kwargs : dict, default True
        Options to be passed in to the compute method
    **kwargs :
        Key-word arguments to be passed on to ``cudf.to_orc``.
    """
```

### CODE REVIEW

**Comment by rjzamora** [comment]
cc @randerzander

**Comment by vyasr** [comment]
@rjzamora I've retargeted this to 21.12 since it looks like there's still a ways to go and reviewers are tied up elsewhere. If you think it's crucial to make it into 21. If you think it's crucial to get it into 21.10 we can try to reprioritize.

**Comment by vyasr** [comment]
@rjzamora what's the status on this PR? Do we still anticipate this moving forward, or have we decided to wait on pyarrow as well?

**Comment by rjzamora** [comment]
>@rjzamora what's the status on this PR? Do we still anticipate this moving forward, or have we decided to wait on pyarrow as well?

I will close this for now.  My assumption is that there is no rush here, and so we might as well implement most of this in dask.  It is about time for me to check on the state of pyarrow-ORC anyway :)

@randerzander - Feel free to say otherwise if partitioned/aggregated/filtered ORC support is back to "high-priority."

**Pull request closed without merging**
