### PR TITLE
Add missing device_scalar stream parameters.

### LINKED ISSUE #6580: [BUG] Missing stream arguments to `device_scalar` methods
**Describe the bug**
I found several `device_scalar` method calls that don't pass the stream argument available in the scope. They will not be synchronized correctly if the passed explicit stream is non-blocking. Here is the list of mistakes I found:

https://github.com/rapidsai/cudf/blob/branch-0.17/cpp/src/bitmask/null_mask.cu#L450
https://github.com/rapidsai/cudf/blob/branch-0.17/cpp/src/copying/concatenate.cu#L233
https://github.com/rapidsai/cudf/blob/branch-0.17/cpp/src/join/hash_join.cu#L218
https://github.com/rapidsai/cudf/blob/branch-0.17/cpp/src/join/hash_join.cu#L275
https://github.com/rapidsai/cudf/blob/branch-0.17/cpp/src/join/hash_join.cu#L292
https://github.com/rapidsai/cudf/blob/branch-0.17/cpp/src/join/hash_join.cuh#L120
https://github.com/rapidsai/cudf/blob/branch-0.17/cpp/src/join/hash_join.cuh#L140
https://github.com/rapidsai/cudf/blob/branch-0.17/cpp/src/join/hash_join.cuh#L142
https://github.com/rapidsai/cudf/blob/branch-0.17/cpp/src/join/nested_loop_join.cuh#L89
https://github.com/rapidsai/cudf/blob/branch-0.17/cpp/src/join/nested_loop_join.cuh#L98

### PR DESCRIPTION
**Pull request by harrism**
Fixes #6580 .  Adds missing stream parameters in various calls to `rmm::device_scalar` methods. Also removes one unused line of code and fixes a narrowing cast warning (nvcc warning that wasn't being treated as error).

### CODE REVIEW

**Comment by GPUtester** [comment]
Please update the changelog in order to start CI tests.

View the gpuCI docs [here](https://docs.rapids.ai/gpuci#open-pr-or-update-pr).

**Comment by magnatelee** [comment]
I found another place where the stream argument is missing: 
https://github.com/rapidsai/cudf/blob/branch-0.17/cpp/src/join/hash_join.cu#L224

**Review by davidwendt — APPROVED** [review]

**Comment by cwharris** [comment]
Should we delete the default `stream` arguments?

https://github.com/rapidsai/rmm/blob/210c863b34314737fe5a3eacb213333926b72294/include/rmm/device_scalar.hpp#L76-L102

**Review by cwharris — APPROVED** [review]

**Comment by harrism** [comment]
> Should we delete the default `stream` arguments?
> 
> https://github.com/rapidsai/rmm/blob/210c863b34314737fe5a3eacb213333926b72294/include/rmm/device_scalar.hpp#L76-L102

Not in this PR.

**Review by karthikeyann — APPROVED** [review]

**Comment by harrism** [comment]
rerun tests

**Pull request merged**
