### PR TITLE
Implement user_datasource_wrapper is_empty() and is_device_read_preferred().

### PR DESCRIPTION
**Pull request by tpn**
## Description
These two routines are missing from the current `user_datasource_wrapper` impl.

## Checklist
- [x] I am familiar with the [Contributing Guidelines](https://github.com/rapidsai/cudf/blob/HEAD/CONTRIBUTING.md).
- [ ] New or existing tests cover these changes.
- [x] The documentation is up to date with these changes.

### CODE REVIEW

**Comment by tpn** [comment]
Friendly ping for another `/ok to test`... I think the one on Friday bombed out for unrelated reasons.

**Review by hyperbolic2346 — APPROVED** [review]

**Comment by tpn** [comment]
Want me to rebase this against 23.12?  I think it's otherwise ready to merge, correct?

**Comment by tpn** [comment]
Friendly ping, any thoughts on getting this merged?

**Comment by davidwendt** [comment]
cc @vuule

**Review by vuule — APPROVED** [review]
Looks good
Thank you for the patch!

**Pull request merged**
