### PR TITLE
[REVIEW] Fixing cudf reduction for POWER platform

### PR DESCRIPTION
**Pull request by pradghos**
Fixes https://github.com/rapidsai/cudf/issues/1545

### CODE REVIEW

**Comment by GPUtester** [comment]
Can one of the admins verify this patch?

**Comment by jrhemstad** [comment]
okay to test

**Comment by kkraus14** [comment]
ok to test

**Comment by kkraus14** [comment]
@jrhemstad given this is just Cython there's no libcudf changes needed, right?

**Comment by harrism** [comment]
The only reason I didn't put this fix in last week was because Jake said we should do this instead: https://github.com/rapidsai/cudf/issues/1751

Thanks @pradghos for the simple fix. :)

**Pull request merged**
