### PR TITLE
[REVIEW] clarify documentation on boost dependency

### LINKED ISSUE #5794: [FEA] support linking Boost statically
**Is your feature request related to a problem? Please describe.**
The java library requires linking Boost statically (https://github.com/rapidsai/cudf/tree/branch-0.15/java#build-from-source). However, the current conda-based build environment doesn't actually support this. One needs to obtain `libboost_filesystem.a` separately.

**Describe the solution you'd like**
There are several options:
1. Ask the user to install Boost manually outside of conda, `sudo apt install libboost-all-dev`. This may be a very old version, depending on the OS.
1. Ask the user to download and build Boost. This seems like extra work.
1. Download and build Boost using CMake. This may increase the CMake running time, but it does make the build more self contained. However, with the shared library option, Boost still needs to be in the conda environment.
1. Replace the couple places we actually use Boost (really just `boost::filesystem::path` and `boost::filesystem::create_directories`) with our own code. Making this work cross platform is probably non-trivial.
1. Wait for CUDA 11 and C++17 and replace `boost::filesystem` with `std::filesystem`.

Looking at these options, maybe we can do 1 right now and 5 later?

**Additional context**
* Also see #2599
* Static libs were recently removed from the `conda-cpp` conda package (https://github.com/conda-forge/boost-cpp-feedstock/pull/76).

### PR DESCRIPTION
**Pull request by rongou**
Fixes #5794 

@kkraus14 @revans2 @jlowe

### CODE REVIEW

**Comment by GPUtester** [comment]
Please update the changelog in order to start CI tests.

View the gpuCI docs [here](https://docs.rapids.ai/gpuci#open-pr-or-update-pr).

**Comment by abellina** [comment]
Should we remove `boost-dev` from the conda environments? I am getting linking errors because I think parts of boost are coming from conda, and parts are coming from the apt installed version.

**Comment by kkraus14** [comment]
> Should we remove `boost-dev` from the conda environments? I am getting linking errors because I think parts of boost are coming from conda, and parts are coming from the apt installed version. @rongou @kkraus14

Can you open an new issue? We definitely still depend on boost and should get it from conda for our default build, but give an option to statically link / build boost ourselves in the future.

**Comment by abellina** [comment]
ok let me figure out _what_ is going on, then will file something. Maybe it is as simple of: if you do the system version, then just don't include in conda (for the instructions), you'd think that 1 version would be picked by the FindBoost cmake util.

**Comment by rongou** [comment]
For the JNI build, you should pass in `-DBoost_USE_STATIC_LIBS=ON`. The `boost-cpp` conda package doesn't include static libs.

**Pull request merged**
