### PR TITLE
Update JNI java CSV APIs to not use deprecated API

### LINKED ISSUE #9062: [FEA] Add Java bindings for CSV reading with `data_type` schema
**Is your feature request related to a problem? Please describe.**
#8240 is removing the ability to specify data types for CSV reading as strings.  Currently the Java bindings for CSV reading only support passing strings for the data types.

**Describe the solution you'd like**
The Java bindings should add a `Table.readCSV` method that takes the data schema to read as an array of `DType` rather than strings.

### PR DESCRIPTION
**Pull request by revans2**
This fixes #9062

### CODE REVIEW

**Review by jlowe — APPROVED** [review]
I marked this as a breaking change since it removes `DType#getSimpleName`.

**Comment by revans2** [comment]
> I marked this as a breaking change since it removes `DType#getSimpleName`.

Good catch. That API was never supposed to be public, but I guess I missed it when it when it.

**Comment by revans2** [comment]
Build failure looks like it is related to AST changes in https://github.com/rapidsai/cudf/pull/9045. I'll try to upmerge and see what happens.

**Comment by revans2** [comment]
@gpucibot merge

**Pull request merged**
