### PR TITLE
Add trailing comma support for nested JSON reader

### PR DESCRIPTION
**Pull request by karthikeyann**
## Description
Adds trailing comma support for nested JSON reader.
Now the nested reader can ignore trailing `,` comma before `]` and `}` on list and struct respectively.

## Checklist
- [x] I am familiar with the [Contributing Guidelines](https://github.com/rapidsai/cudf/blob/HEAD/CONTRIBUTING.md).
- [x] New or existing tests cover these changes.
- [x] The documentation is up to date with these changes.

### CODE REVIEW

**Comment by elstehle** [comment]
Should we add a test or two to make sure the behaviour keeps working as expected?

**Comment by karthikeyann** [comment]
Added - pass, fail unit test cases.

**Review by elstehle — APPROVED** [review]

**Review by PointKernel — APPROVED** [review]

**Comment by karthikeyann** [comment]
@gpucibot merge

**Pull request merged**
