### PR TITLE
Use as_column instead of full

### PR DESCRIPTION
**Pull request by mroeschke**
## Description

Similar to https://github.com/rapidsai/cudf/pull/14689, ensures there's 1 entrypoint to create a column from a scalar.

This builds on https://github.com/rapidsai/cudf/pull/14620

## Checklist
- [ ] I am familiar with the [Contributing Guidelines](https://github.com/rapidsai/cudf/blob/HEAD/CONTRIBUTING.md).
- [ ] New or existing tests cover these changes.
- [ ] The documentation is up to date with these changes.

### CODE REVIEW

**Review by rjzamora — APPROVED** [review]
Change looks fine for dask-cudf

**Review by vyasr — APPROVED** [review]
@mroeschke can you verify that `full` isn't used by cuspatial? Otherwise this LGTM pending resolution of the upstream nvcomp issues. Feel free to merge when those are resolved and CI is passing.

**Comment by mroeschke** [comment]
Thanks for the reminder. Opened up a PR on the cuspatial side https://github.com/rapidsai/cuspatial/pull/1350

**Pull request merged**
