### PR TITLE
Fix ORC writer on the alignment of Map column meta 

### LINKED ISSUE #9781: [BUG] ORC writer doesn't align column meta with column for Map type
**Describe the bug**
Currently, when building orc_table_view, ORC writer doesn't arrange correct column_metadata for columns of `TypeKind::MAP`: [code link](https://github.com/rapidsai/cudf/blob/branch-22.02/cpp/src/io/orc/writer_impl.cu#L1506).
If I am not wrong, in terms of column meta, we also need to unwrap the list layer before unwrapping the struct of map key and map value. Just like what Parquet writer does: [code link](https://github.com/rapidsai/cudf/blob/branch-22.02/cpp/src/io/parquet/writer_impl.cu#L497).

I found this bug with the Spark-level tests. When reading ORC file written by cuDF ORC writer, Spark failed to parse the decimal precision from the metadata, if the decimal columns are the children of MapType.

### PR DESCRIPTION
**Pull request by sperlingxx**
Fixes #9781

Current PR is to fix the problem of the alignment of Map column meta in ORC writer, to make it working like [Parquet writer](https://github.com/rapidsai/cudf/blob/branch-22.02/cpp/src/io/parquet/writer_impl.cu#L497).

### CODE REVIEW

**Review by ttnghia — APPROVED** [review]

**Review by vuule — APPROVED** [review]
Looks good, thank you for the patch!

**Comment by vuule** [comment]
Forgot one thing - could you add a cudf test?

**Review by mythrocks — APPROVED** [review]
The change makes sense. It is now in line with the comment for `MAP`, which indicates that the `LIST` `child` column is to be serialized, not the `LIST` itself.

Would it be viable to add a test to repro the failure?

**Review by devavret — APPROVED** [review]

**Comment by sperlingxx** [comment]
Hi @mythrocks @vuule, I couldn't find a simple way to add the test, since `cudf::reader` doesn't fetch the real field names of map children from ORC: https://github.com/rapidsai/cudf/blob/branch-22.02/cpp/src/io/orc/orc.cpp#L481.

**Comment by ttnghia** [comment]
Rerun tests.

**Comment by vuule** [comment]
https://github.com/rapidsai/cudf/pull/9852 adds the test for this fix.

**Pull request merged**
