### PR TITLE
Allow anonymous user in devcontainer name.

### PR DESCRIPTION
**Pull request by bdice**
## Description
In https://github.com/rapidsai/cudf/pull/15572, we updated the devcontainer name to include the current user's name. However, in GitHub Codespaces, the username is not defined. As a result, the container name starts with a dash. This is not allowed by GitHub Codespaces, so it fails to launch.

This PR adds a default value of `anon` to the devcontainer username.

## Checklist
- [x] I am familiar with the [Contributing Guidelines](https://github.com/rapidsai/cudf/blob/HEAD/CONTRIBUTING.md).
- [x] New or existing tests cover these changes.
- [x] The documentation is up to date with these changes.

### CODE REVIEW

**Review by jameslamb — APPROVED** [review]
Makes sense to me, thanks!

**Comment by vyasr** [comment]
Can we rapids-reviser this (or at least create an issue)? I assume it affects all RAPIDS repos.

**Review by trxcllnt — APPROVED** [review]

**Comment by bdice** [comment]
> Can we rapids-reviser this (or at least create an issue)? I assume it affects all RAPIDS repos.

I applied this fix across repos. The new PRs link to this one.
- https://github.com/rapidsai/cugraph-ops/pull/654
- https://github.com/rapidsai/cuspatial/pull/1396
- https://github.com/rapidsai/raft/pull/2355
- https://github.com/rapidsai/rmm/pull/1576

**Comment by vyasr** [comment]
> > Can we rapids-reviser this (or at least create an issue)? I assume it affects all RAPIDS repos.
> 
> I applied this fix across repos. The new PRs link to this one.
> 
>     * [Allow anonymous user in devcontainer name cugraph-ops#654](https://github.com/rapidsai/cugraph-ops/pull/654)
> 
>     * [Allow anonymous user in devcontainer name cuspatial#1396](https://github.com/rapidsai/cuspatial/pull/1396)
> 
>     * [Allow anonymous user in devcontainer name raft#2355](https://github.com/rapidsai/raft/pull/2355)
> 
>     * [Allow anonymous user in devcontainer name rmm#1576](https://github.com/rapidsai/rmm/pull/1576)

Thanks!

**Pull request merged**
