### PR TITLE
Fix host buffer access from device function in the Parquet reader

### PR DESCRIPTION
**Pull request by vuule**
## Description
Closes https://github.com/rapidsai/cudf/issues/14311
The host access becomes an issue when pageable memory is used for host side of `hostdevice_vector`.
This PR fixes the device lambda to use the device pointer instead.

## Checklist
- [x] I am familiar with the [Contributing Guidelines](https://github.com/rapidsai/cudf/blob/HEAD/CONTRIBUTING.md).
- [x] New or existing tests cover these changes.
- [x] The documentation is up to date with these changes.

### CODE REVIEW

**Review by shrshi — COMMENTED** [review]
Looks good to me, thank you!

**Review by shrshi — APPROVED** [review]

**Review by vyasr — APPROVED** [review]

**Review by ttnghia — APPROVED** [review]
Is there any test for the related function? If yes, how this didn't crash the test?

**Comment by vuule** [comment]
> Is there any test for the related function? If yes, how this didn't crash the test?

The use of pinned memory was hiding the issue. When using pageable memory in `hostdevice_vector`s, all of the Parquet reader tests crash.

**Comment by ttnghia** [comment]
> The use of pinned memory was hiding the issue. When using pageable memory in `hostdevice_vector`s, all of the Parquet reader tests crash.

Then can we have a test with both pinned memory/pageable memory?

**Comment by vuule** [comment]
> > The use of pinned memory was hiding the issue. When using pageable memory in `hostdevice_vector`s, all of the Parquet reader tests crash.
> 
> Then can we have a test with both pinned memory/pageable memory? Such as through macro definition or toggling the corresponding env variable?

I've started working on the test and realized some problems. The env var is read only once and cached. We can't enable pageable memory use for only one test.
We would also need separate tests for each format.
I don't think we should be adding tests for this at this time. Maybe if/when the option gets some use.

**Comment by vuule** [comment]
Merged to enable spark experiments; we can add tests in a separate PR.

**Pull request merged**
