### PR TITLE
Switch `pytest-xdist` algo to `worksteal`

### PR DESCRIPTION
**Pull request by galipremsagar**
## Description
This PR switches `pytest-xdist` distribution algorithm to a much more efficient algorithm `worksteal`, that will assign any idle pytest worker to pickup remaining pytests.

I see a 25% time savings when this switch is made locally:
```
`loadscope`:
== 101421 passed, 2115 skipped, 867 xfailed in 1179.48s (0:19:39) ==
`worksteal`:
== 101423 passed, 2115 skipped, 867 xfailed in 891.79s (0:14:51) ==
```
## Checklist
- [x] I am familiar with the [Contributing Guidelines](https://github.com/rapidsai/cudf/blob/HEAD/CONTRIBUTING.md).
- [x] New or existing tests cover these changes.
- [x] The documentation is up to date with these changes.

### CODE REVIEW

**Review by bdice — APPROVED** [review]
Nice! This is a new feature in pytest-xdist 3.2.0, from about a year ago (after I had last investigated the options for `--dist`). https://pytest-xdist.readthedocs.io/en/latest/changelog.html#pytest-xdist-3-2-0-2023-02-07

I vaguely recall there _might_ have been some issues caused by other `--dist` options in the past. 🤔 I tried to see if I could find a past issue/PR about this but didn't see one.

**Comment by galipremsagar** [comment]
> Nice! This is a new feature in pytest-xdist 3.2.0, from about a year ago (after I had last investigated the options for `--dist`). https://pytest-xdist.readthedocs.io/en/latest/changelog.html#pytest-xdist-3-2-0-2023-02-07
> 
> I vaguely recall there _might_ have been some issues caused by other `--dist` options in the past. 🤔 I tried to see if I could find a past issue/PR about this but didn't see one.

Yes, `loadscope` was the best distribution I found more than a year ago. While going through `pytest-xdist` docs today, I found this algorithm which was perfect for our setup.

**Comment by bdice** [comment]
@galipremsagar For awareness, I have prepared a series of PRs (locally) that will apply the `worksteal` strategy across RAPIDS repos that support `pytest-xdist`. I will open those PRs after this one is merged.

**Review by raydouglass — APPROVED** [review]

**Comment by galipremsagar** [comment]
> @galipremsagar For awareness, I have prepared a series of PRs (locally) that will apply the `worksteal` strategy across RAPIDS repos that support `pytest-xdist`. I will open those PRs after this one is merged.

Thanks @bdice ! For reference here are the time savings:
`branch-24.04`:
```
======== 101174 passed, 2091 skipped, 1136 xfailed in 853.34s (0:14:13) ========
```

This PR:
```
======== 101424 passed, 2115 skipped, 869 xfailed in 689.92s (0:11:29) =========
```

An entire job that took [27 mins](https://github.com/rapidsai/cudf/actions/runs/7994625400/job/21835843808) now takes just [17 mins](https://github.com/rapidsai/cudf/actions/runs/8142069791/job/22252789883?pr=15207)! - **10mins** time reduction.

**Comment by vyasr** [comment]
That's an amazing speedup @galipremsagar!

@bdice when you make your PRs, can you also double-check and align the parallelism across wheel/conda builds? For example, [cuml wheel tests](https://github.com/rapidsai/cuml/blob/branch-24.04/ci/test_wheel.sh#L22) are currently using `-n 4` while [conda tests](https://github.com/rapidsai/cuml/blob/branch-24.04/ci/test_python_singlegpu.sh#L16) use `-n 8`. Adjusting those can also save us time.

There are larger improvements we could make to unify the testing logic more generally, but for now I'm just focusing on the quick wins!

**Comment by bdice** [comment]
Follow-up PRs across RAPIDS:
- [ ] https://github.com/rapidsai/cuspatial/pull/1355
- [ ] https://github.com/rapidsai/cugraph-ops/pull/609
- [ ] https://github.com/rapidsai/cucim/pull/708
- [ ] https://github.com/rapidsai/cuml/pull/5792
- [ ] https://github.com/rapidsai/cuxfilter/pull/576
- [ ] https://github.com/rapidsai/cudf-pandas-integration/pull/100

I'll work on the manual changes needed for each of these and prepare them for review.

**Pull request merged**
