### PR TITLE
[REVIEW] Allow concatenating columns with null columns

### LINKED ISSUE #1723: [BUG] Concat string columns with Nulls
**Describe the bug**
There is an issue where an error is thrown when there's a concat of dataframes that have columns which are defined as string dtype, but expected to have all null values.

**Steps/Code to reproduce bug**
To reproduce (in Jupyter). Here the csv records are split and later combined using concat, similar to the notebook referenced below.
```
!echo "col1,col2,col3,col4\n1,string1,,string2\n2,,string3,string4" > sample-1.csv
def fcn_filter(df, ids):
    out_dfs = []
    for i in ids:
        df['present'] = df['col1'].str.contains(i)
        temp_df = df[df.present == True]
        out_dfs.append(temp_df)
    
    out_df = cudf.multi.concat(out_dfs)
    return out_df

sample_df = dask_cudf.read_csv("sample-1.csv",
                               names=["col1","col2","col3","col4"],
                               delimiter=",",
                               usecols=["col1","col2","col3","col4"],
                               dtype=['str','str','str','str'],
                               skip_blank_lines=True,
                              )

output_df = sample_df.map_partitions(fcn_filter, ["1","2"])
final_gdf = output_df.compute()
```
Error Output:
```
KeyErrorTraceback (most recent call last)
<ipython-input-30-4eacfc6bdc4b> in <module>
      1 tdf = sample_df.map_partitions(fcn_filter, ["1","2"])
----> 2 final_gdf = tdf.compute()

/conda/envs/rapids/lib/python3.6/site-packages/dask/base.py in compute(self, **kwargs)
    154         dask.base.compute
    155         """
--> 156         (result,) = compute(self, traverse=False, **kwargs)
    157         return result
    158 

/conda/envs/rapids/lib/python3.6/site-packages/dask/base.py in compute(*args, **kwargs)
    396     keys = [x.__dask_keys__() for x in collections]
    397     postcomputes = [x.__dask_postcompute__() for x in collections]
--> 398     results = schedule(dsk, keys, **kwargs)
    399     return repack([f(r, *a) for r, (f, a) in zip(results, postcomputes)])
    400 

/conda/envs/rapids/lib/python3.6/site-packages/dask/local.py in get_sync(dsk, keys, **kwargs)
    501     """
    502     kwargs.pop('num_workers', None)    # if num_workers present, remove it
--> 503     return get_async(apply_sync, 1, dsk, keys, **kwargs)
    504 
    505 

/conda/envs/rapids/lib/python3.6/site-packages/dask/local.py in get_async(apply_async, num_workers, dsk, result, cache, get_id, rerun_exceptions_locally, pack_exception, raise_exception, callbacks, dumps, loads, **kwargs)
    447             # Seed initial tasks into the thread pool
    448             while state['ready'] and len(state['running']) < num_workers:
--> 449                 fire_task()
    450 
    451             # Main loop, wait on tasks to finish, insert new ones

/conda/envs/rapids/lib/python3.6/site-packages/dask/local.py in fire_task()
    443                             args=(key, dumps((dsk[key], data)),
    444                                   dumps, loads, get_id, pack_exception),
--> 445                             callback=queue.put)
    446 
    447             # Seed initial tasks into the thread pool

/conda/envs/rapids/lib/python3.6/site-packages/dask/local.py in apply_sync(func, args, kwds, callback)
    490 def apply_sync(func, args=(), kwds={}, callback=None):
    491     """ A naive synchronous version of apply_async """
--> 492     res = func(*args, **kwds)
    493     if callback is not None:
    494         callback(res)

/conda/envs/rapids/lib/python3.6/site-packages/dask/local.py in execute_task(key, task_info, dumps, loads, get_id, pack_exception)
    233         failed = False
    234     except BaseException as e:
--> 235         result = pack_exception(e, dumps)
    236         failed = True
    237     return key, result, failed

/conda/envs/rapids/lib/python3.6/site-packages/dask/local.py in execute_task(key, task_info, dumps, loads, get_id, pack_exception)
    228     try:
    229         task, data = loads(task_info)
--> 230         result = _execute_task(task, data)
    231         id = get_id()
    232         result = dumps((result, id))

/conda/envs/rapids/lib/python3.6/site-packages/dask/core.py in _execute_task(arg, cache, dsk)
    117         func, args = arg[0], arg[1:]
    118         args2 = [_execute_task(a, cache) for a in args]
--> 119         return func(*args2)
    120     elif not ishashable(arg):
    121         return arg

/conda/envs/rapids/lib/python3.6/site-packages/dask/optimization.py in __call__(self, *args)
    940                              % (len(self.inkeys), len(args)))
    941         return core.get(self.dsk, self.outkey,
--> 942                         dict(zip(self.inkeys, args)))
    943 
    944     def __reduce__(self):

/conda/envs/rapids/lib/python3.6/site-packages/dask/core.py in get(dsk, out, cache)
    147     for key in toposort(dsk):
    148         task = dsk[key]
--> 149         result = _execute_task(task, cache)
    150         cache[key] = result
    151     result = _execute_task(out, cache)

/conda/envs/rapids/lib/python3.6/site-packages/dask/core.py in _execute_task(arg, cache, dsk)
    117         func, args = arg[0], arg[1:]
    118         args2 = [_execute_task(a, cache) for a in args]
--> 119         return func(*args2)
    120     elif not ishashable(arg):
    121         return arg

/conda/envs/rapids/lib/python3.6/site-packages/dask/compatibility.py in apply(func, args, kwargs)
     91     def apply(func, args, kwargs=None):
     92         if kwargs:
---> 93             return func(*args, **kwargs)
     94         else:
     95             return func(*args)

/conda/envs/rapids/lib/python3.6/site-packages/dask/dataframe/core.py in apply_and_enforce(*args, **kwargs)
   3877     func = kwargs.pop('_func')
   3878     meta = kwargs.pop('_meta')
-> 3879     df = func(*args, **kwargs)
   3880     if is_dataframe_like(df) or is_series_like(df) or is_index_like(df):
   3881         if not len(df):

<ipython-input-28-7b3a69822d98> in fcn_filter(df, ids)
      6         out_dfs.append(temp_df)
      7 
----> 8     out_df = cudf.multi.concat(out_dfs)
      9     return out_df

/conda/envs/rapids/lib/python3.6/site-packages/cudf/multi.py in concat(objs, axis, ignore_index)
     50 
     51     if typ is DataFrame:
---> 52         return DataFrame._concat(objs, axis=axis, ignore_index=ignore_index)
     53     elif typ is Series:
     54         return Series._concat(objs, axis=axis)

/conda/envs/rapids/lib/python3.6/site-packages/cudf/dataframe/dataframe.py in _concat(cls, objs, axis, ignore_index)
   1049             index = Index._concat([o.index for o in objs])
   1050         data = [(c, Series._concat([o[c] for o in objs], index=index))
-> 1051                 for c in objs[0].columns]
   1052         out = cls(data)
   1053         out._index = index

/conda/envs/rapids/lib/python3.6/site-packages/cudf/dataframe/dataframe.py in <listcomp>(.0)
   1049             index = Index._concat([o.index for o in objs])
   1050         data = [(c, Series._concat([o[c] for o in objs], index=index))
-> 1051                 for c in objs[0].columns]
   1052         out = cls(data)
   1053         out._index = index

/conda/envs/rapids/lib/python3.6/site-packages/cudf/dataframe/series.py in _concat(cls, objs, axis, index)
    619         else:
    620             name = None
--> 621         col = Column._concat([o._column for o in objs])
    622         return cls(data=col, index=index, name=name)
    623 

/conda/envs/rapids/lib/python3.6/site-packages/cudf/dataframe/column.py in _concat(cls, objs, dtype)
     76         head = objs[0]
     77         for o in objs:
---> 78             if not o.is_type_equivalent(head):
     79                 raise ValueError("All series must be of same type")
     80         # Filter out inputs that have 0 length

/conda/envs/rapids/lib/python3.6/site-packages/cudf/dataframe/columnops.py in is_type_equivalent(self, other)
     55                 del dct[k]
     56 
---> 57         remove_base(mine)
     58         remove_base(theirs)
     59 

/conda/envs/rapids/lib/python3.6/site-packages/cudf/dataframe/columnops.py in remove_base(dct)
     53             basekeys = Column._replace_defaults(self).keys()
     54             for k in basekeys:
---> 55                 del dct[k]
     56 
     57         remove_base(mine)

KeyError: 'mask'
```
For reference, the issue was originally found while running this notebook: https://github.com/rapidsai/notebooks-extended/tree/master/advanced/blog_notebooks/cyber/network_mapping

**Expected behavior**
No error is thrown

**Environment details (please complete the following information):**
For my environment I am using docker and have used the notebooks-extended Docker file here:
https://github.com/rapidsai/notebooks-extended/blob/master/Dockerfile
Although made some modification to temporarily exclude Line 12
 

**Additional context**
https://github.com/rapidsai/dask-cudf/issues/252#issuecomment-491969839

Thank you!

### PR DESCRIPTION
**Pull request by shwina**
Concatenating nulls to a column currently fails because a column of nulls in cuDF can have any dtype. This PR enables the concatenation of nulls of any dtype to a column.

Fixes #1723

### CODE REVIEW

**Comment by shwina** [comment]
Run tests

**Comment by shwina** [comment]
The failing test passes consistently on my environment. I'm running a different (0.24.2) version of Pandas though. Any suggestion @kkraus14?

**Comment by thomcom** [comment]
Last I heard CI was on Pandas 0.23.4. It has bitten me before.

**Comment by shwina** [comment]
Seems to be unrelated to Pandas version too..

```shell
ashwint@dgx13 ~/w/c/python> python -c 'import pandas; print(pandas.__version__)'                                                                                             (cudf_dev) 
0.23.4
ashwint@dgx13 ~/w/c/python> pytest cudf/tests/test_multi.py -k test_concat_all_nulls                                                                                         (cudf_dev) 
================================================================================= test session starts ==================================================================================
platform linux -- Python 3.7.3, pytest-4.5.0, py-1.8.0, pluggy-0.11.0
rootdir: /home/nfs/ashwint/workspace/cudf/python
collected 14 items / 11 deselected / 3 selected                                                                                                                                        

cudf/tests/test_multi.py ...                                                                                                                                                     [100%]

=================================================================================== warnings summary ===================================================================================
/home/nfs/ashwint/miniconda3/envs/cudf_dev/lib/python3.7/site-packages/_pytest/cacheprovider.py:133
  /home/nfs/ashwint/miniconda3/envs/cudf_dev/lib/python3.7/site-packages/_pytest/cacheprovider.py:133: PytestCacheWarning: cache could not write path /home/nfs/ashwint/workspace/cudf/p
ython/.pytest_cache/v/cache/stepwise                                                                                                                                                   
    self.warn("cache could not write path {path}", path=path)

/home/nfs/ashwint/miniconda3/envs/cudf_dev/lib/python3.7/site-packages/_pytest/cacheprovider.py:133
  /home/nfs/ashwint/miniconda3/envs/cudf_dev/lib/python3.7/site-packages/_pytest/cacheprovider.py:133: PytestCacheWarning: cache could not write path /home/nfs/ashwint/workspace/cudf/p
ython/.pytest_cache/v/cache/nodeids                                                                                                                                                    
    self.warn("cache could not write path {path}", path=path)

-- Docs: https://docs.pytest.org/en/latest/warnings.html
================================================================= 3 passed, 11 deselected, 2 warnings in 0.52 seconds ==================================================================


```

**Comment by shwina** [comment]
Attempting to debug with local CI now

**Comment by shwina** [comment]
Tests seem to pass with local CI as well 😕

**Comment by shwina** [comment]
run tests

**Comment by kkraus14** [comment]
rerun tests

**Comment by shwina** [comment]
@kkraus14 Marking this ready to merge but please have a quick look before merging

**Comment by shwina** [comment]
rerun tests

**Pull request merged**
