### PR TITLE
Remove repetition of install instructions [skip ci]

### PR DESCRIPTION
**Pull request by eyal0**
The instruction provided and the alternate are identical.

### CODE REVIEW

**Comment by GPUtester** [comment]
Can one of the admins verify this patch?

**Comment by GPUtester** [comment]
Can one of the admins verify this patch?

**Comment by harrism** [comment]
Thanks for the fix @eyal0 

CI: ok to test

**Comment by GPUtester** [comment]
Please update the changelog in order to start CI tests.

View the gpuCI docs [here](https://docs.rapids.ai/gpuci#open-pr-or-update-pr).

**Comment by harrism** [comment]
@eyal0 you will need to add a line to CHANGELOG.md for this PR in order for our CI to accept it. See above. Thanks!

**Pull request merged**
