### PR TITLE
[REVIEW] Add CODEOWNERS

### PR DESCRIPTION
**Pull request by mike-wendt**
Work with cuDF team to setup the correct permissions for the repo before merging

The current suggestion is for the following people to be explicitly in the `CODEOWNERS` file:
- @jrhemstad 
- @harrism
- @kkraus14
- @thomcom
- @mjsamoht
- (devops team for CI/conda changes)

The first commit is only an example file where we can use that as a base to customize certain folders and file types are owned by some or all of those above.

Let's discuss and iterate here on how we would like to breakdown the permissions and to what level.

### CODE REVIEW

**Comment by jrhemstad** [comment]
Here's my initial thoughts:

`cudf/` owners:
- devops team

DevOps should be able to approve/merge a PR touching any files if necessary.

`cpp/` owners:
- @harrism
- @jrhemstad
- @mjsamoht

C++ devs are responsible for approving anything touching code in the `cpp/` directory

`python/` owners:
- @thomcom
- @kkraus14

Python devs are responsible for approving anything touching code in the `python/` directory

**Comment by mjsamoht** [comment]
Will GitHub be able to enforce this new policy?  Or is this just an agreement among owners that they're expected to follow?

Also, how do we handle PRs that touch files both in cpp and python?  I don't believe GitHub can enforce two separate approvals before allowing merging.

**Comment by jrhemstad** [comment]
> Will GitHub be able to enforce this new policy? Or is this just an agreement among owners that they're expected to follow?
> 
> Also, how do we handle PRs that touch files both in cpp and python? I don't believe GitHub can enforce two separate approvals before allowing merging.

GitHub does enforce this. 

See
https://help.github.com/en/articles/about-code-owners
https://help.github.com/en/articles/enabling-required-reviews-for-pull-requests

**Comment by kkraus14** [comment]
> Here's my initial thoughts:
> 
> `cudf/` owners:
> 
> * devops team
> 
> DevOps should be able to approve/merge a PR touching any files if necessary.
> 
> `cudf/cpp/` owners:
> 
> * @harrism
> * @jrhemstad
> * @mjsamoht
> 
> C++ devs are responsible for approving anything touching code in the `cpp/` directory
> 
> `cudf/python/` owners:
> 
> * @thomcom
> * @kkraus14
> 
> Python devs are responsible for approving anything touching code in the `python/` directory

This sounds great! I think we should consider creating groups and tying things to groups so that users can be added / removed from groups more easily.

I'd add myself as a codeowner to `cudf/cpp/cmake`, `cudf/ci`, and `cudf/conda` as well.

**Comment by jrhemstad** [comment]
> This sounds great! I think we should consider creating groups and tying things to groups so that users can be added / removed from groups more easily.

I like the groups idea. Something like `cppmaintainers`, `pythonmaintainers`, `buildmaintainers`, etc. 

> I'd add myself as a codeowner to `cudf/cpp/cmake`, `cudf/ci`, and `cudf/conda` as well.

**Comment by harrism** [comment]
Definitely should be groups. I don't think we should have individual's names in the codeowners file.  

Shouldn't all the PICs (me, Keith, Thomas, Mike Wendt) be listed under `/cudf owners` though? Sometimes we need to review and merge PRs that cross boundaries. PICs should be considered responsible enough to have that power and not abuse it.

**Comment by raydouglass** [comment]
I've updated the code owners file and created groups with the people mentioned.
You can checkout out the groups (they are subteams on the left) here: https://github.com/orgs/rapidsai/teams/cudf-write

**Comment by mike-wendt** [comment]
@raydouglass @kkraus14 before I do a CL, should we explicitly call out the `ci` folder? that way someone from @rapidsai/ops can give a 👍/ 👎 before code there is committed

or is that too much of a blocker?

**Comment by kkraus14** [comment]
> @raydouglass @kkraus14 before I do a CL, should we explicitly call out the `ci` folder? that way someone from @rapidsai/ops can give a 👍/ 👎 before code there is committed
> 
> or is that too much of a blocker?

I think that would often become noise for the ops team. That folder is most commonly changed when we need to add a dependency to the gpu script for testing purposes and I don't think it needs more than a normal review from developers.

**Comment by mike-wendt** [comment]
> I think that would often become noise for the ops team. That folder is most commonly changed when we need to add a dependency to the gpu script for testing purposes and I don't think it needs more than a normal review from developers.

works for me and if we ever need to update it we can in the future, I'll merge shortly

**Pull request merged**
