### PR TITLE
find and replace

### PR DESCRIPTION
**Pull request by razajafri**
Adds the ability to find and replace all values in a Column Vector 

From java docs:
    Returns a vector with all values "oldValues[i]" replaced with "newValues[i]".
    Warning:
       Currently this function doesn't work for Strings or StringCategories.
       NaNs can't be replaced in the original vector but regular values can be replaced with NaNs
       Nulls can't be replaced in the original vector but regular values can be replaced with Nulls
       Mixing of types isn't allowed, the resulting vector will be the same type as the original.
         e.g. You can't replace an integer vector with values from a long vector
   
    Usage:
       this = {1, 4, 5, 1, 5}
       oldValues = {1, 5, 7}
       newValues = {2, 6, 9}
   
       result = this.findAndReplaceAll(oldValues, newValues);
       result = {2, 4, 6, 2, 6}  (1 and 5 replaced with 2 and 6 but 7 wasn't found so no change)

### CODE REVIEW

**Comment by abellina** [comment]
rerun tests

**Comment by abellina** [comment]
@razajafri what happens if the two columns passed to find and replace all are not the same size? Should the java side check these in java-land and throw an `IllegalArgumentException`?

**Comment by razajafri** [comment]
> @razajafri what happens if the two columns passed to find and replace all are not the same size? Should the java side check these in java-land and throw an `IllegalArgumentException`?

do you mean the oldValues and newValues? It will throw a CudfException 
https://github.com/rapidsai/cudf/blob/5e51f02ef6891a842a1ddc84548a7fc70f8ca887/cpp/src/replace/replace.cu#L283

**Comment by razajafri** [comment]
rerun tests

**Pull request merged**
