### PR TITLE
[REVIEW] Adding feature `Series.histogram`

### LINKED ISSUE #1061: [FEA] Binning/Histograms
In exploration of data, histogramming with a fixed bin size can be useful when trying to understand distribution and especially skew.  I would like to be able to generate a histogram on a column/series of a dataframe.  While `value_counts` exists, it doesn't expose an option to set the number of bins.  Providing both an option to value_counts and a new method, `hist` would be valuable.

cc @thomcom

### PR DESCRIPTION
**Pull request by rgsl888prabhu**
Adds support for feature `Series.histogram` and test cases to validate. Supports all types apart from `string`.

closes #1061

### CODE REVIEW

**Comment by GPUtester** [comment]
Please update the changelog in order to start CI tests.

View the gpuCI docs [here](https://docs.rapids.ai/gpuci#open-pr-or-update-pr).

**Comment by rgsl888prabhu** [comment]
> We shouldn't introduce a new `histogram` API here.
> 
> This should likely go underneath the `cut`: https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.cut.html and/or `value_counts`: https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.value_counts.html functions.

`pandas.cut` is quite different, it returns Series with bins replacing the corresponding value as shown below. This can't be mimicked with cudf and cupy.histogram.
```
>>> pd.cut(pd.Series([1, 2, 3, 4, 5, 6]), bins=3)
0    (0.995, 2.667]
1    (0.995, 2.667]
2    (2.667, 4.333]
3    (2.667, 4.333]
4      (4.333, 6.0]
5      (4.333, 6.0]
dtype: category
Categories (3, interval[float64]): [(0.995, 2.667] < (2.667, 4.333] < (4.333, 6.0]]
```

**Comment by jakirkham** [comment]
If we stick with this approach, would suggest changing the `ValueError`s here to `TypeError`s since they seem to be about the type of the `Series` and not particular values that are off.

**Comment by rgsl888prabhu** [comment]
> We shouldn't introduce a new `histogram` API here.
> 
> This should likely go underneath the `cut`: https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.cut.html and/or `value_counts`: https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.value_counts.html functions.

And in case of `value_counts`, index will be of type `interval`, I was thinking to use string type index providing bin edges. But this could be time consuming as it needs to be created on host side.

**Comment by kkraus14** [comment]
Given we don't support Intervals yet, I'm not sure how we can properly support this. Should we just put this on hold until we support Intervals?

**Comment by rgsl888prabhu** [comment]
> Given we don't support Intervals yet, I'm not sure how we can properly support this. Should we just put this on hold until we support Intervals?

Currently we can return string index, but it wouldn't help if the downstream requirement is interval index.

**Comment by kkraus14** [comment]
> > Given we don't support Intervals yet, I'm not sure how we can properly support this. Should we just put this on hold until we support Intervals?
> 
> Currently we can return string index, but it wouldn't help if the downstream requirement is interval index.

Yea, returning a StringIndex in this situation doesn't really make sense from my perspective. Sounds like we should add an issue for IntervalDtype / IntervalIndex support.

**Comment by rgsl888prabhu** [comment]
> IntervalDtype / IntervalIndex

Created a `Feature/Discussion` issue https://github.com/rapidsai/cudf/issues/5376. Feel free to update to make it better.

**Comment by kkraus14** [comment]
@rgsl888prabhu I'm going to close this for now since it's blocked on `IntervalType`. We can reopen in the future if it makes sense to do so.

**Pull request closed without merging**
