### PR TITLE
Fix `cudf::hash_partition` for `decimal32` and `decimal64`

### PR DESCRIPTION
**Pull request by codereport**
This resolves https://github.com/rapidsai/cudf/issues/6996

### CODE REVIEW

**Comment by revans2** [comment]
I ran with this patch and it fixed the issues I was seeing in Spark.

**Comment by codereport** [comment]
> I ran with this patch and it fixed the issues I was seeing in Spark.

:+1:  I am just putting together another unit test for `cudf::partition` and then I will mark the PR as ready for review.

**Review by hyperbolic2346 — APPROVED** [review]
I wonder how much more of this is around. This is a subtle difference and easy to miss.

**Comment by codereport** [comment]
> I wonder how much more of this is around. This is a subtle difference and easy to miss.

The fix is subtle but the API (`cudf::hash_partition`) would completely break when used. Most APIs had `fixed_width` tests that the original `fixed_point` column support was able to piggy back on top of to test that it worked. However, for APIs like this one that didn't, it's possible that it is broken and then we will find out once it is used. 

It is on my list of things to do to go through every API at some point and make sure there are tests.

**Review by devavret — APPROVED** [review]

**Pull request merged**
