### PR TITLE
Fix Parquet decimal64 stats

### PR DESCRIPTION
**Pull request by etseidl**
## Description
In the Parquet writer, `decimal64` stats were being treated like `decimal128` (i.e. written in network byte order), when they should be treated like an `int64_t`. This PR fixes that and adds tests of `decimal32` and `decimal64` statistics.

## Checklist
- [x] I am familiar with the [Contributing Guidelines](https://github.com/rapidsai/cudf/blob/HEAD/CONTRIBUTING.md).
- [x] New or existing tests cover these changes.
- [x] The documentation is up to date with these changes.

### CODE REVIEW

**Review by davidwendt — APPROVED** [review]

**Review by mythrocks — APPROVED** [review]

**Comment by etseidl** [comment]
@vuule I just looked at this [comment](https://github.com/rapidsai/cudf/pull/13848/files#r1325110539). Could you take a look at this fix in that light? The problem is that decimal128 stats are to be written big endian, while decimal64 should be little endian. The current code will only write out the high 8 bytes of the `__int128_t`, so all decimal64 stats wind up being 0.

**Review by vuule — APPROVED** [review]
Thank you for fixing my mess :)

**Pull request merged**
