### PR TITLE
Fix unused variables and functions

### PR DESCRIPTION
**Pull request by karthikeyann**
## Description
Removed unused variables and functions.
Removed src/io/utilities/type_conversion.cpp/hpp
Rename some variables which are shadowed by other variables to avoid confusion.

## Checklist
- [x] I am familiar with the [Contributing Guidelines](https://github.com/rapidsai/cudf/blob/HEAD/CONTRIBUTING.md).
- [x] New or existing tests cover these changes.
- [x] The documentation is up to date with these changes.

### CODE REVIEW

**Review by ttnghia — APPROVED** [review]

**Comment by vuule** [comment]
I'm surprised some of these didn't trigger warning-as-error.
How did you catch these?

**Comment by karthikeyann** [comment]
> I'm surprised some of these didn't trigger warning-as-error. How did you catch these?

by running `cppcheck`.

**Review by vuule — APPROVED** [review]
nice!

**Review by bdice — APPROVED** [review]
@karthikeyann After these changes, is the code “clean” according to cppcheck or are there lots of false positives? Feel free to add a pre-commit hook if it’s relatively clean and not too slow to run. Search cppcheck here, there are several options: https://pre-commit.com/hooks.html

**Comment by vyasr** [comment]
Last I checked none of the available cppcheck hooks actually installed cppcheck, they required it to already be installed on the system (unlike the clang-format wheels that are available). It would be great if that had changed, though.

**Comment by karthikeyann** [comment]
@bdice cppcheck still has many false positives, especially in tests/ code. Not ready now. will check if more fixes and configuration can make it to add as a pre-commit hook. [clang-tidy](https://github.com/rapidsai/cudf/issues/584) is an option too.

@vyasr I installed cppcheck using conda. It's available in pypi https://pypi.org/project/cppcheck-codequality/. If it is pip installable, it can be a pre-commit hook right? (without the need for conda)

**Comment by bdice** [comment]
@vyasr Ah, right. I forgot that cppcheck itself is not pip-installable. Ignore my proposal. @karthikeyann That pip package seems like a utility for converting reports, not `cppcheck` itself.

**Pull request merged**
