### PR TITLE
[REVIEW] Fixes groupby performance issue

### LINKED ISSUE #3057: [BUG] Groupby performance regression
**Describe the bug**
Groupby performance has degraded and memory usage has increased in 0.10

**Steps/Code to reproduce bug**
```
# imports
import cudf
import numpy as np

# setup
df = cudf.DataFrame()
n_elem = 20_000_000
n_groups = n_elem // 100

for i in range(5):
    df[str(i)] = np.random.randint(0,n_groups,n_elem)
for i in range(5,7):
    df[str(i)] = np.random.random(n_elem)

# groupby
%%time
res = df.groupby([str(i) for i in range(5)], sort = True)['5','6'].sum()

Old Time: ~1.3s      Old peak memory: ~3GB
New Time: ~3.5s.   New Peak memory: ~4.5GB
```

With sort=False
```
%%time
res = df.groupby([str(i) for i in range(5)], sort = False)['5','6'].sum()

Old Time: ~250 ms
New Time: ~2s
```

Similar pattern for other aggs like `min/max` and grouping by fewer columns.

**Expected behavior**
Similar performance with the newer version. 

The git bisect path led me to 74b562c06751de441d4ee30460528c9fa6f7221d being the faulty commit which is a part of #2870 

**Environment overview (please complete the following information)**
Build from source dec6423a06ed25f6411236a5b3e6cf725434a800

### PR DESCRIPTION
**Pull request by rgsl888prabhu**
Taking care of series which will have same indices as the dataframe and skipping the join.

Old version groupby: 
`%time res = df.groupby([str(i) for i in range(5)], sort = True)['5','6'].sum()`
```
CPU times: user 465 ms, sys: 132 ms, total: 597 ms
Wall time: 597 ms
```
`%time res = df.groupby([str(i) for i in range(5)], sort = False)['5','6'].sum()`
```
CPU times: user 62.2 ms, sys: 24.8 ms, total: 86.9 ms
Wall time: 85.4 ms
```
New Version groupby:
`%time res = df.groupby([str(i) for i in range(5)], sort = True)['5','6'].sum()`
```
CPU times: user 353 ms, sys: 96.1 ms, total: 449 ms
Wall time: 449 ms
```
`%time res = df.groupby([str(i) for i in range(5)], sort = False)['5','6'].sum()`
```
CPU times: user 68.8 ms, sys: 20.2 ms, total: 89 ms
Wall time: 87.7 ms
```
My system spec:
2 Quadro RTX 8000
48 GB RAM
Intel(R) Xeon(R) Gold 6128 CPU @ 3.40GHz

close #3057

### CODE REVIEW

**Comment by rgsl888prabhu** [comment]
@AK-ayush I have validated the performance and looks good. Can you please try and let me know if you find the similar results with my branch?

**Comment by ayushdg** [comment]
I believe you meant to tag me 😄 . I'll build from your branch and let you know if the performance is as expected

**Comment by ayushdg** [comment]
Tested with the fix. Groupby performance is back to what is expected. Thanks @rgsl888prabhu! 😄

**Comment by rgsl888prabhu** [comment]
rerun tests

**Pull request merged**
