### PR TITLE
test is_valid before reading column data

### LINKED ISSUE #14310: [BUG] memcheck error reported in gpuEncodeDeltaBinaryPages in ParquetWriterDeltaTest/0.SupportedDeltaTestTypes
**Describe the bug**
Nightly memcheck runs reports a 1-byte read error when running `ParquetWriterDeltaTest/0.SupportedDeltaTestTypes` gtest in `PARQUET_TEST`
```
========= Invalid __global__ read of size 1 bytes
=========     at 0x124b0 in void cudf::io::parquet::detail::gpuEncodeDeltaBinaryPages<(int)128>(cudf::device_span<cudf::io::parquet::detail::EncPage, (unsigned long)18446744073709551615>, cudf::device_span<cudf::device_span<const unsigned char, (unsigned long)18446744073709551615>, (unsigned long)18446744073709551615>, cudf::device_span<cudf::device_span<unsigned char, (unsigned long)18446744073709551615>, (unsigned long)18446744073709551615>, cudf::device_span<cudf::io::compression_result, (unsigned long)18446744073709551615>)
=========     by thread (64,0,0) in block (0,0,0)
=========     Address 0x7f2491a04e40 is out of bounds
=========     and is 33 bytes after the nearest allocation at 0x7f2491a00000 of size 20,000 bytes
=========     Saved host backtrace up to driver entry point at kernel launch time
=========     Host Frame: [0x32e130]
=========                in /usr/lib/x86_64-linux-gnu/libcuda.so.1
=========     Host Frame: [0x1488c]
=========                in /conda/envs/rapids/lib/libcudart.so.11.0
=========     Host Frame:cudaLaunchKernel [0x6c318]
=========                in /conda/envs/rapids/lib/libcudart.so.11.0
=========     Host Frame:cudf::io::parquet::detail::EncodePages(cudf::device_span<cudf::io::parquet::detail::EncPage, 18446744073709551615ul>, bool, cudf::device_span<cudf::device_span<unsigned char const, 18446744073709551615ul>, 18446744073709551615ul>, cudf::device_span<cudf::device_span<unsigned char, 18446744073709551615ul>, 18446744073709551615ul>, cudf::device_span<cudf::io::compression_result, 18446744073709551615ul>, rmm::cuda_stream_view) [0x147fa6e]
=========                in /conda/envs/rapids/lib/libcudf.so
=========     Host Frame:cudf::io::parquet::detail::(anonymous namespace)::encode_pages(cudf::detail::hostdevice_2dvector<cudf::io::parquet::detail::EncColumnChunk>&, cudf::device_span<cudf::io::parquet::detail::EncPage, 18446744073709551615ul>, unsigned int, unsigned int, unsigned int, unsigned int, cudf::io::statistics_chunk const*, cudf::io::statistics_chunk const*, cudf::io::statistics_chunk const*, std::optional<cudf::io::writer_compression_statistics>&, cudf::io::parquet::detail::Compression, int, bool, rmm::cuda_stream_view) [0x14d7c6a]
=========                in /conda/envs/rapids/lib/libcudf.so
=========     Host Frame:cudf::io::parquet::detail::(anonymous namespace)::convert_table_to_parquet_data(cudf::io::table_input_metadata&, cudf::table_view const&, cudf::host_span<cudf::io::partition_info const, 18446744073709551615ul>, cudf::host_span<std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > const, 18446744073709551615ul>, std::unique_ptr<cudf::io::parquet::detail::aggregate_writer_metadata, std::default_delete<cudf::io::parquet::detail::aggregate_writer_metadata> > const&, std::optional<int>, unsigned long, unsigned long, int, int, int, cudf::io::statistics_freq, cudf::io::parquet::detail::Compression, bool, cudf::io::dictionary_policy, unsigned long, cudf::io::detail::single_write_mode, bool, bool, cudf::host_span<std::unique_ptr<cudf::io::data_sink, std::default_delete<cudf::io::data_sink> > const, 18446744073709551615ul>, rmm::cuda_stream_view) [0x14e13eb]
=========                in /conda/envs/rapids/lib/libcudf.so
=========     Host Frame:cudf::io::parquet::detail::writer::impl::write(cudf::table_view const&, std::vector<cudf::io::partition_info, std::allocator<cudf::io::partition_info> > const&) [0x14e2ae3]

```
The error can be reproduced using the following command:
```
compute-sanitizer --tool memcheck gtests/PARQUET_TEST --gtest_filter=ParquetWriterDeltaTest/0.SupportedDeltaTestTypes --rmm_mode=cuda
```

Error was introduced with PR https://github.com/rapidsai/cudf/pull/14100

### PR DESCRIPTION
**Pull request by etseidl**
## Description
Fixes #14310.

## Checklist
- [x] I am familiar with the [Contributing Guidelines](https://github.com/rapidsai/cudf/blob/HEAD/CONTRIBUTING.md).
- [x] New or existing tests cover these changes.
- [x] The documentation is up to date with these changes.

### CODE REVIEW

**Review by vuule — APPROVED** [review]

**Review by davidwendt — APPROVED** [review]
I verified locally this fixes the memcheck error reported in #14310

**Comment by GregoryKimball** [comment]
Thank you @etseidl for jumping on this and thank you @davidwendt for confirming the fix!

**Pull request merged**
