### PR TITLE
[REVIEW] Use `Column.full` instead of `scalar_broadcast_to` or `cupy.zeros` 

### LINKED ISSUE #5636: [FEA] Add `column_full` internal api which behaves similar to numpy.full
**Is your feature request related to a problem? Please describe.**
We currently have a method `_return_sentinel_series` which returns a series filled with the required scalar values, it would be better to move this to a column level api like `column_full`.

https://github.com/rapidsai/cudf/blob/branch-0.15/python/cudf/cudf/core/series.py#L2190

**Additional context**
https://github.com/rapidsai/cudf/pull/5619#discussion_r449047440

### PR DESCRIPTION
**Pull request by galipremsagar**
Resolves: #5636 

This PR fully resolves #5636 , as `Column.full` was added as part of this PR https://github.com/rapidsai/cudf/pull/5974, replacing some additional usage instances to close #5636

### CODE REVIEW

**Review by shwina — APPROVED** [review]

**Comment by galipremsagar** [comment]
rerun tests

**Comment by jakirkham** [comment]
Are we able to get rid of `scalar_broadcast_to` then?

**Comment by galipremsagar** [comment]
> Are we able to get rid of `scalar_broadcast_to` then?

As of now, No. Looks like libcudf on boolean types.

cc: @rgsl888prabhu

**Comment by galipremsagar** [comment]
> Are we able to get rid of `scalar_broadcast_to` then?

As of now, No. The reason is we have special handling for datetime/timedelta nat values and categorical dtypes. Also we would still need it because internally we call `to_cudf_compatible_scalar` where we modify dtypes incase of unsupported time units are sent.

**Review by rgsl888prabhu — APPROVED** [review]

**Pull request merged**
