### PR TITLE
[REVIEW] support contiguous split of fixed-point decimal column

### PR DESCRIPTION
**Pull request by sperlingxx**
This PR is about to support contiguous split of fixed-point decimal column through implementing specialized dispatching branches for fixed-point types.

### CODE REVIEW

**Comment by GPUtester** [comment]
Please update the changelog in order to start CI tests.

View the gpuCI docs [here](https://docs.rapids.ai/gpuci#open-pr-or-update-pr).

**Comment by revans2** [comment]
@nvdbaranec could you take a look at this?

**Comment by nvdbaranec** [comment]
There is a huge rewrite of contiguous_split that will be merged soon (https://github.com/rapidsai/cudf/pull/6615) that will obliterate any changes that come from this PR.  I suggest tabling this PR for now - I'll make sure decimal works with the new PR

Pinging @jrhemstad

**Comment by sperlingxx** [comment]
> Should this be closed as superceded by #6615?

Yes, I close it now.

**Pull request closed without merging**
