### PR TITLE
[Hotfix]Use HighLevelGraph api in DataFrame constructor

### PR DESCRIPTION
**Pull request by rjzamora**
Current [cudf test failures](https://gpuci.gpuopenanalytics.com/view/RAPIDS%20branch-gpu-matrix/job/rapidsai/job/gpuci/job/cudf/job/branches/job/cudf-gpu-matrix-branch-0.11/CC_VERSION=7,CUDA=10.0,LINUX_VERSION=centos7,PYTHON_VERSION=3.7/lastCompletedBuild/testReport/) are related to [a recent PR in main-line dask](https://github.com/dask/dask/pull/5613).  That change leads to a failure in dask_cudf, because it assumes that the parallel `DataFrame` constructor is using the `HighLevelGraph` API.  This fix does just that.

### CODE REVIEW

**Comment by quasiben** [comment]
rerun tests

**Comment by kkraus14** [comment]
rerun tests

**Comment by kkraus14** [comment]
rerun tests

**Comment by kkraus14** [comment]
rerun tests

**Comment by kkraus14** [comment]
rerun tests

**Comment by quasiben** [comment]
This is consistently failing in the `cuda10.0`  test:

```
=================================== FAILURES ===================================
______________________________ test_float_series _______________________________

    @given(st.lists(st.floats()))
>   def test_float_series(x):

cudf/tests/test_repr.py:138: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/conda/envs/gdf/lib/python3.7/site-packages/hypothesis/core.py:653: in execute_once
    % (test.__name__, text_repr[0])
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <hypothesis.core.StateForActualGivenExecution object at 0x7fa26c0eecf8>
message = 'Hypothesis test_float_series(x=[0.0]) produces unreliable results: Falsified on the first call but did not on a subsequent one'

    def __flaky(self, message):
        if len(self.falsifying_examples) <= 1:
>           raise Flaky(message)
E           hypothesis.errors.Flaky: Hypothesis test_float_series(x=[0.0]) produces unreliable results: Falsified on the first call but did not on a subsequent one

/conda/envs/gdf/lib/python3.7/site-packages/hypothesis/core.py:853: Flaky
---------------------------------- Hypothesis ----------------------------------
Falsifying example: test_float_series(
    x=[0.0],
```

I think @thomcom has a fix here: https://github.com/rapidsai/cudf/pull/3570

**Pull request merged**
