### PR TITLE
Fix read_parquet bug for bytes input

### LINKED ISSUE #9665: [BUG] cudf read_parquet is not ignoring pandas metadata for use_pandas_metadata=True
**Describe the bug**
Although libcudf is ignoring pandas metadata when `use_pandas_metadata=False`, this metadata is still being extracted and then parsed with pyarrow [in python.pyx](https://github.com/rapidsai/cudf/blob/ba2b51dd8f1b1dd0611f90742e0ffb835615cd33/python/cudf/cudf/_lib/parquet.pyx#L178). If `use_pandas_metadata=False` was working properly, downstream libraries (like NVTabular) could avoid wrapping in-memory bytes objects in `BytesIO` before calling `read_parquet` (which is currently doubling the host-memory usage).

Related: [NVT#1235](https://github.com/NVIDIA-Merlin/NVTabular/issues/1235)

### PR DESCRIPTION
**Pull request by rjzamora**
Closes #9665 (That "bug" is actually wrong, but this PR should address NVTabular performance regression motivating that bug)

The current implementation of `read_parquet` will fail for `bytes` input when there is `RangeIndex` information in the pandas metadata.  This is because cudf will use pyarrow to read the pandas metadata, but pyarrow will not accept `bytes` as input. Issue #9665 incorrectly claims that we should be able to avoid reading the pandas metadata if `use_pandas_metadata=False`. However, for pandas/pyarrow-compatibility reasons, this is **not** actually true.  Rather than adjusting the behavior of `use_pandas_metadata=False`, this PR simply ensures that `bytes` input is wrapped in `BytesIO` before being passed to `pa.parquet.read_metadata`.  Also, since using `BytesIO` seems to have performance consequences when the original bytes buffer has external references, we only wrap the elements of the buffer that contain the footer metadata.

### CODE REVIEW

**Comment by rjzamora** [comment]
cc @quasiben - If it is not too much of a headache, I am hoping that we can get this into 21.12 so that NVTabular will have the option of passing in `bytes` to `cudf.read_parquet`.   Note that this is a certainly a "want", but not necessarily a "need," since an alternative `fsspec.parquet` optimiztion should also work for cudf-21.12 in the future (once some open PRs in fsspec and s3fs are merged/released).

**Comment by rjzamora** [comment]
I am converting this to a draft since I no longer feel it is high priority, and I suspect that the fix to handle `bytes` input  should be a bit simpler than the current implementation (no need to find the size of the footer metadata, etc..).

**Comment by quasiben** [comment]
I think this is a small enough change that we could include this today

**Review by brandon-b-miller — APPROVED** [review]

**Comment by rjzamora** [comment]
>I think this is a small enough change that we could include this today

I simplified the PR so the change is even smaller now (just stops `bytes` input from breaking in the pyarrow call)

**Comment by brandon-b-miller** [comment]
> > I think this is a small enough change that we could include this today
> 
> I simplified the PR so the change is even smaller now (just stops `bytes` input from breaking in the pyarrow call)

This LGTM.

Over the long term, it would be useful to migrate some of the machinery in this file out to python from cython if possible. It makes it a little easier to step through the code and debug what is happening especially if the processing deals exclusively with python objects.

**Comment by rjzamora** [comment]
> it would be useful to migrate some of the machinery in this file out to python from cython if possible

Thats true. I tried to minimize my changes here, but it is certaibly unfortunate that we are parsing/processing the json string in the `pyx` file after it has already been extracted from the `user_data`.  I guess the only reason this is done (for now) is because it is nice to have the `libparquet.read_parquet(..)` call return a dataframe object (rather than a dataframe and other metadata).

**Comment by rjzamora** [comment]
@gpucibot merge

**Pull request merged**
