### PR TITLE
[REVIEW] fix gcc-9 compile errors under CUDA 11

### PR DESCRIPTION
**Pull request by rongou**
When compiling libcudf with gcc-9 under CUDA 11, getting these type of errors:
```bash
error: moving a local object in a return statement prevents copy elision
```
Compiler suggests removing the `std::move()` call.

@jrhemstad @kkraus14

### CODE REVIEW

**Comment by GPUtester** [comment]
Can one of the admins verify this patch?

**Comment by GPUtester** [comment]
Please update the changelog in order to start CI tests.

View the gpuCI docs [here](https://docs.rapids.ai/gpuci#open-pr-or-update-pr).

**Comment by vuule** [comment]
Do we know that copy elision definitely kicks in at these sites (i.e. does compiler warn only in such cases)? 
Because, for `cudf::column`, a move is negligible but a copy overhead is significant and so your PR looks scary without some sort of indication that the elision really happens.
Maybe there's a benchmark that can exercise at least one of these paths?

**Comment by harrism** [comment]
I believe that the worse case for RVO is that if the compiler cannot perform copy elision, it will implicitly invoke the move constructor. That makes `std::move()` redundant in all `return` cases, doesn't it?

@jrhemstad is always correcting people when they `return std::move`, so perhaps he can confirm.

**Comment by vuule** [comment]
Just [looked it up](https://stackoverflow.com/a/9532647), and yes, standard says that it will try treating the object as an rvalue before treating it as an lvalue.
So return moves are completely redundant (at best).

**Comment by jrhemstad** [comment]
> Just [looked it up](https://stackoverflow.com/a/9532647), and yes, standard says that it will try treating the object as an rvalue before treating it as an lvalue.
> So return moves are completely redundant (at best).

In preferential order, the compiler will attempt to do:
RVO/copy-elision > invoke the move ctor (if exists) > invoke copy ctor

If you do `return std::move(...)` then you force the compiler to skip RVO/copy-elision which is actually more efficient than doing a move construction.

**Pull request merged**
