### PR TITLE
Allow multiple row-groups per task in dask_cudf read_parquet

### LINKED ISSUE #3394: [FEA] Add parameter to specify number of row groups per partition for parquets with dask-cudf
**Is your feature request related to a problem? Please describe.**

I would like to have a parameter to allow reading n rows groups per partition for parquets.  We can currently read only `1 row  group` per partition with the  `split_row_groups = True` behavior.  1 partition may or may not be more performant so having this flexibility will go a long way. 

**Describe the solution you'd like**

I would like to have the api another parameter `rows_groups_per_part`  parameter which will allow us to control partition sizes as `chunk-size` allows us to do with `csvs` . 

```python
dask_cudf.read_parquet( 'path*', split_row_groups=True, gather_statistics=True, rows_groups_per_part = x) 
```

I would also like for this to work even if we have to read multiple files (compressed / non-compressed) .  

#### Edge Cases to discuss

I think we may also need to cover below in the future but as a initial implementation we can may be assume below wont be problems. 

* How to handle cases where each files (compressed + non compressed)  have different number of row groups 
 
**Additional context**

Relevant issue +discussion about reading single large parquet files at https://github.com/rapidsai/cudf/issues/3142

### PR DESCRIPTION
**Pull request by rjzamora**
Closes #3394 

~This PR adds some logic to the `dask_cudf.io.read_parquet` implementation to allow a single task to read/aggregate multiple row groups.  Currently, the `split_row_groups` kwarg (default `True`) allows the output DataFrame to be partitioned by row-group (rather than *by file*).  However, it was up to the user to repartition the dataframe after the read if either row-group or file-sized partitions were not desired.~

~The new `row_groups_per_part` kwarg allows to user to pass in the desired number of row-groups to aggregate into each read task (and therefore each output partition).~

~Ideally, the `read_metadata` changes would go into the upstream dask implementation of `read_parquet`.  However, the changes do add some complexity - So, it might be best to start with dask_cudf and prove that there can be a performance benefit.~

**EDIT**:  Since the `chunksize` kwarg has been added to the upstream dask code, this PR now only adds a test.  It also adds some simple logic in `read_parquet` to set `gather_statistics=True` if/when `split_row_groups=True` (default, and required for `chunksize` to work).

### CODE REVIEW

**Comment by mrocklin** [comment]
I'm somewhat against special casing this in dask-cudf if we can get away with it.  

In general I would prefer to first see if we can find a general solution upstream.  If it's ok I'd like to hold off on this PR until we investigate the upstream option.  My apologies for not seeing the original issue until now.

**Comment by rjzamora** [comment]
@mrocklin - I do understand the preference for implementing directly in dask.  However, the "general" implementation should be the same (the read_metadata code would just go in the ArrowEngine) - I started with dask_cudf-only to allow us/others to test things out a bit

**Comment by mrocklin** [comment]
> However, the "general" implementation should be the same (the read_metadata code would just go in the ArrowEngine)

Understood.  Let's see if we can make this fully general, even across fastparquet.  I could imagine an optional chunksize parameter that takes a number of bytes.  If we have statistics that let us guess how large each row group is then we could group the row groups accordingly.  This seems like it would be of general benefit, rather than just for the cudf folks.

> I started with dask_cudf-only to allow us/others to test things out a bit

If it's ok I'm inclined to use cudf work to motivate general improvements when possible.  I would like to avoid the codebases diverging much.

**Comment by rjzamora** [comment]
> Understood. Let's see if we can make this fully general, even across fastparquet. I could imagine an optional chunksize parameter that takes a number of bytes. If we have statistics that let us guess how large each row group is then we could group the row groups accordingly. This seems like it would be of general benefit, rather than just for the cudf folks.

I'm good with this - I like the idea of passing an approximate chunksize in bytes.

> If it's ok I'm inclined to use cudf work to motivate general improvements when possible. I would like to avoid the codebases diverging much.

Right - I opened this PR to get feedback on the general fuctionality from cudf-focused people before spending to much time on upstream changes. The plan was certainly to move the changes to upstream if the consensus was positive.

**Comment by rjzamora** [comment]
**UPDATE**:  This branch has been updated to align with [dask#5607](ttps://github.com/dask/dask/pull/5607).  I will revisit this PR once the upstream changes have been merged.

**Pull request merged**
