### PR TITLE
[WIP] Use CuPy array views [skip ci]

### PR DESCRIPTION
**Pull request by jakirkham**
Extracted from PR ( https://github.com/rapidsai/cudf/pull/4023 ). Uses CuPy for array views of columns and their masks.

### CODE REVIEW

**Comment by harrism** [comment]
Please remember to set labels and project on PRs.

**Comment by raydouglass** [comment]
add to whitelist

**Comment by dillon-cullinan** [comment]
rerun tests

**Comment by harrism** [comment]
Is this PR still needed @jakirkham

**Comment by GPUtester** [comment]
Please update the changelog in order to start CI tests.

View the gpuCI docs [here](https://docs.rapids.ai/gpuci#open-pr-or-update-pr).

**Comment by kkraus14** [comment]
@jakirkham instead of continually bumping the branch I'm going to close this and we can reopen a new PR if / when work is resumed.

**Pull request closed without merging**
