### PR TITLE
Extend cudf devcontainers to specify jitify2 kernel cache

### PR DESCRIPTION
**Pull request by robertmaynard**
## Description
This ensures that inside devcontainers, the helper clean commands will also remvoe the jitify2 cache as it is part of the build directory.

## Checklist
- [x] I am familiar with the [Contributing Guidelines](https://github.com/rapidsai/cudf/blob/HEAD/CONTRIBUTING.md).

### CODE REVIEW

**Comment by vyasr** [comment]
We'll also need this change in the unified devcontainers (i.e. in https://github.com/rapidsai/devcontainers).

**Comment by robertmaynard** [comment]
> We'll also need this change in the unified devcontainers (i.e. in https://github.com/rapidsai/devcontainers).

The unified devcontainers have the change ( https://github.com/rapidsai/devcontainers/blob/branch-24.04/.devcontainer/rapids.Dockerfile#L53 )

**Comment by vyasr** [comment]
Ah didn't see that got lumped into the CUDA 12.2 PR. All good then.

**Review by vyasr — APPROVED** [review]

**Pull request merged**
