### PR TITLE
Update nvCOMP integration table

### PR DESCRIPTION
**Pull request by vuule**
Update with ZSTD and DEFLATE info.
image

### CODE REVIEW

**Comment by vuule** [comment]
CC @galipremsagar

**Comment by vuule** [comment]
Thoughts on removing CSV, JSON and Avro from the table until they start using nvCOMP?

**Comment by galipremsagar** [comment]
> Thoughts on removing CSV, JSON and Avro from the table until they start using nvCOMP?

Umm, feels okay to keep it since the table acts as a better way to know what works and what doesn't than compared to lines/paragraph of text.

**Review by galipremsagar — APPROVED** [review]

**Comment by galipremsagar** [comment]
@gpucibot merge

**Pull request merged**
