### PR TITLE
Update cudfjni 22.06.0-SNAPSHOT

### PR DESCRIPTION
**Pull request by pxLi**
As title, update cudf JNI version 22.06.0-SNAPSHOT

### CODE REVIEW

**Comment by pxLi** [comment]
Will rerun test after 22.06 CI Images are ready

**Review by jlowe — APPROVED** [review]

**Comment by pxLi** [comment]
rerun test

**Comment by pxLi** [comment]
rerun tests

**Comment by pxLi** [comment]
```
10:26:58 conda.CondaMultiError: Downloaded bytes did not match Content-Length
10:26:58   url: https://conda.anaconda.org/rapidsai-nightly/linux-aarch64/cudatoolkit-11.4.1-h4cb0003_8.tar.bz2
10:26:58   target_path: /opt/conda/envs/rapids/pkgs/cudatoolkit-11.4.1-h4cb0003_8.tar.bz2
10:26:58   Content-Length: 1035210656
10:26:58   downloaded bytes: 806944373
```
non-related error

**Comment by pxLi** [comment]
rerun tests

**Comment by pxLi** [comment]
rerun tests

**Comment by pxLi** [comment]
@gpucibot merge

**Pull request merged**
