### PR TITLE
Add empty test files for test reorganization

### PR DESCRIPTION
**Pull request by shwina**
## Description

This PR adds empty test modules that match the "Test Organization" guidelines outlined in the [developer guide](https://github.com/rapidsai/cudf/blob/branch-23.02/docs/cudf/source/developer_guide/testing.md#test-organization). Follow-up PRs will move existing tests into these test modules. 

While I have attempted to match the structure of our API reference as much a possible, there are small differences. For example, the API reference lumps together [Reshaping, Sorting, and Transposing](https://docs.rapids.ai/api/cudf/stable/api_docs/dataframe.html#reshaping-sorting-transposing), while I opted to include two different modules for reshaping and sorting.

There are only a couple of instances where I needed to deviate from the structure though.

## Checklist
- [x] I am familiar with the [Contributing Guidelines](https://github.com/rapidsai/cudf/blob/HEAD/CONTRIBUTING.md).
- [x] New or existing tests cover these changes.
- [x] The documentation is up to date with these changes.

### CODE REVIEW

**Comment by shwina** [comment]
For ease of reference, the file names are:

```
dataframe/test_constructing.py                                                                                                                                                                             
dataframe/test_attributes.py                                                                                                                                                                               
dataframe/test_conversion.py                                                                                                                                                                               
dataframe/test_indexing.py                                                                                                                                                                                 
dataframe/test_binary_operations.py                                                                                                                                                                        
dataframe/test_function_application.py                                                                                                                                                                     
dataframe/test_computation.py                                                                                                                                                                              
dataframe/test_reindexing.py                                                                                                                                                                               
dataframe/test_selecting.py                                                                                                                                                                                
dataframe/test_missing.py                                                                                                                                                                                  
dataframe/test_reshaping.py                                                                                                                                                                                
dataframe/test_sorting.py                                                                                                                                                                                  
dataframe/test_combining.py                                                                                                                                                                                
dataframe/test_timeseries.py                                                                                                                                                                               
dataframe/test_io_serialization.py                                                                                                                                                                         
general_functions/test_data_manipulation.py                                                                                                                                                                
general_functions/test_conversion.py                                                                                                                                                                       
general_functions/test_datetimelike.py                                                                                                                                                                     
general_utilities/test_testing.py                                                                                                                                                                          
groupby/test_indexing.py                                                                                                                                                                                   
groupby/test_function_application.py                                                                                                                                                                       
groupby/test_computation.py                                                                                                                                                                                
groupby/test_stats.py                                                                                                                                                                                      
indexes/test_constructing.py                                                                                                                                                                               
indexes/test_properties.py                                                                                                                                                                                 
indexes/test_modifying.py                                                                                                                                                                                  
indexes/test_computation.py                                                                                                                                                                                
indexes/test_multiindex_compat.py                                                                                                                                                                          
indexes/test_missing.py                                                                                                                                                                                    
indexes/test_memory_usage.py                                                                                                                                                                               
indexes/test_conversion.py                                                                                                                                                                                 
indexes/test_sorting.py                                                                                                                                                                                    
indexes/test_time_specific.py                                                                                                                                                                              
indexes/test_combining.py                                                                                                                                                                                  
indexes/test_selecting.py                                                                                                                                                                                  
indexes/test_numeric.py                                                                                                                                                                                    
indexes/test_categorical.py                                                                                                                                                                                
indexes/test_modifying.py                                                                                                                                                                                  
indexes/test_interval.py                                                                                                                                                                                   
indexes/multiindex/test_constructing.py                                                                                                                                                                    
indexes/multiindex/test_properties.py                                                                                                                                                                      
indexes/multiindex/test_selecting.py                                                                                                                                                                       
indexes/datetime/test_constructing.py                                                                                                                                                                      
indexes/datetime/test_components.py                                                                                                                                                                        
indexes/datetime/test_time_specific.py                                                                                                                                                                     
indexes/datetime/test_conversion.py                                                                                                                                                                        
indexes/timedelta/test_constructing.py 
indexes/timedelta/test_components.py                                                                                                                                                                       
indexes/timedelta/test_conversion.py                                                                                                                                                                       
io/test_csv.py                                                                                                                                                                                             
io/test_text.py                                                                                                                                                                                            
io/test_json.py                                                                                                                                                                                            
io/test_parquet.py                                                                                                                                                                                         
io/test_orc.py                                                                                                                                                                                             
io/test_hdf5.py                                                                                                                                                                                            
io/test_feather.py                                                                                                                                                                                         
io/test_avro.py                                                                                                                                                                                            
lists/test_list_methods.py                                                                                                                                                                                 
options/test_options.py                                                                                                                                                                                    
series/test_constructing.py                                                                                                                                                                                
series/test_attributes.py                                                                                                                                                                                  
series/test_conversion.py                                                                                                                                                                                  
series/test_indexing.py                                                                                                                                                                                    
series/test_binary_operations.py                                                                                                                                                                           
series/test_function_application.py                                                                                                                                                                        
series/test_computation.py                                                                                                                                                                                 
series/test_selecting.py                                                                                                                                                                                   
series/test_missing.py                                                                                                                                                                                     
series/test_reshaping.py                                                                                                                                                                                   
series/test_sorting.py                                                                                                                                                                                     
series/test_combining.py                                                                                                                                                                                   
series/test_timeseries.py                                                                                                                                                                                  
series/test_accessors.py                                                                                                                                                                                   
series/test_datetimelike.py                                                                                                                                                                                
series/test_categorial.py                                                                                                                                                                                  
series/test_io_serialization.py                                                                                                                                                                            
strings/test_string_methods.py                                                                                                                                                                             
structs/test_struct_methods.py                                                                                                                                                                             
text/test_subword_tokenizer.py                                                                                                                                                                             
window/test_rolling.py     
```

**Comment by shwina** [comment]
In addition to organizing tests to align with the layout of our API reference, we currently recommend in our developer guide that:

> In cases where tests may be shared by multiple classes sharing a common parent
> (e.g. DataFrame and Series both require IndexedFrame tests),
> the tests may be placed in a directory corresponding to the parent class.

Thus, for example, rather than placing tests for `Series.first` in `series/test_selecting.py`, and tests for `DataFrame.first` in `dataframe/test_selecting.py`, we recommend placing both in `indexed_frame/test_selecting.py`.

This way of organizing tests has both pros and cons, and I believe the cons outweigh the pros. I'm curious what others think.

* :green_circle: **Pro**: The location of the tests for a method matches the location in the class hierarchy that test is implemented in. (this is also a con, see below).

* :green_circle: **Pro**: Because all tests for `.first` are in the same module, any specific testing utilities needed by the test can be included in the same module. There's no need for duplication or ambiguity as to where those utilities should live.

* :red_circle: **Con**: Our class hierarchy is an implementation detail. If a new class is added into the hierarchy, tests may need to be relocated. Also, if a method newly needs to be specialized in a subclass, tests for that method need to be relocated to the directory corresponding to that subclass. Not only does this add churn, it also becomes easy for things to go out of sync.

* :red_circle: **Con**: It's not easy to predict where the tests for a method live without knowledge of where the method is implemented in the source: are the tests for `DataFrame.first` in `frame/test_selecting.py`, `indexed_frame/test_selecting.py`, or `dataframe/test_selecting.py`?

**Comment by brandon-b-miller** [comment]
I think major changes to the hierarchy of our internal classes should be uncommon enough to make moving tests a lot of overhead, although I do think we should certainly do so if such changes are ever made. And while such things are implementation details, I think if one is interacting with our tests directly it's more likely that such details might be relevant anyways.

**Comment by vyasr** [comment]
@shwina what's the status on this PR? Should we take a look at it, or is it not quite ready yet, Also, how do we want to tackle next steps? I think we should wait to get everything reorganized to our liking before closing #4730, right?

**Review by vyasr — APPROVED** [review]
Only one question, I see that there are data subpackages for each file format (avro, orc, etc). Is that necessary? I could see value in subdirectories if you want to store data in those, but why do they need `__init__.py` files? Other than that, this org looks good to me.

**Pull request merged**
