### PR TITLE
Add packed serialization option for dataframes

### PR DESCRIPTION
**Pull request by charlesbluca**
Adds the option to enable pack/unpack for dataframe serialization using the environment variable `CUDF_PACKED_SERIALIZATION`. This is intended to be a temporary solution to aid in benchmarking, which will eventually be replaced by a config module discussed in #5311.

### CODE REVIEW

**Review by brandon-b-miller — COMMENTED** [review]
@charlesbluca this looks fine overall but I am wondering how we plan on testing this? Seems we have some tests for serialization that might suffice from the perspective of coverage, but you'd have to inject the environment variable in both the true and false state during the test session somehow.

**Comment by charlesbluca** [comment]
That's a good point I didn't consider - I imagine we could either

- Make a function/context manager to specific enable/disable pack/unpack independent of the env variable
- Call `os.environ.get()` on each call of `serialize/deserialize`, from which we should be able to use `os.environ.set()` to enable pack/unpack from the test script

**Comment by brandon-b-miller** [comment]
Something like this may help https://docs.pytest.org/en/latest/how-to/monkeypatch.html

**Comment by charlesbluca** [comment]
Converting this to draft as there are currently a lot of issues with pack/unpack serialization that need to be worked out before this option is really useful for its intended purpose (benchmarking).

**Comment by galipremsagar** [comment]
Moving this to `21.12`, please target this PR to `21.12`.

**Comment by charlesbluca** [comment]
Closing this as we haven't really found a place for pack/unpack serialization yet - will reopen if this changes in the future

**Pull request closed without merging**
