### PR TITLE
Fix dask.dataframe API docs  links after reorg

### PR DESCRIPTION
**Pull request by jsignell**
ref: https://github.com/dask/dask/pull/7890

### CODE REVIEW

**Comment by GPUtester** [comment]
Can one of the admins verify this patch?

**Review by galipremsagar — APPROVED** [review]
Thanks @jsignell !

**Comment by galipremsagar** [comment]
ok to test

**Comment by ajschmidt8** [comment]
ok to test

**Comment by galipremsagar** [comment]
@gpucibot merge

**Comment by galipremsagar** [comment]
rerun tests

**Pull request merged**
