### PR TITLE
Fix cudf java build error.

### PR DESCRIPTION
**Pull request by firestarman**
cudf Java build is broken by https://github.com/rapidsai/cudf/pull/9942. So update the `hash` JNI accordingly.

Signed-off-by: Firestarman <firestarmanllc@gmail.com>

### CODE REVIEW

**Review by GaryShen2008 — APPROVED** [review]

**Comment by sperlingxx** [comment]
LGTM! Thanks for the fix.

**Comment by sperlingxx** [comment]
rerun tests

**Comment by firestarman** [comment]
rerun tests

**Comment by firestarman** [comment]
java build failed in CI, seems to be related to conda libraries installation.
```
16:58:49 Solving environment: ...working... Build timed out (after 40 minutes). Marking the build as failed.
16:58:50 Build was aborted
16:58:50 Recording test results
16:58:51 [Checks API] No suitable checks publisher found.
16:58:51 [Set GitHub commit status (universal)] ERROR on repos 
```

**Comment by firestarman** [comment]
I am going to merge this to unblock the cudf java nightly build.
The failure in gpuci/java is not relevant.

**Comment by firestarman** [comment]
@gpucibot merge

**Pull request merged**
