### PR TITLE
[REVIEW] Introduce parity with pandas for `MultiIndex.loc` ordering & fix a bug in `Groupby` with `as_index`

### PR DESCRIPTION
**Pull request by galipremsagar**
## Description
This PR:

- [x] Adds ordering in `MultiIndex.loc` when pandas compatibility mode is enabled.
- [x] Fixes a bug in `Groupby` when `as_index` is passed and is not being respected when a getitem call is performed on the groupby.

## Checklist
- [x] I am familiar with the [Contributing Guidelines](https://github.com/rapidsai/cudf/blob/HEAD/CONTRIBUTING.md).
- [x] New or existing tests cover these changes.
- [x] The documentation is up to date with these changes.

### CODE REVIEW

**Review by bdice — APPROVED** [review]
This looks fine. Once this is merged, please get the permalink for this TODO and copy it into some issue about deterministic join/merge. There is at least one existing issue on this topic but I can’t search for it at this moment.

**Comment by galipremsagar** [comment]
Thanks @bdice ! Made a note of it in https://github.com/rapidsai/cudf/issues/12236

**Comment by wence-** [comment]
Sorry, I had a review pending but didn't hit go in time. I think this change was wrong unfortunately :(

**Comment by galipremsagar** [comment]
> Sorry, I had a review pending but didn't hit go in time. I think this change was wrong unfortunately :(

Apologies for the merge @wence-, I think the solution you pointed out here: https://github.com/rapidsai/cudf/pull/13657#discussion_r1251820066 seems good to me. Could you open a PR with same changes that I can review & approve instead? I'm not on my workstation, or else I would have done it.

**Comment by wence-** [comment]
https://github.com/rapidsai/cudf/pull/13660

**Pull request merged**
