### PR TITLE
Fix clang-format version check for 11.1.0

### PR DESCRIPTION
**Pull request by davidwendt**
Fixes CI builds failing style checks which stop the build from compiling and executing tests.

### CODE REVIEW

**Review by ttnghia — APPROVED** [review]

**Review by jrhemstad — APPROVED** [review]

**Comment by bdice** [comment]
I created #9730 to solve the same problem. This forward-merges @galipremsagar’s PR #9716. I think the forward merger is the desired way to fix this?

**Comment by davidwendt** [comment]
> I created #9730 to solve the same problem by forward-merging @galipremsagar’s PR #9716. I think the forward merger is the desired way to fix this?

Perhaps but then why is it failing in 22.02? Seems like something is wrong. This change unblocks me on my current PRs and does not appear to hold up 9730.

**Comment by bdice** [comment]
> > I created #9730 to solve the same problem by forward-merging @galipremsagar’s PR #9716. I think the forward merger is the desired way to fix this?
> 
> Perhaps but then why is it failing in 22.02? Seems like something is wrong. This change unblocks me on my current PRs and does not appear to hold up 9730.

@galipremsagar’s PR targeted 21.12 but had a merge conflict with 22.02, causing the error we see on 22.02. The forward-merger I created (with resolved conflicts from #9721) also includes the change in this PR.

**Review by bdice — COMMENTED** [review]
This PR does not correct the version numbers in the conda environment pinnings, so local environments created from that file would not match the pinned clang-format in CI. Forward-merging #9730 would fix the issue while keeping environments consistent.

**Comment by davidwendt** [comment]
Fixed by #9730

**Pull request closed without merging**
