### PR TITLE
Refactor index construction

### PR DESCRIPTION
**Pull request by vyasr**
The changes in #8309 allow us to avoid overriding `__new__` for all index types and instead use the more standard `__init__`, which also makes it easier to share logic between different index classes via typical inheritance patterns.

### CODE REVIEW

**Comment by vyasr** [comment]
rerun tests

**Comment by vyasr** [comment]
rerun tests

**Review by shwina — APPROVED** [review]

**Review by galipremsagar — APPROVED** [review]

**Comment by galipremsagar** [comment]
rerun tests

**Comment by galipremsagar** [comment]
@gpucibot merge

**Comment by galipremsagar** [comment]
rerun tests

**Comment by vyasr** [comment]
rerun tests

**Pull request merged**
