### PR TITLE
Change cudf::detail::tdigest to cudf::tdigest::detail

### PR DESCRIPTION
**Pull request by davidwendt**
## Description
Changes `cudf::detail::tdigest` to `cudf::tdigest::detail` in the tdigest source files.
While working on #12049, found there was a mixture of `cudf::tdigest` and `cudf::detail::tdigest` that seemed confusing and inconsistent. Changing to `cudf::tdigest::detail` made this code easier to follow.
Also, move the `size_begin()` member function in `tdigest_column_view` out as a standalone function in a separate `.cuh` header since it is only used in a few places and the `tdigest_column_view.cuh` is included in many places. This allowed changing the `tdigest_column_view.cuh` to a `.hpp` file.

Depends on #12049 

## Checklist
- [x] I am familiar with the [Contributing Guidelines](https://github.com/rapidsai/cudf/blob/HEAD/CONTRIBUTING.md).
- [x] New or existing tests cover these changes.
- [x] The documentation is up to date with these changes.

### CODE REVIEW

**Review by bdice — APPROVED** [review]

**Review by ttnghia — APPROVED** [review]
This is a potential improvement with documentation: We need to standardize either `cudf::detail::module_name` or `cudf::module_name::detail` namespace. From this PR, `cudf::module_name::detail` should be favored and published into the dev guide.

**Comment by bdice** [comment]
> This is a potential improvement with documentation: We need to standardize either `cudf::detail::module_name` or `cudf::module_name::detail` namespace. From this PR, `cudf::module_name::detail` should be favored and published into the dev guide.

This also came up in https://github.com/rapidsai/cudf/pull/12046#discussion_r1014532713.

**Comment by vuule** [comment]
> > This is a potential improvement with documentation: We need to standardize either `cudf::detail::module_name` or `cudf::module_name::detail` namespace. From this PR, `cudf::module_name::detail` should be favored and published into the dev guide.
> 
> This also came up in [#12046 (comment)](https://github.com/rapidsai/cudf/pull/12046#discussion_r1014532713).

I'm planning to open an issue for cuIO (which is mostly in the wrong order of namespaces). Let me know if this is something we need to fix in the rest of libcudf as well, so the issue reflects that too.

**Comment by davidwendt** [comment]
@gpucibot merge

**Pull request merged**
