### PR TITLE
Drop NumPy build dep from cudf (keep in pylibcudf)

### PR DESCRIPTION
**Pull request by jakirkham**
## Description

With the pylibcudf refactor, only pylibcudf looks for NumPy headers. Whereas the Python cudf package does not. Given this, we shouldn't need the NumPy build dependency on anything other than pylibcudf. So drop the NumPy build dependency elsewhere. In addition to cleaning up the dependencies this will ease the NumPy 2 upgrade effort.

## Checklist
- [ ] I am familiar with the [Contributing Guidelines](https://github.com/rapidsai/cudf/blob/HEAD/CONTRIBUTING.md).
- [ ] New or existing tests cover these changes.
- [ ] The documentation is up to date with these changes.

### CODE REVIEW

**Comment by vyasr** [comment]
We're about 2 PRs away from numpy and pyarrow being removed as build dependencies altogether so this PR is probably superfluous.

**Comment by jakirkham** [comment]
Was having issues updating to NumPy 2 without running into conflicts between `pylibcudf` and friends as several are building with NumPy 1.23 and need `pylibcudf` in their build requirements. So we either update them altogether or we start removing more NumPy bits. Am ambivalent between the two approaches

**Comment by vyasr** [comment]
Commented on that issue.

**Comment by jakirkham** [comment]
Closing this out now that NumPy 2 is used in the builds as of PR: https://github.com/rapidsai/cudf/pull/16300

**Pull request closed without merging**
