### PR TITLE
Fix all-empty input column for strings split APIs

### LINKED ISSUE #16453: [BUG] `split_record` output empty list for empty input string
For an empty input string, `split_record` does not output anything (empty list). This is inconsistent with the cases when the input does not contain the split delimiter then the output list has one element equal to the input. For example:
```
input = "abcxyz"
output = split_record(input, "@")
output = ["abcxyz"]
```

However:
```
input = ""
output = split_record(input, "@")
output = []
```
This inconsistent behavior causes mismatching between cudf and Java String.split API, which states that:
> If the expression does not match any part of the input then the resulting array has just one element, namely this string.

Ref: https://docs.oracle.com/javase/8/docs/api/java/lang/String.html#split-java.lang.String-int-

### PR DESCRIPTION
**Pull request by davidwendt**
## Description
Fixes specialized behavior for all empty input column on the strings split APIs.
Verifying behavior with Pandas `str.split( pat, expand, regex )`
`pat=None     -- whitespace`
`expand=False -- record APIs`
`regex=True   -- re APIs`

- [x] `split`
- [x] `split` - whitespace
- [x] `rsplit`
- [x] `rsplit` - whitespace
- [x] `split_record`
- [x] `split_record` - whitespace
- [x] `rsplit_record`
- [x] `rsplit_record` - whitespace
- [x] `split_re`
- [x] `rsplit_re`
- [x] `split_record_re`
- [x] `rsplit_record_re`

Closes #16453

## Checklist
- [x] I am familiar with the [Contributing Guidelines](https://github.com/rapidsai/cudf/blob/HEAD/CONTRIBUTING.md).
- [x] New or existing tests cover these changes.
- [x] The documentation is up to date with these changes.

### CODE REVIEW

**Review by harrism — APPROVED** [review]

**Review by bdice — APPROVED** [review]
Just to verify — this aligns with pandas behavior, but what about Spark? Code looks fine otherwise.

**Comment by davidwendt** [comment]
> Just to verify — this aligns with pandas behavior, but what about Spark? Code looks fine otherwise.

Good point. I forgot to add the original issue which came from Spark.
https://github.com/rapidsai/cudf/issues/16453
@ttnghia Can you verify this will be OK for Spark?

**Comment by ttnghia** [comment]
Spark integration tests (after reverting workaround for empty strings due to issue https://github.com/rapidsai/cudf/issues/16453) all passed with this work :+1:

**Review by hyperbolic2346 — APPROVED** [review]

**Pull request merged**
