### PR TITLE
[REVIEW] fix array out-of-bound errors in Orc writer

### LINKED ISSUE #6333: [BUG] array out of bound in orc writer
I was trying to build libcudf with gcc-10 and it complained about this error. This looks like it might be a legitimate bug.
```console
/home/rou/src/cudf/cpp/src/io/orc/writer_impl.cu: In member function ‘void cudf::io::detail::orc::writer::impl::write_index_stream(int32_t, int32_t, cudf::io::detail::orc::orc_column_view*, size_t, size_t, size_t, size_t, const hostdevice_vector<cudf::io::orc::gpu::EncChunk>&, const hostdevice_vector<cudf::io::orc::gpu::StripeStream>&, const hostdevice_vector<cudf::io::gpu_inflate_status_s>&, cudf::io::orc::StripeInformation&, std::vector<cudf::io::orc::Stream>&, cudf::io::orc::ProtobufWriter*)’:
/home/rou/src/cudf/cpp/src/io/orc/writer_impl.cu:868:157: error: array subscript 4 is outside array bounds of ‘std::array<int, 4> [1]’ [-Werror=array-bounds]
  868 |       while ((record[1] >= 0) && (static_cast<size_t>(record[0]) >= compression_blocksize_) &&
      |                                                                                                                                                             ^                               
/home/rou/src/cudf/cpp/src/io/orc/writer_impl.cu:844:31: note: while referencing ‘present’
  844 |   std::array<int32_t, 4> present;
      |                               ^~~    
/home/rou/src/cudf/cpp/src/io/orc/writer_impl.cu:868:157: error: array subscript 4 is outside array bounds of ‘std::array<int, 4> [1]’ [-Werror=array-bounds]
  868 |       while ((record[1] >= 0) && (static_cast<size_t>(record[0]) >= compression_blocksize_) &&
      |                                                                                                                                                             ^                               
/home/rou/src/cudf/cpp/src/io/orc/writer_impl.cu:845:31: note: while referencing ‘data’
  845 |   std::array<int32_t, 4> data;
      |                               ^   
/home/rou/src/cudf/cpp/src/io/orc/writer_impl.cu:868:157: error: array subscript 4 is outside array bounds of ‘std::array<int, 4> [1]’ [-Werror=array-bounds]
  868 |       while ((record[1] >= 0) && (static_cast<size_t>(record[0]) >= compression_blocksize_) &&
      |                                                                                                                                                             ^                               
/home/rou/src/cudf/cpp/src/io/orc/writer_impl.cu:846:31: note: while referencing ‘data2’
  846 |   std::array<int32_t, 4> data2;
      |                               ^    
cc1plus: all warnings being treated as errors
CMakeFiles/cudf.dir/build.make:1056: recipe for target 'CMakeFiles/cudf.dir/src/io/orc/writer_impl.cu.o' failed
make[2]: *** [CMakeFiles/cudf.dir/src/io/orc/writer_impl.cu.o] Error 1
CMakeFiles/Makefile2:489: recipe for target 'CMakeFiles/cudf.dir/all' failed
make[1]: *** [CMakeFiles/cudf.dir/all] Error 2
Makefile:159: recipe for target 'all' failed
make: *** [all] Error 2
```

@j-ieong @harrism @jrhemstad

### PR DESCRIPTION
**Pull request by rongou**
Fixes #6333 

gcc-10 also complained about the missing includes.

@OlivierNV

### CODE REVIEW

**Comment by GPUtester** [comment]
Please update the changelog in order to start CI tests.

View the gpuCI docs [here](https://docs.rapids.ai/gpuci#open-pr-or-update-pr).

**Review by vuule — APPROVED** [review]
Thanks for patching this! Surprising that it does not affect any tests.
It would be good to include a test in this PR, but I understand this is not a practical request in this case.

**Review by harrism — APPROVED** [review]

**Comment by rongou** [comment]
@vuule agree it's a bit strange the tests were passing before. I suspect the out-of-bound calls are being short-circuited in the if statement, but I don't really understand this code to verify it. :) Please add more tests if you can catch the issue.

**Comment by OlivierNV** [comment]
Actually, the statement `while ((record[1] >= 0) && ...` should also be `while ((record[0] >= 0) && ...` (the check if positive is because it is being casted to unsigned in the subsequent comparison to make sure it's in bounds ~ not really a big deal since negative value would indicate that data is already messed up)
The use of `std::array` makes it quite difficult to understand what this does here (a struct with named fields would be more appropriate)

**Comment by vuule** [comment]
Thank you @OlivierNV . Will file issues for struct use and test coverage.

**Pull request merged**
