### PR TITLE
[REVIEW] Add nvtext is_vowel/is_consonant functions

### LINKED ISSUE #2768: [FEA] Add is_consonant, is_vowel, contains_vowel functions to  Nvstrings/Nvtext
**Is your feature request related to a problem? Please describe.**

I would like for nvtext/Nvstrings to add below functions:

* is_consonant
* is_vowel
* contains_vowel

The API requested is as follows:

* is_consonant
```python

def is_consonant(nvstrs, index):
"""
  Parameters
    ----------
    nvstrs:  nvstrsings instance
    index: index of the character
  
  Returns
   --------
  Returns a bool array with True if the character at that index of a string is a consonant otherwise its marked as false. 

     Please not that if there is no character at that index we mark it as False
    The input of the index can be negative numbers/array too. 

"""
```
* is_vowel

This can just be inverse of is_consonant.
```python
is_vowel(nvstrs, index)
```

* contains_vowel
```python
def contains_vowel(nvstrs):
"""
  Parameters
    ----------
    nvstrs:  nvstrsings instance
    
     Returns
   --------
  Returns a bool array with True if the string contains vowel otherwise returns False
  
  Please mark null strings as False
"""

```

**Describe alternatives you've considered**
I can consider looping through characters buts that may be  too expensive. 

**Additional context**
We all-ready have some of the implementation at:
 https://github.com/rapidsai/cudf/blob/a80e9a1e173abf60f5703486933e80d87982212a/cpp/custrings/text/stemmer.cu#L36

I need the above functions for porter stemmer implementation. 

For definition of vowel/consonant below is used from the https://www.nltk.org/_modules/nltk/stem/porter.html#PorterStemmer and porter stemmer paper.
````
  A consonant is defined in the paper as follows:

            A consonant in a word is a letter other than A, E, I, O or
            U, and other than Y preceded by a consonant. (The fact that
            the term `consonant' is defined to some extent in terms of
            itself does not make it ambiguous.) So in TOY the consonants
            are T and Y, and in SYZYGY they are S, Z and G. If a letter
            is not a consonant it is a vowel.
        """ 
````

### PR DESCRIPTION
**Pull request by davidwendt**
Fixes #2768 
Adding functions for supporting Porter stemmer acceleration checking characters in NVStrings instance for vowels or consonants as defined.

https://www.nltk.org/_modules/nltk/stem/porter.html#PorterStemmer and porter stemmer paper.

>             A consonant in a word is a letter other than A, E, I, O or
>             U, and other than Y preceded by a consonant. (The fact that
>             the term `consonant' is defined to some extent in terms of
>             itself does not make it ambiguous.) So in TOY the consonants
>             are T and Y, and in SYZYGY they are S, Z and G. If a letter
>             is not a consonant it is a vowel.

### CODE REVIEW

**Comment by davidwendt** [comment]
@VibhuJawa I could use some advice on handling `index` parameter as an array as described in #2768 . This would need to be a device memory pointer. There is no easy way to distinguish a plain integer from a pointer address. We could add an additional bool parameter perhaps.

**Comment by VibhuJawa** [comment]
> @VibhuJawa I could use some advice on handling `index` parameter as an array as described in #2768 . This would need to be a device memory pointer. There is no easy way to distinguish a plain integer from a pointer address. We could add an additional bool parameter perhaps.

I am fine with having the additional `bool parameter` to address whether index is a `int` or a `dev_ptr`  . 

I don't have a  strong opinion from   an `API` standpoint but i think we  have something like the `bdevmem `  in the `from_offsets` function may be we can follow that to be consistent. 
 https://github.com/rapidsai/cudf/blob/c68835079a70d0ea912854f5b7beff4792e4f6a1/python/nvstrings/nvstrings.py#L122-L124

**Comment by davidwendt** [comment]
> Are we handing negative indices too ? If yes then may be we should add a test for that too.
> 
Yes, negative indices should work too. I will add a test case for that.

**Comment by davidwendt** [comment]
rerun tests

**Comment by davidwendt** [comment]
rerun tests

**Comment by harrism** [comment]
I thought nvstrings was going away as part of libcudf++?

**Comment by davidwendt** [comment]
> I thought nvstrings was going away as part of libcudf++?

This is NVText which has a different fate yet to be decided once NVStrings is ported.

**Comment by davidwendt** [comment]
rerun tests

**Pull request merged**
