### PR TITLE
Remove unused custreamz thirdparty directory

### LINKED ISSUE #10918: Drop `thirdparty` directory in `custreamz`
Appears there is a [`thirdparty` directory in `custreamz`]( https://github.com/rapidsai/cudf/tree/branch-22.06/python/custreamz/thirdparty ), but it is empty except for a license file. Guessing this was uses previously for something, but it appears to be no longer needed. If that's true, should we drop it?

### PR DESCRIPTION
**Pull request by vyasr**
## Description

Closes #10918 

## Checklist
- [x] I am familiar with the [Contributing Guidelines](https://github.com/rapidsai/cudf/blob/HEAD/CONTRIBUTING.md).
- [x] New or existing tests cover these changes.
- [x] The documentation is up to date with these changes.

### CODE REVIEW

**Review by galipremsagar — APPROVED** [review]
cc: @jdye64 for visibility

**Comment by jdye64** [comment]
> cc: @jdye64 for visibility

Thanks for the heads-up, yep that is totally fine.

**Review by bdice — APPROVED** [review]

**Comment by vyasr** [comment]
rerun tests

**Comment by vyasr** [comment]
rerun tests

**Comment by bdice** [comment]
@gpucibot merge

**Pull request merged**
