### PR TITLE
[REVIEW] tests/types_test.cpp int to char fix for Arm Jetson TX2/Xavier/Maxwell

### PR DESCRIPTION
**Pull request by awthomp**
Fixed issue [2593](https://github.com/rapidsai/cudf/issues/2593) by explicitly casting negative int types to chars.

Close [2593](https://github.com/rapidsai/cudf/issues/2593)

### CODE REVIEW

**Comment by GPUtester** [comment]
Can one of the admins verify this patch?

**Comment by harrism** [comment]
From the commit history it looks like your branch is based off of something old. You'll want to do something like this:

```
git pull branch-0.10
git checkout bug-issue2593-tests-typeconversion
git merge branch-0.10
```

Then push again.

**Comment by awthomp** [comment]
Boy, I've worked this into a state, and I'm not enough of a git-ninja to rescue whatever happened to my local repo. Despite changing branches to 0.10, looks like it's the code from 0.8. Will close and resubmit when I get my environment fixed.

**Comment by harrism** [comment]
We've all been there. It's good practice. Let me know if you need help.

**Pull request closed without merging**
