### PR TITLE
compile libnvcomp with PTDS if requested

### LINKED ISSUE #9534: [BUG] libnvcomp is not compiled with PTDS
CUDF does not define CUDA_API_PER_THREAD_DEFAULT_STREAM when building libnvcomp.a, even when -DPER_THREAD_DEFAULT_STREAM=ON is defined.

We found this when comparing nsys traces taken while running tpc-ds benchmarks on spark-rapids with and without LIBCUDF_USE_NVCOMP=1 defined.  The cudf snappy kernels use per thread default streams, but nvcomp was using only 1 stream (7).  As a result, most queries were slower with LIBCUDF_USE_NVCOMP=1, which is not what we expect.

**Expected behavior**
When you compile CUDF with -DPER_THREAD_DEFAULT_STREAM=ON, libnvcomp.a should be compiled with CUDA_API_PER_THREAD_DEFAULT_STREAM.   We expect that with this change, most queries will be at least as fast if not faster when run with LIBCUDF_USE_NVCOMP=1.

### PR DESCRIPTION
**Pull request by jbrennan333**
closes #9534 

Change get_nvcomp.cmake to compile with CUDA_API_PER_THREAD_DEFAULT_STREAM is PER_THREAD_DEFAULT_STREAM is defined.

I did not add unit tests for this, but I tested it manually by building CUDF and then running a query to verify that PTDS was being used.

### CODE REVIEW

**Comment by jbrennan333** [comment]
I believe this is ready to merge.  The 11.5 build issues are unrelated.

**Comment by jbrennan333** [comment]
@robertmaynard do I need another review to get this merged?

**Comment by robertmaynard** [comment]
> @robertmaynard do I need another review to get this merged?

In general we required two reviews before merging. Maybe @vyasr  or @jrhemstad could provide the second review.

**Review by vyasr — APPROVED** [review]
LGTM

**Comment by vyasr** [comment]
@gpucibot merge

**Comment by jbrennan333** [comment]
Thanks @robertmaynard and @vyasr!

**Pull request merged**
