### PR TITLE
[REVIEW] Preemptive fix for expected dask.dataframe dispatch changes

### PR DESCRIPTION
**Pull request by rjzamora**
[dask#5973](https://github.com/dask/dask/pull/5973) introduces the `ignore_index=` argument to the `group_split_dispatch` and `concat_dispatch` functions.  ~This~ **The upstream** change improves the performace of `set_index`, but will break the `dask_cudf` code without the changes introduced in this PR.

### CODE REVIEW

**Comment by rjzamora** [comment]
@kkraus14 - Sorry that my original PR blurb was a bit unclear (I think).  To clarify: This PR should be merged **before** the upstream dask PR.

**Comment by rjzamora** [comment]
rerun tests

**Comment by rjzamora** [comment]
rerun tests

**Comment by kkraus14** [comment]
@rjzamora Don't trigger a restart on CI for these failures. I'll just admin merge assuming the GPU tests pass.

**Comment by jakirkham** [comment]
So does this mean we require the latest version of Dask now? Or is this still compatible with older versions?

**Pull request merged**
