### PR TITLE
[WIP] Add docs build script [skip-ci]

### PR DESCRIPTION
**Pull request by dillon-cullinan**
Moving the docs build into the repo to better streamline our doc build jobs.

### CODE REVIEW

**Comment by GPUtester** [comment]
Please update the changelog in order to start CI tests.

View the gpuCI docs [here](https://docs.rapids.ai/gpuci#open-pr-or-update-pr).

**Comment by harrism** [comment]
@dillon-cullinan is this still needed? It is orphaned, so needs to at least be assigned to a project.

**Comment by kkraus14** [comment]
@dillon-cullinan what's the state of this?

**Comment by kkraus14** [comment]
Targeting branch-0.14 so I'm going to just close this... Feel free to reopen if needed...

**Pull request closed without merging**
