### PR TITLE
Replace `ccache` with `sccache`

### PR DESCRIPTION
**Pull request by ajschmidt8**
This PR replaces `ccache` with `sccache`.

### CODE REVIEW

**Comment by ajschmidt8** [comment]
rerun tests

**Comment by ajschmidt8** [comment]
pre-cache C++ build time ([link to log](https://gpuci.gpuopenanalytics.com/job/rapidsai/job/gpuci/job/cudf/job/prb/job/cudf-cpu-cuda-build/7484/CUDA=11.5/console)): 1:34:39.5

image

**Comment by ajschmidt8** [comment]
rerun tests

**Comment by davidwendt** [comment]
Is there any way to get the ccache hit results for the build. We report that in the [Build Metrics Report](https://gpuci.gpuopenanalytics.com/job/rapidsai/job/gpuci/job/cudf/job/prb/job/cudf-cpu-cuda-build/CUDA=11.5/7504/Build_20Metrics_20Report/).
The report values are generated here: https://github.com/rapidsai/cudf/blob/b7aa47fa917095e17ab376f8cadaa78b3ee4566c/build.sh#L187-L194
These an be helpful in understanding the results.

**Comment by ajschmidt8** [comment]
> Is there any way to get the ccache hit results for the build. We report that in the [Build Metrics Report](https://gpuci.gpuopenanalytics.com/job/rapidsai/job/gpuci/job/cudf/job/prb/job/cudf-cpu-cuda-build/CUDA=11.5/7504/Build_20Metrics_20Report/). The report values are generated here:
> 
> 
> 
> These can be helpful in understanding the results.

@davidwendt, I had this on my list of things to investigate :slightly_smiling_face:. You beat me to it. `sccache` does have a `--show-stats` (`-s`) flag as well. The output it a little bit different than `ccache -s`. I've posted the output for each below.




<details>
<summary>
ccache -s
</summary>

```
cache directory                     /root/.cache/ccache
primary config                      /root/.config/ccache/ccache.conf
secondary config (readonly)         /etc/opt/conda/ccache.conf
cache hit (direct)                     0
cache hit (preprocessed)               0
cache miss                             0
cache hit rate                      0.00 %
cleanups performed                     0
files in cache                         0
cache size                           0.0 kB
max cache size                       5.0 GB
```
</details>


<details>
<summary>
sccache -s
</summary>

```
Compile requests                      0
Compile requests executed             0
Cache hits                            0
Cache misses                          0
Cache timeouts                        0
Cache read errors                     0
Forced recaches                       0
Cache write errors                    0
Compilation failures                  0
Cache errors                          0
Non-cacheable compilations            0
Non-cacheable calls                   0
Non-compilation calls                 0
Unsupported compiler calls            0
Average cache write               0.000 s
Average cache read miss           0.000 s
Average cache read hit            0.000 s
Failed distributed compilations       0
Cache location                  S3, bucket: Bucket(name=rapids-sccache, base_url=http://rapids-sccache.s3-us-west-2.amazonaws.com/)
```
</details>


There is also a `--zero-stats` (`-z`) flag:

<details>
<summary>
All sccache commands
</summary>

```
# sccache
sccache: No command specified
sccache 0.2.15

USAGE:
    sccache [FLAGS] [OPTIONS] [cmd]...

FLAGS:
        --dist-auth       authenticate for distributed compilation
        --dist-status     show status of the distributed client
    -h, --help            Prints help information
    -s, --show-stats      show cache statistics
        --start-server    start background server
        --stop-server     stop background server
    -V, --version         Prints version information
    -z, --zero-stats      zero statistics counters

OPTIONS:
        --package-toolchain <executable> <out>    package toolchain for distributed compilation
        --stats-format <stats-format>
            set output format of statistics [default: text]  [possible values: text, json]


ARGS:
    <cmd>...    

Enabled features:
    S3:        true
    Redis:     true
    Memcached: true
    GCS:       true
    Azure:     true
```
</details>

So it seems that we should be able to get the same information from `sccache` by just updating the commands to use `sccache` instead of `ccache` and changing the `grep` arguments. Does that sound accurate?

**Comment by ajschmidt8** [comment]
> pre-cache C++ build time ([link to log](https://gpuci.gpuopenanalytics.com/job/rapidsai/job/gpuci/job/cudf/job/prb/job/cudf-cpu-cuda-build/7484/CUDA=11.5/console)): 1:34:39.5
> 
post-cache C++ build time ([link to log](https://gpuci.gpuopenanalytics.com/job/rapidsai/job/gpuci/job/cudf/job/prb/job/cudf-cpu-cuda-build/7504/CUDA=11.5/consoleFull)): 0:05:36.4

image

**Comment by davidwendt** [comment]
> So it seems that we should be able to get the same information from `sccache` by just updating the commands to use `sccache` instead of `ccache` and changing the `grep` arguments. Does that sound accurate?

I'm not sure. Are the cache-hits from a local cache for the build? That is, are the sscache statistics from the server's cache or are the statistics local to the current build?

**Comment by ajschmidt8** [comment]
> > So it seems that we should be able to get the same information from `sccache` by just updating the commands to use `sccache` instead of `ccache` and changing the `grep` arguments. Does that sound accurate?
> 
> I'm not sure. Are the cache-hits from a local cache for the build? That is, are the sscache statistics from the server's cache or are the statistics local to the current build?

The stats are local to the current build. `sccache` has the capability to set up a shared server, but in the absence of one, it spins up its own for each local build. The short article below talks about this for reference.


https://github.com/mozilla/sccache/blob/master/docs/Jenkins.md

**Comment by ajschmidt8** [comment]
@davidwendt, I pushed commit ac47436 with the changes we discussed. Please review when you have a minute.

**Comment by davidwendt** [comment]
The `cache hit rate` looks a little strange in the build metrics report here
https://gpuci.gpuopenanalytics.com/job/rapidsai/job/gpuci/job/cudf/job/prb/job/cudf-cpu-cuda-build/CUDA=11.5/7537/Build_20Metrics_20Report/

**Comment by ajschmidt8** [comment]
> The `cache hit rate` looks a little strange in the build metrics report here https://gpuci.gpuopenanalytics.com/job/rapidsai/job/gpuci/job/cudf/job/prb/job/cudf-cpu-cuda-build/CUDA=11.5/7537/Build_20Metrics_20Report/

yeah, interesting. I'll debug.

**Comment by ajschmidt8** [comment]
> The `cache hit rate` looks a little strange in the build metrics report here https://gpuci.gpuopenanalytics.com/job/rapidsai/job/gpuci/job/cudf/job/prb/job/cudf-cpu-cuda-build/CUDA=11.5/7537/Build_20Metrics_20Report/

Just pushed an update. As it turns out, `sccache -s` outputs different fields based on whether or not there is any data. So my original `grep` pattern didn't work.

<details>
<summary>
"sccache -s" with stats
</summary>

```
Compile requests                     610
Compile requests executed            610
Cache hits                           609
Cache hits (C/C++)                   284
Cache hits (CUDA)                    325
Cache misses                           1
Cache misses (CUDA)                    1
Cache timeouts                         0
Cache read errors                      0
Forced recaches                        0
Cache write errors                     0
Compilation failures                   0
Cache errors                           0
Non-cacheable compilations             0
Non-cacheable calls                    0
Non-compilation calls                  0
Unsupported compiler calls             0
Average cache write                0.182 s
Average cache read miss           66.172 s
Average cache read hit             0.153 s
Failed distributed compilations        0
Cache location                  S3, bucket: Bucket(name=rapids-sccache, base_url=http://rapids-sccache.s3-us-west-2.amazonaws.com/)

```
</details>

<details>
<summary>
"sccache -s" with no stats
</summary>

```
Compile requests                      0
Compile requests executed             0
Cache hits                            0
Cache misses                          0
Cache timeouts                        0
Cache read errors                     0
Forced recaches                       0
Cache write errors                    0
Compilation failures                  0
Cache errors                          0
Non-cacheable compilations            0
Non-cacheable calls                   0
Non-compilation calls                 0
Unsupported compiler calls            0
Average cache write               0.000 s
Average cache read miss           0.000 s
Average cache read hit            0.000 s
Failed distributed compilations       0
Cache location                  S3, bucket: Bucket(name=rapids-sccache, base_url=http://rapids-sccache.s3-us-west-2.amazonaws.com/)
```
</details>

**Comment by davidwendt** [comment]
Ok. This looks great: https://gpuci.gpuopenanalytics.com/job/rapidsai/job/gpuci/job/cudf/job/prb/job/cudf-cpu-cuda-build/CUDA=11.5/7548/Build_20Metrics_20Report/

As an experiment, you can temporarily remove the word `static` from this line https://github.com/rapidsai/cudf/blob/2c6b0dac61a6671642bb5b076e910e20e2bdd1b6/cpp/include/cudf/types.hpp#L343 and push a commit to this PR. This change causes a recompile of almost everything. We should see a cache-hit rate of less than 10%.

**Comment by ajschmidt8** [comment]
> Ok. This looks great: https://gpuci.gpuopenanalytics.com/job/rapidsai/job/gpuci/job/cudf/job/prb/job/cudf-cpu-cuda-build/CUDA=11.5/7548/Build_20Metrics_20Report/
> 
> As an experiment, you can temporarily remove the word `static` from this line
> 
> and push a commit to this PR. This change causes a recompile of almost everything. We should see a cache-hit rate of less than 10%.

done in d3dac36

**Comment by ajschmidt8** [comment]
PR is ready for review, but we'll wait to merge until all the other PRs are confirmed working as well.

**Review by raydouglass — APPROVED** [review]

**Review by davidwendt — APPROVED** [review]

**Comment by ajschmidt8** [comment]
@gpucibot merge

**Pull request merged**
