### PR TITLE
Remove deprecated Index methods from Frame

### PR DESCRIPTION
**Pull request by vyasr**
This PR moves a number of methods from Frame to IndexedFrame that are no longer supported for Index objects. The one holdout is `Frame.replace`, which is also deprecated for Index but is used internally by Index methods in one place. In order to make this PR as simple to review as possible, I have omitted that function here. All changes in this PR are trivial moves of code aside from the deletions of the warnings.

### CODE REVIEW

**Review by bdice — APPROVED** [review]
LGTM. I verified that this is a trivial move of the existing code into classes where it fits better. I am leaving this review pretty minimal since the sole purpose of this PR is to clean up where methods are defined -- I'm leaving any improvements to those methods out of the scope of this PR. Thanks @vyasr for this!

**Comment by vyasr** [comment]
Blocked on #11070

**Comment by vyasr** [comment]
rerun tests

**Comment by vyasr** [comment]
@gpucibot merge

**Pull request merged**
