### PR TITLE
[REVIEW] fix gcc-9 compilation error

### PR DESCRIPTION
**Pull request by rongou**
The `std::move()` call prevents copy elision:
```
/home/rou/src/cudf/cpp/src/dictionary/remove_keys.cu: In instantiation of ‘std::unique_ptr<cudf::column> cudf::dictionary::detail::_GLOBAL__N__46_tmpxft_00004b4a_00000000_7_remove_keys_cpp1_ii_8f7b9da6::remove_keys_fn(const cudf::dictionary_column_view&, KeysKeeper, rmm::mr::device_memory_resource*, cudaStream_t) [with KeysKeeper = __nv_dl_wrapper_t<__nv_dl_tag<std::unique_ptr<cudf::column> (*)(const cudf::dictionary_column_view&, const cudf::column_view&, rmm::mr::device_memory_resource*, CUstream_st*), cudf::dictionary::detail::remove_keys, 1>, const bool*>; cudaStream_t = CUstream_st*]’:
/home/rou/src/cudf/cpp/src/dictionary/remove_keys.cu:160:65:   required from here
/home/rou/src/cudf/cpp/src/dictionary/remove_keys.cu:83:27: error: moving a local object in a return statement prevents copy elision [-Werror=pessimizing-move]
   83 |       return std::move(positions);
      |                           ^
/home/rou/src/cudf/cpp/src/dictionary/remove_keys.cu:83:27: note: remove ‘std::move’ call
/home/rou/src/cudf/cpp/src/dictionary/remove_keys.cu: In instantiation of ‘std::unique_ptr<cudf::column> cudf::dictionary::detail::_GLOBAL__N__46_tmpxft_00004b4a_00000000_7_remove_keys_cpp1_ii_8f7b9da6::remove_keys_fn(const cudf::dictionary_column_view&, KeysKeeper, rmm::mr::device_memory_resource*, cudaStream_t) [with KeysKeeper = __nv_dl_wrapper_t<__nv_dl_tag<std::unique_ptr<cudf::column> (*)(const cudf::dictionary_column_view&, rmm::mr::device_memory_resource*, CUstream_st*), cudf::dictionary::detail::remove_unused_keys, 1>, const bool*>; cudaStream_t = CUstream_st*]’:
/home/rou/src/cudf/cpp/src/dictionary/remove_keys.cu:186:65:   required from here
/home/rou/src/cudf/cpp/src/dictionary/remove_keys.cu:83:27: error: moving a local object in a return statement prevents copy elision [-Werror=pessimizing-move]
/home/rou/src/cudf/cpp/src/dictionary/remove_keys.cu:83:27: note: remove ‘std::move’ call
cc1plus: all warnings being treated as errors
CMakeFiles/cudf.dir/build.make:2668: recipe for target 'CMakeFiles/cudf.dir/src/dictionary/remove_keys.cu.o' failed
make[2]: *** [CMakeFiles/cudf.dir/src/dictionary/remove_keys.cu.o] Error 1
CMakeFiles/Makefile2:230: recipe for target 'CMakeFiles/cudf.dir/all' failed
make[1]: *** [CMakeFiles/cudf.dir/all] Error 2
Makefile:148: recipe for target 'all' failed
make: *** [all] Error 2
```

@davidwendt @jrhemstad @kkraus14

### CODE REVIEW

**Comment by GPUtester** [comment]
Can one of the admins verify this patch?

**Comment by GPUtester** [comment]
Please update the changelog in order to start CI tests.

View the gpuCI docs [here](https://docs.rapids.ai/gpuci#open-pr-or-update-pr).

**Comment by devavret** [comment]
Github shows only 1 line changed. And that's the changelog. Where's the code?

**Review by davidwendt — APPROVED** [review]

**Review by karthikeyann — APPROVED** [review]

**Review by devavret — APPROVED** [review]

**Comment by harrism** [comment]
rerun tests

**Comment by galipremsagar** [comment]
rerun tests

**Pull request merged**
