### PR TITLE
Fix default parameter values of `write_csv` and `write_parquet`

### LINKED ISSUE #6671: [BUG] CSV writer parameter rows_per_chunk has a bad default value
Current default value for `rows_per_chunk` parameter of the CSV writer is 8, which means that the input table is by default broken into many small slices that are written out sequentially. This reduces the performance by an order on magnitude in some cases.

In Python layer, the default is the number of rows (i.e. write table out in a single pass). We can follow this by setting `rows_per_chunk` in the constructor of `csv_writer_options_builder`, where the table size is known.

Note: All `write_csv` tests explicitly set `rows_per_chunk` to 1 (internally changed to 8). We should instead cover different values.

### PR DESCRIPTION
**Pull request by vuule**
Fixes #6671, #6851

- Set the `rows_per_chunk` in `csv_writer_options` to the size of the input table.
- Change `rows_per_chunk` type to `size_type` (used for number of rows).
- Set the default compression in `to_parquet`/`write_parquet` to "snappy".

### CODE REVIEW

**Comment by vuule** [comment]
rerun tests

**Review by kkraus14 — APPROVED** [review]
python lgtm

**Review by codereport — APPROVED** [review]
lgtm

**Review by rgsl888prabhu — APPROVED** [review]

**Review by harrism — APPROVED** [review]

**Comment by vuule** [comment]
Rerun tests

**Pull request merged**
