### PR TITLE
[REVIEW] Filtered reading with join predicates

### PR DESCRIPTION
**Pull request by calebwin**
This PR introduces a `joins` parameter to `read_parquet` and `read_orc` to allow for GPU-accelerated statistics-based filtering of row groups and stripes on joins to avoid I/O.

Joins are expressed as follows-
```python
In [1]: fname = "orc/concatenated_yellow_tripdata_2015-01_08_head_60M.orc"

In [2]: df = cudf.read_orc(fname).query("tpep_pickup_datetime == @dt")

In [3]: %timeit cudf.read_orc(fname)
1.44 s ± 12.9 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

In [12]: %timeit cudf.read_orc(fname,joins=[("tpep_pickup_datetime","==",df["tpep_pickup_datetime"])])
47.1 ms ± 4.19 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
```

Overhead seems insignificant from some simple testing-
```python
In [1]: fname = "parquet/concatenated_yellow_tripdata_2015-01_08_head_85M.parquet"

In [9]: %timeit df=cudf.read_parquet(fname)
1.23 s ± 82.3 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

In [8]: %timeit cudf.read_parquet(fname,joins=[("tpep_pickup_datetime","==",df["tpep_pickup_datetime"])])
1.2 s ± 4.94 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```

There are 2 parts of this implementation of join-based filtering for Parquet, ORC.
1. `joins` are incorporated into `filters` through the gathering of min-max statistics of data to be joined with and generation of filtering predicates.
2. row-group/stripe statistics are loaded onto the GPU and checked against each row of the data being joined with to determine which row groups/stripes can be filtered out. This was implemented using a Numba kernel with the operation being parallelized across both row groups/stripes and rows of the data being joined with.

This is also integrated into Dask cuDF for both Parquet and ORC. Both Parquet and ORC leverage the incorporation of `joins` into `filters`. The implementation for ORC additionally downloads data to be joined with onto the client node and executes the above Numba kernel to filter out stripes of the dataset being read in.

The relevant files are-
- `python/cudf/cudf/io/parquet.py`, `python/cudf/cudf/io/orc.py` for usage in Parquet and ORC reader functions
- `python/dask_cudf/dask_cudf/io/orc.py` for integration with dask-cudf for ORC
- `python/cudf/cudf/tests/test_parquet.py`, `python/cudf/cudf/tests/test_orc.py` for tests
- `python/cudf/cudf/utils/filterutils.py` for join-based filtering kernel (using Numba)
- `python/cudf/cudf/utils/ioutils.py` for docs

Depends on #6116

### CODE REVIEW

**Comment by GPUtester** [comment]
Please update the changelog in order to start CI tests.

View the gpuCI docs [here](https://docs.rapids.ai/gpuci#open-pr-or-update-pr).

**Review by mike-wendt — APPROVED** [review]
Approved for changes in our codeowners files

**Comment by calebwin** [comment]
I'm changing this to WIP so that I can finish a few improvements w.r.t operator support.

**Comment by calebwin** [comment]
My main concern right now is with integration into Dask cuDF. Currently, you can specify joins in a call to `dask_cudf.read_orc` and the filtering will be done on the client.
```python
In [6]: df_filtered = dask_cudf.read_orc("python/cudf/cudf/tests/data/orc/concatenated_yellow_tripdata_2015-01_08_head_60M.orc",joins=[("tpep_pickup_date
   ...: time","==",df["tpep_pickup_datetime"].compute())])                                                                                               

In [7]: df_filtered                                                                                                                                      
Out[7]: <dask_cudf.DataFrame | 1 tasks | 1 npartitions>

In [12]: len(df_filtered)                                                                                                                                
Out[12]: 1315840
```
But what I'm concerned about is the `df["tpep_pickup_datetime"].compute()` - is it okay to assume that the data being joined with is small enough to cheaply transfer to and fit on client as a `cudf.DataFrame`? or should we support calling the `_apply_operator` Numba kernel that this PR has on distributed partitions to avoid data movement and support joins with larger, low-entropy data. I'll look more into this soon.

cc @rjzamora @VibhuJawa

**Comment by VibhuJawa** [comment]
is it okay to assume that the data being joined with is small enough to cheaply transfer to and fit on client as a `cudf.DataFrame`? 

For a lot of cases, I think this will a very safe assumption to make.  I think we can start with this for now and then move into more complex use cases as we hit them. 

CC: @ayushdg  and @beckernick  , who may have opinions on this too.

**Comment by harrism** [comment]
@calebwin @kkraus14 should this move to 0.17?

**Comment by jakirkham** [comment]
JFYI Caleb's internship ended. So I think we are on our own in terms of figuring out what to do next. FWIW bumping it to the next release sounds reasonable to me.

cc @quasiben (in case you have thoughts here)

**Comment by kkraus14** [comment]
pushed to 0.18

**Comment by GPUtester** [comment]
Can one of the admins verify this patch?

**Comment by nvdbaranec** [comment]
What's the deal with this PR?  Is it time to put it out to pasture?  @kkraus14

**Comment by kkraus14** [comment]
> What's the deal with this PR? Is it time to put it out to pasture? @kkraus14

Caleb was an intern with us in the summer of 2020 and spent time looking at enabling passing different predicates into different IO read functions in Python, with the intention of pushing things down to C++ afterwards.

We ran out of time to fully go through this PR and reviewing / updating it has fallen through the cracks. Would suggest we leave this open until after cuIO refactoring is done and then re-evaluate what we want to do then.

**Comment by karthikeyann** [comment]
Converting to draft and moving to 0.19

**Comment by karthikeyann** [comment]
cuio code refactor might have changed the code substantially and this PR needs to go through major change.
@calebwin will this work be merged to cudf?

**Comment by harrism** [comment]
It's been over a year. I think we can close and reopen if needed.

**Pull request closed without merging**
