### PR TITLE
[REVIEW] Add include guards _around_ inclusions of `NVStrings.h`

### PR DESCRIPTION
**Pull request by eyalroz**
This fixes bug #1402.

### CODE REVIEW

**Comment by kkraus14** [comment]
@eyalroz @davidwendt is this something that should be handled within NVStrings instead?

**Comment by eyalroz** [comment]
> @eyalroz @davidwendt is this something that should be handled within NVStrings instead?

Yes. But right now it isn't.

**Comment by eyalroz** [comment]
@davidwendt : Yes, that's true. I don't mind either way, I just generally assume third-party library version dependencies are out of my control.

**Comment by kkraus14** [comment]
> @davidwendt : Yes, that's true. I don't mind either way, I just generally assume third-party library version dependencies are out of my control.

NVStrings is not a third party library, it's another open source library that's a part of RAPIDS similar to cudf.

**Comment by kkraus14** [comment]
I'm going to close this and raise an issue that we should bump the dependency of NVStrings to v0.7.

**Pull request closed without merging**
