### PR TITLE
[REVIEW] Series covariance and Pearson correlation

### PR DESCRIPTION
**Pull request by beckernick**
Summary of Changes
- Adds Series-level covariance and Pearson correlation as a stopgap until they are directly supported via libcuDF
~- Adds DataFrame-level covariance and Pearson correlation via CuPy.~

A future libcuDF-only version will likely be able to better support DataFrame level covariance and correlation natively. Currently, in Python, we can't do binary ops between DataFrames and Series (#2166) , nor can we do do efficient transposes. We could work around the binary op issue, but we need to transpose to leverage the matrix form of the covariance formula.

~As a result, we'd need to independently calculate each covariance value. Casting nans to nulls and dropping nulls is necessary for the math, but adds a few milliseconds per `cov/corr` call. However, since just the covariance math itself takes 3-5 ms, we would get a significant quadratic explosion if `ncols > 10-30` no matter what if we don't use the matrix formula.~

~Instead, we can use CuPy for now.~

### CODE REVIEW

**Comment by beckernick** [comment]
Dask versions of any `corr/cov` methods will be blocked until we:

- [ ] Create an `astype` DataFrame method (#2195 ) and support the `copy` parameter in it
- [ ] Create a Series method for `notnull`. This is an alias of `notna`, so it should be trivial.
- [ ] Finish a `df.values` implementation (#1824 )

**Comment by beckernick** [comment]
This is now ready for review

**Comment by beckernick** [comment]
Updating to remove dataframe implementations for now after discussion with @kkraus14

**Comment by kkraus14** [comment]
@beckernick approved, suggest you open an issue for a libcudf implementation if you haven't already

**Comment by beckernick** [comment]
Will update the existing issue to reflect libcuDF implementation

**Comment by kkraus14** [comment]
```
____________ test_array_func_missing_cudf_series[<lambda>0-np_ar0] _____________

np_ar = array([0.85203364, 0.37148003, 0.24277552, 0.6316116 , 0.8227346 ,
       0.13154083, 0.59179169, 0.68867617, 0.682033...48, 0.30085795, 0.55301161, 0.92713472, 0.34632781,
       0.31003306, 0.79814686, 0.76295427, 0.04999537, 0.89813435])
func = <function <lambda> at 0x7ff21fcabae8>

    @pytest.mark.skipif(missing_arrfunc_cond, reason=missing_arrfunc_reason)
    @pytest.mark.parametrize("np_ar", [np.random.random(100)])
    @pytest.mark.parametrize(
        "func",
        [
            lambda x: np.cov(x, x),
            lambda x: np.dot(x, x),
            lambda x: np.linalg.norm(x),
        ],
    )
    def test_array_func_missing_cudf_series(np_ar, func):
        cudf_ser = cudf.Series(np_ar)
        with pytest.raises(TypeError):
>           func(cudf_ser)
E           Failed: DID NOT RAISE <class 'TypeError'>

cudf/tests/test_array_function.py:53: Failed
```

**Comment by beckernick** [comment]
rerun tests

**Comment by kkraus14** [comment]
@beckernick You need to set the environment variable: `export NUMPY_EXPERIMENTAL_ARRAY_FUNCTION=1`, I'm guessing it's because you're implementing `cov` that it's working for numpy `__array_function__` `np.cov`

**Comment by beckernick** [comment]
Yep, you're right. Will update the tests

**Comment by kkraus14** [comment]
rerun tests

**Comment by kkraus14** [comment]
rerun tests

**Pull request merged**
