### PR TITLE
Make Doxygen comments formatting consistent

### PR DESCRIPTION
**Pull request by vuule**
Making this PR since wrong formatting keeps getting propagated in new PRs and (sometimes) corrected in code review.

Changes:

- Ironed out the formatting of Doxygen comments to match the guidelines. 
- Removed the outdated file with formatting examples.

### CODE REVIEW

**Review by davidwendt — APPROVED** [review]
Wow.

**Review by rgsl888prabhu — COMMENTED** [review]
There are couple of files where copyright year needs to be updated, other than that looks good.

**Review by karthikeyann — APPROVED** [review]
Looks good. 

check these if these are left out intentionally. (these are not doxygen comments. just cpp comments)
cpp/benchmarks/iterator/iterator_benchmark.cu for "---"
cpp/include/cudf_test/type_list_utilities.hpp for "---"
src/io/comp/debrotli.cu for "**/"

**Comment by vuule** [comment]
This was a bad idea.

**Comment by vuule** [comment]
> check these if these are left out intentionally. (these are not doxygen comments. just cpp comments)
> cpp/benchmarks/iterator/iterator_benchmark.cu for "---"
> cpp/include/cudf_test/type_list_utilities.hpp for "---"
> src/io/comp/debrotli.cu for "**/"

Did not change the "lines" unrelated to doxygen comments, would prefer to check with authors before removing them. 
Fixed up debrotli, thanks for pointing it out.

**Pull request merged**
