### PR TITLE
Change build.sh to find C++ library by default and avoid shadowing CMAKE_ARGS

### PR DESCRIPTION
**Pull request by vyasr**
#10919 changed the Python build system to build its own internal copy of libcudf when invoked directly. It also modified our build.sh script (and associated CI scripts) accordingly so that everywhere that should be reusing a C++ build for a Python build would do so via CMake. This PR makes that behavior the default in build.sh, so any builds of the Python library using build.sh will revert to the prior behavior of searching for a C++ library and failing if one doesn't already exist on the path. Users can still provide the appropriate CMake arguments to the build.sh invocation to make it build libcudf within cuDF Python if they so desire.

Additionally, this PR avoids shadowing the `CMAKE_ARGS` environment variable in build.sh, which is important for conda-forge compatibility.

### CODE REVIEW

**Review by bdice — COMMENTED** [review]
@vyasr Can you confirm / paste a snippet of the output from the failure mode, when `cudf` is requested but `libcudf` has not yet been built?

**Comment by vyasr** [comment]
> @vyasr Can you paste a snippet of the output from the failure mode, when `cudf` is requested but `libcudf` has not yet been built?

I don't currently have a working environment but I can post one when I do unless someone beats me to it.

**Comment by vyasr** [comment]
@bdice here you go. It's a typical `find_package` error:
```
CMake Error at CMakeLists.txt:37 (find_package):
By not providing "Findcudf.cmake" in CMAKE_MODULE_PATH this project has 
asked CMake to find a package configuration file provided by "cudf", but 
CMake did not find one.

Could not find a package configuration file provided by "cudf" (requested
        version 22.08.00) with any of the following names:

cudfConfig.cmake
cudf-config.cmake

Add the installation prefix of "cudf" to CMAKE_PREFIX_PATH or set 
"cudf_DIR" to a directory containing one of the above files.  If "cudf"
provides a separate development package or SDK, be sure it has been
installed.
```

**Comment by galipremsagar** [comment]
rerun tests

**Review by ajschmidt8 — APPROVED** [review]

**Comment by vyasr** [comment]
Issue is resolved in https://github.com/rapidsai/cuspatial/pull/543 but I'm waiting for some follow-ups to confirm that there's no problem with the solution.

**Comment by galipremsagar** [comment]
@gpucibot merge

**Pull request merged**
