### PR TITLE
Remove applying nvbench that doesn't exist in 23.08

### PR DESCRIPTION
**Pull request by robertmaynard**
NVBench has integrated the `public_fmt_dep_in_conda` fixes. So for 23.08 rapids-cmake dropped the patch and moved to newest nvbench https://github.com/rapidsai/rapids-cmake/pull/417

## Checklist
- [x] I am familiar with the [Contributing Guidelines](https://github.com/rapidsai/cudf/blob/HEAD/CONTRIBUTING.md).
- [x] New or existing tests cover these changes.
- [x] The documentation is up to date with these changes.

### CODE REVIEW

**Review by bdice — APPROVED** [review]
Yes, this should fix some things I saw recently! 😄

**Comment by bdice** [comment]
I see style checks are failing. I'll open a PR to fix that.

**Comment by jakirkham** [comment]
Thanks Rob and Bradley! 🙏

**Pull request merged**
