### PR TITLE
Convert device_memory_resource pointers to async_resource_ref

### PR DESCRIPTION
**Pull request by harrism**
## Description
This (for now) is just an example of conversion of some libcudf APIs to take `cuda::mr::async_resource_ref<cuda::mr::device_accessible>` instead of a pointer to a `rmm::mr::device_memory_resource`.

## Checklist
- [x] I am familiar with the [Contributing Guidelines](https://github.com/rapidsai/cudf/blob/HEAD/CONTRIBUTING.md).
- [X] New or existing tests cover these changes.
- [X] The documentation is up to date with these changes.

### CODE REVIEW

**Comment by davidwendt** [comment]
Perhaps we can create something like the following in a libcudf headers (`e.g. cudf/include/utilties/memory_resource.hpp`)?
```
using cudf_resource_ref = cuda::mr::async_resource_ref<cuda::mr::device_accessible>;
```
And use that instead. Maybe makes this kind of change a little more future-proof.

**Comment by harrism** [comment]
@davidwendt yes planning on it. This PR is just a draft to show @bdice what the changes look like at the API level.

**Comment by harrism** [comment]
@davidwendt added the alias. It will be interesting to see how much compile time this adds, since it adds a CCCL include to types.hpp. It definitely gave me pause...

**Comment by davidwendt** [comment]
> @davidwendt added the alias. It will be interesting to see how much compile time this adds, since it adds a CCCL include to types.hpp. It definitely gave me pause...

I certainly would like to avoid adding includes to `types.hpp` if possible.

**Comment by harrism** [comment]
> I certainly would like to avoid adding includes to types.hpp if possible.

What about creating a new header? It will need to be included from nearly every file in libcudf though...

**Comment by davidwendt** [comment]
> > I certainly would like to avoid adding includes to types.hpp if possible.
> 
> What about creating a new header? It will need to be included from nearly every file in libcudf though...

Reference: https://github.com/rapidsai/cudf/pull/14873#issuecomment-1909062759
I'm just not sure it belongs in `types.hpp`. 
I don't want to put it in `types.hpp` just because it is already included everywhere.
Nearly everywhere is not the same as everywhere (e.g. it is not needed in kernel defintions).

**Comment by harrism** [comment]
Fair enough. @bdice  suggested types.hpp.

**Comment by bdice** [comment]
I hadn't considered the impact on compile time from `types.hpp`. I'd support a new header, like we have done for [default_stream.hpp](https://github.com/rapidsai/cudf/blob/branch-24.02/cpp/include/cudf/utilities/default_stream.hpp). Is there any chance we'd want to define this in RMM? It seems like a declaration of a device-accessible memory resource would be reused heavily in other RAPIDS libraries.

**Comment by harrism** [comment]
Possibly. At least until more properties are created and used.

**Comment by harrism** [comment]
This has been updated to use the new `rmm::device_async_resource_ref` alias.

**Pull request closed without merging**
