### PR TITLE
Update to use rapids-export(COMPONENTS) feature.

### LINKED ISSUE #12976: [BUG] Cannot find GTest::gmock GTest::gtest after installing libcudf
**Describe the bug**
The RAPIDS Accelerator for Apache Spark has a JNI layer which builds a static version of libcudf and has its own native tests.  In the past, we could additionally pull in the testing components of libcudf via:
```
rapids_find_package(cudf REQUIRED COMPONENTS testing)
```

But recently this has been failing with:
```
00:58:12  [INFO]      [exec] CMake Error at /home/jenkins/agent/workspace/jenkins-spark-rapids-jni_nightly-dev-377-cuda11/target/cmake-build/_deps/rapids-cmake-src/rapids-cmake/find/package.cmake:125 (find_package):
00:58:12  [INFO]      [exec]   Found package configuration file:
00:58:12  [INFO]      [exec] 
00:58:12  [INFO]      [exec]     /home/jenkins/agent/workspace/jenkins-spark-rapids-jni_nightly-dev-377-cuda11/target/libcudf-install/lib64/cmake/cudf/cudf-config.cmake
00:58:12  [INFO]      [exec] 
00:58:12  [INFO]      [exec]   but it set cudf_FOUND to FALSE so package "cudf" is considered to be NOT
00:58:12  [INFO]      [exec]   FOUND.  Reason given by package:
00:58:12  [INFO]      [exec] 
00:58:12  [INFO]      [exec]   The following imported targets are referenced, but are missing:
00:58:12  [INFO]      [exec]   GTest::gmock GTest::gtest
00:58:12  [INFO]      [exec] 
00:58:12  [INFO]      [exec] Call Stack (most recent call first):
00:58:12  [INFO]      [exec]   CMakeLists.txt:104 (rapids_find_package)
```
**Steps/Code to reproduce bug**
Build the https://github.com/NVIDIA/spark-rapids-jni repository via:
```
build/build-in-docker clean package -DBUILD_TESTS=ON
```

I have not verified this, but it is probably reproducible without the full spark-rapids-jni build environment by building libcudf via:
```
cmake --build build --target install -DBUILD_SHARED_LIBS=OFF -DCUDA_STATIC_RUNTIME=ON -DCUDF_ENABLE_ARROW_S3=OFF -DCUDF_ENABLE_ARROW_PARQUET=ON -DCUDF_USE_ARROW_STATIC=ON -DCUDF_USE_PER_THREAD_DEFAULT_STREAM=ON -DUSE_GDS=ON
```
and then try to pull in the libcudf dependency via the `rapids_find_package` line mentioned above.

**Expected behavior**
Build does not fail when pulling in libcudf testing components

### PR DESCRIPTION
**Pull request by robertmaynard**
## Description
Not only does this simplify the `cudf` CMakeLists.txt it removes a bug where we failed to install the testing dependencies file since it relied on internal rapids-cmake details.

Expected to fix the following:

- cuspatial issues with not finding GTest targets
- [spark-rapids-jni](https://github.com/NVIDIA/spark-rapids-jni) issues with not finding GTest targets

Fixes #12976 

## Checklist
- [x] I am familiar with the [Contributing Guidelines](https://github.com/rapidsai/cudf/blob/HEAD/CONTRIBUTING.md).
- [x] New or existing tests cover these changes.
- [x] The documentation is up to date with these changes.

### CODE REVIEW

**Review by bdice — APPROVED** [review]

**Review by hyperbolic2346 — APPROVED** [review]

**Comment by vyasr** [comment]
Is the export name being set here clashing with the "nice" export name in rapids-cmake, leading to trying to install an export set that doesn't actually exist?

**Comment by robertmaynard** [comment]
> Is the export name being set here clashing with the "nice" export name in rapids-cmake, leading to trying to install an export set that doesn't actually exist?

Maybe? What failures are you looking at. I can't see what is going wrong in the wheel builds

**Comment by vyasr** [comment]
It's failing with 
```
    -- Configuring done (22.5s)
    CMake Error: INSTALL(EXPORT) given unknown export "cudf-testing-exports"
    -- Generating done (0.2s)
```
(you have to expand some in-text dropdowns or open the raw log).

**Comment by robertmaynard** [comment]
> It's failing with 
> 
> ```
> 
>     -- Configuring done (22.5s)
> 
>     CMake Error: INSTALL(EXPORT) given unknown export "cudf-testing-exports"
> 
>     -- Generating done (0.2s)
> 
> ```
> 
> (you have to expand some in-text dropdowns or open the raw log).

The "nice" name is only used for the files rapids-CMake generates. 

What this looks like is that for some builds we disable cudf test util from being built, but we are always trying to export it. 
We will need to update the PR to only add the COMPONENTS arguments to rapids_export when cudf test util is being built.

**Comment by vyasr** [comment]
Good catch. Pushed the fix.

**Review by jlowe — APPROVED** [review]
Verified that pulling in this fix resolves #12976.

**Pull request merged**
