### PR TITLE
[REVIEW] Add comparison binaryops to Datetime Series / Index / Column

### LINKED ISSUE #553: [BUG] Support comparision with Pandas timestamp objects
**Describe the bug**

cudf Index objects do not compare nicely against pandas TimeStamp objects.  

This might also be extended to strings, or any other object that Pandas can convert into Pandas TimeStamp objects.

**Steps/Code to reproduce bug**

```python
import pandas as pd
s = pd.util.testing.makeTimeSeries()

s.head()
# 2000-01-03    0.684674
# 2000-01-04    0.671145
# 2000-01-05   -0.876270
# 2000-01-06    1.493458
# 2000-01-07   -0.488496
# Freq: B, dtype: float64

import cudf
g = cudf.Series.from_pandas(s)

ts = s.index[5]  # one pandas timestamp
g.index > ts
```

```python-traceback
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-8-34cd7939f90c> in <module>
----> 1 g.index > ts

pandas/_libs/tslib.pyx in pandas._libs.tslib._Timestamp.__richcmp__ (pandas/_libs/tslib.c:20281)()

TypeError: Cannot compare type 'Timestamp' with type 'GenericIndex'
```

**Expected behavior**

Ideally the `GenericIndex` comparison operators would identify pandas TimeStamp objects and convert them into some other object appropriate for comparison.

### LINKED ISSUE #948: [FEA] Add binary operations to 'DatetimeColumn' object
**Is your feature request related to a problem? Please describe.**
I am trying to calculate the timestep by substracting end_date and start_date.

Please, find below the code and the error raised:

screenshot 2019-02-14 at 14 35 39

**Describe the solution you'd like**
To be able to substract two columns of type 'numpy.datetime64'.

**Describe alternatives you've considered**
None yet.

**Additional context**
Add any other context, code examples, or references to existing implementations about the feature request here.

### PR DESCRIPTION
**Pull request by kkraus14**
Fixes #553
Fixes #948

### CODE REVIEW

**Comment by miguelangel** [comment]
Hi,

I have just downloaded the latest dev container version of RAPIDS, pip uninstall cudf, and git clone the latest branch (0.6) and submodules, and installed it.

When I try to execute the following code, the same error as detailed in https://github.com/rapidsai/cudf/issues/948 shows up:

2019-02-20 10_18_17-jupyterlab

Could you please double check?

Thank you!
Miguel

**Comment by kkraus14** [comment]
@miguelangel we don't support timedeltas still so there's logical type for us to return with this operation. For now you should continue typecasting datetimes as int64 objects for doing subtraction binaryops, but things like comparisons that return a boolean should work as expected.

**Comment by miguelangel** [comment]
Hi @kkraus14,

I understand. Thank you!

**Comment by devavret** [comment]
this added a test failure in [`test_binops.py`](https://github.com/rapidsai/cudf/commit/5b01fe08743fed94c3fdf59beb4a154afa1f0618#diff-0357306a3e88eab6186c19973cfeb208R73) because binary ops don't yet support `int16`

**Pull request merged**
