### PR TITLE
Merge branch-23.12 into branch-24.02

### PR DESCRIPTION
**Pull request by galipremsagar**
## Description
This PR resolves conflicts in https://github.com/rapidsai/cudf/pull/14406
## Checklist
- [ ] I am familiar with the [Contributing Guidelines](https://github.com/rapidsai/cudf/blob/HEAD/CONTRIBUTING.md).
- [ ] New or existing tests cover these changes.
- [ ] The documentation is up to date with these changes.

### CODE REVIEW

**Review by raydouglass — APPROVED** [review]

**Comment by raydouglass** [comment]
Marking with `DO NOT MERGE` since this must be manually merged with a merge commit.

**Comment by vyasr** [comment]
We need kvikio's PR to merge first so that we can get kvikio builds up for CI to run here.

**Comment by vyasr** [comment]
There's an error in this forward merger in the cudf-kafka CMakeLists.txt. I'm not sure if that's the only issue, so I'm going to try and do another version of the forward merge myself then diff against this PR to verify.

**Comment by vyasr** [comment]
@bdice wants to make the PR, so I'm just going to verify that I see the differences I expect when he's done.

**Comment by galipremsagar** [comment]
closing for https://github.com/rapidsai/cudf/pull/14422

**Comment by vyasr** [comment]
For the record, I diffed the two PR branches and @bdice's has the change I was expecting to see:
```
(rapids) rapids@compose:~/cudf/second_workspace$ git diff bdice/branch-24.02-merge-23.12 galipremsagar/branch-24.02-merge-23.12
diff --git a/conda/recipes/custreamz/meta.yaml b/conda/recipes/custreamz/meta.yaml
index 755394e393..b8c5918ea6 100644
--- a/conda/recipes/custreamz/meta.yaml
+++ b/conda/recipes/custreamz/meta.yaml
@@ -45,7 +45,7 @@ requirements:
     - streamz
     - cudf ={{ version }}
     - cudf_kafka ={{ version }}
-    - rapids-dask-dependency ={{ minor_version }}
+    - rapids-dask-dependency ={{ version }}
     - python-confluent-kafka >=1.9.0,<1.10.0a0
     - {{ pin_compatible('cuda-version', max_pin='x', min_pin='x') }}

diff --git a/cpp/libcudf_kafka/CMakeLists.txt b/cpp/libcudf_kafka/CMakeLists.txt
index e31f6bd409..939239b8b2 100644
--- a/cpp/libcudf_kafka/CMakeLists.txt
+++ b/cpp/libcudf_kafka/CMakeLists.txt
@@ -21,7 +21,7 @@ include(rapids-export)
 include(rapids-find)

 project(
-  CUDF_KAFKA
+  CUDA_KAFKA
   VERSION 24.02.00
   LANGUAGES CXX
 )
diff --git a/python/cudf_kafka/CMakeLists.txt b/python/cudf_kafka/CMakeLists.txt
index d55c3fdc07..1e21c87358 100644
--- a/python/cudf_kafka/CMakeLists.txt
+++ b/python/cudf_kafka/CMakeLists.txt
@@ -14,7 +14,7 @@

 cmake_minimum_required(VERSION 3.26.4 FATAL_ERROR)

-set(cudf_kafka_version 23.12.00)
+set(cudf_kafka_version 24.02.00)

 include(../../fetch_rapids.cmake)
```

namely the `CUDA_KAFKA` vs `CUDF_KAFKA` and the `cudf_kafka_version` (the first one is from a separate new PR that isn't in this forward merge but is otherwise unrelated).

**Comment by vyasr** [comment]
Whoops just realized that the `cudf_kafka_version` fix is actually backwards. Each PR has one of the right two. Bradley's fixing that version on his PR now.

**Comment by bdice** [comment]
Done: https://github.com/rapidsai/cudf/pull/14422/commits/e4e69757b340ce45e8ceca53047f079c8b3eb648

**Pull request closed without merging**
