### PR TITLE
[WIP] Sort-based Groupby

### PR DESCRIPTION
**Pull request by aocsa**
List of changes:

- [x] Proposes new C++ API for distributive groupbys in accordance with https://gist.github.com/jrhemstad/717054db12c3755a8c4a7f40647ddfb6
- [ ] Implements new distributive API to perform requested operations in a single pass through the input data
- [x]  Adds a device_table function to perform a set of distributive operations between two rows of two tables.

All the best,

### CODE REVIEW

**Comment by jrhemstad** [comment]
@aocsa can you resolve your conflicts with the main branch so that I can review?

**Comment by harrism** [comment]
Is this ready for review?

**Comment by williamBlazing** [comment]
> Is this ready for review?

No not yet

**Comment by harrism** [comment]
Changing base to branch-0.10. Moving to 0.10 project board.

**Pull request closed without merging**
