### PR TITLE
Rework minhash APIs for deprecation cycle

### PR DESCRIPTION
**Pull request by davidwendt**
## Description
Renames `minhash_permuted()` to `minhash()` and deprecates `minhash_permuted`
Also removes the `word_minhash` APIs deprecated in 24.12.

## Checklist
- [x] I am familiar with the [Contributing Guidelines](https://github.com/rapidsai/cudf/blob/HEAD/CONTRIBUTING.md).
- [x] New or existing tests cover these changes.
- [x] The documentation is up to date with these changes.

### CODE REVIEW

**Review by Matt711 — COMMENTED** [review]
Can you update the python type stubs [here](https://github.com/rapidsai/cudf/blob/branch-25.02/python/pylibcudf/pylibcudf/nvtext/minhash.pyi)?

**Review by bdice — APPROVED** [review]

**Review by Matt711 — APPROVED** [review]
Thanks, approving the python changes.

**Review by vyasr — APPROVED** [review]
It may make sense to mark this PR as breaking since IIUC there are some functions that are now marked as deprecated that were not previously and that will break anyone compiling against cudf with -Werror. Other than that, LGTM.

**Comment by davidwendt** [comment]
Holding off on merging to record some profiles for posterity.

**Pull request merged**
