### PR TITLE
Fixed documentation bug in groupby agg method

### PR DESCRIPTION
**Pull request by ahmet-uyar**
This is a non-functional documentation update.
The output of the c column is missing in the result of the first example in agg method:
python/cudf/cudf/core/groupby/groupby.py
I added the values of the c columns.

### CODE REVIEW

**Comment by GPUtester** [comment]
Can one of the admins verify this patch?

**Comment by GPUtester** [comment]
Can one of the admins verify this patch?

**Comment by kkraus14** [comment]
ok to test

**Review by kkraus14 — APPROVED** [review]

**Comment by kkraus14** [comment]
Thanks for the fix, LGTM!

**Comment by kkraus14** [comment]
@gpucibot merge

**Comment by ahmet-uyar** [comment]
I added another commit with similar non-functional documentation fix in the pipe method. Not sure, whether I should have added it to this pull request.

**Comment by kkraus14** [comment]
That's perfectly fine, thanks for the fixes!

**Comment by galipremsagar** [comment]
rerun tests

**Comment by kkraus14** [comment]
rerun tests

**Comment by galipremsagar** [comment]
rerun tests

**Comment by galipremsagar** [comment]
rerun tests

**Comment by ttnghia** [comment]
Rerun tests.

**Review by ttnghia — APPROVED** [review]

**Comment by galipremsagar** [comment]
@gpucibot merge

**Review by galipremsagar — APPROVED** [review]

**Pull request merged**
