### PR TITLE
[REVIEW] Build GBench Benchmarks in CI

### PR DESCRIPTION
**Pull request by dillon-cullinan**
Adding gbench benchmarks to our build process.

Should the benchmark option in the build process be an option flag like `-b` or a "build target" argument like `bench`?

### CODE REVIEW

**Comment by kkraus14** [comment]
Moving to 0.10.

**Comment by harrism** [comment]
@dillon-cullinan I think it should be a build target.  Currently it's an option like `-DCMAKE_BUILD_BENCHMARKS=ON`, I think.

**Comment by harrism** [comment]
Looking at the conflicting files, it looks like just about everything in this PR is already in branch-0.10 but under the target `benchmarks` rather than `bench`. The only exception is that branch-0.10 ci/gpu/build.sh doesn't clean the `benchmarks` target...

**Comment by harrism** [comment]
@dillon-cullinan is this still needed?

**Comment by harrism** [comment]
Move to 0.12.  Would really like to get this into CI early in 0.12, @dillon-cullinan

**Pull request merged**
