### PR TITLE
Remove detail from device_span

### PR DESCRIPTION
**Pull request by rwlee**
Fix for issue caused by stale PR issue from #7406

### CODE REVIEW

**Review by kkraus14 — APPROVED** [review]

**Review by hyperbolic2346 — APPROVED** [review]

**Review by galipremsagar — CHANGES_REQUESTED** [review]
I think we need to fix this line too: https://github.com/rapidsai/cudf/blob/branch-0.19/cpp/src/structs/structs_column_factories.cu#L53

**Review by galipremsagar — APPROVED** [review]
Thanks @rwlee !

**Review by hyperbolic2346 — APPROVED** [review]

**Comment by rwlee** [comment]
> I think we need to fix this line too: https://github.com/rapidsai/cudf/blob/branch-0.19/cpp/src/structs/structs_column_factories.cu#L53

grep through the codebase for `detail::device_span` comes up clean now, had missed the reference without a `cudf::` prefix.

**Comment by ttnghia** [comment]
Rerun tests.

**Review by jrhemstad — APPROVED** [review]

**Review by vuule — APPROVED** [review]

**Comment by kkraus14** [comment]
rerun tests

**Comment by kkraus14** [comment]
@gpucibot merge

**Review by trxcllnt — APPROVED** [review]

**Comment by kkraus14** [comment]
rerun tests

**Comment by hyperbolic2346** [comment]
@gpucibot merge

**Pull request merged**
