### PR TITLE
[REVIEW] Use CUDF_HOME variable to clarify install paths in README

### PR DESCRIPTION
**Pull request by trstovall**
Relative addressing after optional `cd` is ambiguous.  This occurs in README section on building from source.  CUDF_HOME bash variable has been added to replace path placeholders and relative pathing.

### CODE REVIEW

**Comment by GPUtester** [comment]
Can one of the admins verify this patch?

**Comment by GPUtester** [comment]
Can one of the admins verify this patch?

**Comment by randerzander** [comment]
add to whitelist

**Comment by harrism** [comment]
run tests

**Comment by trstovall** [comment]
I have added the line to CHANGELOG (creating a conflict).  I am not able to resolve that conflict.  No other conflicts exist with branch-0.5.

**Comment by randerzander** [comment]
I believe this addresses the merge conflict.. anything else for this PR @harrism @trstovall ?

**Comment by harrism** [comment]
rerun tests

**Comment by kkraus14** [comment]
run tests

**Comment by kkraus14** [comment]
run tests

**Comment by harrism** [comment]
rerun tests

**Comment by harrism** [comment]
rerun tests

**Pull request merged**
