### PR TITLE
Update `dask` + `distributed` to `2021.4.0`

### PR DESCRIPTION
**Pull request by jakirkham**
Needed to pick up some serialization bug fixes in the recent Distributed release ( https://github.com/dask/distributed/issues/4645 ) ( https://github.com/dask/distributed/issues/4662 )

### CODE REVIEW

**Comment by jakirkham** [comment]
cc @kkraus14

**Review by kkraus14 — APPROVED** [review]

**Review by raydouglass — CHANGES_REQUESTED** [review]
Can you also open a PR against integration to update the versions there as well?

**Comment by jakirkham** [comment]
These versions appear to be already supported in the integration repo since they are above the minimums. Do we want to bump the minimums?

https://github.com/rapidsai/integration/blob/9c8060e2c20219809591d200de706ef9225b4132/conda/recipes/versions.yaml#L49-L50
https://github.com/rapidsai/integration/blob/9c8060e2c20219809591d200de706ef9225b4132/conda/recipes/versions.yaml#L53-L54

**Comment by raydouglass** [comment]
> Do we want to bump the minimums?

If you're bumping the minimums in cudf, then you should do the same in integration.

**Comment by jakirkham** [comment]
With `distributed`, we are bumping the maximum (not minimum). With `dask`, cuDF has adopted a tighter pinning policy. I'm not sure if we view these the same way as bumping minimums, but wanted to clarify in case something is getting lost here. Happy to do whatever we think is appropriate

**Comment by raydouglass** [comment]
> Happy to do whatever we think is appropriate

Sorry, just to clarify, whatever pinnings we use for dask/distributed in cudf should also be mirrored in integration. Whether its a minimum or maximum change, cudf and integration should mirror the pinnings.

**Comment by kkraus14** [comment]
> In addition, we should update other repos as well such as [cuml](https://github.com/rapidsai/cuml/blob/branch-0.19/conda/recipes/cuml/meta.yaml#L49-L50)

cuML shouldn't be forced to follow cuDF's positioning on Dask / Distributed versioning. We need much more fine grained control over versioning in cuDF because dask.dataframe is often being changed alongside cuDF. cuML is generally using more general Dask APIs that don't have nearly the churn where they're safer to pin more loosely.

If someone is only using cuML without dask-cudf this would unnecessarily constrain them.

**Review by raydouglass — APPROVED** [review]

**Comment by raydouglass** [comment]
@gpucibot merge

**Pull request merged**
