### PR TITLE
Update parquet_common.h

### PR DESCRIPTION
**Pull request by goodengineer**
32 constant in batch size and other parts are further widely used in code, numerous times defined as constexpr in other files down the includes hierarchy, what if to make it macro to save memory consumption... proposal...

### CODE REVIEW

**Comment by GPUtester** [comment]
Can one of the admins verify this patch?

**Comment by GPUtester** [comment]
Can one of the admins verify this patch?

**Comment by GPUtester** [comment]
Can one of the admins verify this patch?

**Comment by harrism** [comment]
Stale, closing.

**Pull request closed without merging**
