### PR TITLE
Temporary fix Parquet metadata with empty value string being ignored from writing

### PR DESCRIPTION
**Pull request by ttnghia**
When writing to Parquet files, Spark needs to write pairs of key-value strings into files' metadata. Sometimes the value strings are just an empty string. Such empty string is ignored from writing into the file, causing other applications (such as Spark) to read the value and interpret it as a `null` instead of an empty string as in the original input, as described in https://github.com/rapidsai/cudf/issues/14024. This is wrong and led to data corruption as I tested.

This PR intentionally modifies the empty value string into a space character to workaround the bug. This is a temporary fix while waiting for a better fix to be worked on.

### CODE REVIEW

**Review by revans2 — APPROVED** [review]
This looks okay to me. Just not sure if we want to do the work around in the Spark plugin instead of doing it here?

**Comment by ttnghia** [comment]
I think we should fix in cudf instead, because there may be more metadata in the form of `{"key_str", ""}` pairs being written in the future. Currently we are having problem with a few known keys such as `legacyDateTime`  and `legacyINT96` thus if we only fix for these keys in the plugin then I'm not sure if we still miss some other and the problem may show up again.

A permanent fix for the problem should be tracked by https://github.com/rapidsai/cudf/issues/14024. After that is closed, we can revert this.

**Pull request merged**
