### PR TITLE
[DOC] Update Pylibcudf doc strings

### LINKED ISSUE #15937: [FEA]: Finish documentation for pylibcudf
Many pylibcudf functions are missing docstrings.

Once pylibcudf is ready to be released, we should go

- [ ] Add missing docstrings to any functions that are missing docstrings
- [ ] Add references to the libcudf C++ equivalent of the pylibcudf function if missing from existing docstrings.
- [ ] Create .rst files for modules missing .rst files and add to index.rst

### PR DESCRIPTION
**Pull request by Matt711**
## Description

This PR is a first pass at #15937. We will close #15937 after #15162 is closed
## Checklist
- [ ] I am familiar with the [Contributing Guidelines](https://github.com/rapidsai/cudf/blob/HEAD/CONTRIBUTING.md).
- [ ] New or existing tests cover these changes.
- [ ] The documentation is up to date with these changes.

### CODE REVIEW

**Comment by mroeschke** [comment]
Just an idea if you're interested, for these pylibcudf docstring it might be good to enforce some numpydoc rules to ensure these docstrings are populated with certain sections: https://numpydoc.readthedocs.io/en/latest/validation.html#built-in-validation-checks

Namely, the `RT01`, `PR`, `SA01`, and `SS01` rules

**Comment by Matt711** [comment]
> Just an idea if you're interested, for these pylibcudf docstring it might be good to enforce some numpydoc rules to ensure these docstrings are populated with certain sections: https://numpydoc.readthedocs.io/en/latest/validation.html#built-in-validation-checks
> 
> Namely, the `RT01`, `PR`, `SA01`, and `SS01` rules

Thanks for the suggestion! Unfortunately, I don't think it works with Cython.

**Comment by vyasr** [comment]
We'll need to make some decision about how many fixes we consider sufficient to close the issue since there will always be more to fix. Maybe we should at least wait until #15162 is closed to say that all of those modules can have fixed docstrings when this PR is merged?

**Comment by Matt711** [comment]
> We'll need to make some decision about how many fixes we consider sufficient to close the issue since there will always be more to fix. Maybe we should at least wait until #15162 is closed to say that all of those modules can have fixed docstrings when this PR is merged?

That sounds good to me. I updated the title and PR description.

**Review by galipremsagar — APPROVED** [review]

**Pull request merged**
