### PR TITLE
Improve distinct join with set `retrieve`

### PR DESCRIPTION
**Pull request by PointKernel**
## Description
This PR updates the distinct join to use `static_set::retrieve` instead of the custom device code.

## Checklist
- [x] I am familiar with the [Contributing Guidelines](https://github.com/rapidsai/cudf/blob/HEAD/CONTRIBUTING.md).
- [x] New or existing tests cover these changes.
- [x] The documentation is up to date with these changes.

### CODE REVIEW

**Review by bdice — APPROVED** [review]
Thanks @PointKernel! This is nice cleanup.

**Review by davidwendt — APPROVED** [review]
cuco is awesome

**Review by ttnghia — APPROVED** [review]
:tada:

**Review by mhaseeb123 — APPROVED** [review]

**Review by karthikeyann — APPROVED** [review]

**Review by shrshi — APPROVED** [review]

**Pull request merged**
