### PR TITLE
[REVIEW] Remove max version pin for `dask` & `distributed` on development branch

### PR DESCRIPTION
**Pull request by galipremsagar**
This PR will remove max version pinning for `dask` & `distributed` for development purposes.

### CODE REVIEW

**Review by ajschmidt8 — APPROVED** [review]

**Comment by jakirkham** [comment]
We are just pinning the Dask + Distributed versions in the release. So new versions of Dask + Distributed don't accidentally break past releases

**Review by jakirkham — APPROVED** [review]

**Review by vyasr — APPROVED** [review]
Got it, thanks. LGTM

**Comment by vyasr** [comment]
Actually quick follow up, do we need to remove the pin that was added in that cuda array interface test, then?

**Comment by galipremsagar** [comment]
> Actually quick follow up, do we need to remove the pin that was added in that cuda array interface test, then?

is this the pytorch one? If yes, no. That's needed as we don't test in CI with pytorch, but somehow a very old version of torch is being shipped in containers somehow.

**Comment by jakirkham** [comment]
@gpucibot merge

**Pull request merged**
