### PR TITLE
[REVIEW] Deduplicates aggregates before sending them to cudf::groupby

### PR DESCRIPTION
**Pull request by abellina**
This a java-side fix for https://github.com/rapidsai/cudf/issues/2331. Additionally, since java has reference counting, we are able to reduce the memory footprint by increasing the ref count of aggregated columns and handing those to the user (e.g. Spark).

### CODE REVIEW

**Comment by jrhemstad** [comment]
#2461 should be merged shortly, so you can probably just hold off on adding this WAR.

**Comment by abellina** [comment]
@jrhemstad sounds good. I'll hold and test using #2461 once its in.

**Comment by revans2** [comment]
@jrhemstad and @abellina I would like to see us do this on the java side too because it will reduce the overall memory footprint of operations like this which we know spark is going to do.

**Comment by abellina** [comment]
@jrhemstad my bad on the description. The ref counting stuff is all in the java side so yeah this does reduce the memory footprint over the plain c++ version.

**Comment by jrhemstad** [comment]
> @jrhemstad and @abellina I would like to see us do this on the java side too because it will reduce the overall memory footprint of operations like this which we know spark is going to do.

Ah, okay, I thought maybe you had a good reason to be doing duplicate agg requests (though I don't know what they'd be :smile:  ).

**Comment by abellina** [comment]
@revans2, upmerged, this is ready for another look.

**Pull request merged**
