### PR TITLE
[OPS] TST Run unit tests with numba 0.51.0

### PR DESCRIPTION
**Pull request by mike-wendt**
Do a GPU test run to see if the timeout issues seen in a pre-release version of numba 0.51 is still present in the recently released 0.51.0 packages

cc @jakirkham @kkraus14

### CODE REVIEW

**Comment by GPUtester** [comment]
Please update the changelog in order to start CI tests.

View the gpuCI docs [here](https://docs.rapids.ai/gpuci#open-pr-or-update-pr).

**Comment by mike-wendt** [comment]
Looks like at least the cos7 gpu test pulled `0.51.0rc1` will have to do a rerun with a more restrictive spec

**Comment by mike-wendt** [comment]
Also on ubuntu18.04
```
00:07:50.666   added / updated specs:
00:07:50.666     - numba=0.51.0
00:07:50.666 
00:07:50.666 
00:07:50.666 The following packages will be downloaded:
00:07:50.666 
00:07:50.666     package                    |            build
00:07:50.666     ---------------------------|-----------------
00:07:50.666     numba-0.51.0rc1            |np1.11py3.7h04863e7_g833c5907c_0         3.6 MB  numba
00:07:50.666     ------------------------------------------------------------
00:07:50.666                                            Total:         3.6 MB
00:07:50.666 
00:07:50.666 The following packages will be UPDATED:
00:07:50.666 
00:07:50.666   numba              conda-forge::numba-0.50.1-py37h0da468~ --> numba::numba-0.51.0rc1-np1.11py3.7h04863e7_g833c5907c_0
```

**Comment by mike-wendt** [comment]
```
## Package Plan ##

  environment location: /opt/conda/envs/gdf

  added / updated specs:
    - numba=0.51.0


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    numba-0.51.0rc1            |np1.11py3.8h04863e7_g833c5907c_0         3.6 MB  numba/label/dev
    ------------------------------------------------------------
                                           Total:         3.6 MB

The following packages will be UPDATED:

  numba              conda-forge::numba-0.50.1-py38hcb8c33~ --> numba/label/dev::numba-0.51.0rc1-np1.11py3.8h04863e7_g833c5907c_0
```

Looks like the mirror timing just missed the `0.51.0` pkg when I ran this. Confirming the mirror is updated now and will rerun.

**Comment by mike-wendt** [comment]
@kkraus14 @gmarkall @jakirkham all the gpu tests passed

conda build failures are due to instance failures that we're looking at

**Pull request closed without merging**
