### PR TITLE
Support for polars 1.12 in cudf-polars

### PR DESCRIPTION
**Pull request by wence-**
## Description

No new updates are required, we must just no longer xfail a test if running with 1.12

## Checklist
- [x] I am familiar with the [Contributing Guidelines](https://github.com/rapidsai/cudf/blob/HEAD/CONTRIBUTING.md).
- [x] New or existing tests cover these changes.
- [x] The documentation is up to date with these changes.

### CODE REVIEW

**Review by vyasr — APPROVED** [review]
I guess we forgot to update the ruff isort when we moved from a cudf to a pylibcudf dependency? Those changes cluttered this PR a bit as a result, but otherwise everything LGTM.

Should we start thinking about a world where we can support a range of polars versions, or are we not there yet? Probably need to upstream more IR testing first I suppose.

**Comment by wence-** [comment]
This one now supports two versions!

**Comment by vyasr** [comment]
Yes! Sorry I should have been more clear, I'm asking if you think that this is a one-off or if you think we're getting to a place where we only need to bump the upper bounds (and eventually can remove the upper bound). IR stability is part of the equation, but perhaps not all of it since we also need to pass the polars test suite so behavior changes could hit us even if the IR is stable.

**Comment by wence-** [comment]
> Yes! Sorry I should have been more clear, I'm asking if you think that this is a one-off or if you think we're getting to a place where we only need to bump the upper bounds (and eventually can remove the upper bound). IR stability is part of the equation, but perhaps not all of it since we also need to pass the polars test suite so behavior changes could hit us even if the IR is stable.

Oh, I see what you mean.

I expect that we will continue to bump lower bounds as well, because although we can adapt to changes across versions in the IR (we can recognise this via IR versioning as well), I'd rather not do too much, and as you note, testing against all the versions might result in different answers due to bugs. As noticed here, I had a test that I expected to fail against 1.11 (due to a polars issue) that then needs to be removed for 1.12 (because it was fixed).

I suspect we will get to a point that is similar to the pandas situation: we have some lower bound that we periodically update. As discussed for other reasons, I think we should always have an upper bound, but it might get to the point where it is bounded above by the next major version.

**Pull request merged**
