### PR TITLE
Fix Inaccurate error message in join.pyx

### PR DESCRIPTION
**Pull request by Shakeebbk**
Update the string of the exception message.
Closes: #1272

### CODE REVIEW

**Comment by GPUtester** [comment]
Can one of the admins verify this patch?

**Comment by thomcom** [comment]
@Shakeebbk , we're targeting branch `branch-0.7` presently, can you resubmit this PR targeting that branch?

**Comment by harrism** [comment]
I've changed the base branch to branch-0.7. @Shakeebbk you just need to merge branch-0.7 into your feature branch and push to your fork.

**Comment by harrism** [comment]
You also need to update CHANGELOG.md in order to pass CI.

**Comment by kkraus14** [comment]
ok to test

**Pull request merged**
