### PR TITLE
Remove `lists::drop_list_duplicates`

### PR DESCRIPTION
**Pull request by ttnghia**
This PR completely removes `cudf::lists::drop_list_duplicates`. It is replaced by the new API `cudf::list::distinct` which has a simpler implementation but better performance. The replacements for internal cudf usage have all been merged before thus there is no side effect or breaking for the existing APIs in this work.

Closes https://github.com/rapidsai/cudf/issues/11114, https://github.com/rapidsai/cudf/issues/11093, https://github.com/rapidsai/cudf/issues/11053, https://github.com/rapidsai/cudf/issues/11034, and closes https://github.com/rapidsai/cudf/issues/9257.

Depends on:
 * https://github.com/rapidsai/cudf/pull/11228
 * https://github.com/rapidsai/cudf/pull/11149
 * https://github.com/rapidsai/cudf/pull/11234
 * https://github.com/rapidsai/cudf/pull/11233

### CODE REVIEW

**Review by Ethyling — APPROVED** [review]

**Review by robertmaynard — APPROVED** [review]
CMake changes approved

**Comment by vuule** [comment]
Should the PR be named "Remove ..."? Deprecation means that the API is still available.

**Review by vuule — APPROVED** [review]

**Review by bdice — APPROVED** [review]
Nice. -1,741 lines of code is a great feeling.

**Comment by bdice** [comment]
@ttnghia I think this can be merged when you're ready. You're more familiar with the state of all the linked issues than I am -- please close or comment on all the related issues once this is merged.

**Comment by ttnghia** [comment]
Thanks all for helping on this. I'm merging.

**Comment by ttnghia** [comment]
@gpucibot merge

**Pull request merged**
