### PR TITLE
Move replace.hpp files to legacy

### PR DESCRIPTION
**Pull request by jwyles**
Issue #2944
Replace.hpp refactor phase I:
Moved headers and code files to legacy directories, updated paths and build files.

### CODE REVIEW

**Comment by harrism** [comment]
rerun tests

**Comment by jrhemstad** [comment]
rerun tests

**Comment by jrhemstad** [comment]
@jwyles update with the latest branch-0.11 to unblock CI.

**Comment by jrhemstad** [comment]
@jwyles please fix merge conflicts and CI issues.

**Pull request merged**
