### PR TITLE
[REVIEW] Pin `transformers` to `<=4.10.3`

### PR DESCRIPTION
**Pull request by galipremsagar**
There is a importError in latest transformers release, hence pinning the max transformers version.

### CODE REVIEW

**Review by shwina — APPROVED** [review]

**Review by ajschmidt8 — APPROVED** [review]

**Comment by ajschmidt8** [comment]
https://github.com/rapidsai/integration/pull/362 is merged. We just need to wait until the new `integration` packages are published and then we need to rebuild the CI containers so they use the latest `integration` packages and then we can rerun the tests here and everything should pass.

**Comment by ajschmidt8** [comment]
rerun tests

**Comment by galipremsagar** [comment]
rerun tests

**Comment by galipremsagar** [comment]
rerun tests

**Comment by ajschmidt8** [comment]
CI has passed. merging.

**Pull request merged**
