### PR TITLE
Clean up CUDA stream use in cuIO

### PR DESCRIPTION
**Pull request by vuule**
Removes defaults for internal stream parameters.
Fixes cases where default stream was used instead of propagating the stream.

### CODE REVIEW

**Comment by vuule** [comment]
rerun tests

**Comment by vuule** [comment]
rerun tests

**Comment by davidwendt** [comment]
This looks good to me. Just update the copyright year I think.

**Comment by vuule** [comment]
> This looks good to me. Just update the copyright year I think.

Lol, I just checked the year in some files and did not update since "2021 is already included".

**Review by davidwendt — APPROVED** [review]

**Review by robertmaynard — APPROVED** [review]

**Comment by vuule** [comment]
@gpucibot merge

**Pull request merged**
