### PR TITLE
Fix UDF Caching

### PR DESCRIPTION
**Pull request by brandon-b-miller**
This PR fixes an issue in caching `apply` UDFs where we were incorrectly getting a cache miss on the same function/dataframe. This was happening because `dict_values` objects don't compare as equal.

### CODE REVIEW

**Review by galipremsagar — APPROVED** [review]
Is it possible to add a pytest to catch/validate the issue?

**Comment by brandon-b-miller** [comment]
> Is it possible to add a pytest to catch/validate the issue?

We probably should - let me look into this.

**Comment by brandon-b-miller** [comment]
I wasn't 100% sure what the best way of testing this would be, but I came up with something that might be going in the right direction. Let me know what you think.

**Review by charlesbluca — APPROVED** [review]

**Review by shwina — APPROVED** [review]

**Comment by brandon-b-miller** [comment]
@gpucibot merge

**Pull request merged**
