### PR TITLE
Add `bytes_per_second` to copy_if_else benchmark

### PR DESCRIPTION
**Pull request by Blonck**
Adds `bytes_per_second` to the `COPY_IF_ELSE_BENCH` benchmark.

This patch relates to #13735.

## Checklist
- [x] I am familiar with the [Contributing Guidelines](https://github.com/rapidsai/cudf/blob/HEAD/CONTRIBUTING.md).

### CODE REVIEW

**Review by bdice — APPROVED** [review]
Looks good to me. Thanks!

**Review by davidwendt — APPROVED** [review]

**Pull request merged**
