### PR TITLE
Operators on different sized dataframes

### LINKED ISSUE #1736: [BUG]DataFrame support methods add/sub does not match Pandas
The support methods add and sub on empty DataFrame/Series results in output that does not match with Pandas.

The following script:
```
import pandas as pd
pd.DataFrame({}) + pd.DataFrame({'x': [1, 2], 'y': [1.0, 2.0]})
```
results in 
```
    x   y
0 NaN NaN
1 NaN NaN
```
But, this:
```
import cudf
pd.DataFrame({}) + pd.DataFrame({'x': [1, 2], 'y': [1.0, 2.0]})
```
results in
```
<cudf.DataFrame ncols=2 nrows=0 >
```

**Expected behavior**
The `__add__` method does not hold place holders for data but Pandas does. Also, mismatched dimensions results in an error with cudf where as Pandas append NaN values to match dimensions.

**Environment details:**
 cudf - 0.7

### PR DESCRIPTION
**Pull request by madsbk**
This PR fixes #1736 by inserting new NaN columns with the length of the largest operand.

However, this does **not** work when operands share columns with different length. 
E.g. `cudf.DataFrame({'x': [1, 2]}) + cudf.DataFrame({'x': [1, 2, 3]}` will raise `NotImplementedError`.

To support this case, we need to insert NaN rows until the length of the operands matches -- similar to how [`.reindex()`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.reindex.html#pandas.DataFrame.reindex) works in Pandas. Thus, we might consider implementing #1779 before handling this case.

I have added testing of both cases.

Finally, there is still an issue with NaN and pow(). The problem is the following cases where the result is not NaN:
```python
pow(1, NaN) == 1
pow(NaN, 0) == 1
```
which we cannot handle by inserting new NaN columns.

### CODE REVIEW

**Comment by thomcom** [comment]
Thanks @madsbk ! Can you update your CHANGELOG.md with this new PR and a description of the fix? After you push it'll rerun tests and hopefully come back all green.

**Comment by madsbk** [comment]
Do any of you know why the [check-changelog](https://gpuci.gpuopenanalytics.com/blue/organizations/jenkins/gpuCI%2Fcudf%2Fprb%2Fcudf-changelog/detail/cudf-changelog/1557/pipeline) fails even though I have updated the [changelog](https://github.com/rapidsai/cudf/pull/1817/commits/4144c089e2c1e434791332c51ee230c6eba4ac9c)?

**Comment by kkraus14** [comment]
> Do any of you know why the [check-changelog](https://gpuci.gpuopenanalytics.com/blue/organizations/jenkins/gpuCI%2Fcudf%2Fprb%2Fcudf-changelog/detail/cudf-changelog/1557/pipeline) fails even though I have updated the [changelog](https://github.com/rapidsai/cudf/pull/1817/commits/4144c089e2c1e434791332c51ee230c6eba4ac9c)?

You have an incorrect PR # 😄, you have `PR #1736` instead of `PR #1817`

**Comment by thomcom** [comment]
Hey @madsbk - it has a conflict. This happens annoyingly whenever someone else gets a PR merged more quickly than your PR was merged. To correct it, you need to pull a fresh branch-0.8 locally, merge it into your branch `different_length`, resolve the conflict there, and push again.

**Comment by madsbk** [comment]
Ahh make sense :)
Updated the changelog to say PR #1817 instead of PR #1736 :blush: and fixed the conflict.

**Comment by madsbk** [comment]
Btw, what do you guys prefer when solving conflicts in a PR: `merge` or `rebase`?

**Comment by thomcom** [comment]
I've never used rebase to resolve conflicts, why prefer one way or the other?

So long as your rebase only affects local commits I'm happy with it, I think. :)

**Comment by madsbk** [comment]
Using `rebase` avoids a lot of merges in the commit history, which makes it easier to follow. But `rebase` also change the history of the commits in the PR, which might invalid references to specific commits.

Anyway,  I will use `merge` if that is what you use :)

**Pull request merged**
