### PR TITLE
[REVIEW] New proposed groupby API

### PR DESCRIPTION
**Pull request by jrhemstad**
Currently, the groupby API exposes separate APIs for each aggregation operation (e.g., groupby_sum, groupby_count, etc.) and only supports a single aggregation column. 

To replace this API, this PR proposes a new consolidated API with just a single function that supports an arbitrary number of groupby and aggregation columns. 

This API change is in preparation for implementing a single-pass, multi-aggregation hash-based groupby.

### CODE REVIEW

**Comment by kkraus14** [comment]
@jrhemstad @harrism you can refer to the columns you're passing into the groupby call as the "key columns"

**Comment by GPUtester** [comment]
Can one of the admins verify this patch?

**Comment by kkraus14** [comment]
add to whitelist

**Comment by jrhemstad** [comment]
Closing this PR since the API sounds like it is acceptable. Will introduce this new API and implementation in an upcoming PR.

**Pull request closed without merging**
