### PR TITLE
Refactor io memory fetches to use hostdevice_vector methods

### PR DESCRIPTION
**Pull request by ChrisJar**
This replaces `cudaMemcpyAsync(hostdevice_vector)` with `hostdevice_vector.device_to_host()` or `hostdevice_vector.host_to_device()` when appropriate.

Issue #6538

### CODE REVIEW

**Comment by kkraus14** [comment]
@ChrisJar what's the state of this PR? Should we try to get this in for 0.18 or push to 0.19?

**Comment by kkraus14** [comment]
cc @vuule for visibility of tracking cuIO work

**Comment by vuule** [comment]
The patch looks good, thank you @ChrisJar !
Edited the description since for some reason I could not link the issue.

**Review by karthikeyann — APPROVED** [review]

**Review by vuule — APPROVED** [review]

**Comment by vuule** [comment]
@gpucibot merge

**Pull request merged**
