### PR TITLE
[REVIEW] Fix DataFrame __sizeof__

### PR DESCRIPTION
**Pull request by pentschev**
Currently, the computation of `DataFrame.__sizeof__()` sums `_index.__sizeof__()` as many times as there are columns. This doesn't reflect the behavior of Pandas, nor the real amount of device memory used.

I reckon this isn't a good long-term solution, but we require a reliable way of computing the amount of used memory for proper device memory spilling within dask-cuda, which is needed for 0.8 already. As far as I could understand, Pandas relies on the `deep` keyword argument to compute the memory used by a `DataFrame`, which isn't implemented yet, and probably won't make it to 0.8, but https://github.com/rapidsai/cudf/issues/1937 was open to tackle that.

cc @kkraus14 @quasiben

### CODE REVIEW

**Comment by quasiben** [comment]
Any interest in adding a `memory_usage` function as well https://github.com/rapidsai/cudf/issues/1937 ?  Or would you rather that be a separate PR ?

**Comment by pentschev** [comment]
@quasiben if we do `memory_usage` as Pandas does, it will require implementing the `deep` argument, and that touches a significant part of the codebase, which may take a while. That said, I'm not sure I'll have time to do all that before the next release. So if there are no objections, I'd rather have this integrated first, and then either me or someone else can continue on #1937 with no need to rush.

**Comment by quasiben** [comment]
Sounds good

**Comment by pentschev** [comment]
Thanks @kkraus14 and @quasiben for reviewing/merging.

**Pull request merged**
