### PR TITLE
Java bindings for mixed semi and anti joins

### PR DESCRIPTION
**Pull request by jlowe**
This depends on #9941 and #10037.  Adds Java bindings for mixed left semi join and mixed left anti join.

### CODE REVIEW

**Comment by jlowe** [comment]
Converting this to a draft until #10037 has been merged to avoid inadvertent early merging since Java CI failures are a non-blocker.

**Review by abellina — APPROVED** [review]

**Review by tgravescs — APPROVED** [review]

**Review by jbrennan333 — APPROVED** [review]
+1 this looks good to me.

**Comment by jlowe** [comment]
#10037 has been merged, so this should be ready to go.

**Comment by jlowe** [comment]
@gpucibot merge

**Pull request merged**
