### PR TITLE
Clean up existing JNI scalar to column code

### PR DESCRIPTION
**Pull request by revans2**
## Description
This removes some special case code that is no longer needed.

## Checklist
- [X] I am familiar with the [Contributing Guidelines](https://github.com/rapidsai/cudf/blob/HEAD/CONTRIBUTING.md).
- [X] New or existing tests cover these changes.
- [X] The documentation is up to date with these changes.

### CODE REVIEW

**Review by jlowe — APPROVED** [review]

**Review by ttnghia — APPROVED** [review]

**Comment by revans2** [comment]
@gpucibot merge

**Comment by galipremsagar** [comment]
@gpucibot merge

**Comment by galipremsagar** [comment]
@gpucibot merge

**Comment by ttnghia** [comment]
@gpucibot merge

**Pull request merged**
