### PR TITLE
Branch 0.19 merge 0.18

### PR DESCRIPTION
**Pull request by nvdbaranec**
Fixes https://github.com/rapidsai/cudf/pull/7305

### CODE REVIEW

**Review by jlowe — APPROVED** [review]
Java approval

**Comment by kkraus14** [comment]
I think we can just merge #7305 directly via a merge commit instead of this. Pinged ops to confirm.

**Review by revans2 — APPROVED** [review]
The java merge looks fine

**Comment by kkraus14** [comment]
#7305 merged so closing this.

**Pull request closed without merging**
