### PR TITLE
Remove 10.2 workarounds in groupby functions for dictionary column types

### PR DESCRIPTION
**Pull request by davidwendt**
Reference #7913 
This removes the compiler restrictions in the libcudf groupby code that was disabled because of compiler issues on nvcc 10.2 when adding dictionary columns support. The corresponding disabled gtests have been enabled as well.

Details of the compiler bug are documented here: https://nvbugswb.nvidia.com/NvBugs5/SWBug.aspx?bugid=3186317

This also fixes an issue where the sum-of-squares aggregation was not working for values specified as a dictionary column.

### CODE REVIEW

**Comment by davidwendt** [comment]
rerun tests

**Review by karthikeyann — APPROVED** [review]

**Comment by karthikeyann** [comment]
Creating separate functor for each operation for dicitonary keytype is repeated code and not scalable. It needs another refactor, may be in another PR. For removing 10.2 workarounds, this PR looks good.

**Review by ttnghia — APPROVED** [review]

**Comment by ttnghia** [comment]
Rerun tests.

**Comment by harrism** [comment]
@gpucibot merge

**Pull request merged**
