### PR TITLE
Use _from_data instead of _from_columns for initialzing Frame

### PR DESCRIPTION
**Pull request by mroeschke**
## Description
In the spirit of reducing redundant methods, `_from_columns` just calls `_from_data` (hoping to rename to `_from_mapping` or similar) so removing the need for `_from_columns`.

Hoping to do the same for the `_from_columns_like_self` in a follow up.

## Checklist
- [ ] I am familiar with the [Contributing Guidelines](https://github.com/rapidsai/cudf/blob/HEAD/CONTRIBUTING.md).
- [ ] New or existing tests cover these changes.
- [ ] The documentation is up to date with these changes.

### CODE REVIEW

**Comment by isVoid** [comment]
A bit of background for `_from_columns` - this was introduced when we want to refactor the cython layer with only list of columns input and output. `_from_columns` was just a sugar to make constructing from the result of a cython function easier.

**Comment by mroeschke** [comment]
> this was introduced when we want to refactor the cython layer with only list of columns input and output

Is this still an effort being worked on? My observation of the current usage is that it tends to always be paired with column labels like `_from_data`.

**Comment by isVoid** [comment]
If I remember correctly, the remaining work to be done are cuio cython APIs. But this work shouldn't be block by that, in fact, follow ups to that refactor can always resort to `_from_data`.

**Review by isVoid — APPROVED** [review]

**Comment by vyasr** [comment]
> > this was introduced when we want to refactor the cython layer with only list of columns input and output
> 
> Is this still an effort being worked on? My observation of the current usage is that it tends to always be paired with column labels like `_from_data`.

This work was put on hold because I decided that getting pylibcudf done first would be better. Most of the structure that I imagined imposing at the Cython layer will be largely informed by refactoring cudf internals around pylibcudf objects once pylibcudf is done.

**Pull request merged**
