### PR TITLE
[REVIEW] Fix make issue /usr/bin/ld: cannot find -lNVCategory

### PR DESCRIPTION
**Pull request by prabindh**
Fix for https://github.com/rapidsai/cudf/issues/4178

Dependency addition, no unit-test for code required.

### CODE REVIEW

**Comment by GPUtester** [comment]
Can one of the admins verify this patch?

**Comment by GPUtester** [comment]
Can one of the admins verify this patch?

**Comment by dillon-cullinan** [comment]
skip ci

**Comment by prabindh** [comment]
As discussed in #4178 , will fix this via documentation.

**Pull request closed without merging**
