### PR TITLE
Support equally comparing two different tables in the newly experimental row comparator

### PR DESCRIPTION
**Pull request by ttnghia**
The new row comparator (https://github.com/rapidsai/cudf/pull/10164) only added a `self_comparator` utility to compare rows of the same table. This PR adds `equality::table_comparator` that allows equally comparing rows from different tables. Immediate usage of such comparator is for linearly searching a struct scalar in a structs column.

In addition, it also fixes the comparator that produces wrong results when the input is sliced.

This PR is required for https://github.com/rapidsai/cudf/pull/10548 and https://github.com/rapidsai/cudf/pull/10656.

### CODE REVIEW

**Comment by ttnghia** [comment]
@jrhemstad @devavret The new equality comparator seems to be incorrect for sliced input. I still didn't figure out what's wrong. If you uncover anything, please let me know.

**Comment by jrhemstad** [comment]
@ttnghia this work is actually already under way. See https://github.com/rapidsai/cudf/issues/10508 

CC @bdice

**Comment by ttnghia** [comment]
@bdice If you are working on similar thing, please apply this patch: https://github.com/rapidsai/cudf/pull/10667/files#diff-0743b70282a92785dee8e55adc4099f501b4ed6c20c21e39fe187b2f4f0664a0L560-R562. It is fixing the bug when the input column is sliced.

**Comment by ttnghia** [comment]
In addition, I'm still not sure if this (https://github.com/rapidsai/cudf/pull/10667/files#diff-0743b70282a92785dee8e55adc4099f501b4ed6c20c21e39fe187b2f4f0664a0R564-R565) also needs to be fixed by the same way. This needs to be tested too.

**Pull request closed without merging**
