### PR TITLE
[REVIEW] Optimize `DataFrame` creation across code-base

### PR DESCRIPTION
**Pull request by galipremsagar**
After internal profiling, it appears that `_init_from_dict_like` was being repeatedly called even for `ColumnAccessor` inputs, which is not necessary and is an expensive method where we do proper index re-alignment. This PR handles by raising an error when a developer tries to create a `DataFrame` with `ColumnAccessor`, and also changes multiple of those instances where such calls are present to `_from_data` call which will now avoid going through `_init_from_dict_like` method for `ColumnAccessor` input. For a dataframe of shape `30_00_000 x 3` the speed up is about **2.5x to 4x**.

```python
In [1]: import cudf

In [2]: x = cudf.DataFrame(
   ...:     {
   ...:         "a": [1, 2, 3] * 10_00_000,
   ...:         "b": [3, 4, 5] * 10_00_000,
   ...:         "c": ["a", "b", "c"] * 10_00_000,
   ...:     },
   ...:     index=list(range(0, 3000000)),
   ...: )

In [3]: x
Out[3]: 
         a  b  c
0        1  3  a
1        2  4  b
2        3  5  c
3        1  3  a
4        2  4  b
...     .. .. ..
2999995  2  4  b
2999996  3  5  c
2999997  1  3  a
2999998  2  4  b
2999999  3  5  c

[3000000 rows x 3 columns]

In [4]: x.index
Out[4]: 
Int64Index([      0,       1,       2,       3,       4,       5,       6,
                  7,       8,       9,
            ...
            2999990, 2999991, 2999992, 2999993, 2999994, 2999995, 2999996,
            2999997, 2999998, 2999999],
           dtype='int64', length=3000000)
```
On `branch-22.04`:
```python
In [3]: %timeit cudf.DataFrame(x._data, x._index)
35.4 µs ± 240 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)

In [4]: %timeit cudf.DataFrame(x._data)
40.6 µs ± 242 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)

```

This `PR`:

```python
In [4]: %timeit cudf.DataFrame._from_data(x._data, x._index)
8.11 µs ± 169 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)

In [3]: %timeit cudf.DataFrame._from_data(x._data)
16.9 µs ± 220 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)
```

### CODE REVIEW

**Comment by galipremsagar** [comment]
cc: @randerzander @ayushdg

**Comment by vyasr** [comment]
To be clear, there are _a ton_ of places in cudf that are doing inefficient things right now when it comes to materializing more intermediates than we need. We need to do a comprehensive review to remove things like this.

**Comment by galipremsagar** [comment]
After an offline discussion with @vyasr we decided to raise an error if someone passes a `ColumnAccessor` to `DataFrame/Series` constructors thus forcing devs to use a much faster `Series/DataFrame._from_data` method. I have also now changed the internal code that was using the ineffecient code path before.

**Review by bdice — APPROVED** [review]
Nice. Perf improvements look awesome, too!

**Comment by galipremsagar** [comment]
@gpucibot merge

**Pull request merged**
