### PR TITLE
Add JNI for extract_quarter, add_calendrical_months, and is_leap_year

### PR DESCRIPTION
**Pull request by revans2**
A number of new APIs have been added to cudf c++ date time processing. This wraps them with corresponding java APIs and adds a few tests.

### CODE REVIEW

**Comment by revans2** [comment]
This is not really a high priority for Spark. 

We already support quarter of the year by getting the month and doing a bit of math with it.  This should hopefully speed that up, but we have not seen it as slow in any actual queries. 

`add_calendrical_months` should allow us to support adding months to dates and timestamps, but Spark supports INT32 instead of INT16 for the type and we currently only support scalar values to add, which this does not. It is still a good step.

Spark has no SQL API for leap year detection so that is not going to help much yet.

I just thought it would be good to keep the APIs up to date.

**Comment by revans2** [comment]
rerun tests

**Review by jlowe — APPROVED** [review]

**Comment by revans2** [comment]
rerun tests

**Comment by revans2** [comment]
@gpucibot merge

**Pull request merged**
