### PR TITLE
Remove now redundant cuda initialization

### PR DESCRIPTION
**Pull request by vyasr**
## Description

Prior to #11452 cuDF Python did not require CUDA for compilation. When libcudf was is found by CMake, however, it triggers a compilation of the C++ library, which does require CUDA for compilation. In order to support this behavior, we included some extra logic in cuDF's CMake to ensure that the appropriate CUDA architectures are compiled for (respecting the extra options like `RAPIDS` and `NATIVE` that `rapids-cmake` offers). However, with the merge of #11452 this conditional is now redundant because cuDF requires CUDA compilation unconditionally, so we can remove the extra code.

## Checklist
- [x] I am familiar with the [Contributing Guidelines](https://github.com/rapidsai/cudf/blob/HEAD/CONTRIBUTING.md).
- [x] New or existing tests cover these changes.
- [x] The documentation is up to date with these changes.

### CODE REVIEW

**Review by bdice — APPROVED** [review]
This looks good to me. Discussed offline with @vyasr and realized this cleanup was needed. 😄

**Comment by ajschmidt8** [comment]
(updating branch to retrigger GHAs to test [new sccache settings](https://github.com/rapidsai/ci-imgs/pull/36))

**Comment by vyasr** [comment]
@gpucibot merge

**Pull request merged**
