### PR TITLE
[REVIEW] Fix CudfEngine.read_metadata API in dask_cudf

### PR DESCRIPTION
**Pull request by rjzamora**
*NOTE [dask#6282](https://github.com/dask/dask/pull/6282) is now merged.*

When [dask#6282](https://github.com/dask/dask/pull/6282), the read_parquet tests in dask_cudf will break, because the `CudfEngine.read_metadata` API will (slightly) change.  This PR simply adds the necessary change to align with upstream Dask.

### CODE REVIEW

**Comment by GPUtester** [comment]
Please update the changelog in order to start CI tests.

View the gpuCI docs [here](https://docs.rapids.ai/gpuci#open-pr-or-update-pr).

**Comment by rjzamora** [comment]
@quasiben @jakirkham - We will need this fix to go in as soon as dask#6282 is merged :)

**Comment by kkraus14** [comment]
@rjzamora should we bump the required version of Dask / Distributed in the conda recipes / environment files based on this change?

**Comment by rjzamora** [comment]
> @rjzamora should we bump the required version of Dask / Distributed in the conda recipes / environment files based on this change?

0.15 will certainly require the latest dask version now (note that the API will likely change again before the 0.15 release since some performance issues in read_parquet are certainly calling for another partial refactor - sorry :/ )

**Comment by kkraus14** [comment]
> > @rjzamora should we bump the required version of Dask / Distributed in the conda recipes / environment files based on this change?
> 
> 0.15 will certainly require the latest dask version now (note that the API will likely change again before the 0.15 release since some performance issues in read_parquet are certainly calling for another partial refactor - sorry :/ )

Should we bump this now or merge as is and then bump when the 2nd refactor lands in Dask?

**Comment by kkraus14** [comment]
Going to merge now. If we decide we should bump before the next refactor we can push a PR doing so.

**Pull request merged**
