### PR TITLE
Remove deprecated PER_THREAD_DEFAULT_STREAM

### PR DESCRIPTION
**Pull request by jbrennan333**
Closes https://github.com/rapidsai/cudf/issues/10862.

The `PER_THREAD_DEFAULT_STREAM` build option was deprecated in branch-22.06 via #10877, and replaced with the new build option `CUDF_USE_PER_THREAD_DEFAULT_STREAM`.

This PR removes `PER_THREAD_DEFAULT_STREAM`.

I am putting this up as a draft because I am not certain if we want to do this in 22.08 or wait for a later release?

### CODE REVIEW

**Review by jlowe — APPROVED** [review]
Java approval

**Review by vyasr — APPROVED** [review]
Looks like there's [one leftover reference in build.sh](https://github.com/rapidsai/cudf/blob/branch-22.08/build.sh#L168). There's also [a typo in cpp/CMakeLists.txt](https://github.com/rapidsai/cudf/blob/branch-22.08/cpp/CMakeLists.txt#L85), it's missing `USE`. Let's get those fixed in this PR so that it's a clean transition.

**Review by vyasr — CHANGES_REQUESTED** [review]
Oops accidentally hit approve instead of request changes :grimacing:

**Comment by jbrennan333** [comment]
> Looks like there's [one leftover reference in build.sh](https://github.com/rapidsai/cudf/blob/branch-22.08/build.sh#L168). There's also [a typo in cpp/CMakeLists.txt](https://github.com/rapidsai/cudf/blob/branch-22.08/cpp/CMakeLists.txt#L85), it's missing USE. Let's get those fixed in this PR so that it's a clean transition.

Thanks @vyasr!  I will fix those.

**Comment by jbrennan333** [comment]
I put up another commit to address the issues raised by @vyasr.

**Review by vyasr — APPROVED** [review]

**Comment by vyasr** [comment]
LGTM, thanks!

**Comment by vyasr** [comment]
@gpucibot merge

**Pull request merged**
