### PR TITLE
Shared action worklfows sccache config

### PR DESCRIPTION
**Pull request by divyegala**
## Description
Depends on https://github.com/rapidsai/shared-action-workflows/pull/94

## Checklist
- [x] I am familiar with the [Contributing Guidelines](https://github.com/rapidsai/cudf/blob/HEAD/CONTRIBUTING.md).
- [x] New or existing tests cover these changes.
- [x] The documentation is up to date with these changes.

### CODE REVIEW

**Comment by vyasr** [comment]
The latest run doesn't seem to be using sccache, so we're going to have to dig a little deeper into why here.

**Comment by divyegala** [comment]
@vyasr looks like wheel builds finished in ~7-8m, which means we are getting `sccache` hits and it was just an issue of updating the version

**Comment by vyasr** [comment]
OK, and that was after removing the AWS credentials again?

**Comment by vyasr** [comment]
Closing now that https://github.com/rapidsai/shared-action-workflows/issues/84 is merged

**Pull request closed without merging**
