### PR TITLE
Fix Aggregation Type Promotion: Ensure Unsigned Input Types Result in Unsigned Output for Sum and Multiply

### PR DESCRIPTION
**Pull request by SurajAralihalli**
## Description

During aggregation, output types are modified to prevent overflow. Presently, summing INT32 yields INT64, but summing UINT32 still results in INT64 instead of UINT64. This pull request resolves Issue #[10149](https://github.com/rapidsai/cudf/issues/10149) to ensure the correct output type is used when summing or multiplying integers.

## Checklist
- [X] I am familiar with the [Contributing Guidelines](https://github.com/rapidsai/cudf/blob/HEAD/CONTRIBUTING.md).
- [x] New or existing tests cover these changes.
- [x] The documentation is up to date with these changes.

### CODE REVIEW

**Comment by karthikeyann** [comment]
@SurajAralihalli The groupby tests already tests this. Since the tests use `cudf::detail::target_type_t`, this was not caught. 
Suggestion: Add static assert with `std::is_unsigned_v<Source>` in https://github.com/rapidsai/cudf/blob/580ee40bf5fe1a66eaba914cdddb718a09193bab/cpp/tests/groupby/sum_tests.cpp#L38 
Perhaps, adding a separate test for type checking to cover all cases, could be considered too.

**Comment by SurajAralihalli** [comment]
> @SurajAralihalli The groupby tests already tests this. Since the tests use `cudf::detail::target_type_t`, this was not caught. Suggestion: Add static assert with `std::is_unsigned_v<Source>` in
> 
> https://github.com/rapidsai/cudf/blob/580ee40bf5fe1a66eaba914cdddb718a09193bab/cpp/tests/groupby/sum_tests.cpp#L38
> 
> 
> Perhaps, adding a separate test for type checking to cover all cases, could be considered too.

Thanks @karthikeyann, the `groupby_sum_test` doesn't include any unsigned types. I have added uint16_t and uint64_t in the `supported_types` to test.

**Comment by karthikeyann** [comment]
https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword
Use keyword like closes or fixes or resolves

**Comment by SurajAralihalli** [comment]
> https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword
> Recommend using keyword like closes or fixes or resolves in description

Thanks @karthikeyann, I'll keep that in mind!

**Review by ttnghia — APPROVED** [review]

**Review by shrshi — APPROVED** [review]

**Comment by nvdbaranec** [comment]
I don't see any specific handling here for int32/uint32.  Is that handled in another way?

**Comment by SurajAralihalli** [comment]
> I don't see any specific handling here for int32/uint32. Is that handled in another way?

For computing `target_type_t'?  The target type is always upscaled to int64/uint64 for integers of any type.

**Review by karthikeyann — APPROVED** [review]

**Pull request merged**
