### PR TITLE
[REVIEW] Improve Dockerfile

### LINKED ISSUE #881: Dockerfile has no cleaning commands [BUG]
**Describe the bug**
The Dockerfile contains build commands but no corresponding clean commands. 

**Steps/Code to reproduce bug**
Each layer size is bigger than its intended size due to storage space taken by temporary files. 

**Expected behavior**
dockerfile best practices suggest to clean the temporary files after build/install in same RUN command. https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#run
Otherwise, that layer will take more storage space. 

**Environment details (please complete the following information):**
 - Environment location: [Docker]
 - Method of cuDF install: [ Docker build from source]

**Additional context**
add clean commands for all build commands generating temporary files.

### PR DESCRIPTION
**Pull request by igormp**
Cleans up apt's cache after installing everything.

Also added the number of cores of the current machine in order to avoid an infinite amount of threads being spawned and using way too much RAM.

Fixes #881.

### CODE REVIEW

**Comment by GPUtester** [comment]
Can one of the admins verify this patch?

**Comment by GPUtester** [comment]
Can one of the admins verify this patch?

**Review by ajschmidt8 — APPROVED** [review]

**Comment by ajschmidt8** [comment]
add to whitelist

**Comment by GPUtester** [comment]
Please update the changelog in order to start CI tests.

View the gpuCI docs [here](https://docs.rapids.ai/gpuci#open-pr-or-update-pr).

**Comment by ajschmidt8** [comment]
@igormp, thank you for your contribution. Can you please add an entry to the changelog file below in order to start CI?

https://github.com/rapidsai/cudf/blob/branch-0.17/CHANGELOG.md

**Comment by igormp** [comment]
I solved the conflicts with the base branch. Is there anything else needed?

**Review by karthikeyann — APPROVED** [review]

**Review by ajschmidt8 — APPROVED** [review]

**Pull request merged**
