### PR TITLE
Enable more Pydocstyle rules

### PR DESCRIPTION
**Pull request by bdice**
## Description
Recently I have reviewed a handful of PRs with problems in their docstrings that I've been fixing with GitHub review suggestions. I took 40 minutes and enabled a bunch of pydocstyle rules that we agreed on in #10711, to help prevent some of these problems and reduce the amount of review effort required for the future. There are a handful of big ones (`D200, D202, D205, D400`) that will require a more intense effort to implement -- those rules may not be worth the significant refactoring effort. I think this may resolve the part of #10711 that we wanted to tackle in the short term, though I'm happy to hear others' views (@shwina @vyasr).

Error code reference: https://www.pydocstyle.org/en/stable/error_codes.html

## Checklist
- [x] I am familiar with the [Contributing Guidelines](https://github.com/rapidsai/cudf/blob/HEAD/CONTRIBUTING.md).
- [x] New or existing tests cover these changes.
- [x] The documentation is up to date with these changes.

### CODE REVIEW

**Review by shwina — APPROVED** [review]
LGTM! Happy to defer enforcing the remaining rules to a future PR.

**Review by mroeschke — APPROVED** [review]

**Review by galipremsagar — APPROVED** [review]
Awesome ! Way less noise(warnings) during docs build 🥳 🕺

**Comment by bdice** [comment]
> Awesome ! Way less noise(warnings) during docs build 🥳 🕺

Fantastic point! I hadn't thought to check that.

**Comment by bdice** [comment]
@gpucibot merge

**Pull request merged**
