### PR TITLE
Update cudf java bindings to 21.10.0-SNAPSHOT

### PR DESCRIPTION
**Pull request by pxLi**
update cudf JNI version to 21.10.0, and preparing nightly artifact build

### CODE REVIEW

**Comment by pxLi** [comment]
Waiting for branch-21.10 CI ready

**Review by jlowe — APPROVED** [review]

**Comment by pxLi** [comment]
rerun tests

**Comment by pxLi** [comment]
rerun tests

**Comment by pxLi** [comment]
rerun tests

**Comment by pxLi** [comment]
rerun tests

**Comment by pxLi** [comment]
rerun tests

**Comment by pxLi** [comment]
@gpucibot merge

**Comment by pxLi** [comment]
@gpucibot merge

**Comment by pxLi** [comment]
@gpucibot merge

**Comment by ttnghia** [comment]
@gpucibot merge

**Pull request merged**
