### PR TITLE
Standardize newlines at ends of files.

### PR DESCRIPTION
**Pull request by bdice**
## Description
This PR makes all files end with exactly one newline and enforces that rule with a pre-commit hook. The vast majority of files already comply with this rule, which improves consistency in the library's code style.

## Checklist
- [x] I am familiar with the [Contributing Guidelines](https://github.com/rapidsai/cudf/blob/HEAD/CONTRIBUTING.md).
- [x] New or existing tests cover these changes.
- [x] The documentation is up to date with these changes.

### CODE REVIEW

**Comment by davidwendt** [comment]
Did I miss a vote on this somewhere?

**Comment by bdice** [comment]
> Did I miss a vote on this somewhere?

Not yet. I am opening a few standardization PRs like this and am planning to bring them up for discussion.

**Review by vuule — APPROVED** [review]

**Review by galipremsagar — APPROVED** [review]

**Review by vuule — APPROVED** [review]

**Review by msadang — APPROVED** [review]
LGTM

**Review by mroeschke — APPROVED** [review]

**Review by robertmaynard — APPROVED** [review]

**Review by ttnghia — APPROVED** [review]

**Comment by bdice** [comment]
@gpucibot merge

**Pull request merged**
