### PR TITLE
use libcu++ time_point as timestamp

### PR DESCRIPTION
**Pull request by karthikeyann**
Replace timestamp struct with libcu++ time_point as libcu++ time_point `__shared__` limitation is fixed.

### CODE REVIEW

**Comment by davidwendt** [comment]
Curious if this is also now fixed
https://github.com/rapidsai/cudf/blob/a9f15b8cab5c31813e5cf60720c55ac0f9b64601/cpp/tests/iterator/iterator_tests.cuh#L86-L87

**Review by cwharris — APPROVED** [review]

**Comment by rgsl888prabhu** [comment]
> Curious if this is also now fixed
> https://github.com/rapidsai/cudf/blob/a9f15b8cab5c31813e5cf60720c55ac0f9b64601/cpp/tests/iterator/iterator_tests.cuh#L86-L87

@karthikeyann Rest looks good, wauting on your reply for this.

**Review by ttnghia — APPROVED** [review]

**Comment by karthikeyann** [comment]
> > Curious if this is also now fixed
> > https://github.com/rapidsai/cudf/blob/a9f15b8cab5c31813e5cf60720c55ac0f9b64601/cpp/tests/iterator/iterator_tests.cuh#L86-L87
> 
> @karthikeyann Rest looks good, wauting on your reply for this.

Thanks @davidwendt 
This is fixed now.

**Review by rgsl888prabhu — APPROVED** [review]

**Review by jrhemstad — APPROVED** [review]

**Comment by karthikeyann** [comment]
@gpucibot merge

**Comment by karthikeyann** [comment]
rerun tests

**Pull request merged**
