### PR TITLE
Revert "Java API change for supporting structs (#7730)"

### PR DESCRIPTION
**Pull request by razajafri**
This reverts commit 3327f7be8eae964ea3c9fc9a025c4c67eacbe3d3.

We have to revert this because the dependent project is broken and my system is in a broken state.

### CODE REVIEW

**Review by rongou — APPROVED** [review]

**Review by rgsl888prabhu — APPROVED** [review]

**Review by revans2 — APPROVED** [review]

**Comment by rongou** [comment]
@gpucibot merge

**Comment by razajafri** [comment]
@gpucibot merge

**Comment by razajafri** [comment]
@gpucibot merge

**Comment by mythrocks** [comment]
Merged, at last! I wonder why it took that long.

**Pull request merged**
