### PR TITLE
Fix missing clone overrides on derived aggregations

### LINKED ISSUE #6891: [BUG] Java aggregation tests are crashing the JVM
**Describe the bug**
After #6392 some groupby aggregation tests in TableTest are failing.  One in particular is `testGroupByAvg` which tests mean aggregation.  The JVM crashes hard with no Java stacktrace.  Instead it terminates the process with this on stderr:
```
terminate called after throwing an instance of 'cudf::logic_error'
  what():  cuDF failure at: ../include/cudf/detail/aggregation/aggregation.cuh:436: Unsupported aggregation for initializing values
```

The odd thing is we wrap all libcudf calls with `catch (const std::exception&` which somehow is not catching this error and providing a stacktrace.

**Steps/Code to reproduce bug**
In the `java` directory execute `mvn test -Dtest=TableTest#testGroupByAvg`

**Expected behavior**
Aggregations do not crash

### PR DESCRIPTION
**Pull request by jlowe**
Fixes #6891 

Adds missing `clone()` overrides on aggregations that are derived but do not use `derived_aggregation`.

### CODE REVIEW

**Comment by GPUtester** [comment]
Please update the changelog in order to start CI tests.

View the gpuCI docs [here](https://docs.rapids.ai/gpuci#open-pr-or-update-pr).

**Review by harrism — APPROVED** [review]
Thanks for the fix.

**Review by mythrocks — APPROVED** [review]
Good catch, this.

**Review by abellina — APPROVED** [review]

**Comment by karthikeyann** [comment]
Great catch.

**Pull request merged**
