### PR TITLE
[REVIEW] Creating legacy for copying

### PR DESCRIPTION
**Pull request by rgsl888prabhu**
Creating legacy for copying.

### CODE REVIEW

**Comment by harrism** [comment]
@rgsl888prabhu this PR missed updating the benchmarks. Please open another PR that updates the benchmarks that include copying.hpp. You need to use `-DCMAKE_BUILD_BENCHMARKS=On` on the cmake configure command line. CI doesn't build benchmarks, which is why this didn't fail in CI.

**Comment by rgsl888prabhu** [comment]
@harrism should I also update for java files ?

**Comment by harrism** [comment]
If you feel comfortable. Otherwise we should ask @jlowe or @abellina?

**Comment by rgsl888prabhu** [comment]
> If you feel comfortable. Otherwise we should ask @jlowe or @abellina?

I have taken care

**Pull request merged**
