### PR TITLE
[REVIEW] CSV Reader: Avoid row offsets host vector default init

### LINKED ISSUE #2849: [BUG] CSV parser inits row offsets vector on CPU before GPU copy clobbers it
**Describe the bug**
`csv::reader::Impl::select_rows` constructs a vector of row offsets, `h_row_offsets`.  This can be a non-trivial size if a large amount of CSV data is being parsed with relatively few bytes per row.  The CPU zero-initializes this vector before it is clobbered by a GPU memcpy, and the CPU can spend many milliseconds performing this unnecessary initialization.

**Steps/Code to reproduce bug**
Take an nsight trace of `read_csv` on 2GB+ of CSV input and notice the gap of idle GPU time after the GPU counting kernels complete but before the `cudaMemcpyAsync` from device to host is issued.  This time gap is largely due to the CPU zero-initializing `h_row_offsets` which will ultimately be overwritten by the `cudaMemcpyAsync` call.

### PR DESCRIPTION
**Pull request by j-ieong**
Fixes #2849.

* Use `thrust::host_vector` to allow copy-assign from device_vector
* Call `column.finalize()` for final setup of columns

### CODE REVIEW

**Comment by harrism** [comment]
rerun tests

**Comment by j-ieong** [comment]
rerun tests

**Comment by mike-wendt** [comment]
rerun tests

**Comment by mike-wendt** [comment]
Had to redo tests do to a back hypothesis package that has now been reverted

**Comment by mike-wendt** [comment]
@kkraus14 @harrism This should be good to merge now

**Pull request merged**
