### PR TITLE
[REVIEW] ENH Add Java CI build script

### PR DESCRIPTION
**Pull request by dillon-cullinan**
Adds a build/test script for the Java component of cudf.

### CODE REVIEW

**Comment by dillon-cullinan** [comment]
test this

**Comment by dillon-cullinan** [comment]
test this

**Comment by dillon-cullinan** [comment]
test this

**Comment by dillon-cullinan** [comment]
test this

**Comment by dillon-cullinan** [comment]
test this

**Comment by dillon-cullinan** [comment]
test this

**Review by raydouglass — APPROVED** [review]

**Comment by dillon-cullinan** [comment]
@gpucibot merge

**Pull request merged**
