### PR TITLE
Add stream parameter to external dict APIs

### PR DESCRIPTION
**Pull request by SurajAralihalli**
## Description
This PR adds stream parameter to public dictionary APIs, which include:

1. `cudf::dictionary::encode`
2. `cudf::dictionary::decode`
3. `cudf::dictionary::get_index`
4. `cudf::dictionary::add_keys`
5. `cudf::dictionary::remove_keys`
6. `cudf::dictionary::remove_unused_keys`
7. `cudf::dictionary::set_keys` 
8. `cudf::dictionary::match_dictionaries`

Reference [13744](https://github.com/rapidsai/cudf/issues/13744)

## Checklist
- [X] I am familiar with the [Contributing Guidelines](https://github.com/rapidsai/cudf/blob/HEAD/CONTRIBUTING.md).
- [X] New or existing tests cover these changes.
- [X] The documentation is up to date with these changes.

### CODE REVIEW

**Comment by davidwendt** [comment]
Are you using these APIs or do you know anyone who is perhaps?

**Comment by SurajAralihalli** [comment]
> Are you using these APIs or do you know anyone who is perhaps?

I'm not aware of anyone who is using these APIs.

**Review by vyasr — COMMENTED** [review]
PR looks solid. Will approve once we see tests passing. Thanks for the contribution!

**Comment by vuule** [comment]
Some `DictionaryTest`s are failing with `C++ exception with description "cudf_identify_stream_usage found unexpected stream!" thrown in the test body.`

**Comment by vyasr** [comment]
@SurajAralihalli that failure indicates that somewhere in the call stack the stream is not being passed through and we're probably using `cudf::get_default_stream()` instead. You'll want to trace that back to its source. A debug build of cudf can be very helpful here, but it's also quite slow so manually tracking may be faster.

**Comment by SurajAralihalli** [comment]
Thankyou @vyasr for the tip!

This PR includes additional changes:

1. In the `column_wrapper.hpp` file, it explicitly provides `cudf::test::get_default_stream()` as an argument to the `cudf::dictionary::encode()` function.

2. In the `search.cu` file, a bug in the `find_index_fn` has been fixed. The bug involved the incorrect use of `cudf::get_default_stream()` instead of the `stream` variable.

**Comment by SurajAralihalli** [comment]
The code style check encountered an issue because there was an extra blank line in the CmakeLists.txt file. This occurred during the process of resolving merge conflicts on the GitHub UI and was not detected by the pre-commit checker on my local machine. I apologize for this oversight.

**Comment by vyasr** [comment]
> The code style check encountered an issue because there was an extra blank line in the CmakeLists.txt file. This occurred during the process of resolving merge conflicts on the GitHub UI and was not detected by the pre-commit checker on my local machine. I apologize for this oversight.

Good find! Let's see if tests pass this time around.

**Review by vyasr — APPROVED** [review]

**Pull request merged**
