### PR TITLE
[WIP] Selectively use dictionary encoding in Parquet writer

### PR DESCRIPTION
**Pull request by etseidl**
## Description
The current implementation of Zstd compression in nvcomp is limited to 64k chunk sizes.  In some cases, column chunks will not be compressed because the dictionary page exceeds this size, but the data pages do not.  This PR attempts to fix this by selectively disabling dictionary encoding when the dictionary page is too large.  Dictionary encoding will still be used if the data reduction from encoding exceeds a 4:1 ratio (4:1 is chosen rather arbitrarily and needs refinement).

This is a clumsy first attempt to gather feedback and suggestions for other approaches to try.  

## Checklist
- [X] I am familiar with the [Contributing Guidelines](https://github.com/rapidsai/cudf/blob/HEAD/CONTRIBUTING.md).
- [ ] New or existing tests cover these changes.
- [ ] The documentation is up to date with these changes.

### CODE REVIEW

**Comment by GPUtester** [comment]
Can one of the admins verify this patch?

Admins can comment `ok to test` to allow this one PR to run or `add to allowlist` to allow all future PRs from the same author to run.

**Comment by etseidl** [comment]
I'd also point out that the parquet_write_io_compression benchmark for Zstd with cardinality 0 and run_length 32 produces a file an order of magnitude larger than SNAPPY or no compression.  This is due to not using dictionary encoding on list columns that wind up far exceeding the requested 64k size and thus are also not compressed.  This is probably related to the fragment size issue in #12130.

**Comment by etseidl** [comment]
@jbrennan333 would you be able to run your tests against this branch?  I'm curious to see what effect it has on your file sizes.

**Comment by jbrennan333** [comment]
> @jbrennan333 would you be able to run your tests against this branch? I'm curious to see what effect it has on your file sizes.

Yes.  I will give this a try and let you know what impact it has.

**Comment by jbrennan333** [comment]
I ran NDS2.0 data conversion from raw (csv) to parquet-zstd at scale 100 and scale 3000 with this change.
At scale 100, the output data was nearly identical in size as without:
```
27570448	gpu_parquet_sf100_zstd
27570648	seidl_parquet_sf100_zstd
```
At scale 3000 though, this did seem to decrease the output file sizes:
```
      11.8 K       11.8 K            725.6 G /data/jimb/cpu_parquet_sf3k_decimal_zstd
      11.8 K       11.8 K            778.0 G /data/jimb/gpu_parquet_sf3k_decimal_zstd
      11.8 K       11.8 K            676.9 G /data/jimb/seidl_gpu_parquet_sf3k_decimal_zstd
```
Here are more details on the CPU sizes:
```
           1            2              1.2K /data/jimb/cpu_parquet_sf3k_decimal_zstd/income_band
           1            2              1.7K /data/jimb/cpu_parquet_sf3k_decimal_zstd/reason
           1            2              2.5K /data/jimb/cpu_parquet_sf3k_decimal_zstd/ship_mode
           1            2              5.7K /data/jimb/cpu_parquet_sf3k_decimal_zstd/warehouse
           1            2             15.2K /data/jimb/cpu_parquet_sf3k_decimal_zstd/call_center
           1            2             15.5K /data/jimb/cpu_parquet_sf3k_decimal_zstd/web_site
           1            2             18.0K /data/jimb/cpu_parquet_sf3k_decimal_zstd/household_demographics
           1            2             47.7K /data/jimb/cpu_parquet_sf3k_decimal_zstd/web_page
           1            2             57.2K /data/jimb/cpu_parquet_sf3k_decimal_zstd/promotion
           1            2             85.9K /data/jimb/cpu_parquet_sf3k_decimal_zstd/store
           1            2            482.3K /data/jimb/cpu_parquet_sf3k_decimal_zstd/time_dim
           1            2           1012.9K /data/jimb/cpu_parquet_sf3k_decimal_zstd/date_dim
           1            2              1.1M /data/jimb/cpu_parquet_sf3k_decimal_zstd/catalog_page
           1            2              5.3M /data/jimb/cpu_parquet_sf3k_decimal_zstd/customer_demographics
           1            2             19.5M /data/jimb/cpu_parquet_sf3k_decimal_zstd/item
           1            2            193.5M /data/jimb/cpu_parquet_sf3k_decimal_zstd/customer_address
           1            2              1.1G /data/jimb/cpu_parquet_sf3k_decimal_zstd/customer
         262          262              3.8G /data/jimb/cpu_parquet_sf3k_decimal_zstd/inventory
       2.1K        2.1K             11.8G /data/jimb/cpu_parquet_sf3k_decimal_zstd/web_returns
       2.1K        2.1K             24.5G /data/jimb/cpu_parquet_sf3k_decimal_zstd/catalog_returns
       2.0K        2.0K             35.4G /data/jimb/cpu_parquet_sf3k_decimal_zstd/store_returns
       1.8K        1.8K            108.0G /data/jimb/cpu_parquet_sf3k_decimal_zstd/web_sales
       1.8K        1.8K            235.4G /data/jimb/cpu_parquet_sf3k_decimal_zstd/catalog_sales
       1.8K        1.8K            305.5G /data/jimb/cpu_parquet_sf3k_decimal_zstd/store_sales
```
Here are the original GPU sizes:
```
           1            2                944 /data/jimb/gpu_parquet_sf3k_decimal_zstd/income_band
           1            2              1.4K /data/jimb/gpu_parquet_sf3k_decimal_zstd/reason
           1            2              2.0K /data/jimb/gpu_parquet_sf3k_decimal_zstd/ship_mode
           1            2              4.5K /data/jimb/gpu_parquet_sf3k_decimal_zstd/warehouse
           1            2             12.1K /data/jimb/gpu_parquet_sf3k_decimal_zstd/call_center
           1            2             12.8K /data/jimb/gpu_parquet_sf3k_decimal_zstd/web_site
           1            2             17.5K /data/jimb/gpu_parquet_sf3k_decimal_zstd/household_demographics
           1            2             48.4K /data/jimb/gpu_parquet_sf3k_decimal_zstd/web_page
           1            2             59.0K /data/jimb/gpu_parquet_sf3k_decimal_zstd/promotion
           1            2             87.0K /data/jimb/gpu_parquet_sf3k_decimal_zstd/store
           1            2            475.4K /data/jimb/gpu_parquet_sf3k_decimal_zstd/time_dim
           1            2            940.4K /data/jimb/gpu_parquet_sf3k_decimal_zstd/date_dim
           1            2              1.3M /data/jimb/gpu_parquet_sf3k_decimal_zstd/catalog_page
           1            2              5.1M /data/jimb/gpu_parquet_sf3k_decimal_zstd/customer_demographics
           1            2             45.5M /data/jimb/gpu_parquet_sf3k_decimal_zstd/item
           1            2            216.4M /data/jimb/gpu_parquet_sf3k_decimal_zstd/customer_address
           1            2              1.2G /data/jimb/gpu_parquet_sf3k_decimal_zstd/customer
         262          262              4.3G /data/jimb/gpu_parquet_sf3k_decimal_zstd/inventory
       2.1K        2.1K             12.4G /data/jimb/gpu_parquet_sf3k_decimal_zstd/web_returns
       2.1K        2.1K             26.4G /data/jimb/gpu_parquet_sf3k_decimal_zstd/catalog_returns
       2.0K        2.0K             39.2G /data/jimb/gpu_parquet_sf3k_decimal_zstd/store_returns
       1.8K        1.8K            117.9G /data/jimb/gpu_parquet_sf3k_decimal_zstd/web_sales
       1.8K        1.8K            241.7G /data/jimb/gpu_parquet_sf3k_decimal_zstd/catalog_sales
       1.8K        1.8K            334.6G /data/jimb/gpu_parquet_sf3k_decimal_zstd/store_sales
```
And here are the sizes with this change:
```
           1            2                944 /data/jimb/seidl_gpu_parquet_sf3k_decimal_zstd/income_band
           1            2              1.4K /data/jimb/seidl_gpu_parquet_sf3k_decimal_zstd/reason
           1            2              2.0K /data/jimb/seidl_gpu_parquet_sf3k_decimal_zstd/ship_mode
           1            2              4.5K /data/jimb/seidl_gpu_parquet_sf3k_decimal_zstd/warehouse
           1            2             12.1K /data/jimb/seidl_gpu_parquet_sf3k_decimal_zstd/call_center
           1            2             12.8K /data/jimb/seidl_gpu_parquet_sf3k_decimal_zstd/web_site
           1            2             17.5K /data/jimb/seidl_gpu_parquet_sf3k_decimal_zstd/household_demographics
           1            2             48.4K /data/jimb/seidl_gpu_parquet_sf3k_decimal_zstd/web_page
           1            2             59.0K /data/jimb/seidl_gpu_parquet_sf3k_decimal_zstd/promotion
           1            2             87.1K /data/jimb/seidl_gpu_parquet_sf3k_decimal_zstd/store
           1            2            475.4K /data/jimb/seidl_gpu_parquet_sf3k_decimal_zstd/time_dim
           1            2            940.4K /data/jimb/seidl_gpu_parquet_sf3k_decimal_zstd/date_dim
           1            2              1.3M /data/jimb/seidl_gpu_parquet_sf3k_decimal_zstd/catalog_page
           1            2              5.1M /data/jimb/seidl_gpu_parquet_sf3k_decimal_zstd/customer_demographics
           1            2             46.3M /data/jimb/seidl_gpu_parquet_sf3k_decimal_zstd/item
           1            2            216.4M /data/jimb/seidl_gpu_parquet_sf3k_decimal_zstd/customer_address
           1            2              1.2G /data/jimb/seidl_gpu_parquet_sf3k_decimal_zstd/customer
         262          262              4.2G /data/jimb/seidl_gpu_parquet_sf3k_decimal_zstd/inventory
       2.1K        2.1K             11.8G /data/jimb/seidl_gpu_parquet_sf3k_decimal_zstd/web_returns
       2.1K        2.1K             24.6G /data/jimb/seidl_gpu_parquet_sf3k_decimal_zstd/catalog_returns
       2.0K        2.0K             35.7G /data/jimb/seidl_gpu_parquet_sf3k_decimal_zstd/store_returns
       1.8K        1.8K            104.2G /data/jimb/seidl_gpu_parquet_sf3k_decimal_zstd/web_sales
       1.8K        1.8K            209.6G /data/jimb/seidl_gpu_parquet_sf3k_decimal_zstd/catalog_sales
       1.8K        1.8K            285.3G /data/jimb/seidl_gpu_parquet_sf3k_decimal_zstd/store_sales
```

**Comment by jbrennan333** [comment]
@etseidl I can put the item data (or at least some of it) somewhere where you can access it.  Note that your change did not make the item output  much bigger than the original gpu code.  I am running data conversion using NDS2.0, our version of TPC-DS benchmarks.  Here is the information about it: https://github.com/NVIDIA/spark-rapids-benchmarks/tree/main/nds
There is a fair bit of setup and then you need to run on spark with a spark-rapids plugin jar that was built with your cudf changes.
Overall at scale 3000, your patch improved the output size by 15%.  Seems like a win to me.

**Comment by jbrennan333** [comment]
I was able to upload the item files for CPU, GPU, and SEIDL by gzipping them.  Interesting that gzip barely changes the cpu size but brings the gpu files much closer to the cpu size.

[cpu-part-00000--c000.zstd.parquet.gz](https://github.com/rapidsai/cudf/files/10015817/cpu-part-00000--c000.zstd.parquet.gz)
[gpu-part-00000-c000.zstd.parquet.gz](https://github.com/rapidsai/cudf/files/10015818/gpu-part-00000-c000.zstd.parquet.gz)
[seidl-part-00000-c000.zstd.parquet.gz](https://github.com/rapidsai/cudf/files/10015819/seidl-part-00000-c000.zstd.parquet.gz)

**Comment by jbrennan333** [comment]
Uploading the parquet-tools inspect output for these.  Looks like some uncompressed columns is the main issue, which is what @vuule was trying to address in https://github.com/rapidsai/cudf/pull/12130.

[seidl-inspect.txt](https://github.com/rapidsai/cudf/files/10015942/seidl-inspect.txt)
[gpu-inspect.txt](https://github.com/rapidsai/cudf/files/10015943/gpu-inspect.txt)
[cpu-inspect.txt](https://github.com/rapidsai/cudf/files/10015944/cpu-inspect.txt)

**Comment by etseidl** [comment]
Thanks for the files!  I'm building the csv now, but can only do scale 1000 on my workstation.

Yes, the problem is the "item_desc" column not compressing, even though it's not using dictionary encoding.  Looking deeper the page sizes are just a tad over 64k, so that's why no compression happening.  If I use a 32KiB page size, then I wind up with the same file at 23.3MiB.  The row counts per page are at 625 which is consistent with @vuule's fragment size scaling (5000 * 512/64).  If the fragment size were a bit smaller then we'd see an improvement (I just tried fragment size = 4000 with 64k page size and got 22.97MiB).  

Feels like squeezing a balloon 😝

**Comment by jbrennan333** [comment]
I just re-ran with this change at scale 100.  I think when I ran it the first time, I accidentally ran with the original gpu version.
This time I got an improvement for scale 100 as well.
```
25G	seidl_parquet_sf100_zstd
26G	cpu_parquet_sf100_zstd
27G	gpu_parquet_sf100_zstd
```
Original GPU:
```
16K	gpu_parquet_sf100_zstd/income_band
16K	gpu_parquet_sf100_zstd/reason
16K	gpu_parquet_sf100_zstd/ship_mode
20K	gpu_parquet_sf100_zstd/warehouse
24K	gpu_parquet_sf100_zstd/call_center
24K	gpu_parquet_sf100_zstd/web_site
32K	gpu_parquet_sf100_zstd/household_demographics
40K	gpu_parquet_sf100_zstd/web_page
44K	gpu_parquet_sf100_zstd/store
48K	gpu_parquet_sf100_zstd/promotion
488K	gpu_parquet_sf100_zstd/time_dim
796K	gpu_parquet_sf100_zstd/catalog_page
960K	gpu_parquet_sf100_zstd/date_dim
5.0M	gpu_parquet_sf100_zstd/customer_demographics
16M	gpu_parquet_sf100_zstd/customer_address
27M	gpu_parquet_sf100_zstd/item
82M	gpu_parquet_sf100_zstd/customer
435M	gpu_parquet_sf100_zstd/web_returns
887M	gpu_parquet_sf100_zstd/catalog_returns
1.3G	gpu_parquet_sf100_zstd/store_returns
1.6G	gpu_parquet_sf100_zstd/inventory
3.8G	gpu_parquet_sf100_zstd/web_sales
7.8G	gpu_parquet_sf100_zstd/catalog_sales
11G	gpu_parquet_sf100_zstd/store_sales
```
With this patch:
```
16K	seidl_parquet_sf100_zstd/income_band
16K	seidl_parquet_sf100_zstd/reason
16K	seidl_parquet_sf100_zstd/ship_mode
20K	seidl_parquet_sf100_zstd/warehouse
24K	seidl_parquet_sf100_zstd/call_center
24K	seidl_parquet_sf100_zstd/web_site
32K	seidl_parquet_sf100_zstd/household_demographics
40K	seidl_parquet_sf100_zstd/web_page
44K	seidl_parquet_sf100_zstd/store
48K	seidl_parquet_sf100_zstd/promotion
488K	seidl_parquet_sf100_zstd/time_dim
796K	seidl_parquet_sf100_zstd/catalog_page
960K	seidl_parquet_sf100_zstd/date_dim
5.0M	seidl_parquet_sf100_zstd/customer_demographics
16M	seidl_parquet_sf100_zstd/customer_address
27M	seidl_parquet_sf100_zstd/item
82M	seidl_parquet_sf100_zstd/customer
435M	seidl_parquet_sf100_zstd/web_returns
887M	seidl_parquet_sf100_zstd/catalog_returns
1.3G	seidl_parquet_sf100_zstd/store_returns
1.6G	seidl_parquet_sf100_zstd/inventory
3.7G	seidl_parquet_sf100_zstd/web_sales
7.3G	seidl_parquet_sf100_zstd/catalog_sales
9.7G	seidl_parquet_sf100_zstd/store_sales
```

**Comment by etseidl** [comment]
@jbrennan333 thanks for all your help!  I'm starting to think this work needs to build on what @vuule did with scaling the fragment size, but add some feedback to find a fragment size smaller than the page size limit.  I think that will be valuable even if the nvComp team ultimately increases the zStd chunk size.

**Comment by vuule** [comment]
Hey, it's even smaller than the CPU version! Very promising :)

> add some feedback to find a fragment size smaller than the page size limit
Could you expand on this?

**Comment by jbrennan333** [comment]
Agreed that some combination of these features may ultimately be what we need.  I did try running at 3TB with this change and with `max_page_fragment_size = 4000`.  The result was worse (larger output sizes):
```
      11.8 K       11.8 K            725.6 G /data/jimb/cpu_parquet_sf3k_decimal_zstd
      11.8 K       11.8 K            778.0 G /data/jimb/gpu_parquet_sf3k_decimal_zstd
      11.8 K       11.8 K            676.9 G /data/jimb/seidl_gpu_parquet_sf3k_decimal_zstd
      11.8 K       11.8 K            812.0 G /data/jimb/vukasin_gpu_parquet_sf3k_decimal_zstd
      11.8 K       11.8 K            939.6 G /data/jimb/seidl-vukasin_gpu_parquet_sf3k_decimal_zstd
```
Where `seidl-vukasin` is this change with `max_page_fragment_size = 4000` and `vukasin` is just the `max_page_fragment_size = 1000` change.
Most of the difference in this case was in store_sales:
```
       1.8K        1.8K            285.3G /data/jimb/seidl_gpu_parquet_sf3k_decimal_zstd/store_sales
       1.8K        1.8K            334.6G /data/jimb/gpu_parquet_sf3k_decimal_zstd/store_sales
       1.8K        1.8K            351.7G /data/jimb/vukasin_gpu_parquet_sf3k_decimal_zstd/store_sales
       1.8K        1.8K            528.2G /data/jimb/seidl-vukasin_gpu_parquet_sf3k_decimal_zstd/store_sales
```
So far the best results I've gotten have been with this change alone.  Let me know if you want me to try anything else.

**Comment by etseidl** [comment]
Yikes!  Fix one file, break another.  Still can't quite understand why a smaller fragment size would make things that much worse. I've got the CSVs now, so hopefully I can get the spark plugin to work with my library soon.  

> Could you expand on this?

@vuule Basically implement the suggestion in writer_impl.cu above max_page_fragment_size (TODO on line 1406).  Maybe do 2 passes when doing InitPageFragments/InitPages.  Hopefully there's a way that's less time consuming than running those kernels twice.  Ofc the nested data will make this tricky.  Maybe different fragment sizes per column???  

Oh, just got word from Eric Schmidt that nvComp 2.5 will support 1MB chunks, so maybe this will become moot.  Should we just wait on that and try again?

**Comment by vuule** [comment]
I wonder if the size increase from reduced fragment size is even related to ZSTD (really shouldn't be :grimacing: ). Would be interesting to see comparison with Snappy as well.

**Comment by etseidl** [comment]
Ahhhh, this is crazy.  So with frag size at 5000, the scaled down value for 64k page size is 625.  For the list_price column I wind up with row counts/page of 16250, which results in page sizes just under 64k, so that column compresses nicely with zstd.  With frag size at 4000, the scaled value is 500, and I wind up with 16500 rows/page, which gives sizes just over 64k, so no compression at all.  The default behavior winds up selecting dictionary encoding with no compression.  For a single partition I wind up with the list_price chunk taking 233KB with the original code, 205KB with frag_size=5000, and 340KB with frag_size=4000.  

This is going to take some more thought 😛

**Comment by vuule** [comment]
Well, at least we hit this kind of odd case early on :)

The fragment size of 1000 should avoid this kind of issue since we should build the exact same pages from 5x fragments (or pages that adhere better to the 64K limit). It's still performing worse than the default 😠

**Comment by etseidl** [comment]
Actually, 1000 will use fragment size of 125 (scaled), so will likely wind up at 16500 rows/page again.

I'm actually wondering why the fragment size is still yielding pages just over 64k.  There must be overhead not accounted for by just summing the fragment sizes.  Perhaps we're missing the vectors for definition and repetition levels in the page size calculation.

**Comment by etseidl** [comment]
@jbrennan333 could you try the latest from this branch with scale=3000?  I think I fixed the page size issue, and lowered the fragment size back to 1000 like @vuule did.  This produced a 9.7G store_sales table for scale=100 and a total size of 25G.

**Comment by jbrennan333** [comment]
> @jbrennan333 could you try the latest from this branch with scale=3000? I think I fixed the page size issue, and lowered the fragment size back to 1000 like @vuule did. This produced a 9.7G store_sales table for scale=100 and a total size of 25G.

I will try it.

**Comment by jbrennan333** [comment]
@etseidl with the latest patch, I got nearly identical results as compared to the original patch for this issue.
```
      11.8K       11.8K            675.4G /data/jimb/seidl-221116_gpu_parquet_sf3k_decimal_zstd
      11.8K       11.8K            676.9G /data/jimb/seidl_gpu_parquet_sf3k_decimal_zstd
      11.8K       11.8K            725.6G /data/jimb/cpu_parquet_sf3k_decimal_zstd
      11.8K       11.8K            778.0G /data/jimb/gpu_parquet_sf3k_decimal_zstd
```
Original patch:
```
...
           1            2              1.2G /data/jimb/seidl_gpu_parquet_sf3k_decimal_zstd/customer
         262          262              4.2G /data/jimb/seidl_gpu_parquet_sf3k_decimal_zstd/inventory
       2.1K        2.1K             11.8G /data/jimb/seidl_gpu_parquet_sf3k_decimal_zstd/web_returns
       2.1K        2.1K             24.6G /data/jimb/seidl_gpu_parquet_sf3k_decimal_zstd/catalog_returns
       2.0K        2.0K             35.7G /data/jimb/seidl_gpu_parquet_sf3k_decimal_zstd/store_returns
       1.8K        1.8K            104.2G /data/jimb/seidl_gpu_parquet_sf3k_decimal_zstd/web_sales
       1.8K        1.8K            209.6G /data/jimb/seidl_gpu_parquet_sf3k_decimal_zstd/catalog_sales
       1.8K        1.8K            285.3G /data/jimb/seidl_gpu_parquet_sf3k_decimal_zstd/store_sales
```
Current patch:
```
...
           1            2              1.2G /data/jimb/seidl-221116_gpu_parquet_sf3k_decimal_zstd/customer
         262          262              4.2G /data/jimb/seidl-221116_gpu_parquet_sf3k_decimal_zstd/inventory
       2.1K        2.1K             11.7G /data/jimb/seidl-221116_gpu_parquet_sf3k_decimal_zstd/web_returns
       2.1K        2.1K             24.5G /data/jimb/seidl-221116_gpu_parquet_sf3k_decimal_zstd/catalog_returns
       2.0K        2.0K             35.5G /data/jimb/seidl-221116_gpu_parquet_sf3k_decimal_zstd/store_returns
       1.8K        1.8K            104.2G /data/jimb/seidl-221116_gpu_parquet_sf3k_decimal_zstd/web_sales
       1.8K        1.8K            209.5G /data/jimb/seidl-221116_gpu_parquet_sf3k_decimal_zstd/catalog_sales
       1.8K        1.8K            284.4G /data/jimb/seidl-221116_gpu_parquet_sf3k_decimal_zstd/store_sales
```
I don't know if there is still time to get a version of this patch into 22.12.  @vuule what to you think?

**Comment by vuule** [comment]
@jbrennan333 it's pretty late in the release cycle and the code that disables dictionaries is fairly experimental. Is there enough benefit from page size fix + fragment size reduction to warrant a late merge into 22.12?

**Comment by jbrennan333** [comment]
> @jbrennan333 it's pretty late in the release cycle and the code that disables dictionaries is fairly experimental. Is there enough benefit from page size fix + fragment size reduction to warrant a late merge into 22.12?

I agree that this is still too experimental to try pushing into 22.12 at this point.  We'll likely want to see how this works with the larger chunk sizes coming in nvcomp-2.5 as well.

**Comment by etseidl** [comment]
Ok, so no rush.  I think I've got what I want out of this round, @vuule should I close this for now until nvcomp 2.5 is out?  I didn't realize how late in the 22.12 cycle it was 😅 

In the mean time I want to look into the possibility of different fragment sizes per column, so we can handle flat fixed-width data one way, and variable width/nested data differently.  I think I also want to add some options to control dictionary use (globally at first, maybe per column later like parquet-mr does).

**Comment by vuule** [comment]
> @vuule should I close this for now until nvcomp 2.5 is out?

My preference would be to merge page size fix + fragment size reduction early into 23.02, the improvements are not limited to ZSTD use case.
Not sure about the dictionary changes, as they do become less relevant with nvCOMP 2.5. Maybe we should revisit that part once 2.5 is out?

> In the mean time I want to look into the possibility of different fragment sizes per column, so we can handle flat fixed-width data one way, and variable width/nested data differently. I think I also want to add some options to control dictionary use (globally at first, maybe per column later like parquet-mr does).

These sound great! I've also been thinking about per-column fragment size (IIRC, we do have functions that get the data size in a column), but haven't had time to prototype it yet.

**Comment by etseidl** [comment]
> My preference would be to merge page size fix + fragment size reduction early into 23.02, the improvements are not limited to ZSTD use case.

Ok, sounds good.  I'll rebase on 23.02 and submit again.

> Not sure about the dictionary changes, as they do become less relevant with nvCOMP 2.5. Maybe we should revisit that part once 2.5 is out?

Again, sounds good.  I still think the dictionary changes will be relevant...I've seen dictionaries > 1MB.  But no sense doing much on that front until 2.5 is available.  Maybe I can get a pre-release to start testing with.

> These sound great! I've also been thinking about per-column fragment size (IIRC, we do have functions that get the data size in a column), but haven't had time to prototype it yet.

Sounds like you're ahead of me on this one...for flat columns not a big issue, but handling the nested ones...

**Pull request closed without merging**
