### PR TITLE
Minor `cudf::round` internal refactoring

### PR DESCRIPTION
**Pull request by codereport**
This is a small cleanup that replaces a `cudf::binary_operation` with a much cleaner `cudf::cast`.

### CODE REVIEW

**Comment by beckernick** [comment]
Not specifically relevant for this PR, but does the existence of cudf::round mean we can rip out this code (and it's associated uses in the Python layer)

https://github.com/rapidsai/cudf/blob/598a14d820d47b7c3bfcb2bb3341b97a85317646/python/cudf/cudf/utils/cudautils.py#L72-L88
https://github.com/rapidsai/cudf/blob/598a14d820d47b7c3bfcb2bb3341b97a85317646/python/cudf/cudf/utils/utils.py#L53-L70

**Review by vuule — APPROVED** [review]

**Comment by codereport** [comment]
> Not specifically relevant for this PR, but does the existence of cudf::round mean we can rip out this code (and its associated uses in the Python layer) and plumb cudf::round up?

@beckernick I can't be certain but based on the code it looks like it.

**Comment by harrism** [comment]
Can you explain why this works? (why is it possible to replace a multiply with a cast?)

**Comment by codereport** [comment]
> Can you explain why this works? (why is it possible to replace a multiply with a cast?)

At the time I implemented `cudf::round`, we didn't have `cudf::cast` for `fixed_point` which is really what we wanted. So using a `cudf::binary_operation` and multiplying by `10^(difference in scales)` is basically just a hacky way of doing the same thing.
```cpp
    auto const scalar = cudf::make_fixed_point_scalar<T>(std::pow(10, diff), scale_type{-diff});	
    return cudf::detail::binary_operation(input, *scalar, cudf::binary_operator::MUL, {}, stream, mr);
```
If you compare this to `cudf::cast` implementation it is very similar.

**Review by harrism — APPROVED** [review]

**Comment by harrism** [comment]
I don't think "Small `cudf::round` cleanup " is a good changelog message. We have to be more careful with PR titles now that CHangelog is automated.

**Comment by codereport** [comment]
> I don't think "Small `cudf::round` cleanup " is a good changelog message. We have to be more careful with PR titles now that CHangelog is automated.

Is `Minor cudf::round internal refactoring` better?

**Comment by harrism** [comment]
Nevermind. I guess for a PR like this it's impossible to provide a clear description smaller than the code change itself.

**Comment by codereport** [comment]
> Nevermind. I guess for a PR like this it's impossible to provide a clear description smaller than the code change itself.

Yea, for "code cleanup" PRs I don't think describing the refactoring will be meaningful to our users. Mostly they care about bug fixes, new features and performance enhancements.

**Comment by harrism** [comment]
Yeah, I guess you are right. The original title would be fine in that case.

**Pull request merged**
