### PR TITLE
[REVIEW] Upgrade `clang` to 11.1.0

### PR DESCRIPTION
**Pull request by galipremsagar**
This PR upgrades `clang` to `11.1.0`. The version upgrade is required because, `clang-11=11.0.0` needs `libclang-cpp11-11.0.0` which needs `libllvm11=11.0.1` only. But for https://github.com/rapidsai/cudf/pull/9687 to work, `numba-0.54` has to be installed which needs `llvmlite 0.37.*` which requires `libllvm11 >=11.1.0,<11.2.0a0`

### CODE REVIEW

**Review by raydouglass — APPROVED** [review]

**Comment by galipremsagar** [comment]
rerun tests

**Comment by quasiben** [comment]
rerun tests

**Comment by quasiben** [comment]
rerun tests

**Comment by quasiben** [comment]
rerun tests

**Comment by galipremsagar** [comment]
rerun tests

**Comment by quasiben** [comment]
rerun tests

**Review by nvdbaranec — APPROVED** [review]

**Comment by galipremsagar** [comment]
rerun tests

**Comment by jakirkham** [comment]
rerun tests

**Review by ajschmidt8 — APPROVED** [review]

**Comment by karthikeyann** [comment]
Is this merged to 22.02 as well?

**Comment by galipremsagar** [comment]
> Is this merged to `branch-22.02` as well?

Yes, with https://github.com/rapidsai/cudf/pull/9721

**Pull request merged**
