### PR TITLE
Allow newer scikit-build

### PR DESCRIPTION
**Pull request by vyasr**
## Description

This PR attempts to allow using newer versions of scikit-build again.

cf. https://github.com/rapidsai/cudf/pull/13188

## Checklist
- [x] I am familiar with the [Contributing Guidelines](https://github.com/rapidsai/cudf/blob/HEAD/CONTRIBUTING.md).
- [x] New or existing tests cover these changes.
- [x] The documentation is up to date with these changes.

### CODE REVIEW

**Comment by henryiii** [comment]
If you'd like to keep this simpler, I can yank those two releases.

**Comment by bdice** [comment]
Yes, just wanted to say thank you for your quick responses with those fixed releases earlier and also for yanking the broken packages @henryiii. 💯

This looks good to me @vyasr, I'll approve.

**Review by bdice — APPROVED** [review]

**Review by ajschmidt8 — APPROVED** [review]

**Review by wence- — APPROVED** [review]
/merge

**Pull request merged**
