### PR TITLE
Support polars 1.14

### PR DESCRIPTION
**Pull request by wence-**
## Description

1.13 was yanked for some reason, but 1.14 doesn't bring anything new and difficult.

## Checklist
- [x] I am familiar with the [Contributing Guidelines](https://github.com/rapidsai/cudf/blob/HEAD/CONTRIBUTING.md).
- [x] New or existing tests cover these changes.
- [x] The documentation is up to date with these changes.

### CODE REVIEW

**Review by vyasr — APPROVED** [review]

**Review by brandon-b-miller — APPROVED** [review]

**Review by galipremsagar — APPROVED** [review]

**Comment by davidwendt** [comment]
Looks like something is causing the `cudf-polars-polars-test` to hang.
https://github.com/rapidsai/cudf/actions/runs/11898001278/job/33164817268?pr=17355

**Comment by vyasr** [comment]
Based on the first run of that job it looks like the test that it's waiting on is indeed something that could hang :( 
```
py-polars/tests/unit/test_plugins.py::test_is_dynamic_lib_dir PASSED     [ 95%]
context canceled
py-polars/tests/unit/test_polars_import.py::test_fork_safety 
Error: The operation was canceled.
```

**Comment by wence-** [comment]
> Based on [the first run of that job](https://github.com/rapidsai/cudf/actions/runs/11898001278/job/33154961721?pr=17355#step:9:13561) it looks like the test that it's waiting on is indeed something that could hang :(
> 
> ```
> py-polars/tests/unit/test_plugins.py::test_is_dynamic_lib_dir PASSED     [ 95%]
> context canceled
> py-polars/tests/unit/test_polars_import.py::test_fork_safety 
> Error: The operation was canceled.
> ```

Add that one to deselected tests, I forgot sorry

**Comment by galipremsagar** [comment]
> Add that one to deselected tests, I forgot sorry

Done

**Pull request merged**
