### PR TITLE
Add anonymous namespace to libcudf test source

### LINKED ISSUE #17432: [BUG] Cannot use `cudf::test::iterators::nulls_at ()` in `.cu` test file
When using `cudf::test::iterators::nulls_at ()` in `.cu` test file, I got this error:
```
error #20011-D: calling a __host__ function("std::vector<int, ::std::allocator<int> > ::vector(const ::std::vector<int, ::std::allocator<int> > &)") 
from a __host__ __device__ function("auto ::cudf::test::iterators::nulls_at< ::__gnu_cxx::__normal_iterator<const int *,     ::std::vector<int, ::std::allocator<int> > > > (T1, T1)::[lambda(T1) (instance 1)]::[lambda(T1) (instance 1)]") 
  is not allowed
```
Notice that the implementation of that function is:
```
template <typename Iter>
[[maybe_unused]] static auto nulls_at(Iter index_start, Iter index_end)
{
  using index_type = typename std::iterator_traits<Iter>::value_type;

  return cudf::detail::make_counting_transform_iterator(
    0, [indices = std::vector<index_type>{index_start, index_end}](auto i) {
      return std::find(indices.cbegin(), indices.cend(), i) == indices.cend();
    });
}
```
which initializes `std::vector<index_type>` upon creating the lambda, causing that issue.

### PR DESCRIPTION
**Pull request by davidwendt**
## Description
Uses anonymous namespace declaration on internal only functions and structures in the libcudf gtest source. This helps prevent odd nvcc compile errors like the one described in #17432 

Closes #17432 

## Checklist
- [x] I am familiar with the [Contributing Guidelines](https://github.com/rapidsai/cudf/blob/HEAD/CONTRIBUTING.md).
- [x] New or existing tests cover these changes.
- [x] The documentation is up to date with these changes.

### CODE REVIEW

**Review by vyasr — APPROVED** [review]
Good change. Perhaps we should also be adding some symbol visibility markup to `cudf::tests` functions if they are causing further problems? It looks like the function Nghia originally ran into was in the test util and not a test.

**Comment by davidwendt** [comment]
> Good change. Perhaps we should also be adding some symbol visibility markup to `cudf::tests` functions if they are causing further problems? It looks like the function Nghia originally ran into was in the test util and not a test.

I think that is something separate to consider but the visibility issue here was in the global namespace and not in the `cudf::test` one. I believe the error in the linked issue was just a unfortunate side-effect which would not have been fixed by hiding the `cudf::test` symbols.

**Review by karthikeyann — APPROVED** [review]

**Pull request merged**
