### PR TITLE
[REVIEW]  Replace shuffle warp reduce with cub calls

### PR DESCRIPTION
**Pull request by kaatish**
Redo 6206

### CODE REVIEW

**Comment by GPUtester** [comment]
Please update the changelog in order to start CI tests.

View the gpuCI docs [here](https://docs.rapids.ai/gpuci#open-pr-or-update-pr).

**Comment by kaatish** [comment]
rerun tests

**Comment by vuule** [comment]
rerun tests

**Comment by vuule** [comment]
The CI passed two times with all changes, should be good!

**Review by vuule — APPROVED** [review]
I've already tried to find anything wrong with the changes and failed (see [#6283](https://github.com/rapidsai/cudf/pull/6283)). The new changes to temp storage look good too.

**Comment by vuule** [comment]
Adding @cwharris to review, since he reviewed the original PR.

**Review by cwharris — APPROVED** [review]
lgtm :rocket:

**Comment by OlivierNV** [comment]
This PR will break the float sum statistics when NaNs are present.

**Comment by harrism** [comment]
Do we not have test coverage for that? @vuule

**Comment by vuule** [comment]
> Do we not have test coverage for that? @vuule

Went over the Parquet and ORC tests, and could not find any tests for statistics. Definitely nothing with NaN values. We might have a bigger coverage hole here.

**Comment by harrism** [comment]
Thanks.

**Comment by vuule** [comment]
Thanks @OlivierNV . We completely missed the `isnan` check in there.

To me it looks like the fix is simple - provide a custom functor to the `WarpReduce` call instead of `Sum`, and this functor would check for NaN, as the old code did.
@kaatish does this sound correct?

On the other hand, I don't know how to test the fix. Will look into this.

**Comment by kaatish** [comment]
@vuule A custom functor is probably not required. We can just check whether the local variable is nan or not and set it to 0 if it is so that is passed onto the cub::WarpReduce. Like [this](https://github.com/rapidsai/cudf/pull/6366/files#diff-b0afb690571766a18692674e5854e92e).

**Pull request merged**
