### PR TITLE
Refactor tests/groupby/**

### PR DESCRIPTION
**Pull request by ttnghia**
No change in code/implementation by this PR. It only renames the test files in the folder `tests/groupby`. In particular:
 * It removes the prefixes `group_` and `groupby_` from all the file names in that folder. 
 * The file suffix `_test.cpp` is changed to `_tests.cpp` to enforce consistency with other test files.

The reasons for doing this PR are:
 * Files in this folder have inconsistent prefixes (`group_` and `groupby_`).
 * Adding folder name (`groupby_` or `group_`) as prefixes to the test files is not necessary. Those tests are already in the folder name `groupby`.
 * We should enforce consistency following the cudf dev guide: https://github.com/rapidsai/cudf/blob/branch-0.19/cpp/docs/TESTING.md#directory-and-file-naming.

### CODE REVIEW

**Comment by ttnghia** [comment]
Rerun tests.

**Comment by devavret** [comment]
> * Their names (`group_` and `groupby_`) already show such inconsistency.

This is intentional. `group_` prefix is for the aggregation. `group_max_test` is a test that checks our ability to get each "group's max". `groupby_` prefix is only meant for keys. It is a test of our ability to "group by different key types". The only inconsistency is in `groupby_groups_test` which was added later.

**Comment by ttnghia** [comment]
> > * Their names (`group_` and `groupby_`) already show such inconsistency.
> 
> This is intentional. `group_` prefix is for the aggregation. `group_max_test` is a test that checks our ability to get each "group's max". `groupby_` prefix is only meant for keys. It is a test of our ability to "group by different key types". The only inconsistency is in `groupby_groups_test` which was added later.

Do you mean only `groupby_groups_test` needs to be renamed, the other files must remain intact?

**Comment by devavret** [comment]
> the other files must remain intact?

I was just explaining the rationale behind the original names. If they still make sense with a smaller name then we should have a smaller name.

**Comment by mythrocks** [comment]
>  I think I should push this ASAP so other people can sync ASAP.

Curious: Why is this urgent?

**Comment by ttnghia** [comment]
Not "urgent", just in case somebody is adding new test files to this folder then they can avoid adding those prefixes, so I can avoid refactoring again their files in the future when I merge my PR.

**Comment by ttnghia** [comment]
> > the other files must remain intact?
> 
> I was just explaining the rationale behind the original names. If they still make sense with a smaller name then we should have a smaller name.

Alright, then we need to change the file names, since those files are already in the `groupby` folder, which means they belong to `groupby`.

**Comment by mythrocks** [comment]
> Not "urgent", just in case somebody is adding new test files...

I wonder if it might be acceptable to reserve aesthetic/compliance changes for `branch-0.20`, given how close we are to `branch-0.19` burn-down. 
This sort of thing will cause last minute churn for those making material changes to group-by tests.

**Comment by ttnghia** [comment]
I don't think it will affect anything, as it only renames files instead of changing any implementation.

**Comment by ttnghia** [comment]
Moved this PR to v0.2 release to avoid extra work for the team as v0.19 is near its burn-down stage.

**Comment by karthikeyann** [comment]
After #7387, this PR require more tests files renamed.

**Comment by ttnghia** [comment]
Currently blocked by: 
https://github.com/rapidsai/cudf/pull/7763
https://github.com/rapidsai/cudf/pull/7759

**Comment by ajschmidt8** [comment]
Removing `ops-codeowners` from the required reviews since it doesn't seem there are any file changes that we're responsible for. Feel free to add us back if necessary.

**Review by karthikeyann — APPROVED** [review]

**Review by harrism — APPROVED** [review]

**Comment by harrism** [comment]
@gpucibot merge

**Pull request merged**
