### PR TITLE
[REVIEW] Add support for `make_meta_obj` dispatch in `dask-cudf`

### PR DESCRIPTION
**Pull request by galipremsagar**
Fixes: #7946 

This PR is dependent on upstream dask changes that are needed for a portion of the fix: https://github.com/dask/dask/pull/7586/files

This PR includes changes to introduce `make_meta_obj` which will ensure proper metadata is retrieved from the parent_meta being passed in the upstream PR.

### CODE REVIEW

**Review by jakirkham — APPROVED** [review]

**Comment by jakirkham** [comment]
@gpucibot merge

**Comment by jakirkham** [comment]
rerun tests

**Comment by galipremsagar** [comment]
> rerun tests

This PR is dependent on dask upstream changes: https://github.com/dask/dask/pull/7586

**Review by kkraus14 — APPROVED** [review]

**Comment by galipremsagar** [comment]
rerun tests

**Comment by jakirkham** [comment]
@gpucibot merge

**Comment by jakirkham** [comment]
Looks like the build is failing on the C++ side due to the DLPack issue being addressed in PR ( https://github.com/rapidsai/cudf/pull/8262 )

**Comment by kkraus14** [comment]
rerun tests

**Comment by galipremsagar** [comment]
rerun tests

**Comment by galipremsagar** [comment]
@gpucibot merge

**Comment by jakirkham** [comment]
The failure here is coming from Dask-CUDA, which will be fixed with PR ( https://github.com/rapidsai/dask-cuda/pull/623 ). However that PR also requires this PR to pass. Looks like we may need an admin merge here as well

**Comment by galipremsagar** [comment]
> The failure here is coming from Dask-CUDA, which will be fixed with PR ( [rapidsai/dask-cuda#623](https://github.com/rapidsai/dask-cuda/pull/623) ). However that PR also requires this PR to pass. Looks like we may need an admin merge here as well

yeah cc: @kkraus14

**Pull request merged**
