### PR TITLE
Fill out pylibcudf `binaryop` enum entries

### PR DESCRIPTION
**Pull request by brandon-b-miller**
This PR exposes through `pylibcudf` the set of `libcudf` binary operations which have not yet been wrapped/consumed for a specific cuDF cython usecase.

### CODE REVIEW

**Comment by vyasr** [comment]
We discussed plans offline. Brandon is going to add tests here while I open up a separate PR for tests in another module, then we can collaborate and iterate to establish some shared best practices for pylibcudf testing going forward.

**Comment by vyasr** [comment]
#15300 is where I'm working on tests now.

**Comment by wence-** [comment]
@vyasr / @brandon-b-miller this stalled due to discussion about testing, but I think that was resolved. Is the testing part of this done in #15470?

**Comment by brandon-b-miller** [comment]
Closing in favor of https://github.com/rapidsai/cudf/pull/15470

**Pull request closed without merging**
