### PR TITLE
[REVIEW] Switch JNI code to use the RMM owning wrapper [skip ci]

### PR DESCRIPTION
**Pull request by rongou**
@revans2 @jlowe @jrhemstad

### CODE REVIEW

**Comment by GPUtester** [comment]
Please update the changelog in order to start CI tests.

View the gpuCI docs [here](https://docs.rapids.ai/gpuci#open-pr-or-update-pr).

**Comment by jlowe** [comment]
> Each memory allocation will also include a shared_ptr to that same device_memory_resource

Where is that occurring?  `cudf::column` tracks the resource indirectly via `rmm::device_buffer,  and that [tracks the memory resource via a raw pointer](https://github.com/rapidsai/rmm/blob/branch-0.15/include/rmm/device_buffer.hpp#L390).

**Comment by jrhemstad** [comment]
> > Each memory allocation will also include a shared_ptr to that same device_memory_resource
> 
> Where is that occurring? `cudf::column` tracks the resource indirectly via `rmm::device_buffer`, and that [tracks the memory resource via a raw pointer](https://github.com/rapidsai/rmm/blob/branch-0.15/include/rmm/device_buffer.hpp#L390).

Jason is correct. Leaked allocations will _not_ keep a resource alive. All `owning_wrapper` does is allow a resource to own its Upstream resources so that the user does not have to separately manage their lifetimes.

**Comment by jlowe** [comment]
> All owning_wrapper does is allow a resource to own its Upstream resources so that the user does not have to separately manage their lifetimes.

If that's the case, then I'm not sure what this change is accomplishing other than switching from one API to another.  

@rongou does this change/fix anything semantically?  I still see a corresponding global variable for each memory resource which is managing the lifetimes by keeping them referenced.

**Comment by rongou** [comment]
One thing it fixes is the memory leak from `new managed_mr()` and `new cuda_mr()`.

**Pull request merged**
