### PR TITLE
Remove deprecated `method` parameter from `merge` and `join`.

### LINKED ISSUE #9353: [DEPRECATION] Remove `method` parameters to `merge` and `join` in v22.02
https://github.com/rapidsai/cudf/pull/9291 deprecates the `method` parameter, which should be removed in 22.02. ~Note, I put this under the 21.12 project board for now, so that we don't lose track of it. Needs to be moved to the 22.02 board when it's available.~

### PR DESCRIPTION
**Pull request by bdice**
This PR removes the deprecated `method` parameter from `DataFrame.merge` and `DataFrame.join`. This resolves #9353 and follows up on #9291.

### CODE REVIEW

**Review by galipremsagar — APPROVED** [review]

**Comment by galipremsagar** [comment]
rerun tests

**Comment by galipremsagar** [comment]
rerun tests

**Comment by vyasr** [comment]
@bdice looks like there are a couple more tests that need fixing here.

**Comment by bdice** [comment]
@gpucibot merge

**Comment by bdice** [comment]
@gpucibot merge

**Pull request merged**
