### PR TITLE
Remove `build_struct|list_column`

### PR DESCRIPTION
**Pull request by mroeschke**
## Description
IMO these do not provide much value compared to constructing with `ListColumn` or `StructColumn` cc https://github.com/rapidsai/cudf/pull/14778#discussion_r1457932822

## Checklist
- [ ] I am familiar with the [Contributing Guidelines](https://github.com/rapidsai/cudf/blob/HEAD/CONTRIBUTING.md).
- [ ] New or existing tests cover these changes.
- [ ] The documentation is up to date with these changes.

### CODE REVIEW

**Review by isVoid — CHANGES_REQUESTED** [review]
Since these APIs are also used in cuspatial, would you mind making a PR to cuSpatial replacing these uses?

**Comment by mroeschke** [comment]
> Since these APIs are also used in cuspatial, would you mind making a PR to cuSpatial replacing these uses?

@isVoid sure opened a PR in cuspatial: https://github.com/rapidsai/cuspatial/pull/1327

**Comment by davidwendt** [comment]
Based on https://github.com/rapidsai/cudf/pull/14786#pullrequestreview-1830914656 should this be considered a breaking change?

**Comment by mroeschke** [comment]
I think this is considered a private API since it's in the `cudf.core` Python namespace, but I'll label it as breaking anyways

**Review by isVoid — APPROVED** [review]

**Comment by isVoid** [comment]
> Based on [#14786 (review)](https://github.com/rapidsai/cudf/pull/14786#pullrequestreview-1830914656) should this be considered a breaking change?

Actually no, I don't think this should be a breaking change. cuSpatial shouldn't use these internal APIs in the first place. We discussed about removing all of these usage. Labeling this as a breaking change can make contributors who reads the changelog mistakenly believe they are public API.

**Comment by vyasr** [comment]
I agree with @isVoid, we shouldn't mark these as breaking. We should just remember while reviewing these sort of changes to cudf's column layer that they have the potential to break cuspatial in particular.

**Review by vyasr — APPROVED** [review]

**Comment by mroeschke** [comment]
@vyasr any other project you can think of that might be using this API? I removed this API from cuspatial in https://github.com/rapidsai/cuspatial/pull/1327

**Comment by vyasr** [comment]
Apologies, I missed this query earlier. No, I can't think of any other project using these APIs. Morpheus is the only other package that uses cudf internals, but they tend to use a different set of them (more focused on extracting pointers from columns and then reconstructing them, basically things around pybind/cython interop rather than creating cudf columns from more arbitrary data).

**Pull request merged**
