### PR TITLE
Use `cupy.ndarray` (without `core`)

### PR DESCRIPTION
**Pull request by jakirkham**
`core` is internal to `cupy` and renamed to reflect that in CuPy 9. However that shouldn't be needed to access `ndarray` as it is `import`ed at the top-level. So just use `cupy.ndarray`.

cc @kkraus14 @rjzamora

### CODE REVIEW

**Review by kkraus14 — APPROVED** [review]

**Comment by kkraus14** [comment]
@gpucibot merge

**Review by galipremsagar — COMMENTED** [review]
We'll need to change in these files too:

https://github.com/rapidsai/cudf/blob/branch-0.20/python/cudf/cudf/core/algorithms.py#L56

and all the 6 occurences of `cp.core.core.ndarray` in : https://github.com/rapidsai/cudf/blob/branch-0.20/python/cudf/cudf/tests/test_factorize.py

**Comment by jakirkham** [comment]
Good catch Prem! 😄 Should be fixed above. Can you please take another look? 🙂

**Review by galipremsagar — APPROVED** [review]

**Comment by galipremsagar** [comment]
@gpucibot merge

**Pull request merged**
