### PR TITLE
[REVIEW] Fixing python cudf.io.csv docstrings, bumping to 0.4.0 version in doc…

### LINKED ISSUE #275: missing pygdf.io.read_csv doc on supported datetime format
## Reporting a bug

- [x] I am using the latest version of PyGDF from conda or built from `master`.
- [ ] I have included the following environment details:
      Linux Distro, Linux Kernel, GPU Model
- [ ] I have included the following version information for:
      Arrow, CUDA, Numpy, Pandas, Python
- [ ] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

The test is only testing for DD/MM/YYYY.  What other datetime format is supported?  

I am trying on datetime like `2017-10-07 15:14:44` but it's parsed as `1969-12-31 23:59:59`.

### PR DESCRIPTION
**Pull request by randerzander**
- Update sphinx docs to use correct class names after refactor
- Fix cudf.io.csv read_csv_strings docstring to actually show up in docs
- Improve examples for read_csv and read_csv strings
fixes #275

### CODE REVIEW

**Comment by harrism** [comment]
@randerzander Can you fix conflicts and while you are at it create a 0.5.0 section at the top of CHANGELOG.md and add this PR there?

**Comment by randerzander** [comment]
@harrism any other feedback?

**Comment by harrism** [comment]
Looks good. I fixed the CHANGELOG.md conflict and will merge once CI passes again...

**Comment by harrism** [comment]
This should probably be reviewed by a Python person. LGTM.

**Comment by randerzander** [comment]
@kkraus14 @dantegd anything else needed here?

**Pull request merged**
