### PR TITLE
[REVIEW] Remove dask_cudf join implementation

### PR DESCRIPTION
**Pull request by rjzamora**
Removing the dask_cudf `DataFrame.join` implementation in favor of upstream Dask. 

Blockers:
- [x] Address CI numba error (`dask/dataframe/methods.py:109: in boundary_slice`)
- [x] Address segfault in `libcudf.issorted` with pooled memory allocator (Issue [#3221](https://github.com/rapidsai/cudf/issues/3221))

### CODE REVIEW

**Comment by mrocklin** [comment]
That's a lot of deleted lines :)

**Comment by rjzamora** [comment]
Once the join code is removed, the only remaining API using the code in `batcher_sortnet.py` is `sort_values` and `sort_values_binned`.  Are these methods being used in practice?

**Comment by rjzamora** [comment]
Note that these changes seem performant for the simple tests/benchmarks I have tried so far. E.g...

<details>
<summary>Click for benchmark</summary>
<br>

```python
import dask.dataframe as dd
import dask
import cudf

from dask_cuda import LocalCUDACluster
from dask.distributed import Client, wait
cluster = LocalCUDACluster()
client = Client(cluster)

ddf1 = dask.datasets.timeseries(
    start = "2000-01-01",
    end = "2000-01-04",
    freq = "1s",
    partition_freq="6H",
    seed = 42,
    id_lam = 200,
    dtypes={"id": int, "x": float},
)
gddf1 = ddf1.map_partitions(cudf.from_pandas).persist()

ddf2 = dask.datasets.timeseries(
    start = "2000-01-11",
    end = "2000-01-14",
    freq = "1S",
    partition_freq="12H",
    seed = 142,
    id_lam = 200,
    dtypes={"id": int, "x": float},
)
gddf2 = ddf2.map_partitions(cudf.from_pandas).persist()

# Join (performed in Jupyter notebook)
%timeit wait(gddf1.set_index("id").join(gddf2.set_index("id"), lsuffix="_l", rsuffix="_r").persist())
```

</details>

**This PR**: `1.27 s ± 138 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)`

**Branch 0.11**: `2.37 s ± 165 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)`

**Comment by mrocklin** [comment]
Nice.

**Comment by mrocklin** [comment]
poke @kkraus14 .  This seems like a nice change and mostly harmless to me.

**Comment by kkraus14** [comment]
Will merge once CI is green.

**Pull request merged**
