### PR TITLE
Clean up the starter code on README

### PR DESCRIPTION
**Pull request by harupy**
Clean up the starter code on README.

### CODE REVIEW

**Comment by GPUtester** [comment]
Can one of the admins verify this patch?

**Comment by harrism** [comment]
@harupy Needs an entry in CHANGELOG.md in order to pass tests.

**Comment by harrism** [comment]
ok to test

**Comment by harupy** [comment]
@harrism 
> Needs an entry in CHANGELOG.md in order to pass tests.
ok I'll add it.

**Comment by kkraus14** [comment]
Thanks for your contribution @harupy!

**Comment by harupy** [comment]
@kkraus14 Thanks for merging!

**Pull request merged**
