### PR TITLE
docs: change 'CSV' to 'csv' in python/custreamz/README.md to match kafka.py

### PR DESCRIPTION
**Pull request by a-hirota**
## Description
This PR corrects a typo in the `python/custreamz/README.md` file by changing the uppercase `'CSV'` to lowercase `'csv'`. This change aligns the documentation with the `message_format` options defined in `python/custreamz/custreamz/kafka.py`, ensuring consistency across the codebase.

## Checklist
- [x] I am familiar with the [Contributing Guidelines](https://github.com/rapidsai/cudf/blob/HEAD/CONTRIBUTING.md).
- [ ] New or existing tests cover these changes.
- [x] The documentation is up to date with these changes.

### CODE REVIEW

**Review by vyasr — APPROVED** [review]
This looks good to me, thank you!

**Review by Matt711 — APPROVED** [review]
Thanks!

**Pull request merged**
