### PR TITLE
[REVIEW] Align column data allocation size to 8 bytes

### LINKED ISSUE #3145: [FEA] 8B-align the size of column data device vectors
For small data types, this enables load optimizations, like 4x faster string comparison.
Unlike NvStrings, the new libcudf++ column allocations no longer align the character data buffer, causing a 3x perf drop for things like sorting string columns if resorting to the default string compare. It's possible to do the load optimizations without aligning the size at allocation time, but that may trigger bounds-checking tools like cuda-memcheck.

### PR DESCRIPTION
**Pull request by OlivierNV**
Enables data loading optimizations without tripping bounds checking tools (prerequisite for parquet/orc writers). Resolves #3145

### CODE REVIEW

**Comment by OlivierNV** [comment]
rerun tests

**Comment by jrhemstad** [comment]
I think we should push this down into `device_buffer` such that it will always allocate at least a multiple of 8 bytes. That way we don't have to remember to round up the allocation size all over in libcudf.

What do you think @harrism ?

**Comment by harrism** [comment]
@jrhemstad makes sense. Does Arrow have any requirements around size padding?

**Comment by OlivierNV** [comment]
> @jrhemstad makes sense. Does Arrow have any requirements around size padding?

Arrow does appear to require 8-byte alignment and padding (with 64-byte recommended)
From https://arrow.apache.org/docs/memory_layout.html
"Alignment and Padding
As noted above, all buffers must be aligned in memory at 8-byte boundaries and padded to a length that is a multiple of 8 bytes."

**Comment by jrhemstad** [comment]
Superseded by https://github.com/rapidsai/rmm/pull/165

**Pull request closed without merging**
