### PR TITLE
update cudfjni to 22.08.0-SNAPSHOT

### PR DESCRIPTION
**Pull request by pxLi**
Signed-off-by: Peixin Li <pxli@nyu.edu>

update build version of cudfjni to 22.08.0-SNAPSHOT

### CODE REVIEW

**Comment by pxLi** [comment]
will rerun tests when the CI is ready for branch-22.08

**Review by jlowe — COMMENTED** [review]
The version in java/src/main/native/CMakeLists.txt should be updated as well.

**Comment by pxLi** [comment]
> The version in java/src/main/native/CMakeLists.txt should be updated as well.

I saw https://github.com/rapidsai/cudf/commit/de3eb738d24576f0b1bff4f9e0fdcfa4f06b8fe6 already includes java/src/main/native/CMakeLists.txt 22.08 update

**Review by jlowe — APPROVED** [review]

**Comment by pxLi** [comment]
rerun tests

**Comment by pxLi** [comment]
@gpucibot merge

**Pull request merged**
