### PR TITLE
Enable pydocstyle rules involving quotes

### PR DESCRIPTION
**Pull request by vyasr**
This PR enables D30* errors for pydocstyle. It also sets up the `ignore-decorators` configuration so that future PRs involving D10* errors will treat docutils decorators appropriately. Contributes to #10711.

### CODE REVIEW

**Review by bdice — APPROVED** [review]
Great work. For a next step after this PR, I'd like to reduce the exclusions before adding more rules. We should try to enforce our style rules uniformly for `dask_cudf`, `cudf_kafka`, `custreamz`, and `python/cudf/cudf/tests`.

**Comment by vyasr** [comment]
@bdice I am very much on board with trying to synchronize across all of the different cudf packages and reduce the number of configuration files. I don't think that there is a particular order in which we need to do these things, I suspect that we can progress to this goal incrementally in any order without running into many problems. The only issue that I'd foresee is that if multiple people work on this we'll need coordination to avoid conflicts.

**Comment by vyasr** [comment]
@gpucibot merge

**Comment by vyasr** [comment]
@bdice I opened #10758 to discuss this further.

**Pull request merged**
