### PR TITLE
[REVIEW] Leverage dask.dataframe shuffle API in dask_cudf

### LINKED ISSUE #5307: [FEA] Support new DataFrame.shuffle API in dask_cudf
**Is your feature request related to a problem? Please describe.**
Now that [dask#6066](https://github.com/dask/dask/pull/6066) has been merged, the functionality in `sorting.rearrange_by_hash` can now (hopefully) be replaced with `DataFrame.shuffle`.

Currently, dask_cudf is "publicly" exposing the same functionality as `DataFrame.shuffle` in the form of a `columns` argument to `DataFrame.repartition`.  As summarized in [dask#6133](https://github.com/dask/dask/issues/6133), `repartition` is **not** the ideal API for this behavior, and so a dedicated `shuffle` API has been added upstream.  I propose that we align `dask_cudf` with this new `dask.dataframe` API.

**Describe the solution you'd like**
I propose that we:
- Add support for `DataFrame.shuffle` (wrap the upstream `shuffle` method with `shuffle="tasks"`)
- Redirect any `rearrange_by_hash`-based code to use this new API (cleaning out `rearrange_by_hash`)
- Add a deprecation warning for the `columns` argument to `repartition`

Note that significant effort has gone into the optimization of `rearrange_by_hash`, so we will need to do sufficient benchmarking and testing to avoid performance regressions.

**Describe alternatives you've considered**
The alternative is to do nothing.  This would result in diverging API's for hash-based partitioning and would require us to use/maintain redundant shuffling code.

### PR DESCRIPTION
**Pull request by rjzamora**
Closes #5307

This PR removes the `rearrange_by_hash` code in `dask_cudf.sorting`, and redirects all dependent code to use the (new) upstream-dask `shuffle` API (introduced in [dask#6066](https://github.com/dask/dask/pull/6066)).  Note that the algorithm used by upstream dask should be the same, but we will still need to check carefully for performance regressions before merging this in.

**TODO**:
- [x] Add support for DataFrame.shuffle (wrap the upstream shuffle method with shuffle="tasks")
- [x] Redirect any rearrange_by_hash-based code to use this new API (cleaning out rearrange_by_hash)
- [x] Add a deprecation warning for the columns argument to repartition
- [x] Benchmark changes to check for performance regressions (address regressions if they exist)

### CODE REVIEW

**Comment by quasiben** [comment]
This is really cool to see experiments moving from cudf to dask and then replacing with upstreamed work.

**Comment by rjzamora** [comment]
I did some light benchmarking of tpcxbb queries 2, 3, 4 and 30 (sf1000 data) on 15 V100 GPUs on a DGX-2 machine (time in seconds):

```
# q02
PR:    23.14, 17.94
0.15:    21.87, 18.00

# q03
PR:    28.46, 27.62
0.15:    30.79, 28.79

# q04
PR:    19.60, 15.22
0.15:   17.06, 15.40

# q30
PR:    20.87, 20.27
0.15:    24.04, 20.37
```

Note that I did not collect enough data to detect statistical differences in the performance, but there doesn't seem to be an obvious regression (or "broken" code) at the sf1000 scale.

@beckernick @VibhuJawa - Any other tests you recommend? Is anyone else already set up to test this branch on the 10k scale?

**Comment by rjzamora** [comment]
@beckernick @VibhuJawa @ayushdg - No problem if you have been distracted by other things, but just wanted to check if there was any update on 10k testing here?

**Comment by VibhuJawa** [comment]
> @beckernick @VibhuJawa @ayushdg - No problem if you have been distracted by other things, but just wanted to check if there was any update on 10k testing here?

Can confirm that we don't see a regression with this PR  on 10k. 
(Using pr cudf/pull/5318). 

There may even be  a slight improvement with PR but it can be noise too . 

**PR**
```python
dask: 2.19.0+8.g7aaef9fa 
distributed: 2.19.0+10.gdb5e88cd
```


```python
2 | ucx | TRUE | FALSE | dask | parquet | 91.09715319
2 | ucx | TRUE | FALSE | dask | parquet | 86.13638091
2 | ucx | TRUE | FALSE | dask | parquet | 86.86514831
2 | ucx | TRUE | FALSE | dask | parquet | 87.95563507
2 | ucx | TRUE | FALSE | dask | parquet | 86.74555063

3 | ucx | TRUE | FALSE | dask | parquet | 193.7365444
3 | ucx | TRUE | FALSE | dask | parquet | 158.8870072
3 | ucx | TRUE | FALSE | dask | parquet | 175.0744009
3 | ucx | TRUE | FALSE | dask | parquet | 152.9931328
3 | ucx | TRUE | FALSE | dask | parquet | 170.0338874

4 | ucx | TRUE | FALSE | dask | parquet | 86.53266621
4 | ucx | TRUE | FALSE | dask | parquet | 82.68642497
4 | ucx | TRUE | FALSE | dask | parquet | 84.88976192
4 | ucx | TRUE | FALSE | dask | parquet | 84.95811272
4 | ucx | TRUE | FALSE | dask | parquet | 89.15348434

8 | ucx | TRUE | FALSE | dask | parquet | 167.1421793
8 | ucx | TRUE | FALSE | dask | parquet | 168.2803082
8 | ucx | TRUE | FALSE | dask | parquet | 168.2982454
8 | ucx | TRUE | FALSE | dask | parquet | 170.1504653
8 | ucx | TRUE | FALSE | dask | parquet | 164.4873414

30 | ucx | TRUE | FALSE | dask | parquet | 84.40247369
30 | ucx | TRUE | FALSE | dask | parquet | 80.84242225
30 | ucx | TRUE | FALSE | dask | parquet | 82.50999212
30 | ucx | TRUE | FALSE | dask | parquet | 79.74432111
30 | ucx | TRUE | FALSE | dask | parquet | 80.42760372
```

**Master** 
```python
dask:2.19.0+7.gad5006fc 
distributed: 2.19.0+7.g955b5683
```


```python
2 | ucx | TRUE | FALSE | dask | parquet | 89.28844237
2 | ucx | TRUE | FALSE | dask | parquet | 88.54520917
2 | ucx | TRUE | FALSE | dask | parquet | 89.30665851
2 | ucx | TRUE | FALSE | dask | parquet | 88.73954988
2 | ucx | TRUE | FALSE | dask | parquet | 88.38623881



3 | ucx | TRUE | FALSE | dask | parquet | 166.7168272
3 | ucx | TRUE | FALSE | dask | parquet | 173.722337
3 | ucx | TRUE | FALSE | dask | parquet | 152.8289795
3 | ucx | TRUE | FALSE | dask | parquet | 148.8808599
3 | ucx | TRUE | FALSE | dask | parquet | 147.6185112


4 | ucx | TRUE | FALSE | dask | parquet | 84.12735152
4 | ucx | TRUE | FALSE | dask | parquet | 87.46360564
4 | ucx | TRUE | FALSE | dask | parquet | 85.2715435
4 | ucx | TRUE | FALSE | dask | parquet | 87.84634161
4 | ucx | TRUE | FALSE | dask | parquet | 86.95689702

8 | ucx | TRUE | FALSE | dask | parquet | 175.3781891
8 | ucx | TRUE | FALSE | dask | parquet | 174.778513
8 | ucx | TRUE | FALSE | dask | parquet | 170.3399734
8 | ucx | TRUE | FALSE | dask | parquet | 172.612191
8 | ucx | TRUE | FALSE | dask | parquet | 173.2185934


30 | ucx | TRUE | FALSE | dask | parquet | 86.3293376
30 | ucx | TRUE | FALSE | dask | parquet | 83.14115071
30 | ucx | TRUE | FALSE | dask | parquet | 86.3293376
30 | ucx | TRUE | FALSE | dask | parquet | 82.71371984


```

**Comment by rjzamora** [comment]
Thanks @VibhuJawa !!

**Comment by jakirkham** [comment]
Should this still be marked as a draft?

**Comment by rjzamora** [comment]
> Should this still be marked as a draft?

Nope - Thanks! (sorry, could have sworn I changed it)

**Comment by rjzamora** [comment]
Woohoo - Thanks for the help here everyone!

**Pull request merged**
