### PR TITLE
Increase `pip` verbosity in cuDF Conda build

### PR DESCRIPTION
**Pull request by jakirkham**
## Description

When building cuDF Conda packages, configure `pip` with a verbosity of `2` to provide a bit more information about how the build is performing.

## Checklist
- [ ] I am familiar with the [Contributing Guidelines](https://github.com/rapidsai/cudf/blob/HEAD/CONTRIBUTING.md).
- [ ] New or existing tests cover these changes.
- [ ] The documentation is up to date with these changes.

### CODE REVIEW

**Comment by bdice** [comment]
@jakirkham Is this ready / does it show the logs you want? Do you want to request an ops review?

**Comment by jakirkham** [comment]
Thanks for the reminder Bradley! 🙏

Yeah this is working as expected

We may want to do this in more places or add a `pip.conf` to generalize this (like our build images). For example

```ini
# filename: /etc/xdg/pip/pip.conf
[global]
quiet = 0
verbose = 2
```

https://pip.pypa.io/en/stable/topics/configuration/#repeatable-options

cc @vyasr (if you have thoughts here as well)

**Comment by bdice** [comment]
@jakirkham I would suggest changing this in the CI images or some other central location, if that works. What specific info are you needing from the verbose output?

**Comment by jakirkham** [comment]
Yeah agree

With the current verbosity (`0`), there is no insight into package builds. Instead `pip` simply installs the package (or doesn't). For example from `branch-24.04`'s [recent CI run]( https://github.com/rapidsai/cudf/actions/runs/8300761067/job/22720093519#step:7:675 ):

```
Processing $SRC_DIR/python/cudf
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Building wheels for collected packages: cudf
  Building wheel for cudf (pyproject.toml): started
  Building wheel for cudf (pyproject.toml): finished with status 'done'
  Created wheel for cudf: filename=cudf-24.4.0a568-cp311-cp311-manylinux_2_35_x86_64.whl size=12530265 sha256=b61a00254deb1fbb7a4b5cf09e6deb07e760f4ce953b4f9144d70cc8a8776a79
  Stored in directory: /tmp/pip-ephem-wheel-cache-c26kl73v/wheels/5e/24/82/5c2b292e0ac6da16a78548a8d31778b075082108073e38f109
Successfully built cudf
Installing collected packages: cudf
Successfully installed cudf-24.4.0a568
```

Compare this to what is present here with verbosity `2` (or `-vv` to `pip install`) where we get some insight into `scikit-build-core` and CMake. Here is a snippet from [this CI build]( https://github.com/rapidsai/cudf/actions/runs/8093857434/job/22118240502?pr=15168#step:7:629 ):

```
...
*** scikit-build-core 0.8.1 using CMake 3.28.3 (wheel)
  *** Configuring CMake...
  2024-02-29 10:02:07,719 - scikit_build_core - WARNING - Unsupported CMAKE_ARGS ignored: -DCMAKE_BUILD_TYPE=Release
  2024-02-29 10:02:07,719 - scikit_build_core - WARNING - Unsupported CMAKE_ARGS ignored: -DCMAKE_INSTALL_PREFIX=/opt/conda/conda-bld/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho
  2024-02-29 10:02:07,721 - scikit_build_core - WARNING - libdir/ldlibrary: /opt/conda/conda-bld/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/libpython3.11.a is not a real file!
  2024-02-29 10:02:07,721 - scikit_build_core - WARNING - Can't find a Python library, got libdir=/opt/conda/conda-bld/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib, ldlibrary=libpython3.11.a, multiarch=x86_64-linux-gnu, masd=None
  2024-02-29 10:02:07,770 - scikit_build_core - WARNING - Unsupported CMAKE_ARGS ignored: -DCMAKE_BUILD_TYPE=Release
  2024-02-29 10:02:07,770 - scikit_build_core - WARNING - Unsupported CMAKE_ARGS ignored: -DCMAKE_INSTALL_PREFIX=/opt/conda/conda-bld/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho
  loading initial cache file build/cp311-cp311-manylinux_2_35_x86_64/CMakeInit.txt
  -- The CXX compiler identification is GNU 11.4.0
  -- The CUDA compiler identification is NVIDIA 11.8.89
...
```

This way we are able to explore any configuration issues (like a dependency not being detected, a configuration error, etc.)

**Comment by vyasr** [comment]
I would check in with @ajschmidt8. I believe that we've run into performance issues with CI rendering etc in the past when the logs are too verbose (I'm especially thinking of test jobs, but I think build jobs too). We intentionally reduced verbosity for that reason IIRC.

If that's not an issue then I'm not opposed to setting this configuration up more broadly.

**Comment by jakirkham** [comment]
We already do the same with devcontainers and wheel builds

Can't see why this would only be a performance issue in some builds and not others

**Comment by vyasr** [comment]
devcontainer builds often slow down and occasionally crash my browser if I try to open the dropdowns. I can only ever reliably view those outputs by opening the raw logs. Wheel builds have a lot less output to begin with than conda builds, so it's just less total output than the conda build will have if we include pip verbosity and conda build verbosity in the same run. Also FWIW we've discussed reducing the verbosity of wheel builds for similar reasons.

**Comment by bdice** [comment]
I can second most of what @vyasr said above. I would prefer that we enable verbose logging levels only when diagnosing problems rather than by default. I don’t think I have never needed the verbose pip output in RAPIDS builds.

**Comment by jakirkham** [comment]
Would argue the verbosity level picked here is useful and not extra. It tells us how CMake has configured the build, which is critical for figuring out build issues (like configuration issues or not using packages we installed). Issues we have spent a lot of time debugging in the past. Adequate log output would be very helpful when debugging these. Otherwise we are in the dark

If we are having issues rendering logs in some browsers (am not familiar with this problem), would suggest we address that separately. Don't think the answer to that is to cutout useful information

**Comment by bdice** [comment]
The volume of log outputs causing UI issues is not really separable from the conversation of increasing log outputs…

But as discussed above, cudf is not the right repo to fix this. Please find a way to do this for all of RAPIDS in our shared CI images.

**Comment by vyasr** [comment]
Correct me if I'm wrong, but pip _will_ produce the output if a build actually fails, right? conda builds don't block that in some way? So if something actually goes wrong you will see the full output. What we're talking about here is showing the full output even for successful builds.

**Comment by ajschmidt8** [comment]
I wonder if log groups help with the UI issues from long logs at all.

- https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#grouping-log-lines

Might be worth doing some experimenting with.

**Comment by vyasr** [comment]
Superseded by https://github.com/rapidsai/ci-imgs/pull/140

**Pull request closed without merging**
