### PR TITLE
Update required spdlog and fmt version for our conda envs

### PR DESCRIPTION
**Pull request by robertmaynard**
## Description
This ensures that we don't have older versions of these packages installed causing rapids-cmake to download the newer versions.

## Checklist
- [x] I am familiar with the [Contributing Guidelines](https://github.com/rapidsai/cudf/blob/HEAD/CONTRIBUTING.md).
- [x] New or existing tests cover these changes.
- [x] The documentation is up to date with these changes.

### CODE REVIEW

**Comment by vyasr** [comment]
@robertmaynard you'll want to run `rapids-dependency-file-generator` to update all the necessary files (e.g. conda env files). It can be pip installed and then run from the command line in the root of the repo.

**Comment by robertmaynard** [comment]
> @robertmaynard you'll want to run `rapids-dependency-file-generator` to update all the necessary files (e.g. conda env files). It can be pip installed and then run from the command line in the root of the repo.

Thanks, updated with the output. I couldn't remember if we did that through some sort of merge time magic.

**Comment by vyasr** [comment]
Not quite yet, but we're slowly moving in that direction. Should have pre-commit hooks in place for it very soon at least. pre-commit autofixes in CI are still a ways away though, and I don't recall from our debates about it whether people were generally in favor of that or not (due to the possible divergence between local and remote changes from a remote run of the hook). Probably a debate we'll have again once we're closer to being able to enable such a feature.

**Review by vyasr — APPROVED** [review]

**Review by ajschmidt8 — APPROVED** [review]

**Comment by vyasr** [comment]
@robertmaynard out of curiosity, if cudf pulls the latest rmm won't we just inherit these requirements from rmm? Also, this will affect #12637 CC @vuule

**Comment by ajschmidt8** [comment]
Do these packages need to be added to the conda recipes at all?

Right now that `build` dependencies list in `dependencies.yaml` is really only used for downstream projects like `rapids-compose` and `rapids-compose v2`

**Comment by robertmaynard** [comment]
I added these to the dependencies.yaml as I was running into conda envs that had spdlog 7 in them.

Looking at the conda envs more closely it looks like that this is due to them bringing librmm 23.02 for some reason instead of librmm 23.04. 

I think we can close this PR as it isn't needed

**Comment by vyasr** [comment]
OK good so cudf should indeed be pulling the requirement from rmm as I would have expected. I will close this for now, we can reopen if the issue reappears.

**Pull request closed without merging**
