### PR TITLE
[REVIEW] fix uint32_t undefined errors

### PR DESCRIPTION
**Pull request by rongou**
Newer gcc compilers seem to be unhappy about not including `cstdint`:
```console
/home/rou/src/cudf/cpp/src/io/orc/orc_common.h(24): error: identifier "uint32_t" is undefined
```

### CODE REVIEW

**Comment by GPUtester** [comment]
Please update the changelog in order to start CI tests.

View the gpuCI docs [here](https://docs.rapids.ai/gpuci#open-pr-or-update-pr).

**Comment by harrism** [comment]
Please use labels.

**Review by harrism — APPROVED** [review]
Thanks!

**Comment by rongou** [comment]
> Please use labels.

Hmm, I don't think I can add labels. Need to be added to the project?

**Comment by harrism** [comment]
> > Please use labels.
> 
> Hmm, I don't think I can add labels. Need to be added to the project?

Done.

**Review by davidwendt — APPROVED** [review]

**Pull request merged**
