### PR TITLE
[REVIEW] Remove PatchedNumbaDeviceArray with CuPy 6.6.0+

### PR DESCRIPTION
**Pull request by brandon-b-miller**
Closes https://github.com/rapidsai/cudf/issues/3248

Should not be merged before https://github.com/rapidsai/cudf/pull/3619.

### CODE REVIEW

**Comment by brandon-b-miller** [comment]
This is actually ready for review, CI failures should be fixed by 3619.

**Comment by jakirkham** [comment]
@brandon-b-miller, can you please merge with `master`?

**Comment by brandon-b-miller** [comment]
tests seem to be failing here, looking into it.

**Comment by brandon-b-miller** [comment]
Should pass CI now.

**Comment by jakirkham** [comment]
Thanks! 😄

**Pull request merged**
