### PR TITLE
[REVIEW] Update cython version to 0.29.x

### PR DESCRIPTION
**Pull request by dantegd**
Update cython to version `0.29.x`, to solve this integration issue between cuDF and cuML: 

https://github.com/rapidsai/cuml/issues/58

### CODE REVIEW

**Comment by kkraus14** [comment]
Note this should also be updated in #567.

**Comment by harrism** [comment]
rerun tests

**Comment by harrism** [comment]
Builds are failing.

**Comment by dantegd** [comment]
@harrism it is failing because there is no prebuild cython 0.29 conda package in conda forge for python 3.5 :(

**Comment by kkraus14** [comment]
I'm exploring submitting a PR to the conda-forge Cython feedstock to enable Python 3.5 builds.

**Comment by mike-wendt** [comment]
@kkraus14 can we use this PR to do the testing for 3.7? As it will solve two issues at once?

**Comment by kkraus14** [comment]
@mike-wendt we can use this one as well, but id like to separate the code changes and Cython dependency bump into separate PRs if possible.

**Comment by mike-wendt** [comment]
That's fine @kkraus14 I guess this was more of a way to see if there are issues from both cython and 3.7 updates

**Comment by mike-wendt** [comment]
Want to hold onto this so we can also test py37 on this see #668

**Comment by kkraus14** [comment]
This will depend on Python 3.6+ support which is being figured out by #668.

**Comment by kkraus14** [comment]
@dantegd handling in #668 so closing this.

**Pull request closed without merging**
