### PR TITLE
Update CHANGELOG.md

### PR DESCRIPTION
**Pull request by goodengineer**

### CODE REVIEW

**Comment by GPUtester** [comment]
Can one of the admins verify this patch?

**Comment by GPUtester** [comment]
Can one of the admins verify this patch?

**Comment by kkraus14** [comment]
@goodengineer you need to update the CHANGELOG in the existing pull requests as opposed to opening a new pull request to update it.

Can you push these changes into your existing PRs?

**Comment by harrism** [comment]
Changes from #6063 and #6064 have been incorporated into #5861 by @code_report, so these can all be closed.

**Pull request closed without merging**
