### PR TITLE
Allow CuPy 9 to be used with cuDF

### PR DESCRIPTION
**Pull request by jakirkham**

### CODE REVIEW

**Review by ajschmidt8 — APPROVED** [review]

**Comment by kkraus14** [comment]
They aren't currently versioned, but the requirements txt files should be updated to capture this versioning: https://github.com/rapidsai/cudf/blob/branch-0.20/python/cudf/requirements/cuda-11.0/dev_requirements.txt#L6

The versioning in the `setup.py` should be handled as well: https://github.com/rapidsai/cudf/blob/branch-0.20/python/cudf/setup.py#L88-L90

**Comment by jakirkham** [comment]
Would it make sense to include that in a separate issue/PR given versioning is not handled in those parts of the code yet?

**Comment by jakirkham** [comment]
Any thoughts on the question above @kkraus14?

Personally am unclear on what is needed for `setup.py` in particular. So thinking that would be better saved for someone else who knows what they want to see done

**Comment by kkraus14** [comment]
We can punt on those for now, that's fine.

**Comment by kkraus14** [comment]
@gpucibot merge

**Comment by jakirkham** [comment]
Thanks Keith! 😄

Went ahead and filed issue ( https://github.com/rapidsai/cudf/issues/8104 ) about adding the version requirements to `requirements.txt` and `setup.py` files. Feel free to add anything I missed over there 🙂

**Pull request merged**
