### PR TITLE
Fix some libcudf detail calls not passing the stream variable

### PR DESCRIPTION
**Pull request by davidwendt**
## Description
Fixes some calls that were not passing the stream variable to detail functions.
Found these while looking into improvements for #11577 

## Checklist
- [x] I am familiar with the [Contributing Guidelines](https://github.com/rapidsai/cudf/blob/HEAD/CONTRIBUTING.md).
- [x] New or existing tests cover these changes.
- [x] The documentation is up to date with these changes.

### CODE REVIEW

**Review by ttnghia — APPROVED** [review]

**Comment by PointKernel** [comment]
Should we remove the default value for all input stream parameters in `include`? e.g. 
https://github.com/rapidsai/cudf/blob/f4f34287dadd9ee9a946b253aa045ba3256028b6/cpp/include/cudf/column/column_device_view.cuh#L823-L824

In this way, all issues of the same kind can be unveiled.

According to the developer guide:
> The internal detail API has the same parameters as the public API, plus a rmm::cuda_stream_view parameter at the end with no default value.

while `grep -rn "= cudf::default_stream_value" | wc -l` shows there are 295 default stream being set in the `cudf/cpp/include` folder

**Comment by ttnghia** [comment]
> Should we remove the default value for all input stream parameters in `include`? e.g.

I always recommend removing the default stream value for `detail` APIs whenever I see a new one or a modified one.

**Comment by davidwendt** [comment]
> > Should we remove the default value for all input stream parameters in `include`? e.g.
> 
> I always recommend removing the default stream value for `detail` APIs whenever I see a new one or a modified one.

Technically the parameter is only used with a compound column type.
Regardless, I also agree with removing it here.

**Review by PointKernel — APPROVED** [review]
LGTM

I will make a PR to remove all default streams.

**Review by harrism — APPROVED** [review]

**Comment by davidwendt** [comment]
@gpucibot merge

**Pull request merged**
