### PR TITLE
[REVIEW] split iterator and gather tests to speedup build tests

### LINKED ISSUE #5464: [FEA] Split COPYING_TEST into multiple different tests.
COPYING_TEST is getting pretty large.  It contains tests for:

- concatenate
- gather
- split
- slice
- copy_range
- scatter
... and more

It takes a pretty long time to compile.  We should consider breaking this up into a set of separate tests.

### PR DESCRIPTION
**Pull request by karthikeyann**
Fixes #5464 
gather_test.cu (88s)
iterator_test.cu compilation time is 339s (5.65 minutes) ! This will be higher after Duration Types are added to FixedWidthTypes. 

- [x] splits iterator tests (339s to 83s+136s+142s)
- [x] splits gather_tests  (88s to 17s + 26s + 30s)

### CODE REVIEW

**Comment by GPUtester** [comment]
Please update the changelog in order to start CI tests.

View the gpuCI docs [here](https://docs.rapids.ai/gpuci#open-pr-or-update-pr).

**Comment by harrism** [comment]
Have you done a ninja profile to show the benefit of this? (Total time is not reduced, but parallelism is increased, right?)

**Comment by karthikeyann** [comment]
> Have you done a ninja profile to show the benefit of this? (Total time is not reduced, but parallelism is increased, right?)

I did. I have attached the tracing json files of old and new builds [fresh_build.ninja_trace_old_new.zip](https://github.com/rapidsai/cudf/files/4824631/fresh_build.ninja_trace_old_new.zip) (view json using [chrome://tracing/](chrome://tracing/) )

Yes. But parallel builds gives benefit.

image

**Comment by karthikeyann** [comment]
splitting `gather_tests.cu` takes lesser compile time cumulatively. (old 88s, new 74s).

**Comment by harrism** [comment]
Nice job. I actually started splitting up the iterator tests for the same reason a while back but got distracted.   I think reductions will soon be a problem. :)

**Comment by karthikeyann** [comment]
After adding duration types, the compile time is too high. So I looked into it.
For reductions, I will try device side dispatch.

--
Karthikeyan Natarajan

________________________________

**Pull request merged**
