### PR TITLE
[REVIEW] Refactor `CompactProtocolReader::InitSchema`

### PR DESCRIPTION
**Pull request by codereport**
We need to start "modernizing" `cuIO`. This PR is just a small step - refactors a confusing `for` loop into a "rotated" `std::find_if`. Also uses C++ range-based `for` loops.

### CODE REVIEW

**Comment by GPUtester** [comment]
Please update the changelog in order to start CI tests.

View the gpuCI docs [here](https://docs.rapids.ai/gpuci#open-pr-or-update-pr).

**Comment by codereport** [comment]
> While you're at it, could you also add a comment block explaining what's this doing.

At this point, I can't add a meaningful comment that says anything the code doesn't.

**Comment by vuule** [comment]
> > While you're at it, could you also add a comment block explaining what's this doing.
> 
> At this point, I can't add a meaningful comment that says anything the code doesn't.

Perhaps so, but it's still not very easy to read and understand this code. Maybe improved names can help here instead of comments (`g`, `cur`, `it`... are not very descriptive IMO).

**Comment by codereport** [comment]
> > > While you're at it, could you also add a comment block explaining what's this doing.
> > 
> > 
> > At this point, I can't add a meaningful comment that says anything the code doesn't.
> 
> Perhaps so, but it's still not very easy to read and understand this code. Maybe improved names can help here instead of comments (`g`, `cur`, `it`... are not very descriptive IMO).

I will do my best to add a block comment.

**Pull request merged**
