### PR TITLE
Rename ARROW_STATIC_LIB because it conflicts with one in FindArrow.cmake

### PR DESCRIPTION
**Pull request by trxcllnt**
Rename `ARROW_STATIC_LIB` because it conflicts with CMake variable in Arrow's `FindArrow.cmake`.

Here's the new way to statically link Arrow with libcudf:
```
cmake -D CUDF_USE_ARROW_STATIC=ON ..
```

### CODE REVIEW

**Review by kkraus14 — APPROVED** [review]
LGTM, thanks @trxcllnt

**Comment by trxcllnt** [comment]
The test failures seem unrelated to this change.

**Comment by kkraus14** [comment]
rerun tests

**Comment by kkraus14** [comment]
@gpucibot merge

**Pull request merged**
