### PR TITLE
[REVIEW] Use RMM for Numba

### PR DESCRIPTION
**Pull request by gmarkall**
This PR goes along with https://github.com/rapidsai/rmm/pull/317.

When cuDF is imported, it now configures Numba to make all allocations from the RMM memory pool via `RMMNumbaManager` (similar to how the CuPy allocator is set to be RMM).

References to RMM functions that re-implemented Numba functions are removed and replaced with calls to the Numba version - since Numba is now using RMM, the allocations will still come from the RMM pool.

The Numba requirement is bumped to 0.49, as it is the first released version with the EMM plugin interface - earlier PRs #4950 and #5033 made appropriate fixes for the Python testsuite to succeed with Numba 0.49.

This PR is marked as WIP just until I've updated the corresponding RMM PR - will change to REVIEW once everything is aligned.

### CODE REVIEW

**Comment by GPUtester** [comment]
Please update the changelog in order to start CI tests.

View the gpuCI docs [here](https://docs.rapids.ai/gpuci#open-pr-or-update-pr).

**Comment by gmarkall** [comment]
As described in https://github.com/rapidsai/rmm/pull/317#issuecomment-620790447, I'm having a couple of things to get over with the RMM PR - my local testing of this branch makes no change to the test results (compared to `branch-0.14`), so I hope this will be ready to review as soon as the RMM PR hurdles are overcome.

**Comment by gmarkall** [comment]
I believe this is now ready for review.

**Comment by kkraus14** [comment]
Thanks for putting this in @gmarkall!

**Pull request merged**
