### PR TITLE
Support Dask + Distributed 2021.05.1

### PR DESCRIPTION
**Pull request by jakirkham**
Allow installing Dask + Distributed 2021.05.1 to be installed.

~~This isn't released yet, but this tees things up so we are ready to go once it comes out.~~

Associated integration PR ( https://github.com/rapidsai/integration/pull/284 )

### CODE REVIEW

**Review by galipremsagar — APPROVED** [review]

**Comment by jakirkham** [comment]
This is still waiting for packages. Just taking off the draft status 🙂

**Review by quasiben — APPROVED** [review]

**Comment by jakirkham** [comment]
rerun tests

**Comment by jakirkham** [comment]
@gpucibot merge

**Review by cwharris — APPROVED** [review]

**Comment by cwharris** [comment]
should we use ci/gpu/build.sh to force update dask+distributed and run tests so we know it'll work with latest, rather than waiting on integration to merge and publish?

**Comment by jakirkham** [comment]
Thanks Christopher!

We do run with `main` branches of both on CI already

Also ran with new Conda packages upthread

**Review by Ethyling — APPROVED** [review]

**Pull request merged**
