### PR TITLE
[REVIEW] Improve performance for creating columns from memoryview objects; Fixes #348

### LINKED ISSUE #348: Python Arrays are very slow to convert to cuDF Series
```python
import array as arr
import numpy as np

np_test = np.random.randint(0, 100, int(1e7))
arr_test = arr.array('q', memoryview(np_test))

cudf.Series(np_test)

cudf.Series(arr_test)
```

We should implement handling memoryview compatible objects more cleanly in the columnops.as_column code.

### PR DESCRIPTION
**Pull request by kkraus14**

### CODE REVIEW

**Comment by randerzander** [comment]
@kkraus14 

For your branch and master, I did some basic testing for 1m element numpy arrays as memoryviews:
```
import cudf
import time
import numpy as np
import array as arr

nelem = 1000000
perf = {}

types = ['int8', 'int16', 'int32', 'int64', 'float32', 'float64']

for type in types:
    np_arr = np.random.randint(0, 10, nelem).astype(type)
    data = memoryview(np_arr)
    data = arr.array(data.format, data)

    t1 = time.time()
    gs = cudf.Series(data)
    t2 = time.time()
    print(type + ' ' + str(t2-t1))
```

Then compared percent of decrease 
```
type	fea-ext-memoryview-handling		master	Percent Decrease
int8	0.6589558125	int8	0.7661750317	13.99408944
int16	0.001443624496	int16	0.08777427673	98.3552989
int32	0.04063463211	int32	0.06321716309	35.72215182
int64	0.00252532959	int64	0.06478381157	96.10191261
float32	0.3577108383	float32	0.03993105888	-795.8210684
float64	0.1249196529	float64	0.04084920883	-205.8067867
```

In summary, big improvements for everything except float32 and float64 types which are much worse

**Comment by kkraus14** [comment]
I think what's happening is that in master PyArrow is creating a PyArrow array from Python array and isn't calculating nulls whereas in my branch we go memoryview --> Numpy array (should be close to zero-op) but then we calculate the null bitmask which is the overhead you're seeing. Can you try to insert some nulls into the float arrays and see if the master results are correct / the same as this branch?

**Comment by randerzander** [comment]
@kkraus14 given that the source of this change is a desire for Python arrays to load to cuDF.Series faster, and NaN-checking for floats will actually make them load slower..

I could see use cases where you know/can guarantee ahead of time that you don't have any NaNs (or don't care if they're represented as null).

I propose we add a cuDF config (can't really be an arg, since df['a'] = [0.0, 1.1, 2.2,..] takes no args) called NaN_as_null:
If False (default), behave as master does today.. just write the NaNs
If True - perform the null mask calculation, replacing NaNs with null

I don't have a strong opinion on the default behavior.. do others?

**Comment by kkraus14** [comment]
I'm 100% against a cuDF config, this is something that should be a parameter to the cudf.Series.__init__ function and then a user can control the before with df['a'] = cudf.Series([0.0, 1.1, 2.2, nan], nan_as_null=True). By default we can have it check to see if the input is a Pandas Series we set the flag to True. Unsure of what the default behavior should be for a numpy array (is np.nan usually considered null?).

**Comment by randerzander** [comment]
@dantegd @robocopnixon do you have opinions on this approach?

@kkraus14 I still have the question about whether we need to perform the NaN->null swap on the host-side and get the slowdown, or whether the conversion could be handled with cudf `replace` when the PR merges?

**Comment by robocopnixon** [comment]
Numpy NaNs aren't equal to each other (NaN has nothing to which it is equal). The motivation behind this is that it guards against mistakes like comparing log(-1) to 1/0 and saying they're the same thing. None type in base python is equal to None. I am not sure if the null mask in cuDF behaves in the numpy way or the base python way. 

Pandas can be a pain because if it sees 'None' in a column, it will treat the dtype of the column as an object and the user will need to sort out what the data means. 

In the vast majority of user cases, they care if the data is missing in whatever the DataFrame was created from, not if it is a representation of an undefined mathematical operation. That said, I think most users expect numpy NaNs to fill missing values when working with pandas. 

I'm fine with the API Keith proposes, but I also want to point out there's a pandas option for treating -inf and inf as NA, which is somewhat different than numpy: `pandas.options.mode.use_inf_as_na = True`

**Comment by kkraus14** [comment]
> @kkraus14 I still have the question about whether we need to perform the NaN->null swap on the host-side and get the slowdown, or whether the conversion could be handled with cudf `replace` when the PR merges?

We can do the NaN --> null swap on the GPU using the functionality we've already written in `cudautils.mask_from_devary` which will soon be replaced with a more optimized implementation in libgdf. The problem is if we have a combination of nulls and NaNs then it becomes a tricker situation but this can't happen in pure arrays.

PyArrow has a parameter called `from_pandas` on its `pyarrow.Array` and `pyarrow.Table` constructors that when true treats NaN as nulls, otherwise it treats NaN as a discrete value.

On a side note, some quick testing shows we should definitely do this on the GPU as even our unoptimized implementation gives significant speedup:

```
import pyarrow as pa
import numpy as np
from numba import cuda
import cudf as gd

test_np = np.random.randn(int(1e8)) 
test_np[np.random.choice(test_np.size, int(len(test_np)/2), replace=False)] = np.nan
gpu_test_np = cuda.to_device(test_np)

%timeit pa.array(test_np, from_pandas=True)
# 853 ms ± 31 ms per loop (mean ± std. dev. of 7 runs, 1 loop each) 

%timeit gd.cudautils.mask_from_devary(gpu_test_np)
# 6.84 ms ± 14.1 µs per loop (mean ± std. dev. of 7 runs, 100 loops each) 
```

**Comment by randerzander** [comment]
```df['a'] = cudf.Series([0.0, 1.1, 2.2, nan], nan_as_null=True)```

Makes sense to me- let's have nan_as_null = False by default.

"The problem is if we have a combination of nulls and NaNs then it becomes a tricker situation but this can't happen in pure arrays." -- what will happen in the case of mixed nulls and NaNs in a numpy array?

**Comment by kkraus14** [comment]
> "The problem is if we have a combination of nulls and NaNs then it becomes a tricker situation but this can't happen in pure arrays." -- what will happen in the case of mixed nulls and NaNs in a numpy array?

This actually can't happen. Numpy doesn't have a second allocation for a bitmask or anything, it uses a binary float representation for NaN which is why you can't have NaN in integers in Numpy / Pandas. It's moreso the case in cuDF that you could have both NaN and null and if you wanted to convert the NaNs to nulls you'd have to convert the nulls to NaNs first and then convert all the NaNs to nulls to get the correct results. Will work on updating the implementation with this parameter.

**Comment by kkraus14** [comment]
rerun tests

**Comment by kkraus14** [comment]
Reverted behavior to current default behavior but can easily be changed in a followup PR.

**Comment by kkraus14** [comment]
Merging.

**Pull request merged**
