### PR TITLE
Update cudf java bindings to 21.12.0-SNAPSHOT

### PR DESCRIPTION
**Pull request by pxLi**
Signed-off-by: Peixin Li <pxli@nyu.edu>

update cudf JNI version to 21.12.0

### CODE REVIEW

**Comment by pxLi** [comment]
waiting CI ready for branch-21.12

**Review by revans2 — APPROVED** [review]

**Comment by pxLi** [comment]
rerun tests

**Comment by pxLi** [comment]
CI failed
```
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   TableTest.testPartition:2927->assertTablesAreEqual:322->assertPartialTablesAreEqual:312->assertPartialColumnsAreEqual:161->assertPartialColumnsAreEqual:210 Column 0 Row 2 ==> expected: <5> but was: <9>
[ERROR]   NvcompTest.testBatchedLZ4CompressRoundTrip:183 mismatch in batch buffer 0 ==> array contents differ at index [2049], expected: <1> but was: <0>
[ERROR]   NvcompTest.testBatchedLZ4RoundTripAsync:120 mismatch in batch buffer 0 ==> array contents differ at index [2049], expected: <1> but was: <0>
[ERROR]   NvcompTest.testLZ4RoundTripAsync:38->lz4RoundTrip:316 Expected 256 at 256 found 0
[ERROR]   NvcompTest.testLZ4RoundTripSync:33->lz4RoundTrip:316 Expected 256 at 256 found 0
[ERROR] Errors: 
[ERROR]   TableTest>CudfTestBase.afterAll:53 » Rmm Could not shut down RMM there appear ...
[ERROR]   CompiledExpressionTest>CudfTestBase.afterAll:53 » Rmm Could not shut down RMM ...
[INFO] 
[ERROR] Tests run: 1075, Failures: 5, Errors: 2, Skipped: 5
[INFO] 

```

**Comment by pxLi** [comment]
the version upgrade should not affect cudf java CI check, could be librmm 21.12 has not merged new commits from branch-21.10
@jlowe  @revans2 do you have any idea why above cases failed? Thanks

BTW our docker env and build script also failed locally 

```
[ERROR] Errors:
[ERROR]   TableTest>CudfTestBase.afterAll:53 ? Rmm Could not shut down RMM there appear ...
```
TableTest was the only one constantly failed when running w/ 'mvn test', 
but it passed if we specify `-Dtest=ai.rapids.cudf.TableTest` only. Looks like some where have resource leak

**Comment by jlowe** [comment]
I was not able to reproduce any test failures, and I see the Java CI build has now passed.  However I did see in the test logs at least one leak that was generated by one of the tests.  If the JVM doesn't garbage collect in a timely manner then that can lead to a failure to shutdown RMM.

I'll post a PR shortly to fix the leak in the test.

**Pull request merged**
