### PR TITLE
Add thrust output iterator fix (1805) to thrust.patch

### PR DESCRIPTION
**Pull request by davidwendt**
## Description
Adds fix from https://github.com/NVIDIA/thrust/pull/1805 to libcudf's `thrust.patch` 

## Checklist
- [x] I am familiar with the [Contributing Guidelines](https://github.com/rapidsai/cudf/blob/HEAD/CONTRIBUTING.md).
- [x] New or existing tests cover these changes.
- [x] The documentation is up to date with these changes.

### CODE REVIEW

**Review by harrism — APPROVED** [review]
Thanks @davidwendt !

**Comment by vyasr** [comment]
I would suggest waiting for the corresponding thrust PR to get merged, but it looks like it's already approved and they're just deciding which branch to put the changes on so I'm OK merging this sooner.

**Comment by harrism** [comment]
@vyasr it can take a while to merge Thrust PRs because they merge into main and have to be careful...  (Not to mention their CI takes 50 hours per compiler version!)

**Comment by harrism** [comment]
cuDF does use `transform_output_iterator` so I'm guessing if this change was going to break it, it would have shown up in CI for this PR.

**Comment by harrism** [comment]
@gpucibot merge

**Comment by harrism** [comment]
Wow, did I lose merge permission?

**Pull request merged**
