### PR TITLE
[REVIEW] Fixes bug where we were going off the end of the validity buffer

### PR DESCRIPTION
**Pull request by abellina**
Fixes a small off-by-one error in the java api when serializing validity buffers.

### CODE REVIEW

**Comment by revans2** [comment]
@abellina can you upmerge to kick CI on this again?

**Comment by abellina** [comment]
@revans2 upmerged.

**Comment by dillon-cullinan** [comment]
rerun tests

**Comment by abellina** [comment]
@dillon-cullinan @kkraus14 ok so what happened was that the commit I wanted to add here got added in a different PR https://github.com/rapidsai/cudf/commit/0143c8c0d76f541e2aeeb28069b57fdd79e7a0f4. I still would like the CHANGELOG updated, but otherwise git is showing the state of this correctly.

**Pull request closed without merging**
