### PR TITLE
Fix floating point data generation in benchmarks

### PR DESCRIPTION
**Pull request by vuule**
`numeric_limits::lowest` and `numeric_limits::max` are used as bounds for numeric type generation. However, for normal generators, bounds are shifted to `[0, upper_bound - lower_bound]`, and the random value is shifted back by `lower_bound`.
with `lowest` and `max`, `upper_bound - lower_bound` is out of range for floats and generated values are `nan` and `inf`.
This PR halves the ranges so that `upper_bound - lower_bound` is still within the type range.

Expected to affect benchmarks that use floating point columns (e.g. Parquet reader benchmarks).

### CODE REVIEW

**Review by bdice — APPROVED** [review]
This looks good. Thank you for including the comment.

**Comment by bdice** [comment]
Tests appear to be failing with an unrelated error? https://github.com/rapidsai/cudf/pull/10150?

```
ImportError: /opt/conda/envs/rapids/lib/python3.9/site-packages/cudf/_lib/text.cpython-39-x86_64-linux-gnu.so: undefined symbol:
_ZN4cudf2io4text15multibyte_splitERKNS1_17data_chunk_sourceERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESt8optionalINS1_15byte_range_infoEEPN3rmm2mr22device_memory_resourceE
```

**Comment by vuule** [comment]
> Tests appear to be failing with an unrelated error? #10150?
> 
> ```
> ImportError: /opt/conda/envs/rapids/lib/python3.9/site-packages/cudf/_lib/text.cpython-39-x86_64-linux-gnu.so: undefined symbol:
> _ZN4cudf2io4text15multibyte_splitERKNS1_17data_chunk_sourceERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESt8optionalINS1_15byte_range_infoEEPN3rmm2mr22device_memory_resourceE
> ```

I think it's a CI weirdness caused by API changes in #10150. Merged latest, that usually helps in such cases.

**Review by nvdbaranec — APPROVED** [review]

**Comment by vuule** [comment]
@gpucibot merge

**Pull request merged**
