### PR TITLE
Fix groupby include

### PR DESCRIPTION
**Pull request by bwyogatama**
This PR fixes include that are not grouped correctly in `groupby.hpp`.
This is my first pull request that I'm working on with @bdice !

### CODE REVIEW

**Review by bdice — APPROVED** [review]
Looks good to me. Thanks for this fix. :)

**Review by ttnghia — APPROVED** [review]

**Review by PointKernel — APPROVED** [review]
Looks good to me! :+1:

**Comment by bwyogatama** [comment]
@gpucibot merge

**Comment by ttnghia** [comment]
@gpucibot merge

**Comment by ttnghia** [comment]
> @gpucibot merge

So you may need to be added to the writer group :smiley:

**Pull request merged**
