### PR TITLE
[REVIEW] Remove cuda 11.1 related files

### PR DESCRIPTION
**Pull request by galipremsagar**
Since we never initially supported cuda 11.1, this PR removes respective files and usages.

### CODE REVIEW

**Comment by kkraus14** [comment]
Should we remove these as well? https://github.com/rapidsai/cudf/tree/branch-0.20/python/cudf/requirements/cuda-11.1

**Comment by galipremsagar** [comment]
> Should we remove these as well? https://github.com/rapidsai/cudf/tree/branch-0.20/python/cudf/requirements/cuda-11.1

Yup, done 👍

**Comment by galipremsagar** [comment]
rerun tests

**Review by ajschmidt8 — APPROVED** [review]

**Review by kkraus14 — APPROVED** [review]

**Comment by kkraus14** [comment]
@gpucibot merge

**Pull request merged**
