### PR TITLE
Temporarily disabling problematic test in parquet writer

### PR DESCRIPTION
**Pull request by devavret**
There is a bug in parquet writer that shows up in one pytest.
Disabling this test to unblock CI for other PRs.

Related to #9231

### CODE REVIEW

**Review by brandon-b-miller — APPROVED** [review]

**Comment by brandon-b-miller** [comment]
Is there an open issue tracking the bug mentioned here?

**Comment by devavret** [comment]
> Is there an open issue tracking the bug mentioned here?

Not yet. This comes from a slack thread where CI issues were being discussed.

**Comment by vyasr** [comment]
I think this PR is probably worth getting merged ASAP to unblock CI since it is randomly forcing people to rerun tests, but it probably is worth opening an issue in case this turns out to be something that we can reproduce? I don't know if it really is a CI bug or just an intermittent problem that arises with a specific CUDA/Python/OS combination. Based on CI it was Ubuntu 18.04, CUDA 11.2, Python 3.8 I believe.

**Comment by devavret** [comment]
> I think this PR is probably worth getting merged ASAP to unblock CI since it is randomly forcing people to rerun tests, but it probably is worth opening an issue in case this turns out to be something that we can reproduce? I don't know if it really is a CI bug or just an intermittent problem that arises with a specific CUDA/Python/OS combination. Based on CI it was Ubuntu 18.04, CUDA 11.2, Python 3.8 I believe.

I believe it's a problem with writing an all null dataframe to parquet in Pascal. I found that the other two CI machines have Volta and Ampere.

**Comment by devavret** [comment]
rerun tests

**Comment by devavret** [comment]
@gpucibot merge

**Pull request merged**
