### PR TITLE
[REVIEW] compile_udf: compile straight to PTX instead of using @jit

### PR DESCRIPTION
**Pull request by gmarkall**
Rather than using the `@cuda.jit` decorator then extracting the PTX, Numba 0.50 provides a function to compile a Python function straight to PTX with no jitting. This PR changes `compile_udf` to use this function.

All tests pass for me locally. I've marked the PR as WIP because it will first need the CI environment to be updated to 0.50 before merge.

### CODE REVIEW

**Comment by GPUtester** [comment]
Please update the changelog in order to start CI tests.

View the gpuCI docs [here](https://docs.rapids.ai/gpuci#open-pr-or-update-pr).

**Comment by jrhemstad** [comment]
So does this make getting the PTX for a UDF faster?

**Comment by gmarkall** [comment]
> So does this make getting the PTX for a UDF faster?

Possibly - when I tested this patch in the past, it took the unit testing time down from 316 seconds to 308 seconds: https://github.com/numba/numba/pull/5561#issuecomment-616593604

Unfortunately unit tests aren't a very good benchmark :-) - do you know of something that would be better for me to measure with / without this patch to see what difference it makes for a more realistic use case?

**Comment by kkraus14** [comment]
Pushing to 0.16.

**Comment by harrism** [comment]
Should we push to 0.17? @gmarkall @kkraus14

**Comment by kkraus14** [comment]
> Should we push to 0.17? @gmarkall @kkraus14

No, this is planned to get in for 0.16.

**Comment by gmarkall** [comment]
Now that cuDF uses Numba 0.51.2, I've removed the temporary attempt to test with Numba >0.50, and this is now ready for review.

**Review by kkraus14 — APPROVED** [review]

**Pull request merged**
