### PR TITLE
Move template parameter to function parameter in cudf::detail::left_semi_anti_join

### PR DESCRIPTION
**Pull request by davidwendt**
The `semi_join.cu` takes about 6 minutes to compile on my Linux 18.04 desktop when doing a full build of libcudf. The `join_kind` template parameter used internally in `cudf::detail::left_semi_anti_join` for `left_semi_join` and `left_anti_join` APIs is not used in a `constexpr` or to pass to any other templated function. This PR moves the template parameter to a runtime parameter on the detail functions reducing the compile time for `semi_join.cu` by ~2x.

Another improvement includes un-inlining the `is_trivial_join` utility function to reduce the compile time for files that include `join_common_utils.hpp`.

Finally, the device vector used as a gather map in `detail::left_semi_anti_join` was wrapped with a `column_view`  in order to call `detail::gather` without iterators. This allowed not including the heavy `gather.cuh`. This improved the compile time about 10% and reduced the object file `semi_join.cu.o` size by 2x.

### CODE REVIEW

**Comment by vyasr** [comment]
In #8815 I also created a `join_common_utils.cuh` header for code that's common for normal and conditional joins in the CUDA layers. A significant chunk of that file is also inline functions. I doubt they'll have as significant of an impact, but perhaps it makes sense to break some of those out of the header as well so that they don't get recompiled for both sets of join TUs? I believe at least a few of them are not templated.

**Comment by davidwendt** [comment]
> In #8815 I also created a `join_common_utils.cuh` header for code that's common for normal and conditional joins in the CUDA layers. A significant chunk of that file is also inline functions. I doubt they'll have as significant of an impact, but perhaps it makes sense to break some of those out of the header as well so that they don't get recompiled for both sets of join TUs? I believe at least a few of them are not templated.

Yes, thanks. I see there are 3 host-only utility functions that could be moved to a .cpp or .cu file. Perhaps I could add a `join_utils.cpp` for these and the `is_trivial_join` utility as well.

**Review by hyperbolic2346 — APPROVED** [review]
Do we know the run-time impact of these changes? My only concern here is that we may trade compile time performance for run-time performance.

**Comment by davidwendt** [comment]
> Do we know the run-time impact of these changes? My only concern here is that we may trade compile time performance for run-time performance.

Running `benchmarks/JOIN_BENCH` did not show any change in runtime performance for these changes.

**Review by harrism — APPROVED** [review]
Looks good @davidwendt .

**Comment by harrism** [comment]
@gpucibot merge

**Pull request merged**
