### PR TITLE
Disallow picking output columns from nested columns.

### LINKED ISSUE #7229: [BUG] Parquet reader segfaults loading file with nested type as map key
**Describe the bug**
libcudf crashed with a segfault while trying to load a Parquet file containing a column with a Map type.  This file is a bit interesting since the Map key is a nested type instead of a primitive type.  I verified this file can be loaded successfully in Apache Spark.

The crash occurs when trying to specify the column name to load from this file.  Without specifying the name of any column to load the crash does not occur.

**Steps/Code to reproduce bug**
A sample Parquet file is attached that can reproduce the crash.

[maptest.parquet.zip](https://github.com/rapidsai/cudf/files/5882866/maptest.parquet.zip)

Unzip the archive and use the following test code to reproduce the crash.
```c++
#include <cudf/io/parquet.hpp>
#include <cudf/table/table.hpp>

int main() {
  auto path = std::string("maptest.parquet");
  auto opts = cudf::io::parquet_reader_options::builder(cudf::io::source_info(path))
    // NOTE: without specifying the column name it does not crash
    .columns({"value"})
    .build();
  auto result = cudf::io::read_parquet(opts);
  return 0;
}
```

**Expected behavior**
libcudf methods should not segfault with valid inputs.

### PR DESCRIPTION
**Pull request by devavret**
Only top level columns can be selected by name

Fixes #7229

### CODE REVIEW

**Comment by vuule** [comment]
As we discussed offline - you can use the file included in the issue for testing.

**Comment by jlowe** [comment]
> Only top level columns can be selected by name

To implement efficient queries on nested types we'll need the ability to specify a non-top-level column to load (e.g.: only loading one of the three fields in a top-level struct column).  Will we be able to specify a fully-qualified path to that column from the root?

**Comment by devavret** [comment]
> Will we be able to specify a fully-qualified path to that column from the root?

That's exactly what we discussed offline. That we should probably enable that after this fix and the method to do that should be to specify not just the name but the path in schema e.g. `"name.first"`

**Review by karthikeyann — APPROVED** [review]

**Review by vuule — APPROVED** [review]

**Review by nvdbaranec — APPROVED** [review]

**Comment by vuule** [comment]
rerun tests

**Comment by vuule** [comment]
Perhaps the title should have 'disallow', rather than 'disallowing'.

**Comment by devavret** [comment]
@gpucibot merge

**Review by kkraus14 — APPROVED** [review]

**Pull request merged**
