### PR TITLE
Move compute_column API out of ast namespace

### PR DESCRIPTION
**Pull request by vyasr**
The `compute_column` API is functionally analogous to `cudf::transform`, except that the former expresses the transformation in terms of a cudf expression while the latter accepts string UDFs to be JITted and evaluated. Moving `compute_column` into `transform.hpp` means that the only public APIs in the `ast` namespace are those required to _define_ an expression, so we clearly separate the logic for defining and parsing of expressions from APIs (like conditional joins and `compute_column`) that evaluate those expressions on device and then use the output in different ways.

### CODE REVIEW

**Comment by vyasr** [comment]
@harrism you requested a better name for the `compute_column` API if it's moved outside of the `ast` namespace [here](https://github.com/rapidsai/cudf/pull/8783#discussion_r672718329). The closest API currently in cudf is the `transform` function, which is also extremely generic. Any thoughts on how you'd like to move forward with that?

@jlowe I've updated the JNI bindings, so we should be good to go for now. If the function name changes I'll attempt to propagate that through as well, but I may need a bit of help with that to make sure that I get everything since that will also affect all the Java code using this API (right now the change is just a namespace change when calling the C++ API, which is internal to the JNI).

**Review by jlowe — APPROVED** [review]

**Review by vuule — APPROVED** [review]
Looks good. Not sure if I understand why the changes are made, but PR itself is :+1:

**Comment by vyasr** [comment]
> Looks good. Not sure if I understand why the changes are made, but PR itself is 👍

This API just says "compute a new column by performing some operation on the rows of a table", which is essentially the same as `cudf::transform`. That behavior should dictate where the API lives, not the fact that it happens to represent the operation by an AST expression, otherwise APIs like conditional joins would also live in the `cudf::ast` namespace. In general, since AST expression evaluation could be used in many places we want to limit the `cudf::ast` namespace to just the logic for defining expressions (and `cudf::ast::detail` to internal code for parsing and evaluating those expressions in device code).

**Review by robertmaynard — APPROVED** [review]
CMake changes LGTM

**Comment by vyasr** [comment]
@gpucibot merge

**Review by trxcllnt — APPROVED** [review]

**Comment by trxcllnt** [comment]
@gpucibot merge

**Review by raydouglass — APPROVED** [review]

**Pull request merged**
