### PR TITLE
Remove ERROR_TEST gtest from libcudf

### PR DESCRIPTION
**Pull request by davidwendt**
## Description
Removes the `ERROR_TEST` gtest from libcudf. This test was only verifying some macros on mostly CUDA behavior and not libcudf specific functions. The tests have become troublesome to support in CI especially in conjunction with other tools like `compute-sanitizer`.

## Checklist
- [x] I am familiar with the [Contributing Guidelines](https://github.com/rapidsai/cudf/blob/HEAD/CONTRIBUTING.md).
- [x] New or existing tests cover these changes.
- [x] The documentation is up to date with these changes.

### CODE REVIEW

**Review by bdice — COMMENTED** [review]
Could we drop only the problematic tests? I assume they are the kernel ones, and CUDF_EXPECTS tests are not an issue?

**Comment by davidwendt** [comment]
> Could we drop only the problematic tests? I assume they are the kernel ones, and CUDF_EXPECTS tests are not an issue?

I'm not sure what the advantage would be. If the macros fail, we should certainly see them in other tests. I'm not seeing much value in these tests currently.

The current problem I'm having is with `compute-sanitizer` which reports an error if it found no kernels to measure.
Skipping this test is easy enough with the current script but I'm concerned on how do that with a ctest in the future too.
Removing the tests fixes all of this.

**Review by bdice — APPROVED** [review]
Okay. I don’t know if we have explicit coverage for our macros’ handling of CUDA failure modes elsewhere, but if you’re confident these tests are duplicating coverage from other tests, we can remove them.

**Review by ttnghia — APPROVED** [review]
I agree that the removed code does not add value to our testing.

**Comment by vyasr** [comment]
For posterity, here's the Slack thread where David and I discussed and agreed upon the removal previously: https://nvidia.slack.com/archives/C03DJ7YQB2Q/p1725022526642819?thread_ts=1725001094.550349&cid=C03DJ7YQB2Q

**Review by JayjeetAtGithub — APPROVED** [review]

**Pull request merged**
