### PR TITLE
Use same .clang-format in cuDF JNI

### LINKED ISSUE #15546: [BUG] cuDF JNI should use the same .clang-format as the rest of cuDF
**Describe the bug**
libcudf JNI has its own .clang-format file with different rules. It should not.  For example, headers are ordered in the OPPOSITE order in JNI files from the order in the rest of libcudf.

### PR DESCRIPTION
**Pull request by bdice**
## Description
Closes #15546.

Currently cuDF JNI uses its own `.clang-format` settings. These settings organize includes differently than the rest of the cuDF C++ codebase, so we would like to align them.

This PR removes the JNI's custom `.clang-format` and instead uses the same settings as the rest of cuDF.

## Checklist
- [x] I am familiar with the [Contributing Guidelines](https://github.com/rapidsai/cudf/blob/HEAD/CONTRIBUTING.md).
- [x] New or existing tests cover these changes.
- [x] The documentation is up to date with these changes.

### CODE REVIEW

**Review by ttnghia — APPROVED** [review]
Do we have CI style check for the java folder?

**Comment by bdice** [comment]
> Do we have CI style check for the java folder?

The changes in this PR were enforced by pre-commit, so I’d say yes.

**Review by harrism — APPROVED** [review]
Thank you @bdice!

**Comment by harrism** [comment]
JNI compilation errors are due to the reordering exposing cases where files did not IWYU.  e.g. 
```
In file included from /__w/cudf/cudf/java/src/main/native/src/CompiledExpression.cpp:18:
     [exec] /__w/cudf/cudf/java/src/main/native/src/jni_compiled_expr.hpp:36:37: error: 'ast' is not a member of 'cudf'; did you mean 'cudf::jni::ast'?
```

This file uses libcudf AST types without a corresponding include.

**Pull request merged**
