### PR TITLE
[REVIEW] Fixes in gdf_apply_stencil

### LINKED ISSUE #1313: [BUG] Issues in gdf_apply_stencil
Found following issues in gdf_apply_stencil, stream_compaction_ops.cu while trying to address https://github.com/rapidsai/cudf/issues/371
1. remove_if not working as expected - predicate should be invert of stencil
```
thrust::remove_if(rmm::exec_policy(stream)->on(stream),valid_bit_mask.begin(), valid_bit_mask.begin() + num_values,zipped_stencil_iter, is_stencil_true<thrust::detail::normal_iterator<thrust::device_ptr<int8_t> >::value_type >());
```
2. bit_mask_pack_op is not implemented correct in the context of the following snippet
```
    thrust::transform(rmm::exec_policy(stream)->on(stream), valid_bit_mask_group_8_iter, valid_bit_mask_group_8_iter + ((num_values + GDF_VALID_BITSIZE - 1) / GDF_VALID_BITSIZE),
337             thrust::detail::make_normal_iterator(thrust::device_pointer_cast(output->valid)),bit_mask_pack_op());
```
```
if a valid_bit_mask is - `1, 1, 1, 1, 0, 0, 1, 1`
Expected mask is 0x3f
But with current implementation it is 0xf3
```
Reproduce:
Add the following testcase:
```
TEST_F(FilterOperationsTest, check_remove_if) {                                                                                                                             
     int column_size = 8;                                                                                                                                                    
     int init_value = 10;                                                                                                                                                    
                                                                                                                                                                             
     std::vector<gdf_valid_type> valid_masks(gdf_valid_allocation_size(column_size), 255);                                                                                   
                                                                                                                                                                             
     std::cout << "Left" << std::endl;                                                                                                                                       
     std::vector<int16_t> l_data(column_size, init_value);                                                                                                                   
     for(auto it  = l_data.begin(); it != l_data.end(); it++)                                                                                                                
     {                                                                                                                                                                       
         *it = ++init_value;                                                                                                                                                 
     }                                                                                                                                                                       
     auto c_lhs = cudf::test::column_wrapper<int16_t>{l_data, valid_masks};                                                                                                  
     c_lhs.print();                                                                                                                                                          
                                                                                                                                                                             
     std::cout << "Right" << std::endl;                                                                                                                                      
     std::vector<int16_t> r_data(column_size, init_value);                                                                                                                   
     auto c_rhs = cudf::test::column_wrapper<int16_t>{r_data, valid_masks};                                                                                                  
     c_rhs.print();                                                                                                                                                          
                                                                                                                                                                             
     std::cout << "Stencil" << std::endl;                                                                                                                                    
     std::vector<int8_t> o_data(column_size, 1);                                                                                                                             
     valid_masks[0] = 0xc3;                                                                                                                                                  
     auto c_stencil = cudf::test::column_wrapper<int8_t>{o_data, valid_masks};                                                                                               
     c_stencil.print();                                                                                                                                                      
                                                                                                                                                                             
     gdf_error err = gdf_apply_stencil(c_lhs, c_stencil, c_rhs);                                                                                                             
     EXPECT_EQ(err, GDF_SUCCESS);                                                                                                                                            
     std::cout << "Right [After stencil op]" << std::endl;                                                                                                                   
     c_rhs.print();                                                                                                                                                          
                                                                                                                                                                             
     std::vector<int16_t> expected_values{11, 12, 17, 18};                                                                                                                   
     valid_masks[0] = 0x0f;                                                                                                                                                  
     auto e_rhs = cudf::test::column_wrapper<int16_t>{expected_values, valid_masks};      
     EXPECT_TRUE(c_rhs == e_rhs);                                                                                                                                            
}
```

Possible fixes:
1. Implement *is_stencil_false* and use it as predicate in **remove_if**
```
thrust::remove_if(rmm::exec_policy(stream)->on(stream),valid_bit_mask.begin(), valid_bit_mask.begin() + num_values,zipped_stencil_iter, is_stencil_false<thrust::detail::normal_iterator<thrust::device_ptr<int8_t> >::value_type >());
```
2. **bit_mask_pack_op** update to
```
for(unsigned int i = 0; i < GDF_VALID_BITSIZE; i++){                                                                                                            
     // 0, 8, 16, ....,48,  56                                                                                                                                   
     unsigned char byte = (expanded >> ( i * 8));                                                                                                                
     result |= (byte & 1) << i;                                                                                                                                  
}  
```

### PR DESCRIPTION
**Pull request by Shakeebbk**
Fixes #1313

### CODE REVIEW

**Comment by GPUtester** [comment]
Can one of the admins verify this patch?

**Comment by kkraus14** [comment]
ok to test

**Comment by harrism** [comment]
I'm working on a PR that may make this one redundant. Will update when it's ready to push the PR.

**Comment by eyalroz** [comment]
@harrism : Umm, there's also my PR - and I'm working on reducing the amount of "baggage" it has in terms of utility code (for the host-side stuff - see PR #1366 ). Will ping you on Slack about this.

**Comment by harrism** [comment]
superseded by #1654

**Pull request closed without merging**
