### PR TITLE
[REVIEW] FIX Add codecov upload block to gpu script

### PR DESCRIPTION
**Pull request by dillon-cullinan**
This moves a block from the Jenkins build into the build script. Simplifies the Jenkins builds slightly and fixes a very rare case where tests may error and not be properly caught due to EXITCODE intricacies.

### CODE REVIEW

**Comment by GPUtester** [comment]
Please update the changelog in order to start CI tests.

View the gpuCI docs [here](https://docs.rapids.ai/gpuci#open-pr-or-update-pr).

**Review by raydouglass — APPROVED** [review]

**Review by ajschmidt8 — APPROVED** [review]

**Comment by kkraus14** [comment]
@dillon-cullinan what's the plan with this PR?

**Comment by dillon-cullinan** [comment]
@kkraus14 should be good to merge, PR builder is passing.

**Comment by dillon-cullinan** [comment]
@kkraus14 should be good to merge after CI runs.

**Comment by kkraus14** [comment]
@gpucibot merge

**Pull request merged**
