### PR TITLE
Update Java tests to expect DECIMAL128 from Arrow

### PR DESCRIPTION
**Pull request by jlowe**
After #9986 reading Arrow in libcudf now returns DECIMAL128 instead of DECIMAL64.  This updates the Java tests to expect DECIMAL128 instead of DECIMAL64 by upcasting the decimal columns in the original table being round-tripped through Arrow before comparing the result.

### CODE REVIEW

**Review by rongou — APPROVED** [review]

**Review by mythrocks — APPROVED** [review]
The fix makes sense, given the current `libcudf` behaviour. LGTM!

**Review by ttnghia — APPROVED** [review]

**Comment by jlowe** [comment]
@gpucibot merge

**Comment by galipremsagar** [comment]
rerun tests

**Comment by galipremsagar** [comment]
rerun tests

**Comment by robertmaynard** [comment]
rerun tests

**Pull request merged**
