### PR TITLE
[WIP] Remove RMM init/finalize from cudf test fixture.

### PR DESCRIPTION
**Pull request by jrhemstad**
Cut down on some of the warnings after https://github.com/rapidsai/rmm/pull/331 by removing the deprecated init/finalize in the cudf test fixture.

### CODE REVIEW

**Comment by jrhemstad** [comment]
> Is this related to this #4448 in some way? Maybe that can be closed now?

Unrelated. 

> Also, is this supposed to go into 0.13 or 0.14?

0.13 to minimize warnings from RMM.

**Comment by davidwendt** [comment]
Looks like the gtests are failing now. Any reason why this must go into 0.13? 
Seems like a global change to all gtests should not be allowed during burndown.

**Comment by jrhemstad** [comment]
> Looks like the gtests are failing now. Any reason why this must go into 0.13?
> Seems like a global change to all gtests should not be allowed during burndown.

I'm aware and working on it.

The release has been delayed.

**Comment by harrism** [comment]
We are indeed still in burn down (delaying the release did not change that, it just extended burn down). But this is a necessary improvement to reduce warnings now that we decided to go ahead with deprecation of rmmInit and friends in 0.13. We decided to go ahead with that because we want to *remove* them in 0.13, and that would not be fair without first deprecating them in a way that warns people. But it turns out those warnings are pretty noisy, hence this PR.

**Comment by jrhemstad** [comment]
This is going to be WIP until all raw alloc/free calls are removed from libcudf as these calls will return a "not initialized" error.

**Pull request merged**
