### PR TITLE
[REVIEW] Parquet option for strictly decimal reading [skip ci]

### PR DESCRIPTION
**Pull request by sperlingxx**
This PR is about to add a parquet option to determine whether strictly reading all decimal columns as fixed-point decimal types or converting decimal column who are not backed by int32/64 to float64.
The default value of this option is `false`, because reading `FIXED_LENGTH_BYTE_ARRAY` as decimal is not supported by now.

### CODE REVIEW

**Comment by GPUtester** [comment]
Please update the changelog in order to start CI tests.

View the gpuCI docs [here](https://docs.rapids.ai/gpuci#open-pr-or-update-pr).

**Review by jlowe — COMMENTED** [review]
Do we need a 95K decimal parquet file when we're not even checking the values loaded from it?  That should be trimmed.

**Review by revans2 — APPROVED** [review]
Agree that the test file looks rather large, but it is close enough to the freeze that I am OK with it.

**Comment by sperlingxx** [comment]
> Do we need a 95K decimal parquet file when we're not even checking the values loaded from it? That should be trimmed.

I've shrinked the size of file to 6.5K.

**Pull request merged**
