### PR TITLE
[REVIEW] Fix uncaught string initialization when `object` dtype is in from_pandas and column creation

### PR DESCRIPTION
**Pull request by thomcom**
Fixes the specific issue presented in #626.

### CODE REVIEW

**Comment by kkraus14** [comment]
rerun tests

**Comment by mike-wendt** [comment]
rerun tests

**Comment by mike-wendt** [comment]
rerun tests

**Comment by thomcom** [comment]
The failing test in this should be an xfail @mrocklin ?

**Comment by mrocklin** [comment]
Not sure I'm the best person to answer that, but xfailing seems reasonable to me if we're not supporting this yet.

**Comment by thomcom** [comment]
Sorry, I ask because I think it is your test - loading a DF with a string series, 'Alice', 'Bob', etc, we were working on last week. Maybe I've confused myself.

**Comment by mrocklin** [comment]
xfail away then

**Comment by kkraus14** [comment]
rerun tests

**Comment by kkraus14** [comment]
rerun tests

**Comment by kkraus14** [comment]
rerun tests

**Pull request merged**
