### PR TITLE
Revert "Fix leaks in ColumnVectorTest"

### PR DESCRIPTION
**Pull request by cindyyuanjiang**
Reverts rapidsai/cudf#12625.

Due to test failures in the spark-rapids side: https://github.com/NVIDIA/spark-rapids/issues/7607

### CODE REVIEW

**Comment by ttnghia** [comment]
#12625 should not introduce any failure. Do you know the specific code in that PR that causes the test to fail? If the failure is indeed due to it then you should just fix that test, not reverse everything.

**Comment by ttnghia** [comment]
I just realized that the failed tests are in spark-rapids. So I'm confused why changes in cudf tests could affect spark-rapids tests.

**Comment by cindyyuanjiang** [comment]
> I just realized that the failed tests are in spark-rapids. So I'm confused why changes in cudf tests could affect spark-rapids tests.

@ttnghia We want to revert all PRs related to adding regex program APIs and tests and this is one of the PRs. I put up a new PR to revert all changes altogether, sorry about the confusion.

**Comment by cindyyuanjiang** [comment]
Tracked by: https://github.com/rapidsai/cudf/pull/12639

**Pull request closed without merging**
