### PR TITLE
Implement `interleave_columns` for structs columns

### LINKED ISSUE #8927: [FEA] Support creating lists of structs
**Is your feature request related to a problem? Please describe.**
I am trying to implement a GPU version of Spark's `CreateMap` expression (https://github.com/NVIDIA/spark-rapids/issues/3014) but cuDF doesn't currently support creating a list of structs. The cuDF `interleave_columns_functor` looks for fixed-width, string_view, or list_view but the list view requires non-nested children, so I get an unsupported type error.

**Describe the solution you'd like**
Here is the rough code that I would like to write in the Spark plugin:

```scala
val struct = ColumnVector.makeStruct(keyColumn, valueColumn)
val list = ColumnVector.makeList(numRows, DType.STRUCT, struct)
GpuColumnVector.from(list, dataType)
```

**Describe alternatives you've considered**
None

**Additional context**
None

### PR DESCRIPTION
**Pull request by ttnghia**
This PR adds support for structs column in the `interleave_column` API. In addition, it also does a simple refactor of the existing overload functions with a new style of SFINAE implementation.
Closes #8927.

### CODE REVIEW

**Review by davidwendt — APPROVED** [review]

**Review by rgsl888prabhu — COMMENTED** [review]
Had a question, does this support struct with nesting level more than 1? like Struct{Struct{Struct}}, adding a test case to cover that scenario would be helpful.

Rest looks good.

**Comment by ttnghia** [comment]
> Had a question, does this support struct with nesting level more than 1? like Struct{Struct{Struct}}, adding a test case to cover that scenario would be helpful.
> 
> Rest looks good.

Thanks for the recommendation. Nested structs should be supported, as the interleaving process is called recursively on the children columns. I have added a test for this (2 nested levels should be enough for verifying this case).

**Review by rgsl888prabhu — APPROVED** [review]

**Comment by ttnghia** [comment]
Rerun tests.

**Comment by ttnghia** [comment]
@gpucibot merge

**Pull request merged**
