### PR TITLE
[REVIEW] Implementation of `DataFrame.iloc[]` and `Series.iloc[]` feature 

### PR DESCRIPTION
**Pull request by AK-ayush**
This PR implement the `DataFrame.iloc[]` and `Series.iloc[]` feature similar to pandas api. 
Right now, this feature is implemented **on rows only**.

This feature is suggested by @mrocklin in the issue #606.

### CODE REVIEW

**Comment by AK-ayush** [comment]
Sure, I will add some tests today.

**Comment by beckernick** [comment]
Should we consider maintaining consistency with the pandas API? I expect the following example in the docstring to cause an indexing error based on the dimensionality.

```
# get the rows from indices 0,2,9 and 18.
         >>> df.iloc[0, 2, 9, 18]
              a    b    c
         0    0    0    0
         2    2    2    2
         9    9    9    9
         18   18   18   18
```

I'd expect this output to be generated by `df.iloc[[0, 2, 9, 18]]`.

I know you've listed this as being for rows only currently, but I think allowing this kind of index access `df.iloc[0, 2, 9, 18]` mapping directly to rows might make it more difficult to handle both rows and column based indexing. Would be interested in your thoughts.

**Comment by thomcom** [comment]
Thanks for catching the above @beckernick I'd strongly prefer that we always match Pandas APIs. If they try to use the columnar method before it is supported we should simply throw an exception

```
list_types_tuple = (list, Series, np.Series, np.array) # this should make its way into `util`
# early termination on error condition
if isinstance(arg, list_types_tuple):
    if not isinstance(arg[0], list_types_tuple):
        raise IndexError('cudf columnar iloc not supported')
arg = arg[0]
# continue as normal...
```

**Comment by beckernick** [comment]
To your first question, in my opinion, slicing `-1:1` should reflect standard Python slicing behavior. The example you've shown appears to be wrap-around slicing behavior, which is not standard. If we have: 

```
sample_list = [0,1,2,3,4,5]
```
Using a negative number as an index should simply begin at the nth element from the right of the list, instead of the left. Therefore, `sample_list[-1:1]` should be equivalent to `sample_list[5:1]`, which should return an empty list. By the same logic, `sample_list[-5:3]` is equivalent to `sample_list[1:3]`, which should return `[1, 2]`. Our positional indexing should reflect this standard slicing behavior.

**Comment by AK-ayush** [comment]
Thanks @beckernick for detailed explanation.
I will fix the wrap-around slicing behaviour to reflect the standard python slicing behaviour.

**Comment by thomcom** [comment]
Thanks @AK-ayush and @beckernick ! Here's an example of parallel testing of pandas and cudf, from `test_binops.py`:

```
_reflected_ops = [
    lambda x: 1 + x,
    lambda x: 2 * x,
]


@pytest.mark.parametrize('func, dtype', list(product(_reflected_ops, _dtypes)))
def test_reflected_ops_scalar(func, dtype):
    import pandas as pd

    # create random series
    np.random.seed(12)
    random_series = pd.Series(np.random.sample(100) + 10, dtype=dtype)

    # gpu series
    gs = Series(random_series)
    gs_result = func(gs)

    # pandas
    ps_result = func(random_series)

    # verify
    np.testing.assert_allclose(ps_result, gs_result)
```

There are many more, some of which are less verbose. Does this get you started?

List indexing is v. complicated and potentially difficult, so getting all the tests in place will prevent us from having future bugfixes. :)

**Comment by beckernick** [comment]
Agreed. @AK-ayush I would suggest enumerating the (potentially) failing suite of tests first

**Comment by mrocklin** [comment]
FWIW I mostly care about indexing with ordinary slices like `n:m` where `n <= m`.  I don't personally care about list indexing for dask-cudf work.  I apologize for not saying this upfront.

Of course, implementing more is always good, but if the goal is to get something out quickly then raising informative `NotImplementedError`s seems like a decent first step.

**Comment by thomcom** [comment]
I actually agree that list indexing is probably less important. I think it'd be great to simply have the feature and add to it when asked. I also think that we need almost all of the above unit tests anyway, so that we can communicate the correct Error to the user and believe that we are able to do so across many cases.

**Comment by AK-ayush** [comment]
@thomcom @beckernick @mrocklin can you have a look at it now....
Please let me know if there is any changes required otherwise i'll update the title to [REVIEW] from [WIP].

**Comment by kkraus14** [comment]
This needs to be merged against the latest changes in branch-0.5 to resolve the CI issues.

**Pull request merged**
