### PR TITLE
Restrict CuPy to 6

### PR DESCRIPTION
**Pull request by jakirkham**
As we have not yet tested CuPy 7, restrict cuDF usage to CuPy 6 for now.

### CODE REVIEW

**Comment by jakirkham** [comment]
cc @kkraus14 @rlratzel

**Comment by beckernick** [comment]
This will only be enforced at the time of cuDF installation, correct? I.e., is it correct that I could still install CuPy 7 afterwards if need be?

**Comment by kkraus14** [comment]
> This will only be enforced at the time of cuDF installation, correct? I.e., is it correct that I could still install CuPy 7 afterwards if need be?

It will act as a constraint if you conda install in general. I believe it's possible to override the constraint though.

**Comment by jakirkham** [comment]
> This will only be enforced at the time of cuDF installation, correct? I.e., is it correct that I could still install CuPy 7 afterwards if need be?

It would need to be forced, but yeah you could override.

**Comment by beckernick** [comment]
That's fine with me 👍

**Comment by jakirkham** [comment]
Thanks Ray! 😄

**Comment by jakirkham** [comment]
Looks like this is ready to merge. 🙂

**Comment by jakirkham** [comment]
Thanks @harrism! 😄

**Pull request merged**
