### PR TITLE
Clean up cuco usage

### PR DESCRIPTION
**Pull request by PointKernel**
Depending on https://github.com/rapidsai/rapids-cmake/pull/329

This PR improves cuco implementations by:

- Replacing the deprecated `cuco::sentinel::` namespace by `cuco::`
- Using public `cuco::murmurhash3_32` instead of `cuco::detail::MurmurHash3_32`

## Checklist
- [x] I am familiar with the [Contributing Guidelines](https://github.com/rapidsai/cudf/blob/HEAD/CONTRIBUTING.md).
- [x] New or existing tests cover these changes.
- [x] The documentation is up to date with these changes.

### CODE REVIEW

**Review by ttnghia — APPROVED** [review]

**Review by bdice — APPROVED** [review]
Fantastic. Really happy to see the improvements in cuco! 🚀

**Review by mythrocks — APPROVED** [review]
The material changes look good to me!
(Copyright year needs updating, though, on most of the source files.)

**Comment by PointKernel** [comment]
rerun tests

**Pull request merged**
