### PR TITLE
Address poor performance of Parquet string decoding

### PR DESCRIPTION
**Pull request by etseidl**
## Description
See #15297. The Parquet string decoder can become a bottleneck in the presence of strings of widely varying sizes. This PR is an attempt to address this, at least as a stop gap solution. A more complete solution may be to rework the string decoder to work in a block-wide fashion, such as the new micro-kernels added in #15159.

## Checklist
- [x] I am familiar with the [Contributing Guidelines](https://github.com/rapidsai/cudf/blob/HEAD/CONTRIBUTING.md).
- [x] New or existing tests cover these changes.
- [x] The documentation is up to date with these changes.

### CODE REVIEW

**Comment by etseidl** [comment]
cc @GregoryKimball

**Comment by etseidl** [comment]
String decode current 24.04 top, this PR (using avg length per batch of 32 strings) bottom. Note that there are only 4 pages being decoded in this file.

Screenshot from 2024-03-14 12-33-45

**Comment by GregoryKimball** [comment]
Thank you @etseidl for looking into this performance case!

**Comment by GregoryKimball** [comment]
@etseidl would you please let me know if there are more changes you would like to make - or is this ready for review?

**Comment by etseidl** [comment]
> would you please let me know if there are more changes you would like to make - or is this ready for review?

@GregoryKimball If a quick fix is wanted for 24.04, then I think this is ready. It will take longer to evaluate more complicated solutions. My first attempt at going block wide didn't pan out :(

**Review by ttnghia — APPROVED** [review]

**Review by vuule — APPROVED** [review]
❤️

**Pull request merged**
