### PR TITLE
Use test paths relative to package directory.

### PR DESCRIPTION
**Pull request by bdice**
## Description
This PR standardizes how our test paths are defined for dask-cudf and custreamz. This was originally a test to investigate a question related to CodeCov, which is answered below. We noticed that some coverage reports in the CI outputs used full paths like `/opt/conda/envs/test/lib/python3.10/site-packages/cudf/__init__.py` while other coverage reports gave relative paths like `cudf/__init__.py`. The net result of this PR is that coverage reports are unchanged, but our CI tests are more correct because they always pull from the installed packages rather than the local packages (`import dask_cudf` is fetching the built conda packages from `site-packages` and not importing from the current path in the cloned repo).

## Checklist
- [x] I am familiar with the [Contributing Guidelines](https://github.com/rapidsai/cudf/blob/HEAD/CONTRIBUTING.md).
- [x] New or existing tests cover these changes.
- [x] The documentation is up to date with these changes.

### CODE REVIEW

**Comment by bdice** [comment]
@ajschmidt8 I think the absolute paths must be interpreted correctly by CodeCov. In commit 002fba0, I changed the test paths but forgot to modify the path to `.coveragerc`. Then in commit 689e67e, I fixed that problem and the total coverage is unchanged relative to the base branch. I would like to merge this PR since it makes our path handling more standard across packages and adds a missing `.coveragerc` file for `custreamz`.

**Review by mroeschke — APPROVED** [review]

**Comment by galipremsagar** [comment]
@bdice Should we wait for codecov bot to comment the reports on this PR before merging?

**Comment by bdice** [comment]
> @bdice Should we wait for codecov bot to comment the reports on this PR before merging?

I don't know why the bot hasn't commented yet. I will merge in `branch-23.04` and see if a new commit triggers the bot since I opened this PR from draft.

**Comment by bdice** [comment]
Hard to know what's wrong. @galipremsagar Can you tell? https://app.codecov.io/gh/rapidsai/cudf/pull/12751

**Comment by galipremsagar** [comment]
> Hard to know what's wrong. @galipremsagar Can you tell? https://app.codecov.io/gh/rapidsai/cudf/pull/12751

The error shown in that page that base branch is missing is related to our nightly jobs not running probably.

But the bot should have commented even if above is the case, lets wait and see if the bot comments in a bit.

**Comment by ajschmidt8** [comment]
> The error shown in that page that base branch is missing is related to our nightly jobs not running probably.

For reference, we generally don't enable nightly builds/tests for the next development branch until the release is complete.

So `23.04` nightly builds/tests will begin next week.

**Comment by ajschmidt8** [comment]
I still don't get why in some coverage results (like [this](https://github.com/rapidsai/cudf/actions/runs/4148075004/jobs/7176191144#step:6:1219)), it reports relative paths like:

```
kafka.py 
```

but in that same log ([here](https://github.com/rapidsai/cudf/actions/runs/4148075004/jobs/7176191144#step:6:1416)), it shows other paths absolutely like:

```
/opt/conda/envs/test/lib/python3.10/site-packages/cudf/core/buffer/utils.py
```

**Review by jjacobelli — APPROVED** [review]

**Comment by vyasr** [comment]
@bdice were the above issues with the codecov bot resolved?

**Comment by bdice** [comment]
@vyasr I don't see Codecov bot PR comments on these recent PRs.

- https://github.com/rapidsai/cudf/pull/12871
- https://github.com/rapidsai/cudf/pull/12724

I don't know how to address this, it probably takes repo admin privileges if it's an issue with the application setup or webhooks. cc: @rapidsai/ops

**Pull request merged**
