### PR TITLE
Replace stream.value() with stream for stream_view args

### PR DESCRIPTION
**Pull request by karthikeyann**

### CODE REVIEW

**Review by devavret — APPROVED** [review]

**Review by rgsl888prabhu — APPROVED** [review]
Would need copyright update.

**Comment by karthikeyann** [comment]
> Would need copyright update.

One liner to **update copyright year** in all changed files in PR (needs github cli)
```bash
gh pr diff | grep -F "+++ b/" | sed "s#+++ b/##g"  | xargs -L1 sed -i -E "s/Copyright *\(c\) *([0-9,-]+)*-([0-9]{4}), *NVIDIA *CORPORATION/Copyright (c) \\1-`date +%Y`, NVIDIA CORPORATION/; /`date +%Y`/! s/Copyright *\(c\) ([0-9]{4}), *NVIDIA *CORPORATION/Copyright (c) \\1-`date +%Y`, NVIDIA CORPORATION/" $1
```

**Comment by karthikeyann** [comment]
rerun tests

**Comment by kkraus14** [comment]
@gpucibot merge

**Pull request merged**
